SELECT COALESCE(ANY_VALUE("Id"), ANY_VALUE("Id")) AS "POSTID", "Title" AS "TITLE", ANY_VALUE("CreationDate") AS "POSTCREATIONDATE", "ViewCount" AS "VIEWCOUNT", "Score" AS "SCORE", ANY_VALUE("Id0") AS "USERID", ANY_VALUE("DisplayName") AS "USERDISPLAYNAME", ANY_VALUE("Reputation") AS "USERREPUTATION", COUNT("Id1") AS "VOTECOUNT", SUM(CASE WHEN CAST("VoteTypeId" AS INTEGER) = 2 THEN 1 ELSE 0 END) AS "UPVOTES", SUM(CASE WHEN CAST("VoteTypeId" AS INTEGER) = 3 THEN 1 ELSE 0 END) AS "DOWNVOTES", COUNT("Id2") AS "COMMENTCOUNT", COUNT("Id3") AS "BADGECOUNT"
FROM "s1"
WHERE "CreationDate" >= '2020-01-01'
GROUP BY "Id", "Title", "CreationDate", "ViewCount", "Score", "Id0", "DisplayName", "Reputation"
ORDER BY "Score" DESC NULLS FIRST, "ViewCount" DESC NULLS FIRST