SELECT COALESCE("USERID", "USERID") AS "USERID", "DISPLAYNAME", "POSTSCOUNT", "QUESTIONSCOUNT", "ANSWERSCOUNT", "COMMENTSCOUNT", "BADGESCOUNT", "TOTALBOUNTYAMOUNT"
FROM (SELECT ANY_VALUE("Id") AS "USERID", "DISPLAYNAME", COUNT(DISTINCT "Id0") AS "POSTSCOUNT", SUM("FD_COL_3") AS "QUESTIONSCOUNT", SUM("FD_COL_4") AS "ANSWERSCOUNT", COUNT(DISTINCT "Id1") AS "COMMENTSCOUNT", COUNT(DISTINCT "Id2") AS "BADGESCOUNT", SUM("BountyAmount") AS "TOTALBOUNTYAMOUNT"
FROM "s1"
GROUP BY "Id", "DISPLAYNAME"
ORDER BY 3 DESC NULLS FIRST
FETCH NEXT 100 ROWS ONLY) AS "t3"