SELECT COALESCE("t1"."POSTID", "t1"."POSTID") AS "POSTID", "t1"."POSTTYPEID", "t1"."COMMENTCOUNT", "t1"."VOTECOUNT", "t1"."LASTACTIVITYDATE", "t1"."UPVOTES", "t1"."DOWNVOTES", "t4"."USERID", "t4"."BADGECOUNT", "t4"."TOTALREPUTATION", "t4"."POSTCOUNT"
FROM (SELECT ANY_VALUE("Posts"."Id") AS "POSTID", "Posts"."PostTypeId" AS "POSTTYPEID", COUNT("Comments"."Id") AS "COMMENTCOUNT", COUNT("Votes"."Id") AS "VOTECOUNT", MAX("Posts"."CreationDate") AS "LASTACTIVITYDATE", SUM(CASE WHEN CAST("Votes"."VoteTypeId" AS INTEGER) = 2 THEN 1 ELSE 0 END) AS "UPVOTES", SUM(CASE WHEN CAST("Votes"."VoteTypeId" AS INTEGER) = 3 THEN 1 ELSE 0 END) AS "DOWNVOTES", CAST("Posts"."PostTypeId" AS INTEGER) AS "POSTTYPEID0"
FROM "STACK"."Posts"
LEFT JOIN "STACK"."Comments" ON "Posts"."Id" = "Comments"."PostId"
LEFT JOIN "STACK"."Votes" ON "Posts"."Id" = "Votes"."PostId"
GROUP BY "Posts"."Id", "Posts"."PostTypeId") AS "t1"
INNER JOIN (SELECT ANY_VALUE("Users"."Id") AS "USERID", COUNT("Badges"."Id") AS "BADGECOUNT", SUM("Users"."Reputation") AS "TOTALREPUTATION", COUNT(DISTINCT "Posts0"."Id") AS "POSTCOUNT"
FROM "STACK"."Users"
LEFT JOIN "STACK"."Badges" ON "Users"."Id" = "Badges"."UserId"
LEFT JOIN "STACK"."Posts" AS "Posts0" ON "Users"."Id" = "Posts0"."OwnerUserId"
GROUP BY "Users"."Id") AS "t4" ON "t1"."POSTTYPEID0" = "t4"."USERID"