SELECT COALESCE("t2"."POSTID", "t2"."POSTID") AS "POSTID", "t2"."POSTTYPEID", "t2"."COMMENTCOUNT", "t2"."VOTECOUNT", "t5"."POSTCOUNT" AS "USERPOSTCOUNT", "t5"."TOTALUPVOTES", "t5"."TOTALDOWNVOTES"
FROM (SELECT "t1"."POSTID", "t1"."POSTTYPEID", "t1"."COMMENTCOUNT", "t1"."VOTECOUNT", "t1"."BADGECOUNT", "Users"."Id", "Users"."Reputation", "Users"."CreationDate", "Users"."DisplayName", "Users"."LastAccessDate", "Users"."WebsiteUrl", "Users"."Location", "Users"."AboutMe", "Users"."Views", "Users"."UpVotes", "Users"."DownVotes", "Users"."ProfileImageUrl", "Users"."AccountId"
FROM (SELECT ANY_VALUE("Posts"."Id") AS "POSTID", "Posts"."PostTypeId" AS "POSTTYPEID", COUNT(DISTINCT "Comments"."Id") AS "COMMENTCOUNT", COUNT(DISTINCT "Votes"."Id") AS "VOTECOUNT", COUNT(DISTINCT "Badges"."Id") AS "BADGECOUNT", CAST("Posts"."PostTypeId" AS INTEGER) AS "POSTTYPEID0"
FROM "STACK"."Posts"
LEFT JOIN "STACK"."Comments" ON "Posts"."Id" = "Comments"."PostId"
LEFT JOIN "STACK"."Votes" ON "Posts"."Id" = "Votes"."PostId"
LEFT JOIN "STACK"."Badges" ON "Posts"."OwnerUserId" = "Badges"."UserId"
GROUP BY "Posts"."Id", "Posts"."PostTypeId") AS "t1"
INNER JOIN "STACK"."Users" ON "t1"."POSTTYPEID0" = "Users"."Id") AS "t2"
INNER JOIN (SELECT ANY_VALUE("Users0"."Id") AS "USERID", COUNT(DISTINCT "Posts0"."Id") AS "POSTCOUNT", SUM("Users0"."UpVotes") AS "TOTALUPVOTES", SUM("Users0"."DownVotes") AS "TOTALDOWNVOTES"
FROM "STACK"."Users" AS "Users0"
LEFT JOIN "STACK"."Posts" AS "Posts0" ON "Users0"."Id" = "Posts0"."OwnerUserId"
GROUP BY "Users0"."Id") AS "t5" ON "t2"."Id" = "t5"."USERID"