SELECT COALESCE(ANY_VALUE("PostTypes"."Name"), ANY_VALUE("PostTypes"."Name")) AS "POSTTYPE", COUNT(*) AS "TOTALPOSTS", SUM("Posts"."Score") AS "TOTALSCORE", AVG("t0"."VOTECOUNT") AS "AVERAGEVOTES", AVG("t2"."COMMENTCOUNT") AS "AVERAGECOMMENTS", MAX("Posts"."CreationDate") AS "LATESTPOSTDATE", MIN("Posts"."CreationDate") AS "EARLIESTPOSTDATE"
FROM "STACK"."Posts"
INNER JOIN "STACK"."PostTypes" ON "Posts"."PostTypeId" = "PostTypes"."Id"
LEFT JOIN (SELECT "PostId" AS "POSTID", COUNT(*) AS "VOTECOUNT"
FROM "STACK"."Votes"
GROUP BY "PostId") AS "t0" ON "Posts"."Id" = "t0"."POSTID"
LEFT JOIN (SELECT "PostId" AS "POSTID", COUNT(*) AS "COMMENTCOUNT"
FROM "STACK"."Comments"
GROUP BY "PostId") AS "t2" ON "Posts"."Id" = "t2"."POSTID"
GROUP BY "PostTypes"."Name"