SELECT COALESCE("POSTTYPE", "POSTTYPE") AS "POSTTYPE", "TOTALPOSTS", "TOTALSCORE", "AVERAGEVOTES", "AVERAGECOMMENTS", "LATESTPOSTDATE", "EARLIESTPOSTDATE"
FROM "s1"
ORDER BY "TOTALPOSTS" DESC NULLS FIRST