SELECT COALESCE("POSTID", "POSTID") AS "POSTID", "TITLE", "CREATIONDATE", "SCORE", "VIEWCOUNT", "OWNERDISPLAYNAME", "OWNERREPUTATION", "POSTTYPE", "COMMENTCOUNT", "VOTECOUNT"
FROM "s1"
ORDER BY "CREATIONDATE" DESC NULLS FIRST
FETCH NEXT 100 ROWS ONLY