SELECT COALESCE("USERID", "USERID") AS "USERID", "USERNAME", "REPUTATION", "TOTALPOSTS", "TOTALQUESTIONS", "TOTALANSWERS", "TOTALSCORE", "TOTALVIEWS", "AVERAGESCORE", "AVERAGEVIEWS"
FROM (SELECT ANY_VALUE("Id") AS "USERID", ANY_VALUE("DisplayName") AS "USERNAME", "REPUTATION", COUNT("Id0") AS "TOTALPOSTS", COUNT("FD_COL_4") AS "TOTALQUESTIONS", COUNT("FD_COL_5") AS "TOTALANSWERS", SUM("FD_COL_6") AS "TOTALSCORE", SUM("FD_COL_7") AS "TOTALVIEWS", AVG("FD_COL_6") AS "AVERAGESCORE", AVG("FD_COL_7") AS "AVERAGEVIEWS"
FROM "s1"
GROUP BY "Id", "DisplayName", "REPUTATION"
ORDER BY 4 DESC NULLS FIRST
FETCH NEXT 100 ROWS ONLY) AS "t3"