SELECT COALESCE("POSTTYPE", "POSTTYPE") AS "POSTTYPE", "TOTALPOSTS", "TOTALVIEWS", "AVERAGESCORE", "UNIQUEUSERS", "TOTALQUESTIONS", "TOTALANSWERS", "TOTALTAGWIKIS", "TOTALCLOSEDPOSTS", "AVERAGEUSERREPUTATION"
FROM (SELECT ANY_VALUE("Name") AS "POSTTYPE", COUNT(*) AS "TOTALPOSTS", SUM("ViewCount") AS "TOTALVIEWS", AVG("Score") AS "AVERAGESCORE", COUNT(DISTINCT "OwnerUserId") AS "UNIQUEUSERS", SUM(CASE WHEN CAST("PostTypeId" AS INTEGER) = 1 THEN 1 ELSE 0 END) AS "TOTALQUESTIONS", SUM(CASE WHEN CAST("PostTypeId" AS INTEGER) = 2 THEN 1 ELSE 0 END) AS "TOTALANSWERS", SUM(CASE WHEN CAST("PostTypeId" AS INTEGER) = 4 THEN 1 ELSE 0 END) AS "TOTALTAGWIKIS", SUM(CASE WHEN CAST("PostTypeId" AS INTEGER) = 10 THEN 1 ELSE 0 END) AS "TOTALCLOSEDPOSTS", AVG("Reputation") AS "AVERAGEUSERREPUTATION"
FROM "s1"
WHERE "CreationDate" >= (CAST('2024-10-01 12:34:56' AS TIMESTAMP(0)) - INTERVAL '1' YEAR)
GROUP BY "Name"
ORDER BY 2 DESC NULLS FIRST) AS "t4"