SELECT COALESCE("POSTTYPE", "POSTTYPE") AS "POSTTYPE", "TOTALPOSTS", "TOTALVIEWS", "TOTALSCORE", "AVERAGEANSWERS", "AVERAGECOMMENTS", "AVERAGEFAVORITES", "USERREPUTATION", "ACTIVEUSERS"
FROM (SELECT ANY_VALUE("Name") AS "POSTTYPE", COUNT(*) AS "TOTALPOSTS", SUM("ViewCount") AS "TOTALVIEWS", SUM("Score") AS "TOTALSCORE", AVG("AnswerCount") AS "AVERAGEANSWERS", AVG("CommentCount") AS "AVERAGECOMMENTS", AVG("FavoriteCount") AS "AVERAGEFAVORITES", ANY_VALUE("Reputation") AS "USERREPUTATION", COUNT(DISTINCT "Id1") AS "ACTIVEUSERS"
FROM "s1"
WHERE "CreationDate" >= (CAST('2024-10-01 12:34:56' AS TIMESTAMP(0)) - INTERVAL '1' YEAR)
GROUP BY "Name", "Reputation"
ORDER BY 2 DESC NULLS FIRST) AS "t4"