SELECT COALESCE("t1"."POSTTYPE", "t1"."POSTTYPE") AS "POSTTYPE", "t1"."TOTALPOSTS", "t1"."AVERAGESCORE", "t1"."UNIQUEUSERS", "t1"."TOTALVIEWS", "t1"."TOTALCOMMENTS", "t1"."TOTALANSWERS", "t4"."USERID", "t4"."DISPLAYNAME", "t4"."POSTSCREATED", "t4"."TOTALBOUNTYRECEIVED"
FROM (SELECT ANY_VALUE("PostTypes"."Name") AS "POSTTYPE", COUNT(*) AS "TOTALPOSTS", AVG("Posts"."Score") AS "AVERAGESCORE", COUNT(DISTINCT "Posts"."OwnerUserId") AS "UNIQUEUSERS", SUM("Posts"."ViewCount") AS "TOTALVIEWS", SUM("Posts"."CommentCount") AS "TOTALCOMMENTS", SUM("Posts"."AnswerCount") AS "TOTALANSWERS"
FROM "STACK"."Posts"
INNER JOIN "STACK"."PostTypes" ON "Posts"."PostTypeId" = "PostTypes"."Id"
GROUP BY "PostTypes"."Name") AS "t1"
INNER JOIN (SELECT ANY_VALUE("Users"."Id") AS "USERID", "Users"."DisplayName" AS "DISPLAYNAME", COUNT("Posts0"."Id") AS "POSTSCREATED", SUM("Votes"."BountyAmount") AS "TOTALBOUNTYRECEIVED"
FROM "STACK"."Users"
LEFT JOIN "STACK"."Posts" AS "Posts0" ON "Users"."Id" = "Posts0"."OwnerUserId"
LEFT JOIN "STACK"."Votes" ON "Users"."Id" = "Votes"."UserId"
GROUP BY "Users"."Id", "Users"."DisplayName") AS "t4" ON "t1"."UNIQUEUSERS" = "t4"."POSTSCREATED"