SELECT COALESCE("t2"."POSTID", "t2"."POSTID") AS "POSTID", "t2"."TITLE", "t2"."CREATIONDATE", "t2"."SCORE", "t2"."VIEWCOUNT", "t2"."ANSWERCOUNT", "t2"."COMMENTCOUNT", "t2"."VOTECOUNT", "t2"."OWNERUSERID", "t2"."OWNERREPUTATION", "t2"."USERCREATIONDATE", "t2"."OWNERDISPLAYNAME", "t5"."USERID", "t5"."DISPLAYNAME" AS "USERDISPLAYNAME", "t5"."BADGECOUNT", "t5"."UPVOTES", "t5"."DOWNVOTES", "t5"."TOTALBOUNTY"
FROM (SELECT ANY_VALUE("Id") AS "POSTID", "TITLE", "CREATIONDATE", "SCORE", "VIEWCOUNT", "ANSWERCOUNT", COUNT("Id0") AS "COMMENTCOUNT", COUNT("Id1") AS "VOTECOUNT", ANY_VALUE("Id2") AS "OWNERUSERID", ANY_VALUE("Reputation") AS "OWNERREPUTATION", ANY_VALUE("CreationDate2") AS "USERCREATIONDATE", ANY_VALUE("DisplayName") AS "OWNERDISPLAYNAME"
FROM "s1"
GROUP BY "Id", "TITLE", "CREATIONDATE", "SCORE", "VIEWCOUNT", "ANSWERCOUNT", "Id2", "Reputation", "CreationDate2", "DisplayName") AS "t2"
INNER JOIN (SELECT ANY_VALUE("Users0"."Id") AS "USERID", "Users0"."DisplayName" AS "DISPLAYNAME", COUNT("Badges"."Id") AS "BADGECOUNT", SUM(CASE WHEN CAST("Votes0"."VoteTypeId" AS INTEGER) = 2 THEN 1 ELSE 0 END) AS "UPVOTES", SUM(CASE WHEN CAST("Votes0"."VoteTypeId" AS INTEGER) = 3 THEN 1 ELSE 0 END) AS "DOWNVOTES", SUM("Votes0"."BountyAmount") AS "TOTALBOUNTY"
FROM "STACK"."Users" AS "Users0"
LEFT JOIN "STACK"."Badges" ON "Users0"."Id" = "Badges"."UserId"
LEFT JOIN "STACK"."Votes" AS "Votes0" ON "Users0"."Id" = "Votes0"."UserId"
GROUP BY "Users0"."Id", "Users0"."DisplayName") AS "t5" ON "t2"."OWNERUSERID" = "t5"."USERID"
ORDER BY "t2"."CREATIONDATE" DESC NULLS FIRST
FETCH NEXT 100 ROWS ONLY