SELECT COALESCE("Posts"."Id", "Posts"."Id") AS "Id", "Posts"."Title" AS "TITLE", "Posts"."CreationDate" AS "CREATIONDATE", "Posts"."Score" AS "SCORE", "Posts"."ViewCount" AS "VIEWCOUNT", "Posts"."AnswerCount" AS "ANSWERCOUNT", "Users"."Id" AS "Id2", "Users"."Reputation", "Users"."CreationDate" AS "CreationDate2", "Users"."DisplayName", "Comments"."Id" AS "Id0", "Votes"."Id" AS "Id1"
FROM "STACK"."Posts"
LEFT JOIN "STACK"."Comments" ON "Posts"."Id" = "Comments"."PostId"
LEFT JOIN "STACK"."Votes" ON "Posts"."Id" = "Votes"."PostId"
LEFT JOIN "STACK"."Users" ON "Posts"."OwnerUserId" = "Users"."Id"