SELECT COALESCE("POSTID", "POSTID") AS "POSTID", "TITLE", "OWNERDISPLAYNAME", "CREATIONDATE", "VIEWCOUNT", "SCORE", "COMMENTCOUNT", "VOTECOUNT", "TAGNAME", "POSTTYPE", "LASTEDITEDBY", "LASTEDITEDDATE"
FROM "s1"
ORDER BY "CREATIONDATE" DESC NULLS FIRST