SELECT COALESCE("Posts"."Id", "Posts"."Id") AS "POSTID", "Posts"."Title" AS "TITLE", "Posts"."CreationDate" AS "CREATIONDATE", "Posts"."ViewCount" AS "VIEWCOUNT", "Posts"."Score" AS "SCORE", CASE WHEN "t1"."UPVOTECOUNT" IS NOT NULL THEN CAST("t1"."UPVOTECOUNT" AS BIGINT) ELSE 0 END AS "UPVOTECOUNT", CASE WHEN "t4"."DOWNVOTECOUNT" IS NOT NULL THEN CAST("t4"."DOWNVOTECOUNT" AS BIGINT) ELSE 0 END AS "DOWNVOTECOUNT", CASE WHEN "t6"."COMMENTCOUNT" IS NOT NULL THEN CAST("t6"."COMMENTCOUNT" AS BIGINT) ELSE 0 END AS "COMMENTCOUNT", CASE WHEN "t8"."BADGECOUNT" IS NOT NULL THEN CAST("t8"."BADGECOUNT" AS BIGINT) ELSE 0 END AS "BADGECOUNT", CASE WHEN "Users"."Reputation" IS NOT NULL THEN CAST("Users"."Reputation" AS INTEGER) ELSE 0 END AS "USERREPUTATION"
FROM "STACK"."Posts"
LEFT JOIN (SELECT "PostId" AS "POSTID", COUNT(*) AS "UPVOTECOUNT"
FROM "STACK"."Votes"
WHERE CAST("VoteTypeId" AS INTEGER) = 2
GROUP BY "PostId") AS "t1" ON "Posts"."Id" = "t1"."POSTID"
LEFT JOIN (SELECT "PostId" AS "POSTID", COUNT(*) AS "DOWNVOTECOUNT"
FROM "STACK"."Votes"
WHERE CAST("VoteTypeId" AS INTEGER) = 3
GROUP BY "PostId") AS "t4" ON "Posts"."Id" = "t4"."POSTID"
LEFT JOIN (SELECT "PostId" AS "POSTID", COUNT(*) AS "COMMENTCOUNT"
FROM "STACK"."Comments"
GROUP BY "PostId") AS "t6" ON "Posts"."Id" = "t6"."POSTID"
LEFT JOIN (SELECT "UserId" AS "USERID", COUNT(*) AS "BADGECOUNT"
FROM "STACK"."Badges"
GROUP BY "UserId") AS "t8" ON "Posts"."OwnerUserId" = "t8"."USERID"
LEFT JOIN "STACK"."Users" ON "Posts"."OwnerUserId" = "Users"."Id"
WHERE "Posts"."CreationDate" >= (CAST('2024-10-01 12:34:56' AS TIMESTAMP(0)) - INTERVAL '1' YEAR)