SELECT COALESCE("POSTID", "POSTID") AS "POSTID", "TITLE", "CREATIONDATE", "VIEWCOUNT", "SCORE", "UPVOTECOUNT", "DOWNVOTECOUNT", "COMMENTCOUNT", "BADGECOUNT", "USERREPUTATION"
FROM "s1"
ORDER BY "CREATIONDATE" DESC NULLS FIRST
FETCH NEXT 100 ROWS ONLY