SELECT COALESCE("t1"."POSTTYPE", "t1"."POSTTYPE") AS "POSTTYPE", "t1"."POSTCOUNT", "t1"."AVERAGESCORE", "t3"."UNIQUEUSERSWITHBADGES"
FROM (SELECT ANY_VALUE("PostTypes"."Name") AS "POSTTYPE", COUNT(*) AS "POSTCOUNT", AVG("Posts"."Score") AS "AVERAGESCORE"
FROM "STACK"."Posts"
INNER JOIN "STACK"."PostTypes" ON "Posts"."PostTypeId" = "PostTypes"."Id"
GROUP BY "PostTypes"."Name") AS "t1",
(SELECT COUNT(DISTINCT "UserId") AS "UNIQUEUSERSWITHBADGES"
FROM "STACK"."Badges") AS "t3"