SELECT COALESCE("t1"."POSTTYPE", "t1"."POSTTYPE") AS "POSTTYPE", "t1"."TOTALPOSTS", "t1"."TOTALQUESTIONS", "t1"."TOTALANSWERS", "t1"."TOTALVIEWS", "t1"."AVGSCORE", "t1"."AVGANSWERSPERQUESTION", "t3"."TOTALUSERS", "t3"."TOTALREPUTATION", "t3"."AVGREPUTATION", "t3"."ACTIVEUSERS", "t3"."RECENTUSERS", "t5"."TOTALCOMMENTS", "t5"."AVGCOMMENTLENGTH", "t5"."POSITIVECOMMENTS"
FROM (SELECT ANY_VALUE("PostTypes"."Name") AS "POSTTYPE", COUNT(*) AS "TOTALPOSTS", SUM(CASE WHEN CAST("Posts"."PostTypeId" AS INTEGER) = 1 THEN 1 ELSE 0 END) AS "TOTALQUESTIONS", SUM(CASE WHEN CAST("Posts"."PostTypeId" AS INTEGER) = 2 THEN 1 ELSE 0 END) AS "TOTALANSWERS", SUM("Posts"."ViewCount") AS "TOTALVIEWS", AVG("Posts"."Score") AS "AVGSCORE", AVG("Posts"."AnswerCount") AS "AVGANSWERSPERQUESTION"
FROM "STACK"."Posts"
INNER JOIN "STACK"."PostTypes" ON "Posts"."PostTypeId" = "PostTypes"."Id"
GROUP BY "PostTypes"."Name") AS "t1",
(SELECT COUNT(*) AS "TOTALUSERS", SUM("Reputation") AS "TOTALREPUTATION", AVG("Reputation") AS "AVGREPUTATION", COUNT(DISTINCT CASE WHEN "UpVotes" > 0 THEN "Id" ELSE NULL END) AS "ACTIVEUSERS", SUM(CASE WHEN "LastAccessDate" > CAST((DATE '2024-10-01' - INTERVAL '30' DAY) AS TIMESTAMP(0)) THEN 1 ELSE 0 END) AS "RECENTUSERS"
FROM "STACK"."Users") AS "t3",
(SELECT COUNT(*) AS "TOTALCOMMENTS", AVG(LENGTH("Text")) AS "AVGCOMMENTLENGTH", SUM(CASE WHEN "Score" > 0 THEN 1 ELSE 0 END) AS "POSITIVECOMMENTS"
FROM "STACK"."Comments") AS "t5"