SELECT COALESCE("POSTTYPE", "POSTTYPE") AS "POSTTYPE", "TOTALPOSTS", "TOTALQUESTIONS", "TOTALANSWERS", "TOTALVIEWS", "AVGSCORE", "AVGANSWERSPERQUESTION", "TOTALUSERS", "TOTALREPUTATION", "AVGREPUTATION", "ACTIVEUSERS", "RECENTUSERS", "TOTALCOMMENTS", "AVGCOMMENTLENGTH", "POSITIVECOMMENTS"
FROM "s1"
ORDER BY "TOTALPOSTS" DESC NULLS FIRST