SELECT COALESCE("POSTID", "POSTID") AS "POSTID", "TITLE", "CREATIONDATE", "VIEWCOUNT", "POSTTYPE", "OWNERDISPLAYNAME", "UPVOTESCOUNT", "DOWNVOTESCOUNT", "BADGECOUNT"
FROM "s1"
ORDER BY "CREATIONDATE" DESC NULLS FIRST
FETCH NEXT 100 ROWS ONLY