SELECT COALESCE("t3"."POSTID", "t3"."POSTID") AS "POSTID", "t3"."TITLE", "t3"."CREATIONDATE", "t3"."VIEWCOUNT", "t3"."SCORE", "t3"."COMMENTCOUNT", "t3"."VOTECOUNT", "t7"."USERID", "t7"."DISPLAYNAME", "t7"."POSTSCOUNT", "t7"."TOTALUPVOTES", "t7"."TOTALDOWNVOTES", "t7"."TOTALVIEWS"
FROM (SELECT ANY_VALUE("Id") AS "POSTID", "Title" AS "TITLE", "CreationDate" AS "CREATIONDATE", "ViewCount" AS "VIEWCOUNT", "Score" AS "SCORE", COUNT("Id0") AS "COMMENTCOUNT", COUNT(DISTINCT "Id1") AS "VOTECOUNT", COUNT(DISTINCT "Id2") AS "BADGECOUNT"
FROM "s1"
WHERE "CreationDate" >= (TIMESTAMP '2024-10-01 12:34:56' - INTERVAL '1' YEAR)
GROUP BY "Id", "Title", "CreationDate", "ViewCount", "Score") AS "t3"
INNER JOIN (SELECT ANY_VALUE("Users"."Id") AS "USERID", "Users"."DisplayName" AS "DISPLAYNAME", COUNT(DISTINCT "Posts0"."Id") AS "POSTSCOUNT", SUM("Users"."UpVotes") AS "TOTALUPVOTES", SUM("Users"."DownVotes") AS "TOTALDOWNVOTES", SUM("Users"."Views") AS "TOTALVIEWS"
FROM "STACK"."Users"
LEFT JOIN "STACK"."Posts" AS "Posts0" ON "Users"."Id" = "Posts0"."OwnerUserId"
WHERE "Users"."CreationDate" >= (TIMESTAMP '2024-10-01 12:34:56' - INTERVAL '1' YEAR)
GROUP BY "Users"."Id", "Users"."DisplayName") AS "t7" ON "t3"."POSTID" = "t7"."USERID"
ORDER BY "t3"."VIEWCOUNT" DESC NULLS FIRST, "t3"."SCORE" DESC NULLS FIRST
FETCH NEXT 100 ROWS ONLY