SELECT COALESCE("t1"."USERID", "t1"."USERID") AS "USERID", "t1"."DISPLAYNAME", "t1"."TOTALPOSTS", "t1"."TOTALQUESTIONS", "t1"."TOTALANSWERS", "t1"."TOTALSCORE", "t1"."TOTALVIEWS", "t4"."POSTID", "t4"."TITLE", "t4"."CREATIONDATE", "t4"."SCORE", "t4"."VIEWCOUNT", "t4"."COMMENTCOUNT", "t4"."UPVOTES" AS "POSTUPVOTES", "t4"."DOWNVOTES" AS "POSTDOWNVOTES"
FROM (SELECT ANY_VALUE("Users"."Id") AS "USERID", "Users"."DisplayName" AS "DISPLAYNAME", COUNT(DISTINCT "Posts"."Id") AS "TOTALPOSTS", COUNT(DISTINCT "Comments"."Id") AS "TOTALCOMMENTS", SUM(CASE WHEN CAST("Posts"."PostTypeId" AS INTEGER) = 1 THEN 1 ELSE 0 END) AS "TOTALQUESTIONS", SUM(CASE WHEN CAST("Posts"."PostTypeId" AS INTEGER) = 2 THEN 1 ELSE 0 END) AS "TOTALANSWERS", SUM("Posts"."Score") AS "TOTALSCORE", SUM("Posts"."ViewCount") AS "TOTALVIEWS", SUM(CASE WHEN CAST("Votes"."VoteTypeId" AS INTEGER) = 2 THEN 1 ELSE 0 END) AS "UPVOTES", SUM(CASE WHEN CAST("Votes"."VoteTypeId" AS INTEGER) = 3 THEN 1 ELSE 0 END) AS "DOWNVOTES"
FROM "STACK"."Users"
LEFT JOIN "STACK"."Posts" ON "Users"."Id" = "Posts"."OwnerUserId"
LEFT JOIN "STACK"."Comments" ON "Posts"."Id" = "Comments"."PostId"
LEFT JOIN "STACK"."Votes" ON "Posts"."Id" = "Votes"."PostId"
GROUP BY "Users"."Id", "Users"."DisplayName") AS "t1"
INNER JOIN (SELECT ANY_VALUE("Posts0"."Id") AS "POSTID", "Posts0"."Title" AS "TITLE", "Posts0"."CreationDate" AS "CREATIONDATE", "Posts0"."Score" AS "SCORE", "Posts0"."ViewCount" AS "VIEWCOUNT", COUNT(DISTINCT "Comments0"."Id") AS "COMMENTCOUNT", SUM(CASE WHEN CAST("Votes0"."VoteTypeId" AS INTEGER) = 2 THEN 1 ELSE 0 END) AS "UPVOTES", SUM(CASE WHEN CAST("Votes0"."VoteTypeId" AS INTEGER) = 3 THEN 1 ELSE 0 END) AS "DOWNVOTES"
FROM "STACK"."Posts" AS "Posts0"
LEFT JOIN "STACK"."Comments" AS "Comments0" ON "Posts0"."Id" = "Comments0"."PostId"
LEFT JOIN "STACK"."Votes" AS "Votes0" ON "Posts0"."Id" = "Votes0"."PostId"
GROUP BY "Posts0"."Id", "Posts0"."Title", "Posts0"."CreationDate", "Posts0"."Score", "Posts0"."ViewCount") AS "t4" ON "t1"."USERID" = "t4"."POSTID"