SELECT COALESCE("USERID", "USERID") AS "USERID", "REPUTATION", "DISPLAYNAME", "POSTCOUNT", "QUESTIONCOUNT", "ANSWERCOUNT", "TOTALCOMMENTS", "TOTALVOTES"
FROM "s1"
ORDER BY "REPUTATION" DESC NULLS FIRST