SELECT COALESCE("POSTID", "POSTID") AS "POSTID", "TITLE", "POSTCREATIONDATE", "SCORE", "VIEWCOUNT", "ACCEPTEDANSWERCOUNT", "COMMENTCOUNT", "VOTECOUNT", "USERREPUTATION", "USERLOCATION", "USERCREATIONDATE"
FROM "s1"
ORDER BY "POSTCREATIONDATE" DESC NULLS FIRST
FETCH NEXT 100 ROWS ONLY