SELECT COALESCE(ANY_VALUE("Title"), ANY_VALUE("Title")) AS "POSTTITLE", ANY_VALUE("CreationDate") AS "POSTCREATIONDATE", ANY_VALUE("ViewCount") AS "POSTVIEWS", ANY_VALUE("Score") AS "POSTSCORE", ANY_VALUE("DisplayName") AS "OWNERDISPLAYNAME", COUNT("Id1") AS "COMMENTCOUNT", SUM(CASE WHEN CAST("VoteTypeId" AS INTEGER) = 2 THEN 1 ELSE 0 END) AS "UPVOTECOUNT", SUM(CASE WHEN CAST("VoteTypeId" AS INTEGER) = 3 THEN 1 ELSE 0 END) AS "DOWNVOTECOUNT", AVG(CASE WHEN CAST("PostHistoryTypeId" AS INTEGER) IN (4, 5) THEN 1 ELSE NULL END) AS "AVERAGEEDITS", "CreationDate"
FROM "s1"
WHERE CAST("PostTypeId" AS INTEGER) = 1
GROUP BY "Title", "CreationDate", "ViewCount", "Score", "DisplayName", "Id"
ORDER BY "CreationDate" DESC NULLS FIRST
FETCH NEXT 100 ROWS ONLY