SELECT COALESCE("Posts"."Id", "Posts"."Id") AS "POSTID", "Posts"."Title" AS "TITLE", "Posts"."CreationDate" AS "POSTCREATIONDATE", "Posts"."Score" AS "SCORE", "Posts"."ViewCount" AS "VIEWCOUNT", CASE WHEN "t1"."ACCEPTEDANSWERCOUNT" IS NOT NULL THEN CAST("t1"."ACCEPTEDANSWERCOUNT" AS BIGINT) ELSE 0 END AS "ACCEPTEDANSWERCOUNT", CASE WHEN "t3"."COMMENTCOUNT" IS NOT NULL THEN CAST("t3"."COMMENTCOUNT" AS BIGINT) ELSE 0 END AS "COMMENTCOUNT", CASE WHEN "t5"."VOTECOUNT" IS NOT NULL THEN CAST("t5"."VOTECOUNT" AS BIGINT) ELSE 0 END AS "VOTECOUNT", "Users"."Reputation" AS "USERREPUTATION", "Users"."Location" AS "USERLOCATION", "Users"."CreationDate" AS "USERCREATIONDATE"
FROM "STACK"."Posts"
LEFT JOIN (SELECT "ParentId" AS "PARENTID", COUNT(*) AS "ACCEPTEDANSWERCOUNT"
FROM "STACK"."Posts"
WHERE CAST("PostTypeId" AS INTEGER) = 2
GROUP BY "ParentId") AS "t1" ON "Posts"."Id" = "t1"."PARENTID"
LEFT JOIN (SELECT "PostId" AS "POSTID", COUNT(*) AS "COMMENTCOUNT"
FROM "STACK"."Comments"
GROUP BY "PostId") AS "t3" ON "Posts"."Id" = "t3"."POSTID"
LEFT JOIN (SELECT "PostId" AS "POSTID", COUNT(*) AS "VOTECOUNT"
FROM "STACK"."Votes"
GROUP BY "PostId") AS "t5" ON "Posts"."Id" = "t5"."POSTID"
INNER JOIN "STACK"."Users" ON "Posts"."OwnerUserId" = "Users"."Id"
WHERE "Posts"."CreationDate" >= '2023-01-01'