SELECT COALESCE("POSTTYPE", "POSTTYPE") AS "POSTTYPE", "TOTALPOSTS", "TOTALSCORE", "TOTALVIEWS", "TOTALUPVOTES", "TOTALDOWNVOTES", "AVGSCOREPERPOST", "AVGVIEWSPERPOST"
FROM "s1"
ORDER BY "TOTALPOSTS" DESC NULLS FIRST