SELECT COALESCE("t2"."POSTTYPENAME", "t2"."POSTTYPENAME") AS "POSTTYPENAME", "t2"."POSTCOUNT", "t2"."AVGSCORE", "t2"."USERCOUNT", "t5"."VOTETYPENAME", "t5"."VOTECOUNT"
FROM (SELECT ANY_VALUE("Name") AS "POSTTYPENAME", COUNT(*) AS "POSTCOUNT", AVG("Score") AS "AVGSCORE", COUNT(DISTINCT "UserId") AS "USERCOUNT"
FROM "s1"
GROUP BY "Name") AS "t2",
(SELECT ANY_VALUE("VoteTypes"."Name") AS "VOTETYPENAME", COUNT(*) AS "VOTECOUNT"
FROM "STACK"."Votes" AS "Votes0"
INNER JOIN "STACK"."VoteTypes" ON "Votes0"."VoteTypeId" = "VoteTypes"."Id"
GROUP BY "VoteTypes"."Name") AS "t5"
ORDER BY "t2"."POSTTYPENAME", "t5"."VOTETYPENAME"