SELECT COALESCE("t1"."POSTID", "t1"."POSTID") AS "POSTID", "t1"."TITLE", "t1"."SCORE", "t1"."VIEWCOUNT", "t1"."ANSWERCOUNT", "t1"."COMMENTCOUNT", "t1"."TOTALCOMMENTS", "t1"."TOTALVOTES", "t4"."USERID", "t4"."DISPLAYNAME", "t4"."TOTALPOSTS", "t4"."TOTALSCORE", "t4"."TOTALCOMMENTS" AS "USERTOTALCOMMENTS", "t4"."TOTALVOTES" AS "USERTOTALVOTES"
FROM (SELECT ANY_VALUE("Posts"."Id") AS "POSTID", "Posts"."Title" AS "TITLE", "Posts"."Score" AS "SCORE", "Posts"."ViewCount" AS "VIEWCOUNT", "Posts"."AnswerCount" AS "ANSWERCOUNT", "Posts"."CommentCount" AS "COMMENTCOUNT", "Posts"."CreationDate" AS "CREATIONDATE", COUNT("Comments"."Id") AS "TOTALCOMMENTS", COUNT("Votes"."Id") AS "TOTALVOTES", CAST(ANY_VALUE("Posts"."Id") AS BIGINT) AS "POSTID0"
FROM "STACK"."Posts"
LEFT JOIN "STACK"."Comments" ON "Posts"."Id" = "Comments"."PostId"
LEFT JOIN "STACK"."Votes" ON "Posts"."Id" = "Votes"."PostId"
GROUP BY "Posts"."Id", "Posts"."Title", "Posts"."Score", "Posts"."ViewCount", "Posts"."AnswerCount", "Posts"."CommentCount", "Posts"."CreationDate") AS "t1"
INNER JOIN (SELECT ANY_VALUE("Users"."Id") AS "USERID", "Users"."DisplayName" AS "DISPLAYNAME", COUNT("Posts0"."Id") AS "TOTALPOSTS", SUM(CASE WHEN "Posts0"."Score" IS NOT NULL THEN CAST("Posts0"."Score" AS INTEGER) ELSE 0 END) AS "TOTALSCORE", SUM(CASE WHEN "Comments0"."Id" IS NOT NULL THEN CAST("Comments0"."Id" AS INTEGER) ELSE 0 END) AS "TOTALCOMMENTS", SUM(CASE WHEN "Votes0"."Id" IS NOT NULL THEN CAST("Votes0"."Id" AS INTEGER) ELSE 0 END) AS "TOTALVOTES"
FROM "STACK"."Users"
LEFT JOIN "STACK"."Posts" AS "Posts0" ON "Users"."Id" = "Posts0"."OwnerUserId"
LEFT JOIN "STACK"."Comments" AS "Comments0" ON "Posts0"."Id" = "Comments0"."PostId"
LEFT JOIN "STACK"."Votes" AS "Votes0" ON "Posts0"."Id" = "Votes0"."PostId"
GROUP BY "Users"."Id", "Users"."DisplayName") AS "t4" ON "t1"."POSTID0" = "t4"."TOTALPOSTS"