SELECT COALESCE("POSTID", "POSTID") AS "POSTID", "TITLE", "SCORE", "VIEWCOUNT", "ANSWERCOUNT", "COMMENTCOUNT", "TOTALCOMMENTS", "TOTALVOTES", "USERID", "DISPLAYNAME", "TOTALPOSTS", "TOTALSCORE", "USERTOTALCOMMENTS", "USERTOTALVOTES"
FROM "s1"
ORDER BY "SCORE" DESC NULLS FIRST, "VIEWCOUNT" DESC NULLS FIRST