SELECT COALESCE("t1"."USERID", "t1"."USERID") AS "USERID", "t1"."DISPLAYNAME", "t1"."POSTCOUNT", "t1"."TOTALSCORE", "t1"."TOTALVIEWS", "t1"."QUESTIONCOUNT", "t1"."ANSWERCOUNT", "t3"."EDITCOUNT", "t3"."BODYEDITS", "t3"."TITLEEDITS"
FROM (SELECT ANY_VALUE("Users"."Id") AS "USERID", "Users"."DisplayName" AS "DISPLAYNAME", COUNT("Posts"."Id") AS "POSTCOUNT", SUM(CASE WHEN "Posts"."Score" IS NOT NULL THEN CAST("Posts"."Score" AS INTEGER) ELSE 0 END) AS "TOTALSCORE", SUM(CASE WHEN "Posts"."ViewCount" IS NOT NULL THEN CAST("Posts"."ViewCount" AS INTEGER) ELSE 0 END) AS "TOTALVIEWS", SUM(CASE WHEN CAST("Posts"."PostTypeId" AS INTEGER) = 1 THEN 1 ELSE 0 END) AS "QUESTIONCOUNT", SUM(CASE WHEN CAST("Posts"."PostTypeId" AS INTEGER) = 2 THEN 1 ELSE 0 END) AS "ANSWERCOUNT"
FROM "STACK"."Users"
LEFT JOIN "STACK"."Posts" ON "Users"."Id" = "Posts"."OwnerUserId"
GROUP BY "Users"."Id", "Users"."DisplayName") AS "t1"
LEFT JOIN (SELECT "PostHistory"."PostId" AS "POSTID", COUNT(*) AS "EDITCOUNT", SUM(CASE WHEN "PostHistoryTypes"."Name" = 'Edit Body' THEN 1 ELSE 0 END) AS "BODYEDITS", SUM(CASE WHEN "PostHistoryTypes"."Name" = 'Edit Title' THEN 1 ELSE 0 END) AS "TITLEEDITS"
FROM "STACK"."PostHistory"
INNER JOIN "STACK"."PostHistoryTypes" ON "PostHistory"."PostHistoryTypeId" = "PostHistoryTypes"."Id"
GROUP BY "PostHistory"."PostId") AS "t3" ON "t1"."USERID" = "t3"."POSTID"