SELECT COALESCE("USERID", "USERID") AS "USERID", "DISPLAYNAME", "REPUTATION", "TOTALPOSTS", "TOTALCOMMENTS", "TOTALUPVOTES", "TOTALDOWNVOTES", "TOTALBADGES", "Reputation" AS "Reputation_"
FROM (SELECT ANY_VALUE("Id") AS "USERID", "DisplayName" AS "DISPLAYNAME", "Reputation" AS "REPUTATION", COUNT(DISTINCT "Id0") AS "TOTALPOSTS", COUNT(DISTINCT "Id1") AS "TOTALCOMMENTS", SUM(CASE WHEN CAST("VoteTypeId" AS INTEGER) = 2 THEN 1 ELSE 0 END) AS "TOTALUPVOTES", SUM(CASE WHEN CAST("VoteTypeId" AS INTEGER) = 3 THEN 1 ELSE 0 END) AS "TOTALDOWNVOTES", SUM(CASE WHEN "Id3" IS NOT NULL THEN 1 ELSE 0 END) AS "TOTALBADGES", "Reputation"
FROM "s1"
WHERE "Reputation" > 0
GROUP BY "Id", "DisplayName", "Reputation"
ORDER BY 4 DESC NULLS FIRST, "Reputation" DESC NULLS FIRST
FETCH NEXT 100 ROWS ONLY) AS "t4"