SELECT COALESCE("t2"."POSTID", "t2"."POSTID") AS "POSTID", "t2"."POSTTYPEID", "t2"."TOTALCOMMENTS", "t2"."TOTALVOTES", "t2"."UPVOTES", "t2"."DOWNVOTES", "t2"."DELETIONVOTES", "t6"."USERID", "t6"."TOTALPOSTVIEWS", "t6"."POSTSCREATED"
FROM (SELECT ANY_VALUE("Posts"."Id") AS "POSTID", "Posts"."PostTypeId" AS "POSTTYPEID", COUNT("Comments"."Id") AS "TOTALCOMMENTS", COUNT("Votes"."Id") AS "TOTALVOTES", SUM(CASE WHEN CAST("Votes"."VoteTypeId" AS INTEGER) = 2 THEN 1 ELSE 0 END) AS "UPVOTES", SUM(CASE WHEN CAST("Votes"."VoteTypeId" AS INTEGER) = 3 THEN 1 ELSE 0 END) AS "DOWNVOTES", SUM(CASE WHEN CAST("Votes"."VoteTypeId" AS INTEGER) = 10 THEN 1 ELSE 0 END) AS "DELETIONVOTES"
FROM "STACK"."Posts"
LEFT JOIN "STACK"."Comments" ON "Posts"."Id" = "Comments"."PostId"
LEFT JOIN "STACK"."Votes" ON "Posts"."Id" = "Votes"."PostId"
WHERE "Posts"."CreationDate" >= (CAST('2024-10-01 12:34:56' AS TIMESTAMP(0)) - INTERVAL '1' YEAR)
GROUP BY "Posts"."Id", "Posts"."PostTypeId") AS "t2"
INNER JOIN (SELECT ANY_VALUE("Users"."Id") AS "USERID", SUM("Posts0"."ViewCount") AS "TOTALPOSTVIEWS", COUNT(DISTINCT "Posts0"."Id") AS "POSTSCREATED"
FROM "STACK"."Users"
INNER JOIN "STACK"."Posts" AS "Posts0" ON "Users"."Id" = "Posts0"."OwnerUserId"
WHERE "Users"."CreationDate" >= (CAST('2024-10-01 12:34:56' AS TIMESTAMP(0)) - INTERVAL '1' YEAR)
GROUP BY "Users"."Id") AS "t6" ON "t2"."POSTID" = "t6"."USERID"