SELECT COALESCE("POSTID", "POSTID") AS "POSTID", "POSTTYPEID", "TOTALCOMMENTS", "TOTALVOTES", "UPVOTES", "DOWNVOTES", "DELETIONVOTES", "USERID", "TOTALPOSTVIEWS", "POSTSCREATED"
FROM "s1"
ORDER BY "TOTALVOTES" DESC NULLS FIRST, "TOTALCOMMENTS" DESC NULLS FIRST