SELECT COALESCE("USERID", "USERID") AS "USERID", "REPUTATION", "CREATIONDATE", "POSTCOUNT", "QUESTIONCOUNT", "ANSWERCOUNT", "TOTALVIEWS", "TOTALSCORE", "BADGECOUNT", "GOLDBADGES", "SILVERBADGES", "BRONZEBADGES"
FROM "s1"
ORDER BY "REPUTATION" DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY