SELECT COALESCE("POSTID", "POSTID") AS "POSTID", "TITLE", "CREATIONDATE", "VIEWCOUNT", "SCORE", "OWNERDISPLAYNAME", "COMMENTCOUNT", "BADGECOUNT", "LASTHISTORYUPDATE", "TOTALVOTES", "UPVOTES", "DOWNVOTES"
FROM "s1"
ORDER BY "CREATIONDATE" DESC NULLS FIRST
FETCH NEXT 100 ROWS ONLY