SELECT COALESCE("t1"."POSTID", "t1"."POSTID") AS "POSTID", "t1"."TITLE", "t1"."CREATIONDATE", "t1"."VIEWCOUNT", "t1"."SCORE", "t1"."OWNERDISPLAYNAME", "t1"."COMMENTCOUNT", "t1"."BADGECOUNT", "t1"."LASTHISTORYUPDATE", CASE WHEN "t3"."VOTECOUNT" IS NOT NULL THEN CAST("t3"."VOTECOUNT" AS BIGINT) ELSE 0 END AS "TOTALVOTES", CASE WHEN "t3"."UPVOTES" IS NOT NULL THEN CAST("t3"."UPVOTES" AS INTEGER) ELSE 0 END AS "UPVOTES", CASE WHEN "t3"."DOWNVOTES" IS NOT NULL THEN CAST("t3"."DOWNVOTES" AS INTEGER) ELSE 0 END AS "DOWNVOTES"
FROM (SELECT ANY_VALUE("Posts"."Id") AS "POSTID", "Posts"."Title" AS "TITLE", "Posts"."CreationDate" AS "CREATIONDATE", "Posts"."ViewCount" AS "VIEWCOUNT", "Posts"."Score" AS "SCORE", ANY_VALUE("Users"."DisplayName") AS "OWNERDISPLAYNAME", COUNT("Comments"."Id") AS "COMMENTCOUNT", COUNT("Badges"."Id") AS "BADGECOUNT", MAX("PostHistory"."CreationDate") AS "LASTHISTORYUPDATE"
FROM "STACK"."Posts"
LEFT JOIN "STACK"."Users" ON "Posts"."OwnerUserId" = "Users"."Id"
LEFT JOIN "STACK"."Comments" ON "Posts"."Id" = "Comments"."PostId"
LEFT JOIN "STACK"."Badges" ON "Users"."Id" = "Badges"."UserId"
LEFT JOIN "STACK"."PostHistory" ON "Posts"."Id" = "PostHistory"."PostId"
GROUP BY "Posts"."Id", "Posts"."Title", "Posts"."CreationDate", "Posts"."ViewCount", "Posts"."Score", "Users"."DisplayName") AS "t1"
LEFT JOIN (SELECT "Votes"."PostId" AS "POSTID", COUNT(*) AS "VOTECOUNT", SUM(CASE WHEN "VoteTypes"."Name" = 'UpMod' THEN 1 ELSE 0 END) AS "UPVOTES", SUM(CASE WHEN "VoteTypes"."Name" = 'DownMod' THEN 1 ELSE 0 END) AS "DOWNVOTES"
FROM "STACK"."Votes"
INNER JOIN "STACK"."VoteTypes" ON "Votes"."VoteTypeId" = "VoteTypes"."Id"
GROUP BY "Votes"."PostId") AS "t3" ON "t1"."POSTID" = "t3"."POSTID"