SELECT COALESCE("POSTID", "POSTID") AS "POSTID", "TITLE", "CREATIONDATE", "VIEWCOUNT", "SCORE", "OWNERDISPLAYNAME", "COMMENTCOUNT", "VOTECOUNT", "AVERAGEBOUNTYAMOUNT", "BADGECOUNT", "POSTHISTORYCOUNT"
FROM "s1"
ORDER BY "CREATIONDATE" DESC NULLS FIRST
FETCH NEXT 100 ROWS ONLY