SELECT COALESCE("t1"."USERID", "t1"."USERID") AS "USERID", "t1"."REPUTATION", "t1"."POSTCOUNT", "t1"."BADGECOUNT", "t1"."TOTALBOUNTIES", "t1"."TOTALVIEWS", "t4"."POSTID", "t4"."POSTTYPEID", "t4"."ACCEPTEDANSWERID", "t4"."COMMENTCOUNT", "t4"."VOTECOUNT"
FROM (SELECT ANY_VALUE("Users"."Id") AS "USERID", "Users"."Reputation" AS "REPUTATION", COUNT(DISTINCT "Posts"."Id") AS "POSTCOUNT", COUNT(DISTINCT "Badges"."Id") AS "BADGECOUNT", SUM(CASE WHEN "Votes"."BountyAmount" IS NOT NULL THEN CAST("Votes"."BountyAmount" AS INTEGER) ELSE 0 END) AS "TOTALBOUNTIES", SUM(CASE WHEN "Posts"."ViewCount" IS NOT NULL THEN CAST("Posts"."ViewCount" AS INTEGER) ELSE 0 END) AS "TOTALVIEWS"
FROM "STACK"."Users"
LEFT JOIN "STACK"."Posts" ON "Users"."Id" = "Posts"."OwnerUserId"
LEFT JOIN "STACK"."Badges" ON "Users"."Id" = "Badges"."UserId"
LEFT JOIN "STACK"."Votes" ON "Users"."Id" = "Votes"."UserId"
GROUP BY "Users"."Id", "Users"."Reputation") AS "t1"
INNER JOIN (SELECT ANY_VALUE("Posts0"."Id") AS "POSTID", "Posts0"."PostTypeId" AS "POSTTYPEID", "Posts0"."AcceptedAnswerId" AS "ACCEPTEDANSWERID", COUNT(DISTINCT "Comments"."Id") AS "COMMENTCOUNT", COUNT(DISTINCT "Votes0"."Id") AS "VOTECOUNT"
FROM "STACK"."Posts" AS "Posts0"
LEFT JOIN "STACK"."Comments" ON "Posts0"."Id" = "Comments"."PostId"
LEFT JOIN "STACK"."Votes" AS "Votes0" ON "Posts0"."Id" = "Votes0"."PostId"
GROUP BY "Posts0"."Id", "Posts0"."PostTypeId", "Posts0"."AcceptedAnswerId") AS "t4" ON "t1"."USERID" = "t4"."ACCEPTEDANSWERID"