SELECT COALESCE("USERID", "USERID") AS "USERID", "REPUTATION", "POSTCOUNT", "BADGECOUNT", "TOTALBOUNTIES", "TOTALVIEWS", "POSTID", "POSTTYPEID", "ACCEPTEDANSWERID", "COMMENTCOUNT", "VOTECOUNT"
FROM "s1"
ORDER BY "REPUTATION" DESC NULLS FIRST, "POSTCOUNT" DESC NULLS FIRST