SELECT COALESCE("t3"."TITLE", "t3"."TITLE") AS "TITLE", "t3"."VIEWCOUNT", "t3"."SCORE", "t3"."COMMENTCOUNT", "t3"."VOTECOUNT", "t3"."UPVOTECOUNT", "t3"."DOWNVOTECOUNT", "t6"."DISPLAYNAME" AS "OWNERDISPLAYNAME", "t6"."POSTCOUNT", "t6"."TOTALUPVOTES", "t6"."TOTALDOWNVOTES", "t6"."AVERAGEREPUTATION"
FROM (SELECT ANY_VALUE("Id") AS "POSTID", "Title" AS "TITLE", "CreationDate" AS "CREATIONDATE", "ViewCount" AS "VIEWCOUNT", "Score" AS "SCORE", COUNT("Id0") AS "COMMENTCOUNT", COUNT(DISTINCT "Id1") AS "VOTECOUNT", SUM(CASE WHEN CAST("VoteTypeId" AS INTEGER) = 2 THEN 1 ELSE 0 END) AS "UPVOTECOUNT", SUM(CASE WHEN CAST("VoteTypeId" AS INTEGER) = 3 THEN 1 ELSE 0 END) AS "DOWNVOTECOUNT", COUNT(DISTINCT "Id2") AS "BADGECOUNT"
FROM "s1"
WHERE "CreationDate" >= (TIMESTAMP '2024-10-01 12:34:56' - INTERVAL '1' YEAR)
GROUP BY "Id", "Title", "CreationDate", "ViewCount", "Score") AS "t3"
INNER JOIN (SELECT ANY_VALUE("Users"."Id") AS "USERID", "Users"."DisplayName" AS "DISPLAYNAME", COUNT(DISTINCT "Posts0"."Id") AS "POSTCOUNT", SUM("Users"."UpVotes") AS "TOTALUPVOTES", SUM("Users"."DownVotes") AS "TOTALDOWNVOTES", AVG("Users"."Reputation") AS "AVERAGEREPUTATION"
FROM "STACK"."Users"
LEFT JOIN "STACK"."Posts" AS "Posts0" ON "Users"."Id" = "Posts0"."OwnerUserId"
GROUP BY "Users"."Id", "Users"."DisplayName") AS "t6" ON "t3"."POSTID" = "t6"."USERID"
ORDER BY "t3"."VIEWCOUNT" DESC NULLS FIRST
FETCH NEXT 100 ROWS ONLY