SELECT COALESCE("POSTTYPEID", "POSTTYPEID") AS "POSTTYPEID", "POSTTYPENAME", "TOTALPOSTS", "TOTALSCORE", "TOTALVIEWCOUNT", "AVGVIEWCOUNT", "TOTALQUESTIONS", "TOTALANSWERS", "TOTALWIKIS", "UNIQUEUSERS", "TOTALREPUTATION", "TOTALCOMMENTS", "TOTALVOTES"
FROM "s1"
ORDER BY "POSTTYPEID"