SELECT COALESCE("USERID", "USERID") AS "USERID", "DISPLAYNAME", "POSTCOUNT", "QUESTIONCOUNT", "ANSWERCOUNT", "TOTALCOMMENTS", "TOTALVOTES", "LASTPOSTDATE"
FROM "s1"
ORDER BY "POSTCOUNT" DESC NULLS FIRST
FETCH NEXT 100 ROWS ONLY