SELECT COALESCE("t2"."POSTID", "t2"."POSTID") AS "POSTID", "t2"."POSTTYPEID", "t2"."COMMENTCOUNT", "t2"."VOTECOUNT", "t2"."UPVOTES", "t2"."DOWNVOTES", "t2"."OFFENSIVEVOTES", "t2"."LASTACTIVITYDATE", "t5"."USERID", "t5"."BADGECOUNT", "t5"."TOTALUPVOTES", "t5"."TOTALDOWNVOTES", "t5"."TOTALVIEWS"
FROM (SELECT ANY_VALUE("Id") AS "POSTID", "POSTTYPEID", COUNT("Id0") AS "COMMENTCOUNT", COUNT("Id1") AS "VOTECOUNT", SUM("FD_COL_4") AS "UPVOTES", SUM("FD_COL_5") AS "DOWNVOTES", SUM("FD_COL_6") AS "OFFENSIVEVOTES", MAX("CreationDate") AS "LASTACTIVITYDATE", CAST("POSTTYPEID" AS INTEGER) AS "POSTTYPEID0"
FROM "s1"
GROUP BY "Id", "POSTTYPEID") AS "t2"
INNER JOIN (SELECT ANY_VALUE("Users"."Id") AS "USERID", COUNT("Badges"."Id") AS "BADGECOUNT", SUM("Users"."UpVotes") AS "TOTALUPVOTES", SUM("Users"."DownVotes") AS "TOTALDOWNVOTES", SUM("Users"."Views") AS "TOTALVIEWS"
FROM "STACK"."Users"
LEFT JOIN "STACK"."Badges" ON "Users"."Id" = "Badges"."UserId"
GROUP BY "Users"."Id") AS "t5" ON "t2"."POSTTYPEID0" = "t5"."USERID"
ORDER BY "t2"."LASTACTIVITYDATE" DESC NULLS FIRST