SELECT COALESCE("USERID", "USERID") AS "USERID", "DISPLAYNAME", "REPUTATION", "BADGECOUNT", "GOLDBADGES", "SILVERBADGES", "BRONZEBADGES", "POSTCOUNT", "TOTALSCORE", "TOTALVIEWS", "AVGSCORE"
FROM "s1"
ORDER BY "REPUTATION" DESC NULLS FIRST
FETCH NEXT 100 ROWS ONLY