SELECT COALESCE("t1"."POSTID", "t1"."POSTID") AS "POSTID", "t1"."TITLE", "t1"."CREATIONDATE" AS "POSTCREATIONDATE", "t1"."SCORE", "t1"."VIEWCOUNT", "t1"."COMMENTCOUNT", "t1"."VOTECOUNT", "t1"."BADGECOUNT", "t1"."TAGS", "t3"."HISTORYACTIONCOUNT", "t3"."LASTACTIVITYDATE"
FROM (SELECT ANY_VALUE("Posts"."Id") AS "POSTID", "Posts"."Title" AS "TITLE", "Posts"."CreationDate" AS "CREATIONDATE", "Posts"."Score" AS "SCORE", "Posts"."ViewCount" AS "VIEWCOUNT", COUNT("Comments"."Id") AS "COMMENTCOUNT", COUNT(DISTINCT "Votes"."UserId") AS "VOTECOUNT", COUNT(DISTINCT CASE WHEN "Badges"."Id" IS NOT NULL THEN "Badges"."Id" ELSE NULL END) AS "BADGECOUNT", ARRAY_AGG(DISTINCT "Tags"."TagName") AS "TAGS"
FROM "STACK"."Posts"
LEFT JOIN "STACK"."Comments" ON "Posts"."Id" = "Comments"."PostId"
LEFT JOIN "STACK"."Votes" ON "Posts"."Id" = "Votes"."PostId"
LEFT JOIN "STACK"."Badges" ON "Posts"."OwnerUserId" = "Badges"."UserId"
LEFT JOIN "STACK"."Tags" ON "Posts"."Id" = "Tags"."ExcerptPostId"
GROUP BY "Posts"."Id", "Posts"."Title", "Posts"."CreationDate", "Posts"."Score", "Posts"."ViewCount") AS "t1"
LEFT JOIN (SELECT "PostId" AS "POSTID", COUNT(*) AS "HISTORYACTIONCOUNT", MAX("CreationDate") AS "LASTACTIVITYDATE"
FROM "STACK"."PostHistory"
GROUP BY "PostId") AS "t3" ON "t1"."POSTID" = "t3"."POSTID"