SELECT COALESCE("POSTID", "POSTID") AS "POSTID", "TITLE", "POSTCREATIONDATE", "SCORE", "VIEWCOUNT", "COMMENTCOUNT", "VOTECOUNT", "BADGECOUNT", "TAGS", "HISTORYACTIONCOUNT", "LASTACTIVITYDATE"
FROM "s1"
ORDER BY "POSTCREATIONDATE" DESC NULLS FIRST
FETCH NEXT 100 ROWS ONLY