SELECT COALESCE("POSTTYPE", "POSTTYPE") AS "POSTTYPE", "TOTALPOSTS", "AVERAGESCORE", "TOTALVIEWS", "UNIQUEUSERS"
FROM (SELECT ANY_VALUE("Name") AS "POSTTYPE", COUNT(*) AS "TOTALPOSTS", AVG("Score") AS "AVERAGESCORE", SUM("ViewCount") AS "TOTALVIEWS", COUNT(DISTINCT "OwnerUserId") AS "UNIQUEUSERS"
FROM "s1"
WHERE "CreationDate" >= '2023-01-01'
GROUP BY "Name"
ORDER BY 2 DESC NULLS FIRST) AS "t4"