SELECT COALESCE("USERDISPLAYNAME", "USERDISPLAYNAME") AS "USERDISPLAYNAME", "REPUTATION", "TOTALPOSTS", "QUESTIONSCOUNT", "ANSWERSCOUNT", "TOTALVIEWS", "TOTALSCORE", "AVERAGEPOSTLENGTH", "TOTALCOMMENTS", "TOTALBADGES"
FROM "s1"
ORDER BY "TOTALPOSTS" DESC NULLS FIRST
FETCH NEXT 100 ROWS ONLY