SELECT COALESCE("POSTID", "POSTID") AS "POSTID", "TITLE", "CREATIONDATE", "SCORE", "VIEWCOUNT", "OWNERNAME", "COMMENTCOUNT", "UPVOTES", "DOWNVOTES", "EDITCOUNT", "FIRSTEDITDATE", "LASTEDITDATE"
FROM "s1"
ORDER BY "CREATIONDATE" DESC NULLS FIRST
FETCH NEXT 100 ROWS ONLY