SELECT COALESCE("t2"."POSTID", "t2"."POSTID") AS "POSTID", "t2"."POSTTYPEID", "t2"."CREATIONDATE", "t2"."SCORE", "t2"."VIEWCOUNT", "t2"."COMMENTCOUNT", "t2"."VOTECOUNT", "t5"."USERID", "t5"."REPUTATION", "t5"."BADGECOUNT", "t5"."TOTALPOSTS"
FROM (SELECT "t1"."POSTID", "t1"."POSTTYPEID", "t1"."CREATIONDATE", "t1"."SCORE", "t1"."VIEWCOUNT", "t1"."COMMENTCOUNT", "t1"."VOTECOUNT", "Users"."Id", "Users"."Reputation", "Users"."CreationDate", "Users"."DisplayName", "Users"."LastAccessDate", "Users"."WebsiteUrl", "Users"."Location", "Users"."AboutMe", "Users"."Views", "Users"."UpVotes", "Users"."DownVotes", "Users"."ProfileImageUrl", "Users"."AccountId"
FROM (SELECT ANY_VALUE("Posts"."Id") AS "POSTID", "Posts"."PostTypeId" AS "POSTTYPEID", "Posts"."CreationDate" AS "CREATIONDATE", "Posts"."Score" AS "SCORE", "Posts"."ViewCount" AS "VIEWCOUNT", COUNT(CASE WHEN "Comments"."Id" IS NOT NULL THEN 1 ELSE NULL END) AS "COMMENTCOUNT", COUNT(DISTINCT "Votes"."Id") AS "VOTECOUNT", CAST("Posts"."PostTypeId" AS INTEGER) AS "POSTTYPEID0"
FROM "STACK"."Posts"
LEFT JOIN "STACK"."Comments" ON "Posts"."Id" = "Comments"."PostId"
LEFT JOIN "STACK"."Votes" ON "Posts"."Id" = "Votes"."PostId"
GROUP BY "Posts"."Id", "Posts"."PostTypeId", "Posts"."CreationDate", "Posts"."Score", "Posts"."ViewCount") AS "t1"
INNER JOIN "STACK"."Users" ON "t1"."POSTTYPEID0" = "Users"."Id") AS "t2"
INNER JOIN (SELECT ANY_VALUE("Users0"."Id") AS "USERID", "Users0"."Reputation" AS "REPUTATION", COUNT(DISTINCT "Badges"."Id") AS "BADGECOUNT", COUNT(DISTINCT "Posts0"."Id") AS "TOTALPOSTS"
FROM "STACK"."Users" AS "Users0"
LEFT JOIN "STACK"."Badges" ON "Users0"."Id" = "Badges"."UserId"
LEFT JOIN "STACK"."Posts" AS "Posts0" ON "Users0"."Id" = "Posts0"."OwnerUserId"
GROUP BY "Users0"."Id", "Users0"."Reputation") AS "t5" ON "t2"."Id" = "t5"."USERID"