SELECT COALESCE("POSTTYPE", "POSTTYPE") AS "POSTTYPE", "POSTCOUNT", "AVGSCORE", "TOTALVIEWS", "AVGANSWERCOUNT", "AVGCOMMENTCOUNT", "USERWITHMOSTBADGES", "BADGECOUNT", "MAXREPUTATION", "AVGREPUTATION"
FROM "s1"
ORDER BY "POSTCOUNT" DESC NULLS FIRST