SELECT COALESCE("USERID", "USERID") AS "USERID", "DISPLAYNAME", "TOTALPOSTS", "QUESTIONS", "ANSWERS", "AVGPOSTSCORE", "AVGVIEWCOUNT", "TOTALCOMMENTS", "TOTALBADGES"
FROM "s1"
ORDER BY "TOTALPOSTS" DESC NULLS FIRST
FETCH NEXT 100 ROWS ONLY