SELECT COALESCE("POSTTITLE", "POSTTITLE") AS "POSTTITLE", "POSTCREATIONDATE", "AUTHORDISPLAYNAME", "COMMENTCOUNT", "UPVOTES", "DOWNVOTES", "VIEWCOUNT", "SCORE", "POSTTYPENAME", "CreationDate"
FROM "s1"
ORDER BY "CreationDate" DESC NULLS FIRST
FETCH NEXT 100 ROWS ONLY