SELECT COALESCE("USERID", "USERID") AS "USERID", "REPUTATION", "TOTALPOSTS", "QUESTIONS", "ANSWERS", "TOTALSCORE", "TOTALVIEWS", "AVGVIEWSPERPOST", "TOTALCOMMENTS"
FROM "s1"
ORDER BY "REPUTATION" DESC NULLS FIRST, "TOTALPOSTS" DESC NULLS FIRST