SELECT COALESCE("t1"."USERID", "t1"."USERID") AS "USERID", "t1"."BADGECOUNT", "t1"."TOTALVIEWS", "t1"."TOTALUPVOTES", "t1"."TOTALDOWNVOTES", "t7"."POSTTYPE", "t7"."TOTALPOSTS", "t7"."TOTALCOMMENTS", "t7"."TOTALVOTES"
FROM (SELECT ANY_VALUE("Users"."Id") AS "USERID", COUNT("Badges"."Id") AS "BADGECOUNT", SUM("Users"."Views") AS "TOTALVIEWS", SUM("Users"."UpVotes") AS "TOTALUPVOTES", SUM("Users"."DownVotes") AS "TOTALDOWNVOTES", CAST(ANY_VALUE("Users"."Id") AS BIGINT) AS "USERID0"
FROM "STACK"."Users"
LEFT JOIN "STACK"."Badges" ON "Users"."Id" = "Badges"."UserId"
GROUP BY "Users"."Id") AS "t1"
INNER JOIN (SELECT ANY_VALUE("PostTypes"."Name") AS "POSTTYPE", COUNT("Posts"."Id") AS "TOTALPOSTS", SUM("t4"."COMMENTCOUNT") AS "TOTALCOMMENTS", SUM("t4"."VOTECOUNT") AS "TOTALVOTES"
FROM "STACK"."PostTypes"
LEFT JOIN "STACK"."Posts" ON "PostTypes"."Id" = "Posts"."PostTypeId"
LEFT JOIN (SELECT ANY_VALUE("Posts0"."Id") AS "POSTID", "Posts0"."PostTypeId" AS "POSTTYPEID", COUNT("Comments"."Id") AS "COMMENTCOUNT", COUNT(DISTINCT "Votes"."Id") AS "VOTECOUNT", MAX(CASE WHEN CAST("Votes"."VoteTypeId" AS INTEGER) = 2 THEN 1 ELSE 0 END) AS "UPVOTE", MAX(CASE WHEN CAST("Votes"."VoteTypeId" AS INTEGER) = 3 THEN 1 ELSE 0 END) AS "DOWNVOTE", MAX("Posts0"."CreationDate") AS "LASTACTIVITYDATE"
FROM "STACK"."Posts" AS "Posts0"
LEFT JOIN "STACK"."Comments" ON "Posts0"."Id" = "Comments"."PostId"
LEFT JOIN "STACK"."Votes" ON "Posts0"."Id" = "Votes"."PostId"
GROUP BY "Posts0"."Id", "Posts0"."PostTypeId") AS "t4" ON "Posts"."Id" = "t4"."POSTID"
GROUP BY "PostTypes"."Name") AS "t7" ON "t1"."USERID0" = "t7"."TOTALPOSTS"