SELECT COALESCE("USERID", "USERID") AS "USERID", "BADGECOUNT", "TOTALVIEWS", "TOTALUPVOTES", "TOTALDOWNVOTES", "POSTTYPE", "TOTALPOSTS", "TOTALCOMMENTS", "TOTALVOTES"
FROM "s1"
ORDER BY "TOTALVIEWS" DESC NULLS FIRST, "TOTALPOSTS" DESC NULLS FIRST