SELECT COALESCE("POSTID", "POSTID") AS "POSTID", "TITLE", "CREATIONDATE", "VIEWCOUNT", "SCORE", "COMMENTCOUNT", "VOTECOUNT", "UPVOTECOUNT", "DOWNVOTECOUNT", "OWNERDISPLAYNAME", "POSTTYPENAME"
FROM "s1"
ORDER BY "CREATIONDATE" DESC NULLS FIRST
FETCH NEXT 100 ROWS ONLY