SELECT COALESCE("Users0"."Id", "Users0"."Id") AS "USERID", "Users0"."DisplayName" AS "DISPLAYNAME", "t2"."POSTCOUNT", "t2"."COMMENTCOUNT", "t2"."UPVOTES", "t2"."DOWNVOTES", "t2"."REPUTATION"
FROM "STACK"."Users" AS "Users0"
INNER JOIN (SELECT ANY_VALUE("Id") AS "USERID", "REPUTATION", COUNT(DISTINCT "Id0") AS "POSTCOUNT", COUNT(DISTINCT "Id1") AS "COMMENTCOUNT", SUM("FD_COL_4") AS "UPVOTES", SUM("FD_COL_5") AS "DOWNVOTES"
FROM "s1"
GROUP BY "Id", "REPUTATION") AS "t2" ON "Users0"."Id" = "t2"."USERID"
ORDER BY "t2"."REPUTATION" DESC NULLS FIRST, "t2"."POSTCOUNT" DESC NULLS FIRST
FETCH NEXT 100 ROWS ONLY