SELECT COALESCE("POSTID", "POSTID") AS "POSTID", "TITLE", "CREATIONDATE", "COMMENTCOUNT", "VOTECOUNT", "HISTORYCHANGECOUNT", "OWNERDISPLAYNAME", "OWNERREPUTATION"
FROM "s1"
ORDER BY "CREATIONDATE" DESC NULLS FIRST
FETCH NEXT 100 ROWS ONLY