SELECT COALESCE("POSTID", "POSTID") AS "POSTID", "TITLE", "POSTCREATIONDATE", "OWNERDISPLAYNAME", "OWNERREPUTATION", "UPVOTECOUNT", "DOWNVOTECOUNT", "COMMENTCOUNT", "USERBADGECOUNT"
FROM "s1"
ORDER BY "POSTCREATIONDATE" DESC NULLS FIRST
FETCH NEXT 100 ROWS ONLY