SELECT COALESCE("t2"."USERID", "t2"."USERID") AS "USERID", "t2"."REPUTATION", "t2"."POSTCOUNT", "t2"."COMMENTCOUNT", "t2"."BADGECOUNT", CASE WHEN "t4"."VOTECOUNT" IS NOT NULL THEN CAST("t4"."VOTECOUNT" AS BIGINT) ELSE 0 END AS "TOTALVOTES", CASE WHEN "t4"."UPVOTES" IS NOT NULL THEN CAST("t4"."UPVOTES" AS INTEGER) ELSE 0 END AS "UPVOTES", CASE WHEN "t4"."DOWNVOTES" IS NOT NULL THEN CAST("t4"."DOWNVOTES" AS INTEGER) ELSE 0 END AS "DOWNVOTES"
FROM (SELECT ANY_VALUE("Id") AS "USERID", "REPUTATION", COUNT("Id0") AS "POSTCOUNT", COUNT("Id1") AS "COMMENTCOUNT", COUNT("Id2") AS "BADGECOUNT"
FROM "s1"
GROUP BY "Id", "REPUTATION") AS "t2"
LEFT JOIN (SELECT "Votes"."UserId" AS "USERID", COUNT(*) AS "VOTECOUNT", SUM(CASE WHEN "VoteTypes"."Name" = 'UpMod' THEN 1 ELSE 0 END) AS "UPVOTES", SUM(CASE WHEN "VoteTypes"."Name" = 'DownMod' THEN 1 ELSE 0 END) AS "DOWNVOTES"
FROM "STACK"."Votes"
INNER JOIN "STACK"."VoteTypes" ON "Votes"."VoteTypeId" = "VoteTypes"."Id"
GROUP BY "Votes"."UserId") AS "t4" ON "t2"."USERID" = "t4"."USERID"
ORDER BY "t2"."REPUTATION" DESC NULLS FIRST
FETCH NEXT 100 ROWS ONLY