SELECT COALESCE("Posts0"."Id", "Posts0"."Id") AS "POSTID", "Posts0"."Title" AS "TITLE", "Posts0"."CreationDate" AS "CREATIONDATE", "Users"."DisplayName" AS "OWNERDISPLAYNAME", "Posts0"."Score" AS "SCORE", "Posts0"."ViewCount" AS "VIEWCOUNT", CASE WHEN "s1"."ANSWERCOUNT" IS NOT NULL THEN CAST("s1"."ANSWERCOUNT" AS BIGINT) ELSE 0 END AS "ANSWERCOUNT", CASE WHEN "t4"."COMMENTCOUNT" IS NOT NULL THEN CAST("t4"."COMMENTCOUNT" AS BIGINT) ELSE 0 END AS "COMMENTCOUNT"
FROM "STACK"."Posts" AS "Posts0"
INNER JOIN "STACK"."Users" ON "Posts0"."OwnerUserId" = "Users"."Id"
LEFT JOIN "s1" ON "Posts0"."Id" = "s1"."PARENTID"
LEFT JOIN (SELECT "PostId" AS "POSTID", COUNT(*) AS "COMMENTCOUNT"
FROM "STACK"."Comments"
GROUP BY "PostId") AS "t4" ON "Posts0"."Id" = "t4"."POSTID"
WHERE "Posts0"."CreationDate" >= '2022-01-01'
ORDER BY "Posts0"."Score" DESC NULLS FIRST, "Posts0"."ViewCount" DESC NULLS FIRST