SELECT COALESCE("t2"."USERID", "t2"."USERID") AS "USERID", "t2"."DISPLAYNAME", "t2"."TOTALPOSTS", "t2"."TOTALQUESTIONS", "t2"."TOTALANSWERS", "t2"."TOTALVIEWS", "t2"."AVERAGESCORE", CASE WHEN "t4"."TOTALBADGES" IS NOT NULL THEN CAST("t4"."TOTALBADGES" AS BIGINT) ELSE 0 END AS "TOTALBADGES"
FROM (SELECT ANY_VALUE("Id") AS "USERID", "DISPLAYNAME", COUNT("Id0") AS "TOTALPOSTS", SUM("FD_COL_3") AS "TOTALQUESTIONS", SUM("FD_COL_4") AS "TOTALANSWERS", SUM("ViewCount") AS "TOTALVIEWS", AVG("Score") AS "AVERAGESCORE"
FROM "s1"
GROUP BY "Id", "DISPLAYNAME") AS "t2"
LEFT JOIN (SELECT "UserId" AS "USERID", COUNT(*) AS "TOTALBADGES"
FROM "STACK"."Badges"
GROUP BY "UserId") AS "t4" ON "t2"."USERID" = "t4"."USERID"
ORDER BY "t2"."TOTALPOSTS" DESC NULLS FIRST
FETCH NEXT 100 ROWS ONLY