SELECT COALESCE("POSTID", "POSTID") AS "POSTID", "TITLE", "CREATIONDATE", "VIEWCOUNT", "SCORE", "COMMENTCOUNT", "VOTECOUNT", "UPVOTES", "DOWNVOTES", "OWNERDISPLAYNAME", "USERREPUTATION", "TOTALPOSTS", "TOTALBADGES"
FROM "s1"
ORDER BY "SCORE" DESC NULLS FIRST, "VIEWCOUNT" DESC NULLS FIRST