SELECT COALESCE("t0"."POSTID", "t0"."POSTID") AS "POSTID", "t0"."TITLE", "t0"."USERREPUTATION", "t0"."POSTCREATIONDATE", "t0"."LASTACTIVITYDATE", "t3"."COMMENTCOUNT", "t3"."UPVOTES", "t3"."DOWNVOTES", "t0"."SCORE", "t0"."VIEWCOUNT", "t0"."ANSWERCOUNT", "t0"."FAVORITECOUNT"
FROM (SELECT "Posts"."Id" AS "POSTID", "Posts"."OwnerUserId" AS "OWNERUSERID", "Posts"."CreationDate" AS "POSTCREATIONDATE", "Posts"."LastActivityDate" AS "LASTACTIVITYDATE", "Posts"."Score" AS "SCORE", "Posts"."ViewCount" AS "VIEWCOUNT", "Posts"."AnswerCount" AS "ANSWERCOUNT", "Posts"."CommentCount" AS "COMMENTCOUNT", "Posts"."FavoriteCount" AS "FAVORITECOUNT", "Posts"."Title" AS "TITLE", "Users"."Reputation" AS "USERREPUTATION"
FROM "STACK"."Posts"
INNER JOIN "STACK"."Users" ON "Posts"."OwnerUserId" = "Users"."Id"
WHERE "Posts"."CreationDate" >= (CAST('2024-10-01 12:34:56' AS TIMESTAMP(0)) - INTERVAL '1' YEAR)) AS "t0"
INNER JOIN (SELECT ANY_VALUE("Posts0"."Id") AS "POSTID", COUNT("Comments"."Id") AS "COMMENTCOUNT", SUM(CASE WHEN CAST("Votes"."VoteTypeId" AS INTEGER) = 2 THEN 1 ELSE 0 END) AS "UPVOTES", SUM(CASE WHEN CAST("Votes"."VoteTypeId" AS INTEGER) = 3 THEN 1 ELSE 0 END) AS "DOWNVOTES"
FROM "STACK"."Posts" AS "Posts0"
LEFT JOIN "STACK"."Comments" ON "Posts0"."Id" = "Comments"."PostId"
LEFT JOIN "STACK"."Votes" ON "Posts0"."Id" = "Votes"."PostId"
GROUP BY "Posts0"."Id") AS "t3" ON "t0"."POSTID" = "t3"."POSTID"