SELECT COALESCE("QUESTIONID", "QUESTIONID") AS "QUESTIONID", "QUESTIONSCORE", "QUESTIONVIEWS", "ANSWERCOUNT", "AVERAGEANSWERSCORE", "AVERAGEANSWERVIEWS"
FROM (SELECT ANY_VALUE("Id") AS "QUESTIONID", ANY_VALUE("Score") AS "QUESTIONSCORE", ANY_VALUE("ViewCount") AS "QUESTIONVIEWS", COUNT("Id0") AS "ANSWERCOUNT", CASE WHEN AVG("Score0") IS NOT NULL THEN CAST(AVG("Score0") AS INTEGER) ELSE 0 END AS "AVERAGEANSWERSCORE", CASE WHEN AVG("ViewCount0") IS NOT NULL THEN CAST(AVG("ViewCount0") AS INTEGER) ELSE 0 END AS "AVERAGEANSWERVIEWS"
FROM "s1"
WHERE CAST("PostTypeId" AS INTEGER) = 1
GROUP BY "Id", "Score", "ViewCount"
ORDER BY 1) AS "t4"