SELECT COALESCE("t1"."POSTID", "t1"."POSTID") AS "POSTID", "t1"."POSTTYPE", "t1"."COMMENTCOUNT", "t1"."VOTECOUNT", "t1"."UPVOTES", "t1"."DOWNVOTES", "t1"."LASTACTIVITYDATE", "t1"."TOTALVIEWS", "t4"."USERID", "t4"."DISPLAYNAME" AS "OWNERDISPLAYNAME", "t4"."BADGECOUNT", "t4"."USERUPVOTES", "t4"."USERDOWNVOTES", "t4"."POSTSCOUNT"
FROM (SELECT ANY_VALUE("Posts"."Id") AS "POSTID", ANY_VALUE("PostTypes"."Name") AS "POSTTYPE", COUNT("Comments"."Id") AS "COMMENTCOUNT", COUNT(DISTINCT "Votes"."Id") AS "VOTECOUNT", SUM(CASE WHEN CAST("Votes"."VoteTypeId" AS INTEGER) = 2 THEN 1 ELSE 0 END) AS "UPVOTES", SUM(CASE WHEN CAST("Votes"."VoteTypeId" AS INTEGER) = 3 THEN 1 ELSE 0 END) AS "DOWNVOTES", MAX("Posts"."CreationDate") AS "LASTACTIVITYDATE", SUM("Posts"."ViewCount") AS "TOTALVIEWS"
FROM "STACK"."Posts"
LEFT JOIN "STACK"."Comments" ON "Posts"."Id" = "Comments"."PostId"
LEFT JOIN "STACK"."Votes" ON "Posts"."Id" = "Votes"."PostId"
INNER JOIN "STACK"."PostTypes" ON "Posts"."PostTypeId" = "PostTypes"."Id"
GROUP BY "Posts"."Id", "PostTypes"."Name") AS "t1"
LEFT JOIN (SELECT ANY_VALUE("Users"."Id") AS "USERID", "Users"."DisplayName" AS "DISPLAYNAME", COUNT("Badges"."Id") AS "BADGECOUNT", SUM("Users"."UpVotes") AS "USERUPVOTES", SUM("Users"."DownVotes") AS "USERDOWNVOTES", COUNT(DISTINCT "Posts0"."Id") AS "POSTSCOUNT"
FROM "STACK"."Users"
LEFT JOIN "STACK"."Badges" ON "Users"."Id" = "Badges"."UserId"
LEFT JOIN "STACK"."Posts" AS "Posts0" ON "Users"."Id" = "Posts0"."OwnerUserId"
GROUP BY "Users"."Id", "Users"."DisplayName") AS "t4" ON "t1"."POSTID" = "t4"."USERID"