SELECT COALESCE("USERID", "USERID") AS "USERID", "USERDISPLAYNAME", "TOTALPOSTS", "TOTALPOSTSCORE", "TOTALPOSTVIEWS", "TOTALVOTES", "LASTPOSTDATE"
FROM (SELECT "USERID", "USERDISPLAYNAME", COUNT("POSTID") AS "TOTALPOSTS", SUM("POSTSCORE") AS "TOTALPOSTSCORE", SUM("POSTVIEWCOUNT") AS "TOTALPOSTVIEWS", SUM("VOTECOUNT") AS "TOTALVOTES", MAX("POSTCREATIONDATE") AS "LASTPOSTDATE"
FROM "s1"
GROUP BY "USERID", "USERDISPLAYNAME"
ORDER BY 3 DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY) AS "t4"