SELECT COALESCE("t2"."POSTID", "t2"."POSTID") AS "POSTID", "t2"."POSTTYPEID", "t2"."CREATIONDATE", "t2"."SCORE", "t2"."VIEWCOUNT", "t2"."ANSWERCOUNT", "t2"."TOTALCOMMENTCOUNT", "t2"."FAVORITECOUNT", "t2"."OWNERREPUTATION", "t4"."REVISIONCOUNT", "t4"."LASTEDITDATE", "t4"."CLOSEDPOSTS", "t4"."REOPENEDPOSTS"
FROM (SELECT ANY_VALUE("Id") AS "POSTID", "POSTTYPEID", "CREATIONDATE", "SCORE", "VIEWCOUNT", "ANSWERCOUNT", "COMMENTCOUNT", "FAVORITECOUNT", ANY_VALUE("Reputation") AS "OWNERREPUTATION", COUNT("Id1") AS "TOTALCOMMENTCOUNT", AVG("VoteTypeId") AS "AVGVOTETYPE"
FROM "s1"
GROUP BY "Id", "POSTTYPEID", "CREATIONDATE", "SCORE", "VIEWCOUNT", "ANSWERCOUNT", "COMMENTCOUNT", "FAVORITECOUNT", "Reputation") AS "t2"
LEFT JOIN (SELECT "PostId" AS "POSTID", COUNT(*) AS "REVISIONCOUNT", MAX("CreationDate") AS "LASTEDITDATE", MAX(CASE WHEN CAST("PostHistoryTypeId" AS INTEGER) = 10 THEN 1 ELSE 0 END) AS "CLOSEDPOSTS", MAX(CASE WHEN CAST("PostHistoryTypeId" AS INTEGER) = 11 THEN 1 ELSE 0 END) AS "REOPENEDPOSTS"
FROM "STACK"."PostHistory"
GROUP BY "PostId") AS "t4" ON "t2"."POSTID" = "t4"."POSTID"
ORDER BY "t2"."CREATIONDATE" DESC NULLS FIRST
FETCH NEXT 100 ROWS ONLY