SELECT COALESCE("t1"."USERID", "t1"."USERID") AS "USERID", "t1"."DISPLAYNAME", "t1"."REPUTATION", "t1"."POSTCOUNT", "t1"."QUESTIONS", "t1"."ANSWERS", "t1"."TOTALSCORE", "t1"."UPVOTES", "t1"."DOWNVOTES", "t4"."POSTID", "t4"."TITLE", "t4"."CREATIONDATE", "t4"."SCORE" AS "POSTSCORE", "t4"."VIEWCOUNT", "t4"."COMMENTCOUNT", "t4"."EDITHISTORYCOUNT"
FROM (SELECT ANY_VALUE("Users"."Id") AS "USERID", "Users"."DisplayName" AS "DISPLAYNAME", "Users"."Reputation" AS "REPUTATION", COUNT(DISTINCT "Posts"."Id") AS "POSTCOUNT", SUM(CASE WHEN CAST("Posts"."PostTypeId" AS INTEGER) = 1 THEN 1 ELSE 0 END) AS "QUESTIONS", SUM(CASE WHEN CAST("Posts"."PostTypeId" AS INTEGER) = 2 THEN 1 ELSE 0 END) AS "ANSWERS", SUM("Posts"."Score") AS "TOTALSCORE", SUM(CASE WHEN CAST("Votes"."VoteTypeId" AS INTEGER) = 2 THEN 1 ELSE 0 END) AS "UPVOTES", SUM(CASE WHEN CAST("Votes"."VoteTypeId" AS INTEGER) = 3 THEN 1 ELSE 0 END) AS "DOWNVOTES"
FROM "STACK"."Users"
LEFT JOIN "STACK"."Posts" ON "Users"."Id" = "Posts"."OwnerUserId"
LEFT JOIN "STACK"."Votes" ON "Posts"."Id" = "Votes"."PostId"
GROUP BY "Users"."Id", "Users"."DisplayName", "Users"."Reputation") AS "t1"
INNER JOIN (SELECT ANY_VALUE("Posts0"."Id") AS "POSTID", "Posts0"."Title" AS "TITLE", "Posts0"."CreationDate" AS "CREATIONDATE", "Posts0"."Score" AS "SCORE", "Posts0"."ViewCount" AS "VIEWCOUNT", COUNT("Comments"."Id") AS "COMMENTCOUNT", COUNT(DISTINCT "PostHistory"."Id") AS "EDITHISTORYCOUNT"
FROM "STACK"."Posts" AS "Posts0"
LEFT JOIN "STACK"."Comments" ON "Posts0"."Id" = "Comments"."PostId"
LEFT JOIN "STACK"."PostHistory" ON "Posts0"."Id" = "PostHistory"."PostId"
GROUP BY "Posts0"."Id", "Posts0"."Title", "Posts0"."CreationDate", "Posts0"."Score", "Posts0"."ViewCount") AS "t4" ON "t1"."USERID" = "t4"."POSTID"