SELECT COALESCE("t3"."POSTID", "t3"."POSTID") AS "POSTID", "t3"."TITLE", "t3"."POSTTYPEID", "t3"."CREATIONDATE", "t3"."VOTECOUNT", "t3"."COMMENTCOUNT", "t3"."BADGECOUNT", "t3"."UPVOTES", "t3"."DOWNVOTES", "Users"."DisplayName" AS "OWNERDISPLAYNAME", "Users"."Reputation" AS "OWNERREPUTATION"
FROM (SELECT ANY_VALUE("Id") AS "POSTID", "Title" AS "TITLE", "PostTypeId" AS "POSTTYPEID", "CreationDate" AS "CREATIONDATE", COUNT("Id0") AS "VOTECOUNT", COUNT("Id1") AS "COMMENTCOUNT", COUNT("Id2") AS "BADGECOUNT", SUM(CASE WHEN CAST("VoteTypeId" AS INTEGER) = 2 THEN 1 ELSE 0 END) AS "UPVOTES", SUM(CASE WHEN CAST("VoteTypeId" AS INTEGER) = 3 THEN 1 ELSE 0 END) AS "DOWNVOTES"
FROM "s1"
WHERE "CreationDate" >= CAST(DATE '2023-01-01' AS TIMESTAMP(0))
GROUP BY "Id", "Title", "PostTypeId", "CreationDate") AS "t3"
INNER JOIN "STACK"."Users" ON "t3"."POSTID" = "Users"."Id"
ORDER BY "t3"."CREATIONDATE" DESC NULLS FIRST