SELECT COALESCE("USERID", "USERID") AS "USERID", "DISPLAYNAME", "REPUTATION", "POSTCOUNT", "UPVOTES", "DOWNVOTES", "AVGREPUTATION", "AVGPOSTCOUNT", "AVGUPVOTES", "AVGDOWNVOTES"
FROM "s1"
ORDER BY "REPUTATION" DESC NULLS FIRST