SELECT COALESCE("s1"."POSTTYPEID", "s1"."POSTTYPEID") AS "POSTTYPEID", "s1"."TOTALPOSTS", "s1"."TOTALSCORE", "s1"."AVERAGEVIEWCOUNT", "s1"."AVERAGEANSWERCOUNT", "s1"."AVERAGECOMMENTCOUNT", "t3"."TOTALUSERS", "t3"."AVERAGEREPUTATION", "t3"."MOSTRECENTACCESSDATE", "t5"."VOTETYPEID", "t5"."TOTALVOTES"
FROM "s1",
(SELECT COUNT(*) AS "TOTALUSERS", AVG("Reputation") AS "AVERAGEREPUTATION", MAX("LastAccessDate") AS "MOSTRECENTACCESSDATE"
FROM "STACK"."Users") AS "t3",
(SELECT "VoteTypeId" AS "VOTETYPEID", COUNT(*) AS "TOTALVOTES"
FROM "STACK"."Votes"
GROUP BY "VoteTypeId") AS "t5"
ORDER BY "s1"."POSTTYPEID", "t5"."VOTETYPEID"