SELECT COALESCE("t1"."DISPLAYNAME", "t1"."DISPLAYNAME") AS "DISPLAYNAME", "t1"."TOTALVOTES", "t1"."UPVOTES", "t1"."DOWNVOTES", "t4"."POSTID", "t4"."TITLE", "t4"."SCORE", "t4"."VIEWCOUNT", "t4"."ANSWERCOUNT", "t4"."COMMENTCOUNT", "t7"."POSTUPVOTES", "t7"."POSTDOWNVOTES"
FROM (SELECT ANY_VALUE("Users"."Id") AS "USERID", "Users"."DisplayName" AS "DISPLAYNAME", COUNT("Votes"."Id") AS "TOTALVOTES", SUM(CASE WHEN CAST("Votes"."VoteTypeId" AS INTEGER) = 2 THEN 1 ELSE 0 END) AS "UPVOTES", SUM(CASE WHEN CAST("Votes"."VoteTypeId" AS INTEGER) = 3 THEN 1 ELSE 0 END) AS "DOWNVOTES"
FROM "STACK"."Users"
LEFT JOIN "STACK"."Votes" ON "Users"."Id" = "Votes"."UserId"
GROUP BY "Users"."Id", "Users"."DisplayName") AS "t1"
INNER JOIN (SELECT ANY_VALUE("Posts"."Id") AS "POSTID", "Posts"."Title" AS "TITLE", "Posts"."OwnerUserId" AS "OWNERUSERID", "Posts"."Score" AS "SCORE", "Posts"."ViewCount" AS "VIEWCOUNT", "Posts"."AnswerCount" AS "ANSWERCOUNT", COUNT("Comments"."Id") AS "COMMENTCOUNT"
FROM "STACK"."Posts"
LEFT JOIN "STACK"."Comments" ON "Posts"."Id" = "Comments"."PostId"
GROUP BY "Posts"."Id", "Posts"."Title", "Posts"."OwnerUserId", "Posts"."Score", "Posts"."ViewCount", "Posts"."AnswerCount") AS "t4" ON "t1"."USERID" = "t4"."OWNERUSERID"
INNER JOIN (SELECT ANY_VALUE("Posts0"."Id") AS "POSTID", SUM(CASE WHEN CAST("Votes0"."VoteTypeId" AS INTEGER) = 2 THEN 1 ELSE 0 END) AS "POSTUPVOTES", SUM(CASE WHEN CAST("Votes0"."VoteTypeId" AS INTEGER) = 3 THEN 1 ELSE 0 END) AS "POSTDOWNVOTES"
FROM "STACK"."Posts" AS "Posts0"
LEFT JOIN "STACK"."Votes" AS "Votes0" ON "Posts0"."Id" = "Votes0"."PostId"
GROUP BY "Posts0"."Id") AS "t7" ON "t4"."POSTID" = "t7"."POSTID"