SELECT COALESCE("DISPLAYNAME", "DISPLAYNAME") AS "DISPLAYNAME", "TOTALVOTES", "UPVOTES", "DOWNVOTES", "POSTID", "TITLE", "SCORE", "VIEWCOUNT", "ANSWERCOUNT", "COMMENTCOUNT", "POSTUPVOTES", "POSTDOWNVOTES"
FROM "s1"
ORDER BY "TOTALVOTES" DESC NULLS FIRST, "SCORE" DESC NULLS FIRST