SELECT COALESCE("USERID", "USERID") AS "USERID", "DISPLAYNAME", "TOTALPOSTS", "TOTALQUESTIONS", "TOTALANSWERS", "TOTALSCORE", "AVGVIEWCOUNT", "TOTALBADGES", "GOLDBADGES", "SILVERBADGES", "BRONZEBADGES"
FROM "s1"
ORDER BY "TOTALPOSTS" DESC NULLS FIRST
FETCH NEXT 100 ROWS ONLY