SELECT COALESCE("t2"."POSTTYPEID", "t2"."POSTTYPEID") AS "POSTTYPEID", "t2"."TOTALPOSTS", "t2"."TOTALACCEPTEDANSWERS", "t4"."USERID", "t4"."REPUTATION", "t4"."POSTSCOUNT", "t4"."TOTALBOUNTIES"
FROM (SELECT "PostTypeId" AS "POSTTYPEID", COUNT(*) AS "TOTALPOSTS", SUM(1) AS "TOTALACCEPTEDANSWERS"
FROM "STACK"."Posts"
GROUP BY "PostTypeId") AS "t2"
INNER JOIN (SELECT ANY_VALUE("Id") AS "USERID", "REPUTATION", COUNT(DISTINCT "Id0") AS "POSTSCOUNT", SUM("BountyAmount") AS "TOTALBOUNTIES", COUNT(DISTINCT "Id0") > 0 AS "$f4"
FROM "s1"
GROUP BY "Id", "REPUTATION") AS "t4" ON "t4"."$f4"
ORDER BY "t2"."TOTALPOSTS" DESC NULLS FIRST, "t4"."REPUTATION" DESC NULLS FIRST