SELECT COALESCE("Posts"."Id", "Posts"."Id") AS "POSTID", "Posts"."Title" AS "TITLE", "Posts"."CreationDate" AS "CREATIONDATE", "Posts"."Score" AS "SCORE", "Posts"."ViewCount" AS "VIEWCOUNT", CASE WHEN "t6"."ACCEPTEDANSWERID" IS NOT NULL THEN CAST("t6"."ACCEPTEDANSWERID" AS INTEGER) ELSE 0 END AS "ACCEPTEDANSWERID", "Users"."DisplayName" AS "OWNERDISPLAYNAME", "Users"."Reputation" AS "OWNERREPUTATION", "t0"."COMMENTCOUNT", "t2"."BADGECOUNT", "t4"."TAGNAME"
FROM "STACK"."Posts"
INNER JOIN "STACK"."Users" ON "Posts"."OwnerUserId" = "Users"."Id"
LEFT JOIN (SELECT "PostId" AS "POSTID", COUNT(*) AS "COMMENTCOUNT"
FROM "STACK"."Comments"
GROUP BY "PostId") AS "t0" ON "Posts"."Id" = "t0"."POSTID"
LEFT JOIN (SELECT "UserId" AS "USERID", COUNT(*) AS "BADGECOUNT"
FROM "STACK"."Badges"
GROUP BY "UserId") AS "t2" ON "Users"."Id" = "t2"."USERID"
LEFT JOIN (SELECT "PostLinks"."PostId" AS "POSTID", LISTAGG("Tags"."TagName", ', ') AS "TAGNAME"
FROM "STACK"."PostLinks"
INNER JOIN "STACK"."Tags" ON "PostLinks"."RelatedPostId" = "Tags"."Id"
GROUP BY "PostLinks"."PostId") AS "t4" ON "Posts"."Id" = "t4"."POSTID"
LEFT JOIN (SELECT "AcceptedAnswerId" AS "ACCEPTEDANSWERID"
FROM "STACK"."Posts"
WHERE CAST("PostTypeId" AS INTEGER) = 1) AS "t6" ON "Posts"."Id" = "t6"."ACCEPTEDANSWERID"
WHERE CAST("Posts"."PostTypeId" AS INTEGER) = 1