SELECT COALESCE("POSTID", "POSTID") AS "POSTID", "TITLE", "CREATIONDATE", "SCORE", "VIEWCOUNT", "ACCEPTEDANSWERID", "OWNERDISPLAYNAME", "OWNERREPUTATION", "COMMENTCOUNT", "BADGECOUNT", "TAGNAME"
FROM "s1"
ORDER BY "CREATIONDATE" DESC NULLS FIRST
FETCH NEXT 100 ROWS ONLY