SELECT COALESCE("t3"."TOTALPOSTS", "t3"."TOTALPOSTS") AS "TOTALPOSTS", "t3"."UNIQUEUSERS", "t3"."TOTALANSWERS", "t3"."TOTALCOMMENTS", "s1"."TOTALVOTES", "s1"."UNIQUEVOTERS", "t5"."TOTALUSERS", "t5"."AVGREPUTATION", "t5"."MAXREPUTATION"
FROM (SELECT COUNT(*) AS "TOTALPOSTS", COUNT(DISTINCT "OwnerUserId") AS "UNIQUEUSERS", SUM("AnswerCount") AS "TOTALANSWERS", SUM("CommentCount") AS "TOTALCOMMENTS"
FROM "STACK"."Posts") AS "t3",
"s1",
(SELECT COUNT(*) AS "TOTALUSERS", AVG("Reputation") AS "AVGREPUTATION", MAX("Reputation") AS "MAXREPUTATION"
FROM "STACK"."Users") AS "t5"