SELECT COALESCE("Title", "Title") AS "TITLE", "CreationDate" AS "CREATIONDATE", "DisplayName" AS "OWNERDISPLAYNAME", "ViewCount" AS "VIEWCOUNT", "AnswerCount" AS "ANSWERCOUNT"
FROM "s1"
WHERE CAST("PostTypeId" AS INTEGER) = 1
ORDER BY "CreationDate" DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY