SELECT COALESCE("Posts"."Id", "Posts"."Id") AS "POSTID", "Posts"."Title" AS "TITLE", "Posts"."CreationDate" AS "CREATIONDATE", "Users"."DisplayName" AS "OWNERDISPLAYNAME", CASE WHEN "t0"."COMMENTCOUNT" IS NOT NULL THEN CAST("t0"."COMMENTCOUNT" AS BIGINT) ELSE 0 END AS "NUMBEROFCOMMENTS", CASE WHEN "t3"."ANSWERCOUNT" IS NOT NULL THEN CAST("t3"."ANSWERCOUNT" AS BIGINT) ELSE 0 END AS "NUMBEROFANSWERS", CASE WHEN "t6"."TOTALUPVOTES" IS NOT NULL THEN CAST("t6"."TOTALUPVOTES" AS BIGINT) ELSE 0 END AS "TOTALUPVOTES"
FROM "STACK"."Posts"
INNER JOIN "STACK"."Users" ON "Posts"."OwnerUserId" = "Users"."Id"
LEFT JOIN (SELECT "PostId" AS "POSTID", COUNT(*) AS "COMMENTCOUNT"
FROM "STACK"."Comments"
GROUP BY "PostId") AS "t0" ON "Posts"."Id" = "t0"."POSTID"
LEFT JOIN (SELECT "ParentId" AS "PARENTID", COUNT(*) AS "ANSWERCOUNT"
FROM "STACK"."Posts"
WHERE CAST("PostTypeId" AS INTEGER) = 2
GROUP BY "ParentId") AS "t3" ON "Posts"."Id" = "t3"."PARENTID"
LEFT JOIN (SELECT "PostId" AS "POSTID", COUNT(*) AS "TOTALUPVOTES"
FROM "STACK"."Votes"
WHERE CAST("VoteTypeId" AS INTEGER) = 2
GROUP BY "PostId") AS "t6" ON "Posts"."Id" = "t6"."POSTID"
WHERE CAST("Posts"."PostTypeId" AS INTEGER) = 1