SELECT COALESCE("POSTID", "POSTID") AS "POSTID", "TITLE", "CREATIONDATE", "OWNERDISPLAYNAME", "NUMBEROFCOMMENTS", "NUMBEROFANSWERS", "TOTALUPVOTES"
FROM "s1"
ORDER BY "CREATIONDATE" DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY