SELECT COALESCE("Id", "Id") AS "POSTID", "Title" AS "TITLE", "DisplayName" AS "OWNERDISPLAYNAME", "CreationDate" AS "CREATIONDATE", "Score" AS "SCORE", "ViewCount" AS "VIEWCOUNT", "COMMENTCOUNT_" AS "COMMENTCOUNT", "VOTECOUNT"
FROM "s1"
WHERE CAST("PostTypeId" AS INTEGER) = 1
ORDER BY "CreationDate" DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY