SELECT COALESCE("Posts"."Id", "Posts"."Id") AS "Id", "Posts"."PostTypeId", "Posts"."AcceptedAnswerId", "Posts"."ParentId", "Posts"."CreationDate", "Posts"."Score", "Posts"."ViewCount", "Posts"."Body", "Posts"."OwnerUserId", "Posts"."OwnerDisplayName", "Posts"."LastEditorUserId", "Posts"."LastEditorDisplayName", "Posts"."LastEditDate", "Posts"."LastActivityDate", "Posts"."Title", "Posts"."Tags", "Posts"."AnswerCount", "Posts"."CommentCount", "Posts"."FavoriteCount", "Posts"."ClosedDate", "Posts"."CommunityOwnedDate", "Posts"."ContentLicense", "Users"."Id" AS "Id0", "Users"."Reputation", "Users"."CreationDate" AS "CreationDate0", "Users"."DisplayName", "Users"."LastAccessDate", "Users"."WebsiteUrl", "Users"."Location", "Users"."AboutMe", "Users"."Views", "Users"."UpVotes", "Users"."DownVotes", "Users"."ProfileImageUrl", "Users"."AccountId", "t0"."POSTID", "t0"."COMMENTCOUNT" AS "COMMENTCOUNT_", "t2"."POSTID" AS "POSTID0", "t2"."VOTECOUNT"
FROM "STACK"."Posts"
INNER JOIN "STACK"."Users" ON "Posts"."OwnerUserId" = "Users"."Id"
LEFT JOIN (SELECT "PostId" AS "POSTID", COUNT(*) AS "COMMENTCOUNT"
FROM "STACK"."Comments"
GROUP BY "PostId") AS "t0" ON "Posts"."Id" = "t0"."POSTID"
LEFT JOIN (SELECT "PostId" AS "POSTID", COUNT(*) AS "VOTECOUNT"
FROM "STACK"."Votes"
GROUP BY "PostId") AS "t2" ON "Posts"."Id" = "t2"."POSTID"