SELECT COALESCE("Id", "Id") AS "ID", "Title" AS "TITLE", "CreationDate" AS "CREATIONDATE", "Score" AS "SCORE", "DisplayName" AS "OWNERDISPLAYNAME"
FROM "s1"
WHERE CAST("PostTypeId" AS INTEGER) = 1
ORDER BY "CreationDate" DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY