SELECT COALESCE("DISPLAYNAME", "DISPLAYNAME") AS "DISPLAYNAME", "POSTCOUNT", "TOTALVIEWS"
FROM (SELECT "DISPLAYNAME", COUNT(*) AS "POSTCOUNT", SUM("FD_COL_1") AS "TOTALVIEWS"
FROM "s1"
GROUP BY "DISPLAYNAME"
ORDER BY 2 DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY) AS "t2"