SELECT COALESCE("USERID", "USERID") AS "USERID", "DISPLAYNAME", "BADGECOUNT", "POSTCOUNT", "QUESTIONCOUNT", "ANSWERCOUNT", "TOTALSCORE", "AVERAGEVIEWS", "RECENTACTIVITYCOUNT"
FROM "s1"
ORDER BY "TOTALSCORE" DESC NULLS FIRST, "QUESTIONCOUNT" DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY