SELECT COALESCE("DISPLAYNAME", "DISPLAYNAME") AS "DISPLAYNAME", "REPUTATIONLEVEL", "TOTALPOSTS", "TOTALQUESTIONS", "TOTALANSWERS", "RECENTUPVOTES", "RECENTCLOSEVOTES"
FROM "s1"
ORDER BY "TOTALPOSTS" DESC NULLS FIRST, "REPUTATIONLEVEL"