SELECT COALESCE("POSTID", "POSTID") AS "POSTID", "TITLE", "TAGSLIST", "USERDISPLAYNAME", "TOTALPOSTS", "TOTALVIEWS", "TOTALANSWERED", "HIGHENGAGEMENTPOSTS", "TOTALMODERATIONHISTORY", "TOTALCLOSURES", "TOTALREOPENS"
FROM (SELECT "t3"."POSTID", "t3"."TITLE", "t3"."TAGSLIST", "t7"."DISPLAYNAME" AS "USERDISPLAYNAME", "t7"."TOTALPOSTS", "t7"."TOTALVIEWS", "t7"."TOTALANSWERED", "t7"."HIGHENGAGEMENTPOSTS", "t3"."TOTALMODERATIONHISTORY", "t3"."TOTALCLOSURES", "t3"."TOTALREOPENS"
FROM (SELECT ANY_VALUE("Id") AS "POSTID", "Title" AS "TITLE", "ViewCount" AS "VIEWCOUNT", "AnswerCount" AS "ANSWERCOUNT", "CreationDate" AS "CREATIONDATE", LISTAGG(DISTINCT "TagName", ', ') AS "TAGSLIST", COUNT(DISTINCT "UserId") AS "TOTALMODERATIONHISTORY", SUM(CASE WHEN CAST("PostHistoryTypeId" AS INTEGER) = 10 THEN 1 ELSE 0 END) AS "TOTALCLOSURES", SUM(CASE WHEN CAST("PostHistoryTypeId" AS INTEGER) = 11 THEN 1 ELSE 0 END) AS "TOTALREOPENS", CAST(ANY_VALUE("Id") AS BIGINT) AS "POSTID0"
FROM "s1"
WHERE CAST("PostTypeId" AS INTEGER) = 1 AND "CreationDate" >= (CAST('2024-10-01 12:34:56' AS TIMESTAMP(0)) - INTERVAL '1' YEAR)
GROUP BY "Id", "Title", "ViewCount", "AnswerCount", "CreationDate") AS "t3"
INNER JOIN (SELECT ANY_VALUE("Users"."Id") AS "USERID", "Users"."DisplayName" AS "DISPLAYNAME", COUNT(DISTINCT "Posts0"."Id") AS "TOTALPOSTS", SUM("Posts0"."ViewCount") AS "TOTALVIEWS", SUM(CASE WHEN "Posts0"."AnswerCount" > 0 THEN 1 ELSE 0 END) AS "TOTALANSWERED", SUM(CASE WHEN "Posts0"."ViewCount" > 100 THEN 1 ELSE 0 END) AS "HIGHENGAGEMENTPOSTS"
FROM "STACK"."Users"
INNER JOIN "STACK"."Posts" AS "Posts0" ON "Users"."Id" = "Posts0"."OwnerUserId"
WHERE "Posts0"."CreationDate" >= (CAST('2024-10-01 12:34:56' AS TIMESTAMP(0)) - INTERVAL '1' YEAR)
GROUP BY "Users"."Id", "Users"."DisplayName") AS "t7" ON "t3"."POSTID0" = "t7"."TOTALPOSTS") AS "t8"
WHERE "t8"."TOTALVIEWS" > 500
ORDER BY "TOTALANSWERED" DESC NULLS FIRST