SELECT COALESCE("DISPLAYNAME", "DISPLAYNAME") AS "DISPLAYNAME", "BADGECOUNT", "GOLDBADGES", "SILVERBADGES", "BRONZEBADGES", "POSTCOUNT", "TOTALVIEWS", "TOTALSCORE", "AVGSCORE"
FROM "s1"
ORDER BY "TOTALSCORE" DESC NULLS FIRST, "TOTALVIEWS" DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY