SELECT COALESCE("TITLE", "TITLE") AS "TITLE", "TOTALPOSTS", "TOTALUPVOTES", "TOTALDOWNVOTES", "TOTALCLOSEDPOSTS"
FROM "s1"
WHERE "TOTALPOSTS" > 1
ORDER BY "TOTALPOSTS" DESC NULLS FIRST, "TOTALUPVOTES" DESC NULLS FIRST, "TOTALDOWNVOTES"
FETCH NEXT 10 ROWS ONLY