SELECT COALESCE("Posts"."Id", "Posts"."Id") AS "POSTID", "Posts"."Title" AS "TITLE", CASE WHEN "t1"."POSTCOUNT" IS NOT NULL THEN CAST("t1"."POSTCOUNT" AS BIGINT) ELSE 0 END AS "TOTALPOSTS", CASE WHEN "t4"."UPVOTECOUNT" IS NOT NULL THEN CAST("t4"."UPVOTECOUNT" AS INTEGER) ELSE 0 END AS "TOTALUPVOTES", CASE WHEN "t4"."DOWNVOTECOUNT" IS NOT NULL THEN CAST("t4"."DOWNVOTECOUNT" AS INTEGER) ELSE 0 END AS "TOTALDOWNVOTES", CASE WHEN "t6"."CLOSEDPOSTCOUNT" IS NOT NULL THEN CAST("t6"."CLOSEDPOSTCOUNT" AS INTEGER) ELSE 0 END AS "TOTALCLOSEDPOSTS"
FROM "STACK"."Posts"
LEFT JOIN (SELECT "Id" AS "ID", COUNT(*) AS "POSTCOUNT"
FROM "STACK"."Posts"
WHERE CAST("PostTypeId" AS INTEGER) = 1 OR CAST("PostTypeId" AS INTEGER) = 2
GROUP BY "Id") AS "t1" ON "Posts"."Id" = "t1"."ID"
LEFT JOIN (SELECT ANY_VALUE("Users"."Id") AS "USERID", "Users"."DisplayName" AS "DISPLAYNAME", SUM(CASE WHEN CAST("Votes"."VoteTypeId" AS INTEGER) = 2 THEN 1 ELSE 0 END) AS "UPVOTECOUNT", SUM(CASE WHEN CAST("Votes"."VoteTypeId" AS INTEGER) = 3 THEN 1 ELSE 0 END) AS "DOWNVOTECOUNT"
FROM "STACK"."Users"
LEFT JOIN "STACK"."Votes" ON "Users"."Id" = "Votes"."UserId"
GROUP BY "Users"."Id", "Users"."DisplayName") AS "t4" ON "Posts"."OwnerUserId" = "t4"."USERID"
LEFT JOIN (SELECT "Tags"."TagName" AS "TAGNAME", COUNT(*) AS "POSTCOUNT", SUM(CASE WHEN CAST("Posts1"."PostTypeId" AS INTEGER) = 1 THEN 1 ELSE 0 END) AS "QUESTIONCOUNT", SUM(CASE WHEN CAST("Posts1"."PostTypeId" AS INTEGER) = 2 THEN 1 ELSE 0 END) AS "ANSWERCOUNT", SUM(CASE WHEN CAST("PostHistory"."PostHistoryTypeId" AS INTEGER) = 10 THEN 1 ELSE 0 END) AS "CLOSEDPOSTCOUNT"
FROM "STACK"."Posts" AS "Posts1"
INNER JOIN "STACK"."Tags" ON "Posts1"."Tags" LIKE '%' || "Tags"."TagName" || '%'
LEFT JOIN "STACK"."PostHistory" ON "Posts1"."Id" = "PostHistory"."PostId"
GROUP BY "Tags"."TagName") AS "t6" ON "Posts"."Tags" LIKE '%' || "t6"."TAGNAME" || '%'