SELECT COALESCE("DISPLAYNAME", "DISPLAYNAME") AS "DISPLAYNAME", "BADGECOUNT", "QUESTIONCOUNT", "ANSWERCOUNT", "TOTALSCORE", "AVGVIEWCOUNT", "BADGESUMMARY"
FROM "s1"
ORDER BY "TOTALSCORE" DESC NULLS FIRST, "BADGECOUNT" DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY