SELECT COALESCE("DISPLAYNAME", "DISPLAYNAME") AS "USERNAME", "TOTALUPVOTES", "TOTALDOWNVOTES", "POSTID", "TITLE_" AS "POSTTITLE", "VIEWCOUNT_" AS "VIEWCOUNT", "TOTALANSWERS", "TOTALCOMMENTS", "CLOSECOUNT", "LASTCLOSEDDATE"
FROM "s1"
WHERE "TOTALUPVOTES" > "TOTALDOWNVOTES"
ORDER BY "VIEWCOUNT_" DESC NULLS FIRST, "TOTALUPVOTES" DESC NULLS FIRST