SELECT COALESCE("DISPLAYNAME", "DISPLAYNAME") AS "USERDISPLAYNAME", "TOTALREPUTATION", "BADGECOUNT", "CLOSEDPOSTS", "TITLE" AS "POSTTITLE", "POSTCREATIONDATE", "POSTUPVOTES", "POSTDOWNVOTES", "POSTAVGVOTE"
FROM "s1"
WHERE "CLOSEDPOSTS" > 0
ORDER BY "TOTALREPUTATION" DESC NULLS FIRST, "POSTCREATIONDATE" DESC NULLS FIRST
FETCH NEXT 100 ROWS ONLY