SELECT COALESCE("t4"."POSTID", "t4"."POSTID") AS "POSTID", "t4"."TITLE", "t4"."SCORE", "t4"."CREATIONDATE", "t4"."UPVOTES", "t4"."DOWNVOTES", "t4"."USERBADGECOUNT", "t10"."LASTCLOSEDATE", "t10"."CLOSEREASONNAMES", CASE WHEN "t10"."LASTCLOSEDATE" IS NOT NULL THEN 'Closed' ELSE 'Open  ' END AS "POSTSTATUS"
FROM (SELECT "Posts"."Id" AS "POSTID", "Posts"."Title" AS "TITLE", "Posts"."Score" AS "SCORE", "Posts"."CreationDate" AS "CREATIONDATE", CASE WHEN "t0"."UPVOTES" IS NOT NULL THEN CAST("t0"."UPVOTES" AS INTEGER) ELSE 0 END AS "UPVOTES", CASE WHEN "t0"."DOWNVOTES" IS NOT NULL THEN CAST("t0"."DOWNVOTES" AS INTEGER) ELSE 0 END AS "DOWNVOTES", CASE WHEN "t2"."BADGECOUNT" IS NOT NULL THEN CAST("t2"."BADGECOUNT" AS BIGINT) ELSE 0 END AS "USERBADGECOUNT"
FROM "STACK"."Posts"
LEFT JOIN (SELECT "PostId" AS "POSTID", SUM(CASE WHEN CAST("VoteTypeId" AS INTEGER) = 2 THEN 1 ELSE 0 END) AS "UPVOTES", SUM(CASE WHEN CAST("VoteTypeId" AS INTEGER) = 3 THEN 1 ELSE 0 END) AS "DOWNVOTES", COUNT(*) AS "TOTALVOTES"
FROM "STACK"."Votes"
GROUP BY "PostId") AS "t0" ON "Posts"."Id" = "t0"."POSTID"
LEFT JOIN "STACK"."Users" ON "Posts"."OwnerUserId" = "Users"."Id"
LEFT JOIN (SELECT "UserId" AS "USERID", COUNT(*) AS "BADGECOUNT"
FROM "STACK"."Badges"
GROUP BY "UserId") AS "t2" ON "Users"."Id" = "t2"."USERID"
WHERE "Posts"."CreationDate" >= (TIMESTAMP '2024-10-01 12:34:56' - INTERVAL '30' DAY)) AS "t4"
LEFT JOIN (SELECT "PostId" AS "POSTID", MAX("CreationDate") AS "LASTCLOSEDATE", LISTAGG("Name", ', ') AS "CLOSEREASONNAMES"
FROM (SELECT "t5"."Id", "t5"."PostHistoryTypeId", "t5"."PostId", "t5"."RevisionGUID", "t5"."CreationDate", "t5"."UserId", "t5"."UserDisplayName", "t5"."Comment", "t5"."Text", "t5"."ContentLicense", "t6"."Id" AS "Id0", "t6"."Name"
FROM (SELECT "Id", "PostHistoryTypeId", "PostId", "RevisionGUID", "CreationDate", "UserId", "UserDisplayName", "Comment", "Text", "ContentLicense", CAST("Comment" AS INTEGER) AS "Comment0"
FROM "STACK"."PostHistory") AS "t5"
INNER JOIN (SELECT "Id", "Name", CAST("Id" AS INTEGER) AS "Id0"
FROM "STACK"."CloseReasonTypes") AS "t6" ON "t5"."Comment0" = "t6"."Id0") AS "t7"
WHERE CAST("t7"."PostHistoryTypeId" AS INTEGER) = 10
GROUP BY "PostId") AS "t10" ON "t4"."POSTID" = "t10"."POSTID"