SELECT COALESCE("USERID", "USERID") AS "USERID", "DISPLAYNAME", "NETVOTES", "GOLDBADGES", "SILVERBADGES", "BRONZEBADGES", "COMMENTCOUNT", "RELATEDPOSTS"
FROM "s1"
ORDER BY "NETVOTES" DESC NULLS FIRST, "DISPLAYNAME"
FETCH NEXT 50 ROWS ONLY