SELECT COALESCE("t1"."USERID", "t1"."USERID") AS "USERID", "t1"."DISPLAYNAME", "t1"."NETVOTES", "t1"."GOLDBADGES", "t1"."SILVERBADGES", "t1"."BRONZEBADGES", CASE WHEN "t5"."COMMENTCOUNT" IS NOT NULL THEN CAST("t5"."COMMENTCOUNT" AS BIGINT) ELSE 0 END AS "COMMENTCOUNT", CASE WHEN "t5"."RELATEDPOSTS" IS NOT NULL THEN CAST("t5"."RELATEDPOSTS" AS BIGINT) ELSE 0 END AS "RELATEDPOSTS"
FROM (SELECT ANY_VALUE("Users"."Id") AS "USERID", "Users"."DisplayName" AS "DISPLAYNAME", SUM(CASE WHEN CAST("Votes"."VoteTypeId" AS INTEGER) = 2 THEN 1 ELSE 0 END) - SUM(CASE WHEN CAST("Votes"."VoteTypeId" AS INTEGER) = 3 THEN 1 ELSE 0 END) AS "NETVOTES", SUM(CASE WHEN CAST("Badges"."Class" AS INTEGER) = 1 THEN 1 ELSE 0 END) AS "GOLDBADGES", SUM(CASE WHEN CAST("Badges"."Class" AS INTEGER) = 2 THEN 1 ELSE 0 END) AS "SILVERBADGES", SUM(CASE WHEN CAST("Badges"."Class" AS INTEGER) = 3 THEN 1 ELSE 0 END) AS "BRONZEBADGES"
FROM "STACK"."Users"
LEFT JOIN "STACK"."Votes" ON "Users"."Id" = "Votes"."UserId"
LEFT JOIN "STACK"."Badges" ON "Users"."Id" = "Badges"."UserId"
GROUP BY "Users"."Id", "Users"."DisplayName") AS "t1"
LEFT JOIN (SELECT ANY_VALUE("Posts"."Id") AS "POSTID", "Posts"."OwnerUserId" AS "OWNERUSERID", COUNT("Comments"."Id") AS "COMMENTCOUNT", COUNT(DISTINCT "Posts0"."Id") AS "RELATEDPOSTS"
FROM "STACK"."Posts"
LEFT JOIN "STACK"."Comments" ON "Posts"."Id" = "Comments"."PostId"
LEFT JOIN "STACK"."PostLinks" ON "Posts"."Id" = "PostLinks"."PostId"
LEFT JOIN "STACK"."Posts" AS "Posts0" ON "PostLinks"."RelatedPostId" = "Posts0"."Id"
WHERE "Posts"."CreationDate" >= (CAST('2024-10-01 12:34:56' AS TIMESTAMP(0)) - INTERVAL '30' DAY)
GROUP BY "Posts"."Id", "Posts"."OwnerUserId") AS "t5" ON "t1"."USERID" = "t5"."OWNERUSERID"
WHERE "t1"."NETVOTES" > 10 AND ("t1"."GOLDBADGES" > 0 OR "t1"."SILVERBADGES" > 2)