SELECT COALESCE(ANY_VALUE("Id"), ANY_VALUE("Id")) AS "USERID", "DISPLAYNAME", "REPUTATION", COUNT(DISTINCT "Id0") AS "QUESTIONCOUNT", COUNT(DISTINCT "Id1") AS "ANSWERCOUNT", SUM("FD_COL_5") AS "ACCEPTEDANSWERCOUNT", SUM("FD_COL_6") AS "TOTALCOMMENTCOUNT", SUM("FD_COL_7") AS "TOTALUPVOTES", SUM("FD_COL_8") AS "TOTALDOWNVOTES"
FROM "s1"
GROUP BY "Id", "DISPLAYNAME", "REPUTATION"
HAVING COUNT(DISTINCT "Id0") > 0
ORDER BY "REPUTATION" DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY