SELECT COALESCE("USERID", "USERID") AS "USERID", "DISPLAYNAME", "TOTALPOSTS", "TOTALQUESTIONS", "TOTALANSWERS", "AVERAGEPOSTSCORE", "TOTALBADGES", "GOLDBADGES", "SILVERBADGES", "BRONZEBADGES", CASE WHEN "TOTALPOSTS" > 100 THEN 'High Activity    ' WHEN "TOTALPOSTS" >= 50 AND "TOTALPOSTS" <= 100 THEN 'Moderate Activity' ELSE 'Low Activity     ' END AS "ACTIVITYLEVEL"
FROM "s1"
WHERE "TOTALPOSTS" > 0
ORDER BY "TOTALPOSTS" DESC NULLS FIRST
OFFSET 0 ROWS
FETCH NEXT 10 ROWS ONLY