SELECT COALESCE("DISPLAYNAME", "DISPLAYNAME") AS "DISPLAYNAME", "TOTALPOSTS", "QUESTIONS", "ANSWERS", "BADGECOUNT", "AVGSCORE", "TOTALVIEWS"
FROM "s1"
ORDER BY "BADGECOUNT" DESC NULLS FIRST, "TOTALPOSTS" DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY