SELECT COALESCE("POSTID", "POSTID") AS "POSTID", "TITLE", "SCORE", "TOTALCLOSECOUNT", "OWNERDISPLAYNAME", "OWNERREPUTATION", "EFFECTIVEOWNER"
FROM (SELECT "Id" AS "POSTID", "Title" AS "TITLE", "Score" AS "SCORE", CASE WHEN "CLOSECOUNT" IS NOT NULL THEN CAST("CLOSECOUNT" AS BIGINT) ELSE 0 END AS "TOTALCLOSECOUNT", "DISPLAYNAME" AS "OWNERDISPLAYNAME", "REPUTATION" AS "OWNERREPUTATION", "DISPLAYNAME" AS "EFFECTIVEOWNER"
FROM "s1"
WHERE CAST("PostTypeId" AS INTEGER) = 1 AND "Score" > 10) AS "t7"
WHERE "TOTALCLOSECOUNT" = 0
ORDER BY "SCORE" DESC NULLS FIRST, "TITLE"