SELECT COALESCE("DISPLAYNAME", "DISPLAYNAME") AS "DISPLAYNAME", "REPUTATION", "CLOSEDPOSTCOUNT", "RECENTCLOSEDPOSTS", "CLOSEDPOSTTITLES"
FROM "s1"
ORDER BY "REPUTATION" DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY