SELECT COALESCE("USERID", "USERID") AS "USERID", "DISPLAYNAME", "POSTCOUNT", "TOTALVIEWS", "AVERAGESCORE", "GOLDBADGES", "SILVERBADGES", "BRONZEBADGES", CASE WHEN "POSTCOUNT" > 50 THEN 'Highly Active    ' WHEN "POSTCOUNT" >= 21 AND "POSTCOUNT" <= 50 THEN 'Moderately Active' ELSE 'Less Active      ' END AS "ACTIVITYLEVEL"
FROM (SELECT "Users"."Id" AS "USERID", "Users"."DisplayName" AS "DISPLAYNAME", CASE WHEN "t2"."POSTCOUNT" IS NOT NULL THEN CAST("t2"."POSTCOUNT" AS BIGINT) ELSE 0 END AS "POSTCOUNT", CASE WHEN "t2"."TOTALVIEWS" IS NOT NULL THEN CAST("t2"."TOTALVIEWS" AS INTEGER) ELSE 0 END AS "TOTALVIEWS", CASE WHEN "t2"."AVERAGESCORE" IS NOT NULL THEN CAST("t2"."AVERAGESCORE" AS INTEGER) ELSE 0 END AS "AVERAGESCORE", CASE WHEN "t5"."GOLDBADGES" IS NOT NULL THEN CAST("t5"."GOLDBADGES" AS INTEGER) ELSE 0 END AS "GOLDBADGES", CASE WHEN "t5"."SILVERBADGES" IS NOT NULL THEN CAST("t5"."SILVERBADGES" AS INTEGER) ELSE 0 END AS "SILVERBADGES", CASE WHEN "t5"."BRONZEBADGES" IS NOT NULL THEN CAST("t5"."BRONZEBADGES" AS INTEGER) ELSE 0 END AS "BRONZEBADGES"
FROM "STACK"."Users"
LEFT JOIN (SELECT "OWNERUSERID", COUNT(*) AS "POSTCOUNT", SUM("ViewCount") AS "TOTALVIEWS", AVG("Score") AS "AVERAGESCORE"
FROM "s1"
GROUP BY "OWNERUSERID") AS "t2" ON "Users"."Id" = "t2"."OWNERUSERID"
LEFT JOIN (SELECT ANY_VALUE("Users0"."Id") AS "USERID", "Users0"."DisplayName" AS "DISPLAYNAME", SUM(CASE WHEN CAST("Badges"."Class" AS INTEGER) = 1 THEN 1 ELSE 0 END) AS "GOLDBADGES", SUM(CASE WHEN CAST("Badges"."Class" AS INTEGER) = 2 THEN 1 ELSE 0 END) AS "SILVERBADGES", SUM(CASE WHEN CAST("Badges"."Class" AS INTEGER) = 3 THEN 1 ELSE 0 END) AS "BRONZEBADGES"
FROM "STACK"."Users" AS "Users0"
LEFT JOIN "STACK"."Badges" ON "Users0"."Id" = "Badges"."UserId"
GROUP BY "Users0"."Id", "Users0"."DisplayName") AS "t5" ON "Users"."Id" = "t5"."USERID") AS "t6"
WHERE "t6"."TOTALVIEWS" > 1000
ORDER BY "TOTALVIEWS" DESC NULLS FIRST