SELECT COALESCE("DISPLAYNAME", "DISPLAYNAME") AS "DISPLAYNAME", "REPUTATION", "TITLE", "CREATIONDATE", "COMMENTCOUNT", "UPVOTECOUNT", "DOWNVOTECOUNT", "ACCEPTEDANSWERUPVOTES", "RELATEDPOSTCOUNT", "DUPLICATECOUNT"
FROM "s1"
ORDER BY "REPUTATION" DESC NULLS FIRST, "CREATIONDATE" DESC NULLS FIRST
OFFSET 0 ROWS
FETCH NEXT 10 ROWS ONLY