SELECT COALESCE("DISPLAYNAME", "DISPLAYNAME") AS "DISPLAYNAME", "POSTCOUNT", "POSITIVESCOREPOSTS", "NEGATIVESCOREPOSTS", "TOTALBOUNTY", "TITLE", "COMMENTCOUNT", "HIGHVIEWCOUNT", "LASTACTIVITY"
FROM "s1"
ORDER BY "TOTALBOUNTY" DESC NULLS FIRST, "POSTCOUNT" DESC NULLS FIRST
FETCH NEXT 50 ROWS ONLY