SELECT COALESCE("TITLE", "TITLE") AS "TITLE", "CREATIONDATE", "OWNERDISPLAYNAME", "SCORE", "UPVOTES", "DOWNVOTES", "TOTALBADGES", "TOTALPOSTS"
FROM "s1"
ORDER BY "SCORE" DESC NULLS FIRST, "UPVOTES" DESC NULLS FIRST, "DOWNVOTES"