SELECT COALESCE("USERID", "USERID") AS "USERID", "DISPLAYNAME", "REPUTATION", "POSTCOUNT", "POSITIVEPOSTS", "NEGATIVEPOSTS", "POPULARPOSTS", "AVERAGEVIEWS", "BADGECOUNT", "GOLDBADGES", "SILVERBADGES", "BRONZEBADGES"
FROM "s1"
ORDER BY "REPUTATION" DESC NULLS FIRST, "POSTCOUNT" DESC NULLS FIRST
FETCH NEXT 50 ROWS ONLY