SELECT COALESCE("t2"."USERID", "t2"."USERID") AS "USERID", "t2"."DISPLAYNAME", "t2"."REPUTATION", "t2"."VIEWS", "t2"."UPVOTES", "t2"."DOWNVOTES", "t2"."POSTCOUNT", "t2"."QUESTIONCOUNT", "t2"."ANSWERCOUNT", "t2"."CLOSEDPOSTCOUNT", CASE WHEN "t5"."BADGECOUNT" IS NOT NULL THEN CAST("t5"."BADGECOUNT" AS BIGINT) ELSE 0 END AS "GOLDBADGECOUNT", CASE WHEN "t8"."EDITCOUNT" IS NOT NULL THEN CAST("t8"."EDITCOUNT" AS BIGINT) ELSE 0 END AS "EDITCOUNT"
FROM (SELECT ANY_VALUE("Users"."Id") AS "USERID", "Users"."DisplayName" AS "DISPLAYNAME", "Users"."Reputation" AS "REPUTATION", "Users"."Views" AS "VIEWS", "Users"."UpVotes" AS "UPVOTES", "Users"."DownVotes" AS "DOWNVOTES", COUNT(DISTINCT "Posts"."Id") AS "POSTCOUNT", SUM(CASE WHEN CAST("Posts"."PostTypeId" AS INTEGER) = 1 THEN 1 ELSE 0 END) AS "QUESTIONCOUNT", SUM(CASE WHEN CAST("Posts"."PostTypeId" AS INTEGER) = 2 THEN 1 ELSE 0 END) AS "ANSWERCOUNT", SUM(CASE WHEN "Posts"."ClosedDate" IS NOT NULL THEN 1 ELSE 0 END) AS "CLOSEDPOSTCOUNT"
FROM "STACK"."Users"
LEFT JOIN "STACK"."Posts" ON "Users"."Id" = "Posts"."OwnerUserId"
WHERE "Users"."Reputation" > 1000
GROUP BY "Users"."Id", "Users"."DisplayName", "Users"."Reputation", "Users"."Views", "Users"."UpVotes", "Users"."DownVotes") AS "t2"
LEFT JOIN (SELECT "UserId" AS "USERID", COUNT(*) AS "BADGECOUNT"
FROM "STACK"."Badges"
WHERE CAST("Class" AS INTEGER) = 1
GROUP BY "UserId") AS "t5" ON "t2"."USERID" = "t5"."USERID"
LEFT JOIN (SELECT "UserId" AS "USERID", COUNT(*) AS "EDITCOUNT"
FROM "STACK"."PostHistory"
WHERE CAST("PostHistoryTypeId" AS INTEGER) = 4 OR CAST("PostHistoryTypeId" AS INTEGER) = 5 OR CAST("PostHistoryTypeId" AS INTEGER) = 6
GROUP BY "UserId") AS "t8" ON "t2"."USERID" = "t8"."USERID"