SELECT COALESCE("POSTID", "POSTID") AS "POSTID", "TITLE", "VIEWCOUNT", "VOTECOUNT", "UPVOTES", "DOWNVOTES", CASE WHEN "USERBADGECOUNT" IS NOT NULL THEN CAST("USERBADGECOUNT" AS BIGINT) ELSE 0 END AS "USERBADGECOUNT", CASE WHEN "GOLDBADGES" IS NOT NULL THEN CAST("GOLDBADGES" AS INTEGER) ELSE 0 END AS "GOLDBADGES", CASE WHEN "SILVERBADGES" IS NOT NULL THEN CAST("SILVERBADGES" AS INTEGER) ELSE 0 END AS "SILVERBADGES", CASE WHEN "BRONZEBADGES" IS NOT NULL THEN CAST("BRONZEBADGES" AS INTEGER) ELSE 0 END AS "BRONZEBADGES"
FROM (SELECT "Posts"."Id" AS "POSTID", "Posts"."Title" AS "TITLE", "Posts"."ViewCount" AS "VIEWCOUNT", "t2"."VOTECOUNT", "t2"."UPVOTES", "t2"."DOWNVOTES", "t5"."BADGECOUNT" AS "USERBADGECOUNT", "t5"."GOLDBADGES", "t5"."SILVERBADGES", "t5"."BRONZEBADGES"
FROM "STACK"."Posts"
INNER JOIN (SELECT ANY_VALUE("Posts0"."Id") AS "POSTID", "Posts0"."OwnerUserId" AS "OWNERUSERID", COUNT("Votes"."Id") AS "VOTECOUNT", SUM(CASE WHEN CAST("Votes"."VoteTypeId" AS INTEGER) = 2 THEN 1 ELSE 0 END) AS "UPVOTES", SUM(CASE WHEN CAST("Votes"."VoteTypeId" AS INTEGER) = 3 THEN 1 ELSE 0 END) AS "DOWNVOTES"
FROM "STACK"."Posts" AS "Posts0"
LEFT JOIN "STACK"."Votes" ON "Posts0"."Id" = "Votes"."PostId"
WHERE "Posts0"."CreationDate" >= '2021-01-01'
GROUP BY "Posts0"."Id", "Posts0"."OwnerUserId") AS "t2" ON "Posts"."Id" = "t2"."POSTID"
LEFT JOIN (SELECT ANY_VALUE("Users"."Id") AS "USERID", COUNT("Badges"."Id") AS "BADGECOUNT", SUM(CASE WHEN CAST("Badges"."Class" AS INTEGER) = 1 THEN 1 ELSE 0 END) AS "GOLDBADGES", SUM(CASE WHEN CAST("Badges"."Class" AS INTEGER) = 2 THEN 1 ELSE 0 END) AS "SILVERBADGES", SUM(CASE WHEN CAST("Badges"."Class" AS INTEGER) = 3 THEN 1 ELSE 0 END) AS "BRONZEBADGES"
FROM "STACK"."Users"
LEFT JOIN "STACK"."Badges" ON "Users"."Id" = "Badges"."UserId"
GROUP BY "Users"."Id") AS "t5" ON "t2"."OWNERUSERID" = "t5"."USERID") AS "t6"
WHERE "t6"."VIEWCOUNT" > 1000