SELECT COALESCE("USERID", "USERID") AS "USERID", "DISPLAYNAME", "QUESTIONCOUNT", "ANSWERCOUNT", "TOTALSCORE", "TOTALVIEWS", "UNIQUETAGCOUNT", "BADGECOUNT", "GOLDBADGES", "SILVERBADGES", "BRONZEBADGES"
FROM (SELECT "t4"."USERID", "t4"."DISPLAYNAME", CASE WHEN "t5"."QUESTIONCOUNT" IS NOT NULL THEN CAST("t5"."QUESTIONCOUNT" AS BIGINT) ELSE 0 END AS "QUESTIONCOUNT", CASE WHEN "t5"."ANSWERCOUNT" IS NOT NULL THEN CAST("t5"."ANSWERCOUNT" AS BIGINT) ELSE 0 END AS "ANSWERCOUNT", CASE WHEN "t5"."TOTALSCORE" IS NOT NULL THEN CAST("t5"."TOTALSCORE" AS INTEGER) ELSE 0 END AS "TOTALSCORE", CASE WHEN "t5"."TOTALVIEWS" IS NOT NULL THEN CAST("t5"."TOTALVIEWS" AS INTEGER) ELSE 0 END AS "TOTALVIEWS", CASE WHEN "t5"."UNIQUETAGCOUNT" IS NOT NULL THEN CAST("t5"."UNIQUETAGCOUNT" AS BIGINT) ELSE 0 END AS "UNIQUETAGCOUNT", "t4"."BADGECOUNT", "t4"."GOLDBADGES", "t4"."SILVERBADGES", "t4"."BRONZEBADGES"
FROM (SELECT ANY_VALUE("Users"."Id") AS "USERID", "Users"."DisplayName" AS "DISPLAYNAME", COUNT("Badges"."Id") AS "BADGECOUNT", SUM(CASE WHEN CAST("Badges"."Class" AS INTEGER) = 1 THEN 1 ELSE 0 END) AS "GOLDBADGES", SUM(CASE WHEN CAST("Badges"."Class" AS INTEGER) = 2 THEN 1 ELSE 0 END) AS "SILVERBADGES", SUM(CASE WHEN CAST("Badges"."Class" AS INTEGER) = 3 THEN 1 ELSE 0 END) AS "BRONZEBADGES"
FROM "STACK"."Users"
LEFT JOIN "STACK"."Badges" ON "Users"."Id" = "Badges"."UserId"
GROUP BY "Users"."Id", "Users"."DisplayName") AS "t4"
LEFT JOIN (SELECT "OWNERUSERID", COUNT("FD_COL_1") AS "QUESTIONCOUNT", COUNT("FD_COL_2") AS "ANSWERCOUNT", SUM("Score") AS "TOTALSCORE", SUM("ViewCount") AS "TOTALVIEWS", COUNT(DISTINCT "Tags") AS "UNIQUETAGCOUNT"
FROM "s1"
GROUP BY "OWNERUSERID") AS "t5" ON "t4"."USERID" = "t5"."OWNERUSERID") AS "t6"
WHERE "t6"."TOTALVIEWS" > 1000
ORDER BY "TOTALSCORE" DESC NULLS FIRST, "QUESTIONCOUNT" DESC NULLS FIRST
FETCH NEXT 50 ROWS ONLY