SELECT COALESCE("DisplayName", "DisplayName") AS "USER", "Title" AS "POST_TITLE", "CreationDate" AS "POST_CREATION_DATE", "Score" AS "POST_SCORE", CASE WHEN "AVG_COMMENT_SCORE" IS NOT NULL THEN CAST("AVG_COMMENT_SCORE" AS INTEGER) ELSE 0 END AS "AVERAGE_COMMENT_SCORE", CASE WHEN "UPVOTES_" IS NOT NULL THEN CAST("UPVOTES_" AS INTEGER) ELSE 0 END AS "TOTAL_UPVOTES", CASE WHEN "DOWNVOTES_" IS NOT NULL THEN CAST("DOWNVOTES_" AS INTEGER) ELSE 0 END AS "TOTAL_DOWNVOTES"
FROM "s1"
WHERE CAST("PostTypeId" AS INTEGER) = 1
ORDER BY "CreationDate" DESC NULLS FIRST
FETCH NEXT 100 ROWS ONLY