SELECT COALESCE("Users"."Id", "Users"."Id") AS "USERID", "Users"."DisplayName" AS "DISPLAYNAME", "t4"."BADGECOUNT", "t5"."TOTALPOSTS", "t5"."QUESTIONS", "t5"."ANSWERS", "t5"."TOTALSCORE", "t5"."AVGVIEWCOUNT"
FROM "STACK"."Users"
INNER JOIN (SELECT ANY_VALUE("Users0"."Id") AS "USERID", "Users0"."DisplayName" AS "DISPLAYNAME", COUNT("Badges"."Id") AS "BADGECOUNT", SUM(CASE WHEN CAST("Badges"."Class" AS INTEGER) = 1 THEN 1 ELSE 0 END) AS "GOLDBADGES", SUM(CASE WHEN CAST("Badges"."Class" AS INTEGER) = 2 THEN 1 ELSE 0 END) AS "SILVERBADGES", SUM(CASE WHEN CAST("Badges"."Class" AS INTEGER) = 3 THEN 1 ELSE 0 END) AS "BRONZEBADGES"
FROM "STACK"."Users" AS "Users0"
LEFT JOIN "STACK"."Badges" ON "Users0"."Id" = "Badges"."UserId"
GROUP BY "Users0"."Id", "Users0"."DisplayName") AS "t4" ON "Users"."Id" = "t4"."USERID"
INNER JOIN (SELECT "OWNERUSERID", COUNT(*) AS "TOTALPOSTS", SUM("FD_COL_1") AS "QUESTIONS", SUM("FD_COL_2") AS "ANSWERS", SUM("Score") AS "TOTALSCORE", AVG("ViewCount") AS "AVGVIEWCOUNT"
FROM "s1"
GROUP BY "OWNERUSERID") AS "t5" ON "Users"."Id" = "t5"."OWNERUSERID"
WHERE "Users"."LastAccessDate" > CAST((CURRENT_DATE - INTERVAL '6' MONTH) AS TIMESTAMP(0))
ORDER BY "t5"."TOTALSCORE" DESC NULLS FIRST, "t4"."BADGECOUNT" DESC NULLS FIRST
FETCH NEXT 100 ROWS ONLY