SELECT COALESCE("t4"."USERID", "t4"."USERID") AS "USERID", "t4"."DISPLAYNAME", "t4"."BADGECOUNT", "t4"."GOLDBADGES", "t4"."SILVERBADGES", "t4"."BRONZEBADGES", "t5"."POSTCOUNT", "t5"."SCOREPOSITIVE", "t5"."QUESTIONS", "t5"."ANSWERS"
FROM (SELECT ANY_VALUE("Users"."Id") AS "USERID", "Users"."DisplayName" AS "DISPLAYNAME", COUNT("Badges"."Id") AS "BADGECOUNT", SUM(CASE WHEN CAST("Badges"."Class" AS INTEGER) = 1 THEN 1 ELSE 0 END) AS "GOLDBADGES", SUM(CASE WHEN CAST("Badges"."Class" AS INTEGER) = 2 THEN 1 ELSE 0 END) AS "SILVERBADGES", SUM(CASE WHEN CAST("Badges"."Class" AS INTEGER) = 3 THEN 1 ELSE 0 END) AS "BRONZEBADGES"
FROM "STACK"."Users"
LEFT JOIN "STACK"."Badges" ON "Users"."Id" = "Badges"."UserId"
GROUP BY "Users"."Id", "Users"."DisplayName") AS "t4"
LEFT JOIN (SELECT "OWNERUSERID", COUNT(*) AS "POSTCOUNT", SUM("FD_COL_1") AS "SCOREPOSITIVE", SUM("FD_COL_2") AS "QUESTIONS", SUM("FD_COL_3") AS "ANSWERS"
FROM "s1"
GROUP BY "OWNERUSERID") AS "t5" ON "t4"."USERID" = "t5"."OWNERUSERID"
ORDER BY "t4"."BADGECOUNT" DESC NULLS FIRST, "t5"."SCOREPOSITIVE" DESC NULLS FIRST, "t5"."POSTCOUNT" DESC NULLS FIRST
FETCH NEXT 100 ROWS ONLY