SELECT COALESCE("DISPLAYNAME", "DISPLAYNAME") AS "DISPLAYNAME", "REPUTATION", "POSTCOUNT", "POPULARPOSTS", "HIGHSCOREPOSTS", "BADGECOUNT", CASE WHEN "REPUTATION" > 1000 THEN 'Elite ' WHEN "REPUTATION" > 500 THEN 'Pro   ' ELSE 'Novice' END AS "USERTIER"
FROM (SELECT "t2"."USERID", "t2"."DISPLAYNAME", "t2"."REPUTATION", "t2"."POSTCOUNT", "t2"."POPULARPOSTS", "t2"."HIGHSCOREPOSTS", CASE WHEN "t4"."BADGECOUNT" IS NOT NULL THEN CAST("t4"."BADGECOUNT" AS BIGINT) ELSE 0 END AS "BADGECOUNT"
FROM (SELECT ANY_VALUE("Users"."Id") AS "USERID", "Users"."DisplayName" AS "DISPLAYNAME", "Users"."Reputation" AS "REPUTATION", COUNT(DISTINCT "Posts"."Id") AS "POSTCOUNT", SUM(CASE WHEN "Posts"."ViewCount" > 1000 THEN 1 ELSE 0 END) AS "POPULARPOSTS", SUM(CASE WHEN "Posts"."Score" > 50 THEN 1 ELSE 0 END) AS "HIGHSCOREPOSTS"
FROM "STACK"."Users"
LEFT JOIN "STACK"."Posts" ON "Users"."Id" = "Posts"."OwnerUserId"
WHERE "Users"."Reputation" > 100
GROUP BY "Users"."Id", "Users"."DisplayName", "Users"."Reputation") AS "t2"
LEFT JOIN (SELECT "UserId" AS "USERID", COUNT(*) AS "BADGECOUNT"
FROM "STACK"."Badges"
GROUP BY "UserId") AS "t4" ON "t2"."USERID" = "t4"."USERID") AS "t5"
WHERE "t5"."POSTCOUNT" > 10