SELECT COALESCE("DISPLAYNAME", "DISPLAYNAME") AS "DISPLAYNAME", "REPUTATION", "POSTCOUNT", "POPULARPOSTS", "HIGHSCOREPOSTS", "BADGECOUNT", "USERTIER"
FROM "s1"
ORDER BY "REPUTATION" DESC NULLS FIRST, "POSTCOUNT" DESC NULLS FIRST
FETCH NEXT 20 ROWS ONLY