SELECT COALESCE("DISPLAYNAME", "DISPLAYNAME") AS "DISPLAYNAME", "REPUTATION", "TOTALUPVOTES", "TOTALDOWNVOTES", "TOTALQUESTIONS", "TOTALANSWERS", "AVGSCORE", "TOTALVIEWS", "ENGAGEMENTCATEGORY"
FROM "s1"
ORDER BY "REPUTATION" DESC NULLS FIRST, "TOTALUPVOTES" DESC NULLS FIRST