SELECT COALESCE("Users"."DisplayName", "Users"."DisplayName") AS "DISPLAYNAME", "s1"."POSTCOUNT", "s1"."QUESTIONCOUNT", "s1"."ANSWERCOUNT", "s1"."AVGSCORE", "s1"."TOTALVIEWS", "s1"."TOTALCOMMENTS", CASE WHEN "t3"."BADGECOUNT" IS NOT NULL THEN CAST("t3"."BADGECOUNT" AS BIGINT) ELSE 0 END AS "BADGECOUNT", CASE WHEN "t3"."HIGHESTBADGECLASS" IS NOT NULL THEN CAST("t3"."HIGHESTBADGECLASS" AS INTEGER) ELSE 0 END AS "HIGHESTBADGECLASS"
FROM "STACK"."Users"
INNER JOIN "s1" ON "Users"."Id" = "s1"."OWNERUSERID"
LEFT JOIN (SELECT "UserId" AS "USERID", COUNT(*) AS "BADGECOUNT", MAX("Class") AS "HIGHESTBADGECLASS"
FROM "STACK"."Badges"
GROUP BY "UserId") AS "t3" ON "Users"."Id" = "t3"."USERID"
WHERE "Users"."Reputation" > 1000
ORDER BY "s1"."AVGSCORE" DESC NULLS FIRST, "s1"."TOTALVIEWS" DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY