SELECT COALESCE("USERID", "USERID") AS "USERID", "DISPLAYNAME", "REPUTATION", "TOTALPOSTS", "TOTALSCORE", "TOTALCOMMENTS", "TOTALCLOSED", "TOTALREOPENED"
FROM (SELECT ANY_VALUE("Users"."Id") AS "USERID", "Users"."DisplayName" AS "DISPLAYNAME", "Users"."Reputation" AS "REPUTATION", "t2"."UPVOTES", "t2"."DOWNVOTES", "t2"."REPUTATIONCHANGE", COUNT(DISTINCT "t4"."POSTID") AS "TOTALPOSTS", SUM("t4"."SCORE") AS "TOTALSCORE", CASE WHEN SUM("t4"."COMMENTCOUNT") IS NOT NULL THEN CAST(SUM("t4"."COMMENTCOUNT") AS INTEGER) ELSE 0 END AS "TOTALCOMMENTS", CASE WHEN SUM("t4"."CLOSEDCOUNT") IS NOT NULL THEN CAST(SUM("t4"."CLOSEDCOUNT") AS INTEGER) ELSE 0 END AS "TOTALCLOSED", CASE WHEN SUM("t4"."REOPENEDCOUNT") IS NOT NULL THEN CAST(SUM("t4"."REOPENEDCOUNT") AS INTEGER) ELSE 0 END AS "TOTALREOPENED"
FROM "STACK"."Users"
LEFT JOIN (SELECT "UserId" AS "USERID", SUM(CASE WHEN CAST("VoteTypeId" AS INTEGER) = 2 THEN 1 ELSE 0 END) AS "UPVOTES", SUM(CASE WHEN CAST("VoteTypeId" AS INTEGER) = 3 THEN 1 ELSE 0 END) AS "DOWNVOTES", SUM(CASE WHEN CAST("VoteTypeId" AS INTEGER) = 2 THEN 1 ELSE -1 END) AS "REPUTATIONCHANGE"
FROM "STACK"."Votes"
GROUP BY "UserId") AS "t2" ON "Users"."Id" = "t2"."USERID"
LEFT JOIN (SELECT ANY_VALUE("Id") AS "POSTID", "OWNERUSERID", "TITLE", "CREATIONDATE", "SCORE", "VIEWCOUNT", SUM("FD_COL_6") AS "COMMENTCOUNT", SUM("FD_COL_7") AS "CLOSEDCOUNT", SUM("FD_COL_8") AS "REOPENEDCOUNT"
FROM "s1"
GROUP BY "Id", "OWNERUSERID", "TITLE", "CREATIONDATE", "SCORE", "VIEWCOUNT") AS "t4" ON "Users"."Id" = "t4"."OWNERUSERID"
GROUP BY "Users"."Id", "Users"."DisplayName", "Users"."Reputation", "t2"."UPVOTES", "t2"."DOWNVOTES", "t2"."REPUTATIONCHANGE") AS "t7"
WHERE "t7"."REPUTATION" > 1000
ORDER BY "REPUTATION" DESC NULLS FIRST, "TOTALSCORE" DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY