SELECT COALESCE("DISPLAYNAME", "DISPLAYNAME") AS "DISPLAYNAME", "REPUTATION", "POSTCOUNT", "QUESTIONCOUNT", "ANSWERCOUNT", "BADGECOUNT", "GOLDBADGES", "SILVERBADGES", "BRONZEBADGES", "UPVOTESRECEIVED", "DOWNVOTESRECEIVED", "AVGPOSTSCORE"
FROM (SELECT "t2"."USERID", "t2"."DISPLAYNAME", "t2"."REPUTATION", "t2"."POSTCOUNT", "t2"."QUESTIONCOUNT", "t2"."ANSWERCOUNT", CASE WHEN "t4"."BADGECOUNT" IS NOT NULL THEN CAST("t4"."BADGECOUNT" AS BIGINT) ELSE 0 END AS "BADGECOUNT", CASE WHEN "t4"."GOLDBADGES" IS NOT NULL THEN CAST("t4"."GOLDBADGES" AS INTEGER) ELSE 0 END AS "GOLDBADGES", CASE WHEN "t4"."SILVERBADGES" IS NOT NULL THEN CAST("t4"."SILVERBADGES" AS INTEGER) ELSE 0 END AS "SILVERBADGES", CASE WHEN "t4"."BRONZEBADGES" IS NOT NULL THEN CAST("t4"."BRONZEBADGES" AS INTEGER) ELSE 0 END AS "BRONZEBADGES", "t2"."UPVOTESRECEIVED", "t2"."DOWNVOTESRECEIVED", "t2"."AVGPOSTSCORE"
FROM (SELECT ANY_VALUE("Id") AS "USERID", "DISPLAYNAME", "REPUTATION", "UPVOTES", "DOWNVOTES", COUNT(DISTINCT "Id0") AS "POSTCOUNT", SUM("FD_COL_6") AS "QUESTIONCOUNT", SUM("FD_COL_7") AS "ANSWERCOUNT", SUM("FD_COL_8") AS "UPVOTESRECEIVED", SUM("FD_COL_9") AS "DOWNVOTESRECEIVED", AVG("Score") AS "AVGPOSTSCORE"
FROM "s1"
GROUP BY "Id", "DISPLAYNAME", "REPUTATION", "UPVOTES", "DOWNVOTES") AS "t2"
LEFT JOIN (SELECT "UserId" AS "USERID", COUNT(*) AS "BADGECOUNT", SUM(CASE WHEN CAST("Class" AS INTEGER) = 1 THEN 1 ELSE 0 END) AS "GOLDBADGES", SUM(CASE WHEN CAST("Class" AS INTEGER) = 2 THEN 1 ELSE 0 END) AS "SILVERBADGES", SUM(CASE WHEN CAST("Class" AS INTEGER) = 3 THEN 1 ELSE 0 END) AS "BRONZEBADGES"
FROM "STACK"."Badges"
GROUP BY "UserId") AS "t4" ON "t2"."USERID" = "t4"."USERID") AS "t5"
WHERE "t5"."REPUTATION" > 1000
ORDER BY "REPUTATION" DESC NULLS FIRST, "POSTCOUNT" DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY