SELECT COALESCE("USERID", "USERID") AS "USERID", "DISPLAYNAME", "TOTALPOSTS", "TOTALQUESTIONS", "TOTALANSWERS", "AVERAGEREPUTATION", "TOTALUPVOTES", "TOTALDOWNVOTES", "POSTID", "TITLE", "CREATIONDATE", "COMMENTCOUNT", "RELATEDPOSTLINKS", "CLOSEDDATE", "REOPENEDDATE", CASE WHEN "CLOSEDDATE" IS NOT NULL THEN 'Closed  ' WHEN "REOPENEDDATE" IS NOT NULL THEN 'Reopened' ELSE 'Active  ' END AS "POSTSTATUS"
FROM (SELECT *
FROM (SELECT ANY_VALUE("Users"."Id") AS "USERID", "Users"."DisplayName" AS "DISPLAYNAME", COUNT(DISTINCT "Posts"."Id") AS "TOTALPOSTS", SUM(CASE WHEN CAST("Posts"."PostTypeId" AS INTEGER) = 1 THEN 1 ELSE 0 END) AS "TOTALQUESTIONS", SUM(CASE WHEN CAST("Posts"."PostTypeId" AS INTEGER) = 2 THEN 1 ELSE 0 END) AS "TOTALANSWERS", AVG("Users"."Reputation") AS "AVERAGEREPUTATION", SUM(CASE WHEN CAST("Votes"."VoteTypeId" AS INTEGER) = 2 THEN 1 ELSE 0 END) AS "TOTALUPVOTES", SUM(CASE WHEN CAST("Votes"."VoteTypeId" AS INTEGER) = 3 THEN 1 ELSE 0 END) AS "TOTALDOWNVOTES"
FROM "STACK"."Users"
LEFT JOIN "STACK"."Posts" ON "Users"."Id" = "Posts"."OwnerUserId"
LEFT JOIN "STACK"."Votes" ON "Posts"."Id" = "Votes"."PostId"
GROUP BY "Users"."Id", "Users"."DisplayName") AS "t1"
INNER JOIN (SELECT ANY_VALUE("Posts0"."Id") AS "POSTID", "Posts0"."Title" AS "TITLE", "Posts0"."CreationDate" AS "CREATIONDATE", COUNT("Comments"."Id") AS "COMMENTCOUNT", COUNT("PostLinks"."RelatedPostId") AS "RELATEDPOSTLINKS", MAX(CASE WHEN CAST("PostHistory"."PostHistoryTypeId" AS INTEGER) = 10 THEN "PostHistory"."CreationDate" ELSE NULL END) AS "CLOSEDDATE", MAX(CASE WHEN CAST("PostHistory"."PostHistoryTypeId" AS INTEGER) = 11 THEN "PostHistory"."CreationDate" ELSE NULL END) AS "REOPENEDDATE"
FROM "STACK"."Posts" AS "Posts0"
LEFT JOIN "STACK"."Comments" ON "Posts0"."Id" = "Comments"."PostId"
LEFT JOIN "STACK"."PostLinks" ON "Posts0"."Id" = "PostLinks"."PostId"
LEFT JOIN "STACK"."PostHistory" ON "Posts0"."Id" = "PostHistory"."PostId"
GROUP BY "Posts0"."Id", "Posts0"."Title", "Posts0"."CreationDate") AS "t4" ON "t1"."USERID" = "t4"."POSTID") AS "t5"
WHERE "t5"."AVERAGEREPUTATION" > 100