SELECT COALESCE("POSTID", "POSTID") AS "POSTID", "TITLE", "SCORE", "OWNERDISPLAYNAME", "CREATIONDATE", "COMMENTCOUNT", "ENGAGEMENTLEVEL", "UPVOTES", "DOWNVOTES"
FROM "s1"
ORDER BY "SCORE" DESC NULLS FIRST, "COMMENTCOUNT" DESC NULLS FIRST
FETCH NEXT 50 ROWS ONLY