SELECT COALESCE("DISPLAYNAME", "DISPLAYNAME") AS "DISPLAYNAME", "REPUTATION", "BADGECOUNT", "POSTCOUNT", "QUESTIONCOUNT", "ANSWERCOUNT", "TOTALVIEWS", "EDITCOUNT", "TITLEANDBODYEDITS"
FROM "s1"
ORDER BY "BADGECOUNT" DESC NULLS FIRST, "TOTALVIEWS" DESC NULLS FIRST
FETCH NEXT 100 ROWS ONLY