SELECT COALESCE("t2"."USERID", "t2"."USERID") AS "USERID", "t2"."DISPLAYNAME", "t2"."TOTALPOSTS", "t2"."TOTALCOMMENTS", "t2"."TOTALUPVOTES", "t2"."TOTALDOWNVOTES", "t2"."GOLDBADGES", "t2"."SILVERBADGES", "t2"."BRONZEBADGES", "t4"."QUESTIONS", "t4"."ANSWERS", "t4"."AVERAGESCORE", "t4"."TOTALVIEWS", "t4"."UNIQUETAGS"
FROM (SELECT ANY_VALUE("Id") AS "USERID", "DISPLAYNAME", COUNT(DISTINCT "Id0") AS "TOTALPOSTS", COUNT(DISTINCT "Id1") AS "TOTALCOMMENTS", SUM("FD_COL_4") AS "TOTALUPVOTES", SUM("FD_COL_5") AS "TOTALDOWNVOTES", SUM("FD_COL_6") AS "GOLDBADGES", SUM("FD_COL_7") AS "SILVERBADGES", SUM("FD_COL_8") AS "BRONZEBADGES"
FROM "s1"
GROUP BY "Id", "DISPLAYNAME") AS "t2"
LEFT JOIN (SELECT "OwnerUserId" AS "OWNERUSERID", COUNT(CASE WHEN CAST("PostTypeId" AS INTEGER) = 1 THEN 1 ELSE NULL END) AS "QUESTIONS", COUNT(CASE WHEN CAST("PostTypeId" AS INTEGER) = 2 THEN 1 ELSE NULL END) AS "ANSWERS", AVG("Score") AS "AVERAGESCORE", SUM("ViewCount") AS "TOTALVIEWS", COUNT(DISTINCT "Tags") AS "UNIQUETAGS"
FROM "STACK"."Posts"
GROUP BY "OwnerUserId") AS "t4" ON "t2"."USERID" = "t4"."OWNERUSERID"
ORDER BY "t2"."TOTALPOSTS" DESC NULLS FIRST, "t2"."TOTALUPVOTES" DESC NULLS FIRST, "t4"."AVERAGESCORE" DESC NULLS FIRST
FETCH NEXT 100 ROWS ONLY