SELECT COALESCE("DISPLAYNAME", "DISPLAYNAME") AS "DISPLAYNAME", "REPUTATION", "LASTACCESSDATE", "ENGAGEMENTSCORE", "BADGECOUNT", "GOLDBADGES", "SILVERBADGES", "BRONZEBADGES", "POSTCOUNT", "QUESTIONCOUNT", "ANSWERCOUNT", "WIKICOUNT", "TOTALSCORE", "AVGVIEWCOUNT"
FROM (SELECT "DisplayName" AS "DISPLAYNAME", "Reputation" AS "REPUTATION", "LastAccessDate" AS "LASTACCESSDATE", "Views" + "UpVotes" - "DownVotes" AS "ENGAGEMENTSCORE", "BADGECOUNT", "GOLDBADGES", "SILVERBADGES", "BRONZEBADGES", "POSTCOUNT", "QUESTIONCOUNT", "ANSWERCOUNT", "WIKICOUNT", "TOTALSCORE", "AVGVIEWCOUNT"
FROM "s1"
WHERE "Reputation" > 100 AND "LastAccessDate" > (CAST('2024-10-01 12:34:56' AS TIMESTAMP(0)) - INTERVAL '1' YEAR)
ORDER BY 4 DESC NULLS FIRST, "Reputation" DESC NULLS FIRST
FETCH NEXT 100 ROWS ONLY) AS "t7"