SELECT COALESCE("USERID", "USERID") AS "USERID", "DISPLAYNAME", "POSTCOUNT", "QUESTIONCOUNT", "ANSWERCOUNT", "TOTALBADGES", "GOLDBADGES", "SILVERBADGES", "BRONZEBADGES", "UPVOTES", "DOWNVOTES"
FROM "s1"
ORDER BY "UPVOTES" DESC NULLS FIRST, "DOWNVOTES"
FETCH NEXT 100 ROWS ONLY