SELECT COALESCE("USERID", "USERID") AS "USERID", "DISPLAYNAME", "TOTALBADGES", "TOTALPOSTS", "TOTALQUESTIONS", "TOTALANSWERS", "TOTALTAGWIKIS", "POSITIVEPOSTS", "CONTRIBUTORSTATUS"
FROM "s1"
ORDER BY "TOTALPOSTS" DESC NULLS FIRST, "TOTALBADGES" DESC NULLS FIRST
FETCH NEXT 50 ROWS ONLY