SELECT COALESCE("OwnerUserId", "OwnerUserId") AS "OWNERUSERID", CASE WHEN CAST("PostTypeId" AS INTEGER) = 1 THEN 1 ELSE 0 END AS "FD_COL_1", CASE WHEN CAST("PostTypeId" AS INTEGER) = 2 THEN 1 ELSE 0 END AS "FD_COL_2", "ViewCount", "Score"
FROM "STACK"."Posts"
WHERE "CreationDate" >= (CAST('2024-10-01 12:34:56' AS TIMESTAMP(0)) - INTERVAL '1' YEAR)