SELECT COALESCE("Users0"."DisplayName", "Users0"."DisplayName") AS "DISPLAYNAME", "t6"."TOTALBADGES", "t6"."GOLDBADGES", "t6"."SILVERBADGES", "t6"."BRONZEBADGES", "t6"."TOTALPOSTS", "t6"."QUESTIONS", "t6"."ANSWERS", "t6"."TOTALVIEWS", "t6"."TOTALSCORE"
FROM (SELECT "t4"."USERID", "t4"."TOTALBADGES", "t4"."GOLDBADGES", "t4"."SILVERBADGES", "t4"."BRONZEBADGES", "t5"."TOTALPOSTS", "t5"."QUESTIONS", "t5"."ANSWERS", "t5"."TOTALVIEWS", "t5"."TOTALSCORE"
FROM (SELECT ANY_VALUE("Users"."Id") AS "USERID", COUNT("Badges"."Id") AS "TOTALBADGES", SUM(CASE WHEN CAST("Badges"."Class" AS INTEGER) = 1 THEN 1 ELSE 0 END) AS "GOLDBADGES", SUM(CASE WHEN CAST("Badges"."Class" AS INTEGER) = 2 THEN 1 ELSE 0 END) AS "SILVERBADGES", SUM(CASE WHEN CAST("Badges"."Class" AS INTEGER) = 3 THEN 1 ELSE 0 END) AS "BRONZEBADGES"
FROM "STACK"."Users"
LEFT JOIN "STACK"."Badges" ON "Users"."Id" = "Badges"."UserId"
GROUP BY "Users"."Id") AS "t4"
LEFT JOIN (SELECT "OWNERUSERID", COUNT(*) AS "TOTALPOSTS", SUM("FD_COL_1") AS "QUESTIONS", SUM("FD_COL_2") AS "ANSWERS", SUM("ViewCount") AS "TOTALVIEWS", SUM("Score") AS "TOTALSCORE"
FROM "s1"
GROUP BY "OWNERUSERID") AS "t5" ON "t4"."USERID" = "t5"."OWNERUSERID") AS "t6"
INNER JOIN "STACK"."Users" AS "Users0" ON "t6"."USERID" = "Users0"."Id"
WHERE "t6"."TOTALPOSTS" > 5
ORDER BY "t6"."TOTALSCORE" DESC NULLS FIRST, "t6"."TOTALBADGES" DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY