SELECT COALESCE("t5"."USERID", "t5"."USERID") AS "USERID", "t5"."DISPLAYNAME", "t5"."POSTCOUNT", "t5"."QUESTIONS", "t5"."ANSWERS", "t5"."CLOSEDPOSTS", "t5"."AVGREPUTATION", "t5"."NETVOTES", "Badges"."Name" AS "BADGENAME", "Badges"."Class" AS "CLASS"
FROM (SELECT "USERID", "DISPLAYNAME", "POSTCOUNT", "QUESTIONS", "ANSWERS", "CLOSEDPOSTS", "AVGREPUTATION", "UPVOTES" - "DOWNVOTES" AS "NETVOTES"
FROM (SELECT ANY_VALUE("Users"."Id") AS "USERID", "Users"."DisplayName" AS "DISPLAYNAME", COUNT(DISTINCT "Posts"."Id") AS "POSTCOUNT", SUM(CASE WHEN CAST("Posts"."PostTypeId" AS INTEGER) = 1 THEN 1 ELSE 0 END) AS "QUESTIONS", SUM(CASE WHEN CAST("Posts"."PostTypeId" AS INTEGER) = 2 THEN 1 ELSE 0 END) AS "ANSWERS", SUM(CASE WHEN CAST("Posts"."PostTypeId" AS INTEGER) IN (10, 11) THEN 1 ELSE 0 END) AS "CLOSEDPOSTS", AVG("Users"."Reputation") AS "AVGREPUTATION", SUM(CASE WHEN CAST("Votes"."VoteTypeId" AS INTEGER) = 2 THEN 1 ELSE 0 END) AS "UPVOTES", SUM(CASE WHEN CAST("Votes"."VoteTypeId" AS INTEGER) = 3 THEN 1 ELSE 0 END) AS "DOWNVOTES"
FROM "STACK"."Users"
LEFT JOIN "STACK"."Posts" ON "Users"."Id" = "Posts"."OwnerUserId"
LEFT JOIN "STACK"."Votes" ON "Posts"."Id" = "Votes"."PostId"
WHERE "Users"."CreationDate" < (CAST('2024-10-01 12:34:56' AS TIMESTAMP(0)) - INTERVAL '1' YEAR)
GROUP BY "Users"."Id", "Users"."DisplayName") AS "t2"
WHERE "t2"."POSTCOUNT" > 5
ORDER BY 8 DESC NULLS FIRST, "AVGREPUTATION" DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY) AS "t5"
LEFT JOIN "STACK"."Badges" ON "t5"."USERID" = "Badges"."UserId"