SELECT COALESCE("USERID", "USERID") AS "USERID", "DISPLAYNAME", "POSTCOUNT", "QUESTIONS", "ANSWERS", "CLOSEDPOSTS", "AVGREPUTATION", "NETVOTES", "BADGENAME", "CLASS"
FROM "s1"
ORDER BY "NETVOTES" DESC NULLS FIRST, "AVGREPUTATION" DESC NULLS FIRST