SELECT COALESCE("USERID", "USERID") AS "USERID", "DISPLAYNAME", "BADGECOUNT", "QUESTIONCOUNT", "ANSWERCOUNT", "TOTALVIEWS", "AVGSCORE", "PERFORMANCESCORE"
FROM "s1"
ORDER BY "AVGSCORE" DESC NULLS FIRST, "TOTALVIEWS" DESC NULLS FIRST