SELECT COALESCE("DISPLAYNAME", "DISPLAYNAME") AS "DISPLAYNAME", "BADGECOUNT", "GOLDCOUNT", "SILVERCOUNT", "BRONZECOUNT", "POSTCOUNT", "QUESTIONCOUNT", "ANSWERCOUNT", "TOTALSCORE", "AVGVIEWCOUNT"
FROM "s1"
ORDER BY "TOTALSCORE" DESC NULLS FIRST, "BADGECOUNT" DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY