SELECT COALESCE("USERID", "USERID") AS "USERID", "DISPLAYNAME", "REPUTATION", "TOTALVOTES", "UPVOTES", "DOWNVOTES", "TOTALBADGES", "GOLDBADGES", "SILVERBADGES", "BRONZEBADGES", "TOTALPOSTS", "QUESTIONS", "ANSWERS", "TOTALVIEWS", "TOTALSCORE"
FROM "s1"
ORDER BY "REPUTATION" DESC NULLS FIRST
FETCH NEXT 50 ROWS ONLY