SELECT COALESCE("USERID", "USERID") AS "USERID", "DISPLAYNAME", "BADGECOUNT", "GOLDBADGECOUNT", "SILVERBADGECOUNT", "BRONZEBADGECOUNT", "QUESTIONCOUNT", "ANSWERCOUNT", "TOTALSCORE", "TOTALVIEWS"
FROM "s1"
ORDER BY "TOTALSCORE" DESC NULLS FIRST, "BADGECOUNT" DESC NULLS FIRST, "DISPLAYNAME"
FETCH NEXT 100 ROWS ONLY