SELECT COALESCE("USERID", "USERID") AS "USERID", "DISPLAYNAME", "TOTALPOSTS", "TOTALQUESTIONS", "TOTALANSWERS", "TOTALSCORE", "AVGVIEWS", "TOTALCOMMENTS", "LASTCOMMENTDATE", "LASTPOSTDATE"
FROM "s1"
ORDER BY "TOTALSCORE" DESC NULLS FIRST, "LASTPOSTDATE" DESC NULLS FIRST