SELECT COALESCE("t1"."POSTID", "t1"."POSTID") AS "POSTID", "t1"."TITLE", "t1"."CREATIONDATE", "t1"."SCORE", "t1"."VIEWCOUNT", "t1"."OWNERDISPLAYNAME", "t1"."COMMENTCOUNT", "t3"."VOTECOUNT", "t3"."UPVOTECOUNT", "t3"."DOWNVOTECOUNT", "t1"."BADGECOUNT"
FROM (SELECT ANY_VALUE("Posts"."Id") AS "POSTID", "Posts"."Title" AS "TITLE", "Posts"."CreationDate" AS "CREATIONDATE", "Posts"."Score" AS "SCORE", "Posts"."ViewCount" AS "VIEWCOUNT", ANY_VALUE("Users"."DisplayName") AS "OWNERDISPLAYNAME", COUNT("Comments"."Id") AS "COMMENTCOUNT", COUNT(DISTINCT "Badges"."Id") AS "BADGECOUNT"
FROM "STACK"."Posts"
LEFT JOIN "STACK"."Users" ON "Posts"."OwnerUserId" = "Users"."Id"
LEFT JOIN "STACK"."Comments" ON "Posts"."Id" = "Comments"."PostId"
LEFT JOIN "STACK"."Badges" ON "Users"."Id" = "Badges"."UserId"
GROUP BY "Posts"."Id", "Posts"."Title", "Posts"."CreationDate", "Posts"."Score", "Posts"."ViewCount", "Users"."DisplayName") AS "t1"
LEFT JOIN (SELECT "PostId" AS "POSTID", COUNT(*) AS "VOTECOUNT", SUM(CASE WHEN CAST("VoteTypeId" AS INTEGER) = 2 THEN 1 ELSE 0 END) AS "UPVOTECOUNT", SUM(CASE WHEN CAST("VoteTypeId" AS INTEGER) = 3 THEN 1 ELSE 0 END) AS "DOWNVOTECOUNT"
FROM "STACK"."Votes"
GROUP BY "PostId") AS "t3" ON "t1"."POSTID" = "t3"."POSTID"