SELECT COALESCE("s1"."Id", "s1"."Id") AS "USERID", "s1"."DisplayName" AS "DISPLAYNAME", CASE WHEN "s1"."POSTCOUNT" IS NOT NULL THEN CAST("s1"."POSTCOUNT" AS BIGINT) ELSE 0 END AS "POSTCOUNT", CASE WHEN "s1"."QUESTIONCOUNT" IS NOT NULL THEN CAST("s1"."QUESTIONCOUNT" AS INTEGER) ELSE 0 END AS "QUESTIONCOUNT", CASE WHEN "s1"."ANSWERCOUNT" IS NOT NULL THEN CAST("s1"."ANSWERCOUNT" AS INTEGER) ELSE 0 END AS "ANSWERCOUNT", CASE WHEN "t4"."VOTECOUNT" IS NOT NULL THEN CAST("t4"."VOTECOUNT" AS BIGINT) ELSE 0 END AS "VOTECOUNT", CASE WHEN "t4"."UPVOTES" IS NOT NULL THEN CAST("t4"."UPVOTES" AS INTEGER) ELSE 0 END AS "UPVOTES", CASE WHEN "t4"."DOWNVOTES" IS NOT NULL THEN CAST("t4"."DOWNVOTES" AS INTEGER) ELSE 0 END AS "DOWNVOTES", "s1"."Reputation"
FROM "s1"
LEFT JOIN (SELECT "Votes"."UserId" AS "USERID", COUNT(*) AS "VOTECOUNT", SUM(CASE WHEN "VoteTypes"."Name" = 'UpMod' THEN 1 ELSE 0 END) AS "UPVOTES", SUM(CASE WHEN "VoteTypes"."Name" = 'DownMod' THEN 1 ELSE 0 END) AS "DOWNVOTES"
FROM "STACK"."Votes"
INNER JOIN "STACK"."VoteTypes" ON "Votes"."VoteTypeId" = "VoteTypes"."Id"
GROUP BY "Votes"."UserId") AS "t4" ON "s1"."Id" = "t4"."USERID"
ORDER BY "s1"."Reputation" DESC NULLS FIRST
FETCH NEXT 100 ROWS ONLY