SELECT COALESCE("POSTID", "POSTID") AS "POSTID", "TITLE", "POSTCREATIONDATE", "SCORE", "VIEWCOUNT", "OWNERDISPLAYNAME", "OWNERREPUTATION", "COMMENTCOUNT", "UPVOTECOUNT", "DOWNVOTECOUNT", "POSTTAG", "POSTTYPENAME", "CreationDate"
FROM "s1"
ORDER BY "CreationDate" DESC NULLS FIRST
FETCH NEXT 100 ROWS ONLY