SELECT COALESCE("TITLE", "TITLE") AS "TITLE", "TOTALPOSTS", "TOTALUPVOTES", "TOTALDOWNVOTES", "TOTALCLOSEDPOSTS"
FROM (SELECT "Posts0"."Id" AS "POSTID", "Posts0"."Title" AS "TITLE", CASE WHEN "t4"."POSTCOUNT" IS NOT NULL THEN CAST("t4"."POSTCOUNT" AS BIGINT) ELSE 0 END AS "TOTALPOSTS", CASE WHEN "t7"."UPVOTECOUNT" IS NOT NULL THEN CAST("t7"."UPVOTECOUNT" AS INTEGER) ELSE 0 END AS "TOTALUPVOTES", CASE WHEN "t7"."DOWNVOTECOUNT" IS NOT NULL THEN CAST("t7"."DOWNVOTECOUNT" AS INTEGER) ELSE 0 END AS "TOTALDOWNVOTES", CASE WHEN "s1"."CLOSEDPOSTCOUNT" IS NOT NULL THEN CAST("s1"."CLOSEDPOSTCOUNT" AS INTEGER) ELSE 0 END AS "TOTALCLOSEDPOSTS"
FROM "STACK"."Posts" AS "Posts0"
LEFT JOIN (SELECT "Id" AS "ID", COUNT(*) AS "POSTCOUNT"
FROM "STACK"."Posts"
WHERE CAST("PostTypeId" AS INTEGER) = 1 OR CAST("PostTypeId" AS INTEGER) = 2
GROUP BY "Id") AS "t4" ON "Posts0"."Id" = "t4"."ID"
LEFT JOIN (SELECT ANY_VALUE("Users"."Id") AS "USERID", "Users"."DisplayName" AS "DISPLAYNAME", SUM(CASE WHEN CAST("Votes"."VoteTypeId" AS INTEGER) = 2 THEN 1 ELSE 0 END) AS "UPVOTECOUNT", SUM(CASE WHEN CAST("Votes"."VoteTypeId" AS INTEGER) = 3 THEN 1 ELSE 0 END) AS "DOWNVOTECOUNT"
FROM "STACK"."Users"
LEFT JOIN "STACK"."Votes" ON "Users"."Id" = "Votes"."UserId"
GROUP BY "Users"."Id", "Users"."DisplayName") AS "t7" ON "Posts0"."OwnerUserId" = "t7"."USERID"
LEFT JOIN "s1" ON "Posts0"."Tags" LIKE '%' || "s1"."TAGNAME" || '%') AS "t8"
WHERE "t8"."TOTALPOSTS" > 1
ORDER BY "TOTALPOSTS" DESC NULLS FIRST, "TOTALUPVOTES" DESC NULLS FIRST, "TOTALDOWNVOTES"
FETCH NEXT 10 ROWS ONLY