SELECT COALESCE("OwnerUserId", "OwnerUserId") AS "OWNERUSERID", COUNT(*) AS "POSTCOUNT", SUM("ViewCount") AS "TOTALVIEWS", AVG("Score") AS "AVERAGESCORE"
FROM "STACK"."Posts"
WHERE "CreationDate" >= (TIMESTAMP '2024-10-01 12:34:56' - INTERVAL '1' YEAR)
GROUP BY "OwnerUserId"