SELECT COALESCE("s1"."USERID", "s1"."USERID") AS "USERID", "s1"."DISPLAYNAME", "s1"."TOTALPOSTS", "s1"."QUESTIONCOUNT", "s1"."ANSWERCOUNT", "s1"."TOTALVIEWS", "s1"."TOTALSCORE", "s1"."GOLDBADGES", "s1"."SILVERBADGES", "s1"."BRONZEBADGES", "t6"."CLOSEREOPENCOUNT", "t6"."EDITSUGGESTIONCOUNT", "s1"."LASTPOSTDATE"
FROM "s1"
LEFT JOIN (SELECT "UserId" AS "USERID", COUNT(CASE WHEN CAST("PostHistoryTypeId" AS INTEGER) IN (10, 11) THEN 1 ELSE NULL END) AS "CLOSEREOPENCOUNT", COUNT(CASE WHEN CAST("PostHistoryTypeId" AS INTEGER) IN (24, 25) THEN 1 ELSE NULL END) AS "EDITSUGGESTIONCOUNT"
FROM "STACK"."PostHistory"
GROUP BY "UserId") AS "t6" ON "s1"."USERID" = "t6"."USERID"
WHERE "s1"."TOTALPOSTS" > 0
ORDER BY "s1"."TOTALSCORE" DESC NULLS FIRST, "s1"."LASTPOSTDATE" DESC NULLS FIRST
FETCH NEXT 100 ROWS ONLY