SELECT COALESCE("OwnerUserId", "OwnerUserId") AS "OWNERUSERID", COUNT(*) AS "POSTCOUNT", SUM(CASE WHEN "Score" > 0 THEN 1 ELSE 0 END) AS "SCOREPOSITIVE", SUM(CASE WHEN CAST("PostTypeId" AS INTEGER) = 1 THEN 1 ELSE 0 END) AS "QUESTIONS", SUM(CASE WHEN CAST("PostTypeId" AS INTEGER) = 2 THEN 1 ELSE 0 END) AS "ANSWERS"
FROM "STACK"."Posts"
WHERE "CreationDate" >= CAST((CAST('2024-10-01' AS DATE) - INTERVAL '1' YEAR) AS TIMESTAMP(0))
GROUP BY "OwnerUserId"