SELECT COALESCE("t5"."USERID", "t5"."USERID") AS "USERID", "t5"."DISPLAYNAME", "t5"."BADGECOUNT", "t5"."GOLDBADGES", "t5"."SILVERBADGES", "t5"."BRONZEBADGES", "s1"."POSTCOUNT", "s1"."SCOREPOSITIVE", "s1"."QUESTIONS", "s1"."ANSWERS"
FROM (SELECT ANY_VALUE("Users"."Id") AS "USERID", "Users"."DisplayName" AS "DISPLAYNAME", COUNT("Badges"."Id") AS "BADGECOUNT", SUM(CASE WHEN CAST("Badges"."Class" AS INTEGER) = 1 THEN 1 ELSE 0 END) AS "GOLDBADGES", SUM(CASE WHEN CAST("Badges"."Class" AS INTEGER) = 2 THEN 1 ELSE 0 END) AS "SILVERBADGES", SUM(CASE WHEN CAST("Badges"."Class" AS INTEGER) = 3 THEN 1 ELSE 0 END) AS "BRONZEBADGES"
FROM "STACK"."Users"
LEFT JOIN "STACK"."Badges" ON "Users"."Id" = "Badges"."UserId"
GROUP BY "Users"."Id", "Users"."DisplayName") AS "t5"
LEFT JOIN "s1" ON "t5"."USERID" = "s1"."OWNERUSERID"
ORDER BY "t5"."BADGECOUNT" DESC NULLS FIRST, "s1"."SCOREPOSITIVE" DESC NULLS FIRST, "s1"."POSTCOUNT" DESC NULLS FIRST
FETCH NEXT 100 ROWS ONLY