SELECT COALESCE("USERID", "USERID") AS "USERID", "DISPLAYNAME", "REPUTATION", "TOTALPOSTS", "TOTALSCORE", "TOTALCOMMENTS", "TOTALCLOSED", "TOTALREOPENED"
FROM (SELECT ANY_VALUE("Users"."Id") AS "USERID", "Users"."DisplayName" AS "DISPLAYNAME", "Users"."Reputation" AS "REPUTATION", "t4"."UPVOTES", "t4"."DOWNVOTES", "t4"."REPUTATIONCHANGE", COUNT(DISTINCT "s1"."POSTID") AS "TOTALPOSTS", SUM("s1"."SCORE") AS "TOTALSCORE", CASE WHEN SUM("s1"."COMMENTCOUNT") IS NOT NULL THEN CAST(SUM("s1"."COMMENTCOUNT") AS INTEGER) ELSE 0 END AS "TOTALCOMMENTS", CASE WHEN SUM("s1"."CLOSEDCOUNT") IS NOT NULL THEN CAST(SUM("s1"."CLOSEDCOUNT") AS INTEGER) ELSE 0 END AS "TOTALCLOSED", CASE WHEN SUM("s1"."REOPENEDCOUNT") IS NOT NULL THEN CAST(SUM("s1"."REOPENEDCOUNT") AS INTEGER) ELSE 0 END AS "TOTALREOPENED"
FROM "STACK"."Users"
LEFT JOIN (SELECT "UserId" AS "USERID", SUM(CASE WHEN CAST("VoteTypeId" AS INTEGER) = 2 THEN 1 ELSE 0 END) AS "UPVOTES", SUM(CASE WHEN CAST("VoteTypeId" AS INTEGER) = 3 THEN 1 ELSE 0 END) AS "DOWNVOTES", SUM(CASE WHEN CAST("VoteTypeId" AS INTEGER) = 2 THEN 1 ELSE -1 END) AS "REPUTATIONCHANGE"
FROM "STACK"."Votes"
GROUP BY "UserId") AS "t4" ON "Users"."Id" = "t4"."USERID"
LEFT JOIN "s1" ON "Users"."Id" = "s1"."OWNERUSERID"
GROUP BY "Users"."Id", "Users"."DisplayName", "Users"."Reputation", "t4"."UPVOTES", "t4"."DOWNVOTES", "t4"."REPUTATIONCHANGE") AS "t7"
WHERE "t7"."REPUTATION" > 1000
ORDER BY "REPUTATION" DESC NULLS FIRST, "TOTALSCORE" DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY