SELECT COALESCE("Users0"."DisplayName", "Users0"."DisplayName") AS "DISPLAYNAME", "t6"."TOTALBADGES", "t6"."GOLDBADGES", "t6"."SILVERBADGES", "t6"."BRONZEBADGES", "t6"."TOTALPOSTS", "t6"."QUESTIONS", "t6"."ANSWERS", "t6"."TOTALVIEWS", "t6"."TOTALSCORE"
FROM (SELECT "t5"."USERID", "t5"."TOTALBADGES", "t5"."GOLDBADGES", "t5"."SILVERBADGES", "t5"."BRONZEBADGES", "s1"."TOTALPOSTS", "s1"."QUESTIONS", "s1"."ANSWERS", "s1"."TOTALVIEWS", "s1"."TOTALSCORE"
FROM (SELECT ANY_VALUE("Users"."Id") AS "USERID", COUNT("Badges"."Id") AS "TOTALBADGES", SUM(CASE WHEN CAST("Badges"."Class" AS INTEGER) = 1 THEN 1 ELSE 0 END) AS "GOLDBADGES", SUM(CASE WHEN CAST("Badges"."Class" AS INTEGER) = 2 THEN 1 ELSE 0 END) AS "SILVERBADGES", SUM(CASE WHEN CAST("Badges"."Class" AS INTEGER) = 3 THEN 1 ELSE 0 END) AS "BRONZEBADGES"
FROM "STACK"."Users"
LEFT JOIN "STACK"."Badges" ON "Users"."Id" = "Badges"."UserId"
GROUP BY "Users"."Id") AS "t5"
LEFT JOIN "s1" ON "t5"."USERID" = "s1"."OWNERUSERID") AS "t6"
INNER JOIN "STACK"."Users" AS "Users0" ON "t6"."USERID" = "Users0"."Id"
WHERE "t6"."TOTALPOSTS" > 5
ORDER BY "t6"."TOTALSCORE" DESC NULLS FIRST, "t6"."TOTALBADGES" DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY