SELECT COALESCE("L_ORDERKEY", "L_ORDERKEY") AS "L_ORDERKEY", "TOTAL_REVENUE"
FROM (SELECT "L_ORDERKEY", SUM("FD_COL_1") AS "TOTAL_REVENUE"
FROM "s1"
GROUP BY "L_ORDERKEY"
ORDER BY 2 DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY) AS "t4"