SELECT COALESCE("t2"."N_NAME", "t2"."N_NAME") AS "N_NAME", "t2"."TOTAL_REVENUE"
FROM (SELECT "nation"."n_name" AS "N_NAME", SUM("lineitem"."l_extendedprice" * (1 - "lineitem"."l_discount")) AS "TOTAL_REVENUE"
FROM "TPCH"."nation"
INNER JOIN "TPCH"."supplier" ON "nation"."n_nationkey" = "supplier"."s_nationkey"
INNER JOIN ("TPCH"."lineitem" INNER JOIN "s1" ON "lineitem"."l_partkey" = "s1"."p_partkey") ON "supplier"."s_suppkey" = "s1"."ps_suppkey"
GROUP BY "nation"."n_name"
ORDER BY 2 DESC NULLS FIRST) AS "t2"