SELECT COALESCE("p_name", "p_name") AS "p_name", "TOTAL_AVAILABLE_QUANTITY", "AVERAGE_SUPPLY_COST", "TOTAL_SUPPLIERS"
FROM (SELECT "p_name", SUM("ps_availqty") AS "TOTAL_AVAILABLE_QUANTITY", AVG("ps_supplycost") AS "AVERAGE_SUPPLY_COST", COUNT(DISTINCT "s_suppkey") AS "TOTAL_SUPPLIERS"
FROM "s1"
GROUP BY "p_name"
ORDER BY 2 DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY) AS "t1"