SELECT COALESCE("S_NAME", "S_NAME") AS "S_NAME", "TOTAL_COST"
FROM (SELECT "S_NAME", SUM("FD_COL_1") AS "TOTAL_COST"
FROM "s1"
GROUP BY "S_NAME"
ORDER BY 2 DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY) AS "t3"