SELECT COALESCE("NATION", "NATION") AS "NATION", "TOTAL_COST"
FROM (SELECT "n_name", ANY_VALUE("n_name") AS "NATION", SUM("FD_COL_1") AS "TOTAL_COST"
FROM "s1"
GROUP BY "n_name"
ORDER BY 3 DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY) AS "t2"