SELECT COALESCE("P_PARTKEY", "P_PARTKEY") AS "P_PARTKEY", "P_NAME", "REVENUE"
FROM (SELECT "P_PARTKEY", "P_NAME", SUM("FD_COL_2") AS "REVENUE"
FROM "s1"
GROUP BY "P_PARTKEY", "P_NAME"
ORDER BY 3 DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY) AS "t4"