SELECT COALESCE("NATION", "NATION") AS "NATION", "REGION", "SUPPLIER_COUNT", "TOTAL_AVAILABILITY", "AVERAGE_SUPPLY_COST"
FROM (SELECT "NATION", "REGION", "SUPPLIER_COUNT", "TOTAL_AVAILABILITY", "AVERAGE_SUPPLY_COST"
FROM "s1"
ORDER BY "REGION", "NATION") AS "t3"