SELECT COALESCE("P_BRAND", "P_BRAND") AS "P_BRAND", "P_TYPE", "AVG_PRICE", "ORDER_COUNT"
FROM (SELECT "P_BRAND", "P_TYPE", AVG("FD_COL_2") AS "AVG_PRICE", COUNT(DISTINCT "o_orderkey") AS "ORDER_COUNT"
FROM "s1"
GROUP BY "P_BRAND", "P_TYPE"
ORDER BY 3 DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY) AS "t3"