SELECT COALESCE("t19"."r_name", "t19"."r_name") AS "R_NAME", "t19"."TOTAL_SUPPLIER_COST", "t19"."AVERAGE_CUSTOMER_SPENT", "t19"."CUSTOMER_COUNT"
FROM (SELECT "t16"."r_name", SUM("t16"."TOTAL_SUPPLY_COST") AS "TOTAL_SUPPLIER_COST", AVG("t6"."TOTAL_SPENT") AS "AVERAGE_CUSTOMER_SPENT", COUNT(DISTINCT "t6"."C_CUSTKEY") AS "CUSTOMER_COUNT", COUNT(DISTINCT "t16"."S_SUPPKEY") AS "$f4"
FROM (SELECT "t1"."c_custkey" AS "C_CUSTKEY", "t1"."c_name" AS "C_NAME", SUM("t4"."TOTAL_DISCOUNTED_PRICE") AS "TOTAL_SPENT", RANK() OVER (ORDER BY SUM("t4"."TOTAL_DISCOUNTED_PRICE") DESC NULLS FIRST) AS "SPEND_RANK"
FROM (SELECT "customer"."c_custkey", "customer"."c_name", "customer"."c_address", "customer"."c_nationkey", "customer"."c_phone", "customer"."c_acctbal", "customer"."c_mktsegment", "customer"."c_comment", "orders"."o_orderkey", "orders"."o_custkey", "orders"."o_orderstatus", "orders"."o_totalprice", "orders"."o_orderdate", "orders"."o_orderpriority", "orders"."o_clerk", "orders"."o_shippriority", "orders"."o_comment"
FROM "TPCH"."orders"
RIGHT JOIN "TPCH"."customer" ON "orders"."o_custkey" = "customer"."c_custkey") AS "t1"
LEFT JOIN (SELECT "t2"."o_orderkey" AS "O_ORDERKEY", "t2"."o_orderdate" AS "O_ORDERDATE", SUM("lineitem"."l_extendedprice" * (1 - "lineitem"."l_discount")) AS "TOTAL_DISCOUNTED_PRICE"
FROM (SELECT *
FROM "TPCH"."orders"
WHERE "o_orderdate" >= DATE '1997-01-01') AS "t2"
INNER JOIN "TPCH"."lineitem" ON "t2"."o_orderkey" = "lineitem"."l_orderkey"
GROUP BY "t2"."o_orderkey", "t2"."o_orderdate") AS "t4" ON "t1"."o_orderkey" = "t4"."O_ORDERKEY"
GROUP BY "t1"."c_custkey", "t1"."c_name") AS "t6"
RIGHT JOIN (SELECT "t15"."r_regionkey", "t15"."r_name", "t15"."r_comment", "t15"."n_nationkey", "t15"."n_name", "t15"."n_regionkey", "t15"."n_comment", "t15"."s_suppkey", "t15"."s_name", "t15"."s_address", "t15"."s_nationkey", "t15"."s_phone", "t15"."s_acctbal", "t15"."s_comment", "t15"."S_SUPPKEY", "t15"."S_NAME", "t15"."TOTAL_SUPPLY_COST", "t15"."UNIQUE_PARTS", "t11"."c_custkey" AS "C_CUSTKEY", "t11"."c_name" AS "C_NAME", "t11"."TOTAL_SPENT"
FROM (SELECT "t7"."c_custkey", "t7"."c_name", SUM("t10"."TOTAL_DISCOUNTED_PRICE") AS "TOTAL_SPENT"
FROM (SELECT "customer0"."c_custkey", "customer0"."c_name", "customer0"."c_address", "customer0"."c_nationkey", "customer0"."c_phone", "customer0"."c_acctbal", "customer0"."c_mktsegment", "customer0"."c_comment", "orders1"."o_orderkey", "orders1"."o_custkey", "orders1"."o_orderstatus", "orders1"."o_totalprice", "orders1"."o_orderdate", "orders1"."o_orderpriority", "orders1"."o_clerk", "orders1"."o_shippriority", "orders1"."o_comment"
FROM "TPCH"."orders" AS "orders1"
RIGHT JOIN "TPCH"."customer" AS "customer0" ON "orders1"."o_custkey" = "customer0"."c_custkey") AS "t7"
LEFT JOIN (SELECT "t8"."o_orderkey" AS "O_ORDERKEY", "t8"."o_orderdate" AS "O_ORDERDATE", SUM("lineitem0"."l_extendedprice" * (1 - "lineitem0"."l_discount")) AS "TOTAL_DISCOUNTED_PRICE"
FROM (SELECT *
FROM "TPCH"."orders"
WHERE "o_orderdate" >= DATE '1997-01-01') AS "t8"
INNER JOIN "TPCH"."lineitem" AS "lineitem0" ON "t8"."o_orderkey" = "lineitem0"."l_orderkey"
GROUP BY "t8"."o_orderkey", "t8"."o_orderdate") AS "t10" ON "t7"."o_orderkey" = "t10"."O_ORDERKEY"
GROUP BY "t7"."c_custkey", "t7"."c_name") AS "t11"
RIGHT JOIN (SELECT "t12"."r_regionkey", "t12"."r_name", "t12"."r_comment", "t12"."n_nationkey", "t12"."n_name", "t12"."n_regionkey", "t12"."n_comment", "t12"."s_suppkey", "t12"."s_name", "t12"."s_address", "t12"."s_nationkey", "t12"."s_phone", "t12"."s_acctbal", "t12"."s_comment", "t14"."S_SUPPKEY", "t14"."S_NAME", "t14"."TOTAL_SUPPLY_COST", "t14"."UNIQUE_PARTS", CAST("t12"."n_nationkey" AS BIGINT) AS "n_nationkey0"
FROM (SELECT "s1"."r_regionkey", "s1"."r_name", "s1"."r_comment", "s1"."n_nationkey", "s1"."n_name", "s1"."n_regionkey", "s1"."n_comment", "supplier"."s_suppkey", "supplier"."s_name", "supplier"."s_address", "supplier"."s_nationkey", "supplier"."s_phone", "supplier"."s_acctbal", "supplier"."s_comment"
FROM "TPCH"."supplier"
RIGHT JOIN "s1" ON "supplier"."s_nationkey" = "s1"."n_nationkey") AS "t12"
LEFT JOIN (SELECT "supplier0"."s_suppkey" AS "S_SUPPKEY", "supplier0"."s_name" AS "S_NAME", SUM("partsupp"."ps_supplycost" * "partsupp"."ps_availqty") AS "TOTAL_SUPPLY_COST", COUNT(DISTINCT "partsupp"."ps_partkey") AS "UNIQUE_PARTS"
FROM "TPCH"."supplier" AS "supplier0"
INNER JOIN "TPCH"."partsupp" ON "supplier0"."s_suppkey" = "partsupp"."ps_suppkey"
GROUP BY "supplier0"."s_suppkey", "supplier0"."s_name") AS "t14" ON "t12"."s_suppkey" = "t14"."S_SUPPKEY") AS "t15" ON "t11"."c_custkey" = "t15"."n_nationkey0") AS "t16" ON "t6"."C_CUSTKEY" = "t16"."C_CUSTKEY"
GROUP BY "t16"."r_name"
HAVING COUNT(DISTINCT "t16"."S_SUPPKEY") > 5 AND AVG("t6"."TOTAL_SPENT") IS NOT NULL
ORDER BY 2 DESC NULLS FIRST) AS "t19"