SELECT COALESCE("t10"."REGION", "t10"."REGION") AS "REGION", "t10"."TOTAL_SUPPLIERS", "t10"."TOTAL_SUPPLY_COST", "t10"."TOTAL_ORDER_PRICE", "t10"."AVG_ITEMS_PER_ORDER", "t10"."AVG_UNIQUE_PARTS_PER_SUPPLIER"
FROM (SELECT "t2"."R_NAME", ANY_VALUE("t2"."R_NAME") AS "REGION", COUNT(DISTINCT "t2"."s_suppkey") AS "TOTAL_SUPPLIERS", SUM(CASE WHEN "t3"."TOTAL_SUPPLY_COST" IS NOT NULL THEN CAST("t3"."TOTAL_SUPPLY_COST" AS DECIMAL(19, 2)) ELSE 0.00 END) AS "TOTAL_SUPPLY_COST", SUM(CASE WHEN "t6"."TOTAL_PRICE" IS NOT NULL THEN CAST("t6"."TOTAL_PRICE" AS DECIMAL(19, 4)) ELSE 0.0000 END) AS "TOTAL_ORDER_PRICE", AVG("t6"."NUMBER_OF_ITEMS") AS "AVG_ITEMS_PER_ORDER", AVG("t3"."UNIQUE_PARTS") AS "AVG_UNIQUE_PARTS_PER_SUPPLIER"
FROM (SELECT "t1"."N_NATIONKEY", "t1"."R_NAME", "t1"."N_NAME", "supplier0"."s_suppkey", "supplier0"."s_name", "supplier0"."s_address", "supplier0"."s_nationkey", "supplier0"."s_phone", "supplier0"."s_acctbal", "supplier0"."s_comment"
FROM "TPCH"."supplier" AS "supplier0"
RIGHT JOIN (SELECT "nation"."n_nationkey" AS "N_NATIONKEY", "region"."r_name" AS "R_NAME", "nation"."n_name" AS "N_NAME"
FROM "TPCH"."nation"
LEFT JOIN "TPCH"."region" ON "nation"."n_regionkey" = "region"."r_regionkey") AS "t1" ON "supplier0"."s_nationkey" = "t1"."N_NATIONKEY") AS "t2"
LEFT JOIN (SELECT "S_SUPPKEY", "S_NAME", SUM("FD_COL_2") AS "TOTAL_SUPPLY_COST", COUNT(DISTINCT "ps_partkey") AS "UNIQUE_PARTS"
FROM "s1"
GROUP BY "S_SUPPKEY", "S_NAME") AS "t3" ON "t2"."s_suppkey" = "t3"."S_SUPPKEY"
LEFT JOIN (SELECT "t4"."o_orderkey" AS "O_ORDERKEY", "t4"."o_orderdate" AS "O_ORDERDATE", SUM("lineitem"."l_extendedprice" * (1 - "lineitem"."l_discount")) AS "TOTAL_PRICE", COUNT(*) AS "NUMBER_OF_ITEMS"
FROM (SELECT *
FROM "TPCH"."orders"
WHERE "o_orderdate" >= DATE '1997-01-01') AS "t4"
INNER JOIN "TPCH"."lineitem" ON "t4"."o_orderkey" = "lineitem"."l_orderkey"
GROUP BY "t4"."o_orderkey", "t4"."o_orderdate") AS "t6" ON "t2"."s_suppkey" = "t6"."O_ORDERKEY"
GROUP BY "t2"."R_NAME"
HAVING COUNT(DISTINCT "t2"."s_suppkey") > 0
ORDER BY 5 DESC NULLS FIRST, 7 DESC NULLS FIRST) AS "t10"