SELECT COALESCE("t8"."REGION", "t8"."REGION") AS "REGION", "t8"."NATION", "t8"."NATION_SALES", "t8"."TOTAL_SUPPLY_COST", "t8"."SALES_TO_SUPPLY_COST_RATIO"
FROM (SELECT "t6"."r_name" AS "REGION", "t6"."n_name" AS "NATION", CASE WHEN "t6"."TOTAL_SALES" IS NOT NULL THEN CAST("t6"."TOTAL_SALES" AS DECIMAL(19, 2)) ELSE 0.00 END AS "NATION_SALES", CAST("s1"."TOTAL_SUPPLY_COST" AS DECIMAL(19, 2)) AS "TOTAL_SUPPLY_COST", CASE WHEN CASE WHEN "t6"."TOTAL_SALES" IS NOT NULL THEN CAST("t6"."TOTAL_SALES" AS DECIMAL(19, 2)) ELSE 0.00 END > 0.00 THEN CASE WHEN "t6"."TOTAL_SALES" IS NOT NULL THEN CAST("t6"."TOTAL_SALES" AS DECIMAL(19, 2)) ELSE 0.00 END / CAST("s1"."TOTAL_SUPPLY_COST" AS DECIMAL(19, 2)) ELSE NULL END AS "SALES_TO_SUPPLY_COST_RATIO"
FROM (SELECT "t3"."r_regionkey", "t3"."r_name", "t3"."r_comment", "t3"."n_nationkey", "t3"."n_name", "t3"."n_regionkey", "t3"."n_comment", "t5"."n_name" AS "N_NAME", "t5"."TOTAL_SALES", CAST("t3"."n_nationkey" AS BIGINT) AS "n_nationkey0"
FROM (SELECT "region"."r_regionkey", "region"."r_name", "region"."r_comment", "nation"."n_nationkey", "nation"."n_name", "nation"."n_regionkey", "nation"."n_comment"
FROM "TPCH"."nation"
RIGHT JOIN "TPCH"."region" ON "nation"."n_regionkey" = "region"."r_regionkey") AS "t3"
LEFT JOIN (SELECT "t4"."n_name", SUM("orders"."o_totalprice") AS "TOTAL_SALES"
FROM "TPCH"."orders"
RIGHT JOIN (SELECT "nation0"."n_nationkey", "nation0"."n_name", "nation0"."n_regionkey", "nation0"."n_comment", "customer"."c_custkey", "customer"."c_name", "customer"."c_address", "customer"."c_nationkey", "customer"."c_phone", "customer"."c_acctbal", "customer"."c_mktsegment", "customer"."c_comment"
FROM "TPCH"."customer"
RIGHT JOIN "TPCH"."nation" AS "nation0" ON "customer"."c_nationkey" = "nation0"."n_nationkey") AS "t4" ON "orders"."o_custkey" = "t4"."c_custkey"
GROUP BY "t4"."n_name") AS "t5" ON "t3"."n_name" = "t5"."n_name") AS "t6"
INNER JOIN "s1" ON "t6"."n_nationkey0" = "s1"."PS_SUPPKEY"
ORDER BY 5 DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY) AS "t8"