SELECT COALESCE("nation"."n_name", "nation"."n_name") AS "n_name", ANY_VALUE("nation"."n_name") AS "NATION_NAME", SUM("t13"."TOTAL_SALES") AS "FD_COL_2", COUNT(DISTINCT "t13"."S_SUPPKEY") AS "SUPPLIER_COUNT"
FROM (SELECT "t3"."S_SUPPKEY", "t3"."S_NAME", "t3"."TOTAL_SALES", "t3"."ORDER_COUNT", "t3"."SALES_RANK", "t12"."$f1" AS "$f0"
FROM (SELECT "supplier0"."s_suppkey" AS "S_SUPPKEY", "supplier0"."s_name" AS "S_NAME", "t2"."TOTAL_SALES", "t2"."ORDER_COUNT", RANK() OVER (ORDER BY "t2"."TOTAL_SALES" DESC NULLS FIRST) AS "SALES_RANK"
FROM (SELECT "supplier"."s_suppkey" AS "S_SUPPKEY", "supplier"."s_name" AS "S_NAME", SUM("t0"."l_extendedprice" * (1 - "t0"."l_discount")) AS "TOTAL_SALES", COUNT(DISTINCT "t"."o_orderkey") AS "ORDER_COUNT"
FROM "TPCH"."supplier"
INNER JOIN "TPCH"."partsupp" ON "supplier"."s_suppkey" = "partsupp"."ps_suppkey"
INNER JOIN ((SELECT *
FROM "TPCH"."orders"
WHERE "o_orderstatus" = 'O') AS "t" INNER JOIN (SELECT *
FROM "TPCH"."lineitem"
WHERE "l_shipdate" >= DATE '1997-01-01') AS "t0" ON "t"."o_orderkey" = "t0"."l_orderkey") ON "partsupp"."ps_partkey" = "t0"."l_partkey"
GROUP BY "supplier"."s_suppkey", "supplier"."s_name") AS "t2"
INNER JOIN "TPCH"."supplier" AS "supplier0" ON "t2"."S_SUPPKEY" = "supplier0"."s_suppkey") AS "t3"
LEFT JOIN (SELECT "t9"."S_SUPPKEY" AS "s_suppkey", "t11"."$f1"
FROM (SELECT "supplier2"."s_suppkey" AS "S_SUPPKEY"
FROM (SELECT "supplier1"."s_suppkey" AS "S_SUPPKEY", "supplier1"."s_name" AS "S_NAME", SUM("t5"."l_extendedprice" * (1 - "t5"."l_discount")) AS "TOTAL_SALES", COUNT(DISTINCT "t4"."o_orderkey") AS "ORDER_COUNT"
FROM "TPCH"."supplier" AS "supplier1"
INNER JOIN "TPCH"."partsupp" AS "partsupp0" ON "supplier1"."s_suppkey" = "partsupp0"."ps_suppkey"
INNER JOIN ((SELECT *
FROM "TPCH"."orders"
WHERE "o_orderstatus" = 'O') AS "t4" INNER JOIN (SELECT *
FROM "TPCH"."lineitem"
WHERE "l_shipdate" >= DATE '1997-01-01') AS "t5" ON "t4"."o_orderkey" = "t5"."l_orderkey") ON "partsupp0"."ps_partkey" = "t5"."l_partkey"
GROUP BY "supplier1"."s_suppkey", "supplier1"."s_name") AS "t7"
INNER JOIN "TPCH"."supplier" AS "supplier2" ON "t7"."S_SUPPKEY" = "supplier2"."s_suppkey"
GROUP BY "supplier2"."s_suppkey") AS "t9"
LEFT JOIN (SELECT "s_suppkey", SINGLE_VALUE("s_nationkey") AS "$f1"
FROM "TPCH"."supplier"
GROUP BY "s_suppkey") AS "t11" ON "t9"."S_SUPPKEY" IS NOT DISTINCT FROM "t11"."s_suppkey") AS "t12" ON "t3"."S_SUPPKEY" = "t12"."s_suppkey") AS "t13"
RIGHT JOIN "TPCH"."nation" ON "t13"."$f0" = "nation"."n_nationkey"
GROUP BY "nation"."n_name"