SELECT COALESCE("t5"."REGION_NAME", "t5"."REGION_NAME") AS "REGION_NAME", "t5"."TOTAL_SALES", "t5"."RAN", "t"."n_name" AS "N_NAME", "t"."UNIQUE_SUPPLIERS", "t"."AVG_ACCOUNT_BALANCE"
FROM (SELECT "nation"."n_name", COUNT(DISTINCT "supplier"."s_suppkey") AS "UNIQUE_SUPPLIERS", AVG("supplier"."s_acctbal") AS "AVG_ACCOUNT_BALANCE"
FROM "TPCH"."nation"
INNER JOIN "TPCH"."supplier" ON "nation"."n_nationkey" = "supplier"."s_nationkey"
GROUP BY "nation"."n_name") AS "t"
RIGHT JOIN (SELECT ANY_VALUE("t3"."r_name") AS "REGION_NAME", SUM("orders"."o_totalprice") AS "TOTAL_SALES", ROW_NUMBER() OVER (ORDER BY SUM("orders"."o_totalprice") DESC NULLS FIRST) AS "RAN"
FROM (SELECT "t2"."r_regionkey", "t2"."r_name", "t2"."r_comment", "t2"."n_nationkey", "t2"."n_name", "t2"."n_regionkey", "t2"."n_comment", "t2"."s_suppkey", "t2"."s_name", "t2"."s_address", "t2"."s_nationkey", "t2"."s_phone", "t2"."s_acctbal", "t2"."s_comment", "t2"."ps_partkey", "t2"."ps_suppkey", "t2"."ps_availqty", "t2"."ps_supplycost", "t2"."ps_comment", "part"."p_partkey", "part"."p_name", "part"."p_mfgr", "part"."p_brand", "part"."p_type", "part"."p_size", "part"."p_container", "part"."p_retailprice", "part"."p_comment", "lineitem"."l_orderkey", "lineitem"."l_partkey", "lineitem"."l_suppkey", "lineitem"."l_linenumber", "lineitem"."l_quantity", "lineitem"."l_extendedprice", "lineitem"."l_discount", "lineitem"."l_tax", "lineitem"."l_returnflag", "lineitem"."l_linestatus", "lineitem"."l_shipdate", "lineitem"."l_commitdate", "lineitem"."l_receiptdate", "lineitem"."l_shipinstruct", "lineitem"."l_shipmode", "lineitem"."l_comment"
FROM "TPCH"."lineitem"
RIGHT JOIN ((SELECT "t1"."r_regionkey", "t1"."r_name", "t1"."r_comment", "t1"."n_nationkey", "t1"."n_name", "t1"."n_regionkey", "t1"."n_comment", "t1"."s_suppkey", "t1"."s_name", "t1"."s_address", "t1"."s_nationkey", "t1"."s_phone", "t1"."s_acctbal", "t1"."s_comment", "partsupp"."ps_partkey", "partsupp"."ps_suppkey", "partsupp"."ps_availqty", "partsupp"."ps_supplycost", "partsupp"."ps_comment"
FROM "TPCH"."partsupp"
RIGHT JOIN (SELECT "t0"."r_regionkey", "t0"."r_name", "t0"."r_comment", "t0"."n_nationkey", "t0"."n_name", "t0"."n_regionkey", "t0"."n_comment", "supplier0"."s_suppkey", "supplier0"."s_name", "supplier0"."s_address", "supplier0"."s_nationkey", "supplier0"."s_phone", "supplier0"."s_acctbal", "supplier0"."s_comment"
FROM "TPCH"."supplier" AS "supplier0"
RIGHT JOIN (SELECT "region"."r_regionkey", "region"."r_name", "region"."r_comment", "nation0"."n_nationkey", "nation0"."n_name", "nation0"."n_regionkey", "nation0"."n_comment"
FROM "TPCH"."nation" AS "nation0"
RIGHT JOIN "TPCH"."region" ON "nation0"."n_regionkey" = "region"."r_regionkey") AS "t0" ON "supplier0"."s_nationkey" = "t0"."n_nationkey") AS "t1" ON "partsupp"."ps_suppkey" = "t1"."s_suppkey") AS "t2" LEFT JOIN "TPCH"."part" ON "t2"."ps_partkey" = "part"."p_partkey") ON "lineitem"."l_partkey" = "part"."p_partkey") AS "t3"
LEFT JOIN "TPCH"."orders" ON "t3"."l_orderkey" = "orders"."o_orderkey"
GROUP BY "t3"."r_name") AS "t5" ON "t"."n_name" = "t5"."REGION_NAME"