SELECT COALESCE("t20"."REGION_NAME", "t20"."REGION_NAME") AS "REGION_NAME", "t20"."TOTAL_SALES", "t20"."N_NAME", "t20"."UNIQUE_SUPPLIERS", "t20"."AVG_ACCOUNT_BALANCE", "t20"."RICH_CUSTOMER_NAME", "t20"."CUSTOMER_CLASSIFICATION", "t20"."SALES_PER_AVG_BALANCE"
FROM (SELECT "t18"."REGION_NAME", "t18"."TOTAL_SALES", "t18"."N_NAME", "t18"."UNIQUE_SUPPLIERS", "t18"."AVG_ACCOUNT_BALANCE", "t18"."RICH_CUSTOMER_NAME", "t18"."CUSTOMER_CLASSIFICATION", CASE WHEN "t18"."AVG_ACCOUNT_BALANCE0" <> 0.00 AND "t18"."TOTAL_SALES" IS NOT NULL THEN CAST("t18"."TOTAL_SALES" / CASE WHEN "t18"."AVG_ACCOUNT_BALANCE0" = 0.00 THEN NULL ELSE "t18"."AVG_ACCOUNT_BALANCE0" END AS DECIMAL(19, 6)) ELSE 0.000000 END AS "SALES_PER_AVG_BALANCE"
FROM (SELECT AVG("t12"."TOTAL_SALES") AS "EXPR$0"
FROM (SELECT "t11"."r_name", ANY_VALUE("t11"."r_name") AS "REGION_NAME", SUM("orders0"."o_totalprice") AS "TOTAL_SALES", COUNT(DISTINCT "orders0"."o_orderkey") AS "ORDER_COUNT"
FROM (SELECT "t10"."r_regionkey", "t10"."r_name", "t10"."r_comment", "t10"."n_nationkey", "t10"."n_name", "t10"."n_regionkey", "t10"."n_comment", "t10"."s_suppkey", "t10"."s_name", "t10"."s_address", "t10"."s_nationkey", "t10"."s_phone", "t10"."s_acctbal", "t10"."s_comment", "t10"."ps_partkey", "t10"."ps_suppkey", "t10"."ps_availqty", "t10"."ps_supplycost", "t10"."ps_comment", "part0"."p_partkey", "part0"."p_name", "part0"."p_mfgr", "part0"."p_brand", "part0"."p_type", "part0"."p_size", "part0"."p_container", "part0"."p_retailprice", "part0"."p_comment", "lineitem0"."l_orderkey", "lineitem0"."l_partkey", "lineitem0"."l_suppkey", "lineitem0"."l_linenumber", "lineitem0"."l_quantity", "lineitem0"."l_extendedprice", "lineitem0"."l_discount", "lineitem0"."l_tax", "lineitem0"."l_returnflag", "lineitem0"."l_linestatus", "lineitem0"."l_shipdate", "lineitem0"."l_commitdate", "lineitem0"."l_receiptdate", "lineitem0"."l_shipinstruct", "lineitem0"."l_shipmode", "lineitem0"."l_comment"
FROM "TPCH"."lineitem" AS "lineitem0"
RIGHT JOIN ((SELECT "t9"."r_regionkey", "t9"."r_name", "t9"."r_comment", "t9"."n_nationkey", "t9"."n_name", "t9"."n_regionkey", "t9"."n_comment", "t9"."s_suppkey", "t9"."s_name", "t9"."s_address", "t9"."s_nationkey", "t9"."s_phone", "t9"."s_acctbal", "t9"."s_comment", "partsupp0"."ps_partkey", "partsupp0"."ps_suppkey", "partsupp0"."ps_availqty", "partsupp0"."ps_supplycost", "partsupp0"."ps_comment"
FROM "TPCH"."partsupp" AS "partsupp0"
RIGHT JOIN (SELECT "t8"."r_regionkey", "t8"."r_name", "t8"."r_comment", "t8"."n_nationkey", "t8"."n_name", "t8"."n_regionkey", "t8"."n_comment", "supplier1"."s_suppkey", "supplier1"."s_name", "supplier1"."s_address", "supplier1"."s_nationkey", "supplier1"."s_phone", "supplier1"."s_acctbal", "supplier1"."s_comment"
FROM "TPCH"."supplier" AS "supplier1"
RIGHT JOIN (SELECT "region0"."r_regionkey", "region0"."r_name", "region0"."r_comment", "nation1"."n_nationkey", "nation1"."n_name", "nation1"."n_regionkey", "nation1"."n_comment"
FROM "TPCH"."nation" AS "nation1"
RIGHT JOIN "TPCH"."region" AS "region0" ON "nation1"."n_regionkey" = "region0"."r_regionkey") AS "t8" ON "supplier1"."s_nationkey" = "t8"."n_nationkey") AS "t9" ON "partsupp0"."ps_suppkey" = "t9"."s_suppkey") AS "t10" LEFT JOIN "TPCH"."part" AS "part0" ON "t10"."ps_partkey" = "part0"."p_partkey") ON "lineitem0"."l_partkey" = "part0"."p_partkey") AS "t11"
LEFT JOIN "TPCH"."orders" AS "orders0" ON "t11"."l_orderkey" = "orders0"."o_orderkey"
GROUP BY "t11"."r_name") AS "t12") AS "t13"
INNER JOIN (SELECT "t17"."REGION_NAME", "t17"."TOTAL_SALES", "t17"."N_NAME", "t17"."UNIQUE_SUPPLIERS", "t17"."AVG_ACCOUNT_BALANCE", "t17"."RICH_CUSTOMER_NAME", "t17"."CUSTOMER_CLASSIFICATION", "t14"."n_name" AS "N_NAME0", "t14"."UNIQUE_SUPPLIERS" AS "UNIQUE_SUPPLIERS0", "t14"."AVG_ACCOUNT_BALANCE" AS "AVG_ACCOUNT_BALANCE0"
FROM (SELECT "nation2"."n_name", COUNT(DISTINCT "supplier2"."s_suppkey") AS "UNIQUE_SUPPLIERS", AVG("supplier2"."s_acctbal") AS "AVG_ACCOUNT_BALANCE"
FROM "TPCH"."nation" AS "nation2"
INNER JOIN "TPCH"."supplier" AS "supplier2" ON "nation2"."n_nationkey" = "supplier2"."s_nationkey"
GROUP BY "nation2"."n_name") AS "t14"
RIGHT JOIN (SELECT "s1"."REGION_NAME", "s1"."TOTAL_SALES", "s1"."N_NAME", "s1"."UNIQUE_SUPPLIERS", "s1"."AVG_ACCOUNT_BALANCE", "t16"."C_NAME" AS "RICH_CUSTOMER_NAME", "t16"."CUSTOMER_CLASSIFICATION"
FROM (SELECT "c_custkey" AS "C_CUSTKEY", "c_name" AS "C_NAME", "c_acctbal" AS "C_ACCTBAL", CASE WHEN "c_acctbal" >= 1000.00 AND "c_acctbal" <= 2000.00 THEN 'Middle-Class' WHEN "c_acctbal" > 2000.00 THEN 'High-Class  ' ELSE 'Low-Class   ' END AS "CUSTOMER_CLASSIFICATION"
FROM "TPCH"."customer"
WHERE CAST("c_acctbal" AS DECIMAL(15, 2)) > 1500.00) AS "t16"
RIGHT JOIN "s1" ON "t16"."C_NAME" = "s1"."N_NAME") AS "t17" ON "t14"."n_name" = "t17"."N_NAME") AS "t18" ON "t13"."EXPR$0" > "t18"."TOTAL_SALES"
ORDER BY "t18"."TOTAL_SALES" DESC NULLS FIRST, "t18"."UNIQUE_SUPPLIERS") AS "t20"