SELECT COALESCE("t12"."R_NAME", "t12"."R_NAME") AS "R_NAME", "t12"."UNIQUE_CUSTOMERS", "t12"."AVG_SUPPLIER_COST", "t12"."LARGE_ORDERS", "t12"."POPULAR_PARTS"
FROM (SELECT "t7"."r_name" AS "R_NAME", COUNT(DISTINCT "customer"."c_custkey") AS "UNIQUE_CUSTOMERS", AVG("t7"."TOTAL_COST") AS "AVG_SUPPLIER_COST", SUM(CASE WHEN "t9"."TOTAL_LINES" > 5 THEN 1 ELSE 0 END) AS "LARGE_ORDERS", LISTAGG(DISTINCT "part"."p_name", ', ') AS "POPULAR_PARTS"
FROM (SELECT "t6"."r_regionkey", "t6"."r_name", "t6"."r_comment", "t6"."n_nationkey", "t6"."n_name", "t6"."n_regionkey", "t6"."n_comment", "t6"."s_suppkey", "t6"."s_name", "t6"."s_address", "t6"."s_nationkey", "t6"."s_phone", "t6"."s_acctbal", "t6"."s_comment", "t6"."S_SUPPKEY", "t6"."S_NAME", "t6"."TOTAL_COST", "t6"."l_orderkey", "t6"."l_partkey", "t6"."l_suppkey", "t6"."l_linenumber", "t6"."l_quantity", "t6"."l_extendedprice", "t6"."l_discount", "t6"."l_tax", "t6"."l_returnflag", "t6"."l_linestatus", "t6"."l_shipdate", "t6"."l_commitdate", "t6"."l_receiptdate", "t6"."l_shipinstruct", "t6"."l_shipmode", "t6"."l_comment", CAST("t2"."o_orderkey" AS BIGINT) AS "o_orderkey", CAST("t2"."o_custkey" AS BIGINT) AS "o_custkey", CAST("t2"."o_orderstatus" AS VARCHAR CHARACTER SET "ISO-8859-1") AS "o_orderstatus", CAST("t2"."o_totalprice" AS DECIMAL(15, 2)) AS "o_totalprice", CAST("t2"."o_orderdate" AS DATE) AS "o_orderdate", CAST("t2"."o_orderpriority" AS VARCHAR CHARACTER SET "ISO-8859-1") AS "o_orderpriority", CAST("t2"."o_clerk" AS VARCHAR CHARACTER SET "ISO-8859-1") AS "o_clerk", CAST("t2"."o_shippriority" AS INTEGER) AS "o_shippriority", CAST("t2"."o_comment" AS VARCHAR CHARACTER SET "ISO-8859-1") AS "o_comment"
FROM (SELECT *
FROM "TPCH"."orders"
WHERE "o_orderstatus" = 'O') AS "t2"
INNER JOIN (SELECT "t5"."r_regionkey", "t5"."r_name", "t5"."r_comment", "t5"."n_nationkey", "t5"."n_name", "t5"."n_regionkey", "t5"."n_comment", "t5"."s_suppkey", "t5"."s_name", "t5"."s_address", "t5"."s_nationkey", "t5"."s_phone", "t5"."s_acctbal", "t5"."s_comment", "t5"."S_SUPPKEY", "t5"."S_NAME", "t5"."TOTAL_COST", "lineitem"."l_orderkey", "lineitem"."l_partkey", "lineitem"."l_suppkey", "lineitem"."l_linenumber", "lineitem"."l_quantity", "lineitem"."l_extendedprice", "lineitem"."l_discount", "lineitem"."l_tax", "lineitem"."l_returnflag", "lineitem"."l_linestatus", "lineitem"."l_shipdate", "lineitem"."l_commitdate", "lineitem"."l_receiptdate", "lineitem"."l_shipinstruct", "lineitem"."l_shipmode", "lineitem"."l_comment"
FROM "TPCH"."lineitem"
RIGHT JOIN (SELECT "s1"."r_regionkey", "s1"."r_name", "s1"."r_comment", "s1"."n_nationkey", "s1"."n_name", "s1"."n_regionkey", "s1"."n_comment", "s1"."s_suppkey", "s1"."s_name", "s1"."s_address", "s1"."s_nationkey", "s1"."s_phone", "s1"."s_acctbal", "s1"."s_comment", CAST("t4"."S_SUPPKEY" AS BIGINT) AS "S_SUPPKEY", CAST("t4"."S_NAME" AS VARCHAR CHARACTER SET "ISO-8859-1") AS "S_NAME", CAST("t4"."TOTAL_COST" AS DECIMAL(19, 2)) AS "TOTAL_COST"
FROM (SELECT "supplier0"."s_suppkey" AS "S_SUPPKEY", "supplier0"."s_name" AS "S_NAME", SUM("partsupp"."ps_supplycost" * "partsupp"."ps_availqty") AS "TOTAL_COST"
FROM "TPCH"."supplier" AS "supplier0"
INNER JOIN "TPCH"."partsupp" ON "supplier0"."s_suppkey" = "partsupp"."ps_suppkey"
GROUP BY "supplier0"."s_suppkey", "supplier0"."s_name") AS "t4"
INNER JOIN "s1" ON "t4"."S_SUPPKEY" = "s1"."s_suppkey") AS "t5" ON "lineitem"."l_suppkey" = "t5"."s_suppkey") AS "t6" ON "t2"."o_orderkey" = "t6"."l_orderkey") AS "t7"
LEFT JOIN (SELECT "l_orderkey" AS "L_ORDERKEY", COUNT(*) AS "TOTAL_LINES", SUM("l_extendedprice" * (1 - "l_discount")) AS "TOTAL_REVENUE"
FROM "TPCH"."lineitem"
GROUP BY "l_orderkey") AS "t9" ON "t7"."o_orderkey" = "t9"."L_ORDERKEY"
LEFT JOIN "TPCH"."partsupp" AS "partsupp0" ON "t7"."l_partkey" = "partsupp0"."ps_partkey"
LEFT JOIN "TPCH"."part" ON "partsupp0"."ps_partkey" = "part"."p_partkey"
LEFT JOIN "TPCH"."customer" ON "t7"."o_custkey" = "customer"."c_custkey"
GROUP BY "t7"."r_name"
ORDER BY 2 DESC NULLS FIRST, 3 DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY) AS "t12"