SELECT COALESCE("t8"."R_NAME", "t8"."R_NAME") AS "R_NAME", "t8"."C_NAME", "t8"."TOTAL_SPENT", "t8"."P_NAME", "t8"."TOTAL_AVAILABLE", "t8"."AVG_SUPPLY_COST"
FROM (SELECT "t1"."r_name" AS "R_NAME", "t5"."C_NAME", "t5"."TOTAL_SPENT", "t2"."p_name" AS "P_NAME", "t2"."TOTAL_AVAILABLE", "t2"."AVG_SUPPLY_COST"
FROM (SELECT "t0"."r_regionkey", "t0"."r_name", "t0"."r_comment", "t0"."n_nationkey", "t0"."n_name", "t0"."n_regionkey", "t0"."n_comment", "supplier"."s_suppkey", "supplier"."s_name", "supplier"."s_address", "supplier"."s_nationkey", "supplier"."s_phone", "supplier"."s_acctbal", "supplier"."s_comment"
FROM "TPCH"."supplier"
RIGHT JOIN (SELECT "region"."r_regionkey", "region"."r_name", "region"."r_comment", "nation"."n_nationkey", "nation"."n_name", "nation"."n_regionkey", "nation"."n_comment"
FROM "TPCH"."nation"
RIGHT JOIN "TPCH"."region" ON "nation"."n_regionkey" = "region"."r_regionkey") AS "t0" ON "supplier"."s_nationkey" = "t0"."n_nationkey") AS "t1"
LEFT JOIN (SELECT "p_partkey", "p_name", "p_brand", SUM("ps_availqty") AS "TOTAL_AVAILABLE", AVG("ps_supplycost") AS "AVG_SUPPLY_COST"
FROM "s1"
GROUP BY "p_partkey", "p_name", "p_brand") AS "t2" ON "t1"."s_suppkey" = "t2"."p_partkey"
LEFT JOIN (SELECT "customer"."c_custkey" AS "C_CUSTKEY", "customer"."c_name" AS "C_NAME", "customer"."c_acctbal" AS "C_ACCTBAL", SUM("lineitem"."l_extendedprice" * (1 - "lineitem"."l_discount")) AS "TOTAL_SPENT"
FROM "TPCH"."lineitem"
INNER JOIN ("TPCH"."customer" INNER JOIN "TPCH"."orders" ON "customer"."c_custkey" = "orders"."o_custkey") ON "lineitem"."l_orderkey" = "orders"."o_orderkey"
GROUP BY "customer"."c_custkey", "customer"."c_name", "customer"."c_acctbal"
HAVING SUM("lineitem"."l_extendedprice" * (1 - "lineitem"."l_discount")) > 1000.0000) AS "t5" ON "t1"."s_suppkey" = "t5"."C_CUSTKEY"
WHERE "t5"."C_ACCTBAL" IS NOT NULL AND "t5"."TOTAL_SPENT" > 5000.0000 OR "t5"."C_ACCTBAL" IS NULL AND "t2"."AVG_SUPPLY_COST" < 50.00
ORDER BY "t1"."r_name", "t5"."TOTAL_SPENT" DESC NULLS FIRST, "t2"."TOTAL_AVAILABLE" DESC NULLS FIRST) AS "t8"