SELECT COALESCE("t14"."R_NAME", "t14"."R_NAME") AS "R_NAME", "t14"."REGION_COUNT", "t14"."TOTAL_RETAIL_PRICE", "t14"."AVG_ORDER_PRICE"
FROM (SELECT "t12"."R_NAME", "t12"."REGION_COUNT", CASE WHEN "t12"."$f2" IS NOT NULL THEN CAST("t12"."$f2" AS DECIMAL(19, 2)) ELSE 0.00 END AS "TOTAL_RETAIL_PRICE", "t12"."AVG_ORDER_PRICE"
FROM "s1"
INNER JOIN (SELECT "t11"."R_NAME", "t11"."REGION_COUNT", SUM("t11"."P_RETAILPRICE") AS "$f2", AVG("t2"."O_TOTALPRICE") AS "AVG_ORDER_PRICE"
FROM (SELECT "o_orderkey" AS "O_ORDERKEY", "o_orderdate" AS "O_ORDERDATE", "o_totalprice" AS "O_TOTALPRICE", ROW_NUMBER() OVER (PARTITION BY EXTRACT(YEAR FROM "o_orderdate") ORDER BY "o_totalprice" DESC NULLS FIRST) AS "ORDER_RANK", EXTRACT(YEAR FROM "o_orderdate") AS "$f4"
FROM "TPCH"."orders"
WHERE "o_orderdate" >= DATE '1994-01-01') AS "t2"
RIGHT JOIN (SELECT "t10"."R_NAME", "t10"."REGION_COUNT", "t10"."TOTAL_QUANTITY", "t3"."P_PARTKEY", "t3"."P_NAME", "t3"."P_RETAILPRICE", "t3"."SIZE_CATEGORY"
FROM (SELECT "p_partkey" AS "P_PARTKEY", "p_name" AS "P_NAME", "p_retailprice" AS "P_RETAILPRICE", CASE WHEN "p_size" >= 1 AND "p_size" <= 5 THEN 'Small ' WHEN "p_size" >= 6 AND "p_size" <= 15 THEN 'Medium' ELSE 'Large ' END AS "SIZE_CATEGORY"
FROM "TPCH"."part") AS "t3"
RIGHT JOIN (SELECT "t8"."r_name" AS "R_NAME", COUNT(DISTINCT "t8"."N_NATIONKEY") AS "REGION_COUNT", SUM("t4"."TOTAL_QTY") AS "TOTAL_QUANTITY", COUNT(DISTINCT "t8"."N_NATIONKEY") > 5 AS "$f3"
FROM (SELECT "l_orderkey", SUM("l_quantity") AS "TOTAL_QTY"
FROM "TPCH"."lineitem"
GROUP BY "l_orderkey") AS "t4"
RIGHT JOIN (SELECT "region"."r_regionkey", "region"."r_name", "region"."r_comment", "t7"."N_NAME", "t7"."SUPPLIER_COUNT", "t7"."N_NATIONKEY", CAST("t7"."N_NATIONKEY" AS BIGINT) AS "N_NATIONKEY0"
FROM (SELECT "nation"."n_name" AS "N_NAME", COUNT(DISTINCT "supplier"."s_suppkey") AS "SUPPLIER_COUNT", "nation"."n_nationkey" AS "N_NATIONKEY"
FROM "TPCH"."nation"
INNER JOIN "TPCH"."supplier" ON "nation"."n_nationkey" = "supplier"."s_nationkey"
GROUP BY "nation"."n_nationkey", "nation"."n_name") AS "t7"
RIGHT JOIN "TPCH"."region" ON "t7"."N_NATIONKEY" = "region"."r_regionkey") AS "t8" ON "t4"."l_orderkey" = "t8"."N_NATIONKEY0"
GROUP BY "t8"."r_name") AS "t10" ON "t10"."$f3") AS "t11" ON "t2"."$f4" = "t11"."REGION_COUNT"
GROUP BY "t11"."R_NAME", "t11"."REGION_COUNT") AS "t12" ON "s1"."FD_COL_0" < "t12"."AVG_ORDER_PRICE"
ORDER BY "t12"."R_NAME" DESC NULLS FIRST
OFFSET 5 ROWS
FETCH NEXT 10 ROWS ONLY) AS "t14"