SELECT COALESCE("NATION_REGION", "NATION_REGION") AS "NATION_REGION", "UNIQUE_CUSTOMERS", "TOTAL_RETAIL_PRICE_LARGE_NAME", "AVG_SALES_PRICE", "PART_COMMENTS"
FROM (SELECT "NATION_REGION", "UNIQUE_CUSTOMERS", "TOTAL_RETAIL_PRICE_LARGE_NAME", ROUND("FD_COL_5", 2) AS "AVG_SALES_PRICE", "PART_COMMENTS"
FROM "s1"
WHERE "UNIQUE_CUSTOMERS" > 10
ORDER BY "NATION_REGION") AS "t5"