SELECT COALESCE("SUPPLIER_NAME", "SUPPLIER_NAME") AS "SUPPLIER_NAME", "PART_NAME", "TOTAL_ORDERS", "TOTAL_REVENUE", "MARKET_SEGMENTS", "FIRST_SHIP_DATE", "LAST_SHIP_DATE"
FROM (SELECT "s_name", "p_name", ANY_VALUE("s_name") AS "SUPPLIER_NAME", ANY_VALUE("p_name") AS "PART_NAME", COUNT(DISTINCT "o_orderkey") AS "TOTAL_ORDERS", SUM("FD_COL_3") AS "TOTAL_REVENUE", LISTAGG(DISTINCT "c_mktsegment", "FD_COL_5") AS "MARKET_SEGMENTS", MIN("l_shipdate") AS "FIRST_SHIP_DATE", MAX("l_shipdate") AS "LAST_SHIP_DATE"
FROM "s1"
GROUP BY "s_name", "p_name"
ORDER BY 6 DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY) AS "t6"