SELECT COALESCE("t9"."FORMATTED_NAME_ADDRESS", "t9"."FORMATTED_NAME_ADDRESS") AS "FORMATTED_NAME_ADDRESS", "t9"."P_NAME", "t9"."MODIFIED_COMMENT", "t9"."C_NAME", "t9"."TOTAL_QUANTITY", "t9"."TOTAL_REVENUE"
FROM (SELECT "t6"."FORMATTED_NAME_ADDRESS", "t6"."P_NAME", "t6"."MODIFIED_COMMENT", "t6"."C_NAME", SUM("s1"."L_QUANTITY") AS "TOTAL_QUANTITY", SUM("s1"."L_EXTENDEDPRICE" * (1 - "s1"."L_DISCOUNT")) AS "TOTAL_REVENUE"
FROM (SELECT "t5"."S_SUPPKEY", "t5"."S_NAME", "t5"."S_NATIONKEY", "t5"."FORMATTED_NAME_ADDRESS", "t5"."ps_partkey", "t5"."ps_suppkey", "t5"."ps_availqty", "t5"."ps_supplycost", "t5"."ps_comment", "t5"."P_PARTKEY", "t5"."P_NAME", "t5"."P_MFGR", "t5"."P_TYPE", "t5"."P_SIZE", "t5"."MODIFIED_COMMENT", "t2"."C_CUSTKEY", "t2"."C_NAME", "t2"."C_MKTSEGMENT", "t2"."LAST_TEN_ADDRESS_DIGITS"
FROM (SELECT "c_custkey" AS "C_CUSTKEY", "c_name" AS "C_NAME", "c_mktsegment" AS "C_MKTSEGMENT", RIGHT("c_address", 10) AS "LAST_TEN_ADDRESS_DIGITS"
FROM "TPCH"."customer") AS "t2"
INNER JOIN (SELECT "t3"."S_SUPPKEY", "t3"."S_NAME", "t3"."S_NATIONKEY", "t3"."FORMATTED_NAME_ADDRESS", "partsupp"."ps_partkey", "partsupp"."ps_suppkey", "partsupp"."ps_availqty", "partsupp"."ps_supplycost", "partsupp"."ps_comment", "t4"."P_PARTKEY", "t4"."P_NAME", "t4"."P_MFGR", "t4"."P_TYPE", "t4"."P_SIZE", "t4"."MODIFIED_COMMENT", CAST("t3"."S_NATIONKEY" AS BIGINT) AS "S_NATIONKEY0"
FROM (SELECT "s_suppkey" AS "S_SUPPKEY", "s_name" AS "S_NAME", "s_nationkey" AS "S_NATIONKEY", CONCAT("s_name", ' (', SUBSTRING("s_address", 1, 10), '...)') AS "FORMATTED_NAME_ADDRESS"
FROM "TPCH"."supplier") AS "t3"
INNER JOIN ((SELECT "p_partkey" AS "P_PARTKEY", "p_name" AS "P_NAME", "p_mfgr" AS "P_MFGR", "p_type" AS "P_TYPE", "p_size" AS "P_SIZE", REPLACE("p_comment", 'part', 'component') AS "MODIFIED_COMMENT"
FROM "TPCH"."part") AS "t4" INNER JOIN "TPCH"."partsupp" ON "t4"."P_PARTKEY" = "partsupp"."ps_partkey") ON "t3"."S_SUPPKEY" = "partsupp"."ps_suppkey") AS "t5" ON "t2"."C_CUSTKEY" = "t5"."S_NATIONKEY0") AS "t6"
INNER JOIN "s1" ON "t6"."P_PARTKEY" = "s1"."L_ORDERKEY"
GROUP BY "t6"."FORMATTED_NAME_ADDRESS", "t6"."P_NAME", "t6"."MODIFIED_COMMENT", "t6"."C_NAME"
ORDER BY 6 DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY) AS "t9"