SELECT COALESCE("P_NAME", "P_NAME") AS "P_NAME", "UNIQUE_SUPPLIERS", "TOTAL_AVAILABLE_QUANTITY", "AVERAGE_RETAIL_PRICE", "SUPPLIER_INFO"
FROM (SELECT "P_NAME", "UNIQUE_SUPPLIERS", "TOTAL_AVAILABLE_QUANTITY", "AVERAGE_RETAIL_PRICE", "SUPPLIER_INFO"
FROM "s1"
WHERE "UNIQUE_SUPPLIERS" > 1
ORDER BY "TOTAL_AVAILABLE_QUANTITY" DESC NULLS FIRST, "AVERAGE_RETAIL_PRICE"
FETCH NEXT 10 ROWS ONLY) AS "t5"