SELECT COALESCE("t"."N_NATIONKEY", "t"."N_NATIONKEY") AS "N_NATIONKEY", "t"."NATIONNAME", "t0"."P_PARTKEY", "t0"."P_NAME", "t0"."PARTINFO", "t2"."ps_partkey" AS "PS_PARTKEY", "t2"."ps_suppkey" AS "PS_SUPPKEY", "t2"."TOTALAVAILABLE", "t2"."MINSUPPLYCOST", "t3"."S_SUPPKEY", "t3"."S_NAME", "t3"."S_NATIONKEY", "t3"."SUPPLIERINFO"
FROM (SELECT "n_nationkey" AS "N_NATIONKEY", "n_name" AS "NATIONNAME"
FROM "TPCH"."nation") AS "t"
INNER JOIN ((SELECT "p_partkey" AS "P_PARTKEY", "p_name" AS "P_NAME", CONCAT("p_name", ' [', "p_brand", '] - ', "p_comment") AS "PARTINFO"
FROM "TPCH"."part") AS "t0" INNER JOIN ((SELECT "ps_partkey", "ps_suppkey", SUM("ps_availqty") AS "TOTALAVAILABLE", MIN("ps_supplycost") AS "MINSUPPLYCOST"
FROM "TPCH"."partsupp"
GROUP BY "ps_partkey", "ps_suppkey"
HAVING SUM("ps_availqty") > 100) AS "t2" INNER JOIN (SELECT "s_suppkey" AS "S_SUPPKEY", "s_name" AS "S_NAME", "s_nationkey" AS "S_NATIONKEY", CONCAT("s_name", ' - ', "s_address", ' (', "s_phone", ')') AS "SUPPLIERINFO"
FROM "TPCH"."supplier") AS "t3" ON "t2"."ps_suppkey" = "t3"."S_SUPPKEY") ON "t0"."P_PARTKEY" = "t2"."ps_partkey") ON "t"."N_NATIONKEY" = "t3"."S_NATIONKEY"