SELECT COALESCE("SUPPLIERINFO", "SUPPLIERINFO") AS "SUPPLIERINFO", "NATIONNAME", "PARTINFO", "TOTALAVAILABLE", "MINSUPPLYCOST"
FROM (SELECT "SUPPLIERINFO", "NATIONNAME", "PARTINFO", "TOTALAVAILABLE", "MINSUPPLYCOST"
FROM "s1"
ORDER BY "SUPPLIERINFO", "MINSUPPLYCOST" DESC NULLS FIRST) AS "t6"