SELECT COALESCE("P_NAME", "P_NAME") AS "P_NAME", "SUPPLIER_COUNT", "TOTAL_AVAILABLE_QUANTITY", "TRUNCATED_COMMENT", "REGION_NAME", "p_name" AS "p_name_"
FROM (SELECT "P_NAME", "SUPPLIER_COUNT", "TOTAL_AVAILABLE_QUANTITY", "TRUNCATED_COMMENT", "REGION_NAME", "P_NAME" AS "p_name"
FROM "s1"
ORDER BY "TOTAL_AVAILABLE_QUANTITY" DESC NULLS FIRST, "P_NAME") AS "t6"