SELECT COALESCE("PRODUCT_NAME", "PRODUCT_NAME") AS "PRODUCT_NAME", "SUPPLIER_NAME", "CUSTOMER_NAME", "TOTAL_ORDERS", "TOTAL_SALES", "AVERAGE_QUANTITY", "LAST_SHIP_DATE", "REGIONS_SUPPLIED"
FROM (SELECT "PRODUCT_NAME", "SUPPLIER_NAME", "CUSTOMER_NAME", "TOTAL_ORDERS", "TOTAL_SALES", "AVERAGE_QUANTITY", "LAST_SHIP_DATE", "REGIONS_SUPPLIED"
FROM "s1"
ORDER BY "TOTAL_SALES" DESC NULLS FIRST) AS "t6"