SELECT COALESCE("t5"."NATION_NAME", "t5"."NATION_NAME") AS "NATION_NAME", "t5"."REGION_NAME", "t5"."SUPPLIER_NAME", "t5"."TOTAL_AVAILABLE_QUANTITY", "t5"."DISTINCT_PARTS_SUPPLIED", "t5"."PART_NAMES", "t5"."BENCHMARK_DATE"
FROM (SELECT "nation0"."n_name" AS "NATION_NAME", "t3"."REGION_NAME", "t2"."S_NAME" AS "SUPPLIER_NAME", "t2"."TOTAL_AVAILABLE_QUANTITY", "t2"."DISTINCT_PARTS_SUPPLIED", "t2"."PART_NAMES", DATE '1998-10-01' AS "BENCHMARK_DATE"
FROM (SELECT *
FROM "s1"
WHERE "TOTAL_AVAILABLE_QUANTITY" > 1000) AS "t2"
INNER JOIN ((SELECT "nation"."n_nationkey" AS "N_NATIONKEY", "nation"."n_name" AS "N_NAME", "region"."r_regionkey" AS "R_REGIONKEY", "region"."r_name" AS "REGION_NAME"
FROM "TPCH"."region"
INNER JOIN "TPCH"."nation" ON "region"."r_regionkey" = "nation"."n_regionkey") AS "t3" INNER JOIN "TPCH"."nation" AS "nation0" ON "t3"."N_NATIONKEY" = "nation0"."n_nationkey") ON "t2"."S_NATIONKEY" = "t3"."N_NATIONKEY"
ORDER BY "t2"."TOTAL_AVAILABLE_QUANTITY" DESC NULLS FIRST) AS "t5"