SELECT COALESCE("t9"."REGION_NAME", "t9"."REGION_NAME") AS "REGION_NAME", "t9"."SUPPLIER_COUNT", "t9"."CUSTOMER_COUNT", "t9"."SUPPLIER_DETAILS", "t9"."CUSTOMER_ORDERS_SUMMARY", "t9"."r_name"
FROM (SELECT ANY_VALUE("t3"."r_name") AS "REGION_NAME", COUNT(DISTINCT "t3"."SUPPLIER_NAME") AS "SUPPLIER_COUNT", COUNT(DISTINCT "t5"."CUSTOMER_NAME") AS "CUSTOMER_COUNT", LISTAGG("t3"."SUPPLY_INFO", '; ') AS "SUPPLIER_DETAILS", LISTAGG("t5"."ORDER_SUMMARY", '; ') AS "CUSTOMER_ORDERS_SUMMARY", "t3"."r_name"
FROM (SELECT "t2"."r_regionkey", "t2"."r_name", "t2"."r_comment", "t2"."n_nationkey", "t2"."n_name", "t2"."n_regionkey", "t2"."n_comment", "t2"."s_suppkey", "t2"."s_name", "t2"."s_address", "t2"."s_nationkey", "t2"."s_phone", "t2"."s_acctbal", "t2"."s_comment", "t0"."SUPPLIER_NAME", "t0"."PART_NAME", "t0"."AVAILABLE_QUANTITY", "t0"."SUPPLY_COST", "t0"."SUPPLY_INFO"
FROM (SELECT "supplier"."s_name" AS "SUPPLIER_NAME", "s1"."p_name" AS "PART_NAME", "s1"."ps_availqty" AS "AVAILABLE_QUANTITY", "s1"."ps_supplycost" AS "SUPPLY_COST", CONCAT("supplier"."s_name", ' supplies ', "s1"."p_name", ' with availability of ', CAST("s1"."ps_availqty" AS VARCHAR CHARACTER SET "ISO-8859-1"), ' units at a cost of $', CAST(CAST("s1"."ps_supplycost" AS DECIMAL(12, 2)) AS VARCHAR CHARACTER SET "ISO-8859-1")) AS "SUPPLY_INFO"
FROM "TPCH"."supplier"
INNER JOIN "s1" ON "supplier"."s_suppkey" = "s1"."ps_suppkey") AS "t0"
RIGHT JOIN (SELECT "t1"."r_regionkey", "t1"."r_name", "t1"."r_comment", "t1"."n_nationkey", "t1"."n_name", "t1"."n_regionkey", "t1"."n_comment", "supplier0"."s_suppkey", "supplier0"."s_name", "supplier0"."s_address", "supplier0"."s_nationkey", "supplier0"."s_phone", "supplier0"."s_acctbal", "supplier0"."s_comment"
FROM "TPCH"."supplier" AS "supplier0"
RIGHT JOIN (SELECT "region"."r_regionkey", "region"."r_name", "region"."r_comment", "nation"."n_nationkey", "nation"."n_name", "nation"."n_regionkey", "nation"."n_comment"
FROM "TPCH"."nation"
RIGHT JOIN "TPCH"."region" ON "nation"."n_regionkey" = "region"."r_regionkey") AS "t1" ON "supplier0"."s_nationkey" = "t1"."n_nationkey") AS "t2" ON "t0"."SUPPLIER_NAME" = "t2"."s_name") AS "t3"
LEFT JOIN (SELECT ANY_VALUE("customer"."c_name") AS "CUSTOMER_NAME", COUNT(*) AS "TOTAL_ORDERS", SUM("orders"."o_totalprice") AS "TOTAL_SPENT", CONCAT("customer"."c_name", ' has placed ', CAST(COUNT(*) AS VARCHAR CHARACTER SET "ISO-8859-1"), ' orders totaling $', CAST(CAST(SUM("orders"."o_totalprice") AS DECIMAL(12, 2)) AS VARCHAR CHARACTER SET "ISO-8859-1")) AS "ORDER_SUMMARY"
FROM "TPCH"."customer"
INNER JOIN "TPCH"."orders" ON "customer"."c_custkey" = "orders"."o_custkey"
GROUP BY "customer"."c_name") AS "t5" ON "t3"."SUPPLIER_NAME" = "t5"."CUSTOMER_NAME"
GROUP BY "t3"."r_name"
ORDER BY "t3"."r_name") AS "t9"