SELECT COALESCE("DETAILED_INFO", "DETAILED_INFO") AS "DETAILED_INFO", "COMMENT_LENGTH", "SHORT_COMMENT", "ORDER_COUNT"
FROM (SELECT "s_name", "p_name", "ps_comment", ANY_VALUE("FD_COL_3") AS "DETAILED_INFO", ANY_VALUE("FD_COL_4") AS "COMMENT_LENGTH", ANY_VALUE("FD_COL_5") AS "SHORT_COMMENT", COUNT(DISTINCT "o_orderkey") AS "ORDER_COUNT"
FROM "s1"
GROUP BY "s_name", "p_name", "ps_comment"
HAVING COUNT(DISTINCT "o_orderkey") > 5
ORDER BY 5 DESC NULLS FIRST) AS "t7"