SELECT COALESCE("P_BRAND", "P_BRAND") AS "P_BRAND", "UNIQUE_PARTS", "TOTAL_AVAIL_QTY", "AVG_RETAIL_PRICE", "SUPPLIERS", "REGION_INFO"
FROM (SELECT "P_BRAND", "UNIQUE_PARTS", "TOTAL_AVAIL_QTY", "AVG_RETAIL_PRICE", "SUPPLIERS", CONCAT('Region: ', "r_name", ' (', CAST("FD_COL_6" AS VARCHAR CHARACTER SET "ISO-8859-1"), ' Nations)') AS "REGION_INFO"
FROM "s1"
ORDER BY "TOTAL_AVAIL_QTY" DESC NULLS FIRST, "AVG_RETAIL_PRICE") AS "t6"