SELECT COALESCE("t7"."SUPPLIER_DETAILS", "t7"."SUPPLIER_DETAILS") AS "SUPPLIER_DETAILS", "t7"."P_NAME", "t7"."SIZE_CATEGORY", "t7"."O_TOTALPRICE", "t7"."O_ORDERSTATUS", "t7"."MAX_COMMENT_LENGTH"
FROM (SELECT "t4"."SUPPLIER_DETAILS", "s1"."P_NAME", "s1"."SIZE_CATEGORY", "t3"."O_TOTALPRICE", "t3"."O_ORDERSTATUS", MAX("s1"."COMMENT_LENGTH") AS "MAX_COMMENT_LENGTH"
FROM (SELECT "o_orderkey" AS "O_ORDERKEY", "o_totalprice" AS "O_TOTALPRICE", "o_orderstatus" AS "O_ORDERSTATUS", EXTRACT(YEAR FROM "o_orderdate") AS "ORDER_YEAR"
FROM "TPCH"."orders"
WHERE "o_totalprice" > 1000.00) AS "t3"
INNER JOIN "TPCH"."lineitem" ON "t3"."O_ORDERKEY" = "lineitem"."l_orderkey"
INNER JOIN ("s1" INNER JOIN ((SELECT "supplier"."s_suppkey" AS "S_SUPPKEY", "supplier"."s_name" AS "S_NAME", "supplier"."s_address" AS "S_ADDRESS", "nation"."n_name" AS "NATION_NAME", CONCAT("supplier"."s_name", ' | ', "supplier"."s_address", ' | ', "nation"."n_name") AS "SUPPLIER_DETAILS"
FROM "TPCH"."nation"
INNER JOIN "TPCH"."supplier" ON "nation"."n_nationkey" = "supplier"."s_nationkey") AS "t4" INNER JOIN "TPCH"."partsupp" ON "t4"."S_SUPPKEY" = "partsupp"."ps_suppkey") ON "s1"."P_PARTKEY" = "partsupp"."ps_partkey") ON "lineitem"."l_partkey" = "s1"."P_PARTKEY"
GROUP BY "t3"."O_TOTALPRICE", "t3"."O_ORDERSTATUS", "s1"."P_NAME", "s1"."SIZE_CATEGORY", "t4"."SUPPLIER_DETAILS"
ORDER BY 6 DESC NULLS FIRST, "t3"."O_TOTALPRICE" DESC NULLS FIRST) AS "t7"