SELECT COALESCE("N_NAME", "N_NAME") AS "N_NAME", "PART_COUNT", "MAX_UPPER_NAME_LENGTH", "MIN_LOWER_COMMENT_LENGTH", "MAX_MODIFIED_COMMENT_LENGTH", "AGGREGATED_BRAND_TYPE"
FROM "s1"
ORDER BY "PART_COUNT" DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY