SELECT COALESCE("DISTINCT_PART_COUNT", "DISTINCT_PART_COUNT") AS "DISTINCT_PART_COUNT", "AVERAGE_SUPPLIER_BALANCE", "SUPPLIER_NATIONS"
FROM (SELECT "p_name", COUNT(DISTINCT "p_partkey") AS "DISTINCT_PART_COUNT", AVG("s_acctbal") AS "AVERAGE_SUPPLIER_BALANCE", LISTAGG(DISTINCT "FD_COL_3", "FD_COL_4") AS "SUPPLIER_NATIONS", COUNT(*) AS "$f4"
FROM "s1"
GROUP BY "p_name"
HAVING COUNT(*) > 2
ORDER BY 3 DESC NULLS FIRST) AS "t6"