SELECT COALESCE("t8"."NATION_NAME", "t8"."NATION_NAME") AS "NATION_NAME", "t8"."PART_SUPPLIER_LIST", "t8"."PART_COUNT", "t8"."TOTAL_PART_COUNT", "t8"."PERCENTAGE_OF_TOTAL"
FROM (SELECT "t4"."NATION_NAME", "t4"."PART_SUPPLIER_LIST", "t4"."PART_COUNT", "t6"."TOTAL_PART_COUNT", ROUND("t4"."PART_COUNT" * 100.0 / "t6"."TOTAL_PART_COUNT", 2) AS "PERCENTAGE_OF_TOTAL"
FROM (SELECT "NATION_NAME", "PART_SUPPLIER_LIST", "PART_COUNT"
FROM "s1"
WHERE "PART_COUNT" > 0) AS "t4",
(SELECT COUNT(DISTINCT "p_partkey") AS "TOTAL_PART_COUNT"
FROM "TPCH"."part"
WHERE LENGTH("p_name") > 15) AS "t6"
ORDER BY 5 DESC NULLS FIRST) AS "t8"