SELECT COALESCE("SUPPLIER_INFO", "SUPPLIER_INFO") AS "SUPPLIER_INFO", "SHORT_PART_NAME", "CUSTOMER_COUNT", "TOTAL_REVENUE", "REGION_NAME"
FROM (SELECT "FD_COL_0", "FD_COL_1", "r_name", ANY_VALUE("FD_COL_0") AS "SUPPLIER_INFO", ANY_VALUE("FD_COL_1") AS "SHORT_PART_NAME", COUNT(DISTINCT "c_custkey") AS "CUSTOMER_COUNT", SUM("FD_COL_4") AS "TOTAL_REVENUE", ANY_VALUE("r_name") AS "REGION_NAME"
FROM "s1"
GROUP BY "FD_COL_0", "FD_COL_1", "r_name"
HAVING COUNT(DISTINCT "c_custkey") > 5
ORDER BY 7 DESC NULLS FIRST, 8) AS "t5"