SELECT COALESCE("P_NAME", "P_NAME") AS "P_NAME", "SUPPLIER_INFO", "SANITIZED_COMMENT", "NAME_LENGTH", "SHORT_ADDRESS", "FORMATTED_PHONE", "ORDER_COUNT"
FROM (SELECT "P_NAME", "s_name", "ps_comment", "p_comment", "s_address", "s_phone", ANY_VALUE("FD_COL_6") AS "SUPPLIER_INFO", ANY_VALUE("FD_COL_7") AS "SANITIZED_COMMENT", ANY_VALUE("FD_COL_8") AS "NAME_LENGTH", ANY_VALUE("FD_COL_9") AS "SHORT_ADDRESS", ANY_VALUE("FD_COL_10") AS "FORMATTED_PHONE", COUNT(DISTINCT "o_orderkey") AS "ORDER_COUNT"
FROM "s1"
GROUP BY "P_NAME", "s_name", "ps_comment", "p_comment", "s_address", "s_phone"
HAVING COUNT(DISTINCT "o_orderkey") > 0
ORDER BY 9 DESC NULLS FIRST, 12 DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY) AS "t4"