SELECT COALESCE("PART_NAME", "PART_NAME") AS "PART_NAME", "SUPPLIER_NAME", "CUSTOMER_NAME", "TOTAL_ORDERS", "TOTAL_QUANTITY", "TOTAL_REVENUE", "AVERAGE_TAX", "REGIONS_SUPPLIED"
FROM (SELECT "PART_NAME", "SUPPLIER_NAME", "CUSTOMER_NAME", "TOTAL_ORDERS", "TOTAL_QUANTITY", "TOTAL_REVENUE", "AVERAGE_TAX", "REGIONS_SUPPLIED"
FROM "s1"
WHERE "TOTAL_REVENUE" > 10000.0000
ORDER BY "TOTAL_REVENUE" DESC NULLS FIRST) AS "t6"