SELECT COALESCE("t5"."SUPPLIER_NAME", "t5"."SUPPLIER_NAME") AS "SUPPLIER_NAME", "t5"."PART_NAME", "t5"."TOTAL_LINEITEMS", "t5"."TOTAL_QUANTITY", "t5"."TOTAL_EXTENDED_PRICE", "t5"."NON_SPACE_COMMENT_LENGTH", "t5"."ADJUSTED_COMMENT"
FROM (SELECT "t2"."S_NAME" AS "SUPPLIER_NAME", "s1"."P_NAME" AS "PART_NAME", "t3"."TOTAL_LINEITEMS", "t3"."TOTAL_QUANTITY", "t3"."TOTAL_EXTENDED_PRICE", "s1"."NON_SPACE_COMMENT_LENGTH", "t2"."ADJUSTED_COMMENT"
FROM (SELECT "s_suppkey" AS "S_SUPPKEY", "s_name" AS "S_NAME", "s_address" AS "S_ADDRESS", "s_phone" AS "S_PHONE", CASE WHEN CASE WHEN LOWER("s_comment") = '' THEN FALSE ELSE LOWER("s_comment") IS NOT NULL END THEN CAST(CASE WHEN LOWER("s_comment") = '' THEN NULL ELSE LOWER("s_comment") END AS VARCHAR CHARACTER SET "ISO-8859-1") ELSE 'No Comment' END AS "ADJUSTED_COMMENT"
FROM "TPCH"."supplier") AS "t2"
INNER JOIN ("s1" INNER JOIN ("TPCH"."partsupp" INNER JOIN (SELECT "orders"."o_orderkey", "orders"."o_totalprice", COUNT(*) AS "TOTAL_LINEITEMS", SUM("lineitem"."l_quantity") AS "TOTAL_QUANTITY", SUM("lineitem"."l_extendedprice") AS "TOTAL_EXTENDED_PRICE"
FROM "TPCH"."orders"
INNER JOIN "TPCH"."lineitem" ON "orders"."o_orderkey" = "lineitem"."l_orderkey"
GROUP BY "orders"."o_orderkey", "orders"."o_totalprice") AS "t3" ON "partsupp"."ps_partkey" = "t3"."o_orderkey") ON "s1"."P_PARTKEY" = "partsupp"."ps_partkey") ON "t2"."S_SUPPKEY" = "partsupp"."ps_suppkey"
ORDER BY "t3"."TOTAL_EXTENDED_PRICE" DESC NULLS FIRST
FETCH NEXT 100 ROWS ONLY) AS "t5"