SELECT COALESCE("P_NAME", "P_NAME") AS "P_NAME", "SUPPLIER_NAME", "CUSTOMER_NAME", "O_ORDERDATE", "TOTAL_REVENUE", "TOTAL_ORDERS", "SHORT_COMMENT", "SUPPLIER_INFO", "o_orderdate" AS "o_orderdate_"
FROM (SELECT "P_NAME", "SUPPLIER_NAME", "CUSTOMER_NAME", "O_ORDERDATE", "TOTAL_REVENUE", "TOTAL_ORDERS", "SHORT_COMMENT", "SUPPLIER_INFO", "O_ORDERDATE" AS "o_orderdate"
FROM "s1"
ORDER BY "TOTAL_REVENUE" DESC NULLS FIRST, "O_ORDERDATE" DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY) AS "t5"