SELECT COALESCE("t10"."P_PARTKEY", "t10"."P_PARTKEY") AS "P_PARTKEY", "t10"."DETAILED_INFO", "t10"."SUPPLIER_INFO", "t10"."CUSTOMER_SUMMARY", "t10"."S_SUPPKEY", "t10"."C_CUSTKEY"
FROM (SELECT "t5"."P_PARTKEY", "t5"."DETAILED_INFO", "t5"."SUPPLIER_INFO", "t8"."CUSTOMER_SUMMARY", "t5"."S_SUPPKEY", "t8"."C_CUSTKEY"
FROM (SELECT "t3"."P_PARTKEY", "t3"."P_NAME", "t3"."P_MFGR", "t3"."P_RETAILPRICE", "t3"."P_COMMENT", "t3"."PS_SUPPLYCOST", "t3"."DETAILED_INFO", "t1"."S_SUPPKEY", "t1"."S_NAME", "t1"."S_ADDRESS", "t1"."S_PHONE", "t1"."SUPPLIER_INFO", MOD("t3"."P_PARTKEY", 10) AS "$f12"
FROM (SELECT "supplier"."s_suppkey" AS "S_SUPPKEY", "supplier"."s_name" AS "S_NAME", "supplier"."s_address" AS "S_ADDRESS", "supplier"."s_phone" AS "S_PHONE", CONCAT("supplier"."s_name", ' - Address: ', "supplier"."s_address", ' | Phone: ', "supplier"."s_phone") AS "SUPPLIER_INFO", MOD("supplier"."s_suppkey", 10) AS "$f5"
FROM "s1"
INNER JOIN "TPCH"."supplier" ON "s1"."n_nationkey" = "supplier"."s_nationkey") AS "t1"
INNER JOIN (SELECT "t2"."p_partkey" AS "P_PARTKEY", "t2"."p_name" AS "P_NAME", "t2"."p_mfgr" AS "P_MFGR", "t2"."p_retailprice" AS "P_RETAILPRICE", "t2"."p_comment" AS "P_COMMENT", "partsupp"."ps_supplycost" AS "PS_SUPPLYCOST", CONCAT("t2"."p_name", ' ', "t2"."p_mfgr", ' - Price: ', CAST("t2"."p_retailprice" AS VARCHAR CHARACTER SET "ISO-8859-1"), ' | Comment: ', "t2"."p_comment") AS "DETAILED_INFO", MOD("t2"."p_partkey", 10) AS "$f7"
FROM (SELECT *
FROM "TPCH"."part"
WHERE "p_size" >= 10 AND "p_size" <= 20) AS "t2"
INNER JOIN "TPCH"."partsupp" ON "t2"."p_partkey" = "partsupp"."ps_partkey") AS "t3" ON "t1"."$f5" = "t3"."$f7"
WHERE "t3"."PS_SUPPLYCOST" < 500.00) AS "t5"
INNER JOIN (SELECT "t6"."c_custkey" AS "C_CUSTKEY", "t6"."c_name" AS "C_NAME", "t6"."c_acctbal" AS "C_ACCTBAL", SUM("orders"."o_totalprice") AS "TOTAL_SPENT", COUNT(*) AS "ORDER_COUNT", CONCAT("t6"."c_name", ' - Total Spent: ', CAST(SUM("orders"."o_totalprice") AS VARCHAR CHARACTER SET "ISO-8859-1"), ' | Orders: ', CAST(COUNT(*) AS VARCHAR CHARACTER SET "ISO-8859-1")) AS "CUSTOMER_SUMMARY", MOD("t6"."c_custkey", 10) AS "$f6"
FROM (SELECT *
FROM "TPCH"."customer"
WHERE "c_acctbal" > 1000.00) AS "t6"
INNER JOIN "TPCH"."orders" ON "t6"."c_custkey" = "orders"."o_custkey"
GROUP BY "t6"."c_custkey", "t6"."c_name", "t6"."c_acctbal") AS "t8" ON "t5"."$f12" = "t8"."$f6"
ORDER BY "t5"."P_PARTKEY", "t5"."S_SUPPKEY", "t8"."C_CUSTKEY") AS "t10"