SELECT COALESCE("P_PARTKEY", "P_PARTKEY") AS "P_PARTKEY", "AVG_NAME_LENGTH", "AVG_COMMENT_LENGTH", "TOTAL_RECORDS", "AGGREGATED_STRINGS"
FROM (SELECT "P_PARTKEY", AVG("NAME_LENGTH") AS "AVG_NAME_LENGTH", AVG("COMMENT_LENGTH") AS "AVG_COMMENT_LENGTH", COUNT(*) AS "TOTAL_RECORDS", LISTAGG("CONCATENATED_STRING", "FD_COL_4") AS "AGGREGATED_STRINGS"
FROM (SELECT *
FROM "s1"
UNION ALL
SELECT "t3"."ps_partkey" AS "P_PARTKEY", LENGTH("supplier"."s_name") AS "NAME_LENGTH", LENGTH("supplier"."s_comment") AS "COMMENT_LENGTH", 'Supplier Name: ' || "supplier"."s_name" || ' | Comment: ' || "supplier"."s_comment" AS "CONCATENATED_STRING", '; ' AS "$f4"
FROM "TPCH"."supplier"
INNER JOIN (SELECT *
FROM "TPCH"."partsupp"
WHERE "ps_availqty" > 0) AS "t3" ON "supplier"."s_suppkey" = "t3"."ps_suppkey") AS "t6"
GROUP BY "P_PARTKEY"
ORDER BY 4 DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY) AS "t8"