SELECT COALESCE("SUPPLIER_INFO", "SUPPLIER_INFO") AS "SUPPLIER_INFO", "UNIQUE_PARTS", "TOTAL_AVAILABLE_QUANTITY", "TOTAL_SUPPLY_COST"
FROM (SELECT "SUPPLIER_INFO", "UNIQUE_PARTS", "TOTAL_AVAILABLE_QUANTITY", "TOTAL_SUPPLY_COST"
FROM "s1"
ORDER BY "TOTAL_SUPPLY_COST" DESC NULLS FIRST, "UNIQUE_PARTS") AS "t6"