SELECT COALESCE("SUPPLIER_NAME", "SUPPLIER_NAME") AS "SUPPLIER_NAME", "TOTAL_PARTS", "TOTAL_INVENTORY_VALUE", "PART_NAMES_LIST", "UNIQUE_BRANDS"
FROM "s1"
ORDER BY "TOTAL_INVENTORY_VALUE" DESC NULLS FIRST