SELECT COALESCE("DETAILED_INFO", "DETAILED_INFO") AS "DETAILED_INFO", "TOTAL_AVAILABLE_QUANTITY", "AVERAGE_SUPPLY_COST", "TOTAL_ORDERS"
FROM (SELECT "s_name", "n_name", "p_name", "ps_comment", ANY_VALUE("FD_COL_4") AS "DETAILED_INFO", SUM("ps_availqty") AS "TOTAL_AVAILABLE_QUANTITY", AVG("ps_supplycost") AS "AVERAGE_SUPPLY_COST", COUNT(DISTINCT "o_orderkey") AS "TOTAL_ORDERS"
FROM "s1"
GROUP BY "s_name", "n_name", "p_name", "ps_comment"
ORDER BY 8 DESC NULLS FIRST, 7
FETCH NEXT 10 ROWS ONLY) AS "t5"