SELECT COALESCE("P_NAME", "P_NAME") AS "P_NAME", "RETURNED_QUANTITY", "TOTAL_ORDERS", "MAX_PRICE", "SUPPLIER_DETAILS"
FROM (SELECT "P_NAME", SUM("FD_COL_1") AS "RETURNED_QUANTITY", COUNT(DISTINCT "o_orderkey") AS "TOTAL_ORDERS", MAX("l_extendedprice") AS "MAX_PRICE", LISTAGG(DISTINCT "FD_COL_4", "FD_COL_5") AS "SUPPLIER_DETAILS"
FROM "s1"
GROUP BY "P_NAME"
HAVING SUM("FD_COL_1") > 0.00
ORDER BY 3 DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY) AS "t5"