SELECT COALESCE("t10"."N_NAME", "t10"."N_NAME") AS "N_NAME", "t10"."R_NAME", "t10"."TOTAL_SUPPLY_VALUE", "t10"."TOTAL_ORDERS", "t10"."AVG_ORDER_VALUE"
FROM (SELECT "t5"."n_name" AS "N_NAME", "t5"."r_name" AS "R_NAME", CASE WHEN SUM("t5"."TOTAL_SUPPLY_VALUE") IS NOT NULL THEN CAST(SUM("t5"."TOTAL_SUPPLY_VALUE") AS DECIMAL(19, 2)) ELSE 0.00 END AS "TOTAL_SUPPLY_VALUE", CASE WHEN SUM("t7"."TOTAL_ORDERS") IS NOT NULL THEN CAST(SUM("t7"."TOTAL_ORDERS") AS BIGINT) ELSE 0 END AS "TOTAL_ORDERS", CASE WHEN AVG("t7"."AVG_ORDER_VALUE") IS NOT NULL THEN CAST(AVG("t7"."AVG_ORDER_VALUE") AS DECIMAL(15, 2)) ELSE 0.00 END AS "AVG_ORDER_VALUE"
FROM (SELECT "t3"."n_nationkey", "t3"."n_name", "t3"."n_regionkey", "t3"."n_comment", "t3"."r_regionkey", "t3"."r_name", "t3"."r_comment", "t2"."PS_SUPPKEY", "t2"."TOTAL_SUPPLY_VALUE", "t2"."PART_COUNT", CAST("t3"."n_nationkey" AS BIGINT) AS "n_nationkey0"
FROM (SELECT "partsupp"."ps_suppkey" AS "PS_SUPPKEY", SUM("partsupp"."ps_supplycost" * "partsupp"."ps_availqty") AS "TOTAL_SUPPLY_VALUE", COUNT(DISTINCT "partsupp"."ps_partkey") AS "PART_COUNT"
FROM (SELECT *
FROM "TPCH"."supplier"
WHERE "s_acctbal" > 10000.00) AS "t0"
INNER JOIN "TPCH"."partsupp" ON "t0"."s_suppkey" = "partsupp"."ps_suppkey"
GROUP BY "partsupp"."ps_suppkey") AS "t2"
RIGHT JOIN (SELECT "nation"."n_nationkey", "nation"."n_name", "nation"."n_regionkey", "nation"."n_comment", "region"."r_regionkey", "region"."r_name", "region"."r_comment", CAST("nation"."n_nationkey" AS BIGINT) AS "n_nationkey0"
FROM "TPCH"."region"
INNER JOIN "TPCH"."nation" ON "region"."r_regionkey" = "nation"."n_regionkey") AS "t3" ON "t2"."PS_SUPPKEY" = "t3"."n_nationkey0"
WHERE "t3"."r_name" LIKE 'Europe%') AS "t5"
LEFT JOIN (SELECT "c_custkey", "c_name", COUNT("o_orderkey") AS "TOTAL_ORDERS", AVG("o_totalprice") AS "AVG_ORDER_VALUE"
FROM "s1"
GROUP BY "c_custkey", "c_name"
HAVING COUNT("o_orderkey") > 5) AS "t7" ON "t5"."n_nationkey0" = "t7"."c_custkey"
GROUP BY "t5"."n_name", "t5"."r_name"
ORDER BY 3 DESC NULLS FIRST, 4 DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY) AS "t10"