SELECT COALESCE("t11"."CUSTOMER_NAME", "t11"."CUSTOMER_NAME") AS "CUSTOMER_NAME", "t11"."TOTAL_CUSTOMER_SPENT", "t11"."SUPPLIER_NAME", "t11"."AVG_SUPPLY_COST", "t11"."SUPPLIED_PARTS"
FROM (SELECT "t8"."c_name" AS "CUSTOMER_NAME", "t8"."TOTAL_CUSTOMER_SPENT", "t9"."s_name" AS "SUPPLIER_NAME", "t9"."AVG_SUPPLY_COST", "t9"."SUPPLIED_PARTS"
FROM (SELECT AVG("t5"."TOTAL_SPENT") AS "EXPR$0"
FROM (SELECT "customer0"."c_custkey" AS "C_CUSTKEY", "customer0"."c_name" AS "C_NAME", "t3"."o_orderkey" AS "O_ORDERKEY", "t3"."o_orderdate" AS "O_ORDERDATE", SUM("lineitem0"."l_extendedprice" * (1 - "lineitem0"."l_discount")) AS "TOTAL_SPENT", SUM("lineitem0"."l_quantity") AS "TOTAL_ITEMS"
FROM "TPCH"."lineitem" AS "lineitem0"
INNER JOIN ("TPCH"."customer" AS "customer0" INNER JOIN (SELECT *
FROM "TPCH"."orders"
WHERE "o_orderdate" >= DATE '1996-01-01' AND "o_orderdate" <= DATE '1996-12-31') AS "t3" ON "customer0"."c_custkey" = "t3"."o_custkey") ON "lineitem0"."l_orderkey" = "t3"."o_orderkey"
GROUP BY "customer0"."c_custkey", "customer0"."c_name", "t3"."o_orderkey", "t3"."o_orderdate") AS "t5") AS "t6"
INNER JOIN (SELECT "customer1"."c_custkey", "customer1"."c_name", SUM("s1"."TOTAL_SPENT") AS "TOTAL_CUSTOMER_SPENT"
FROM "TPCH"."customer" AS "customer1"
INNER JOIN "s1" ON "customer1"."c_custkey" = "s1"."C_CUSTKEY"
GROUP BY "customer1"."c_custkey", "customer1"."c_name"
ORDER BY 3 DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY) AS "t8" ON "t6"."EXPR$0" < "t8"."TOTAL_CUSTOMER_SPENT"
CROSS JOIN (SELECT "supplier"."s_suppkey", "supplier"."s_name", AVG("partsupp"."ps_supplycost") AS "AVG_SUPPLY_COST", COUNT(DISTINCT "partsupp"."ps_partkey") AS "SUPPLIED_PARTS"
FROM "TPCH"."partsupp"
RIGHT JOIN "TPCH"."supplier" ON "partsupp"."ps_suppkey" = "supplier"."s_suppkey"
GROUP BY "supplier"."s_suppkey", "supplier"."s_name") AS "t9"
ORDER BY "t8"."TOTAL_CUSTOMER_SPENT" DESC NULLS FIRST, "t9"."AVG_SUPPLY_COST") AS "t11"