SELECT COALESCE("customer"."c_custkey", "customer"."c_custkey") AS "c_custkey", "customer"."c_name", "customer"."c_address", "customer"."c_nationkey", "customer"."c_phone", "customer"."c_acctbal", "customer"."c_mktsegment", "customer"."c_comment", "t"."o_custkey" AS "O_CUSTKEY", "t"."AVG_TOTALPRICE", "t0"."c_custkey" AS "C_CUSTKEY_", "t0"."ORDER_COUNT", "t0"."MAX_ORDER_PRICE", "t5"."PS_SUPPKEY", "t5"."TOTAL_SUPPLYCOST"
FROM "TPCH"."customer"
LEFT JOIN (SELECT "o_custkey", AVG("o_totalprice") AS "AVG_TOTALPRICE"
FROM "TPCH"."orders"
GROUP BY "o_custkey") AS "t" ON "customer"."c_custkey" = "t"."o_custkey"
LEFT JOIN (SELECT "customer0"."c_custkey", COUNT("orders0"."o_orderkey") AS "ORDER_COUNT", MAX("orders0"."o_totalprice") AS "MAX_ORDER_PRICE"
FROM "TPCH"."orders" AS "orders0"
RIGHT JOIN "TPCH"."customer" AS "customer0" ON "orders0"."o_custkey" = "customer0"."c_custkey"
GROUP BY "customer0"."c_custkey") AS "t0" ON "customer"."c_custkey" = "t0"."c_custkey"
LEFT JOIN (SELECT "t4"."PS_SUPPKEY", "t4"."TOTAL_SUPPLYCOST"
FROM (SELECT AVG("ps_supplycost" * "ps_availqty") AS "EXPR$0"
FROM "TPCH"."partsupp") AS "t2"
INNER JOIN (SELECT "ps_suppkey" AS "PS_SUPPKEY", SUM("ps_supplycost" * "ps_availqty") AS "TOTAL_SUPPLYCOST"
FROM "TPCH"."partsupp"
GROUP BY "ps_suppkey") AS "t4" ON "t2"."EXPR$0" < "t4"."TOTAL_SUPPLYCOST") AS "t5" ON "t0"."c_custkey" = "t5"."PS_SUPPKEY"