SELECT COALESCE("SUPPLIER_NAME", "SUPPLIER_NAME") AS "SUPPLIER_NAME", "CUSTOMER_NAME", "REVENUE", "NUMBER_OF_ORDERS"
FROM (SELECT "S_NAME", "C_NAME", ANY_VALUE("S_NAME") AS "SUPPLIER_NAME", ANY_VALUE("C_NAME") AS "CUSTOMER_NAME", SUM("FD_COL_2") AS "REVENUE", COUNT(DISTINCT "o_orderkey") AS "NUMBER_OF_ORDERS"
FROM "s1"
GROUP BY "S_NAME", "C_NAME"
ORDER BY 5 DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY) AS "t9"