SELECT COALESCE("C_NAME", "C_NAME") AS "C_NAME", "REGION_NAME", "NATION_NAME", "TOTAL_SUPPLY_COST", "TOTAL_AVAILABLE_QUANTITY", "CUSTOMER_SEGMENT"
FROM (SELECT "C_NAME", "REGION_NAME", "NATION_NAME", "CUSTOMER_SEGMENT", SUM("PS_SUPPLYCOST") AS "TOTAL_SUPPLY_COST", SUM("FD_COL_5") AS "TOTAL_AVAILABLE_QUANTITY"
FROM "s1"
GROUP BY "C_NAME", "REGION_NAME", "NATION_NAME", "CUSTOMER_SEGMENT"
HAVING SUM("PS_SUPPLYCOST") > 5000.00
ORDER BY 5 DESC NULLS FIRST, "C_NAME") AS "t14"