SELECT COALESCE("t11"."P_NAME", "t11"."P_NAME") AS "P_NAME", "t11"."TOTAL_REVENUE", "t11"."SUPPLIER_REVENUE", "t11"."CUSTOMER_EXPENDITURE"
FROM (SELECT "t7"."P_NAME", "t7"."TOTAL_REVENUE", "t9"."SUPPLIER_REVENUE", "t3"."CUSTOMER_EXPENDITURE"
FROM (SELECT "customer"."c_custkey" AS "C_CUSTKEY", SUM("orders"."o_totalprice") AS "CUSTOMER_EXPENDITURE", SUM("orders"."o_totalprice") > 1000.00 AS "$f2"
FROM "TPCH"."customer"
INNER JOIN ("s1" INNER JOIN "TPCH"."orders" ON "s1"."l_orderkey" = "orders"."o_orderkey") ON "customer"."c_custkey" = "orders"."o_custkey"
GROUP BY "customer"."c_custkey"
HAVING SUM("orders"."o_totalprice") > 1000.00) AS "t3"
CROSS JOIN ((SELECT "part0"."p_partkey" AS "P_PARTKEY", "part0"."p_name" AS "P_NAME", "t5"."TOTAL_REVENUE"
FROM (SELECT "part"."p_partkey" AS "P_PARTKEY", SUM("s10"."l_extendedprice" * (1 - "s10"."l_discount")) AS "TOTAL_REVENUE"
FROM "TPCH"."part"
INNER JOIN "s1" AS "s10" ON "part"."p_partkey" = "s10"."l_partkey"
GROUP BY "part"."p_partkey") AS "t5"
INNER JOIN "TPCH"."part" AS "part0" ON "t5"."P_PARTKEY" = "part0"."p_partkey"
ORDER BY "t5"."TOTAL_REVENUE" DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY) AS "t7" INNER JOIN (SELECT "supplier"."s_suppkey" AS "S_SUPPKEY", SUM("s11"."l_extendedprice" * (1 - "s11"."l_discount")) AS "SUPPLIER_REVENUE"
FROM "TPCH"."supplier"
INNER JOIN ("TPCH"."partsupp" INNER JOIN "s1" AS "s11" ON "partsupp"."ps_partkey" = "s11"."l_partkey") ON "supplier"."s_suppkey" = "partsupp"."ps_suppkey"
GROUP BY "supplier"."s_suppkey") AS "t9" ON "t7"."P_PARTKEY" = "t9"."S_SUPPKEY")
ORDER BY "t7"."TOTAL_REVENUE" DESC NULLS FIRST, "t9"."SUPPLIER_REVENUE" DESC NULLS FIRST, "t3"."CUSTOMER_EXPENDITURE" DESC NULLS FIRST) AS "t11"