SELECT COALESCE("NATION", "NATION") AS "NATION", "TOTAL_REVENUE", "AVG_SUPPLIER_BALANCE", "TOTAL_ORDERS", "TOTAL_CUSTOMERS"
FROM (SELECT "NATION", "TOTAL_REVENUE", "AVG_SUPPLIER_BALANCE", "TOTAL_ORDERS", "TOTAL_CUSTOMERS"
FROM "s1"
ORDER BY "TOTAL_REVENUE" DESC NULLS FIRST) AS "t5"