SELECT COALESCE("t12"."N_NAME", "t12"."N_NAME") AS "N_NAME", "t12"."TOTAL_ACCTBAL", "t12"."TOTAL_SUPPLYCOST", "t12"."TOTAL_ORDERVALUE", "t12"."TOTAL_LINES"
FROM (SELECT "s1"."N_NAME", "s1"."TOTAL_ACCTBAL", "s1"."TOTAL_SUPPLYCOST", "s1"."TOTAL_ORDERVALUE", "t10"."TOTAL_LINES"
FROM (SELECT "orders0"."o_orderkey" AS "O_ORDERKEY", COUNT(*) AS "TOTAL_LINES", COUNT(*) > 5 AS "$f2"
FROM "TPCH"."orders" AS "orders0"
INNER JOIN "TPCH"."lineitem" ON "orders0"."o_orderkey" = "lineitem"."l_orderkey"
GROUP BY "orders0"."o_orderkey"
HAVING COUNT(*) > 5) AS "t10",
"s1"
ORDER BY "s1"."TOTAL_ACCTBAL" DESC NULLS FIRST, "s1"."TOTAL_SUPPLYCOST" DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY) AS "t12"