SELECT COALESCE("REVENUE_TIER", "REVENUE_TIER") AS "REVENUE_TIER", COUNT(*) AS "NATION_COUNT", AVG("TOTAL_REVENUE") AS "AVG_REVENUE", SUM("TOTAL_ORDERS") AS "TOTAL_ORDERS_AGGREGATED"
FROM "s1"
GROUP BY "REVENUE_TIER"
ORDER BY "REVENUE_TIER" DESC NULLS FIRST