SELECT COALESCE("t7"."N_NAME", "t7"."N_NAME") AS "N_NAME", "t7"."C_NAME", "t7"."S_NAME", "t7"."TOTAL_COST", "t7"."ORDER_COUNT", "t7"."TOTAL_SPENT", "t7"."SUPPLIER_COUNT"
FROM (SELECT "t5"."n_name" AS "N_NAME", "t4"."c_name" AS "C_NAME", "t3"."S_NAME", "t3"."TOTAL_COST", "t4"."ORDER_COUNT", "t4"."TOTAL_SPENT", "t5"."SUPPLIER_COUNT"
FROM (SELECT "supplier"."s_suppkey" AS "S_SUPPKEY", "supplier"."s_name" AS "S_NAME", "supplier"."s_nationkey" AS "S_NATIONKEY", SUM("partsupp"."ps_supplycost" * "partsupp"."ps_availqty") AS "TOTAL_COST"
FROM "TPCH"."supplier"
INNER JOIN "TPCH"."partsupp" ON "supplier"."s_suppkey" = "partsupp"."ps_suppkey"
GROUP BY "supplier"."s_suppkey", "supplier"."s_name", "supplier"."s_nationkey"
HAVING SUM("partsupp"."ps_supplycost" * "partsupp"."ps_availqty") > 100000.00) AS "t3"
INNER JOIN ((SELECT "c_custkey", "c_name", "c_nationkey", COUNT(*) AS "ORDER_COUNT", SUM("o_totalprice") AS "TOTAL_SPENT"
FROM "s1"
GROUP BY "c_custkey", "c_name", "c_nationkey") AS "t4" INNER JOIN (SELECT "nation"."n_nationkey", "nation"."n_name", COUNT(*) AS "SUPPLIER_COUNT"
FROM "TPCH"."nation"
INNER JOIN "TPCH"."supplier" AS "supplier0" ON "nation"."n_nationkey" = "supplier0"."s_nationkey"
GROUP BY "nation"."n_nationkey", "nation"."n_name") AS "t5" ON "t4"."c_nationkey" = "t5"."n_nationkey") ON "t3"."S_NATIONKEY" = "t4"."c_nationkey"
ORDER BY "t4"."TOTAL_SPENT" DESC NULLS FIRST, "t3"."TOTAL_COST" DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY) AS "t7"