SELECT COALESCE("t6"."CUSTOMER_NAME", "t6"."CUSTOMER_NAME") AS "CUSTOMER_NAME", "t6"."TOTAL_ORDERS", "t6"."SUPPLIER_NAME", "t6"."SUPPLIER_COST"
FROM (SELECT "t3"."c_name" AS "CUSTOMER_NAME", "t3"."TOTAL_ORDER_VALUE" AS "TOTAL_ORDERS", "t4"."S_NAME" AS "SUPPLIER_NAME", "t4"."TOTAL_COST" AS "SUPPLIER_COST"
FROM (SELECT "customer"."c_custkey", "customer"."c_name", SUM("orders"."o_totalprice") AS "TOTAL_ORDER_VALUE"
FROM "TPCH"."customer"
INNER JOIN "TPCH"."orders" ON "customer"."c_custkey" = "orders"."o_custkey"
GROUP BY "customer"."c_custkey", "customer"."c_name"
HAVING SUM("orders"."o_totalprice") > 10000.00) AS "t3"
INNER JOIN (SELECT "S_SUPPKEY", "S_NAME", SUM("FD_COL_2") AS "TOTAL_COST"
FROM "s1"
GROUP BY "S_SUPPKEY", "S_NAME") AS "t4" ON "t3"."TOTAL_ORDER_VALUE" > "t4"."TOTAL_COST"
ORDER BY "t3"."TOTAL_ORDER_VALUE" DESC NULLS FIRST, "t4"."TOTAL_COST") AS "t6"