SELECT COALESCE("t13"."NATION_NAME", "t13"."NATION_NAME") AS "NATION_NAME", "t13"."SUPPLIER_COUNT", "t13"."TOTAL_SUPPLY_COST_PER_NATION", "t13"."LINE_ITEM_COUNT", "t13"."TOTAL_ORDER_VALUE", "t13"."O_ORDERSTATUS"
FROM (SELECT "t11"."n_name" AS "NATION_NAME", "t11"."SUPPLIER_COUNT", "t11"."TOTAL_SUPPLY_COST_PER_NATION", "t7"."LINE_ITEM_COUNT", "t7"."TOTAL_ORDER_VALUE", "t7"."O_ORDERSTATUS"
FROM (SELECT "t4"."O_ORDERKEY", "t4"."LINE_ITEM_COUNT", "t4"."TOTAL_ORDER_VALUE", "t4"."O_ORDERDATE", "t4"."O_ORDERSTATUS", "t4"."O_CUSTKEY", "t6"."$f1" AS "$f0"
FROM (SELECT "orders"."o_orderkey" AS "O_ORDERKEY", COUNT(*) AS "LINE_ITEM_COUNT", SUM("lineitem"."l_extendedprice") AS "TOTAL_ORDER_VALUE", "orders"."o_orderdate" AS "O_ORDERDATE", "orders"."o_orderstatus" AS "O_ORDERSTATUS", "orders"."o_custkey" AS "O_CUSTKEY"
FROM "TPCH"."orders"
INNER JOIN "TPCH"."lineitem" ON "orders"."o_orderkey" = "lineitem"."l_orderkey"
GROUP BY "orders"."o_orderkey", "orders"."o_custkey", "orders"."o_orderstatus", "orders"."o_orderdate") AS "t4"
LEFT JOIN (SELECT "c_custkey", SINGLE_VALUE("c_nationkey") AS "$f1"
FROM "TPCH"."customer"
GROUP BY "c_custkey") AS "t6" ON "t4"."O_CUSTKEY" = "t6"."c_custkey") AS "t7"
INNER JOIN (SELECT "nation"."n_nationkey", "nation"."n_name", "region"."r_regionkey", COUNT(DISTINCT "s1"."s_suppkey_") AS "SUPPLIER_COUNT", SUM("s1"."TOTAL_SUPPLY_COST") AS "TOTAL_SUPPLY_COST_PER_NATION"
FROM "TPCH"."region"
INNER JOIN "TPCH"."nation" ON "region"."r_regionkey" = "nation"."n_regionkey"
INNER JOIN "s1" ON "nation"."n_nationkey" = "s1"."s_nationkey_"
GROUP BY "region"."r_regionkey", "nation"."n_nationkey", "nation"."n_name"
HAVING SUM("s1"."TOTAL_SUPPLY_COST") > 10000.00) AS "t11" ON "t7"."$f0" = "t11"."n_nationkey"
ORDER BY "t7"."TOTAL_ORDER_VALUE" DESC NULLS FIRST, "t11"."SUPPLIER_COUNT") AS "t13"