SELECT COALESCE("REGION_NAME", "REGION_NAME") AS "REGION_NAME", "NATION_NAME", "TOTAL_ORDERS", "TOTAL_REVENUE", "TOTAL_SUPPLIER_COST"
FROM "s1"
ORDER BY "TOTAL_ORDERS" DESC NULLS FIRST, "TOTAL_SUPPLIER_COST" DESC NULLS FIRST