SELECT COALESCE("AVERAGE_SUPPLIER_COST", "AVERAGE_SUPPLIER_COST") AS "AVERAGE_SUPPLIER_COST", "TOTAL_SALES_VALUE"
FROM (SELECT "t7"."REGION_NAME", AVG("t7"."AVG_SUPPLY_COST") AS "AVERAGE_SUPPLIER_COST", SUM("t7"."TOTAL_ORDER_VALUE") AS "TOTAL_SALES_VALUE"
FROM (SELECT "t4"."p_partkey", "t4"."p_name", "t4"."p_brand", "t6"."CUSTOMER_COUNT", "t6"."TOTAL_ORDER_VALUE", MAX("s1"."r_name") AS "REGION_NAME", AVG("t4"."TOTAL_SUPPLY_COST") AS "AVG_SUPPLY_COST"
FROM "s1"
INNER JOIN "TPCH"."supplier" ON "s1"."n_nationkey" = "supplier"."s_nationkey"
INNER JOIN (SELECT "part"."p_partkey", "part"."p_name", "part"."p_mfgr", "part"."p_brand", "part"."p_type", "part"."p_size", "part"."p_container", "part"."p_retailprice", "part"."p_comment", "t3"."S_SUPPKEY", "t3"."S_NAME", "t3"."S_NATIONKEY", "t3"."TOTAL_SUPPLY_COST"
FROM (SELECT "supplier0"."s_suppkey" AS "S_SUPPKEY", "supplier0"."s_name" AS "S_NAME", "supplier0"."s_nationkey" AS "S_NATIONKEY", SUM("partsupp"."ps_supplycost" * "partsupp"."ps_availqty") AS "TOTAL_SUPPLY_COST", SUM("partsupp"."ps_supplycost" * "partsupp"."ps_availqty") > 10000.00 AS "$f4"
FROM "TPCH"."supplier" AS "supplier0"
INNER JOIN "TPCH"."partsupp" ON "supplier0"."s_suppkey" = "partsupp"."ps_suppkey"
GROUP BY "supplier0"."s_suppkey", "supplier0"."s_name", "supplier0"."s_nationkey"
HAVING SUM("partsupp"."ps_supplycost" * "partsupp"."ps_availqty") > 10000.00) AS "t3",
"TPCH"."part") AS "t4" ON "supplier"."s_suppkey" = "t4"."p_partkey"
INNER JOIN (SELECT "t5"."n_nationkey", "t5"."n_name", COUNT(DISTINCT "t5"."c_custkey") AS "CUSTOMER_COUNT", SUM("orders"."o_totalprice") AS "TOTAL_ORDER_VALUE"
FROM "TPCH"."orders"
RIGHT JOIN (SELECT "nation0"."n_nationkey", "nation0"."n_name", "nation0"."n_regionkey", "nation0"."n_comment", "customer"."c_custkey", "customer"."c_name", "customer"."c_address", "customer"."c_nationkey", "customer"."c_phone", "customer"."c_acctbal", "customer"."c_mktsegment", "customer"."c_comment"
FROM "TPCH"."customer"
RIGHT JOIN "TPCH"."nation" AS "nation0" ON "customer"."c_nationkey" = "nation0"."n_nationkey") AS "t5" ON "orders"."o_custkey" = "t5"."c_custkey"
GROUP BY "t5"."n_nationkey", "t5"."n_name") AS "t6" ON "s1"."n_nationkey" = "t6"."n_nationkey"
GROUP BY "t4"."p_partkey", "t4"."p_name", "t4"."p_brand", "t6"."CUSTOMER_COUNT", "t6"."TOTAL_ORDER_VALUE") AS "t7"
GROUP BY "t7"."REGION_NAME"
ORDER BY 3 DESC NULLS FIRST) AS "t9"