SELECT COALESCE("t2"."MOVIE_TITLE", "t2"."MOVIE_TITLE") AS "MOVIE_TITLE", "t2"."PRODUCTION_YEAR", "t2"."CAST_COUNT", "t2"."CAST_NAMES", "t8"."COMPANY_COUNT", "t8"."COMPANY_NAMES"
FROM (SELECT ANY_VALUE("aka_title"."title") AS "MOVIE_TITLE", "aka_title"."production_year" AS "PRODUCTION_YEAR", ANY_VALUE("aka_title"."id") AS "MOVIE_ID", COUNT(DISTINCT "cast_info"."person_id") AS "CAST_COUNT", LISTAGG(DISTINCT "aka_name"."name", ', ') AS "CAST_NAMES", LISTAGG(DISTINCT "keyword"."keyword", ', ') AS "KEYWORDS"
FROM "aka_title"
LEFT JOIN "movie_keyword" ON "aka_title"."id" = "movie_keyword"."movie_id"
LEFT JOIN "keyword" ON "movie_keyword"."keyword_id" = "keyword"."id"
LEFT JOIN "cast_info" ON "aka_title"."id" = "cast_info"."movie_id"
LEFT JOIN "aka_name" ON "cast_info"."person_id" = "aka_name"."person_id"
WHERE "aka_title"."production_year" >= 2000 AND "aka_title"."production_year" <= 2020
GROUP BY "aka_title"."title", "aka_title"."production_year", "aka_title"."id") AS "t2"
LEFT JOIN (SELECT "t6"."MOVIE_ID", COUNT(DISTINCT "movie_companies"."company_id") AS "COMPANY_COUNT", LISTAGG(DISTINCT "company_name"."name", ', ') AS "COMPANY_NAMES"
FROM "movie_companies"
INNER JOIN "company_name" ON "movie_companies"."company_id" = "company_name"."id"
INNER JOIN (SELECT ANY_VALUE("aka_title0"."title") AS "MOVIE_TITLE", "aka_title0"."production_year" AS "PRODUCTION_YEAR", ANY_VALUE("aka_title0"."id") AS "MOVIE_ID", COUNT(DISTINCT "cast_info0"."person_id") AS "CAST_COUNT", LISTAGG(DISTINCT "aka_name0"."name", ', ') AS "CAST_NAMES", LISTAGG(DISTINCT "keyword0"."keyword", ', ') AS "KEYWORDS"
FROM "aka_title" AS "aka_title0"
LEFT JOIN "movie_keyword" AS "movie_keyword0" ON "aka_title0"."id" = "movie_keyword0"."movie_id"
LEFT JOIN "keyword" AS "keyword0" ON "movie_keyword0"."keyword_id" = "keyword0"."id"
LEFT JOIN "cast_info" AS "cast_info0" ON "aka_title0"."id" = "cast_info0"."movie_id"
LEFT JOIN "aka_name" AS "aka_name0" ON "cast_info0"."person_id" = "aka_name0"."person_id"
WHERE "aka_title0"."production_year" >= 2000 AND "aka_title0"."production_year" <= 2020
GROUP BY "aka_title0"."title", "aka_title0"."production_year", "aka_title0"."id") AS "t6" ON "movie_companies"."movie_id" = "t6"."MOVIE_ID"
GROUP BY "t6"."MOVIE_ID") AS "t8" ON "t2"."MOVIE_ID" = "t8"."MOVIE_ID"