SELECT COALESCE("t92"."MOVIE_ID", "t92"."MOVIE_ID") AS "MOVIE_ID", "t92"."TITLE", "t92"."PRODUCTION_YEAR", "t92"."CAST_COUNT", "t92"."MOVIE_KEYWORDS", "t92"."AVG_CAST_COUNT", "t92"."UNIQUE_ACTORS"
FROM (SELECT "t86"."MOVIE_ID", "t86"."TITLE", "t86"."PRODUCTION_YEAR", "t86"."CAST_COUNT", "t86"."MOVIE_KEYWORDS", "t86"."EXPR$0" AS "AVG_CAST_COUNT", CASE WHEN "t89"."EXPR$0" IS NULL THEN 0 ELSE "t89"."EXPR$0" END AS "UNIQUE_ACTORS"
FROM (SELECT "t59"."MOVIE_ID", "t59"."TITLE", "t59"."CAST_COUNT", "t59"."MOVIE_KEYWORDS", "t59"."PRODUCTION_YEAR", "t85"."EXPR$0"
FROM (SELECT "t58"."MOVIE_ID", "t58"."TITLE", "t58"."CAST_COUNT", "t58"."MOVIE_KEYWORDS", "t58"."PRODUCTION_YEAR"
FROM (SELECT AVG(CASE WHEN "t47"."COUNT" IS NOT NULL THEN CAST("t47"."COUNT" AS BIGINT) ELSE 0 END) AS "EXPR$0"
FROM (SELECT "t46"."MOVIE_ID", "t46"."TITLE", "t46"."PRODUCTION_YEAR", "t46"."RAN", "t45"."movie_id" AS "MOVIE_ID0", "t45"."COUNT"
FROM (SELECT "movie_id", COUNT(*) AS "COUNT"
FROM "IMDB"."cast_info"
GROUP BY "movie_id") AS "t45"
RIGHT JOIN (SELECT "id" AS "MOVIE_ID", "title" AS "TITLE", "production_year" AS "PRODUCTION_YEAR", ROW_NUMBER() OVER (PARTITION BY "production_year" ORDER BY "id") AS "RAN"
FROM "IMDB"."aka_title") AS "t46" ON "t45"."movie_id" = "t46"."MOVIE_ID") AS "t47"
LEFT JOIN (SELECT "movie_keyword4"."movie_id" AS "MOVIE_ID", LISTAGG("keyword4"."keyword", ', ') AS "KEYWORDS"
FROM "IMDB"."keyword" AS "keyword4"
INNER JOIN "IMDB"."movie_keyword" AS "movie_keyword4" ON "keyword4"."id" = "movie_keyword4"."keyword_id"
GROUP BY "movie_keyword4"."movie_id") AS "t49" ON "t47"."MOVIE_ID" = "t49"."MOVIE_ID") AS "t51"
INNER JOIN (SELECT "t55"."MOVIE_ID", "t55"."TITLE", CASE WHEN "t55"."COUNT" IS NOT NULL THEN CAST("t55"."COUNT" AS BIGINT) ELSE 0 END AS "CAST_COUNT", CASE WHEN "t57"."KEYWORDS" IS NOT NULL THEN CAST("t57"."KEYWORDS" AS VARCHAR CHARACTER SET "ISO-8859-1") ELSE '' END AS "MOVIE_KEYWORDS", "t55"."PRODUCTION_YEAR"
FROM (SELECT "t54"."MOVIE_ID", "t54"."TITLE", "t54"."PRODUCTION_YEAR", "t54"."RAN", "t53"."movie_id" AS "MOVIE_ID0", "t53"."COUNT"
FROM (SELECT "movie_id", COUNT(*) AS "COUNT"
FROM "IMDB"."cast_info"
GROUP BY "movie_id") AS "t53"
RIGHT JOIN (SELECT "id" AS "MOVIE_ID", "title" AS "TITLE", "production_year" AS "PRODUCTION_YEAR", ROW_NUMBER() OVER (PARTITION BY "production_year" ORDER BY "id") AS "RAN"
FROM "IMDB"."aka_title") AS "t54" ON "t53"."movie_id" = "t54"."MOVIE_ID") AS "t55"
LEFT JOIN (SELECT "movie_keyword5"."movie_id" AS "MOVIE_ID", LISTAGG("keyword5"."keyword", ', ') AS "KEYWORDS"
FROM "IMDB"."keyword" AS "keyword5"
INNER JOIN "IMDB"."movie_keyword" AS "movie_keyword5" ON "keyword5"."id" = "movie_keyword5"."keyword_id"
GROUP BY "movie_keyword5"."movie_id") AS "t57" ON "t55"."MOVIE_ID" = "t57"."MOVIE_ID") AS "t58" ON "t51"."EXPR$0" < "t58"."CAST_COUNT") AS "t59"
LEFT JOIN (SELECT "t76"."PRODUCTION_YEAR", "t84"."EXPR$0"
FROM (SELECT "t74"."PRODUCTION_YEAR"
FROM (SELECT AVG(CASE WHEN "t63"."COUNT" IS NOT NULL THEN CAST("t63"."COUNT" AS BIGINT) ELSE 0 END) AS "EXPR$0"
FROM (SELECT "t62"."MOVIE_ID", "t62"."TITLE", "t62"."PRODUCTION_YEAR", "t62"."RAN", "t61"."movie_id" AS "MOVIE_ID0", "t61"."COUNT"
FROM (SELECT "movie_id", COUNT(*) AS "COUNT"
FROM "IMDB"."cast_info"
GROUP BY "movie_id") AS "t61"
RIGHT JOIN (SELECT "id" AS "MOVIE_ID", "title" AS "TITLE", "production_year" AS "PRODUCTION_YEAR", ROW_NUMBER() OVER (PARTITION BY "production_year" ORDER BY "id") AS "RAN"
FROM "IMDB"."aka_title") AS "t62" ON "t61"."movie_id" = "t62"."MOVIE_ID") AS "t63"
LEFT JOIN (SELECT "movie_keyword6"."movie_id" AS "MOVIE_ID", LISTAGG("keyword6"."keyword", ', ') AS "KEYWORDS"
FROM "IMDB"."keyword" AS "keyword6"
INNER JOIN "IMDB"."movie_keyword" AS "movie_keyword6" ON "keyword6"."id" = "movie_keyword6"."keyword_id"
GROUP BY "movie_keyword6"."movie_id") AS "t65" ON "t63"."MOVIE_ID" = "t65"."MOVIE_ID") AS "t67"
INNER JOIN (SELECT "t71"."MOVIE_ID", "t71"."TITLE", CASE WHEN "t71"."COUNT" IS NOT NULL THEN CAST("t71"."COUNT" AS BIGINT) ELSE 0 END AS "CAST_COUNT", CASE WHEN "t73"."KEYWORDS" IS NOT NULL THEN CAST("t73"."KEYWORDS" AS VARCHAR CHARACTER SET "ISO-8859-1") ELSE '' END AS "MOVIE_KEYWORDS", "t71"."PRODUCTION_YEAR"
FROM (SELECT "t70"."MOVIE_ID", "t70"."TITLE", "t70"."PRODUCTION_YEAR", "t70"."RAN", "t69"."movie_id" AS "MOVIE_ID0", "t69"."COUNT"
FROM (SELECT "movie_id", COUNT(*) AS "COUNT"
FROM "IMDB"."cast_info"
GROUP BY "movie_id") AS "t69"
RIGHT JOIN (SELECT "id" AS "MOVIE_ID", "title" AS "TITLE", "production_year" AS "PRODUCTION_YEAR", ROW_NUMBER() OVER (PARTITION BY "production_year" ORDER BY "id") AS "RAN"
FROM "IMDB"."aka_title") AS "t70" ON "t69"."movie_id" = "t70"."MOVIE_ID") AS "t71"
LEFT JOIN (SELECT "movie_keyword7"."movie_id" AS "MOVIE_ID", LISTAGG("keyword7"."keyword", ', ') AS "KEYWORDS"
FROM "IMDB"."keyword" AS "keyword7"
INNER JOIN "IMDB"."movie_keyword" AS "movie_keyword7" ON "keyword7"."id" = "movie_keyword7"."keyword_id"
GROUP BY "movie_keyword7"."movie_id") AS "t73" ON "t71"."MOVIE_ID" = "t73"."MOVIE_ID") AS "t74" ON "t67"."EXPR$0" < "t74"."CAST_COUNT"
GROUP BY "t74"."PRODUCTION_YEAR") AS "t76"
LEFT JOIN (SELECT "t80"."PRODUCTION_YEAR", AVG(CASE WHEN "t80"."COUNT" IS NOT NULL THEN CAST("t80"."COUNT" AS BIGINT) ELSE 0 END) AS "EXPR$0"
FROM (SELECT "t79"."MOVIE_ID", "t79"."TITLE", "t79"."PRODUCTION_YEAR", "t79"."RAN", "t78"."movie_id" AS "MOVIE_ID0", "t78"."COUNT"
FROM (SELECT "movie_id", COUNT(*) AS "COUNT"
FROM "IMDB"."cast_info"
GROUP BY "movie_id") AS "t78"
RIGHT JOIN (SELECT "id" AS "MOVIE_ID", "title" AS "TITLE", "production_year" AS "PRODUCTION_YEAR", ROW_NUMBER() OVER (PARTITION BY "production_year" ORDER BY "id") AS "RAN"
FROM "IMDB"."aka_title") AS "t79" ON "t78"."movie_id" = "t79"."MOVIE_ID") AS "t80"
LEFT JOIN (SELECT "movie_keyword8"."movie_id" AS "MOVIE_ID", LISTAGG("keyword8"."keyword", ', ') AS "KEYWORDS"
FROM "IMDB"."keyword" AS "keyword8"
INNER JOIN "IMDB"."movie_keyword" AS "movie_keyword8" ON "keyword8"."id" = "movie_keyword8"."keyword_id"
GROUP BY "movie_keyword8"."movie_id") AS "t82" ON "t80"."MOVIE_ID" = "t82"."MOVIE_ID"
GROUP BY "t80"."PRODUCTION_YEAR") AS "t84" ON "t76"."PRODUCTION_YEAR" IS NOT DISTINCT FROM "t84"."PRODUCTION_YEAR") AS "t85" ON "t59"."PRODUCTION_YEAR" = "t85"."PRODUCTION_YEAR") AS "t86"
LEFT JOIN (SELECT "s1"."MOVIE_ID" AS "movie_id", CASE WHEN "t88"."EXPR$0" IS NOT NULL THEN "t88"."EXPR$0" ELSE 0 END AS "EXPR$0"
FROM "s1"
LEFT JOIN (SELECT "cast_info9"."movie_id", COUNT(DISTINCT "person_info"."id") AS "EXPR$0"
FROM "IMDB"."cast_info" AS "cast_info9"
INNER JOIN "IMDB"."person_info" ON "cast_info9"."person_id" = "person_info"."person_id"
GROUP BY "cast_info9"."movie_id") AS "t88" ON "s1"."MOVIE_ID" IS NOT DISTINCT FROM "t88"."movie_id") AS "t89" ON "t86"."MOVIE_ID" = "t89"."movie_id"
ORDER BY "t86"."PRODUCTION_YEAR" DESC NULLS FIRST, "t86"."CAST_COUNT" DESC NULLS FIRST
FETCH NEXT 100 ROWS ONLY) AS "t92"