SELECT COALESCE("t9"."TITLE", "t9"."TITLE") AS "TITLE", "t9"."PRODUCTION_YEAR", "t9"."ACTOR_COUNT", "t9"."MODERN_RATIO", "t9"."COMPANY_NAME"
FROM (SELECT "t7"."TITLE", "t7"."PRODUCTION_YEAR", "t7"."ACTOR_COUNT", "t7"."MODERN_RATIO", "company_name"."name" AS "COMPANY_NAME"
FROM "IMDB"."company_name"
INNER JOIN (SELECT "t6"."TITLE", "t6"."PRODUCTION_YEAR", "t6"."ACTOR_COUNT", "t6"."MODERN_RATIO", "movie_companies0"."id", "movie_companies0"."movie_id", "movie_companies0"."company_id", "movie_companies0"."company_type_id", "movie_companies0"."note"
FROM (SELECT "t3"."TITLE", "t3"."PRODUCTION_YEAR", "t3"."ACTOR_COUNT", "t3"."MODERN_RATIO", "t5"."$f2" AS "$f0"
FROM (SELECT "title"."title" AS "TITLE", "title"."production_year" AS "PRODUCTION_YEAR", COUNT(DISTINCT "s1"."person_id") AS "ACTOR_COUNT", AVG(CASE WHEN "title"."production_year" >= 2000 THEN 1 ELSE 0 END) AS "MODERN_RATIO"
FROM "IMDB"."company_name" AS "company_name0"
INNER JOIN ("s1" INNER JOIN ("IMDB"."title" INNER JOIN "IMDB"."movie_companies" ON "title"."id" = "movie_companies"."movie_id") ON "s1"."movie_id" = "title"."id") ON "company_name0"."id" = "movie_companies"."company_id"
GROUP BY "title"."id", "title"."title", "title"."production_year"
HAVING COUNT(DISTINCT "s1"."person_id") > 10) AS "t3"
LEFT JOIN (SELECT "title", "production_year", SINGLE_VALUE("id") AS "$f2"
FROM "IMDB"."title"
GROUP BY "title", "production_year") AS "t5" ON "t3"."TITLE" = "t5"."title" AND "t3"."PRODUCTION_YEAR" = "t5"."production_year") AS "t6"
INNER JOIN "IMDB"."movie_companies" AS "movie_companies0" ON "t6"."$f0" = "movie_companies0"."movie_id") AS "t7" ON "company_name"."id" = "t7"."company_id"
ORDER BY "t7"."ACTOR_COUNT" DESC NULLS FIRST, "t7"."PRODUCTION_YEAR"
FETCH NEXT 50 ROWS ONLY) AS "t9"