SELECT COALESCE("t5"."MOVIE_TITLE", "t5"."MOVIE_TITLE") AS "MOVIE_TITLE", "t5"."ACTOR_NAME", "t5"."CAST_TYPE", "t5"."MOVIE_INFO", "t5"."MOVIE_KEYWORD", "t5"."COMPANY_NAME", "t5"."PERSON_INFO", "t5"."production_year"
FROM (SELECT "t3"."title" AS "MOVIE_TITLE", "aka_name"."name" AS "ACTOR_NAME", "s1"."kind" AS "CAST_TYPE", "movie_info"."info" AS "MOVIE_INFO", "keyword"."keyword" AS "MOVIE_KEYWORD", "company_name"."name" AS "COMPANY_NAME", "person_info"."info" AS "PERSON_INFO", "t3"."production_year"
FROM (SELECT "id" AS "ID"
FROM "IMDB"."info_type"
WHERE "info" = 'Box Office') AS "t2"
INNER JOIN "IMDB"."movie_info" ON "t2"."ID" = "movie_info"."info_type_id"
INNER JOIN ("IMDB"."keyword" INNER JOIN "IMDB"."movie_keyword" ON "keyword"."id" = "movie_keyword"."keyword_id" INNER JOIN ("IMDB"."company_name" INNER JOIN "IMDB"."movie_companies" ON "company_name"."id" = "movie_companies"."company_id" INNER JOIN ("IMDB"."aka_name" INNER JOIN "IMDB"."person_info" ON "aka_name"."id" = "person_info"."person_id" INNER JOIN ("s1" INNER JOIN ("IMDB"."complete_cast" INNER JOIN (SELECT *
FROM "IMDB"."title"
WHERE "production_year" >= 2000) AS "t3" ON "complete_cast"."movie_id" = "t3"."id") ON "s1"."id00" = "complete_cast"."subject_id") ON "aka_name"."person_id" = "s1"."person_id") ON "movie_companies"."movie_id" = "t3"."id") ON "movie_keyword"."movie_id" = "t3"."id") ON "movie_info"."movie_id" = "t3"."id"
ORDER BY "t3"."production_year" DESC NULLS FIRST, "aka_name"."name") AS "t5"