SELECT COALESCE("P_PARTKEY", "P_PARTKEY") AS "P_PARTKEY", "P_NAME", "TOTAL_QUANTITY", "TOTAL_REVENUE", "AVERAGE_DISCOUNT", "TOTAL_ORDERS"
FROM "s1"
ORDER BY "TOTAL_REVENUE" DESC NULLS FIRST
FETCH NEXT 100 ROWS ONLY