SELECT COALESCE("P_BRAND", "P_BRAND") AS "P_BRAND", "P_NAME", "TOTAL_COST", "ORDER_COUNT"
FROM (SELECT "P_BRAND", "P_NAME", SUM("FD_COL_2") AS "TOTAL_COST", COUNT(DISTINCT "l_orderkey") AS "ORDER_COUNT"
FROM "s1"
GROUP BY "P_BRAND", "P_NAME"
ORDER BY 3 DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY) AS "t3"