SELECT COALESCE("P_BRAND", "P_BRAND") AS "P_BRAND", "P_TYPE", "TOTAL_QUANTITY", "AVG_PRICE"
FROM (SELECT "P_BRAND", "P_TYPE", SUM("l_quantity") AS "TOTAL_QUANTITY", AVG("l_extendedprice") AS "AVG_PRICE"
FROM "s1"
GROUP BY "P_BRAND", "P_TYPE"
ORDER BY 3 DESC NULLS FIRST
FETCH NEXT 100 ROWS ONLY) AS "t3"