SELECT COALESCE("P_BRAND", "P_BRAND") AS "P_BRAND", "P_TYPE", "TOTAL_AVAIL_QTY", "AVG_SUPPLY_COST"
FROM (SELECT "P_BRAND", "P_TYPE", SUM("ps_availqty") AS "TOTAL_AVAIL_QTY", AVG("ps_supplycost") AS "AVG_SUPPLY_COST"
FROM "s1"
GROUP BY "P_BRAND", "P_TYPE"
ORDER BY 3 DESC NULLS FIRST, 4
FETCH NEXT 100 ROWS ONLY) AS "t2"