SELECT COALESCE("NATION", "NATION") AS "NATION", "ORDERS_COUNT", "TOTAL_REVENUE"
FROM (SELECT ANY_VALUE("n_name") AS "NATION", COUNT(DISTINCT "o_orderkey") AS "ORDERS_COUNT", SUM("l_extendedprice" * (1 - "l_discount")) AS "TOTAL_REVENUE"
FROM "s1"
WHERE "o_orderdate" >= DATE '1997-01-01' AND "o_orderdate" < DATE '1997-10-01'
GROUP BY "n_name"
ORDER BY 3 DESC NULLS FIRST) AS "t4"