SELECT COALESCE("S_SUPPKEY", "S_SUPPKEY") AS "S_SUPPKEY", "S_NAME", "TOTALSUPPLYCOST"
FROM (SELECT "S_SUPPKEY", "S_NAME", "TOTALSUPPLYCOST"
FROM "s1"
ORDER BY "TOTALSUPPLYCOST" DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY) AS "t4"
ORDER BY "TOTALSUPPLYCOST"