SELECT COALESCE("N_NAME", "N_NAME") AS "N_NAME", "TOTAL_REVENUE"
FROM (SELECT "N_NAME", SUM("FD_COL_1") AS "TOTAL_REVENUE"
FROM "s1"
GROUP BY "N_NAME"
ORDER BY 2 DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY) AS "t2"