SELECT COALESCE("P_PARTKEY", "P_PARTKEY") AS "P_PARTKEY", "P_NAME", "TOTAL_AVAILABLE_QUANTITY", "AVERAGE_SUPPLY_COST"
FROM "s1"
ORDER BY "TOTAL_AVAILABLE_QUANTITY" DESC NULLS FIRST
FETCH NEXT 100 ROWS ONLY