SELECT COALESCE("NATION_NAME", "NATION_NAME") AS "NATION_NAME", "TOTAL_REVENUE"
FROM (SELECT ANY_VALUE("n_name") AS "NATION_NAME", SUM("l_extendedprice" * (1 - "l_discount")) AS "TOTAL_REVENUE"
FROM "s1"
WHERE "o_orderdate" >= '1996-01-01' AND "o_orderdate" < '1997-01-01'
GROUP BY "n_name"
ORDER BY 2 DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY) AS "t4"