SELECT COALESCE("P_BRAND", "P_BRAND") AS "P_BRAND", "SUPPLIER_COUNT"
FROM (SELECT "P_BRAND", COUNT(DISTINCT "ps_suppkey") AS "SUPPLIER_COUNT"
FROM "s1"
GROUP BY "P_BRAND"
ORDER BY 2 DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY) AS "t2"