SELECT COALESCE("t7"."r_name", "t7"."r_name") AS "R_NAME", "t7"."TOTAL_SUPPLY_COST", "t13"."TOTAL_SPENT" AS "TOTAL_SPENT0", "t13"."C_CUSTKEY" AS "C_CUSTKEY0", "t7"."S_SUPPKEY"
FROM (SELECT "t1"."r_regionkey", "t1"."r_name", "t1"."r_comment", "t1"."n_nationkey", "t1"."n_name", "t1"."n_regionkey", "t1"."n_comment", "t1"."s_suppkey", "t1"."s_name", "t1"."s_address", "t1"."s_nationkey", "t1"."s_phone", "t1"."s_acctbal", "t1"."s_comment", "t1"."S_SUPPKEY", "t1"."S_NAME", "t1"."TOTAL_SUPPLY_COST", "t1"."UNIQUE_PARTS", "t6"."C_CUSTKEY", "t6"."C_NAME", "t6"."TOTAL_SPENT"
FROM (SELECT "region"."r_regionkey", "region"."r_name", "region"."r_comment", "nation"."n_nationkey", "nation"."n_name", "nation"."n_regionkey", "nation"."n_comment", "supplier"."s_suppkey", "supplier"."s_name", "supplier"."s_address", "supplier"."s_nationkey", "supplier"."s_phone", "supplier"."s_acctbal", "supplier"."s_comment", "t0"."S_SUPPKEY", "t0"."S_NAME", "t0"."TOTAL_SUPPLY_COST", "t0"."UNIQUE_PARTS", CAST("nation"."n_nationkey" AS BIGINT) AS "n_nationkey0"
FROM "TPCH"."region"
LEFT JOIN "TPCH"."nation" ON "region"."r_regionkey" = "nation"."n_regionkey"
LEFT JOIN "TPCH"."supplier" ON "nation"."n_nationkey" = "supplier"."s_nationkey"
LEFT JOIN (SELECT "supplier0"."s_suppkey" AS "S_SUPPKEY", "supplier0"."s_name" AS "S_NAME", SUM("partsupp"."ps_supplycost" * "partsupp"."ps_availqty") AS "TOTAL_SUPPLY_COST", COUNT(DISTINCT "partsupp"."ps_partkey") AS "UNIQUE_PARTS"
FROM "TPCH"."supplier" AS "supplier0"
INNER JOIN "TPCH"."partsupp" ON "supplier0"."s_suppkey" = "partsupp"."ps_suppkey"
GROUP BY "supplier0"."s_suppkey", "supplier0"."s_name") AS "t0" ON "supplier"."s_suppkey" = "t0"."S_SUPPKEY") AS "t1"
LEFT JOIN (SELECT "customer"."c_custkey" AS "C_CUSTKEY", "customer"."c_name" AS "C_NAME", SUM("t4"."TOTAL_DISCOUNTED_PRICE") AS "TOTAL_SPENT"
FROM "TPCH"."customer"
LEFT JOIN "TPCH"."orders" ON "customer"."c_custkey" = "orders"."o_custkey"
LEFT JOIN (SELECT "orders0"."o_orderkey" AS "O_ORDERKEY", "orders0"."o_orderdate" AS "O_ORDERDATE", SUM("lineitem"."l_extendedprice" * (1 - "lineitem"."l_discount")) AS "TOTAL_DISCOUNTED_PRICE"
FROM "TPCH"."orders" AS "orders0"
INNER JOIN "TPCH"."lineitem" ON "orders0"."o_orderkey" = "lineitem"."l_orderkey"
WHERE "orders0"."o_orderdate" >= '1997-01-01'
GROUP BY "orders0"."o_orderkey", "orders0"."o_orderdate") AS "t4" ON "orders"."o_orderkey" = "t4"."O_ORDERKEY"
GROUP BY "customer"."c_custkey", "customer"."c_name") AS "t6" ON "t1"."n_nationkey0" = "t6"."C_CUSTKEY") AS "t7"
LEFT JOIN (SELECT "customer0"."c_custkey" AS "C_CUSTKEY", "customer0"."c_name" AS "C_NAME", SUM("t10"."TOTAL_DISCOUNTED_PRICE") AS "TOTAL_SPENT", RANK() OVER (ORDER BY SUM("t10"."TOTAL_DISCOUNTED_PRICE") DESC NULLS FIRST) AS "SPEND_RANK"
FROM "TPCH"."customer" AS "customer0"
LEFT JOIN "TPCH"."orders" AS "orders1" ON "customer0"."c_custkey" = "orders1"."o_custkey"
LEFT JOIN (SELECT "orders2"."o_orderkey" AS "O_ORDERKEY", "orders2"."o_orderdate" AS "O_ORDERDATE", SUM("lineitem0"."l_extendedprice" * (1 - "lineitem0"."l_discount")) AS "TOTAL_DISCOUNTED_PRICE"
FROM "TPCH"."orders" AS "orders2"
INNER JOIN "TPCH"."lineitem" AS "lineitem0" ON "orders2"."o_orderkey" = "lineitem0"."l_orderkey"
WHERE "orders2"."o_orderdate" >= '1997-01-01'
GROUP BY "orders2"."o_orderkey", "orders2"."o_orderdate") AS "t10" ON "orders1"."o_orderkey" = "t10"."O_ORDERKEY"
GROUP BY "customer0"."c_custkey", "customer0"."c_name") AS "t13" ON "t7"."C_CUSTKEY" = "t13"."C_CUSTKEY"