SELECT COALESCE("R_NAME", "R_NAME") AS "R_NAME", "TOTAL_SUPPLIER_COST", "AVERAGE_CUSTOMER_SPENT", "CUSTOMER_COUNT"
FROM (SELECT "R_NAME", SUM("TOTAL_SUPPLY_COST") AS "TOTAL_SUPPLIER_COST", AVG("TOTAL_SPENT0") AS "AVERAGE_CUSTOMER_SPENT", COUNT(DISTINCT "C_CUSTKEY0") AS "CUSTOMER_COUNT"
FROM "s1"
GROUP BY "R_NAME"
HAVING COUNT(DISTINCT "S_SUPPKEY") > 5 AND AVG("TOTAL_SPENT0") IS NOT NULL
ORDER BY 2 DESC NULLS FIRST) AS "t19"