SELECT COALESCE("REGION", "REGION") AS "REGION", "TOTAL_SUPPLIERS", "TOTAL_SUPPLY_COST", "TOTAL_ORDER_PRICE", "AVG_ITEMS_PER_ORDER", "AVG_UNIQUE_PARTS_PER_SUPPLIER"
FROM (SELECT ANY_VALUE("R_NAME") AS "REGION", COUNT(DISTINCT "s_suppkey") AS "TOTAL_SUPPLIERS", SUM("FD_COL_2") AS "TOTAL_SUPPLY_COST", SUM("FD_COL_3") AS "TOTAL_ORDER_PRICE", AVG("NUMBER_OF_ITEMS") AS "AVG_ITEMS_PER_ORDER", AVG("UNIQUE_PARTS") AS "AVG_UNIQUE_PARTS_PER_SUPPLIER"
FROM "s1"
GROUP BY "R_NAME"
HAVING COUNT(DISTINCT "s_suppkey") > 0
ORDER BY 4 DESC NULLS FIRST, 6 DESC NULLS FIRST) AS "t10"