SELECT COALESCE("t"."R_NAME", "t"."R_NAME") AS "R_NAME", "supplier"."s_suppkey", CASE WHEN "t1"."TOTAL_SUPPLY_COST" IS NOT NULL THEN CAST("t1"."TOTAL_SUPPLY_COST" AS DECIMAL(19, 2)) ELSE 0.00 END AS "FD_COL_2", CASE WHEN "t4"."TOTAL_PRICE" IS NOT NULL THEN CAST("t4"."TOTAL_PRICE" AS DECIMAL(19, 4)) ELSE 0.0000 END AS "FD_COL_3", "t4"."NUMBER_OF_ITEMS", "t1"."UNIQUE_PARTS"
FROM (SELECT "nation"."n_nationkey" AS "N_NATIONKEY", "region"."r_name" AS "R_NAME", "nation"."n_name" AS "N_NAME"
FROM "TPCH"."nation"
LEFT JOIN "TPCH"."region" ON "nation"."n_regionkey" = "region"."r_regionkey") AS "t"
LEFT JOIN "TPCH"."supplier" ON "t"."N_NATIONKEY" = "supplier"."s_nationkey"
LEFT JOIN (SELECT "supplier0"."s_suppkey" AS "S_SUPPKEY", "supplier0"."s_name" AS "S_NAME", SUM("partsupp"."ps_supplycost" * "partsupp"."ps_availqty") AS "TOTAL_SUPPLY_COST", COUNT(DISTINCT "partsupp"."ps_partkey") AS "UNIQUE_PARTS"
FROM "TPCH"."supplier" AS "supplier0"
INNER JOIN "TPCH"."partsupp" ON "supplier0"."s_suppkey" = "partsupp"."ps_suppkey"
GROUP BY "supplier0"."s_suppkey", "supplier0"."s_name") AS "t1" ON "supplier"."s_suppkey" = "t1"."S_SUPPKEY"
LEFT JOIN (SELECT "orders"."o_orderkey" AS "O_ORDERKEY", "orders"."o_orderdate" AS "O_ORDERDATE", SUM("lineitem"."l_extendedprice" * (1 - "lineitem"."l_discount")) AS "TOTAL_PRICE", COUNT(*) AS "NUMBER_OF_ITEMS"
FROM "TPCH"."orders"
INNER JOIN "TPCH"."lineitem" ON "orders"."o_orderkey" = "lineitem"."l_orderkey"
WHERE "orders"."o_orderdate" >= DATE '1997-01-01'
GROUP BY "orders"."o_orderkey", "orders"."o_orderdate") AS "t4" ON "supplier"."s_suppkey" = "t4"."O_ORDERKEY"