SELECT COALESCE("t7"."REGION_NAME", "t7"."REGION_NAME") AS "REGION_NAME", "t7"."TOTAL_SALES", "t7"."N_NAME", "t7"."UNIQUE_SUPPLIERS", "t7"."AVG_ACCOUNT_BALANCE", "t7"."RICH_CUSTOMER_NAME", "t7"."CUSTOMER_CLASSIFICATION", CASE WHEN "t7"."TOTAL_SALES" IS NOT NULL AND CASE WHEN "t9"."AVG_ACCOUNT_BALANCE" = 0.00 THEN NULL ELSE "t9"."AVG_ACCOUNT_BALANCE" END IS NOT NULL THEN CAST("t7"."TOTAL_SALES" / CASE WHEN "t9"."AVG_ACCOUNT_BALANCE" = 0.00 THEN NULL ELSE "t9"."AVG_ACCOUNT_BALANCE" END AS DECIMAL(19, 6)) ELSE 0.000000 END AS "SALES_PER_AVG_BALANCE"
FROM (SELECT "t2"."REGION_NAME", "t2"."TOTAL_SALES", "t4"."N_NAME", "t4"."UNIQUE_SUPPLIERS", "t4"."AVG_ACCOUNT_BALANCE", "t6"."C_NAME" AS "RICH_CUSTOMER_NAME", "t6"."CUSTOMER_CLASSIFICATION"
FROM (SELECT ANY_VALUE("r_name") AS "REGION_NAME", SUM("o_totalprice") AS "TOTAL_SALES", ROW_NUMBER() OVER (ORDER BY SUM("o_totalprice") DESC NULLS FIRST) AS "RAN"
FROM "s1"
GROUP BY "r_name") AS "t2"
LEFT JOIN (SELECT "nation0"."n_name" AS "N_NAME", COUNT(DISTINCT "supplier0"."s_suppkey") AS "UNIQUE_SUPPLIERS", AVG("supplier0"."s_acctbal") AS "AVG_ACCOUNT_BALANCE"
FROM "TPCH"."nation" AS "nation0"
INNER JOIN "TPCH"."supplier" AS "supplier0" ON "nation0"."n_nationkey" = "supplier0"."s_nationkey"
GROUP BY "nation0"."n_name") AS "t4" ON "t2"."REGION_NAME" = "t4"."N_NAME"
LEFT JOIN (SELECT "c_custkey" AS "C_CUSTKEY", "c_name" AS "C_NAME", "c_acctbal" AS "C_ACCTBAL", CASE WHEN "c_acctbal" >= 1000.00 AND "c_acctbal" <= 2000.00 THEN 'Middle-Class' WHEN "c_acctbal" > 2000.00 THEN 'High-Class  ' ELSE 'Low-Class   ' END AS "CUSTOMER_CLASSIFICATION"
FROM "TPCH"."customer"
WHERE CASE WHEN "c_acctbal" IS NOT NULL THEN CAST("c_acctbal" AS DECIMAL(15, 2)) ELSE 0.00 END > 1500.00) AS "t6" ON "t4"."N_NAME" = "t6"."C_NAME") AS "t7"
LEFT JOIN (SELECT "nation1"."n_name" AS "N_NAME", COUNT(DISTINCT "supplier1"."s_suppkey") AS "UNIQUE_SUPPLIERS", AVG("supplier1"."s_acctbal") AS "AVG_ACCOUNT_BALANCE"
FROM "TPCH"."nation" AS "nation1"
INNER JOIN "TPCH"."supplier" AS "supplier1" ON "nation1"."n_nationkey" = "supplier1"."s_nationkey"
GROUP BY "nation1"."n_name") AS "t9" ON "t7"."N_NAME" = "t9"."N_NAME"
WHERE "t7"."TOTAL_SALES" < (((SELECT AVG(SUM("orders0"."o_totalprice"))
FROM "TPCH"."region" AS "region0"
LEFT JOIN "TPCH"."nation" AS "nation2" ON "region0"."r_regionkey" = "nation2"."n_regionkey"
LEFT JOIN "TPCH"."supplier" AS "supplier2" ON "nation2"."n_nationkey" = "supplier2"."s_nationkey"
LEFT JOIN "TPCH"."partsupp" AS "partsupp0" ON "supplier2"."s_suppkey" = "partsupp0"."ps_suppkey"
LEFT JOIN "TPCH"."part" AS "part0" ON "partsupp0"."ps_partkey" = "part0"."p_partkey"
LEFT JOIN "TPCH"."lineitem" AS "lineitem0" ON "part0"."p_partkey" = "lineitem0"."l_partkey"
LEFT JOIN "TPCH"."orders" AS "orders0" ON "lineitem0"."l_orderkey" = "orders0"."o_orderkey"
GROUP BY "region0"."r_name")))
ORDER BY "t7"."TOTAL_SALES" DESC NULLS FIRST, "t7"."UNIQUE_SUPPLIERS"