SELECT COALESCE("region"."r_regionkey", "region"."r_regionkey") AS "r_regionkey", "region"."r_name", "region"."r_comment", "nation"."n_nationkey", "nation"."n_name", "nation"."n_regionkey", "nation"."n_comment", "supplier"."s_suppkey", "supplier"."s_name", "supplier"."s_address", "supplier"."s_nationkey", "supplier"."s_phone", "supplier"."s_acctbal", "supplier"."s_comment", "t0"."S_SUPPKEY" AS "S_SUPPKEY_", "t0"."S_NAME" AS "S_NAME_", "t0"."TOTAL_COST", "lineitem"."l_orderkey", "lineitem"."l_partkey", "lineitem"."l_suppkey", "lineitem"."l_linenumber", "lineitem"."l_quantity", "lineitem"."l_extendedprice", "lineitem"."l_discount", "lineitem"."l_tax", "lineitem"."l_returnflag", "lineitem"."l_linestatus", "lineitem"."l_shipdate", "lineitem"."l_commitdate", "lineitem"."l_receiptdate", "lineitem"."l_shipinstruct", "lineitem"."l_shipmode", "lineitem"."l_comment", "orders"."o_orderkey", "orders"."o_custkey", "orders"."o_orderstatus", "orders"."o_totalprice", "orders"."o_orderdate", "orders"."o_orderpriority", "orders"."o_clerk", "orders"."o_shippriority", "orders"."o_comment", "t2"."L_ORDERKEY" AS "L_ORDERKEY_", "t2"."TOTAL_LINES", "t2"."TOTAL_REVENUE", "partsupp0"."ps_partkey", "partsupp0"."ps_suppkey", "partsupp0"."ps_availqty", "partsupp0"."ps_supplycost", "partsupp0"."ps_comment", "part"."p_partkey", "part"."p_name", "part"."p_mfgr", "part"."p_brand", "part"."p_type", "part"."p_size", "part"."p_container", "part"."p_retailprice", "part"."p_comment", "customer"."c_custkey", "customer"."c_name", "customer"."c_address", "customer"."c_nationkey", "customer"."c_phone", "customer"."c_acctbal", "customer"."c_mktsegment", "customer"."c_comment"
FROM "TPCH"."region"
LEFT JOIN "TPCH"."nation" ON "region"."r_regionkey" = "nation"."n_regionkey"
LEFT JOIN "TPCH"."supplier" ON "nation"."n_nationkey" = "supplier"."s_nationkey"
LEFT JOIN (SELECT "supplier0"."s_suppkey" AS "S_SUPPKEY", "supplier0"."s_name" AS "S_NAME", SUM("partsupp"."ps_supplycost" * "partsupp"."ps_availqty") AS "TOTAL_COST"
FROM "TPCH"."supplier" AS "supplier0"
INNER JOIN "TPCH"."partsupp" ON "supplier0"."s_suppkey" = "partsupp"."ps_suppkey"
GROUP BY "supplier0"."s_suppkey", "supplier0"."s_name") AS "t0" ON "supplier"."s_suppkey" = "t0"."S_SUPPKEY"
LEFT JOIN "TPCH"."lineitem" ON "supplier"."s_suppkey" = "lineitem"."l_suppkey"
LEFT JOIN "TPCH"."orders" ON "lineitem"."l_orderkey" = "orders"."o_orderkey"
LEFT JOIN (SELECT "l_orderkey" AS "L_ORDERKEY", COUNT(*) AS "TOTAL_LINES", SUM("l_extendedprice" * (1 - "l_discount")) AS "TOTAL_REVENUE"
FROM "TPCH"."lineitem"
GROUP BY "l_orderkey") AS "t2" ON "orders"."o_orderkey" = "t2"."L_ORDERKEY"
LEFT JOIN "TPCH"."partsupp" AS "partsupp0" ON "lineitem"."l_partkey" = "partsupp0"."ps_partkey"
LEFT JOIN "TPCH"."part" ON "partsupp0"."ps_partkey" = "part"."p_partkey"
LEFT JOIN "TPCH"."customer" ON "orders"."o_custkey" = "customer"."c_custkey"