SELECT COALESCE("R_NAME", "R_NAME") AS "R_NAME", "UNIQUE_CUSTOMERS", "AVG_SUPPLIER_COST", "LARGE_ORDERS", "POPULAR_PARTS"
FROM (SELECT "r_name" AS "R_NAME", COUNT(DISTINCT "c_custkey") AS "UNIQUE_CUSTOMERS", AVG("TOTAL_COST") AS "AVG_SUPPLIER_COST", SUM(CASE WHEN "TOTAL_LINES" > 5 THEN 1 ELSE 0 END) AS "LARGE_ORDERS", LISTAGG(DISTINCT "p_name", ', ') AS "POPULAR_PARTS"
FROM "s1"
WHERE "o_orderstatus" = 'O' AND "TOTAL_COST" IS NOT NULL
GROUP BY "r_name"
ORDER BY 2 DESC NULLS FIRST, 3 DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY) AS "t7"