SELECT COALESCE("REGION_NAME", "REGION_NAME") AS "REGION_NAME", "NATION_NAME", "SUPPLIER_NAME", "TOTAL_REVENUE", "REVENUE_CATEGORY"
FROM (SELECT "r_name" AS "REGION_NAME", "n_name" AS "NATION_NAME", "S_NAME" AS "SUPPLIER_NAME", "TOTAL_REVENUE", CASE WHEN "TOTAL_REVENUE" IS NULL THEN 'No Revenue    ' WHEN "TOTAL_REVENUE" < 10000.0000 THEN 'Low Revenue   ' WHEN "TOTAL_REVENUE" >= 10000.0000 AND "TOTAL_REVENUE" <= 50000.0000 THEN 'Medium Revenue' ELSE 'High Revenue  ' END AS "REVENUE_CATEGORY"
FROM "s1"
WHERE "r_name" IS NOT NULL OR "TOTAL_REVENUE" IS NOT NULL
ORDER BY 5, "TOTAL_REVENUE" DESC NULLS FIRST
FETCH NEXT 100 ROWS ONLY) AS "t6"