SELECT COALESCE("t2"."S_SUPPKEY", "t2"."S_SUPPKEY") AS "S_SUPPKEY", "t2"."S_NAME", "t2"."TOTAL_REVENUE", "t2"."REVENUE_RANK", "supplier0"."s_suppkey" AS "s_suppkey_", "supplier0"."s_name" AS "s_name_", "supplier0"."s_address", "supplier0"."s_nationkey", "supplier0"."s_phone", "supplier0"."s_acctbal", "supplier0"."s_comment", "nation"."n_nationkey", "nation"."n_name", "nation"."n_regionkey", "nation"."n_comment", "region"."r_regionkey", "region"."r_name", "region"."r_comment"
FROM (SELECT "supplier"."s_suppkey" AS "S_SUPPKEY", "supplier"."s_name" AS "S_NAME", SUM("lineitem"."l_extendedprice" * (1 - "lineitem"."l_discount")) AS "TOTAL_REVENUE", RANK() OVER (ORDER BY SUM("lineitem"."l_extendedprice" * (1 - "lineitem"."l_discount")) DESC NULLS FIRST) AS "REVENUE_RANK"
FROM "TPCH"."supplier"
LEFT JOIN "TPCH"."partsupp" ON "supplier"."s_suppkey" = "partsupp"."ps_suppkey"
LEFT JOIN "TPCH"."lineitem" ON "partsupp"."ps_partkey" = "lineitem"."l_partkey"
LEFT JOIN "TPCH"."orders" ON "lineitem"."l_orderkey" = "orders"."o_orderkey"
GROUP BY "supplier"."s_suppkey", "supplier"."s_name"
HAVING COUNT(DISTINCT "orders"."o_orderkey") > 5) AS "t2"
INNER JOIN "TPCH"."supplier" AS "supplier0" ON "t2"."S_SUPPKEY" = "supplier0"."s_suppkey"
INNER JOIN "TPCH"."nation" ON "supplier0"."s_nationkey" = "nation"."n_nationkey"
LEFT JOIN "TPCH"."region" ON "nation"."n_regionkey" = "region"."r_regionkey"