SELECT COALESCE("t9"."R_NAME", "t9"."R_NAME") AS "R_NAME", "t9"."REGION_COUNT", "t9"."P_RETAILPRICE", "t11"."O_TOTALPRICE"
FROM (SELECT "t7"."R_NAME", "t7"."REGION_COUNT", "t7"."TOTAL_QUANTITY", "t8"."P_PARTKEY", "t8"."P_NAME", "t8"."P_RETAILPRICE", "t8"."SIZE_CATEGORY"
FROM (SELECT "t2"."r_name" AS "R_NAME", COUNT(DISTINCT "t2"."N_NATIONKEY") AS "REGION_COUNT", SUM("t4"."TOTAL_QTY") AS "TOTAL_QUANTITY", COUNT(DISTINCT "t2"."N_NATIONKEY") > 5 AS "$f3"
FROM (SELECT "region"."r_regionkey", "region"."r_name", "region"."r_comment", "t1"."N_NAME", "t1"."SUPPLIER_COUNT", "t1"."N_NATIONKEY", CAST("t1"."N_NATIONKEY" AS BIGINT) AS "N_NATIONKEY0"
FROM "TPCH"."region"
LEFT JOIN (SELECT "nation"."n_name" AS "N_NAME", COUNT(DISTINCT "supplier"."s_suppkey") AS "SUPPLIER_COUNT", "nation"."n_nationkey" AS "N_NATIONKEY"
FROM "TPCH"."supplier"
INNER JOIN "TPCH"."nation" ON "supplier"."s_nationkey" = "nation"."n_nationkey"
GROUP BY "nation"."n_name", "nation"."n_nationkey") AS "t1" ON "region"."r_regionkey" = "t1"."N_NATIONKEY") AS "t2"
LEFT JOIN (SELECT "l_orderkey" AS "L_ORDERKEY", SUM("l_quantity") AS "TOTAL_QTY"
FROM "TPCH"."lineitem"
GROUP BY "l_orderkey") AS "t4" ON "t2"."N_NATIONKEY0" = "t4"."L_ORDERKEY"
GROUP BY "t2"."r_name") AS "t7"
LEFT JOIN (SELECT "p_partkey" AS "P_PARTKEY", "p_name" AS "P_NAME", "p_retailprice" AS "P_RETAILPRICE", CASE WHEN "p_size" >= 1 AND "p_size" <= 5 THEN 'Small ' WHEN "p_size" >= 6 AND "p_size" <= 15 THEN 'Medium' ELSE 'Large ' END AS "SIZE_CATEGORY"
FROM "TPCH"."part") AS "t8" ON "t7"."$f3") AS "t9"
LEFT JOIN (SELECT "o_orderkey" AS "O_ORDERKEY", "o_orderdate" AS "O_ORDERDATE", "o_totalprice" AS "O_TOTALPRICE", ROW_NUMBER() OVER (PARTITION BY EXTRACT(YEAR FROM "o_orderdate") ORDER BY "o_totalprice" DESC NULLS FIRST) AS "ORDER_RANK", EXTRACT(YEAR FROM "o_orderdate") AS "$f4"
FROM "TPCH"."orders"
WHERE "o_orderdate" >= DATE '1994-01-01') AS "t11" ON "t9"."REGION_COUNT" = "t11"."$f4"