SELECT COALESCE("R_NAME", "R_NAME") AS "R_NAME", "REGION_COUNT", CASE WHEN SUM("P_RETAILPRICE") IS NOT NULL THEN CAST(SUM("P_RETAILPRICE") AS DECIMAL(19, 2)) ELSE 0.00 END AS "TOTAL_RETAIL_PRICE", AVG("O_TOTALPRICE") AS "AVG_ORDER_PRICE"
FROM "s1"
GROUP BY "R_NAME", "REGION_COUNT"
HAVING AVG("O_TOTALPRICE") > (((SELECT AVG("o_totalprice")
FROM "TPCH"."orders")))
ORDER BY "R_NAME" DESC NULLS FIRST
OFFSET 5 ROWS
FETCH NEXT 10 ROWS ONLY