SELECT COALESCE("NATION_REGION", "NATION_REGION") AS "NATION_REGION", "UNIQUE_CUSTOMERS", "TOTAL_RETAIL_PRICE_LARGE_NAME", "AVG_SALES_PRICE", "PART_COMMENTS"
FROM (SELECT ANY_VALUE(CONCAT("n_name", ' - ', "r_name")) AS "NATION_REGION", COUNT(DISTINCT "c_custkey") AS "UNIQUE_CUSTOMERS", SUM(CASE WHEN LENGTH("p_name") > 20 THEN "p_retailprice" ELSE 0.00 END) AS "TOTAL_RETAIL_PRICE_LARGE_NAME", ROUND(AVG("l_extendedprice" * (1 - "l_discount")), 2) AS "AVG_SALES_PRICE", LISTAGG(DISTINCT "p_comment", ', ') AS "PART_COMMENTS"
FROM "s1"
WHERE "l_shipdate" >= '1997-01-01' AND "l_shipdate" < '1997-12-31'
GROUP BY "n_name", "r_name"
HAVING COUNT(DISTINCT "c_custkey") > 10
ORDER BY 1) AS "t5"