SELECT COALESCE(ANY_VALUE("part"."p_name"), ANY_VALUE("part"."p_name")) AS "PART_NAME", ANY_VALUE("supplier"."s_name") AS "SUPPLIER_NAME", ANY_VALUE("customer"."c_name") AS "CUSTOMER_NAME", ANY_VALUE("orders"."o_orderkey") AS "ORDER_ID", COUNT(*) AS "LINE_ITEM_COUNT", SUM("lineitem"."l_extendedprice") AS "TOTAL_EXTENDED_PRICE", AVG("lineitem"."l_discount") AS "AVERAGE_DISCOUNT", MAX("lineitem"."l_shipdate") AS "LATEST_SHIP_DATE", LISTAGG(DISTINCT "region"."r_name", ', ') AS "REGIONS_SUPPLIED", LISTAGG(DISTINCT "part"."p_comment", '|') AS "PART_COMMENTS"
FROM "TPCH"."part"
INNER JOIN "TPCH"."partsupp" ON "part"."p_partkey" = "partsupp"."ps_partkey"
INNER JOIN "TPCH"."supplier" ON "partsupp"."ps_suppkey" = "supplier"."s_suppkey"
INNER JOIN "TPCH"."lineitem" ON "part"."p_partkey" = "lineitem"."l_partkey"
INNER JOIN "TPCH"."orders" ON "lineitem"."l_orderkey" = "orders"."o_orderkey"
INNER JOIN "TPCH"."customer" ON "orders"."o_custkey" = "customer"."c_custkey"
INNER JOIN "TPCH"."nation" ON "supplier"."s_nationkey" = "nation"."n_nationkey"
INNER JOIN "TPCH"."region" ON "nation"."n_regionkey" = "region"."r_regionkey"
WHERE "part"."p_size" > 10 AND "supplier"."s_acctbal" > 500.00 AND "orders"."o_orderdate" >= DATE '1997-01-01' AND "orders"."o_orderstatus" = 'O'
GROUP BY "part"."p_name", "supplier"."s_name", "customer"."c_name", "orders"."o_orderkey"