SELECT COALESCE("t3"."FORMATTED_NAME_ADDRESS", "t3"."FORMATTED_NAME_ADDRESS") AS "FORMATTED_NAME_ADDRESS", "t3"."P_NAME", "t3"."MODIFIED_COMMENT", "t3"."C_NAME", SUM("t5"."L_QUANTITY") AS "TOTAL_QUANTITY", SUM("t5"."L_EXTENDEDPRICE" * (1 - "t5"."L_DISCOUNT")) AS "TOTAL_REVENUE"
FROM (SELECT "t1"."S_SUPPKEY", "t1"."S_NAME", "t1"."S_NATIONKEY", "t1"."FORMATTED_NAME_ADDRESS", "t1"."ps_partkey", "t1"."ps_suppkey", "t1"."ps_availqty", "t1"."ps_supplycost", "t1"."ps_comment", "t1"."P_PARTKEY", "t1"."P_NAME", "t1"."P_MFGR", "t1"."P_TYPE", "t1"."P_SIZE", "t1"."MODIFIED_COMMENT", "t2"."C_CUSTKEY", "t2"."C_NAME", "t2"."C_MKTSEGMENT", "t2"."LAST_TEN_ADDRESS_DIGITS"
FROM (SELECT "t"."S_SUPPKEY", "t"."S_NAME", "t"."S_NATIONKEY", "t"."FORMATTED_NAME_ADDRESS", "partsupp"."ps_partkey", "partsupp"."ps_suppkey", "partsupp"."ps_availqty", "partsupp"."ps_supplycost", "partsupp"."ps_comment", "t0"."P_PARTKEY", "t0"."P_NAME", "t0"."P_MFGR", "t0"."P_TYPE", "t0"."P_SIZE", "t0"."MODIFIED_COMMENT", CAST("t"."S_NATIONKEY" AS BIGINT) AS "S_NATIONKEY0"
FROM (SELECT "s_suppkey" AS "S_SUPPKEY", "s_name" AS "S_NAME", "s_nationkey" AS "S_NATIONKEY", CONCAT("s_name", ' (', SUBSTRING("s_address", 1, 10), '...)') AS "FORMATTED_NAME_ADDRESS"
FROM "TPCH"."supplier") AS "t"
INNER JOIN "TPCH"."partsupp" ON "t"."S_SUPPKEY" = "partsupp"."ps_suppkey"
INNER JOIN (SELECT "p_partkey" AS "P_PARTKEY", "p_name" AS "P_NAME", "p_mfgr" AS "P_MFGR", "p_type" AS "P_TYPE", "p_size" AS "P_SIZE", REPLACE("p_comment", 'part', 'component') AS "MODIFIED_COMMENT"
FROM "TPCH"."part") AS "t0" ON "partsupp"."ps_partkey" = "t0"."P_PARTKEY") AS "t1"
INNER JOIN (SELECT "c_custkey" AS "C_CUSTKEY", "c_name" AS "C_NAME", "c_mktsegment" AS "C_MKTSEGMENT", RIGHT("c_address", 10) AS "LAST_TEN_ADDRESS_DIGITS"
FROM "TPCH"."customer") AS "t2" ON "t1"."S_NATIONKEY0" = "t2"."C_CUSTKEY") AS "t3"
INNER JOIN (SELECT "l_orderkey" AS "L_ORDERKEY", "l_partkey" AS "L_PARTKEY", "l_quantity" AS "L_QUANTITY", "l_extendedprice" AS "L_EXTENDEDPRICE", "l_discount" AS "L_DISCOUNT"
FROM "TPCH"."lineitem"
WHERE "l_returnflag" = 'N') AS "t5" ON "t3"."P_PARTKEY" = "t5"."L_ORDERKEY"
GROUP BY "t3"."FORMATTED_NAME_ADDRESS", "t3"."P_NAME", "t3"."MODIFIED_COMMENT", "t3"."C_NAME"