SELECT COALESCE("P_NAME", "P_NAME") AS "P_NAME", "P_BRAND", "SUPPLIER_COUNT", "TOTAL_AVAILABLE_QUANTITY", "AVERAGE_SUPPLY_COST", "NATION_COMMENTS", "SHORT_COMMENT"
FROM "s1"
ORDER BY "TOTAL_AVAILABLE_QUANTITY" DESC NULLS FIRST, "AVERAGE_SUPPLY_COST"
FETCH NEXT 50 ROWS ONLY