SELECT COALESCE("PART_INFO", "PART_INFO") AS "PART_INFO", "TOTAL_RETURNED_QUANTITY", "TOTAL_SALES", "TOTAL_ORDERS", "REGION_NAME", "NATION_NAME"
FROM (SELECT ANY_VALUE("FD_COL_6") AS "PART_INFO", SUM("FD_COL_7") AS "TOTAL_RETURNED_QUANTITY", SUM("FD_COL_8") AS "TOTAL_SALES", COUNT(DISTINCT "o_orderkey") AS "TOTAL_ORDERS", ANY_VALUE("r_name") AS "REGION_NAME", ANY_VALUE("n_name") AS "NATION_NAME"
FROM "s1"
GROUP BY "p_partkey", "p_name", "p_mfgr", "p_brand", "r_name", "n_name"
HAVING SUM("FD_COL_8") > 10000.0000
ORDER BY 3 DESC NULLS FIRST) AS "t5"