SELECT COALESCE("SUPPLIER_NAME", "SUPPLIER_NAME") AS "SUPPLIER_NAME", "PART_NAME", "PART_BRAND", "TOTAL_AVAILABLE_QUANTITY", "AVG_EXTENDED_PRICE", "UNIQUE_CUSTOMERS", "REGION_NAME"
FROM (SELECT ANY_VALUE("s_name") AS "SUPPLIER_NAME", ANY_VALUE("p_name") AS "PART_NAME", ANY_VALUE("p_brand") AS "PART_BRAND", SUM("ps_availqty") AS "TOTAL_AVAILABLE_QUANTITY", AVG("l_extendedprice") AS "AVG_EXTENDED_PRICE", COUNT(DISTINCT "c_custkey") AS "UNIQUE_CUSTOMERS", ANY_VALUE("r_name") AS "REGION_NAME"
FROM "s1"
WHERE "s_comment" LIKE '%reliable%' AND "p_type" LIKE '%metal%' AND "l_shipdate" >= DATE '1997-01-01' AND "l_shipdate" <= DATE '1997-12-31'
GROUP BY "s_name", "p_name", "p_brand", "r_name"
HAVING SUM("ps_availqty") > 50
ORDER BY 4 DESC NULLS FIRST, 5) AS "t5"