SELECT COALESCE("P_NAME", "P_NAME") AS "P_NAME", "SUPPLIER_COUNT", "AVG_SUPPLY_COST", "TOTAL_DISCOUNTED_QUANTITY", "MAX_RECENT_ORDER_VALUE", "SUPPLIER_NAMES"
FROM "s1"
ORDER BY "AVG_SUPPLY_COST" DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY