SELECT COALESCE("REGION_NAME", "REGION_NAME") AS "REGION_NAME", "NATION_NAME", "SUPPLIER_NAME", "TOTAL_AVAILABLE_QUANTITY", "AVERAGE_SUPPLY_COST", "CUSTOMER_NAME", "TOTAL_ORDERS", "TOTAL_SPENT", "ALL_PART_NAMES"
FROM "s1"
ORDER BY "TOTAL_SPENT" DESC NULLS FIRST, "TOTAL_ORDERS" DESC NULLS FIRST