SELECT COALESCE("REGION_NAME", "REGION_NAME") AS "REGION_NAME", "NATION_NAME", "SUPPLIER_NAME", "TOTAL_AVAILABLE_QUANTITY", "AVERAGE_SUPPLY_COST", "CUSTOMER_NAME", "TOTAL_ORDERS", "TOTAL_SPENT", "ALL_PART_NAMES"
FROM (SELECT ANY_VALUE("t1"."r_name") AS "REGION_NAME", ANY_VALUE("t1"."n_name") AS "NATION_NAME", ANY_VALUE("t1"."S_NAME") AS "SUPPLIER_NAME", "t1"."TOTAL_AVAILABLE_QUANTITY", "t1"."AVERAGE_SUPPLY_COST", ANY_VALUE("t3"."C_NAME") AS "CUSTOMER_NAME", "t3"."TOTAL_ORDERS", "t3"."TOTAL_SPENT", LISTAGG(DISTINCT "t1"."PART_NAMES", '; ') AS "ALL_PART_NAMES"
FROM (SELECT "region"."r_regionkey", "region"."r_name", "region"."r_comment", "nation"."n_nationkey", "nation"."n_name", "nation"."n_regionkey", "nation"."n_comment", "t0"."S_SUPPKEY", "t0"."S_NAME", "t0"."S_NATIONKEY", "t0"."TOTAL_AVAILABLE_QUANTITY", "t0"."AVERAGE_SUPPLY_COST", "t0"."PART_NAMES", CAST("t0"."S_NATIONKEY" AS BIGINT) AS "S_NATIONKEY0"
FROM "TPCH"."region"
INNER JOIN "TPCH"."nation" ON "region"."r_regionkey" = "nation"."n_regionkey"
INNER JOIN (SELECT "supplier"."s_suppkey" AS "S_SUPPKEY", "supplier"."s_name" AS "S_NAME", "supplier"."s_nationkey" AS "S_NATIONKEY", SUM("partsupp"."ps_availqty") AS "TOTAL_AVAILABLE_QUANTITY", AVG("partsupp"."ps_supplycost") AS "AVERAGE_SUPPLY_COST", LISTAGG(DISTINCT "part"."p_name", ', ') AS "PART_NAMES"
FROM "TPCH"."supplier"
INNER JOIN "TPCH"."partsupp" ON "supplier"."s_suppkey" = "partsupp"."ps_suppkey"
INNER JOIN "TPCH"."part" ON "partsupp"."ps_partkey" = "part"."p_partkey"
GROUP BY "supplier"."s_suppkey", "supplier"."s_name", "supplier"."s_nationkey") AS "t0" ON "nation"."n_nationkey" = "t0"."S_NATIONKEY") AS "t1"
INNER JOIN (SELECT "customer"."c_custkey" AS "C_CUSTKEY", "customer"."c_name" AS "C_NAME", COUNT("orders"."o_orderkey") AS "TOTAL_ORDERS", SUM("orders"."o_totalprice") AS "TOTAL_SPENT"
FROM "TPCH"."customer"
LEFT JOIN "TPCH"."orders" ON "customer"."c_custkey" = "orders"."o_custkey"
GROUP BY "customer"."c_custkey", "customer"."c_name") AS "t3" ON "t1"."S_NATIONKEY0" = "t3"."C_CUSTKEY"
GROUP BY "t1"."r_name", "t1"."n_name", "t1"."S_NAME", "t1"."TOTAL_AVAILABLE_QUANTITY", "t1"."AVERAGE_SUPPLY_COST", "t3"."C_NAME", "t3"."TOTAL_ORDERS", "t3"."TOTAL_SPENT") AS "t6"
WHERE "t6"."TOTAL_SPENT" > 1000.00