SELECT COALESCE("region"."r_name", "region"."r_name") AS "r_name", "t"."SUPPLIER_NAME", "t2"."CUSTOMER_NAME", "t"."SUPPLY_INFO", '; ' AS "FD_COL_4", "t2"."ORDER_SUMMARY"
FROM "TPCH"."region"
LEFT JOIN "TPCH"."nation" ON "region"."r_regionkey" = "nation"."n_regionkey"
LEFT JOIN "TPCH"."supplier" ON "nation"."n_nationkey" = "supplier"."s_nationkey"
LEFT JOIN (SELECT "supplier0"."s_name" AS "SUPPLIER_NAME", "part"."p_name" AS "PART_NAME", "partsupp"."ps_availqty" AS "AVAILABLE_QUANTITY", "partsupp"."ps_supplycost" AS "SUPPLY_COST", CONCAT("supplier0"."s_name", ' supplies ', "part"."p_name", ' with availability of ', CAST("partsupp"."ps_availqty" AS VARCHAR CHARACTER SET "ISO-8859-1"), ' units at a cost of $', CAST(CAST("partsupp"."ps_supplycost" AS DECIMAL(12, 2)) AS VARCHAR CHARACTER SET "ISO-8859-1")) AS "SUPPLY_INFO"
FROM "TPCH"."supplier" AS "supplier0"
INNER JOIN "TPCH"."partsupp" ON "supplier0"."s_suppkey" = "partsupp"."ps_suppkey"
INNER JOIN "TPCH"."part" ON "partsupp"."ps_partkey" = "part"."p_partkey") AS "t" ON "supplier"."s_name" = "t"."SUPPLIER_NAME"
LEFT JOIN (SELECT ANY_VALUE("customer"."c_name") AS "CUSTOMER_NAME", COUNT(*) AS "TOTAL_ORDERS", SUM("orders"."o_totalprice") AS "TOTAL_SPENT", CONCAT("customer"."c_name", ' has placed ', CAST(COUNT(*) AS VARCHAR CHARACTER SET "ISO-8859-1"), ' orders totaling $', CAST(CAST(SUM("orders"."o_totalprice") AS DECIMAL(12, 2)) AS VARCHAR CHARACTER SET "ISO-8859-1")) AS "ORDER_SUMMARY"
FROM "TPCH"."customer"
INNER JOIN "TPCH"."orders" ON "customer"."c_custkey" = "orders"."o_custkey"
GROUP BY "customer"."c_name") AS "t2" ON "t"."SUPPLIER_NAME" = "t2"."CUSTOMER_NAME"