SELECT COALESCE("CUSTOMER_INFO", "CUSTOMER_INFO") AS "CUSTOMER_INFO", "TOTAL_REVENUE", "TOTAL_ORDERS", "SUPPLIED_PARTS", "LAST_ORDER_DATE"
FROM "s1"
ORDER BY "TOTAL_REVENUE" DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY