SELECT COALESCE("SUPPLIER_REGION", "SUPPLIER_REGION") AS "SUPPLIER_REGION", "ORDER_COUNT", "TOTAL_REVENUE", "AVG_QUANTITY_PER_ORDER", "PART_NAMES"
FROM (SELECT ANY_VALUE(CONCAT("s_name", ' from ', "r_name")) AS "SUPPLIER_REGION", COUNT(DISTINCT "o_orderkey") AS "ORDER_COUNT", SUM("l_extendedprice") AS "TOTAL_REVENUE", AVG("l_quantity") AS "AVG_QUANTITY_PER_ORDER", LISTAGG(DISTINCT "p_name", ', ') AS "PART_NAMES"
FROM "s1"
WHERE "p_comment" LIKE '%fragile%' AND "o_orderdate" >= DATE '1996-01-01' AND "o_orderdate" < DATE '1997-01-01'
GROUP BY CONCAT("s_name", ' from ', "r_name")
ORDER BY 3 DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY) AS "t4"