SELECT COALESCE("P_BRAND", "P_BRAND") AS "P_BRAND", "UNIQUE_PARTS", "TOTAL_AVAIL_QTY", "AVG_RETAIL_PRICE", "SUPPLIERS", "REGION_INFO"
FROM (SELECT "P_BRAND", COUNT(DISTINCT "p_partkey") AS "UNIQUE_PARTS", SUM("ps_availqty") AS "TOTAL_AVAIL_QTY", AVG("p_retailprice") AS "AVG_RETAIL_PRICE", LISTAGG(DISTINCT "s_name", "FD_COL_6") AS "SUPPLIERS", CONCAT('Region: ', "r_name", ' (', CAST(COUNT(DISTINCT "n_nationkey") AS VARCHAR CHARACTER SET "ISO-8859-1"), ' Nations)') AS "REGION_INFO"
FROM "s1"
GROUP BY "P_BRAND", "r_name"
HAVING COUNT(DISTINCT "s_suppkey") > 2
ORDER BY 3 DESC NULLS FIRST, 4) AS "t5"