SELECT COALESCE("SUPPLIER_CUSTOMER", "SUPPLIER_CUSTOMER") AS "SUPPLIER_CUSTOMER", "TRUNCATED_PART_NAME", "P_BRAND", "SANITIZED_SUPPLIER_COMMENT", "TOTAL_REVENUE", "REVENUE_CATEGORY", "ORDER_COUNT"
FROM "s1"
ORDER BY "TOTAL_REVENUE" DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY