SELECT COALESCE("P_NAME", "P_NAME") AS "P_NAME", "S_NAME", "TOTAL_AVAILABLE_QUANTITY", "TOTAL_ORDERS", "AVG_ORDER_PRICE", "REGION_NATION"
FROM "s1"
ORDER BY "AVG_ORDER_PRICE" DESC NULLS FIRST, "TOTAL_ORDERS" DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY