SELECT COALESCE("SUPPLIER_INFO", "SUPPLIER_INFO") AS "SUPPLIER_INFO", "TOTAL_ORDERS", "TOTAL_REVENUE", "AVG_DISCOUNTED_PRICE", "PART_NAMES", "FURNITURE_CUSTOMERS"
FROM (SELECT ANY_VALUE(CONCAT("s_name", ' from ', "n_name", ' in ', "r_name")) AS "SUPPLIER_INFO", COUNT(DISTINCT "o_orderkey") AS "TOTAL_ORDERS", SUM("l_extendedprice" * (1 - "l_discount")) AS "TOTAL_REVENUE", AVG(CASE WHEN "l_discount" > 0.00 THEN CAST("l_extendedprice" AS DECIMAL(15, 2)) ELSE NULL END) AS "AVG_DISCOUNTED_PRICE", LISTAGG(DISTINCT "p_name", ', ') AS "PART_NAMES", COUNT(DISTINCT CASE WHEN "c_mktsegment" = 'FURNITURE' THEN "c_custkey" ELSE NULL END) AS "FURNITURE_CUSTOMERS"
FROM "s1"
WHERE "l_shipdate" >= '1997-01-01' AND "l_shipdate" <= '1997-12-31'
GROUP BY "s_name", "n_name", "r_name"
ORDER BY 3 DESC NULLS FIRST, 2 DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY) AS "t4"