SELECT COALESCE("P_NAME", "P_NAME") AS "P_NAME", "SUPPLIER_COUNT", "SUPPLIER_DETAILS", "TOTAL_AVAILABLE_QUANTITY", "AVERAGE_SUPPLY_COST", "MAX_SUPPLY_COST", "MIN_SUPPLY_COST"
FROM "s1"
ORDER BY "TOTAL_AVAILABLE_QUANTITY" DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY