SELECT COALESCE("P_BRAND", "P_BRAND") AS "P_BRAND", "SUPPLIER_COUNT", "AVG_SUPPLY_COST", "FIRST_SHIP_DATE", "LAST_SHIP_DATE", "PART_NAMES", "TOTAL_REVENUE"
FROM (SELECT "P_BRAND", COUNT(DISTINCT "s_suppkey") AS "SUPPLIER_COUNT", AVG("ps_supplycost") AS "AVG_SUPPLY_COST", MIN("l_shipdate") AS "FIRST_SHIP_DATE", MAX("l_shipdate") AS "LAST_SHIP_DATE", LISTAGG(DISTINCT "FD_COL_4", "FD_COL_5") AS "PART_NAMES", SUM("FD_COL_6") AS "TOTAL_REVENUE"
FROM "s1"
GROUP BY "P_BRAND"
ORDER BY 7 DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY) AS "t3"