SELECT COALESCE("S_NAME", "S_NAME") AS "S_NAME", "S_ADDRESS", "COMMENT_EXCERPT", "SUPPLIER_INFO", "PART_COUNT", "TOTAL_AVAILABILITY", "AVERAGE_SUPPLY_COST", "SANITIZED_COMMENT", "COST_CATEGORY"
FROM "s1"
ORDER BY "TOTAL_AVAILABILITY" DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY