SELECT COALESCE("P_PARTKEY", "P_PARTKEY") AS "P_PARTKEY", "P_NAME", "SUPPLIER_NAME", "COMBINED_STRING", "STRING_LENGTH", "COMMENT_SNIPPET", "AVG_STRING_LENGTH", "MAX_STRING_LENGTH", "TOTAL_ENTRIES", "UNIQUE_COMMENTS"
FROM "s1"
ORDER BY "STRING_LENGTH" DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY