SELECT COALESCE("P_PARTKEY", "P_PARTKEY") AS "P_PARTKEY", "P_NAME", "P_RETAILPRICE", "COMMENT_LENGTH", "TOTAL_AVAILABLE_QTY", "SUPPLIER_COUNT", "C_CUSTKEY", "C_NAME", "TOTAL_ORDER_VALUE", "ORDER_COUNT", "COMBINED_INFO"
FROM "s1"
FETCH NEXT 100 ROWS ONLY