SELECT COALESCE("SUPPLIER_NAME", "SUPPLIER_NAME") AS "SUPPLIER_NAME", "SUPPLIER_NATION", "PARTS_SUPPLIED", "TOTAL_SUPPLY_COST", "CUSTOMER_NAME", "TOTAL_ORDERS_PLACED", "TOTAL_SPENT_BY_CUSTOMER"
FROM "s1"
ORDER BY "TOTAL_SPENT_BY_CUSTOMER" DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY