SELECT COALESCE("SUPPLIER_NAME", "SUPPLIER_NAME") AS "SUPPLIER_NAME", "PART_NAME", "TOTAL_LINEITEMS", "TOTAL_QUANTITY", "TOTAL_EXTENDED_PRICE", "NON_SPACE_COMMENT_LENGTH", "ADJUSTED_COMMENT"
FROM "s1"
ORDER BY "TOTAL_EXTENDED_PRICE" DESC NULLS FIRST
FETCH NEXT 100 ROWS ONLY