SELECT COALESCE("P_NAME", "P_NAME") AS "P_NAME", "SUPPLIER_NAME", "CUSTOMER_NAME", "O_ORDERDATE", "TOTAL_REVENUE", "TOTAL_ORDERS", "SHORT_COMMENT", "SUPPLIER_INFO", "o_orderdate_"
FROM "s1"
ORDER BY "TOTAL_REVENUE" DESC NULLS FIRST, "o_orderdate_" DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY