SELECT COALESCE("P_PARTKEY", "P_PARTKEY") AS "P_PARTKEY", "AVG_NAME_LENGTH", "AVG_COMMENT_LENGTH", "TOTAL_RECORDS", "AGGREGATED_STRINGS"
FROM "s1"
ORDER BY "TOTAL_RECORDS" DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY