SELECT COALESCE("SUPPLIER_NAME", "SUPPLIER_NAME") AS "SUPPLIER_NAME", "TOTAL_PRODUCTS", "TOTAL_AVAILABLE_QUANTITY", "AVERAGE_SUPPLY_COST", "BRANDS_OFFERED", "CONTAINER_TYPES", "SUPPLIER_SUMMARY"
FROM "s1"
ORDER BY "TOTAL_PRODUCTS" DESC NULLS FIRST