SELECT COALESCE("P_NAME", "P_NAME") AS "P_NAME", "SUPPLIER_NAME", "TOTAL_QUANTITY", "TOTAL_REVENUE", "TOTAL_ORDERS", "LAST_SHIP_DATE", "FIRST_SHIP_DATE", "AVERAGE_DISCOUNT", "REGIONS_SUPPLY", "SHORT_COMMENT"
FROM (SELECT "p_name" AS "P_NAME", ANY_VALUE("s_name") AS "SUPPLIER_NAME", SUM("l_quantity") AS "TOTAL_QUANTITY", SUM("l_extendedprice") AS "TOTAL_REVENUE", COUNT(DISTINCT "o_orderkey") AS "TOTAL_ORDERS", MAX("l_shipdate") AS "LAST_SHIP_DATE", MIN("l_shipdate") AS "FIRST_SHIP_DATE", AVG("l_discount") AS "AVERAGE_DISCOUNT", LISTAGG(DISTINCT "r_name", ', ') AS "REGIONS_SUPPLY", ANY_VALUE(SUBSTRING("p_comment", 1, 10)) AS "SHORT_COMMENT"
FROM "s1"
WHERE "l_shipdate" >= '1997-01-01' AND "l_shipdate" <= '1997-12-31'
GROUP BY "p_name", "s_name", "p_comment"
HAVING SUM("l_quantity") > 100.00
ORDER BY 4 DESC NULLS FIRST) AS "t5"