SELECT COALESCE("DETAILED_INFO", "DETAILED_INFO") AS "DETAILED_INFO", "TOTAL_AVAILABLE_QUANTITY", "AVERAGE_SUPPLY_COST", "TOTAL_ORDERS"
FROM "s1"
ORDER BY "TOTAL_ORDERS" DESC NULLS FIRST, "AVERAGE_SUPPLY_COST"
FETCH NEXT 10 ROWS ONLY