SELECT COALESCE("R_NAME", "R_NAME") AS "R_NAME", "SUPPLIER_COUNT", "AVG_CUSTOMER_SPENT", "MAX_SUPPLY_COST", "TOTAL_DISCOUNTED_SALES", "TOTAL_RETURNED_QUANTITY"
FROM "s1"
ORDER BY "R_NAME" DESC NULLS FIRST