SELECT COALESCE("region"."r_name", "region"."r_name") AS "R_NAME", COUNT(DISTINCT "supplier"."s_suppkey") AS "SUPPLIER_COUNT", AVG("t2"."TOTAL_SPENT") AS "AVG_CUSTOMER_SPENT", MAX("partsupp0"."ps_supplycost") AS "MAX_SUPPLY_COST", SUM(CASE WHEN "lineitem"."l_discount" > 0.05 THEN "lineitem"."l_extendedprice" * (1 - "lineitem"."l_discount") ELSE NULL END) AS "TOTAL_DISCOUNTED_SALES", SUM(CASE WHEN "lineitem"."l_returnflag" = 'R' THEN "lineitem"."l_quantity" ELSE 0.00 END) AS "TOTAL_RETURNED_QUANTITY"
FROM "TPCH"."region"
LEFT JOIN "TPCH"."nation" ON "region"."r_regionkey" = "nation"."n_regionkey"
LEFT JOIN "TPCH"."supplier" ON "nation"."n_nationkey" = "supplier"."s_nationkey"
LEFT JOIN (SELECT "ps_suppkey" AS "PS_SUPPKEY", MAX("ps_supplycost") AS "MAX_SUPPLYCOST"
FROM "TPCH"."partsupp"
GROUP BY "ps_suppkey") AS "t0" ON "supplier"."s_suppkey" = "t0"."PS_SUPPKEY"
LEFT JOIN "TPCH"."partsupp" AS "partsupp0" ON "supplier"."s_suppkey" = "partsupp0"."ps_suppkey"
LEFT JOIN "TPCH"."lineitem" ON "partsupp0"."ps_partkey" = "lineitem"."l_partkey"
LEFT JOIN (SELECT "customer"."c_custkey" AS "C_CUSTKEY", "customer"."c_name" AS "C_NAME", COUNT("orders"."o_orderkey") AS "ORDER_COUNT", SUM("orders"."o_totalprice") AS "TOTAL_SPENT"
FROM "TPCH"."customer"
LEFT JOIN "TPCH"."orders" ON "customer"."c_custkey" = "orders"."o_custkey"
GROUP BY "customer"."c_custkey", "customer"."c_name") AS "t2" ON "supplier"."s_suppkey" = "t2"."C_CUSTKEY"
WHERE "partsupp0"."ps_availqty" > 10 AND ("supplier"."s_acctbal" IS NOT NULL OR "supplier"."s_name" LIKE 'Supplier%')
GROUP BY "region"."r_name"