SELECT COALESCE("NATION_NAME", "NATION_NAME") AS "NATION_NAME", "TOTAL_SALES", "ORDER_COUNT", "LAST_SHIP_DATE", "PRODUCT_NAMES"
FROM "s1"
ORDER BY "TOTAL_SALES" DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY