SELECT COALESCE("region"."r_regionkey", "region"."r_regionkey") AS "r_regionkey", "region"."r_name", "region"."r_comment", "nation"."n_nationkey", "nation"."n_name", "nation"."n_regionkey", "nation"."n_comment", "supplier"."s_suppkey", "supplier"."s_name", "supplier"."s_address", "supplier"."s_nationkey", "supplier"."s_phone", "supplier"."s_acctbal", "supplier"."s_comment", "partsupp"."ps_partkey", "partsupp"."ps_suppkey", "partsupp"."ps_availqty", "partsupp"."ps_supplycost", "partsupp"."ps_comment", "part"."p_partkey", "part"."p_name", "part"."p_mfgr", "part"."p_brand", "part"."p_type", "part"."p_size", "part"."p_container", "part"."p_retailprice", "part"."p_comment", "lineitem"."l_orderkey", "lineitem"."l_partkey", "lineitem"."l_suppkey", "lineitem"."l_linenumber", "lineitem"."l_quantity", "lineitem"."l_extendedprice", "lineitem"."l_discount", "lineitem"."l_tax", "lineitem"."l_returnflag", "lineitem"."l_linestatus", "lineitem"."l_shipdate", "lineitem"."l_commitdate", "lineitem"."l_receiptdate", "lineitem"."l_shipinstruct", "lineitem"."l_shipmode", "lineitem"."l_comment", "t0"."O_ORDERKEY", "t0"."O_ORDERDATE", "t0"."O_TOTALPRICE", "t0"."RANK_VAL", "t2"."C_CUSTKEY", "t2"."C_NAME", "t2"."C_ACCTBAL", "t2"."CONTACT_NUMBER"
FROM "TPCH"."region"
INNER JOIN "TPCH"."nation" ON "region"."r_regionkey" = "nation"."n_regionkey"
INNER JOIN "TPCH"."supplier" ON "nation"."n_nationkey" = "supplier"."s_nationkey"
INNER JOIN "TPCH"."partsupp" ON "supplier"."s_suppkey" = "partsupp"."ps_suppkey"
INNER JOIN "TPCH"."part" ON "partsupp"."ps_partkey" = "part"."p_partkey"
INNER JOIN "TPCH"."lineitem" ON "part"."p_partkey" = "lineitem"."l_partkey"
INNER JOIN (SELECT "orders"."o_orderkey" AS "O_ORDERKEY", "orders"."o_orderdate" AS "O_ORDERDATE", "orders"."o_totalprice" AS "O_TOTALPRICE", RANK() OVER (PARTITION BY "orders"."o_orderkey" ORDER BY "lineitem0"."l_orderkey") AS "RANK_VAL"
FROM "TPCH"."orders"
INNER JOIN "TPCH"."lineitem" AS "lineitem0" ON "orders"."o_orderkey" = "lineitem0"."l_orderkey"
WHERE "orders"."o_orderstatus" = 'O') AS "t0" ON "lineitem"."l_orderkey" = "t0"."O_ORDERKEY"
INNER JOIN (SELECT "c_custkey" AS "C_CUSTKEY", "c_name" AS "C_NAME", "c_acctbal" AS "C_ACCTBAL", CASE WHEN CASE WHEN "c_phone" = '' THEN NULL ELSE "c_phone" END IS NOT NULL THEN CAST(CASE WHEN "c_phone" = '' THEN NULL ELSE "c_phone" END AS VARCHAR CHARACTER SET "ISO-8859-1") ELSE 'N/A' END AS "CONTACT_NUMBER"
FROM "TPCH"."customer"
WHERE "c_acctbal" > 1000.00) AS "t2" ON "t0"."O_ORDERKEY" = "t2"."C_CUSTKEY"