SELECT COALESCE("R_NAME", "R_NAME") AS "R_NAME", "TOTAL_RETURNED", "TOTAL_CUSTOMERS", "AVG_SUPPLIER_ACCT_BAL", "TOTAL_ORDERS", "TOTAL_QTY_AVAILABLE", "MAX_SUPPLY_COST"
FROM "s1"
ORDER BY "TOTAL_ORDERS" DESC NULLS FIRST