SELECT COALESCE("t0"."REGION_NAME", "t0"."REGION_NAME") AS "REGION_NAME", "t0"."NATION_NAME", "t0"."C_CUSTKEY", "t2"."O_TOTALPRICE", "lineitem"."l_extendedprice" * (1 - "lineitem"."l_discount") AS "FD_COL_4", "t4"."SUPPLIER_COUNT"
FROM (SELECT "customer"."c_custkey" AS "C_CUSTKEY", "nation"."n_name" AS "NATION_NAME", "region"."r_name" AS "REGION_NAME", "customer"."c_acctbal" AS "C_ACCTBAL"
FROM "TPCH"."customer"
INNER JOIN "TPCH"."nation" ON "customer"."c_nationkey" = "nation"."n_nationkey"
INNER JOIN "TPCH"."region" ON "nation"."n_regionkey" = "region"."r_regionkey"
WHERE "customer"."c_acctbal" > 1000.00) AS "t0"
LEFT JOIN (SELECT "o_orderkey" AS "O_ORDERKEY", "o_orderdate" AS "O_ORDERDATE", "o_totalprice" AS "O_TOTALPRICE", "o_orderstatus" AS "O_ORDERSTATUS", DENSE_RANK() OVER (PARTITION BY "o_orderstatus" ORDER BY "o_totalprice" DESC NULLS FIRST) AS "ORDER_RANK", "o_custkey" AS "O_CUSTKEY"
FROM "TPCH"."orders"
WHERE "o_orderdate" >= DATE '1996-01-01' AND "o_orderdate" < DATE '1997-01-01') AS "t2" ON "t0"."C_CUSTKEY" = "t2"."O_CUSTKEY"
LEFT JOIN "TPCH"."lineitem" ON "t2"."O_ORDERKEY" = "lineitem"."l_orderkey"
LEFT JOIN (SELECT "ps_partkey" AS "PS_PARTKEY", COUNT(DISTINCT "ps_suppkey") AS "SUPPLIER_COUNT"
FROM "TPCH"."partsupp"
GROUP BY "ps_partkey") AS "t4" ON "lineitem"."l_partkey" = "t4"."PS_PARTKEY"