SELECT COALESCE("t8"."C_CUSTKEY", "t8"."C_CUSTKEY") AS "C_CUSTKEY", "t8"."C_NAME", "t8"."CUSTOMER_TOTAL_SPENT", "t8"."TOTAL_ORDERS", "t8"."AVG_LINEITEM_PRICE", "t8"."LAST_ORDER_DATE"
FROM (SELECT "t5"."C_CUSTKEY", "t5"."C_NAME", SUM("lineitem0"."l_extendedprice" * (1 - "lineitem0"."l_discount")) AS "CUSTOMER_TOTAL_SPENT", COUNT(DISTINCT "orders1"."o_orderkey") AS "TOTAL_ORDERS", AVG("lineitem0"."l_extendedprice") AS "AVG_LINEITEM_PRICE", MAX("lineitem0"."l_shipdate") AS "LAST_ORDER_DATE"
FROM (SELECT "C_CUSTKEY", "C_NAME", SUM("TOTAL_REVENUE") AS "REVENUE"
FROM "s1"
GROUP BY "C_CUSTKEY", "C_NAME"
ORDER BY 3 DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY) AS "t5"
INNER JOIN "TPCH"."orders" AS "orders1" ON "t5"."C_CUSTKEY" = "orders1"."o_custkey"
INNER JOIN "TPCH"."lineitem" AS "lineitem0" ON "orders1"."o_orderkey" = "lineitem0"."l_orderkey"
GROUP BY "t5"."C_CUSTKEY", "t5"."C_NAME"
ORDER BY 3 DESC NULLS FIRST) AS "t8"