SELECT COALESCE("r_name", "r_name") AS "REGION_NAME", "n_name" AS "NATION_NAME", "S_NAME" AS "SUPPLIER_NAME", "P_NAME" AS "PART_NAME", "AVG_EXTENDED_PRICE", "TOTAL_SUPPLY_COST"
FROM "s1"
WHERE "TOTAL_SUPPLY_COST" > 50000.00
ORDER BY "r_name", "n_name", "TOTAL_SUPPLY_COST" DESC NULLS FIRST