SELECT COALESCE("t2"."r_regionkey", "t2"."r_regionkey") AS "r_regionkey", "t2"."r_name", "t2"."r_comment", "t2"."n_nationkey", "t2"."n_name", "t2"."n_regionkey", "t2"."n_comment", "t2"."S_SUPPKEY", "t2"."S_NAME", "t2"."TOTAL_SUPPLY_COST", "t6"."P_PARTKEY", "t6"."P_NAME", "t6"."AVG_EXTENDED_PRICE"
FROM (SELECT "t"."r_regionkey", "t"."r_name", "t"."r_comment", "t"."n_nationkey", "t"."n_name", "t"."n_regionkey", "t"."n_comment", "t1"."S_SUPPKEY", "t1"."S_NAME", "t1"."TOTAL_SUPPLY_COST"
FROM (SELECT "region"."r_regionkey", "region"."r_name", "region"."r_comment", "nation"."n_nationkey", "nation"."n_name", "nation"."n_regionkey", "nation"."n_comment", CAST("nation"."n_nationkey" AS BIGINT) AS "n_nationkey0"
FROM "TPCH"."region"
INNER JOIN "TPCH"."nation" ON "region"."r_regionkey" = "nation"."n_regionkey") AS "t"
INNER JOIN (SELECT "supplier"."s_suppkey" AS "S_SUPPKEY", "supplier"."s_name" AS "S_NAME", SUM("partsupp"."ps_supplycost" * "partsupp"."ps_availqty") AS "TOTAL_SUPPLY_COST"
FROM "TPCH"."supplier"
INNER JOIN "TPCH"."partsupp" ON "supplier"."s_suppkey" = "partsupp"."ps_suppkey"
GROUP BY "supplier"."s_suppkey", "supplier"."s_name") AS "t1" ON "t"."n_nationkey0" = "t1"."S_SUPPKEY") AS "t2"
INNER JOIN (SELECT "part"."p_partkey" AS "P_PARTKEY", "part"."p_name" AS "P_NAME", AVG("lineitem"."l_extendedprice") AS "AVG_EXTENDED_PRICE"
FROM "TPCH"."part"
INNER JOIN "TPCH"."lineitem" ON "part"."p_partkey" = "lineitem"."l_partkey"
WHERE "lineitem"."l_shipdate" >= '1997-01-01' AND "lineitem"."l_shipdate" <= '1997-12-31'
GROUP BY "part"."p_partkey", "part"."p_name"
HAVING AVG("lineitem"."l_extendedprice") > 100.00) AS "t6" ON "t2"."S_SUPPKEY" = "t6"."P_PARTKEY"