SELECT COALESCE("NATION", "NATION") AS "NATION", "TOTAL_REVENUE", "AVG_SUPPLIER_BALANCE", "TOTAL_ORDERS", "TOTAL_CUSTOMERS"
FROM (SELECT ANY_VALUE("n_name") AS "NATION", SUM("FD_COL_1") AS "TOTAL_REVENUE", AVG("s_acctbal") AS "AVG_SUPPLIER_BALANCE", COUNT(DISTINCT "o_orderkey") AS "TOTAL_ORDERS", COUNT(DISTINCT "c_custkey") AS "TOTAL_CUSTOMERS"
FROM "s1"
GROUP BY "n_name"
HAVING SUM("FD_COL_1") > 500000.0000
ORDER BY 2 DESC NULLS FIRST) AS "t5"