SELECT COALESCE("t6"."N_NAME", "t6"."N_NAME") AS "N_NAME", "t6"."TOTAL_ACCTBAL", "t6"."TOTAL_SUPPLYCOST", "t6"."TOTAL_ORDERVALUE", "t9"."TOTAL_LINES"
FROM (SELECT "t0"."N_NAME", "t0"."TOTAL_ACCTBAL", "t2"."P_PARTKEY", "t2"."TOTAL_SUPPLYCOST", "t5"."C_CUSTKEY", "t5"."TOTAL_ORDERVALUE"
FROM (SELECT "nation"."n_name" AS "N_NAME", SUM("supplier"."s_acctbal") AS "TOTAL_ACCTBAL"
FROM "TPCH"."nation"
INNER JOIN "TPCH"."supplier" ON "nation"."n_nationkey" = "supplier"."s_nationkey"
GROUP BY "nation"."n_name") AS "t0"
INNER JOIN (SELECT "part"."p_partkey" AS "P_PARTKEY", SUM("partsupp"."ps_supplycost" * "partsupp"."ps_availqty") AS "TOTAL_SUPPLYCOST"
FROM "TPCH"."part"
INNER JOIN "TPCH"."partsupp" ON "part"."p_partkey" = "partsupp"."ps_partkey"
GROUP BY "part"."p_partkey") AS "t2" ON "t0"."N_NAME" = 'USA'
INNER JOIN (SELECT "customer"."c_custkey" AS "C_CUSTKEY", SUM("orders"."o_totalprice") AS "TOTAL_ORDERVALUE", SUM("orders"."o_totalprice") > 100000.00 AS "$f2"
FROM "TPCH"."customer"
INNER JOIN "TPCH"."orders" ON "customer"."c_custkey" = "orders"."o_custkey"
GROUP BY "customer"."c_custkey") AS "t5" ON "t5"."$f2") AS "t6"
INNER JOIN (SELECT "orders0"."o_orderkey" AS "O_ORDERKEY", COUNT(*) AS "TOTAL_LINES", COUNT(*) > 5 AS "$f2"
FROM "TPCH"."orders" AS "orders0"
INNER JOIN "TPCH"."lineitem" ON "orders0"."o_orderkey" = "lineitem"."l_orderkey"
GROUP BY "orders0"."o_orderkey") AS "t9" ON "t9"."$f2"