SELECT COALESCE("N_NAME", "N_NAME") AS "N_NAME", "TOTAL_ACCTBAL", "TOTAL_SUPPLYCOST", "TOTAL_ORDERVALUE", "TOTAL_LINES"
FROM "s1"
ORDER BY "TOTAL_ACCTBAL" DESC NULLS FIRST, "TOTAL_SUPPLYCOST" DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY