SELECT COALESCE("R_NAME", "R_NAME") AS "R_NAME", "TOTAL_CUSTOMERS", "TOTAL_PARTS_AVAILABLE", "TOTAL_REVENUE"
FROM (SELECT "R_NAME", COUNT(DISTINCT "c_custkey") AS "TOTAL_CUSTOMERS", SUM("FD_COL_2") AS "TOTAL_PARTS_AVAILABLE", SUM("FD_COL_3") AS "TOTAL_REVENUE"
FROM "s1"
GROUP BY "R_NAME"
ORDER BY 4 DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY) AS "t7"