SELECT COALESCE("S_NAME", "S_NAME") AS "SUPPLIER_NAME", "C_NAME" AS "CUSTOMER_NAME", "TOTAL_SPENT"
FROM "s1"
WHERE "l_shipdate" >= '1997-01-01' AND "l_shipdate" < '1997-12-31'
ORDER BY "S_NAME", "TOTAL_SPENT" DESC NULLS FIRST