SELECT COALESCE("REGION_NAME", "REGION_NAME") AS "REGION_NAME", "TOTAL_SALES", "UNIQUE_CUSTOMERS", "ORDER_COUNT", "AVG_SALES_PER_CUSTOMER", "AVG_SALES_PER_ORDER"
FROM (SELECT ANY_VALUE("r_name") AS "REGION_NAME", SUM("l_extendedprice" * (1 - "l_discount")) AS "TOTAL_SALES", COUNT(DISTINCT "c_custkey") AS "UNIQUE_CUSTOMERS", COUNT(DISTINCT "o_orderkey") AS "ORDER_COUNT", SUM("l_extendedprice" * (1 - "l_discount")) / CASE WHEN COUNT(DISTINCT "c_custkey") = 0 THEN NULL ELSE COUNT(DISTINCT "c_custkey") END AS "AVG_SALES_PER_CUSTOMER", SUM("l_extendedprice" * (1 - "l_discount")) / CASE WHEN COUNT(DISTINCT "o_orderkey") = 0 THEN NULL ELSE COUNT(DISTINCT "o_orderkey") END AS "AVG_SALES_PER_ORDER"
FROM "s1"
WHERE "o_orderdate" >= DATE '1997-01-01' AND "o_orderdate" < DATE '1997-10-01'
GROUP BY "r_regionkey", "r_name"
ORDER BY 2 DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY) AS "t4"