SELECT COALESCE("SUPPLIER_NATION", "SUPPLIER_NATION") AS "SUPPLIER_NATION", AVG("TOTAL_ORDER_VALUE") AS "AVG_ORDER_VALUE", SUM("TOTAL_SUPPLY_COST") AS "TOTAL_SUPPLY_COST"
FROM "s1"
GROUP BY "SUPPLIER_NATION"
ORDER BY "SUPPLIER_NATION"