SELECT COALESCE("t1"."NATION_NAME", "t1"."NATION_NAME") AS "NATION_NAME", "t1"."REGION_NAME", "t3"."PS_SUPPLYCOST", "t3"."PS_AVAILQTY", "t3"."P_NAME"
FROM (SELECT ANY_VALUE("nation"."n_name") AS "NATION_NAME", ANY_VALUE("region"."r_name") AS "REGION_NAME", COUNT(DISTINCT "supplier"."s_suppkey") AS "SUPPLIER_COUNT", SUM("supplier"."s_acctbal") AS "TOTAL_ACCTBAL"
FROM "TPCH"."supplier"
INNER JOIN "TPCH"."nation" ON "supplier"."s_nationkey" = "nation"."n_nationkey"
INNER JOIN "TPCH"."region" ON "nation"."n_regionkey" = "region"."r_regionkey"
GROUP BY "nation"."n_name", "region"."r_name") AS "t1"
LEFT JOIN (SELECT "part"."p_name" AS "P_NAME", "partsupp"."ps_availqty" AS "PS_AVAILQTY", "partsupp"."ps_supplycost" AS "PS_SUPPLYCOST", "partsupp"."ps_comment" AS "PS_COMMENT", "region0"."r_name" AS "REGION_NAME"
FROM "TPCH"."part"
INNER JOIN "TPCH"."partsupp" ON "part"."p_partkey" = "partsupp"."ps_partkey"
INNER JOIN "TPCH"."supplier" AS "supplier0" ON "partsupp"."ps_suppkey" = "supplier0"."s_suppkey"
INNER JOIN "TPCH"."nation" AS "nation0" ON "supplier0"."s_nationkey" = "nation0"."n_nationkey"
INNER JOIN "TPCH"."region" AS "region0" ON "nation0"."n_regionkey" = "region0"."r_regionkey"
WHERE "partsupp"."ps_availqty" > 0) AS "t3" ON "t1"."REGION_NAME" = "t3"."REGION_NAME"