SELECT COALESCE("REVENUE_TIER", "REVENUE_TIER") AS "REVENUE_TIER", COUNT(*) AS "NATION_COUNT", AVG("TOTAL_REVENUE") AS "AVG_REVENUE", SUM("TOTAL_ORDERS") AS "TOTAL_ORDERS_AGGREGATED"
FROM (SELECT CASE WHEN SUM("l_extendedprice" * (1 - "l_discount")) >= 1000000.0000 THEN 'High  ' WHEN SUM("l_extendedprice" * (1 - "l_discount")) >= 500000.0000 THEN 'Medium' ELSE 'Low   ' END AS "REVENUE_TIER", SUM("l_extendedprice" * (1 - "l_discount")) AS "TOTAL_REVENUE", COUNT(DISTINCT "o_orderkey") AS "TOTAL_ORDERS"
FROM "s1"
WHERE "o_orderdate" >= DATE '1996-01-01' AND "o_orderdate" < DATE '1997-01-01'
GROUP BY "n_name") AS "t3"
GROUP BY "REVENUE_TIER"
ORDER BY "REVENUE_TIER" DESC NULLS FIRST