SELECT COALESCE("REGION", "REGION") AS "REGION", "REVENUE", "ORDERCOUNT", "CUSTOMERCOUNT", "SUPPLIERCOUNT"
FROM (SELECT ANY_VALUE("r_name") AS "REGION", SUM("FD_COL_1") AS "REVENUE", COUNT(DISTINCT "o_orderkey") AS "ORDERCOUNT", COUNT(DISTINCT "c_custkey") AS "CUSTOMERCOUNT", COUNT(DISTINCT "S_SUPPKEY") AS "SUPPLIERCOUNT"
FROM "s1"
GROUP BY "r_name"
HAVING SUM("FD_COL_1") > 50000.0000
ORDER BY 2 DESC NULLS FIRST) AS "t8"