SELECT COALESCE("NATION_NAME", "NATION_NAME") AS "NATION_NAME", "REGION_NAME", "TOTAL_REVENUE", "NUMBER_OF_ORDERS", "UNIQUE_CUSTOMERS"
FROM (SELECT ANY_VALUE("n_name") AS "NATION_NAME", ANY_VALUE("r_name") AS "REGION_NAME", SUM("l_extendedprice" * (1 - "l_discount")) AS "TOTAL_REVENUE", COUNT(DISTINCT "o_orderkey") AS "NUMBER_OF_ORDERS", COUNT(DISTINCT "c_custkey") AS "UNIQUE_CUSTOMERS"
FROM "s1"
WHERE "o_orderdate" >= DATE '1997-01-01' AND "o_orderdate" < DATE '1997-10-01' AND ("l_shipmode" = 'AIR' OR "l_shipmode" = 'TRUCK')
GROUP BY "n_name", "r_name"
ORDER BY 3 DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY) AS "t4"