SELECT COALESCE("O_ORDERKEY", "O_ORDERKEY") AS "O_ORDERKEY", "O_TOTALPRICE", "C_NAME", "S_NAME", "TOTAL_SUPPLY_VALUE", "TOTAL_LINE_VALUE"
FROM "s1"
ORDER BY "O_TOTALPRICE" DESC NULLS FIRST, "TOTAL_SUPPLY_VALUE"
FETCH NEXT 50 ROWS ONLY