SELECT COALESCE("t7"."O_ORDERKEY", "t7"."O_ORDERKEY") AS "O_ORDERKEY", "t7"."O_TOTALPRICE", "t7"."C_NAME", "t9"."S_NAME", "t9"."TOTAL_SUPPLY_VALUE", "t11"."TOTAL_LINE_VALUE"
FROM (SELECT "t2"."O_ORDERKEY", "t2"."O_TOTALPRICE", "t2"."C_NAME", "t4"."S_NAME", "t4"."TOTAL_SUPPLY_VALUE", "t6"."TOTAL_LINE_VALUE"
FROM (SELECT "orders"."o_orderkey" AS "O_ORDERKEY", "orders"."o_totalprice" AS "O_TOTALPRICE", "customer"."c_name" AS "C_NAME"
FROM "TPCH"."orders"
INNER JOIN "TPCH"."customer" ON "orders"."o_custkey" = "customer"."c_custkey"
WHERE "orders"."o_totalprice" > (((SELECT AVG("o_totalprice")
FROM "TPCH"."orders")))) AS "t2"
INNER JOIN (SELECT "supplier"."s_suppkey" AS "S_SUPPKEY", "supplier"."s_name" AS "S_NAME", SUM("partsupp"."ps_supplycost" * "partsupp"."ps_availqty") AS "TOTAL_SUPPLY_VALUE"
FROM "TPCH"."supplier"
INNER JOIN "TPCH"."partsupp" ON "supplier"."s_suppkey" = "partsupp"."ps_suppkey"
GROUP BY "supplier"."s_suppkey", "supplier"."s_name") AS "t4" ON "t2"."O_ORDERKEY" = "t4"."S_SUPPKEY"
INNER JOIN (SELECT "l_orderkey" AS "L_ORDERKEY", SUM("l_extendedprice" * (1 - "l_discount")) AS "TOTAL_LINE_VALUE"
FROM "TPCH"."lineitem"
GROUP BY "l_orderkey") AS "t6" ON "t2"."O_ORDERKEY" = "t6"."L_ORDERKEY") AS "t7"
INNER JOIN (SELECT "supplier0"."s_suppkey" AS "S_SUPPKEY", "supplier0"."s_name" AS "S_NAME", SUM("partsupp0"."ps_supplycost" * "partsupp0"."ps_availqty") AS "TOTAL_SUPPLY_VALUE"
FROM "TPCH"."supplier" AS "supplier0"
INNER JOIN "TPCH"."partsupp" AS "partsupp0" ON "supplier0"."s_suppkey" = "partsupp0"."ps_suppkey"
GROUP BY "supplier0"."s_suppkey", "supplier0"."s_name") AS "t9" ON "t7"."S_NAME" = "t9"."S_NAME"
INNER JOIN (SELECT "l_orderkey" AS "L_ORDERKEY", SUM("l_extendedprice" * (1 - "l_discount")) AS "TOTAL_LINE_VALUE"
FROM "TPCH"."lineitem"
GROUP BY "l_orderkey") AS "t11" ON "t7"."O_ORDERKEY" = "t11"."L_ORDERKEY"
WHERE "t9"."TOTAL_SUPPLY_VALUE" > 100000.00