SELECT COALESCE("NATION", "NATION") AS "NATION", "REGION", "TOTAL_REVENUE", "TOTAL_ORDERS", "UNIQUE_CUSTOMERS", "AVERAGE_ORDER_VALUE"
FROM (SELECT ANY_VALUE("n_name") AS "NATION", ANY_VALUE("r_name") AS "REGION", SUM("l_extendedprice" * (1 - "l_discount")) AS "TOTAL_REVENUE", COUNT(DISTINCT "o_orderkey") AS "TOTAL_ORDERS", COUNT(DISTINCT "c_custkey") AS "UNIQUE_CUSTOMERS", AVG("o_totalprice") AS "AVERAGE_ORDER_VALUE"
FROM "s1"
WHERE "o_orderdate" >= DATE '1996-01-01' AND "o_orderdate" < DATE '1997-01-01' AND ("l_shipmode" = 'TRUCK' OR "l_shipmode" = 'AIR')
GROUP BY "n_name", "r_name"
ORDER BY 3 DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY) AS "t4"