SELECT COALESCE("REGION_NAME", "REGION_NAME") AS "REGION_NAME", "TOTAL_SALES", "ORDER_COUNT", "SALES_VARIANCE_PERCENTAGE", "ORDER_COUNT_VARIANCE_PERCENTAGE"
FROM "s1"
ORDER BY "TOTAL_SALES" DESC NULLS FIRST