SELECT COALESCE("t2"."p_partkey", "t2"."p_partkey") AS "P_PARTKEY", "t2"."p_name" AS "P_NAME", "t2"."p_brand" AS "P_BRAND", "t4"."CUSTOMER_COUNT", "t4"."TOTAL_ORDER_VALUE", "region"."r_name", "t2"."TOTAL_SUPPLY_COST"
FROM (SELECT "part"."p_partkey", "part"."p_name", "part"."p_mfgr", "part"."p_brand", "part"."p_type", "part"."p_size", "part"."p_container", "part"."p_retailprice", "part"."p_comment", "t1"."S_SUPPKEY", "t1"."S_NAME", "t1"."S_NATIONKEY", "t1"."TOTAL_SUPPLY_COST"
FROM "TPCH"."part"
INNER JOIN (SELECT "supplier"."s_suppkey" AS "S_SUPPKEY", "supplier"."s_name" AS "S_NAME", "supplier"."s_nationkey" AS "S_NATIONKEY", SUM("partsupp"."ps_supplycost" * "partsupp"."ps_availqty") AS "TOTAL_SUPPLY_COST", SUM("partsupp"."ps_supplycost" * "partsupp"."ps_availqty") > 10000.00 AS "$f4"
FROM "TPCH"."supplier"
INNER JOIN "TPCH"."partsupp" ON "supplier"."s_suppkey" = "partsupp"."ps_suppkey"
GROUP BY "supplier"."s_suppkey", "supplier"."s_name", "supplier"."s_nationkey") AS "t1" ON "t1"."$f4") AS "t2"
INNER JOIN "TPCH"."supplier" AS "supplier0" ON "t2"."p_partkey" = "supplier0"."s_suppkey"
INNER JOIN "TPCH"."nation" ON "supplier0"."s_nationkey" = "nation"."n_nationkey"
INNER JOIN "TPCH"."region" ON "nation"."n_regionkey" = "region"."r_regionkey"
INNER JOIN (SELECT "nation0"."n_nationkey" AS "N_NATIONKEY", "nation0"."n_name" AS "N_NAME", COUNT(DISTINCT "customer"."c_custkey") AS "CUSTOMER_COUNT", SUM("orders"."o_totalprice") AS "TOTAL_ORDER_VALUE"
FROM "TPCH"."nation" AS "nation0"
LEFT JOIN "TPCH"."customer" ON "nation0"."n_nationkey" = "customer"."c_nationkey"
LEFT JOIN "TPCH"."orders" ON "customer"."c_custkey" = "orders"."o_custkey"
GROUP BY "nation0"."n_nationkey", "nation0"."n_name") AS "t4" ON "nation"."n_nationkey" = "t4"."N_NATIONKEY"