SELECT COALESCE("SUPPLIER_NAME", "SUPPLIER_NAME") AS "SUPPLIER_NAME", "REGION", "NATION", "TOTAL_ORDERS"
FROM (SELECT ANY_VALUE("s_name") AS "SUPPLIER_NAME", ANY_VALUE("r_name") AS "REGION", ANY_VALUE("n_name") AS "NATION", SUM("FD_COL_4") AS "TOTAL_ORDERS"
FROM "s1"
GROUP BY "s_suppkey", "s_name", "r_name", "n_name"
HAVING SUM("FD_COL_5") > 100000.0000
ORDER BY 4 DESC NULLS FIRST) AS "t11"