SELECT COALESCE("supplier0"."s_suppkey", "supplier0"."s_suppkey") AS "s_suppkey", "supplier0"."s_name", "region"."r_name", "nation"."n_name", CASE WHEN "t4"."ORDER_COUNT" IS NOT NULL THEN CAST("t4"."ORDER_COUNT" AS BIGINT) ELSE 0 END AS "FD_COL_4", "lineitem0"."l_extendedprice" * (1 - "lineitem0"."l_discount") AS "FD_COL_5"
FROM (SELECT "supplier"."s_suppkey" AS "S_SUPPKEY", SUM("lineitem"."l_extendedprice" * (1 - "lineitem"."l_discount")) AS "TOTAL_REVENUE"
FROM "TPCH"."supplier"
INNER JOIN "TPCH"."partsupp" ON "supplier"."s_suppkey" = "partsupp"."ps_suppkey"
INNER JOIN "TPCH"."lineitem" ON "partsupp"."ps_partkey" = "lineitem"."l_partkey"
GROUP BY "supplier"."s_suppkey"
ORDER BY 2 DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY) AS "t2"
INNER JOIN "TPCH"."supplier" AS "supplier0" ON "t2"."S_SUPPKEY" = "supplier0"."s_suppkey"
INNER JOIN "TPCH"."partsupp" AS "partsupp0" ON "supplier0"."s_suppkey" = "partsupp0"."ps_suppkey"
INNER JOIN "TPCH"."lineitem" AS "lineitem0" ON "partsupp0"."ps_partkey" = "lineitem0"."l_partkey"
INNER JOIN "TPCH"."orders" ON "lineitem0"."l_orderkey" = "orders"."o_orderkey"
INNER JOIN "TPCH"."customer" ON "orders"."o_custkey" = "customer"."c_custkey"
INNER JOIN "TPCH"."nation" ON "supplier0"."s_nationkey" = "nation"."n_nationkey"
INNER JOIN "TPCH"."region" ON "nation"."n_regionkey" = "region"."r_regionkey"
LEFT JOIN (SELECT "customer0"."c_custkey" AS "C_CUSTKEY", COUNT("orders0"."o_orderkey") AS "ORDER_COUNT"
FROM "TPCH"."customer" AS "customer0"
LEFT JOIN "TPCH"."orders" AS "orders0" ON "customer0"."c_custkey" = "orders0"."o_custkey"
GROUP BY "customer0"."c_custkey") AS "t4" ON "customer"."c_custkey" = "t4"."C_CUSTKEY"
WHERE "orders"."o_orderdate" >= '1997-01-01' AND "orders"."o_orderdate" <= '1997-12-31'