SELECT COALESCE("part"."p_partkey", "part"."p_partkey") AS "P_PARTKEY", "part"."p_name" AS "P_NAME", "supplier"."s_name" AS "S_NAME", SUM("lineitem"."l_quantity") AS "TOTAL_QUANTITY", SUM("lineitem"."l_extendedprice" * (1 - "lineitem"."l_discount")) AS "REVENUE"
FROM "part"
INNER JOIN "partsupp" ON "part"."p_partkey" = "partsupp"."ps_partkey"
INNER JOIN "supplier" ON "partsupp"."ps_suppkey" = "supplier"."s_suppkey"
INNER JOIN "lineitem" ON "part"."p_partkey" = "lineitem"."l_partkey"
INNER JOIN "orders" ON "lineitem"."l_orderkey" = "orders"."o_orderkey"
GROUP BY "part"."p_partkey", "part"."p_name", "supplier"."s_name"