SELECT COALESCE("ACTOR_NAME", "ACTOR_NAME") AS "ACTOR_NAME", "MOVIE_TITLE", "ROLE_ORDER", "COMPANY_TYPE", "MOVIE_KEYWORD", "MOVIE_INFO", "ACTOR_GENDER", "production_year"
FROM "s1"
ORDER BY "production_year" DESC NULLS FIRST, "ACTOR_NAME", "ROLE_ORDER"
FETCH NEXT 100 ROWS ONLY