SELECT COALESCE("aka_name"."name", "aka_name"."name") AS "ACTOR_NAME", "aka_title"."title" AS "MOVIE_TITLE", "cast_info"."nr_order" AS "ROLE_ORDER", "company_type"."kind" AS "COMPANY_TYPE", "keyword"."keyword" AS "MOVIE_KEYWORD", "movie_info"."info" AS "MOVIE_INFO", "name"."gender" AS "ACTOR_GENDER", "aka_title"."production_year"
FROM "IMDB"."aka_name"
INNER JOIN "IMDB"."cast_info" ON "aka_name"."person_id" = "cast_info"."person_id"
INNER JOIN "IMDB"."aka_title" ON "cast_info"."movie_id" = "aka_title"."movie_id"
INNER JOIN "IMDB"."movie_companies" ON "aka_title"."id" = "movie_companies"."movie_id"
INNER JOIN "IMDB"."company_type" ON "movie_companies"."company_type_id" = "company_type"."id"
INNER JOIN "IMDB"."movie_keyword" ON "aka_title"."id" = "movie_keyword"."movie_id"
INNER JOIN "IMDB"."keyword" ON "movie_keyword"."keyword_id" = "keyword"."id"
INNER JOIN "IMDB"."movie_info" ON "aka_title"."id" = "movie_info"."movie_id"
INNER JOIN "IMDB"."name" ON "aka_name"."person_id" = "name"."imdb_id"
WHERE "aka_title"."production_year" >= 2000 AND "aka_title"."production_year" <= 2023