SELECT COALESCE(REGION_NAME, REGION_NAME) AS REGION_NAME, TOTAL_SALES, ORDER_COUNT, SALES_VARIANCE_PERCENTAGE, ORDER_COUNT_VARIANCE_PERCENTAGE
FROM (SELECT REGION_NAME, TOTAL_SALES, ORDER_COUNT, (TOTAL_SALES - AVG_SALES) / CASE WHEN AVG_SALES = 0.0000 THEN NULL ELSE AVG_SALES END * 100 AS SALES_VARIANCE_PERCENTAGE, (ORDER_COUNT - AVG_ORDER_COUNT) / CASE WHEN AVG_ORDER_COUNT = 0 THEN NULL ELSE AVG_ORDER_COUNT END * 100 AS ORDER_COUNT_VARIANCE_PERCENTAGE
FROM s1
ORDER BY TOTAL_SALES DESC NULLS FIRST) AS t9