SELECT COALESCE("ACTOR_NAME", "ACTOR_NAME") AS "ACTOR_NAME", "MOVIE_TITLE", "PRODUCTION_YEAR", "CAST_TYPE", "MOVIE_KEYWORD"
FROM (SELECT "name" AS "ACTOR_NAME", "title" AS "MOVIE_TITLE", "production_year" AS "PRODUCTION_YEAR", "kind" AS "CAST_TYPE", "keyword" AS "MOVIE_KEYWORD"
FROM "s1"
ORDER BY "production_year" DESC NULLS FIRST, "name") AS "t2"