SELECT COALESCE("t7"."TITLE", "t7"."TITLE") AS "TITLE", "t7"."CAST_COUNT", "t7"."AVG_ORDER", "t7"."KEYWORD", "t7"."MOVIE_COUNT", "t10"."COMPANY_NAME", "t10"."MOVIES_PRODUCED"
FROM (SELECT "t6"."TITLE", "t6"."CAST_COUNT", "t6"."AVG_ORDER", "t0"."keyword" AS "KEYWORD", "t0"."MOVIE_COUNT"
FROM (SELECT "keyword"."keyword", COUNT("movie_keyword"."movie_id") AS "MOVIE_COUNT"
FROM "IMDB"."movie_keyword"
RIGHT JOIN "IMDB"."keyword" ON "movie_keyword"."keyword_id" = "keyword"."id"
GROUP BY "keyword"."keyword"
HAVING COUNT("movie_keyword"."movie_id") > 5) AS "t0",
(SELECT "t2"."title" AS "TITLE", COUNT(DISTINCT "t2"."person_id") AS "CAST_COUNT", AVG(CASE WHEN "t2"."nr_order" IS NOT NULL THEN CAST("t2"."nr_order" AS INTEGER) ELSE 0 END) AS "AVG_ORDER", COUNT(DISTINCT "t2"."person_id") > 10 AS "$f3"
FROM (SELECT MAX("production_year") AS "EXPR$0"
FROM "IMDB"."aka_title") AS "t1"
INNER JOIN (SELECT "aka_title0"."id", "aka_title0"."movie_id", "aka_title0"."title", "aka_title0"."imdb_index", "aka_title0"."kind_id", "aka_title0"."production_year", "aka_title0"."phonetic_code", "aka_title0"."episode_of_id", "aka_title0"."season_nr", "aka_title0"."episode_nr", "aka_title0"."note", "aka_title0"."md5sum", "cast_info"."id" AS "id0", "cast_info"."person_id", "cast_info"."movie_id" AS "movie_id0", "cast_info"."person_role_id", "cast_info"."note" AS "note0", "cast_info"."nr_order", "cast_info"."role_id"
FROM "IMDB"."cast_info"
RIGHT JOIN "IMDB"."aka_title" AS "aka_title0" ON "cast_info"."movie_id" = "aka_title0"."id") AS "t2" ON "t1"."EXPR$0" = "t2"."production_year"
GROUP BY "t2"."title"
HAVING COUNT(DISTINCT "t2"."person_id") > 10) AS "t6") AS "t7"
LEFT JOIN (SELECT ANY_VALUE("company_name"."name") AS "COMPANY_NAME", COUNT("movie_companies"."movie_id") AS "MOVIES_PRODUCED"
FROM "IMDB"."movie_companies"
RIGHT JOIN "IMDB"."company_name" ON "movie_companies"."company_id" = "company_name"."id"
GROUP BY "company_name"."name"
HAVING COUNT("movie_companies"."movie_id") > 10) AS "t10" ON "t7"."CAST_COUNT" < "t10"."MOVIES_PRODUCED"