SELECT COALESCE("t0"."MOVIE_ID", "t0"."MOVIE_ID") AS "MOVIE_ID", "t0"."KEYWORDS", "t5"."MOVIE_ID" AS "MOVIE_ID0", "t5"."TITLE", "t5"."PRODUCTION_YEAR", "t5"."AVG_STARRING_ROLES", "t5"."FULL_CAST_COUNT", "t5"."ACTORS_LIST"
FROM (SELECT "movie_keyword"."movie_id" AS "MOVIE_ID", LISTAGG(DISTINCT "keyword"."keyword", ', ') AS "KEYWORDS"
FROM "IMDB"."keyword"
INNER JOIN "IMDB"."movie_keyword" ON "keyword"."id" = "movie_keyword"."keyword_id"
GROUP BY "movie_keyword"."movie_id") AS "t0"
RIGHT JOIN (SELECT ANY_VALUE("t1"."id") AS "MOVIE_ID", "t1"."title" AS "TITLE", "t1"."production_year" AS "PRODUCTION_YEAR", CASE WHEN AVG(CASE WHEN "t1"."role_id" IS NOT NULL THEN 1 ELSE NULL END) IS NOT NULL THEN CAST(AVG(CASE WHEN "t1"."role_id" IS NOT NULL THEN 1 ELSE NULL END) AS INTEGER) ELSE 0 END AS "AVG_STARRING_ROLES", COUNT(DISTINCT "t1"."person_id") AS "FULL_CAST_COUNT", LISTAGG(DISTINCT "aka_name"."name", ', ') AS "ACTORS_LIST"
FROM (SELECT "aka_title"."id", "aka_title"."movie_id", "aka_title"."title", "aka_title"."imdb_index", "aka_title"."kind_id", "aka_title"."production_year", "aka_title"."phonetic_code", "aka_title"."episode_of_id", "aka_title"."season_nr", "aka_title"."episode_nr", "aka_title"."note", "aka_title"."md5sum", "cast_info"."id" AS "id0", "cast_info"."person_id", "cast_info"."movie_id" AS "movie_id0", "cast_info"."person_role_id", "cast_info"."note" AS "note0", "cast_info"."nr_order", "cast_info"."role_id"
FROM "IMDB"."cast_info"
RIGHT JOIN "IMDB"."aka_title" ON "cast_info"."movie_id" = "aka_title"."movie_id") AS "t1"
LEFT JOIN "IMDB"."aka_name" ON "t1"."person_id" = "aka_name"."person_id"
GROUP BY "t1"."id", "t1"."title", "t1"."production_year"
HAVING COUNT(DISTINCT "t1"."person_id") > 5 AND ("t1"."production_year" < 2000 OR CASE WHEN AVG(CASE WHEN "t1"."role_id" IS NOT NULL THEN 1 ELSE NULL END) IS NOT NULL THEN CAST(AVG(CASE WHEN "t1"."role_id" IS NOT NULL THEN 1 ELSE NULL END) AS INTEGER) ELSE 0 END > 2)) AS "t5" ON "t0"."MOVIE_ID" = "t5"."MOVIE_ID"