SELECT COALESCE("TITLE", "TITLE") AS "TITLE", "PRODUCTION_YEAR", "COMPANY_COUNT", "ACTOR_NAMES", "COMPANY_NOTES"
FROM (SELECT "TITLE", "production_year" AS "PRODUCTION_YEAR", "COMPANY_COUNT", "ACTOR_NAMES", "COMPANY_NOTES"
FROM "s1"
FETCH NEXT 100 ROWS ONLY) AS "t16"