SELECT COALESCE("t12"."MOVIE_ID", "t12"."MOVIE_ID") AS "MOVIE_ID", "t12"."TITLE", "t12"."COMPANY_COUNT", "t12"."COMPANY_NOTES", "t12"."CAST_COUNT", "t12"."ACTOR_NAMES", "t13"."id", "t13"."movie_id" AS "movie_id_", "t13"."title" AS "title_", "t13"."imdb_index", "t13"."kind_id", "t13"."production_year", "t13"."phonetic_code", "t13"."episode_of_id", "t13"."season_nr", "t13"."episode_nr", "t13"."note", "t13"."md5sum"
FROM (SELECT "t11"."MOVIE_ID", "t11"."TITLE", "t11"."COMPANY_COUNT", "t11"."COMPANY_NOTES", "t4"."CAST_COUNT", "t4"."ACTOR_NAMES"
FROM (SELECT ANY_VALUE("aka_title"."id") AS "MOVIE_ID", "aka_title"."title" AS "TITLE", "aka_title"."production_year" AS "PRODUCTION_YEAR", COUNT(DISTINCT "cast_info"."person_id") AS "CAST_COUNT", LISTAGG(DISTINCT "aka_name"."name", ', ') AS "ACTOR_NAMES"
FROM (SELECT "id" AS "ID"
FROM "IMDB"."kind_type"
WHERE "kind" = 'movie') AS "t0"
INNER JOIN "IMDB"."aka_title" ON "t0"."ID" = "aka_title"."kind_id"
INNER JOIN ("IMDB"."aka_name" INNER JOIN "IMDB"."cast_info" ON "aka_name"."person_id" = "cast_info"."person_id") ON "aka_title"."id" = "cast_info"."movie_id"
GROUP BY "aka_title"."id", "aka_title"."title", "aka_title"."production_year"
HAVING COUNT(DISTINCT "cast_info"."person_id") > 10) AS "t4"
INNER JOIN (SELECT "t9"."MOVIE_ID", "t9"."TITLE", COUNT(DISTINCT "movie_companies"."company_id") AS "COMPANY_COUNT", LISTAGG(DISTINCT "movie_companies"."note", ', ') AS "COMPANY_NOTES"
FROM (SELECT ANY_VALUE("aka_title0"."id") AS "MOVIE_ID", "aka_title0"."title" AS "TITLE", "aka_title0"."production_year" AS "PRODUCTION_YEAR", COUNT(DISTINCT "cast_info0"."person_id") AS "CAST_COUNT", LISTAGG(DISTINCT "aka_name0"."name", ', ') AS "ACTOR_NAMES"
FROM (SELECT "id" AS "ID"
FROM "IMDB"."kind_type"
WHERE "kind" = 'movie') AS "t6"
INNER JOIN "IMDB"."aka_title" AS "aka_title0" ON "t6"."ID" = "aka_title0"."kind_id"
INNER JOIN ("IMDB"."aka_name" AS "aka_name0" INNER JOIN "IMDB"."cast_info" AS "cast_info0" ON "aka_name0"."person_id" = "cast_info0"."person_id") ON "aka_title0"."id" = "cast_info0"."movie_id"
GROUP BY "aka_title0"."id", "aka_title0"."title", "aka_title0"."production_year") AS "t9"
INNER JOIN "IMDB"."movie_companies" ON "t9"."MOVIE_ID" = "movie_companies"."movie_id"
GROUP BY "t9"."MOVIE_ID", "t9"."TITLE") AS "t11" ON "t4"."MOVIE_ID" = "t11"."MOVIE_ID") AS "t12"
INNER JOIN (SELECT *
FROM "IMDB"."aka_title"
WHERE "production_year" >= 2000) AS "t13" ON "t12"."MOVIE_ID" = "t13"."id"