SELECT COALESCE("kind_type"."id", "kind_type"."id") AS "id", "kind_type"."kind", "t4"."PRODUCTION_YEAR", "t4"."KIND_ID", "t4"."TOTAL_MOVIES", "t4"."UNIQUE_ACTORS", "t4"."TOTAL_ROLES", "t4"."TOTAL_PRODUCTION_COMPANIES", "t4"."ALL_KEYWORDS"
FROM "IMDB"."kind_type"
INNER JOIN (SELECT "t3"."PRODUCTION_YEAR", "t3"."KIND_ID", COUNT(DISTINCT "t3"."TITLE") AS "TOTAL_MOVIES", COUNT(DISTINCT "t3"."ACTOR_NAME") AS "UNIQUE_ACTORS", SUM("t3"."NUM_ROLES") AS "TOTAL_ROLES", SUM("t3"."NUM_PRODUCTION_COMPANIES") AS "TOTAL_PRODUCTION_COMPANIES", LISTAGG(DISTINCT "t3"."KEYWORDS", "t3"."$f7") AS "ALL_KEYWORDS"
FROM (SELECT "t0"."production_year" AS "PRODUCTION_YEAR", "t0"."kind_id" AS "KIND_ID", "t0"."title" AS "TITLE", ANY_VALUE("t0"."name") AS "ACTOR_NAME", SUM(1) AS "NUM_ROLES", COUNT(DISTINCT "movie_companies"."company_id") AS "NUM_PRODUCTION_COMPANIES", LISTAGG(DISTINCT "keyword"."keyword", ', ') AS "KEYWORDS", ', ' AS "$f7"
FROM (SELECT "t"."id", "t"."movie_id", "t"."title", "t"."imdb_index", "t"."kind_id", "t"."production_year", "t"."phonetic_code", "t"."episode_of_id", "t"."season_nr", "t"."episode_nr", "t"."note", "t"."md5sum", "cast_info"."id" AS "id0", "cast_info"."person_id", "cast_info"."movie_id" AS "movie_id0", "cast_info"."person_role_id", "cast_info"."note" AS "note0", "cast_info"."nr_order", "cast_info"."role_id", "aka_name"."id" AS "id1", "aka_name"."person_id" AS "person_id0", "aka_name"."name", "aka_name"."imdb_index" AS "imdb_index0", "aka_name"."name_pcode_cf", "aka_name"."name_pcode_nf", "aka_name"."surname_pcode", "aka_name"."md5sum" AS "md5sum0", "movie_keyword"."id" AS "id2", "movie_keyword"."movie_id" AS "movie_id1", "movie_keyword"."keyword_id"
FROM "IMDB"."cast_info"
INNER JOIN ("IMDB"."movie_keyword" RIGHT JOIN (SELECT *
FROM "IMDB"."aka_title"
WHERE "production_year" >= 2000) AS "t" ON "movie_keyword"."movie_id" = "t"."id") ON "cast_info"."movie_id" = "t"."id"
INNER JOIN "IMDB"."aka_name" ON "cast_info"."person_id" = "aka_name"."person_id") AS "t0"
LEFT JOIN "IMDB"."keyword" ON "t0"."keyword_id" = "keyword"."id"
LEFT JOIN "IMDB"."movie_companies" ON "t0"."id" = "movie_companies"."movie_id"
GROUP BY "t0"."id", "t0"."title", "t0"."production_year", "t0"."kind_id", "t0"."name", "t0"."person_id0") AS "t3"
GROUP BY "t3"."PRODUCTION_YEAR", "t3"."KIND_ID") AS "t4" ON "kind_type"."id" = "t4"."KIND_ID"