SELECT COALESCE("MOVIE_ID0", "MOVIE_ID0") AS "MOVIE_ID0", "TITLE", "PRODUCTION_YEAR", ARRAY_AGG(DISTINCT "KEYWORD") AS "KEYWORDS", ARRAY_AGG(DISTINCT "ACTOR_NAME") AS "ACTORS", ARRAY_AGG(DISTINCT "ACTOR_ROLE") AS "ROLES", COUNT(DISTINCT "COMPANY_NAME") AS "COMPANY_COUNT"
FROM "s1"
GROUP BY "MOVIE_ID0", "TITLE", "PRODUCTION_YEAR"
ORDER BY "PRODUCTION_YEAR" DESC NULLS FIRST, "TITLE"