SELECT COALESCE("PRODUCTION_YEAR", "PRODUCTION_YEAR") AS "PRODUCTION_YEAR", "MOVIE_KIND", "TOTAL_MOVIES", "UNIQUE_ACTORS", "TOTAL_ROLES", "TOTAL_PRODUCTION_COMPANIES", "ALL_KEYWORDS"
FROM (SELECT "PRODUCTION_YEAR", "kind" AS "MOVIE_KIND", "TOTAL_MOVIES", "UNIQUE_ACTORS", "TOTAL_ROLES", "TOTAL_PRODUCTION_COMPANIES", "ALL_KEYWORDS"
FROM "s1"
ORDER BY "PRODUCTION_YEAR" DESC NULLS FIRST, "TOTAL_MOVIES" DESC NULLS FIRST) AS "t7"