SELECT COALESCE("t"."MOVIE_ID", "t"."MOVIE_ID") AS "MOVIE_ID", "t"."ACTOR_NAME", "t"."ACTOR_ROLE", "t4"."MOVIE_ID" AS "MOVIE_ID0", "t4"."TITLE", "t4"."PRODUCTION_YEAR", "t4"."KEYWORD", "t4"."COMPANY_NAME", "t4"."COMPANY_TYPE"
FROM (SELECT "cast_info"."movie_id" AS "MOVIE_ID", "aka_name"."name" AS "ACTOR_NAME", "role_type"."role" AS "ACTOR_ROLE"
FROM "IMDB"."role_type"
INNER JOIN ("IMDB"."aka_name" INNER JOIN "IMDB"."cast_info" ON "aka_name"."person_id" = "cast_info"."person_id") ON "role_type"."id" = "cast_info"."role_id") AS "t"
RIGHT JOIN (SELECT "t3"."id" AS "MOVIE_ID", "t3"."title" AS "TITLE", "t3"."production_year" AS "PRODUCTION_YEAR", "t3"."keyword" AS "KEYWORD", "company_name"."name" AS "COMPANY_NAME", "company_type"."kind" AS "COMPANY_TYPE"
FROM (SELECT "t2"."id", "t2"."movie_id", "t2"."title", "t2"."imdb_index", "t2"."kind_id", "t2"."production_year", "t2"."phonetic_code", "t2"."episode_of_id", "t2"."season_nr", "t2"."episode_nr", "t2"."note", "t2"."md5sum", "t2"."id0", "t2"."movie_id0", "t2"."keyword_id", "t2"."id1", "t2"."keyword", "t2"."phonetic_code0", "movie_companies"."id" AS "id2", "movie_companies"."movie_id" AS "movie_id1", "movie_companies"."company_id", "movie_companies"."company_type_id", "movie_companies"."note" AS "note0"
FROM "IMDB"."movie_companies"
RIGHT JOIN (SELECT "t1"."id", "t1"."movie_id", "t1"."title", "t1"."imdb_index", "t1"."kind_id", "t1"."production_year", "t1"."phonetic_code", "t1"."episode_of_id", "t1"."season_nr", "t1"."episode_nr", "t1"."note", "t1"."md5sum", "t1"."id0", "t1"."movie_id0", "t1"."keyword_id", CAST("keyword"."id" AS INTEGER) AS "id1", CAST("keyword"."keyword" AS VARCHAR CHARACTER SET "ISO-8859-1") AS "keyword", CAST("keyword"."phonetic_code" AS VARCHAR CHARACTER SET "ISO-8859-1") AS "phonetic_code0"
FROM "IMDB"."keyword"
INNER JOIN (SELECT "t0"."id", "t0"."movie_id", "t0"."title", "t0"."imdb_index", "t0"."kind_id", "t0"."production_year", "t0"."phonetic_code", "t0"."episode_of_id", "t0"."season_nr", "t0"."episode_nr", "t0"."note", "t0"."md5sum", "movie_keyword"."id" AS "id0", "movie_keyword"."movie_id" AS "movie_id0", "movie_keyword"."keyword_id"
FROM "IMDB"."movie_keyword"
RIGHT JOIN (SELECT *
FROM "IMDB"."aka_title"
WHERE "production_year" >= 2000) AS "t0" ON "movie_keyword"."movie_id" = "t0"."id") AS "t1" ON "keyword"."id" = "t1"."keyword_id") AS "t2" ON "movie_companies"."movie_id" = "t2"."id") AS "t3"
LEFT JOIN "IMDB"."company_name" ON "t3"."company_id" = "company_name"."id"
LEFT JOIN "IMDB"."company_type" ON "t3"."company_type_id" = "company_type"."id") AS "t4" ON "t"."MOVIE_ID" = "t4"."MOVIE_ID"