SELECT COALESCE("ACTOR_NAME", "ACTOR_NAME") AS "ACTOR_NAME", "TOTAL_MOVIES", "MOVIES_LIST", CASE WHEN "$f4" IS NOT NULL THEN CAST("$f4" AS DECIMAL(19, 0)) ELSE 0 END AS "AVERAGE_RATING", "MOVIE_KEYWORDS"
FROM (SELECT "name", ANY_VALUE("name") AS "ACTOR_NAME", COUNT(DISTINCT "movie_id") AS "TOTAL_MOVIES", LISTAGG(DISTINCT "title", "FD_COL_3") AS "MOVIES_LIST", AVG("FD_COL_4") AS "$f4", ARRAY_AGG(DISTINCT "keyword") AS "MOVIE_KEYWORDS"
FROM "s1"
GROUP BY "name"
HAVING COUNT(DISTINCT "movie_id") > 5
ORDER BY 3 DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY) AS "t9"