SELECT COALESCE("t4"."name", "t4"."name") AS "name", "t4"."movie_id", "t4"."title", ', ' AS "FD_COL_3", CAST("t4"."info" AS DECIMAL(19, 0)) AS "FD_COL_4", "keyword"."keyword"
FROM (SELECT "aka_name"."id", "aka_name"."person_id", "aka_name"."name", "aka_name"."imdb_index", "aka_name"."name_pcode_cf", "aka_name"."name_pcode_nf", "aka_name"."surname_pcode", "aka_name"."md5sum", "cast_info"."id" AS "id0", "cast_info"."person_id" AS "person_id0", "cast_info"."movie_id", "cast_info"."person_role_id", "cast_info"."note", "cast_info"."nr_order", "cast_info"."role_id", "title"."id" AS "id1", "title"."title", "title"."imdb_index" AS "imdb_index0", "title"."kind_id", "title"."production_year", "title"."imdb_id", "title"."phonetic_code", "title"."episode_of_id", "title"."season_nr", "title"."episode_nr", "title"."series_years", "title"."md5sum" AS "md5sum0", "t2"."id" AS "id2", "t2"."movie_id" AS "movie_id0", "t2"."info_type_id", "t2"."info", "t2"."note" AS "note0"
FROM "IMDB"."cast_info"
INNER JOIN "IMDB"."aka_name" ON "cast_info"."person_id" = "aka_name"."person_id"
INNER JOIN ("IMDB"."title" LEFT JOIN (SELECT "movie_info"."id", "movie_info"."movie_id", "movie_info"."info_type_id", "movie_info"."info", "movie_info"."note", "t0"."$f0"
FROM (SELECT SINGLE_VALUE("id") AS "$f0"
FROM "IMDB"."info_type"
WHERE "info" = 'rating') AS "t0",
"IMDB"."movie_info"
WHERE "movie_info"."info_type_id" = "t0"."$f0") AS "t2" ON "title"."id" = "t2"."movie_id") ON "cast_info"."movie_id" = "title"."id"
WHERE "title"."production_year" >= 2000) AS "t4"
LEFT JOIN "IMDB"."movie_keyword" ON "t4"."id1" = "movie_keyword"."movie_id"
LEFT JOIN "IMDB"."keyword" ON "movie_keyword"."keyword_id" = "keyword"."id"