SELECT COALESCE("t8"."MOVIE_ID", "t8"."MOVIE_ID") AS "MOVIE_ID", "t8"."TITLE", "t8"."PRODUCTION_YEAR", "t8"."CAST_COUNT", "t8"."KEYWORD_COUNT", "t8"."KEYWORDS", "t8"."ACTOR_NAMES", "t8"."CAST_SIZE_CATEGORY"
FROM (SELECT "t6"."MOVIE_ID", "t6"."TITLE", "t6"."PRODUCTION_YEAR", "t6"."CAST_COUNT", "t2"."KEYWORD_COUNT", "t2"."KEYWORDS", "t6"."ACTOR_NAMES", CASE WHEN "t6"."CAST_COUNT" < 5 THEN 'Low   ' WHEN "t6"."CAST_COUNT" >= 5 AND "t6"."CAST_COUNT" <= 10 THEN 'Medium' ELSE 'High  ' END AS "CAST_SIZE_CATEGORY"
FROM (SELECT "movie_keyword"."movie_id" AS "MOVIE_ID", COUNT(*) AS "KEYWORD_COUNT", LISTAGG("keyword"."keyword", ', ') AS "KEYWORDS"
FROM "IMDB"."keyword"
INNER JOIN "IMDB"."movie_keyword" ON "keyword"."id" = "movie_keyword"."keyword_id"
GROUP BY "movie_keyword"."movie_id") AS "t2"
RIGHT JOIN (SELECT ANY_VALUE("t3"."id") AS "MOVIE_ID", "t3"."title" AS "TITLE", "t3"."production_year" AS "PRODUCTION_YEAR", COUNT("t3"."id0") AS "CAST_COUNT", LISTAGG(DISTINCT "aka_name"."name", ', ') AS "ACTOR_NAMES"
FROM (SELECT "s1"."id", "s1"."title", "s1"."imdb_index", "s1"."kind_id", "s1"."production_year", "s1"."imdb_id", "s1"."phonetic_code", "s1"."episode_of_id", "s1"."season_nr", "s1"."episode_nr", "s1"."series_years", "s1"."md5sum", "cast_info"."id" AS "id0", "cast_info"."person_id", "cast_info"."movie_id", "cast_info"."person_role_id", "cast_info"."note", "cast_info"."nr_order", "cast_info"."role_id"
FROM "IMDB"."cast_info"
RIGHT JOIN "s1" ON "cast_info"."movie_id" = "s1"."id") AS "t3"
LEFT JOIN "IMDB"."aka_name" ON "t3"."person_id" = "aka_name"."person_id"
GROUP BY "t3"."id", "t3"."title", "t3"."production_year") AS "t6" ON "t2"."MOVIE_ID" = "t6"."MOVIE_ID"
ORDER BY "t6"."PRODUCTION_YEAR" DESC NULLS FIRST, "t6"."CAST_COUNT" DESC NULLS FIRST) AS "t8"