SELECT COALESCE("MOVIE_ID", "MOVIE_ID") AS "MOVIE_ID", "TITLE", "PRODUCTION_YEAR", LISTAGG(DISTINCT "FD_COL_3", "FD_COL_4") AS "ACTORS", LISTAGG(DISTINCT "FD_COL_5", "FD_COL_4") AS "PRODUCTION_COMPANIES", LISTAGG(DISTINCT "KEYWORD", "FD_COL_4") AS "KEYWORDS"
FROM "s1"
GROUP BY "MOVIE_ID", "TITLE", "PRODUCTION_YEAR"
ORDER BY "PRODUCTION_YEAR" DESC NULLS FIRST, "TITLE"