SELECT COALESCE("MOVIE_TITLE", "MOVIE_TITLE") AS "MOVIE_TITLE", "PRODUCTION_YEAR", LISTAGG(DISTINCT "ACTOR_NAME", "FD_COL_3") AS "ACTORS", LISTAGG(DISTINCT "ROLE", "FD_COL_3") AS "ROLES", LISTAGG(DISTINCT "PRODUCTION_COMPANY", "FD_COL_3") AS "PRODUCTION_COMPANIES", LISTAGG(DISTINCT "MOVIE_KEYWORD", "FD_COL_3") AS "KEYWORDS"
FROM "s1"
GROUP BY "MOVIE_TITLE", "PRODUCTION_YEAR"
ORDER BY "PRODUCTION_YEAR" DESC NULLS FIRST, "MOVIE_TITLE"