SELECT COALESCE("t6"."KEYWORD", "t6"."KEYWORD") AS "KEYWORD", "t11"."MOVIE_ID", "t11"."TITLE", "t11"."PRODUCTION_YEAR", "t11"."KEYWORD" AS "KEYWORD0", "t11"."NUM_CAST_MEMBERS", "t11"."CAST_NAMES"
FROM (SELECT "KEYWORD"
FROM (SELECT "t2"."KEYWORD", COUNT(*) AS "MOVIE_COUNT"
FROM (SELECT "t0"."id", "t0"."title" AS "TITLE", "t0"."production_year" AS "PRODUCTION_YEAR", "t0"."keyword", ANY_VALUE("t0"."id") AS "MOVIE_ID", ANY_VALUE("t0"."keyword") AS "KEYWORD", COUNT(DISTINCT "t0"."person_id") AS "$f6", LISTAGG(DISTINCT "aka_name"."name", ', ') AS "$f7"
FROM (SELECT "t"."id", "t"."movie_id", "t"."title", "t"."imdb_index", "t"."kind_id", "t"."production_year", "t"."phonetic_code", "t"."episode_of_id", "t"."season_nr", "t"."episode_nr", "t"."note", "t"."md5sum", "t"."id0", "t"."movie_id0", "t"."keyword_id", "keyword"."id" AS "id1", "keyword"."keyword", "keyword"."phonetic_code" AS "phonetic_code0", "cast_info"."id" AS "id2", "cast_info"."person_id", "cast_info"."movie_id" AS "movie_id1", "cast_info"."person_role_id", "cast_info"."note" AS "note0", "cast_info"."nr_order", "cast_info"."role_id"
FROM "IMDB"."cast_info"
RIGHT JOIN ((SELECT "aka_title"."id", "aka_title"."movie_id", "aka_title"."title", "aka_title"."imdb_index", "aka_title"."kind_id", "aka_title"."production_year", "aka_title"."phonetic_code", "aka_title"."episode_of_id", "aka_title"."season_nr", "aka_title"."episode_nr", "aka_title"."note", "aka_title"."md5sum", "movie_keyword"."id" AS "id0", "movie_keyword"."movie_id" AS "movie_id0", "movie_keyword"."keyword_id"
FROM "IMDB"."movie_keyword"
RIGHT JOIN "IMDB"."aka_title" ON "movie_keyword"."movie_id" = "aka_title"."id") AS "t" LEFT JOIN "IMDB"."keyword" ON "t"."keyword_id" = "keyword"."id") ON "cast_info"."movie_id" = "t"."id") AS "t0"
LEFT JOIN "IMDB"."aka_name" ON "t0"."person_id" = "aka_name"."person_id"
GROUP BY "t0"."id", "t0"."title", "t0"."production_year", "t0"."keyword") AS "t2"
GROUP BY "t2"."KEYWORD"
HAVING COUNT(*) > 1
ORDER BY 2 DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY) AS "t5") AS "t6"
INNER JOIN (SELECT ANY_VALUE("t8"."id") AS "MOVIE_ID", "t8"."title" AS "TITLE", "t8"."production_year" AS "PRODUCTION_YEAR", ANY_VALUE("t8"."keyword") AS "KEYWORD", COUNT(DISTINCT "t8"."person_id") AS "NUM_CAST_MEMBERS", CASE WHEN LISTAGG(DISTINCT "aka_name0"."name", ', ') IS NOT NULL THEN CAST(LISTAGG(DISTINCT "aka_name0"."name", ', ') AS VARCHAR CHARACTER SET "ISO-8859-1") ELSE 'No Cast' END AS "CAST_NAMES"
FROM (SELECT "t7"."id", "t7"."movie_id", "t7"."title", "t7"."imdb_index", "t7"."kind_id", "t7"."production_year", "t7"."phonetic_code", "t7"."episode_of_id", "t7"."season_nr", "t7"."episode_nr", "t7"."note", "t7"."md5sum", "t7"."id0", "t7"."movie_id0", "t7"."keyword_id", "keyword0"."id" AS "id1", "keyword0"."keyword", "keyword0"."phonetic_code" AS "phonetic_code0", "cast_info0"."id" AS "id2", "cast_info0"."person_id", "cast_info0"."movie_id" AS "movie_id1", "cast_info0"."person_role_id", "cast_info0"."note" AS "note0", "cast_info0"."nr_order", "cast_info0"."role_id"
FROM "IMDB"."cast_info" AS "cast_info0"
RIGHT JOIN ((SELECT "aka_title0"."id", "aka_title0"."movie_id", "aka_title0"."title", "aka_title0"."imdb_index", "aka_title0"."kind_id", "aka_title0"."production_year", "aka_title0"."phonetic_code", "aka_title0"."episode_of_id", "aka_title0"."season_nr", "aka_title0"."episode_nr", "aka_title0"."note", "aka_title0"."md5sum", "movie_keyword0"."id" AS "id0", "movie_keyword0"."movie_id" AS "movie_id0", "movie_keyword0"."keyword_id"
FROM "IMDB"."movie_keyword" AS "movie_keyword0"
RIGHT JOIN "IMDB"."aka_title" AS "aka_title0" ON "movie_keyword0"."movie_id" = "aka_title0"."id") AS "t7" LEFT JOIN "IMDB"."keyword" AS "keyword0" ON "t7"."keyword_id" = "keyword0"."id") ON "cast_info0"."movie_id" = "t7"."id") AS "t8"
LEFT JOIN "IMDB"."aka_name" AS "aka_name0" ON "t8"."person_id" = "aka_name0"."person_id"
GROUP BY "t8"."id", "t8"."title", "t8"."production_year", "t8"."keyword") AS "t11" ON "t6"."KEYWORD" = "t11"."KEYWORD"