SELECT COALESCE("t4"."MOVIE_TITLE", "t4"."MOVIE_TITLE") AS "MOVIE_TITLE", "t4"."PRODUCTION_YEAR", "t4"."MOVIE_ID", "t4"."CAST_COUNT", "t4"."CAST_NAMES", "t4"."KEYWORDS", "t12"."MOVIE_ID" AS "MOVIE_ID0", "t12"."COMPANY_COUNT", "t12"."COMPANY_NAMES"
FROM (SELECT ANY_VALUE("t1"."title") AS "MOVIE_TITLE", "t1"."production_year" AS "PRODUCTION_YEAR", ANY_VALUE("t1"."id") AS "MOVIE_ID", COUNT(DISTINCT "t1"."person_id") AS "CAST_COUNT", LISTAGG(DISTINCT "aka_name"."name", ', ') AS "CAST_NAMES", LISTAGG(DISTINCT "t1"."keyword", ', ') AS "KEYWORDS"
FROM (SELECT "t0"."id", "t0"."movie_id", "t0"."title", "t0"."imdb_index", "t0"."kind_id", "t0"."production_year", "t0"."phonetic_code", "t0"."episode_of_id", "t0"."season_nr", "t0"."episode_nr", "t0"."note", "t0"."md5sum", "t0"."id0", "t0"."movie_id0", "t0"."keyword_id", "keyword"."id" AS "id1", "keyword"."keyword", "keyword"."phonetic_code" AS "phonetic_code0", "cast_info"."id" AS "id2", "cast_info"."person_id", "cast_info"."movie_id" AS "movie_id1", "cast_info"."person_role_id", "cast_info"."note" AS "note0", "cast_info"."nr_order", "cast_info"."role_id"
FROM "IMDB"."cast_info"
RIGHT JOIN ((SELECT "t"."id", "t"."movie_id", "t"."title", "t"."imdb_index", "t"."kind_id", "t"."production_year", "t"."phonetic_code", "t"."episode_of_id", "t"."season_nr", "t"."episode_nr", "t"."note", "t"."md5sum", "movie_keyword"."id" AS "id0", "movie_keyword"."movie_id" AS "movie_id0", "movie_keyword"."keyword_id"
FROM "IMDB"."movie_keyword"
RIGHT JOIN (SELECT *
FROM "IMDB"."aka_title"
WHERE "production_year" >= 2000 AND "production_year" <= 2020) AS "t" ON "movie_keyword"."movie_id" = "t"."id") AS "t0" LEFT JOIN "IMDB"."keyword" ON "t0"."keyword_id" = "keyword"."id") ON "cast_info"."movie_id" = "t0"."id") AS "t1"
LEFT JOIN "IMDB"."aka_name" ON "t1"."person_id" = "aka_name"."person_id"
GROUP BY "t1"."title", "t1"."production_year", "t1"."id") AS "t4"
LEFT JOIN (SELECT "t10"."MOVIE_ID", COUNT(DISTINCT "movie_companies"."company_id") AS "COMPANY_COUNT", LISTAGG(DISTINCT "company_name"."name", ', ') AS "COMPANY_NAMES"
FROM "IMDB"."company_name"
INNER JOIN "IMDB"."movie_companies" ON "company_name"."id" = "movie_companies"."company_id"
INNER JOIN (SELECT ANY_VALUE("t7"."title") AS "MOVIE_TITLE", "t7"."production_year" AS "PRODUCTION_YEAR", ANY_VALUE("t7"."id") AS "MOVIE_ID", COUNT(DISTINCT "t7"."person_id") AS "CAST_COUNT", LISTAGG(DISTINCT "aka_name0"."name", ', ') AS "CAST_NAMES", LISTAGG(DISTINCT "t7"."keyword", ', ') AS "KEYWORDS"
FROM (SELECT "t6"."id", "t6"."movie_id", "t6"."title", "t6"."imdb_index", "t6"."kind_id", "t6"."production_year", "t6"."phonetic_code", "t6"."episode_of_id", "t6"."season_nr", "t6"."episode_nr", "t6"."note", "t6"."md5sum", "t6"."id0", "t6"."movie_id0", "t6"."keyword_id", "keyword0"."id" AS "id1", "keyword0"."keyword", "keyword0"."phonetic_code" AS "phonetic_code0", "cast_info0"."id" AS "id2", "cast_info0"."person_id", "cast_info0"."movie_id" AS "movie_id1", "cast_info0"."person_role_id", "cast_info0"."note" AS "note0", "cast_info0"."nr_order", "cast_info0"."role_id"
FROM "IMDB"."cast_info" AS "cast_info0"
RIGHT JOIN ((SELECT "t5"."id", "t5"."movie_id", "t5"."title", "t5"."imdb_index", "t5"."kind_id", "t5"."production_year", "t5"."phonetic_code", "t5"."episode_of_id", "t5"."season_nr", "t5"."episode_nr", "t5"."note", "t5"."md5sum", "movie_keyword0"."id" AS "id0", "movie_keyword0"."movie_id" AS "movie_id0", "movie_keyword0"."keyword_id"
FROM "IMDB"."movie_keyword" AS "movie_keyword0"
RIGHT JOIN (SELECT *
FROM "IMDB"."aka_title"
WHERE "production_year" >= 2000 AND "production_year" <= 2020) AS "t5" ON "movie_keyword0"."movie_id" = "t5"."id") AS "t6" LEFT JOIN "IMDB"."keyword" AS "keyword0" ON "t6"."keyword_id" = "keyword0"."id") ON "cast_info0"."movie_id" = "t6"."id") AS "t7"
LEFT JOIN "IMDB"."aka_name" AS "aka_name0" ON "t7"."person_id" = "aka_name0"."person_id"
GROUP BY "t7"."title", "t7"."production_year", "t7"."id") AS "t10" ON "movie_companies"."movie_id" = "t10"."MOVIE_ID"
GROUP BY "t10"."MOVIE_ID") AS "t12" ON "t4"."MOVIE_ID" = "t12"."MOVIE_ID"