SELECT COALESCE("t0"."MOVIE_ID", "t0"."MOVIE_ID") AS "MOVIE_ID", "t0"."COMPANY_NAMES", "t0"."COMPANY_TYPES", "t6"."MOVIE_ID" AS "MOVIE_ID0", "t6"."TITLE", "t6"."PRODUCTION_YEAR", "t6"."AKA_NAMES", "t6"."KEYWORDS", "t6"."CAST_COUNT"
FROM (SELECT "movie_companies"."movie_id" AS "MOVIE_ID", LISTAGG(DISTINCT "company_name"."name", ', ') AS "COMPANY_NAMES", LISTAGG(DISTINCT "company_type"."kind", ', ') AS "COMPANY_TYPES"
FROM "IMDB"."company_type"
INNER JOIN ("IMDB"."company_name" INNER JOIN "IMDB"."movie_companies" ON "company_name"."id" = "movie_companies"."company_id") ON "company_type"."id" = "movie_companies"."company_type_id"
GROUP BY "movie_companies"."movie_id") AS "t0"
RIGHT JOIN (SELECT ANY_VALUE("t2"."id") AS "MOVIE_ID", "t2"."title" AS "TITLE", "t2"."production_year" AS "PRODUCTION_YEAR", LISTAGG(DISTINCT "t2"."name", ', ') AS "AKA_NAMES", LISTAGG(DISTINCT "keyword"."keyword", ', ') AS "KEYWORDS", COUNT("complete_cast"."id") AS "CAST_COUNT"
FROM (SELECT "t1"."id", "t1"."movie_id", "t1"."title", "t1"."imdb_index", "t1"."kind_id", "t1"."production_year", "t1"."phonetic_code", "t1"."episode_of_id", "t1"."season_nr", "t1"."episode_nr", "t1"."note", "t1"."md5sum", "t1"."id0", "t1"."person_id", "t1"."name", "t1"."imdb_index0", "t1"."name_pcode_cf", "t1"."name_pcode_nf", "t1"."surname_pcode", "t1"."md5sum0", "movie_keyword"."id" AS "id1", "movie_keyword"."movie_id" AS "movie_id0", "movie_keyword"."keyword_id"
FROM "IMDB"."movie_keyword"
RIGHT JOIN (SELECT "aka_title"."id", "aka_title"."movie_id", "aka_title"."title", "aka_title"."imdb_index", "aka_title"."kind_id", "aka_title"."production_year", "aka_title"."phonetic_code", "aka_title"."episode_of_id", "aka_title"."season_nr", "aka_title"."episode_nr", "aka_title"."note", "aka_title"."md5sum", "aka_name"."id" AS "id0", "aka_name"."person_id", "aka_name"."name", "aka_name"."imdb_index" AS "imdb_index0", "aka_name"."name_pcode_cf", "aka_name"."name_pcode_nf", "aka_name"."surname_pcode", "aka_name"."md5sum" AS "md5sum0"
FROM "IMDB"."aka_name"
RIGHT JOIN "IMDB"."aka_title" ON "aka_name"."id" = "aka_title"."id") AS "t1" ON "movie_keyword"."movie_id" = "t1"."id") AS "t2"
LEFT JOIN "IMDB"."keyword" ON "t2"."keyword_id" = "keyword"."id"
LEFT JOIN "IMDB"."complete_cast" ON "t2"."id" = "complete_cast"."movie_id"
WHERE "t2"."production_year" >= 2000
GROUP BY "t2"."id", "t2"."title", "t2"."production_year") AS "t6" ON "t0"."MOVIE_ID" = "t6"."MOVIE_ID"