SELECT COALESCE("MOVIE_ID", "MOVIE_ID") AS "MOVIE_ID", "MOVIE_TITLE", "PRODUCTION_YEAR", "LEADING_ROLE", "PRODUCTION_COMPANIES", "NUM_CAST_MEMBERS", "MOVIE_KEYWORDS", "ALL_AKA_NAMES"
FROM (SELECT "MOVIE_ID0" AS "MOVIE_ID", "MOVIE_TITLE0" AS "MOVIE_TITLE", "PRODUCTION_YEAR0" AS "PRODUCTION_YEAR", "LEADING_ROLE", "PRODUCTION_COMPANIES", "NUM_CAST_MEMBERS", "MOVIE_KEYWORDS", "ALL_AKA_NAMES"
FROM "s1"
ORDER BY "PRODUCTION_YEAR0" DESC NULLS FIRST, "NUM_CAST_MEMBERS" DESC NULLS FIRST) AS "t15"