SELECT COALESCE("t6"."MOVIE_ID", "t6"."MOVIE_ID") AS "MOVIE_ID", "t6"."MOVIE_TITLE", "t6"."PRODUCTION_YEAR", "t6"."CAST_COUNT", "t6"."CAST_NAMES", "t6"."KEYWORDS", LISTAGG(DISTINCT "company_name"."name", ', ') AS "COMPANIES"
FROM "IMDB"."company_name"
RIGHT JOIN (SELECT "t5"."MOVIE_ID", "t5"."MOVIE_TITLE", "t5"."PRODUCTION_YEAR", "t5"."CAST_COUNT", "t5"."CAST_NAMES", "t5"."KEYWORDS", "movie_companies"."id", "movie_companies"."movie_id", "movie_companies"."company_id", "movie_companies"."company_type_id", "movie_companies"."note"
FROM "IMDB"."movie_companies"
RIGHT JOIN (SELECT "t3"."MOVIE_ID", "t3"."MOVIE_TITLE", "t3"."PRODUCTION_YEAR", "t3"."CAST_COUNT", "t3"."CAST_NAMES", LISTAGG(DISTINCT "keyword"."keyword", ', ') AS "KEYWORDS"
FROM "IMDB"."keyword"
RIGHT JOIN (SELECT "t2"."MOVIE_ID", "t2"."MOVIE_TITLE", "t2"."PRODUCTION_YEAR", "t2"."CAST_COUNT", "t2"."CAST_NAMES", "movie_keyword"."id", "movie_keyword"."movie_id", "movie_keyword"."keyword_id"
FROM "IMDB"."movie_keyword"
RIGHT JOIN (SELECT ANY_VALUE("t"."id") AS "MOVIE_ID", ANY_VALUE("t"."title") AS "MOVIE_TITLE", "t"."production_year" AS "PRODUCTION_YEAR", COUNT(DISTINCT "cast_info"."person_id") AS "CAST_COUNT", LISTAGG(DISTINCT "aka_name"."name", ', ') AS "CAST_NAMES"
FROM (SELECT *
FROM "IMDB"."aka_title"
WHERE "production_year" >= 2000) AS "t"
INNER JOIN ("IMDB"."aka_name" INNER JOIN "IMDB"."cast_info" ON "aka_name"."person_id" = "cast_info"."person_id") ON "t"."id" = "cast_info"."movie_id"
GROUP BY "t"."id", "t"."title", "t"."production_year") AS "t2" ON "movie_keyword"."movie_id" = "t2"."MOVIE_ID") AS "t3" ON "keyword"."id" = "t3"."keyword_id"
GROUP BY "t3"."MOVIE_ID", "t3"."MOVIE_TITLE", "t3"."PRODUCTION_YEAR", "t3"."CAST_COUNT", "t3"."CAST_NAMES") AS "t5" ON "movie_companies"."movie_id" = "t5"."MOVIE_ID") AS "t6" ON "company_name"."id" = "t6"."company_id"
GROUP BY "t6"."MOVIE_ID", "t6"."MOVIE_TITLE", "t6"."PRODUCTION_YEAR", "t6"."CAST_COUNT", "t6"."CAST_NAMES", "t6"."KEYWORDS"