SELECT COALESCE("t0"."MOVIE_ID", "t0"."MOVIE_ID") AS "MOVIE_ID", "t0"."COMPANY_NAMES", "t0"."COMPANY_TYPES", "t5"."MOVIE_ID" AS "MOVIE_ID0", "t5"."MOVIE_TITLE", "t5"."PRODUCTION_YEAR", "t5"."ACTOR_NAME", "t5"."ACTOR_IMDB_INDEX", "t5"."KEYWORDS"
FROM (SELECT "movie_companies"."movie_id" AS "MOVIE_ID", LISTAGG(DISTINCT "company_name"."name", ', ') AS "COMPANY_NAMES", LISTAGG(DISTINCT "company_type"."kind", ', ') AS "COMPANY_TYPES"
FROM "IMDB"."company_type"
INNER JOIN ("IMDB"."company_name" INNER JOIN "IMDB"."movie_companies" ON "company_name"."id" = "movie_companies"."company_id") ON "company_type"."id" = "movie_companies"."company_type_id"
GROUP BY "movie_companies"."movie_id") AS "t0"
INNER JOIN (SELECT ANY_VALUE("t2"."id") AS "MOVIE_ID", ANY_VALUE("t2"."title") AS "MOVIE_TITLE", "t2"."production_year" AS "PRODUCTION_YEAR", ANY_VALUE("t2"."name") AS "ACTOR_NAME", ANY_VALUE("t2"."imdb_index0") AS "ACTOR_IMDB_INDEX", LISTAGG(DISTINCT "keyword"."keyword", ', ') AS "KEYWORDS"
FROM (SELECT "t1"."id", "t1"."movie_id", "t1"."title", "t1"."imdb_index", "t1"."kind_id", "t1"."production_year", "t1"."phonetic_code", "t1"."episode_of_id", "t1"."season_nr", "t1"."episode_nr", "t1"."note", "t1"."md5sum", "cast_info"."id" AS "id0", "cast_info"."person_id", "cast_info"."movie_id" AS "movie_id0", "cast_info"."person_role_id", "cast_info"."note" AS "note0", "cast_info"."nr_order", "cast_info"."role_id", "aka_name"."id" AS "id1", "aka_name"."person_id" AS "person_id0", "aka_name"."name", "aka_name"."imdb_index" AS "imdb_index0", "aka_name"."name_pcode_cf", "aka_name"."name_pcode_nf", "aka_name"."surname_pcode", "aka_name"."md5sum" AS "md5sum0", "movie_keyword"."id" AS "id2", "movie_keyword"."movie_id" AS "movie_id1", "movie_keyword"."keyword_id"
FROM "IMDB"."cast_info"
INNER JOIN ("IMDB"."movie_keyword" RIGHT JOIN (SELECT *
FROM "IMDB"."aka_title"
WHERE "production_year" >= 2000) AS "t1" ON "movie_keyword"."movie_id" = "t1"."id") ON "cast_info"."movie_id" = "t1"."id"
INNER JOIN "IMDB"."aka_name" ON "cast_info"."person_id" = "aka_name"."person_id") AS "t2"
LEFT JOIN "IMDB"."keyword" ON "t2"."keyword_id" = "keyword"."id"
GROUP BY "t2"."id", "t2"."title", "t2"."production_year", "t2"."name", "t2"."imdb_index0") AS "t5" ON "t0"."MOVIE_ID" = "t5"."MOVIE_ID"