SELECT COALESCE("MOVIE_ID", "MOVIE_ID") AS "MOVIE_ID", "TITLE", "PRODUCTION_YEAR", "NUM_CAST_MEMBERS", "CAST_NAMES", "KEYWORDS"
FROM (SELECT "MOVIE_ID0" AS "MOVIE_ID", "TITLE", "PRODUCTION_YEAR", "NUM_CAST_MEMBERS", "CAST_NAMES", "KEYWORDS"
FROM "s1"
ORDER BY "NUM_CAST_MEMBERS" DESC NULLS FIRST, "PRODUCTION_YEAR" DESC NULLS FIRST) AS "t11"