SELECT COALESCE("MOVIE_ID", "MOVIE_ID") AS "MOVIE_ID", "TITLE", "PRODUCTION_YEAR", "TOTAL_CAST", "CAST_NAMES", "KEYWORD_COUNT", "KEYWORDS"
FROM (SELECT "MOVIE_ID0" AS "MOVIE_ID", "TITLE", "PRODUCTION_YEAR", "TOTAL_CAST", "CAST_NAMES", CASE WHEN "KEYWORD_COUNT" IS NOT NULL THEN CAST("KEYWORD_COUNT" AS BIGINT) ELSE 0 END AS "KEYWORD_COUNT", CASE WHEN "KEYWORDS" IS NOT NULL THEN CAST("KEYWORDS" AS VARCHAR CHARACTER SET "ISO-8859-1") ELSE '' END AS "KEYWORDS"
FROM "s1"
ORDER BY "PRODUCTION_YEAR" DESC NULLS FIRST, "TOTAL_CAST" DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY) AS "t7"