SELECT COALESCE("MOVIE_ID", "MOVIE_ID") AS "MOVIE_ID", "TITLE", "PRODUCTION_YEAR", CASE WHEN "ALIASES" IS NOT NULL THEN CAST("ALIASES" AS VARCHAR CHARACTER SET "ISO-8859-1") ELSE 'No aliases available' END AS "ALIASES", CASE WHEN "KEYWORDS" IS NOT NULL THEN CAST("KEYWORDS" AS VARCHAR CHARACTER SET "ISO-8859-1") ELSE 'No keywords available' END AS "KEYWORDS", "COMPANY_COUNT", "CAST_COUNT", CASE WHEN "CAST_COUNT" > 10 THEN 'Large Cast ' WHEN "CAST_COUNT" >= 5 AND "CAST_COUNT" <= 10 THEN 'Medium Cast' ELSE 'Small Cast ' END AS "CAST_SIZE"
FROM (SELECT "id", "TITLE", "PRODUCTION_YEAR", ANY_VALUE("id") AS "MOVIE_ID", LISTAGG(DISTINCT "name", "FD_COL_4") AS "ALIASES", LISTAGG(DISTINCT "keyword", "FD_COL_4") AS "KEYWORDS", COUNT(DISTINCT "company_id") AS "COMPANY_COUNT", COUNT(DISTINCT "person_id0") AS "CAST_COUNT"
FROM "s1"
GROUP BY "id", "TITLE", "PRODUCTION_YEAR"
HAVING COUNT(DISTINCT "company_id") > 0
ORDER BY "PRODUCTION_YEAR" DESC NULLS FIRST, 8 DESC NULLS FIRST) AS "t7"