SELECT COALESCE("t0"."MOVIE_ID", "t0"."MOVIE_ID") AS "MOVIE_ID", "t0"."CAST_NAMES", "t0"."ROLES", "t6"."MOVIE_ID" AS "MOVIE_ID0", "t6"."MOVIE_TITLE", "t6"."PRODUCTION_YEAR", "t6"."COMPANIES", "t6"."KEYWORDS"
FROM (SELECT "cast_info"."movie_id" AS "MOVIE_ID", LISTAGG(DISTINCT "aka_name"."name", ', ') AS "CAST_NAMES", LISTAGG(DISTINCT "role_type"."role", ', ') AS "ROLES"
FROM "IMDB"."cast_info"
LEFT JOIN "IMDB"."aka_name" ON "cast_info"."person_id" = "aka_name"."person_id"
LEFT JOIN "IMDB"."role_type" ON "cast_info"."role_id" = "role_type"."id"
GROUP BY "cast_info"."movie_id") AS "t0"
RIGHT JOIN (SELECT ANY_VALUE("t2"."id") AS "MOVIE_ID", ANY_VALUE("t2"."title") AS "MOVIE_TITLE", "t2"."production_year" AS "PRODUCTION_YEAR", LISTAGG(DISTINCT "t2"."name", ', ') AS "COMPANIES", LISTAGG(DISTINCT "keyword"."keyword", ', ') AS "KEYWORDS"
FROM (SELECT "t1"."id", "t1"."movie_id", "t1"."title", "t1"."imdb_index", "t1"."kind_id", "t1"."production_year", "t1"."phonetic_code", "t1"."episode_of_id", "t1"."season_nr", "t1"."episode_nr", "t1"."note", "t1"."md5sum", "t1"."id0", "t1"."movie_id0", "t1"."company_id", "t1"."company_type_id", "t1"."note0", "company_name"."id" AS "id1", "company_name"."name", "company_name"."country_code", "company_name"."imdb_id", "company_name"."name_pcode_nf", "company_name"."name_pcode_sf", "company_name"."md5sum" AS "md5sum0", "movie_keyword"."id" AS "id2", "movie_keyword"."movie_id" AS "movie_id1", "movie_keyword"."keyword_id"
FROM "IMDB"."movie_keyword"
RIGHT JOIN ((SELECT "aka_title"."id", "aka_title"."movie_id", "aka_title"."title", "aka_title"."imdb_index", "aka_title"."kind_id", "aka_title"."production_year", "aka_title"."phonetic_code", "aka_title"."episode_of_id", "aka_title"."season_nr", "aka_title"."episode_nr", "aka_title"."note", "aka_title"."md5sum", "movie_companies"."id" AS "id0", "movie_companies"."movie_id" AS "movie_id0", "movie_companies"."company_id", "movie_companies"."company_type_id", "movie_companies"."note" AS "note0"
FROM "IMDB"."movie_companies"
RIGHT JOIN "IMDB"."aka_title" ON "movie_companies"."movie_id" = "aka_title"."id") AS "t1" LEFT JOIN "IMDB"."company_name" ON "t1"."company_id" = "company_name"."id") ON "movie_keyword"."movie_id" = "t1"."id") AS "t2"
LEFT JOIN "IMDB"."keyword" ON "t2"."keyword_id" = "keyword"."id"
WHERE "t2"."production_year" >= 2000
GROUP BY "t2"."id", "t2"."title", "t2"."production_year") AS "t6" ON "t0"."MOVIE_ID" = "t6"."MOVIE_ID"