SELECT COALESCE("t1"."MOVIE_ID", "t1"."MOVIE_ID") AS "MOVIE_ID", "t1"."ACTOR_NAME", "t1"."ROLE", "t1"."ROLE_COUNT", "t6"."TITLE_ID", "t6"."TITLE", "t6"."PRODUCTION_YEAR", "t6"."KEYWORDS", "t6"."COMPANIES"
FROM (SELECT "cast_info"."movie_id" AS "MOVIE_ID", ANY_VALUE("aka_name"."name") AS "ACTOR_NAME", ANY_VALUE("role_type"."role") AS "ROLE", COUNT(*) AS "ROLE_COUNT"
FROM "IMDB"."role_type"
INNER JOIN ("IMDB"."aka_name" INNER JOIN "IMDB"."cast_info" ON "aka_name"."person_id" = "cast_info"."person_id") ON "role_type"."id" = "cast_info"."role_id"
GROUP BY "role_type"."role", "aka_name"."name", "cast_info"."movie_id") AS "t1"
RIGHT JOIN (SELECT ANY_VALUE("t2"."id") AS "TITLE_ID", "t2"."title" AS "TITLE", "t2"."production_year" AS "PRODUCTION_YEAR", LISTAGG(DISTINCT "keyword"."keyword", ', ') AS "KEYWORDS", LISTAGG(DISTINCT "company_name"."name", ', ') AS "COMPANIES"
FROM (SELECT "aka_title"."id", "aka_title"."movie_id", "aka_title"."title", "aka_title"."imdb_index", "aka_title"."kind_id", "aka_title"."production_year", "aka_title"."phonetic_code", "aka_title"."episode_of_id", "aka_title"."season_nr", "aka_title"."episode_nr", "aka_title"."note", "aka_title"."md5sum", "movie_keyword"."id" AS "id0", "movie_keyword"."movie_id" AS "movie_id0", "movie_keyword"."keyword_id"
FROM "IMDB"."movie_keyword"
RIGHT JOIN "IMDB"."aka_title" ON "movie_keyword"."movie_id" = "aka_title"."id") AS "t2"
LEFT JOIN "IMDB"."keyword" ON "t2"."keyword_id" = "keyword"."id"
LEFT JOIN "IMDB"."movie_companies" ON "t2"."id" = "movie_companies"."movie_id"
LEFT JOIN "IMDB"."company_name" ON "movie_companies"."company_id" = "company_name"."id"
WHERE "t2"."production_year" >= 2000 AND "t2"."production_year" <= 2023
GROUP BY "t2"."id", "t2"."title", "t2"."production_year") AS "t6" ON "t1"."MOVIE_ID" = "t6"."TITLE_ID"