SELECT COALESCE("MOVIE_TITLE", "MOVIE_TITLE") AS "MOVIE_TITLE", "PRODUCTION_YEAR", "MOVIE_KIND", "ACTOR_NAME", "ROLE_TYPE", "KEYWORDS", "COMPANIES"
FROM (SELECT "MOVIE_TITLE", "PRODUCTION_YEAR", "MOVIE_KIND", "ACTOR_NAME", "ROLE_TYPE", "KEYWORDS", "COMPANIES"
FROM "s1"
ORDER BY "PRODUCTION_YEAR" DESC NULLS FIRST, "MOVIE_TITLE") AS "t10"