SELECT COALESCE("t0"."MOVIE_ID", "t0"."MOVIE_ID") AS "MOVIE_ID", "t0"."COMPANIES", "t7"."MOVIE_ID" AS "MOVIE_ID0", "t7"."MOVIE_TITLE", "t7"."PRODUCTION_YEAR", "t7"."MOVIE_KIND", "t7"."MOVIE_ID0" AS "MOVIE_ID00", "t7"."ACTOR_NAME", "t7"."ROLE_TYPE", "t7"."MOVIE_ID1", "t7"."KEYWORDS"
FROM (SELECT "movie_companies"."movie_id" AS "MOVIE_ID", LISTAGG("company_name"."name", ', ') AS "COMPANIES"
FROM "IMDB"."company_name"
INNER JOIN "IMDB"."movie_companies" ON "company_name"."id" = "movie_companies"."company_id"
GROUP BY "movie_companies"."movie_id") AS "t0"
RIGHT JOIN (SELECT "t6"."MOVIE_ID", "t6"."MOVIE_TITLE", "t6"."PRODUCTION_YEAR", "t6"."MOVIE_KIND", "t6"."MOVIE_ID0", "t6"."ACTOR_NAME", "t6"."ROLE_TYPE", "t2"."MOVIE_ID" AS "MOVIE_ID1", "t2"."KEYWORDS"
FROM (SELECT "movie_keyword"."movie_id" AS "MOVIE_ID", LISTAGG("keyword"."keyword", ', ') AS "KEYWORDS"
FROM "IMDB"."keyword"
INNER JOIN "IMDB"."movie_keyword" ON "keyword"."id" = "movie_keyword"."keyword_id"
GROUP BY "movie_keyword"."movie_id") AS "t2"
RIGHT JOIN (SELECT "t5"."MOVIE_ID", "t5"."MOVIE_TITLE", "t5"."PRODUCTION_YEAR", "t5"."MOVIE_KIND", "t3"."MOVIE_ID" AS "MOVIE_ID0", "t3"."ACTOR_NAME", "t3"."ROLE_TYPE"
FROM (SELECT "cast_info"."movie_id" AS "MOVIE_ID", "aka_name"."name" AS "ACTOR_NAME", "role_type"."role" AS "ROLE_TYPE"
FROM "IMDB"."role_type"
INNER JOIN ("IMDB"."aka_name" INNER JOIN "IMDB"."cast_info" ON "aka_name"."person_id" = "cast_info"."person_id") ON "role_type"."id" = "cast_info"."role_id") AS "t3"
RIGHT JOIN (SELECT "t4"."id" AS "MOVIE_ID", "t4"."title" AS "MOVIE_TITLE", "t4"."production_year" AS "PRODUCTION_YEAR", "kind_type"."kind" AS "MOVIE_KIND"
FROM (SELECT *
FROM "IMDB"."title"
WHERE "production_year" >= 2020) AS "t4"
INNER JOIN "IMDB"."kind_type" ON "t4"."kind_id" = "kind_type"."id") AS "t5" ON "t3"."MOVIE_ID" = "t5"."MOVIE_ID") AS "t6" ON "t2"."MOVIE_ID" = "t6"."MOVIE_ID") AS "t7" ON "t0"."MOVIE_ID" = "t7"."MOVIE_ID"