SELECT COALESCE("t3"."MOVIE_TITLE", "t3"."MOVIE_TITLE") AS "MOVIE_TITLE", "t3"."PRODUCTION_YEAR", "t3"."ACTOR_NAME", "t3"."ACTOR_ID", "t3"."KEYWORDS", "t3"."COMPANY_TYPES", "t8"."ACTOR_ID" AS "ACTOR_ID0", "t8"."MOVIE_COUNT"
FROM (SELECT ANY_VALUE("t0"."title") AS "MOVIE_TITLE", "t0"."production_year" AS "PRODUCTION_YEAR", ANY_VALUE("t0"."name") AS "ACTOR_NAME", ANY_VALUE("t0"."id1") AS "ACTOR_ID", LISTAGG(DISTINCT "keyword"."keyword", ', ') AS "KEYWORDS", LISTAGG(DISTINCT "company_type"."kind", ', ') AS "COMPANY_TYPES"
FROM (SELECT "t"."id", "t"."movie_id", "t"."title", "t"."imdb_index", "t"."kind_id", "t"."production_year", "t"."phonetic_code", "t"."episode_of_id", "t"."season_nr", "t"."episode_nr", "t"."note", "t"."md5sum", "cast_info"."id" AS "id0", "cast_info"."person_id", "cast_info"."movie_id" AS "movie_id0", "cast_info"."person_role_id", "cast_info"."note" AS "note0", "cast_info"."nr_order", "cast_info"."role_id", "aka_name"."id" AS "id1", "aka_name"."person_id" AS "person_id0", "aka_name"."name", "aka_name"."imdb_index" AS "imdb_index0", "aka_name"."name_pcode_cf", "aka_name"."name_pcode_nf", "aka_name"."surname_pcode", "aka_name"."md5sum" AS "md5sum0", "movie_keyword"."id" AS "id2", "movie_keyword"."movie_id" AS "movie_id1", "movie_keyword"."keyword_id"
FROM "IMDB"."cast_info"
INNER JOIN ("IMDB"."movie_keyword" RIGHT JOIN (SELECT *
FROM "IMDB"."aka_title"
WHERE "production_year" >= 2000) AS "t" ON "movie_keyword"."movie_id" = "t"."id") ON "cast_info"."movie_id" = "t"."id"
INNER JOIN "IMDB"."aka_name" ON "cast_info"."person_id" = "aka_name"."person_id") AS "t0"
LEFT JOIN "IMDB"."keyword" ON "t0"."keyword_id" = "keyword"."id"
LEFT JOIN "IMDB"."movie_companies" ON "t0"."id" = "movie_companies"."movie_id"
LEFT JOIN "IMDB"."company_type" ON "movie_companies"."company_type_id" = "company_type"."id"
GROUP BY "t0"."title", "t0"."production_year", "t0"."name", "t0"."id1") AS "t3"
INNER JOIN (SELECT "t7"."ACTOR_ID", COUNT(*) AS "MOVIE_COUNT"
FROM (SELECT "t5"."title", "t5"."production_year" AS "PRODUCTION_YEAR", "t5"."name", "t5"."id1", ANY_VALUE("t5"."title") AS "MOVIE_TITLE", ANY_VALUE("t5"."name") AS "ACTOR_NAME", ANY_VALUE("t5"."id1") AS "ACTOR_ID", LISTAGG(DISTINCT "keyword0"."keyword", ', ') AS "KEYWORDS", LISTAGG(DISTINCT "company_type0"."kind", ', ') AS "COMPANY_TYPES"
FROM (SELECT "t4"."id", "t4"."movie_id", "t4"."title", "t4"."imdb_index", "t4"."kind_id", "t4"."production_year", "t4"."phonetic_code", "t4"."episode_of_id", "t4"."season_nr", "t4"."episode_nr", "t4"."note", "t4"."md5sum", "cast_info0"."id" AS "id0", "cast_info0"."person_id", "cast_info0"."movie_id" AS "movie_id0", "cast_info0"."person_role_id", "cast_info0"."note" AS "note0", "cast_info0"."nr_order", "cast_info0"."role_id", "aka_name0"."id" AS "id1", "aka_name0"."person_id" AS "person_id0", "aka_name0"."name", "aka_name0"."imdb_index" AS "imdb_index0", "aka_name0"."name_pcode_cf", "aka_name0"."name_pcode_nf", "aka_name0"."surname_pcode", "aka_name0"."md5sum" AS "md5sum0", "movie_keyword0"."id" AS "id2", "movie_keyword0"."movie_id" AS "movie_id1", "movie_keyword0"."keyword_id"
FROM "IMDB"."cast_info" AS "cast_info0"
INNER JOIN ("IMDB"."movie_keyword" AS "movie_keyword0" RIGHT JOIN (SELECT *
FROM "IMDB"."aka_title"
WHERE "production_year" >= 2000) AS "t4" ON "movie_keyword0"."movie_id" = "t4"."id") ON "cast_info0"."movie_id" = "t4"."id"
INNER JOIN "IMDB"."aka_name" AS "aka_name0" ON "cast_info0"."person_id" = "aka_name0"."person_id") AS "t5"
LEFT JOIN "IMDB"."keyword" AS "keyword0" ON "t5"."keyword_id" = "keyword0"."id"
LEFT JOIN "IMDB"."movie_companies" AS "movie_companies0" ON "t5"."id" = "movie_companies0"."movie_id"
LEFT JOIN "IMDB"."company_type" AS "company_type0" ON "movie_companies0"."company_type_id" = "company_type0"."id"
GROUP BY "t5"."title", "t5"."production_year", "t5"."name", "t5"."id1") AS "t7"
GROUP BY "t7"."ACTOR_ID") AS "t8" ON "t3"."ACTOR_ID" = "t8"."ACTOR_ID"