SELECT COALESCE("ACTOR_NAME", "ACTOR_NAME") AS "ACTOR_NAME", "MOVIE_COUNT", "KEYWORDS", "COMPANY_TYPES"
FROM (SELECT "ACTOR_NAME", "MOVIE_COUNT", "KEYWORDS", "COMPANY_TYPES"
FROM "s1"
ORDER BY "MOVIE_COUNT" DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY) AS "t11"