SELECT COALESCE("cast_info"."id", "cast_info"."id") AS "id", "cast_info"."person_id", "cast_info"."movie_id", "cast_info"."person_role_id", "cast_info"."note", "cast_info"."nr_order", "cast_info"."role_id", "t1"."PERSON_ID" AS "PERSON_ID_", "t1"."AK_NAMES", "t1"."CHAR_NAMES", "t7"."MOVIE_ID" AS "MOVIE_ID_", "t7"."MOVIE_TITLE", "t7"."PRODUCTION_COMPANIES", "t7"."KEYWORDS"
FROM "IMDB"."cast_info"
INNER JOIN (SELECT "t"."person_id" AS "PERSON_ID", LISTAGG(DISTINCT "t"."name", ', ') AS "AK_NAMES", LISTAGG(DISTINCT "char_name"."name", ', ') AS "CHAR_NAMES"
FROM (SELECT "aka_name"."id", "aka_name"."person_id", "aka_name"."name", "aka_name"."imdb_index", "aka_name"."name_pcode_cf", "aka_name"."name_pcode_nf", "aka_name"."surname_pcode", "aka_name"."md5sum", "cast_info0"."id" AS "id0", "cast_info0"."person_id" AS "person_id0", "cast_info0"."movie_id", "cast_info0"."person_role_id", "cast_info0"."note", "cast_info0"."nr_order", "cast_info0"."role_id"
FROM "IMDB"."cast_info" AS "cast_info0"
RIGHT JOIN "IMDB"."aka_name" ON "cast_info0"."person_id" = "aka_name"."person_id") AS "t"
LEFT JOIN "IMDB"."char_name" ON "t"."person_id0" = "char_name"."imdb_id"
GROUP BY "t"."person_id") AS "t1" ON "cast_info"."person_id" = "t1"."PERSON_ID"
INNER JOIN (SELECT ANY_VALUE("t3"."id") AS "MOVIE_ID", ANY_VALUE("t3"."title") AS "MOVIE_TITLE", LISTAGG(DISTINCT "t3"."name", ', ') AS "PRODUCTION_COMPANIES", LISTAGG(DISTINCT "keyword"."keyword", ', ') AS "KEYWORDS"
FROM (SELECT "t2"."id", "t2"."movie_id", "t2"."title", "t2"."imdb_index", "t2"."kind_id", "t2"."production_year", "t2"."phonetic_code", "t2"."episode_of_id", "t2"."season_nr", "t2"."episode_nr", "t2"."note", "t2"."md5sum", "t2"."id0", "t2"."movie_id0", "t2"."company_id", "t2"."company_type_id", "t2"."note0", "company_name"."id" AS "id1", "company_name"."name", "company_name"."country_code", "company_name"."imdb_id", "company_name"."name_pcode_nf", "company_name"."name_pcode_sf", "company_name"."md5sum" AS "md5sum0", "movie_keyword"."id" AS "id2", "movie_keyword"."movie_id" AS "movie_id1", "movie_keyword"."keyword_id"
FROM "IMDB"."movie_keyword"
RIGHT JOIN ((SELECT "aka_title"."id", "aka_title"."movie_id", "aka_title"."title", "aka_title"."imdb_index", "aka_title"."kind_id", "aka_title"."production_year", "aka_title"."phonetic_code", "aka_title"."episode_of_id", "aka_title"."season_nr", "aka_title"."episode_nr", "aka_title"."note", "aka_title"."md5sum", "movie_companies"."id" AS "id0", "movie_companies"."movie_id" AS "movie_id0", "movie_companies"."company_id", "movie_companies"."company_type_id", "movie_companies"."note" AS "note0"
FROM "IMDB"."movie_companies"
RIGHT JOIN "IMDB"."aka_title" ON "movie_companies"."movie_id" = "aka_title"."id") AS "t2" LEFT JOIN "IMDB"."company_name" ON "t2"."company_id" = "company_name"."id") ON "movie_keyword"."movie_id" = "t2"."id") AS "t3"
LEFT JOIN "IMDB"."keyword" ON "t3"."keyword_id" = "keyword"."id"
GROUP BY "t3"."id", "t3"."title"
HAVING ANY_VALUE("t3"."title") ILIKE '%adventure%') AS "t7" ON "cast_info"."movie_id" = "t7"."MOVIE_ID"