SELECT COALESCE("AK_NAMES", "AK_NAMES") AS "AK_NAMES", "CHAR_NAMES", "MOVIE_ID", "MOVIE_TITLE", "PRODUCTION_COMPANIES", "KEYWORDS"
FROM (SELECT "AK_NAMES", "CHAR_NAMES", "MOVIE_ID_" AS "MOVIE_ID", "MOVIE_TITLE", "PRODUCTION_COMPANIES", "KEYWORDS"
FROM "s1"
ORDER BY "MOVIE_TITLE") AS "t10"