SELECT COALESCE("t10"."TITLE", "t10"."TITLE") AS "TITLE", "t10"."PRODUCTION_YEAR", "t10"."KEYWORDS", "t10"."ACTOR_COUNT", "t10"."ACTORS", "t10"."COMPANIES"
FROM (SELECT "t7"."TITLE", "t7"."PRODUCTION_YEAR", "t7"."KEYWORDS", "t2"."ACTOR_COUNT", "t2"."ACTORS", "t7"."COMPANIES"
FROM (SELECT "cast_info"."movie_id" AS "MOVIE_ID", COUNT(DISTINCT "cast_info"."person_id") AS "ACTOR_COUNT", LISTAGG(DISTINCT "aka_name"."name", ', ') AS "ACTORS"
FROM "IMDB"."aka_name"
INNER JOIN "IMDB"."cast_info" ON "aka_name"."person_id" = "cast_info"."person_id"
GROUP BY "cast_info"."movie_id") AS "t2"
RIGHT JOIN (SELECT ANY_VALUE("t4"."id") AS "TITLE_ID", "t4"."title" AS "TITLE", "t4"."production_year" AS "PRODUCTION_YEAR", LISTAGG(DISTINCT "t4"."keyword", ', ') AS "KEYWORDS", LISTAGG(DISTINCT "company_name"."name", ', ') AS "COMPANIES"
FROM (SELECT "t3"."id", "t3"."title", "t3"."imdb_index", "t3"."kind_id", "t3"."production_year", "t3"."imdb_id", "t3"."phonetic_code", "t3"."episode_of_id", "t3"."season_nr", "t3"."episode_nr", "t3"."series_years", "t3"."md5sum", "t3"."id0", "t3"."movie_id", "t3"."keyword_id", "keyword"."id" AS "id1", "keyword"."keyword", "keyword"."phonetic_code" AS "phonetic_code0", "movie_companies"."id" AS "id2", "movie_companies"."movie_id" AS "movie_id0", "movie_companies"."company_id", "movie_companies"."company_type_id", "movie_companies"."note"
FROM "IMDB"."movie_companies"
RIGHT JOIN ((SELECT "s1"."id", "s1"."title", "s1"."imdb_index", "s1"."kind_id", "s1"."production_year", "s1"."imdb_id", "s1"."phonetic_code", "s1"."episode_of_id", "s1"."season_nr", "s1"."episode_nr", "s1"."series_years", "s1"."md5sum", "movie_keyword"."id" AS "id0", "movie_keyword"."movie_id", "movie_keyword"."keyword_id"
FROM "IMDB"."movie_keyword"
RIGHT JOIN "s1" ON "movie_keyword"."movie_id" = "s1"."id") AS "t3" LEFT JOIN "IMDB"."keyword" ON "t3"."keyword_id" = "keyword"."id") ON "movie_companies"."movie_id" = "t3"."id") AS "t4"
LEFT JOIN "IMDB"."company_name" ON "t4"."company_id" = "company_name"."id"
GROUP BY "t4"."id", "t4"."title", "t4"."production_year") AS "t7" ON "t2"."MOVIE_ID" = "t7"."TITLE_ID"
WHERE "t2"."ACTOR_COUNT" > 5
ORDER BY "t7"."PRODUCTION_YEAR" DESC NULLS FIRST, "t7"."TITLE") AS "t10"