SELECT COALESCE("t2"."ACTOR_NAME", "t2"."ACTOR_NAME") AS "ACTOR_NAME", "t2"."AVG_CO_STARS_OVER_ALL_MOVIES", "t4"."MOVIE_TITLE", ', ' AS "FD_COL_3"
FROM (SELECT "ACTOR_NAME", AVG("AVG_CO_STARS") AS "AVG_CO_STARS_OVER_ALL_MOVIES"
FROM (SELECT "t"."ACTOR_NAME", "t"."MOVIE_TITLE", "t"."MOVIE_YEAR", AVG("t"."CO_STARS_COUNT") AS "AVG_CO_STARS", COUNT(*) AS "MOVIE_COUNT"
FROM (SELECT "aka_name"."person_id", "aka_name"."name", "title"."title", "title"."production_year", ANY_VALUE("aka_name"."name") AS "ACTOR_NAME", ANY_VALUE("aka_name"."person_id") AS "ACTOR_ID", ANY_VALUE("title"."title") AS "MOVIE_TITLE", ANY_VALUE("title"."production_year") AS "MOVIE_YEAR", COUNT(DISTINCT "cast_info"."id") AS "CO_STARS_COUNT"
FROM "IMDB"."aka_name"
INNER JOIN ("IMDB"."title" INNER JOIN "IMDB"."cast_info" ON "title"."id" = "cast_info"."movie_id") ON "aka_name"."person_id" = "cast_info"."person_id"
GROUP BY "aka_name"."person_id", "aka_name"."name", "title"."title", "title"."production_year") AS "t"
GROUP BY "t"."ACTOR_NAME", "t"."MOVIE_TITLE", "t"."MOVIE_YEAR") AS "t0"
GROUP BY "ACTOR_NAME"
ORDER BY 2 DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY) AS "t2"
INNER JOIN (SELECT "t3"."ACTOR_NAME", "t3"."MOVIE_TITLE", "t3"."MOVIE_YEAR", AVG("t3"."CO_STARS_COUNT") AS "AVG_CO_STARS", COUNT(*) AS "MOVIE_COUNT"
FROM (SELECT "aka_name0"."person_id", "aka_name0"."name", "title0"."title", "title0"."production_year", ANY_VALUE("aka_name0"."name") AS "ACTOR_NAME", ANY_VALUE("aka_name0"."person_id") AS "ACTOR_ID", ANY_VALUE("title0"."title") AS "MOVIE_TITLE", ANY_VALUE("title0"."production_year") AS "MOVIE_YEAR", COUNT(DISTINCT "cast_info0"."id") AS "CO_STARS_COUNT"
FROM "IMDB"."aka_name" AS "aka_name0"
INNER JOIN ("IMDB"."title" AS "title0" INNER JOIN "IMDB"."cast_info" AS "cast_info0" ON "title0"."id" = "cast_info0"."movie_id") ON "aka_name0"."person_id" = "cast_info0"."person_id"
GROUP BY "aka_name0"."person_id", "aka_name0"."name", "title0"."title", "title0"."production_year") AS "t3"
GROUP BY "t3"."ACTOR_NAME", "t3"."MOVIE_TITLE", "t3"."MOVIE_YEAR") AS "t4" ON "t2"."ACTOR_NAME" = "t4"."ACTOR_NAME"