SELECT COALESCE("ACTOR_NAME", "ACTOR_NAME") AS "ACTOR_NAME", "MOVIE_TITLE", "PRODUCTION_YEAR", "ROLE_NAME", "KEYWORDS", "TOTAL_COACTORS", "production_year" AS "production_year_"
FROM (SELECT "ACTOR_NAME", "MOVIE_TITLE", "PRODUCTION_YEAR", "ROLE_NAME", "KEYWORDS", "TOTAL_COACTORS", "PRODUCTION_YEAR" AS "production_year"
FROM "s1"
ORDER BY "TOTAL_COACTORS" DESC NULLS FIRST, "PRODUCTION_YEAR" DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY) AS "t6"