SELECT COALESCE("MOVIE_ID", "MOVIE_ID") AS "MOVIE_ID", "TITLE", "PRODUCTION_YEAR", "AKA_NAMES", "CAST_COUNT", "COMPANY_COUNT", "COMPANIES"
FROM "s1"
ORDER BY "PRODUCTION_YEAR" DESC NULLS FIRST, "CAST_COUNT" DESC NULLS FIRST