SELECT COALESCE("t6"."ACTOR_NAME", "t6"."ACTOR_NAME") AS "ACTOR_NAME", "t6"."MOVIE_TITLE", "t6"."PRODUCTION_YEAR", "t6"."KEYWORDS", "t6"."COMPANY_TYPES", "t6"."ROLES", "t6"."name"
FROM (SELECT ANY_VALUE("t2"."name") AS "ACTOR_NAME", ANY_VALUE("t2"."title") AS "MOVIE_TITLE", "t2"."production_year" AS "PRODUCTION_YEAR", LISTAGG(DISTINCT "keyword"."keyword", ',') AS "KEYWORDS", LISTAGG(DISTINCT "company_type"."kind", ',') AS "COMPANY_TYPES", LISTAGG(DISTINCT "role_type"."role", ',') AS "ROLES", "t2"."name"
FROM (SELECT "t1"."id", "t1"."person_id", "t1"."name", "t1"."imdb_index", "t1"."name_pcode_cf", "t1"."name_pcode_nf", "t1"."surname_pcode", "t1"."md5sum", "cast_info"."id" AS "id0", "cast_info"."person_id" AS "person_id0", "cast_info"."movie_id", "cast_info"."person_role_id", "cast_info"."note", "cast_info"."nr_order", "cast_info"."role_id", "s1"."id" AS "id1", "s1"."title", "s1"."imdb_index" AS "imdb_index0", "s1"."kind_id", "s1"."production_year", "s1"."imdb_id", "s1"."phonetic_code", "s1"."episode_of_id", "s1"."season_nr", "s1"."episode_nr", "s1"."series_years", "s1"."md5sum" AS "md5sum0", "movie_keyword"."id" AS "id2", "movie_keyword"."movie_id" AS "movie_id0", "movie_keyword"."keyword_id"
FROM "IMDB"."cast_info"
INNER JOIN (SELECT *
FROM "IMDB"."aka_name"
WHERE "name" LIKE '%Smith%') AS "t1" ON "cast_info"."person_id" = "t1"."person_id"
INNER JOIN ("IMDB"."movie_keyword" RIGHT JOIN "s1" ON "movie_keyword"."movie_id" = "s1"."id") ON "cast_info"."movie_id" = "s1"."id") AS "t2"
LEFT JOIN "IMDB"."keyword" ON "t2"."keyword_id" = "keyword"."id"
LEFT JOIN "IMDB"."movie_companies" ON "t2"."id1" = "movie_companies"."movie_id"
LEFT JOIN "IMDB"."company_type" ON "movie_companies"."company_type_id" = "company_type"."id"
LEFT JOIN "IMDB"."role_type" ON "t2"."role_id" = "role_type"."id"
GROUP BY "t2"."name", "t2"."title", "t2"."production_year"
ORDER BY "t2"."production_year" DESC NULLS FIRST, "t2"."name") AS "t6"