SELECT COALESCE("MOVIE_TITLE", "MOVIE_TITLE") AS "MOVIE_TITLE", "PRODUCTION_YEAR", "ACTOR_NAME", "ROLE_NAME", COUNT(DISTINCT "MOVIE_ID0") AS "ACTOR_MOVIE_COUNT", LISTAGG(DISTINCT "keyword", "FD_COL_6") AS "KEYWORDS"
FROM "s1"
GROUP BY "MOVIE_TITLE", "PRODUCTION_YEAR", "ACTOR_NAME", "ROLE_NAME"
HAVING COUNT(DISTINCT "MOVIE_ID0") > 1
FETCH NEXT 50 ROWS ONLY