SELECT COALESCE("t6"."MOVIE_TITLE", "t6"."MOVIE_TITLE") AS "MOVIE_TITLE", "t6"."PRODUCTION_YEAR", "t6"."ACTOR_NAME", "t6"."ROLE_NAME", "t6"."MOVIE_ID0", "keyword"."keyword", ', ' AS "FD_COL_6"
FROM "IMDB"."keyword"
RIGHT JOIN (SELECT "t5"."MOVIE_ID", "t5"."MOVIE_TITLE", "t5"."PRODUCTION_YEAR", "t5"."MOVIE_ID0", "t5"."ACTOR_NAME", "t5"."ROLE_NAME", "movie_keyword"."id", "movie_keyword"."movie_id", "movie_keyword"."keyword_id"
FROM "IMDB"."movie_keyword"
RIGHT JOIN (SELECT "t4"."MOVIE_ID", "t4"."MOVIE_TITLE", "t4"."PRODUCTION_YEAR", "t"."MOVIE_ID" AS "MOVIE_ID0", "t"."ACTOR_NAME", "t"."ROLE_NAME"
FROM (SELECT "cast_info"."movie_id" AS "MOVIE_ID", "aka_name"."name" AS "ACTOR_NAME", "role_type"."role" AS "ROLE_NAME"
FROM "IMDB"."role_type"
INNER JOIN ("IMDB"."aka_name" INNER JOIN "IMDB"."cast_info" ON "aka_name"."person_id" = "cast_info"."person_id") ON "role_type"."id" = "cast_info"."role_id") AS "t"
RIGHT JOIN (SELECT "t3"."MOVIE_ID", "t3"."MOVIE_TITLE", "t3"."PRODUCTION_YEAR"
FROM (SELECT *
FROM "IMDB"."info_type"
WHERE "info" ILIKE '%award%') AS "t0"
INNER JOIN ((SELECT "aka_title"."id" AS "MOVIE_ID", "aka_title"."title" AS "MOVIE_TITLE", "aka_title"."production_year" AS "PRODUCTION_YEAR", "keyword0"."keyword" AS "MOVIE_KEYWORD", ROW_NUMBER() OVER (PARTITION BY "aka_title"."production_year" ORDER BY "aka_title"."production_year" DESC NULLS FIRST) AS "RN"
FROM (SELECT "id" AS "ID"
FROM "IMDB"."kind_type"
WHERE "kind" = 'movie') AS "t2"
INNER JOIN "IMDB"."aka_title" ON "t2"."ID" = "aka_title"."kind_id"
INNER JOIN ("IMDB"."keyword" AS "keyword0" INNER JOIN "IMDB"."movie_keyword" AS "movie_keyword0" ON "keyword0"."id" = "movie_keyword0"."keyword_id") ON "aka_title"."id" = "movie_keyword0"."movie_id") AS "t3" INNER JOIN "IMDB"."movie_info" ON "t3"."MOVIE_ID" = "movie_info"."movie_id") ON "t0"."id" = "movie_info"."info_type_id"
GROUP BY "t3"."MOVIE_ID", "t3"."MOVIE_TITLE", "t3"."PRODUCTION_YEAR") AS "t4" ON "t"."MOVIE_ID" = "t4"."MOVIE_ID") AS "t5" ON "movie_keyword"."movie_id" = "t5"."MOVIE_ID") AS "t6" ON "keyword"."id" = "t6"."keyword_id"