SELECT COALESCE("MOVIE_TITLE", "MOVIE_TITLE") AS "MOVIE_TITLE", "PRODUCTION_YEAR", "ACTOR_NAMES", "MOVIE_KEYWORD", "COMPANY_TYPE", "ACTOR_COUNT"
FROM (SELECT "MOVIE_TITLE", "PRODUCTION_YEAR", "ACTOR_NAMES", "MOVIE_KEYWORD", "COMPANY_TYPE", "ACTOR_COUNT"
FROM "s1"
WHERE "ACTOR_COUNT" > 2
ORDER BY "PRODUCTION_YEAR" DESC NULLS FIRST, "MOVIE_TITLE") AS "t5"