SELECT COALESCE("t0"."MOVIE_ID", "t0"."MOVIE_ID") AS "MOVIE_ID", "t0"."COMPANIES", "t7"."MOVIE_ID" AS "MOVIE_ID0", "t7"."MOVIE_TITLE", "t7"."PRODUCTION_YEAR", "t7"."CAST_COUNT", "t7"."ACTOR_NAMES", "t7"."MOVIE_ID0" AS "MOVIE_ID00", "t7"."KEYWORDS"
FROM (SELECT "movie_companies"."movie_id" AS "MOVIE_ID", LISTAGG(DISTINCT "company_name"."name", ', ') AS "COMPANIES"
FROM "IMDB"."company_name"
INNER JOIN "IMDB"."movie_companies" ON "company_name"."id" = "movie_companies"."company_id"
GROUP BY "movie_companies"."movie_id") AS "t0"
RIGHT JOIN (SELECT "t6"."MOVIE_ID", "t6"."MOVIE_TITLE", "t6"."PRODUCTION_YEAR", "t6"."CAST_COUNT", "t6"."ACTOR_NAMES", "t2"."MOVIE_ID" AS "MOVIE_ID0", "t2"."KEYWORDS"
FROM (SELECT "movie_keyword"."movie_id" AS "MOVIE_ID", LISTAGG(DISTINCT "keyword"."keyword", ', ') AS "KEYWORDS"
FROM "IMDB"."keyword"
INNER JOIN "IMDB"."movie_keyword" ON "keyword"."id" = "movie_keyword"."keyword_id"
GROUP BY "movie_keyword"."movie_id") AS "t2"
RIGHT JOIN (SELECT ANY_VALUE("aka_title"."id") AS "MOVIE_ID", ANY_VALUE("aka_title"."title") AS "MOVIE_TITLE", "aka_title"."production_year" AS "PRODUCTION_YEAR", COUNT(*) AS "CAST_COUNT", LISTAGG(DISTINCT "aka_name"."name", ', ') AS "ACTOR_NAMES"
FROM "IMDB"."aka_title"
INNER JOIN ("IMDB"."aka_name" INNER JOIN "IMDB"."cast_info" ON "aka_name"."person_id" = "cast_info"."person_id") ON "aka_title"."id" = "cast_info"."movie_id"
GROUP BY "aka_title"."id", "aka_title"."title", "aka_title"."production_year"
HAVING COUNT(*) > 5) AS "t6" ON "t2"."MOVIE_ID" = "t6"."MOVIE_ID") AS "t7" ON "t0"."MOVIE_ID" = "t7"."MOVIE_ID"