SELECT COALESCE("t12"."TITLE", "t12"."TITLE") AS "TITLE", "t12"."PRODUCTION_YEAR", "t12"."CAST_COUNT", "t12"."COMPANY_NAMES", "t12"."COMPANY_TYPES", "t12"."KEYWORDS"
FROM (SELECT "t10"."TITLE", "t10"."PRODUCTION_YEAR", "t10"."CAST_COUNT", "t10"."COMPANY_NAMES", "t10"."COMPANY_TYPES", "t2"."KEYWORDS"
FROM (SELECT "movie_keyword"."movie_id" AS "MOVIE_ID", LISTAGG(DISTINCT "keyword"."keyword", ', ') AS "KEYWORDS"
FROM "IMDB"."keyword"
INNER JOIN "IMDB"."movie_keyword" ON "keyword"."id" = "movie_keyword"."keyword_id"
GROUP BY "movie_keyword"."movie_id") AS "t2"
RIGHT JOIN (SELECT "t9"."TITLE_ID", "t9"."TITLE", "t9"."PRODUCTION_YEAR", "t9"."KIND_ID", "t9"."CAST_COUNT", "t9"."ACTOR_NAMES", "t4"."MOVIE_ID", "t4"."COMPANY_NAMES", "t4"."COMPANY_TYPES"
FROM (SELECT "movie_companies"."movie_id" AS "MOVIE_ID", LISTAGG(DISTINCT "company_name"."name", ', ') AS "COMPANY_NAMES", LISTAGG(DISTINCT "company_type"."kind", ', ') AS "COMPANY_TYPES"
FROM "IMDB"."company_type"
INNER JOIN ("IMDB"."company_name" INNER JOIN "IMDB"."movie_companies" ON "company_name"."id" = "movie_companies"."company_id") ON "company_type"."id" = "movie_companies"."company_type_id"
GROUP BY "movie_companies"."movie_id") AS "t4"
RIGHT JOIN (SELECT ANY_VALUE("t5"."id") AS "TITLE_ID", "t5"."title" AS "TITLE", "t5"."production_year" AS "PRODUCTION_YEAR", "t5"."kind_id" AS "KIND_ID", COUNT("t5"."person_id") AS "CAST_COUNT", LISTAGG(DISTINCT "aka_name"."name", ', ') AS "ACTOR_NAMES"
FROM (SELECT "s1"."id", "s1"."title", "s1"."imdb_index", "s1"."kind_id", "s1"."production_year", "s1"."imdb_id", "s1"."phonetic_code", "s1"."episode_of_id", "s1"."season_nr", "s1"."episode_nr", "s1"."series_years", "s1"."md5sum", "cast_info"."id" AS "id0", "cast_info"."person_id", "cast_info"."movie_id", "cast_info"."person_role_id", "cast_info"."note", "cast_info"."nr_order", "cast_info"."role_id"
FROM "IMDB"."cast_info"
RIGHT JOIN "s1" ON "cast_info"."movie_id" = "s1"."id") AS "t5"
LEFT JOIN "IMDB"."aka_name" ON "t5"."person_id" = "aka_name"."person_id"
GROUP BY "t5"."id", "t5"."title", "t5"."production_year", "t5"."kind_id"
HAVING COUNT("t5"."person_id") > 3) AS "t9" ON "t4"."MOVIE_ID" = "t9"."TITLE_ID") AS "t10" ON "t2"."MOVIE_ID" = "t10"."TITLE_ID"
ORDER BY "t10"."PRODUCTION_YEAR" DESC NULLS FIRST, "t10"."CAST_COUNT" DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY) AS "t12"