SELECT COALESCE("t41"."MOVIE_ID", "t41"."MOVIE_ID") AS "MOVIE_ID", "t41"."TITLE", "t41"."CAST_COUNT", "t41"."MOVIE_KEYWORDS", "t41"."PRODUCTION_YEAR", "t41"."EXPR$0" AS "FD_COL_5", CASE WHEN "t88"."EXPR$0" IS NULL THEN 0 ELSE "t88"."EXPR$0" END AS "FD_COL_6"
FROM (SELECT "t14"."MOVIE_ID", "t14"."TITLE", "t14"."CAST_COUNT", "t14"."MOVIE_KEYWORDS", "t14"."PRODUCTION_YEAR", "t40"."EXPR$0"
FROM (SELECT "t13"."MOVIE_ID", "t13"."TITLE", "t13"."CAST_COUNT", "t13"."MOVIE_KEYWORDS", "t13"."PRODUCTION_YEAR"
FROM (SELECT AVG(CASE WHEN "t2"."COUNT" IS NOT NULL THEN CAST("t2"."COUNT" AS BIGINT) ELSE 0 END) AS "EXPR$0"
FROM (SELECT "t1"."MOVIE_ID", "t1"."TITLE", "t1"."PRODUCTION_YEAR", "t1"."RAN", "t0"."movie_id" AS "MOVIE_ID0", "t0"."COUNT"
FROM (SELECT "movie_id", COUNT(*) AS "COUNT"
FROM "IMDB"."cast_info"
GROUP BY "movie_id") AS "t0"
RIGHT JOIN (SELECT "id" AS "MOVIE_ID", "title" AS "TITLE", "production_year" AS "PRODUCTION_YEAR", ROW_NUMBER() OVER (PARTITION BY "production_year" ORDER BY "id") AS "RAN"
FROM "IMDB"."aka_title") AS "t1" ON "t0"."movie_id" = "t1"."MOVIE_ID") AS "t2"
LEFT JOIN (SELECT "movie_keyword"."movie_id" AS "MOVIE_ID", LISTAGG("keyword"."keyword", ', ') AS "KEYWORDS"
FROM "IMDB"."keyword"
INNER JOIN "IMDB"."movie_keyword" ON "keyword"."id" = "movie_keyword"."keyword_id"
GROUP BY "movie_keyword"."movie_id") AS "t4" ON "t2"."MOVIE_ID" = "t4"."MOVIE_ID") AS "t6"
INNER JOIN (SELECT "t10"."MOVIE_ID", "t10"."TITLE", CASE WHEN "t10"."COUNT" IS NOT NULL THEN CAST("t10"."COUNT" AS BIGINT) ELSE 0 END AS "CAST_COUNT", CASE WHEN "t12"."KEYWORDS" IS NOT NULL THEN CAST("t12"."KEYWORDS" AS VARCHAR CHARACTER SET "ISO-8859-1") ELSE '' END AS "MOVIE_KEYWORDS", "t10"."PRODUCTION_YEAR"
FROM (SELECT "t9"."MOVIE_ID", "t9"."TITLE", "t9"."PRODUCTION_YEAR", "t9"."RAN", "t8"."movie_id" AS "MOVIE_ID0", "t8"."COUNT"
FROM (SELECT "movie_id", COUNT(*) AS "COUNT"
FROM "IMDB"."cast_info"
GROUP BY "movie_id") AS "t8"
RIGHT JOIN (SELECT "id" AS "MOVIE_ID", "title" AS "TITLE", "production_year" AS "PRODUCTION_YEAR", ROW_NUMBER() OVER (PARTITION BY "production_year" ORDER BY "id") AS "RAN"
FROM "IMDB"."aka_title") AS "t9" ON "t8"."movie_id" = "t9"."MOVIE_ID") AS "t10"
LEFT JOIN (SELECT "movie_keyword0"."movie_id" AS "MOVIE_ID", LISTAGG("keyword0"."keyword", ', ') AS "KEYWORDS"
FROM "IMDB"."keyword" AS "keyword0"
INNER JOIN "IMDB"."movie_keyword" AS "movie_keyword0" ON "keyword0"."id" = "movie_keyword0"."keyword_id"
GROUP BY "movie_keyword0"."movie_id") AS "t12" ON "t10"."MOVIE_ID" = "t12"."MOVIE_ID") AS "t13" ON "t6"."EXPR$0" < "t13"."CAST_COUNT") AS "t14"
LEFT JOIN (SELECT "t31"."PRODUCTION_YEAR", "t39"."EXPR$0"
FROM (SELECT "t29"."PRODUCTION_YEAR"
FROM (SELECT AVG(CASE WHEN "t18"."COUNT" IS NOT NULL THEN CAST("t18"."COUNT" AS BIGINT) ELSE 0 END) AS "EXPR$0"
FROM (SELECT "t17"."MOVIE_ID", "t17"."TITLE", "t17"."PRODUCTION_YEAR", "t17"."RAN", "t16"."movie_id" AS "MOVIE_ID0", "t16"."COUNT"
FROM (SELECT "movie_id", COUNT(*) AS "COUNT"
FROM "IMDB"."cast_info"
GROUP BY "movie_id") AS "t16"
RIGHT JOIN (SELECT "id" AS "MOVIE_ID", "title" AS "TITLE", "production_year" AS "PRODUCTION_YEAR", ROW_NUMBER() OVER (PARTITION BY "production_year" ORDER BY "id") AS "RAN"
FROM "IMDB"."aka_title") AS "t17" ON "t16"."movie_id" = "t17"."MOVIE_ID") AS "t18"
LEFT JOIN (SELECT "movie_keyword1"."movie_id" AS "MOVIE_ID", LISTAGG("keyword1"."keyword", ', ') AS "KEYWORDS"
FROM "IMDB"."keyword" AS "keyword1"
INNER JOIN "IMDB"."movie_keyword" AS "movie_keyword1" ON "keyword1"."id" = "movie_keyword1"."keyword_id"
GROUP BY "movie_keyword1"."movie_id") AS "t20" ON "t18"."MOVIE_ID" = "t20"."MOVIE_ID") AS "t22"
INNER JOIN (SELECT "t26"."MOVIE_ID", "t26"."TITLE", CASE WHEN "t26"."COUNT" IS NOT NULL THEN CAST("t26"."COUNT" AS BIGINT) ELSE 0 END AS "CAST_COUNT", CASE WHEN "t28"."KEYWORDS" IS NOT NULL THEN CAST("t28"."KEYWORDS" AS VARCHAR CHARACTER SET "ISO-8859-1") ELSE '' END AS "MOVIE_KEYWORDS", "t26"."PRODUCTION_YEAR"
FROM (SELECT "t25"."MOVIE_ID", "t25"."TITLE", "t25"."PRODUCTION_YEAR", "t25"."RAN", "t24"."movie_id" AS "MOVIE_ID0", "t24"."COUNT"
FROM (SELECT "movie_id", COUNT(*) AS "COUNT"
FROM "IMDB"."cast_info"
GROUP BY "movie_id") AS "t24"
RIGHT JOIN (SELECT "id" AS "MOVIE_ID", "title" AS "TITLE", "production_year" AS "PRODUCTION_YEAR", ROW_NUMBER() OVER (PARTITION BY "production_year" ORDER BY "id") AS "RAN"
FROM "IMDB"."aka_title") AS "t25" ON "t24"."movie_id" = "t25"."MOVIE_ID") AS "t26"
LEFT JOIN (SELECT "movie_keyword2"."movie_id" AS "MOVIE_ID", LISTAGG("keyword2"."keyword", ', ') AS "KEYWORDS"
FROM "IMDB"."keyword" AS "keyword2"
INNER JOIN "IMDB"."movie_keyword" AS "movie_keyword2" ON "keyword2"."id" = "movie_keyword2"."keyword_id"
GROUP BY "movie_keyword2"."movie_id") AS "t28" ON "t26"."MOVIE_ID" = "t28"."MOVIE_ID") AS "t29" ON "t22"."EXPR$0" < "t29"."CAST_COUNT"
GROUP BY "t29"."PRODUCTION_YEAR") AS "t31"
LEFT JOIN (SELECT "t35"."PRODUCTION_YEAR", AVG(CASE WHEN "t35"."COUNT" IS NOT NULL THEN CAST("t35"."COUNT" AS BIGINT) ELSE 0 END) AS "EXPR$0"
FROM (SELECT "t34"."MOVIE_ID", "t34"."TITLE", "t34"."PRODUCTION_YEAR", "t34"."RAN", "t33"."movie_id" AS "MOVIE_ID0", "t33"."COUNT"
FROM (SELECT "movie_id", COUNT(*) AS "COUNT"
FROM "IMDB"."cast_info"
GROUP BY "movie_id") AS "t33"
RIGHT JOIN (SELECT "id" AS "MOVIE_ID", "title" AS "TITLE", "production_year" AS "PRODUCTION_YEAR", ROW_NUMBER() OVER (PARTITION BY "production_year" ORDER BY "id") AS "RAN"
FROM "IMDB"."aka_title") AS "t34" ON "t33"."movie_id" = "t34"."MOVIE_ID") AS "t35"
LEFT JOIN (SELECT "movie_keyword3"."movie_id" AS "MOVIE_ID", LISTAGG("keyword3"."keyword", ', ') AS "KEYWORDS"
FROM "IMDB"."keyword" AS "keyword3"
INNER JOIN "IMDB"."movie_keyword" AS "movie_keyword3" ON "keyword3"."id" = "movie_keyword3"."keyword_id"
GROUP BY "movie_keyword3"."movie_id") AS "t37" ON "t35"."MOVIE_ID" = "t37"."MOVIE_ID"
GROUP BY "t35"."PRODUCTION_YEAR") AS "t39" ON "t31"."PRODUCTION_YEAR" IS NOT DISTINCT FROM "t39"."PRODUCTION_YEAR") AS "t40" ON "t14"."PRODUCTION_YEAR" = "t40"."PRODUCTION_YEAR") AS "t41"
LEFT JOIN (SELECT "t85"."MOVIE_ID" AS "movie_id", CASE WHEN "t87"."EXPR$0" IS NOT NULL THEN "t87"."EXPR$0" ELSE 0 END AS "EXPR$0"
FROM (SELECT "t57"."MOVIE_ID"
FROM (SELECT "t56"."MOVIE_ID", "t56"."TITLE", "t56"."CAST_COUNT", "t56"."MOVIE_KEYWORDS", "t56"."PRODUCTION_YEAR"
FROM (SELECT AVG(CASE WHEN "t45"."COUNT" IS NOT NULL THEN CAST("t45"."COUNT" AS BIGINT) ELSE 0 END) AS "EXPR$0"
FROM (SELECT "t44"."MOVIE_ID", "t44"."TITLE", "t44"."PRODUCTION_YEAR", "t44"."RAN", "t43"."movie_id" AS "MOVIE_ID0", "t43"."COUNT"
FROM (SELECT "movie_id", COUNT(*) AS "COUNT"
FROM "IMDB"."cast_info"
GROUP BY "movie_id") AS "t43"
RIGHT JOIN (SELECT "id" AS "MOVIE_ID", "title" AS "TITLE", "production_year" AS "PRODUCTION_YEAR", ROW_NUMBER() OVER (PARTITION BY "production_year" ORDER BY "id") AS "RAN"
FROM "IMDB"."aka_title") AS "t44" ON "t43"."movie_id" = "t44"."MOVIE_ID") AS "t45"
LEFT JOIN (SELECT "movie_keyword4"."movie_id" AS "MOVIE_ID", LISTAGG("keyword4"."keyword", ', ') AS "KEYWORDS"
FROM "IMDB"."keyword" AS "keyword4"
INNER JOIN "IMDB"."movie_keyword" AS "movie_keyword4" ON "keyword4"."id" = "movie_keyword4"."keyword_id"
GROUP BY "movie_keyword4"."movie_id") AS "t47" ON "t45"."MOVIE_ID" = "t47"."MOVIE_ID") AS "t49"
INNER JOIN (SELECT "t53"."MOVIE_ID", "t53"."TITLE", CASE WHEN "t53"."COUNT" IS NOT NULL THEN CAST("t53"."COUNT" AS BIGINT) ELSE 0 END AS "CAST_COUNT", CASE WHEN "t55"."KEYWORDS" IS NOT NULL THEN CAST("t55"."KEYWORDS" AS VARCHAR CHARACTER SET "ISO-8859-1") ELSE '' END AS "MOVIE_KEYWORDS", "t53"."PRODUCTION_YEAR"
FROM (SELECT "t52"."MOVIE_ID", "t52"."TITLE", "t52"."PRODUCTION_YEAR", "t52"."RAN", "t51"."movie_id" AS "MOVIE_ID0", "t51"."COUNT"
FROM (SELECT "movie_id", COUNT(*) AS "COUNT"
FROM "IMDB"."cast_info"
GROUP BY "movie_id") AS "t51"
RIGHT JOIN (SELECT "id" AS "MOVIE_ID", "title" AS "TITLE", "production_year" AS "PRODUCTION_YEAR", ROW_NUMBER() OVER (PARTITION BY "production_year" ORDER BY "id") AS "RAN"
FROM "IMDB"."aka_title") AS "t52" ON "t51"."movie_id" = "t52"."MOVIE_ID") AS "t53"
LEFT JOIN (SELECT "movie_keyword5"."movie_id" AS "MOVIE_ID", LISTAGG("keyword5"."keyword", ', ') AS "KEYWORDS"
FROM "IMDB"."keyword" AS "keyword5"
INNER JOIN "IMDB"."movie_keyword" AS "movie_keyword5" ON "keyword5"."id" = "movie_keyword5"."keyword_id"
GROUP BY "movie_keyword5"."movie_id") AS "t55" ON "t53"."MOVIE_ID" = "t55"."MOVIE_ID") AS "t56" ON "t49"."EXPR$0" < "t56"."CAST_COUNT") AS "t57"
LEFT JOIN (SELECT "t74"."PRODUCTION_YEAR", "t82"."EXPR$0"
FROM (SELECT "t72"."PRODUCTION_YEAR"
FROM (SELECT AVG(CASE WHEN "t61"."COUNT" IS NOT NULL THEN CAST("t61"."COUNT" AS BIGINT) ELSE 0 END) AS "EXPR$0"
FROM (SELECT "t60"."MOVIE_ID", "t60"."TITLE", "t60"."PRODUCTION_YEAR", "t60"."RAN", "t59"."movie_id" AS "MOVIE_ID0", "t59"."COUNT"
FROM (SELECT "movie_id", COUNT(*) AS "COUNT"
FROM "IMDB"."cast_info"
GROUP BY "movie_id") AS "t59"
RIGHT JOIN (SELECT "id" AS "MOVIE_ID", "title" AS "TITLE", "production_year" AS "PRODUCTION_YEAR", ROW_NUMBER() OVER (PARTITION BY "production_year" ORDER BY "id") AS "RAN"
FROM "IMDB"."aka_title") AS "t60" ON "t59"."movie_id" = "t60"."MOVIE_ID") AS "t61"
LEFT JOIN (SELECT "movie_keyword6"."movie_id" AS "MOVIE_ID", LISTAGG("keyword6"."keyword", ', ') AS "KEYWORDS"
FROM "IMDB"."keyword" AS "keyword6"
INNER JOIN "IMDB"."movie_keyword" AS "movie_keyword6" ON "keyword6"."id" = "movie_keyword6"."keyword_id"
GROUP BY "movie_keyword6"."movie_id") AS "t63" ON "t61"."MOVIE_ID" = "t63"."MOVIE_ID") AS "t65"
INNER JOIN (SELECT "t69"."MOVIE_ID", "t69"."TITLE", CASE WHEN "t69"."COUNT" IS NOT NULL THEN CAST("t69"."COUNT" AS BIGINT) ELSE 0 END AS "CAST_COUNT", CASE WHEN "t71"."KEYWORDS" IS NOT NULL THEN CAST("t71"."KEYWORDS" AS VARCHAR CHARACTER SET "ISO-8859-1") ELSE '' END AS "MOVIE_KEYWORDS", "t69"."PRODUCTION_YEAR"
FROM (SELECT "t68"."MOVIE_ID", "t68"."TITLE", "t68"."PRODUCTION_YEAR", "t68"."RAN", "t67"."movie_id" AS "MOVIE_ID0", "t67"."COUNT"
FROM (SELECT "movie_id", COUNT(*) AS "COUNT"
FROM "IMDB"."cast_info"
GROUP BY "movie_id") AS "t67"
RIGHT JOIN (SELECT "id" AS "MOVIE_ID", "title" AS "TITLE", "production_year" AS "PRODUCTION_YEAR", ROW_NUMBER() OVER (PARTITION BY "production_year" ORDER BY "id") AS "RAN"
FROM "IMDB"."aka_title") AS "t68" ON "t67"."movie_id" = "t68"."MOVIE_ID") AS "t69"
LEFT JOIN (SELECT "movie_keyword7"."movie_id" AS "MOVIE_ID", LISTAGG("keyword7"."keyword", ', ') AS "KEYWORDS"
FROM "IMDB"."keyword" AS "keyword7"
INNER JOIN "IMDB"."movie_keyword" AS "movie_keyword7" ON "keyword7"."id" = "movie_keyword7"."keyword_id"
GROUP BY "movie_keyword7"."movie_id") AS "t71" ON "t69"."MOVIE_ID" = "t71"."MOVIE_ID") AS "t72" ON "t65"."EXPR$0" < "t72"."CAST_COUNT"
GROUP BY "t72"."PRODUCTION_YEAR") AS "t74"
LEFT JOIN (SELECT "t78"."PRODUCTION_YEAR", AVG(CASE WHEN "t78"."COUNT" IS NOT NULL THEN CAST("t78"."COUNT" AS BIGINT) ELSE 0 END) AS "EXPR$0"
FROM (SELECT "t77"."MOVIE_ID", "t77"."TITLE", "t77"."PRODUCTION_YEAR", "t77"."RAN", "t76"."movie_id" AS "MOVIE_ID0", "t76"."COUNT"
FROM (SELECT "movie_id", COUNT(*) AS "COUNT"
FROM "IMDB"."cast_info"
GROUP BY "movie_id") AS "t76"
RIGHT JOIN (SELECT "id" AS "MOVIE_ID", "title" AS "TITLE", "production_year" AS "PRODUCTION_YEAR", ROW_NUMBER() OVER (PARTITION BY "production_year" ORDER BY "id") AS "RAN"
FROM "IMDB"."aka_title") AS "t77" ON "t76"."movie_id" = "t77"."MOVIE_ID") AS "t78"
LEFT JOIN (SELECT "movie_keyword8"."movie_id" AS "MOVIE_ID", LISTAGG("keyword8"."keyword", ', ') AS "KEYWORDS"
FROM "IMDB"."keyword" AS "keyword8"
INNER JOIN "IMDB"."movie_keyword" AS "movie_keyword8" ON "keyword8"."id" = "movie_keyword8"."keyword_id"
GROUP BY "movie_keyword8"."movie_id") AS "t80" ON "t78"."MOVIE_ID" = "t80"."MOVIE_ID"
GROUP BY "t78"."PRODUCTION_YEAR") AS "t82" ON "t74"."PRODUCTION_YEAR" IS NOT DISTINCT FROM "t82"."PRODUCTION_YEAR") AS "t83" ON "t57"."PRODUCTION_YEAR" = "t83"."PRODUCTION_YEAR"
GROUP BY "t57"."MOVIE_ID") AS "t85"
LEFT JOIN (SELECT "cast_info9"."movie_id", COUNT(DISTINCT "person_info"."id") AS "EXPR$0"
FROM "IMDB"."cast_info" AS "cast_info9"
INNER JOIN "IMDB"."person_info" ON "cast_info9"."person_id" = "person_info"."person_id"
GROUP BY "cast_info9"."movie_id") AS "t87" ON "t85"."MOVIE_ID" IS NOT DISTINCT FROM "t87"."movie_id") AS "t88" ON "t41"."MOVIE_ID" = "t88"."movie_id"