SELECT COALESCE("MOVIE_ID", "MOVIE_ID") AS "MOVIE_ID", "TITLE", "PRODUCTION_YEAR", "CAST_COUNT", "MOVIE_KEYWORDS", "AVG_CAST_COUNT", "UNIQUE_ACTORS"
FROM (SELECT "MOVIE_ID", "TITLE", "PRODUCTION_YEAR", "CAST_COUNT", "MOVIE_KEYWORDS", "FD_COL_5" AS "AVG_CAST_COUNT", "FD_COL_6" AS "UNIQUE_ACTORS"
FROM "s1"
ORDER BY "PRODUCTION_YEAR" DESC NULLS FIRST, "CAST_COUNT" DESC NULLS FIRST
FETCH NEXT 100 ROWS ONLY) AS "t92"