SELECT COALESCE("t0"."MOVIE_ID", "t0"."MOVIE_ID") AS "MOVIE_ID", "t0"."KEYWORD_COUNT", "t0"."BUDGET_INFO", "t6"."MOVIE_ID" AS "MOVIE_ID0", "t6"."TITLE", "t6"."PRODUCTION_YEAR", "t6"."KIND_ID", "t6"."TOTAL_CAST", "t6"."CAST_NAMES"
FROM (SELECT "movie_info"."movie_id" AS "MOVIE_ID", COUNT("movie_keyword"."keyword_id") AS "KEYWORD_COUNT", MAX(CASE WHEN "info_type"."info" = 'Budget' THEN "movie_info"."info" ELSE NULL END) AS "BUDGET_INFO"
FROM "IMDB"."movie_info"
INNER JOIN "IMDB"."info_type" ON "movie_info"."info_type_id" = "info_type"."id"
LEFT JOIN "IMDB"."movie_keyword" ON "movie_info"."movie_id" = "movie_keyword"."movie_id"
GROUP BY "movie_info"."movie_id") AS "t0"
RIGHT JOIN (SELECT ANY_VALUE("t3"."id") AS "MOVIE_ID", "t3"."title" AS "TITLE", "t3"."production_year" AS "PRODUCTION_YEAR", "t3"."kind_id" AS "KIND_ID", COUNT(DISTINCT "t3"."person_id") AS "TOTAL_CAST", LISTAGG(DISTINCT "aka_name"."name", ', ') AS "CAST_NAMES"
FROM "IMDB"."aka_name"
RIGHT JOIN (SELECT "t2"."id", "t2"."movie_id", "t2"."title", "t2"."imdb_index", "t2"."kind_id", "t2"."production_year", "t2"."phonetic_code", "t2"."episode_of_id", "t2"."season_nr", "t2"."episode_nr", "t2"."note", "t2"."md5sum", "t2"."id0", "t2"."movie_id0", "t2"."subject_id", "t2"."status_id", "cast_info"."id" AS "id1", "cast_info"."person_id", "cast_info"."movie_id" AS "movie_id1", "cast_info"."person_role_id", "cast_info"."note" AS "note0", "cast_info"."nr_order", "cast_info"."role_id"
FROM "IMDB"."cast_info"
RIGHT JOIN (SELECT "t1"."id", "t1"."movie_id", "t1"."title", "t1"."imdb_index", "t1"."kind_id", "t1"."production_year", "t1"."phonetic_code", "t1"."episode_of_id", "t1"."season_nr", "t1"."episode_nr", "t1"."note", "t1"."md5sum", "complete_cast"."id" AS "id0", "complete_cast"."movie_id" AS "movie_id0", "complete_cast"."subject_id", "complete_cast"."status_id"
FROM "IMDB"."complete_cast"
RIGHT JOIN (SELECT *
FROM "IMDB"."aka_title"
WHERE "production_year" > 2000) AS "t1" ON "complete_cast"."movie_id" = "t1"."id") AS "t2" ON "cast_info"."id" = "t2"."subject_id") AS "t3" ON "aka_name"."person_id" = "t3"."person_id"
GROUP BY "t3"."id", "t3"."title", "t3"."production_year", "t3"."kind_id") AS "t6" ON "t0"."MOVIE_ID" = "t6"."MOVIE_ID"