SELECT COALESCE("TITLE", "TITLE") AS "TITLE", "PRODUCTION_YEAR", "TOTAL_CAST", "CAST_NAMES", "KEYWORD_COUNT", "BUDGET_INFO"
FROM (SELECT "TITLE", "PRODUCTION_YEAR", "TOTAL_CAST", "CAST_NAMES", CASE WHEN "KEYWORD_COUNT" IS NOT NULL THEN CAST("KEYWORD_COUNT" AS BIGINT) ELSE 0 END AS "KEYWORD_COUNT", "BUDGET_INFO"
FROM "s1"
ORDER BY "PRODUCTION_YEAR" DESC NULLS FIRST, "TOTAL_CAST" DESC NULLS FIRST
FETCH NEXT 100 ROWS ONLY) AS "t9"