SELECT COALESCE("TITLE", "TITLE") AS "TITLE", "PRODUCTION_YEAR", "TOP_ACTOR", "TOTAL_MOVIES_WITH_ACTOR"
FROM (SELECT "TITLE", "PRODUCTION_YEAR", ANY_VALUE("NAME") AS "TOP_ACTOR", COUNT(DISTINCT "movie_id") AS "TOTAL_MOVIES_WITH_ACTOR"
FROM "s1"
GROUP BY "TITLE", "PRODUCTION_YEAR", "NAME"
HAVING COUNT(DISTINCT "movie_id") > 0
ORDER BY "PRODUCTION_YEAR" DESC NULLS FIRST, "TITLE") AS "t9"