SELECT COALESCE("t0"."TITLE_ID", "t0"."TITLE_ID") AS "TITLE_ID", "t0"."TITLE", "t0"."PRODUCTION_YEAR", "t0"."TITLE_RANK", "t0"."id", "t0"."person_id", "t0"."movie_id", "t0"."person_role_id", "t0"."note", "t0"."nr_order", "t0"."role_id", "t4"."PERSON_ID" AS "PERSON_ID_", "t4"."NAME"
FROM (SELECT "t"."TITLE_ID", "t"."TITLE", "t"."PRODUCTION_YEAR", "t"."TITLE_RANK", "cast_info"."id", "cast_info"."person_id", "cast_info"."movie_id", "cast_info"."person_role_id", "cast_info"."note", "cast_info"."nr_order", "cast_info"."role_id"
FROM "IMDB"."cast_info"
RIGHT JOIN (SELECT "id" AS "TITLE_ID", "title" AS "TITLE", "production_year" AS "PRODUCTION_YEAR", ROW_NUMBER() OVER (PARTITION BY "production_year" ORDER BY "title") AS "TITLE_RANK"
FROM "IMDB"."aka_title") AS "t" ON "cast_info"."movie_id" = "t"."TITLE_ID") AS "t0"
LEFT JOIN (SELECT "t3"."person_id" AS "PERSON_ID", "aka_name"."name" AS "NAME"
FROM (SELECT MAX("MOVIE_COUNT") AS "EXPR$0"
FROM (SELECT "person_id", COUNT(DISTINCT "movie_id") AS "MOVIE_COUNT"
FROM "IMDB"."cast_info"
GROUP BY "person_id") AS "t1") AS "t2"
INNER JOIN ("IMDB"."aka_name" INNER JOIN (SELECT "person_id", COUNT(DISTINCT "movie_id") AS "MOVIE_COUNT"
FROM "IMDB"."cast_info"
GROUP BY "person_id") AS "t3" ON "aka_name"."person_id" = "t3"."person_id") ON "t2"."EXPR$0" = "t3"."MOVIE_COUNT") AS "t4" ON "t0"."person_id" = "t4"."PERSON_ID"