SELECT COALESCE("ACTOR_NAME", "ACTOR_NAME") AS "ACTOR_NAME", "MOVIE_TITLE", "PRODUCTION_YEAR", "KEYWORDS", "CAST_TYPE", "COMPANY_NAME", "name"
FROM (SELECT "ACTOR_NAME", "MOVIE_TITLE", "PRODUCTION_YEAR", "KEYWORDS", "CAST_TYPE", "COMPANY_NAME", "name"
FROM "s1"
ORDER BY "PRODUCTION_YEAR" DESC NULLS FIRST, "name") AS "t5"