SELECT COALESCE("ACTOR_NAME", "ACTOR_NAME") AS "ACTOR_NAME", "MOVIE_TITLE", "PRODUCTION_YEAR", "KEYWORDS", "COMPANIES", "ROLE_COUNT", "name"
FROM (SELECT "ACTOR_NAME", "MOVIE_TITLE", "PRODUCTION_YEAR", "KEYWORDS", "COMPANIES", "ROLE_COUNT", "name"
FROM "s1"
WHERE "FD_COL_8" > 2
ORDER BY "PRODUCTION_YEAR" DESC NULLS FIRST, "name") AS "t6"