SELECT COALESCE("TITLE", "TITLE") AS "TITLE", "PRODUCTION_YEAR", "ACTOR_NAME", "MOVIE_COUNT"
FROM (SELECT "TITLE", "PRODUCTION_YEAR", "NAME" AS "ACTOR_NAME", "MOVIE_COUNT"
FROM "s1"
ORDER BY "PRODUCTION_YEAR" DESC NULLS FIRST, "NAME") AS "t7"