SELECT COALESCE("t"."movie_id", "t"."movie_id") AS "MOVIE_ID", "t"."KEYWORD_COUNT", "t5"."MOVIE_ID" AS "MOVIE_ID0", "t5"."TITLE", "t5"."PRODUCTION_YEAR", "t5"."ACTOR_COUNT", "t5"."ACTOR_NAMES"
FROM (SELECT "movie_id", COUNT(*) AS "KEYWORD_COUNT"
FROM "IMDB"."movie_keyword"
GROUP BY "movie_id") AS "t"
RIGHT JOIN (SELECT ANY_VALUE("t2"."id") AS "MOVIE_ID", "t2"."title" AS "TITLE", "t2"."production_year" AS "PRODUCTION_YEAR", COUNT(DISTINCT "t2"."person_id") AS "ACTOR_COUNT", LISTAGG(DISTINCT "aka_name"."name", ', ') AS "ACTOR_NAMES"
FROM "IMDB"."aka_name"
RIGHT JOIN (SELECT "t1"."id", "t1"."movie_id", "t1"."title", "t1"."imdb_index", "t1"."kind_id", "t1"."production_year", "t1"."phonetic_code", "t1"."episode_of_id", "t1"."season_nr", "t1"."episode_nr", "t1"."note", "t1"."md5sum", "t1"."id0", "t1"."movie_id0", "t1"."subject_id", "t1"."status_id", "cast_info"."id" AS "id1", "cast_info"."person_id", "cast_info"."movie_id" AS "movie_id1", "cast_info"."person_role_id", "cast_info"."note" AS "note0", "cast_info"."nr_order", "cast_info"."role_id"
FROM "IMDB"."cast_info"
RIGHT JOIN (SELECT "t0"."id", "t0"."movie_id", "t0"."title", "t0"."imdb_index", "t0"."kind_id", "t0"."production_year", "t0"."phonetic_code", "t0"."episode_of_id", "t0"."season_nr", "t0"."episode_nr", "t0"."note", "t0"."md5sum", "complete_cast"."id" AS "id0", "complete_cast"."movie_id" AS "movie_id0", "complete_cast"."subject_id", "complete_cast"."status_id"
FROM "IMDB"."complete_cast"
RIGHT JOIN (SELECT *
FROM "IMDB"."aka_title"
WHERE "production_year" >= 2000) AS "t0" ON "complete_cast"."movie_id" = "t0"."id") AS "t1" ON "cast_info"."id" = "t1"."subject_id") AS "t2" ON "aka_name"."person_id" = "t2"."person_id"
GROUP BY "t2"."id", "t2"."title", "t2"."production_year") AS "t5" ON "t"."movie_id" = "t5"."MOVIE_ID"