SELECT COALESCE("MOVIE_ID", "MOVIE_ID") AS "MOVIE_ID", "TITLE", "PRODUCTION_YEAR", "ACTOR_COUNT_SAFE", "KEYWORD_COUNT_SAFE", "ACTOR_KEYWORD_DIFF"
FROM (SELECT "MOVIE_ID0" AS "MOVIE_ID", "TITLE", "PRODUCTION_YEAR", "ACTOR_COUNT" AS "ACTOR_COUNT_SAFE", CASE WHEN "KEYWORD_COUNT" IS NULL THEN 0 ELSE "KEYWORD_COUNT" END AS "KEYWORD_COUNT_SAFE", CAST("ACTOR_COUNT" - CASE WHEN "KEYWORD_COUNT" IS NULL THEN 0 ELSE "KEYWORD_COUNT" END AS BIGINT) AS "ACTOR_KEYWORD_DIFF"
FROM "s1"
ORDER BY "PRODUCTION_YEAR" DESC NULLS FIRST, "ACTOR_COUNT" DESC NULLS FIRST) AS "t8"