SELECT COALESCE("t5"."ACTOR_NAME", "t5"."ACTOR_NAME") AS "ACTOR_NAME", "t5"."MOVIE_TITLE", "t5"."CAST_ORDER", "t5"."ACTOR_INFO", "t5"."MOVIE_KEYWORD", "t5"."COMPANY_NAME", "t5"."COMPANY_TYPE", "t5"."production_year"
FROM (SELECT "t1"."name" AS "ACTOR_NAME", "t1"."title" AS "MOVIE_TITLE", "t1"."nr_order" AS "CAST_ORDER", "person_info"."info" AS "ACTOR_INFO", "keyword"."keyword" AS "MOVIE_KEYWORD", "t2"."name" AS "COMPANY_NAME", "t3"."kind" AS "COMPANY_TYPE", "t1"."production_year"
FROM "IMDB"."person_info"
RIGHT JOIN ((SELECT "aka_name"."id", "aka_name"."person_id", "aka_name"."name", "aka_name"."imdb_index", "aka_name"."name_pcode_cf", "aka_name"."name_pcode_nf", "aka_name"."surname_pcode", "aka_name"."md5sum", "cast_info"."id" AS "id0", "cast_info"."person_id" AS "person_id0", "cast_info"."movie_id", "cast_info"."person_role_id", "cast_info"."note", "cast_info"."nr_order", "cast_info"."role_id", "s1"."id" AS "id1", "s1"."title", "s1"."imdb_index" AS "imdb_index0", "s1"."kind_id", "s1"."production_year", "s1"."imdb_id", "s1"."phonetic_code", "s1"."episode_of_id", "s1"."season_nr", "s1"."episode_nr", "s1"."series_years", "s1"."md5sum" AS "md5sum0", "movie_keyword"."id" AS "id2", "movie_keyword"."movie_id" AS "movie_id0", "movie_keyword"."keyword_id"
FROM "IMDB"."movie_keyword"
RIGHT JOIN ("IMDB"."cast_info" INNER JOIN "s1" ON "cast_info"."movie_id" = "s1"."id" INNER JOIN "IMDB"."aka_name" ON "cast_info"."person_id" = "aka_name"."person_id") ON "movie_keyword"."movie_id" = "s1"."id") AS "t1" LEFT JOIN "IMDB"."keyword" ON "t1"."keyword_id" = "keyword"."id" INNER JOIN ("IMDB"."movie_companies" INNER JOIN (SELECT *
FROM "IMDB"."company_name"
WHERE "country_code" = 'USA') AS "t2" ON "movie_companies"."company_id" = "t2"."id" INNER JOIN (SELECT *
FROM "IMDB"."company_type"
WHERE "kind" = 'Distributor') AS "t3" ON "movie_companies"."company_type_id" = "t3"."id") ON "t1"."id1" = "movie_companies"."movie_id") ON "person_info"."person_id" = "t1"."person_id"
ORDER BY "t1"."production_year" DESC NULLS FIRST, "t1"."name") AS "t5"