SELECT COALESCE("MOVIE_ID", "MOVIE_ID") AS "MOVIE_ID", "TITLE", "PRODUCTION_YEAR", "COMPANY_NAME", "KEYWORDS", "ACTORS", "TOTAL_CAST_MEMBERS"
FROM "s1"
ORDER BY "PRODUCTION_YEAR" DESC NULLS FIRST, "TOTAL_CAST_MEMBERS" DESC NULLS FIRST
FETCH NEXT 50 ROWS ONLY