SELECT COALESCE("MOVIE_TITLE", "MOVIE_TITLE") AS "MOVIE_TITLE", "PRODUCTION_YEAR", "NUM_ACTORS", "NUM_KEYWORDS", "COMPANIES"
FROM (SELECT "id", "title", "PRODUCTION_YEAR", ANY_VALUE("title") AS "MOVIE_TITLE", COUNT(DISTINCT "person_id") AS "NUM_ACTORS", COUNT(DISTINCT "keyword") AS "NUM_KEYWORDS", LISTAGG(DISTINCT "name", "FD_COL_6") AS "COMPANIES"
FROM "s1"
GROUP BY "id", "title", "PRODUCTION_YEAR"
HAVING COUNT(DISTINCT "person_id") > 5
ORDER BY "PRODUCTION_YEAR" DESC NULLS FIRST, 5 DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY) AS "t6"