SELECT COALESCE("ACTOR_NAME", "ACTOR_NAME") AS "ACTOR_NAME", "MOVIE_TITLE", "ROLE_ID", "COMPANY_TYPE", "COMPANY_COUNT", "AVG_MOVIE_RATING"
FROM (SELECT "ACTOR_NAME", "MOVIE_TITLE", "ROLE_ID_" AS "ROLE_ID", "COMPANY_TYPE", "COMPANY_COUNT", "AVG_MOVIE_RATING"
FROM "s1"
WHERE "COMPANY_COUNT" > 1
ORDER BY "AVG_MOVIE_RATING" DESC NULLS FIRST, "ACTOR_NAME") AS "t10"