SELECT COALESCE("t3"."AKA_NAME", "t3"."AKA_NAME") AS "AKA_NAME", "t3"."TITLE_NAME", "t3"."PRODUCTION_YEAR", "t3"."ROLE_COUNT"
FROM (SELECT "s1"."AKA_ID", "s1"."AKA_NAME", "s1"."TITLE_NAME", "s1"."PRODUCTION_YEAR", COUNT(*) AS "ROLE_COUNT"
FROM "IMDB"."role_type"
INNER JOIN "s1" ON "role_type"."id" = "s1"."person_role_id"
GROUP BY "s1"."AKA_ID", "s1"."AKA_NAME", "s1"."TITLE_NAME", "s1"."PRODUCTION_YEAR"
HAVING COUNT(*) > 2
ORDER BY "s1"."PRODUCTION_YEAR" DESC NULLS FIRST, 5 DESC NULLS FIRST) AS "t3"