SELECT COALESCE("MOVIE_ID", "MOVIE_ID") AS "MOVIE_ID", "MOVIE_TITLE", "ACTOR_NAME", "ACTOR_ROLE", "TOTAL_APPEARANCES", "COMPANY_NAME", "COMPANY_TYPE", "TOTAL_MOVIES"
FROM (SELECT "MOVIE_ID0" AS "MOVIE_ID", "MOVIE_TITLE", "ACTOR_NAME", "ACTOR_ROLE", "TOTAL_APPEARANCES", CAST("COMPANY_NAME" AS VARCHAR CHARACTER SET "ISO-8859-1") AS "COMPANY_NAME", CAST("COMPANY_TYPE" AS VARCHAR CHARACTER SET "ISO-8859-1") AS "COMPANY_TYPE", CAST("TOTAL_MOVIES" AS BIGINT) AS "TOTAL_MOVIES"
FROM "s1"
ORDER BY "TOTAL_APPEARANCES" DESC NULLS FIRST, "TOTAL_MOVIES" DESC NULLS FIRST
FETCH NEXT 100 ROWS ONLY) AS "t9"