SELECT COALESCE("t2"."MOVIE_ID", "t2"."MOVIE_ID") AS "MOVIE_ID", "t2"."COMPANY_NAME", "t2"."COMPANY_TYPE", "t2"."TOTAL_MOVIES", "t6"."MOVIE_ID" AS "MOVIE_ID0", "t6"."MOVIE_TITLE", "t6"."ACTOR_NAME", "t6"."ACTOR_ROLE", "t6"."TOTAL_APPEARANCES", "complete_cast"."id", "complete_cast"."movie_id" AS "movie_id_", "complete_cast"."subject_id", "complete_cast"."status_id"
FROM (SELECT "MOVIE_ID", "COMPANY_NAME", "COMPANY_TYPE", "TOTAL_MOVIES"
FROM (SELECT "movie_companies"."movie_id", "company_name"."name", "company_type"."kind", ANY_VALUE("company_name"."name") AS "COMPANY_NAME", ANY_VALUE("company_type"."kind") AS "COMPANY_TYPE", COUNT(*) AS "TOTAL_MOVIES"
FROM "IMDB"."company_type"
INNER JOIN ("IMDB"."company_name" INNER JOIN "IMDB"."movie_companies" ON "company_name"."id" = "movie_companies"."company_id") ON "company_type"."id" = "movie_companies"."company_type_id"
GROUP BY "company_type"."kind", "company_name"."name", "movie_companies"."movie_id") AS "t0"
WHERE "t0"."TOTAL_MOVIES" > 5) AS "t2"
INNER JOIN ((SELECT "MOVIE_ID", "MOVIE_TITLE", "ACTOR_NAME", "ACTOR_ROLE", "TOTAL_APPEARANCES"
FROM (SELECT "title"."id" AS "id00", "title"."title", "aka_name"."name", "role_type"."role", ANY_VALUE("title"."id") AS "MOVIE_ID", ANY_VALUE("title"."title") AS "MOVIE_TITLE", ANY_VALUE("aka_name"."name") AS "ACTOR_NAME", ANY_VALUE("role_type"."role") AS "ACTOR_ROLE", COUNT(*) AS "TOTAL_APPEARANCES"
FROM "IMDB"."role_type"
INNER JOIN ("IMDB"."aka_name" INNER JOIN ("IMDB"."title" INNER JOIN "IMDB"."cast_info" ON "title"."id" = "cast_info"."movie_id") ON "aka_name"."person_id" = "cast_info"."person_id") ON "role_type"."id" = "cast_info"."role_id"
GROUP BY "role_type"."role", "aka_name"."name", "title"."id", "title"."title") AS "t4"
WHERE "t4"."TOTAL_APPEARANCES" > 1) AS "t6" LEFT JOIN "IMDB"."complete_cast" ON "t6"."MOVIE_ID" = "complete_cast"."movie_id") ON "t2"."MOVIE_ID" = "t6"."MOVIE_ID"