SELECT COALESCE("t4"."title", "t4"."title") AS "title", "t4"."name", "comp_cast_type"."kind", "t4"."name0", "t"."info", "keyword"."keyword", ANY_VALUE("t4"."title") AS "MOVIE_TITLE", ANY_VALUE("t4"."name") AS "ACTOR_NAME", ANY_VALUE("comp_cast_type"."kind") AS "CAST_TYPE", ANY_VALUE("t4"."name0") AS "COMPANY_NAME", ANY_VALUE("t"."info") AS "MOVIE_INFO", ANY_VALUE("keyword"."keyword") AS "MOVIE_KEYWORD", MAX("t4"."production_year") AS "LATEST_YEAR"
FROM (SELECT *
FROM "IMDB"."info_type"
WHERE "info" LIKE '%box office%') AS "t"
INNER JOIN "IMDB"."movie_info" ON "t"."id" = "movie_info"."info_type_id"
INNER JOIN ("IMDB"."comp_cast_type" INNER JOIN ("IMDB"."keyword" INNER JOIN "IMDB"."movie_keyword" ON "keyword"."id" = "movie_keyword"."keyword_id" INNER JOIN (SELECT "t3"."id", "t3"."title", "t3"."imdb_index", "t3"."kind_id", "t3"."production_year", "t3"."imdb_id", "t3"."phonetic_code", "t3"."episode_of_id", "t3"."season_nr", "t3"."episode_nr", "t3"."series_years", "t3"."md5sum", "complete_cast"."id" AS "id0", "complete_cast"."movie_id", "complete_cast"."subject_id", "complete_cast"."status_id", "cast_info"."id" AS "id1", "cast_info"."person_id", "cast_info"."movie_id" AS "movie_id0", "cast_info"."person_role_id", "cast_info"."note", "cast_info"."nr_order", "cast_info"."role_id", "aka_name"."id" AS "id2", "aka_name"."person_id" AS "person_id0", "aka_name"."name", "aka_name"."imdb_index" AS "imdb_index0", "aka_name"."name_pcode_cf", "aka_name"."name_pcode_nf", "aka_name"."surname_pcode", "aka_name"."md5sum" AS "md5sum0", "company_name"."id" AS "id3", "company_name"."name" AS "name0", "company_name"."country_code", "company_name"."imdb_id" AS "imdb_id0", "company_name"."name_pcode_nf" AS "name_pcode_nf0", "company_name"."name_pcode_sf", "company_name"."md5sum" AS "md5sum1"
FROM "IMDB"."aka_name"
INNER JOIN "IMDB"."cast_info" ON "aka_name"."person_id" = "cast_info"."person_id"
INNER JOIN ("IMDB"."complete_cast" INNER JOIN ("IMDB"."company_name" LEFT JOIN (SELECT FIRST_VALUE("movie_id") OVER (PARTITION BY "company_id" RANGE BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS "MOVIE_ID", "company_id" AS "company_id0"
FROM "IMDB"."movie_companies"
GROUP BY FIRST_VALUE("id") OVER (PARTITION BY "company_id" RANGE BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING), FIRST_VALUE("movie_id") OVER (PARTITION BY "company_id" RANGE BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING), FIRST_VALUE("company_id") OVER (PARTITION BY "company_id" RANGE BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING), FIRST_VALUE("company_type_id") OVER (PARTITION BY "company_id" RANGE BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING), FIRST_VALUE("note") OVER (PARTITION BY "company_id" RANGE BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING), "company_id") AS "t2" ON "company_name"."id" = "t2"."company_id0" INNER JOIN (SELECT *
FROM "IMDB"."title"
WHERE "production_year" >= 2000) AS "t3" ON "t2"."MOVIE_ID" = "t3"."id") ON "complete_cast"."movie_id" = "t3"."id") ON "cast_info"."id" = "complete_cast"."subject_id") AS "t4" ON "movie_keyword"."movie_id" = "t4"."id") ON "comp_cast_type"."id" = "t4"."person_role_id") ON "movie_info"."movie_id" = "t4"."id"
GROUP BY "t"."info", "comp_cast_type"."kind", "keyword"."keyword", "t4"."title", "t4"."name", "t4"."name0"