SELECT COALESCE("PRODUCTIONYEAR", "PRODUCTIONYEAR") AS "PRODUCTIONYEAR", COUNT(*) AS "TOTALMOVIES", LISTAGG(DISTINCT "MOVIETITLE", "FD_COL_2") AS "MOVIETITLES", LISTAGG(DISTINCT "ACTORNAME", "FD_COL_2") AS "ACTORS", LISTAGG(DISTINCT "COMPANYNAME", "FD_COL_2") AS "PRODUCTIONCOMPANIES", LISTAGG(DISTINCT "KEYWORD", "FD_COL_2") AS "KEYWORDS"
FROM "s1"
GROUP BY "PRODUCTIONYEAR"
ORDER BY "PRODUCTIONYEAR" DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY