SELECT COALESCE("t7"."MOVIE_ID", "t7"."MOVIE_ID") AS "MOVIE_ID", "t7"."TITLE", "t7"."PRODUCTION_YEAR", "t7"."AKA_COUNT", "t7"."CAST_COUNT", "t7"."COMPANY_COUNT", "t7"."COMPANY_NAMES"
FROM (SELECT "t5"."MOVIE_ID", "t5"."TITLE", "t5"."PRODUCTION_YEAR", "t5"."AKA_COUNT", "t5"."CAST_COUNT", "t3"."COMPANY_COUNT", "t3"."COMPANY_NAMES"
FROM (SELECT "movie_companies"."movie_id" AS "MOVIE_ID", COUNT(DISTINCT "company_name"."id") AS "COMPANY_COUNT", LISTAGG(DISTINCT "company_name"."name", ', ') AS "COMPANY_NAMES"
FROM "IMDB"."company_name"
INNER JOIN "IMDB"."movie_companies" ON "company_name"."id" = "movie_companies"."company_id"
GROUP BY "movie_companies"."movie_id") AS "t3"
RIGHT JOIN (SELECT ANY_VALUE("id0") AS "MOVIE_ID", "title" AS "TITLE", "production_year" AS "PRODUCTION_YEAR", COUNT("id1") AS "AKA_COUNT", COUNT(DISTINCT "person_id") AS "CAST_COUNT"
FROM "s1"
GROUP BY "id0", "title", "production_year") AS "t5" ON "t3"."MOVIE_ID" = "t5"."MOVIE_ID"
ORDER BY "t5"."PRODUCTION_YEAR" DESC NULLS FIRST, "t5"."TITLE") AS "t7"