SELECT COALESCE("movie_info"."id", "movie_info"."id") AS "id", "movie_info"."movie_id", "movie_info"."info_type_id", "movie_info"."info", "movie_info"."note", "title"."id" AS "id0", "title"."title", "title"."imdb_index", "title"."kind_id", "title"."production_year", "title"."imdb_id", "title"."phonetic_code", "title"."episode_of_id", "title"."season_nr", "title"."episode_nr", "title"."series_years", "title"."md5sum", "t0"."MOVIE_ID" AS "MOVIE_ID_", "t0"."CAST_NAMES", "t0"."TOTAL_CAST_COUNT", "t2"."MOVIE_ID" AS "MOVIE_ID0", "t2"."KEYWORDS"
FROM "IMDB"."movie_info"
RIGHT JOIN ("IMDB"."title" LEFT JOIN (SELECT "cast_info"."movie_id" AS "MOVIE_ID", LISTAGG("aka_name"."name", ', ') AS "CAST_NAMES", COUNT(DISTINCT "cast_info"."person_id") AS "TOTAL_CAST_COUNT"
FROM "IMDB"."aka_name"
INNER JOIN "IMDB"."cast_info" ON "aka_name"."person_id" = "cast_info"."person_id"
GROUP BY "cast_info"."movie_id") AS "t0" ON "title"."id" = "t0"."MOVIE_ID" LEFT JOIN (SELECT "movie_keyword"."movie_id" AS "MOVIE_ID", LISTAGG("keyword"."keyword", ', ') AS "KEYWORDS"
FROM "IMDB"."keyword"
INNER JOIN "IMDB"."movie_keyword" ON "keyword"."id" = "movie_keyword"."keyword_id"
GROUP BY "movie_keyword"."movie_id") AS "t2" ON "title"."id" = "t2"."MOVIE_ID") ON "movie_info"."movie_id" = "title"."id"