SELECT COALESCE("title", "title") AS "TITLE", "production_year" AS "PRODUCTION_YEAR", "CAST_NAMES", "KEYWORDS", CASE WHEN "info" IS NOT NULL THEN CAST("info" AS VARCHAR CHARACTER SET "ISO-8859-1") ELSE 'No info' END AS "MOVIE_INFO"
FROM "s1"
WHERE "production_year" >= 2000 AND "KEYWORDS" ILIKE '%action%' AND "CAST_NAMES" IS NOT NULL