SELECT COALESCE("ACTOR_NAME", "ACTOR_NAME") AS "ACTOR_NAME", "MOVIE_TITLE", "COMPANY_TYPE", "COMPANY_NAME", "PRODUCTION_YEAR", "MOVIE_KEYWORD", "ACTOR_COUNT", "production_year" AS "production_year_"
FROM (SELECT "ACTOR_NAME", "MOVIE_TITLE", "COMPANY_TYPE", "COMPANY_NAME", "PRODUCTION_YEAR", "MOVIE_KEYWORD", "ACTOR_COUNT", "PRODUCTION_YEAR" AS "production_year"
FROM "s1"
ORDER BY "ACTOR_COUNT" DESC NULLS FIRST, "PRODUCTION_YEAR" DESC NULLS FIRST
FETCH NEXT 50 ROWS ONLY) AS "t4"