SELECT COALESCE("ACTOR_NAME", "ACTOR_NAME") AS "ACTOR_NAME", "MOVIE_TITLE", "PRODUCTION_YEAR", "ROLE_ID", "TOTAL_MOVIES", "name"
FROM (SELECT "ACTOR_NAME", "MOVIE_TITLE", "PRODUCTION_YEAR", "ROLE_ID", "TOTAL_MOVIES", "name"
FROM "s1"
ORDER BY "TOTAL_MOVIES" DESC NULLS FIRST, "name") AS "t6"