SELECT COALESCE("t2"."AKA_NAME", "t2"."AKA_NAME") AS "AKA_NAME", "t2"."MOVIE_TITLE", "t2"."CAST_NOTE", "t2"."MOVIE_KEYWORD", "t2"."COMPANY_NAME", "t2"."COMPANY_TYPE", "t2"."production_year"
FROM (SELECT "aka_name"."name" AS "AKA_NAME", "s1"."title" AS "MOVIE_TITLE", "cast_info"."note" AS "CAST_NOTE", "s1"."keyword" AS "MOVIE_KEYWORD", "company_name"."name" AS "COMPANY_NAME", "company_type"."kind" AS "COMPANY_TYPE", "s1"."production_year"
FROM "IMDB"."company_type"
INNER JOIN ("IMDB"."company_name" INNER JOIN "IMDB"."movie_companies" ON "company_name"."id" = "movie_companies"."company_id") ON "company_type"."id" = "movie_companies"."company_type_id"
INNER JOIN ("IMDB"."aka_name" INNER JOIN "IMDB"."cast_info" ON "aka_name"."person_id" = "cast_info"."person_id" INNER JOIN "s1" ON "cast_info"."movie_id" = "s1"."movie_id") ON "movie_companies"."movie_id" = "s1"."id"
ORDER BY "s1"."production_year" DESC NULLS FIRST, "aka_name"."name") AS "t2"