SELECT COALESCE("ACTOR_NAME", "ACTOR_NAME") AS "ACTOR_NAME", "MOVIE_TITLE", "PRODUCTION_YEAR", "ROLE", "COMPANY_TYPE"
FROM (SELECT "name" AS "ACTOR_NAME", "title" AS "MOVIE_TITLE", "production_year" AS "PRODUCTION_YEAR", "role" AS "ROLE", "kind" AS "COMPANY_TYPE"
FROM "s1"
ORDER BY "production_year" DESC NULLS FIRST, "name") AS "t2"