SELECT COALESCE("t2"."ACTOR_NAME", "t2"."ACTOR_NAME") AS "ACTOR_NAME", "t2"."MOVIE_TITLE", "t2"."PRODUCTION_YEAR", "t2"."COMPANY_TYPE"
FROM (SELECT "aka_name"."name" AS "ACTOR_NAME", "s1"."title" AS "MOVIE_TITLE", "s1"."production_year" AS "PRODUCTION_YEAR", "company_type"."kind" AS "COMPANY_TYPE"
FROM "IMDB"."company_type"
INNER JOIN "s1" ON "company_type"."id" = "s1"."company_type_id"
INNER JOIN ("IMDB"."aka_name" INNER JOIN "IMDB"."cast_info" ON "aka_name"."person_id" = "cast_info"."person_id") ON "s1"."id" = "cast_info"."movie_id"
ORDER BY "s1"."production_year" DESC NULLS FIRST, "aka_name"."name") AS "t2"