SELECT COALESCE("ACTOR_NAME", "ACTOR_NAME") AS "ACTOR_NAME", "MOVIE_TITLE", "PRODUCTION_YEAR", "CAST_ORDER", "MOVIE_KEYWORD", "COMPANY_TYPE", "nr_order"
FROM (SELECT "ACTOR_NAME", "MOVIE_TITLE", "production_year" AS "PRODUCTION_YEAR", "CAST_ORDER", "MOVIE_KEYWORD", "COMPANY_TYPE", "nr_order"
FROM "s1"
ORDER BY "production_year" DESC NULLS FIRST, "nr_order") AS "t4"