SELECT COALESCE("t10"."MOVIE_TITLE", "t10"."MOVIE_TITLE") AS "MOVIE_TITLE", "t10"."PRODUCTION_YEAR", "t10"."CAST_COUNT", "t10"."VALID_CAST_COUNT", "t10"."GENRE_LIST", "t10"."ADDITIONAL_INFO", "t10"."INFO_NOTE", "t10"."CAST_SIZE_CATEGORY"
FROM (SELECT "t8"."TITLE" AS "MOVIE_TITLE", "t8"."PRODUCTION_YEAR", "t8"."CAST_COUNT", "t8"."VALID_CAST_COUNT", CASE WHEN "t8"."GENRES" IS NOT NULL THEN CAST("t8"."GENRES" AS VARCHAR CHARACTER SET "ISO-8859-1") ELSE 'No Genre' END AS "GENRE_LIST", "t5"."ADDITIONAL_INFO", "t5"."INFO_NOTE", CASE WHEN "t8"."CAST_COUNT" > 100 THEN 'Large Ensemble ' WHEN "t8"."CAST_COUNT" >= 50 AND "t8"."CAST_COUNT" <= 100 THEN 'Medium Ensemble' ELSE 'Small Ensemble ' END AS "CAST_SIZE_CATEGORY"
FROM (SELECT "t4"."id" AS "MOVIE_ID", "t4"."title" AS "MOVIE_TITLE", "t4"."info" AS "ADDITIONAL_INFO", "movie_info_idx"."note" AS "INFO_NOTE"
FROM (SELECT "aka_title0"."id", "aka_title0"."movie_id", "aka_title0"."title", "aka_title0"."imdb_index", "aka_title0"."kind_id", "aka_title0"."production_year", "aka_title0"."phonetic_code", "aka_title0"."episode_of_id", "aka_title0"."season_nr", "aka_title0"."episode_nr", "aka_title0"."note", "aka_title0"."md5sum", "movie_info"."id" AS "id0", "movie_info"."movie_id" AS "movie_id0", "movie_info"."info_type_id", "movie_info"."info", "movie_info"."note" AS "note0"
FROM "IMDB"."movie_info"
RIGHT JOIN "IMDB"."aka_title" AS "aka_title0" ON "movie_info"."movie_id" = "aka_title0"."id") AS "t4"
LEFT JOIN "IMDB"."movie_info_idx" ON "t4"."id" = "movie_info_idx"."movie_id" AND "t4"."info_type_id" = "movie_info_idx"."info_type_id") AS "t5"
RIGHT JOIN (SELECT "s1"."TITLE_ID", "s1"."TITLE", "s1"."PRODUCTION_YEAR", "s1"."CAST_COUNT", "s1"."VALID_CAST_COUNT", "s1"."DECADE_BUCKET", "t7"."MOVIE_ID", "t7"."GENRES"
FROM (SELECT "aka_title1"."movie_id" AS "MOVIE_ID", LISTAGG(DISTINCT "keyword"."keyword", ', ') AS "GENRES"
FROM "IMDB"."keyword"
INNER JOIN ("IMDB"."aka_title" AS "aka_title1" INNER JOIN "IMDB"."movie_keyword" ON "aka_title1"."id" = "movie_keyword"."movie_id") ON "keyword"."id" = "movie_keyword"."keyword_id"
GROUP BY "aka_title1"."movie_id") AS "t7"
RIGHT JOIN "s1" ON "t7"."MOVIE_ID" = "s1"."TITLE_ID") AS "t8" ON "t5"."MOVIE_ID" = "t8"."TITLE_ID"
ORDER BY "t8"."PRODUCTION_YEAR" DESC NULLS FIRST, "t8"."CAST_COUNT" DESC NULLS FIRST) AS "t10"