SELECT COALESCE("t12"."ACTOR_ID", "t12"."ACTOR_ID") AS "ACTOR_ID", "t12"."ACTOR_NAME", "t12"."MOVIE_COUNT", "t12"."TITLE", "t12"."PRODUCTION_YEAR", "t12"."COMPANY_NAMES", "t12"."TOTAL_COMPANIES"
FROM (SELECT "s1"."ACTOR_ID", "s1"."NAME" AS "ACTOR_NAME", "s1"."MOVIE_COUNT", "s1"."TITLE", "s1"."PRODUCTION_YEAR", "s1"."COMPANY_NAMES", "s1"."TOTAL_COMPANIES"
FROM (SELECT AVG("t9"."MOVIE_COUNT") AS "EXPR$0"
FROM (SELECT "cast_info1"."person_id", COUNT(DISTINCT "cast_info1"."movie_id") AS "MOVIE_COUNT"
FROM (SELECT "id" AS "TITLE_ID", "title" AS "TITLE", "production_year" AS "PRODUCTION_YEAR", ROW_NUMBER() OVER (PARTITION BY "production_year" ORDER BY "title") AS "TITLE_RANK"
FROM "IMDB"."aka_title") AS "t8"
INNER JOIN "IMDB"."cast_info" AS "cast_info1" ON "t8"."TITLE_ID" = "cast_info1"."movie_id"
GROUP BY "cast_info1"."person_id") AS "t9") AS "t10"
INNER JOIN "s1" ON "t10"."EXPR$0" <= "s1"."MOVIE_COUNT"
ORDER BY "s1"."NAME", "s1"."PRODUCTION_YEAR" DESC NULLS FIRST) AS "t12"