SELECT COALESCE("t5"."NAME", "t5"."NAME") AS "NAME", "t5"."ACTOR_ID", "t5"."MOVIE_COUNT", "cast_info"."id", "cast_info"."person_id", "cast_info"."movie_id", "cast_info"."person_role_id", "cast_info"."note", "cast_info"."nr_order", "cast_info"."role_id", "t2"."TITLE_ID", "t2"."TITLE", "t2"."PRODUCTION_YEAR", "t2"."TITLE_RANK", CAST("t1"."MOVIE_ID" AS INTEGER) AS "MOVIE_ID_", CAST("t1"."COMPANY_NAMES" AS VARCHAR CHARACTER SET "ISO-8859-1") AS "COMPANY_NAMES", CAST("t1"."TOTAL_COMPANIES" AS BIGINT) AS "TOTAL_COMPANIES"
FROM (SELECT "movie_companies"."movie_id" AS "MOVIE_ID", LISTAGG(DISTINCT "company_name"."name", ', ') AS "COMPANY_NAMES", COUNT(DISTINCT "movie_companies"."company_id") AS "TOTAL_COMPANIES"
FROM "IMDB"."company_name"
INNER JOIN "IMDB"."movie_companies" ON "company_name"."id" = "movie_companies"."company_id"
GROUP BY "movie_companies"."movie_id"
HAVING COUNT(DISTINCT "movie_companies"."company_id") > 1) AS "t1"
INNER JOIN (SELECT "id" AS "TITLE_ID", "title" AS "TITLE", "production_year" AS "PRODUCTION_YEAR", ROW_NUMBER() OVER (PARTITION BY "production_year" ORDER BY "title") AS "TITLE_RANK"
FROM "IMDB"."aka_title") AS "t2" ON "t1"."MOVIE_ID" = "t2"."TITLE_ID"
INNER JOIN "IMDB"."cast_info" ON "t2"."TITLE_ID" = "cast_info"."movie_id"
INNER JOIN (SELECT "aka_name"."name" AS "NAME", "aka_name"."id" AS "ACTOR_ID", "t4"."MOVIE_COUNT"
FROM (SELECT "cast_info0"."person_id", COUNT(DISTINCT "cast_info0"."movie_id") AS "MOVIE_COUNT"
FROM (SELECT "id" AS "TITLE_ID", "title" AS "TITLE", "production_year" AS "PRODUCTION_YEAR", ROW_NUMBER() OVER (PARTITION BY "production_year" ORDER BY "title") AS "TITLE_RANK"
FROM "IMDB"."aka_title") AS "t3"
INNER JOIN "IMDB"."cast_info" AS "cast_info0" ON "t3"."TITLE_ID" = "cast_info0"."movie_id"
GROUP BY "cast_info0"."person_id") AS "t4"
RIGHT JOIN "IMDB"."aka_name" ON "t4"."person_id" = "aka_name"."person_id") AS "t5" ON "cast_info"."person_id" = "t5"."ACTOR_ID"