SELECT COALESCE("t"."movie_id", "t"."movie_id") AS "MOVIE_ID", "t"."TOTAL_ACTORS", "t5"."MOVIE_ID" AS "MOVIE_ID0", "t5"."TITLE", "t5"."PRODUCTION_YEAR", "t5"."TOTAL_COMPANIES", "t5"."TOTAL_KEYWORDS"
FROM (SELECT "cast_info"."movie_id", COUNT(DISTINCT "aka_name"."id") AS "TOTAL_ACTORS"
FROM "IMDB"."aka_name"
INNER JOIN "IMDB"."cast_info" ON "aka_name"."person_id" = "cast_info"."person_id"
GROUP BY "cast_info"."movie_id") AS "t"
RIGHT JOIN (SELECT "t2"."MOVIE_ID", "t2"."TITLE", "t2"."PRODUCTION_YEAR", CASE WHEN SUM("t2"."company_id") IS NOT NULL THEN CAST(SUM("t2"."company_id") AS INTEGER) ELSE 0 END AS "TOTAL_COMPANIES", COUNT(DISTINCT "keyword"."keyword") AS "TOTAL_KEYWORDS"
FROM (SELECT "t1"."MOVIE_ID", "t1"."TITLE", "t1"."PRODUCTION_YEAR", "t1"."RANK_IN_YEAR", "t1"."id", "t1"."movie_id", "t1"."company_id", "t1"."company_type_id", "t1"."note", "movie_keyword"."id" AS "id0", "movie_keyword"."movie_id" AS "movie_id0", "movie_keyword"."keyword_id"
FROM "IMDB"."movie_keyword"
RIGHT JOIN (SELECT "t0"."MOVIE_ID", "t0"."TITLE", "t0"."PRODUCTION_YEAR", "t0"."RANK_IN_YEAR", "movie_companies"."id", "movie_companies"."movie_id", "movie_companies"."company_id", "movie_companies"."company_type_id", "movie_companies"."note"
FROM "IMDB"."movie_companies"
RIGHT JOIN (SELECT "id" AS "MOVIE_ID", "title" AS "TITLE", "production_year" AS "PRODUCTION_YEAR", ROW_NUMBER() OVER (PARTITION BY "production_year" ORDER BY "title") AS "RANK_IN_YEAR"
FROM "IMDB"."aka_title") AS "t0" ON "movie_companies"."movie_id" = "t0"."MOVIE_ID") AS "t1" ON "movie_keyword"."movie_id" = "t1"."MOVIE_ID") AS "t2"
LEFT JOIN "IMDB"."keyword" ON "t2"."keyword_id" = "keyword"."id"
GROUP BY "t2"."MOVIE_ID", "t2"."TITLE", "t2"."PRODUCTION_YEAR"
HAVING CASE WHEN SUM("t2"."company_id") IS NOT NULL THEN CAST(SUM("t2"."company_id") AS INTEGER) ELSE 0 END > 0) AS "t5" ON "t"."movie_id" = "t5"."MOVIE_ID"