SELECT COALESCE("MOVIE_ID", "MOVIE_ID") AS "MOVIE_ID", "TITLE", "PRODUCTION_YEAR", "TOTAL_COMPANIES", "TOTAL_KEYWORDS", "TOTAL_ACTORS", "MOVIE_ERA"
FROM (SELECT "MOVIE_ID0" AS "MOVIE_ID", "TITLE", "PRODUCTION_YEAR", "TOTAL_COMPANIES", "TOTAL_KEYWORDS", CASE WHEN "TOTAL_ACTORS" IS NOT NULL THEN CAST("TOTAL_ACTORS" AS BIGINT) ELSE 0 END AS "TOTAL_ACTORS", CASE WHEN "PRODUCTION_YEAR" >= 2000 THEN 'Modern ' ELSE 'Classic' END AS "MOVIE_ERA"
FROM "s1"
ORDER BY "PRODUCTION_YEAR" DESC NULLS FIRST, "TITLE") AS "t8"