SELECT COALESCE("t2"."MOVIE_ID", "t2"."MOVIE_ID") AS "MOVIE_ID", "t2"."TITLE", "t2"."PRODUCTION_YEAR", "t2"."KIND_ID", "t2"."KEYWORD", "t2"."COMPANY_NAME", "t2"."COMPANY_TYPE", "t2"."KEYWORD_RANK", "t4"."MOVIE_ID" AS "MOVIE_ID0", "t4"."TOTAL_CAST", "t4"."VALIDATED_CAST", "t4"."NOTE_NON_EMPTY_RATIO", "t4"."CAST_NAMES"
FROM (SELECT "t1"."id" AS "MOVIE_ID", "t1"."title" AS "TITLE", "t1"."production_year" AS "PRODUCTION_YEAR", "t1"."kind_id" AS "KIND_ID", CASE WHEN "t1"."keyword" <> '' THEN CAST(CASE WHEN "t1"."keyword" = '' THEN NULL ELSE "t1"."keyword" END AS VARCHAR CHARACTER SET "ISO-8859-1") ELSE 'No Keyword' END AS "KEYWORD", "company_name"."name" AS "COMPANY_NAME", "company_type"."kind" AS "COMPANY_TYPE", ROW_NUMBER() OVER (PARTITION BY "t1"."id" ORDER BY "t1"."keyword" DESC) AS "KEYWORD_RANK"
FROM (SELECT "t0"."id", "t0"."movie_id", "t0"."title", "t0"."imdb_index", "t0"."kind_id", "t0"."production_year", "t0"."phonetic_code", "t0"."episode_of_id", "t0"."season_nr", "t0"."episode_nr", "t0"."note", "t0"."md5sum", "t0"."id0", "t0"."movie_id0", "t0"."keyword_id", "keyword"."id" AS "id1", "keyword"."keyword", "keyword"."phonetic_code" AS "phonetic_code0", "movie_companies"."id" AS "id2", "movie_companies"."movie_id" AS "movie_id1", "movie_companies"."company_id", "movie_companies"."company_type_id", "movie_companies"."note" AS "note0"
FROM "IMDB"."movie_companies"
RIGHT JOIN ((SELECT "t"."id", "t"."movie_id", "t"."title", "t"."imdb_index", "t"."kind_id", "t"."production_year", "t"."phonetic_code", "t"."episode_of_id", "t"."season_nr", "t"."episode_nr", "t"."note", "t"."md5sum", "movie_keyword"."id" AS "id0", "movie_keyword"."movie_id" AS "movie_id0", "movie_keyword"."keyword_id"
FROM "IMDB"."movie_keyword"
RIGHT JOIN (SELECT *
FROM "IMDB"."aka_title"
WHERE "production_year" >= 2000 AND TRIM(BOTH ' ' FROM "title") <> '') AS "t" ON "movie_keyword"."movie_id" = "t"."id") AS "t0" LEFT JOIN "IMDB"."keyword" ON "t0"."keyword_id" = "keyword"."id") ON "movie_companies"."movie_id" = "t0"."id") AS "t1"
LEFT JOIN "IMDB"."company_name" ON "t1"."company_id" = "company_name"."id"
LEFT JOIN "IMDB"."company_type" ON "t1"."company_type_id" = "company_type"."id") AS "t2"
LEFT JOIN (SELECT "cast_info"."movie_id" AS "MOVIE_ID", COUNT(DISTINCT "cast_info"."person_id") AS "TOTAL_CAST", COUNT(1) AS "VALIDATED_CAST", AVG(CASE WHEN "cast_info"."note" <> '' THEN 1 ELSE 0 END) AS "NOTE_NON_EMPTY_RATIO", LISTAGG(DISTINCT "aka_name"."name", ', ') AS "CAST_NAMES"
FROM "IMDB"."cast_info"
LEFT JOIN "IMDB"."aka_name" ON "cast_info"."person_id" = "aka_name"."person_id"
GROUP BY "cast_info"."movie_id") AS "t4" ON "t2"."MOVIE_ID" = "t4"."MOVIE_ID"