SELECT COALESCE("t16"."TITLE", "t16"."TITLE") AS "TITLE", "t16"."PRODUCTION_YEAR", "t16"."COMPANY_COUNT", "t16"."ACTOR_NAMES", "t16"."COMPANY_NOTES"
FROM (SELECT "t13"."TITLE", "t14"."production_year" AS "PRODUCTION_YEAR", "t13"."COMPANY_COUNT", "t13"."ACTOR_NAMES", "t13"."COMPANY_NOTES"
FROM (SELECT "t12"."MOVIE_ID", "t12"."TITLE", "t12"."COMPANY_COUNT", "t12"."COMPANY_NOTES", "t10"."CAST_COUNT", "t10"."ACTOR_NAMES"
FROM (SELECT ANY_VALUE("aka_title0"."id") AS "MOVIE_ID", "aka_title0"."title" AS "TITLE", "aka_title0"."production_year" AS "PRODUCTION_YEAR", COUNT(DISTINCT "cast_info0"."person_id") AS "CAST_COUNT", LISTAGG(DISTINCT "aka_name0"."name", ', ') AS "ACTOR_NAMES"
FROM (SELECT "id" AS "ID"
FROM "IMDB"."kind_type"
WHERE "kind" = 'movie') AS "t6"
INNER JOIN "IMDB"."aka_title" AS "aka_title0" ON "t6"."ID" = "aka_title0"."kind_id"
INNER JOIN ("IMDB"."aka_name" AS "aka_name0" INNER JOIN "IMDB"."cast_info" AS "cast_info0" ON "aka_name0"."person_id" = "cast_info0"."person_id") ON "aka_title0"."id" = "cast_info0"."movie_id"
GROUP BY "aka_title0"."id", "aka_title0"."title", "aka_title0"."production_year"
HAVING COUNT(DISTINCT "cast_info0"."person_id") > 10) AS "t10"
INNER JOIN (SELECT "s1"."MOVIE_ID", "s1"."TITLE", COUNT(DISTINCT "movie_companies"."company_id") AS "COMPANY_COUNT", LISTAGG(DISTINCT "movie_companies"."note", ', ') AS "COMPANY_NOTES"
FROM "s1"
INNER JOIN "IMDB"."movie_companies" ON "s1"."MOVIE_ID" = "movie_companies"."movie_id"
GROUP BY "s1"."MOVIE_ID", "s1"."TITLE") AS "t12" ON "t10"."MOVIE_ID" = "t12"."MOVIE_ID") AS "t13"
INNER JOIN (SELECT *
FROM "IMDB"."aka_title"
WHERE "production_year" >= 2000) AS "t14" ON "t13"."MOVIE_ID" = "t14"."id"
FETCH NEXT 100 ROWS ONLY) AS "t16"