SELECT COALESCE("t5"."MOVIE_ID", "t5"."MOVIE_ID") AS "MOVIE_ID0", "t5"."TITLE", "t5"."PRODUCTION_YEAR", ARRAY_AGG(DISTINCT "t5"."KEYWORD") AS "KEYWORDS", ARRAY_AGG(DISTINCT "t2"."ACTOR_NAME") AS "ACTORS", ARRAY_AGG(DISTINCT "t2"."ACTOR_ROLE") AS "ROLES", COUNT(DISTINCT "t5"."COMPANY_NAME") AS "COMPANY_COUNT"
FROM (SELECT "cast_info"."movie_id" AS "MOVIE_ID", "aka_name"."name" AS "ACTOR_NAME", "role_type"."role" AS "ACTOR_ROLE"
FROM "IMDB"."role_type"
INNER JOIN ("IMDB"."aka_name" INNER JOIN "IMDB"."cast_info" ON "aka_name"."person_id" = "cast_info"."person_id") ON "role_type"."id" = "cast_info"."role_id") AS "t2"
RIGHT JOIN (SELECT "t4"."id" AS "MOVIE_ID", "t4"."title" AS "TITLE", "t4"."production_year" AS "PRODUCTION_YEAR", "t4"."keyword" AS "KEYWORD", "company_name"."name" AS "COMPANY_NAME", "company_type"."kind" AS "COMPANY_TYPE"
FROM (SELECT "t3"."id", "t3"."movie_id", "t3"."title", "t3"."imdb_index", "t3"."kind_id", "t3"."production_year", "t3"."phonetic_code", "t3"."episode_of_id", "t3"."season_nr", "t3"."episode_nr", "t3"."note", "t3"."md5sum", "t3"."id0", "t3"."movie_id0", "t3"."keyword_id", "t3"."id1", "t3"."keyword", "t3"."phonetic_code0", "movie_companies"."id" AS "id2", "movie_companies"."movie_id" AS "movie_id1", "movie_companies"."company_id", "movie_companies"."company_type_id", "movie_companies"."note" AS "note0"
FROM "IMDB"."movie_companies"
RIGHT JOIN (SELECT "s1"."id", "s1"."movie_id", "s1"."title", "s1"."imdb_index", "s1"."kind_id", "s1"."production_year", "s1"."phonetic_code", "s1"."episode_of_id", "s1"."season_nr", "s1"."episode_nr", "s1"."note", "s1"."md5sum", "s1"."id0", "s1"."movie_id0", "s1"."keyword_id", CAST("keyword"."id" AS INTEGER) AS "id1", CAST("keyword"."keyword" AS VARCHAR CHARACTER SET "ISO-8859-1") AS "keyword", CAST("keyword"."phonetic_code" AS VARCHAR CHARACTER SET "ISO-8859-1") AS "phonetic_code0"
FROM "IMDB"."keyword"
INNER JOIN "s1" ON "keyword"."id" = "s1"."keyword_id") AS "t3" ON "movie_companies"."movie_id" = "t3"."id") AS "t4"
LEFT JOIN "IMDB"."company_name" ON "t4"."company_id" = "company_name"."id"
LEFT JOIN "IMDB"."company_type" ON "t4"."company_type_id" = "company_type"."id") AS "t5" ON "t2"."MOVIE_ID" = "t5"."MOVIE_ID"
GROUP BY "t5"."MOVIE_ID", "t5"."TITLE", "t5"."PRODUCTION_YEAR"
ORDER BY "t5"."PRODUCTION_YEAR" DESC NULLS FIRST, "t5"."TITLE"