SELECT COALESCE("ACTOR_NAME", "ACTOR_NAME") AS "ACTOR_NAME", "TOTAL_MOVIES", "MOVIES_LIST", "AVERAGE_RATING", "MOVIE_KEYWORDS"
FROM (SELECT "ACTOR_NAME", "TOTAL_MOVIES", "MOVIES_LIST", CASE WHEN "FD_COL_4" IS NOT NULL THEN CAST("FD_COL_4" AS DECIMAL(19, 0)) ELSE 0 END AS "AVERAGE_RATING", "MOVIE_KEYWORDS"
FROM "s1"
WHERE "TOTAL_MOVIES" > 5
ORDER BY "TOTAL_MOVIES" DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY) AS "t10"