SELECT COALESCE("t4"."MOVIE_ID", "t4"."MOVIE_ID") AS "MOVIE_ID", "t4"."TITLE", "t4"."PRODUCTION_YEAR", LISTAGG(DISTINCT "t4"."ACTOR_NAME" || ' (' || "t4"."ROLE_NAME" || ')', ', ') AS "ACTORS", LISTAGG(DISTINCT "t2"."COMPANY_NAME" || ' (' || "t2"."COMPANY_TYPE" || ')', ', ') AS "PRODUCTION_COMPANIES", LISTAGG(DISTINCT "t4"."KEYWORD", ', ') AS "KEYWORDS"
FROM (SELECT "movie_companies"."movie_id" AS "MOVIE_ID", "company_name"."name" AS "COMPANY_NAME", "company_type"."kind" AS "COMPANY_TYPE"
FROM "IMDB"."company_type"
INNER JOIN ("IMDB"."company_name" INNER JOIN "IMDB"."movie_companies" ON "company_name"."id" = "movie_companies"."company_id") ON "company_type"."id" = "movie_companies"."company_type_id") AS "t2"
RIGHT JOIN (SELECT "s1"."MOVIE_ID", "s1"."TITLE", "s1"."PRODUCTION_YEAR", "s1"."KEYWORD", "s1"."KEYWORD_RANK", "t3"."MOVIE_ID" AS "MOVIE_ID0", "t3"."ACTOR_NAME", "t3"."ROLE_NAME"
FROM (SELECT "cast_info"."movie_id" AS "MOVIE_ID", "aka_name"."name" AS "ACTOR_NAME", "role_type"."role" AS "ROLE_NAME"
FROM "IMDB"."role_type"
INNER JOIN ("IMDB"."aka_name" INNER JOIN "IMDB"."cast_info" ON "aka_name"."person_id" = "cast_info"."person_id") ON "role_type"."id" = "cast_info"."role_id") AS "t3"
RIGHT JOIN "s1" ON "t3"."MOVIE_ID" = "s1"."MOVIE_ID") AS "t4" ON "t2"."MOVIE_ID" = "t4"."MOVIE_ID"
GROUP BY "t4"."MOVIE_ID", "t4"."TITLE", "t4"."PRODUCTION_YEAR"
ORDER BY "t4"."PRODUCTION_YEAR" DESC NULLS FIRST, "t4"."TITLE"