SELECT COALESCE("t14"."MOVIE_ID", "t14"."MOVIE_ID") AS "MOVIE_ID", "t14"."TITLE", "t14"."PRODUCTION_YEAR", "t14"."KEYWORD", "t14"."NUM_CAST_MEMBERS", "t14"."CAST_NAMES"
FROM (SELECT "t12"."MOVIE_ID", "t12"."TITLE", "t12"."PRODUCTION_YEAR", "t12"."KEYWORD", "t12"."NUM_CAST_MEMBERS", "t12"."CAST_NAMES"
FROM (SELECT "KEYWORD"
FROM "s1"
ORDER BY "MOVIE_COUNT" DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY) AS "t7"
INNER JOIN (SELECT ANY_VALUE("t9"."id") AS "MOVIE_ID", "t9"."title" AS "TITLE", "t9"."production_year" AS "PRODUCTION_YEAR", ANY_VALUE("t9"."keyword") AS "KEYWORD", COUNT(DISTINCT "t9"."person_id") AS "NUM_CAST_MEMBERS", CASE WHEN LISTAGG(DISTINCT "aka_name0"."name", ', ') IS NOT NULL THEN CAST(LISTAGG(DISTINCT "aka_name0"."name", ', ') AS VARCHAR CHARACTER SET "ISO-8859-1") ELSE 'No Cast' END AS "CAST_NAMES"
FROM (SELECT "t8"."id", "t8"."movie_id", "t8"."title", "t8"."imdb_index", "t8"."kind_id", "t8"."production_year", "t8"."phonetic_code", "t8"."episode_of_id", "t8"."season_nr", "t8"."episode_nr", "t8"."note", "t8"."md5sum", "t8"."id0", "t8"."movie_id0", "t8"."keyword_id", "keyword0"."id" AS "id1", "keyword0"."keyword", "keyword0"."phonetic_code" AS "phonetic_code0", "cast_info0"."id" AS "id2", "cast_info0"."person_id", "cast_info0"."movie_id" AS "movie_id1", "cast_info0"."person_role_id", "cast_info0"."note" AS "note0", "cast_info0"."nr_order", "cast_info0"."role_id"
FROM "IMDB"."cast_info" AS "cast_info0"
RIGHT JOIN ((SELECT "aka_title0"."id", "aka_title0"."movie_id", "aka_title0"."title", "aka_title0"."imdb_index", "aka_title0"."kind_id", "aka_title0"."production_year", "aka_title0"."phonetic_code", "aka_title0"."episode_of_id", "aka_title0"."season_nr", "aka_title0"."episode_nr", "aka_title0"."note", "aka_title0"."md5sum", "movie_keyword0"."id" AS "id0", "movie_keyword0"."movie_id" AS "movie_id0", "movie_keyword0"."keyword_id"
FROM "IMDB"."movie_keyword" AS "movie_keyword0"
RIGHT JOIN "IMDB"."aka_title" AS "aka_title0" ON "movie_keyword0"."movie_id" = "aka_title0"."id") AS "t8" LEFT JOIN "IMDB"."keyword" AS "keyword0" ON "t8"."keyword_id" = "keyword0"."id") ON "cast_info0"."movie_id" = "t8"."id") AS "t9"
LEFT JOIN "IMDB"."aka_name" AS "aka_name0" ON "t9"."person_id" = "aka_name0"."person_id"
GROUP BY "t9"."id", "t9"."title", "t9"."production_year", "t9"."keyword") AS "t12" ON "t7"."KEYWORD" = "t12"."KEYWORD"
ORDER BY "t12"."PRODUCTION_YEAR" DESC NULLS FIRST, "t12"."NUM_CAST_MEMBERS" DESC NULLS FIRST) AS "t14"