SELECT COALESCE("t9"."MOVIE_TITLE", "t9"."MOVIE_TITLE") AS "MOVIE_TITLE", "t9"."PRODUCTION_YEAR", "t9"."CAST_COUNT", "t9"."CAST_NAMES", "t9"."COMPANY_COUNT", "t9"."COMPANY_NAMES"
FROM (SELECT "s1"."MOVIE_TITLE", "s1"."PRODUCTION_YEAR", "s1"."CAST_COUNT", "s1"."CAST_NAMES", "t7"."COMPANY_COUNT", "t7"."COMPANY_NAMES"
FROM "s1"
LEFT JOIN (SELECT "s10"."MOVIE_ID", COUNT(DISTINCT "movie_companies"."company_id") AS "COMPANY_COUNT", LISTAGG(DISTINCT "company_name"."name", ', ') AS "COMPANY_NAMES"
FROM "IMDB"."company_name"
INNER JOIN "IMDB"."movie_companies" ON "company_name"."id" = "movie_companies"."company_id"
INNER JOIN "s1" AS "s10" ON "movie_companies"."movie_id" = "s10"."MOVIE_ID"
GROUP BY "s10"."MOVIE_ID") AS "t7" ON "s1"."MOVIE_ID" = "t7"."MOVIE_ID"
ORDER BY "s1"."PRODUCTION_YEAR" DESC NULLS FIRST, "s1"."CAST_COUNT" DESC NULLS FIRST) AS "t9"