SELECT COALESCE("t3"."MOVIE_ID", "t3"."MOVIE_ID") AS "MOVIE_ID", "t3"."MOVIE_TITLE", "t3"."PRODUCTION_YEAR", "t3"."KIND_ID", "t3"."NUM_CAST_MEMBERS", "t3"."ALL_AKA_NAMES", "t3"."id", "t3"."movie_id" AS "movie_id_", "t3"."subject_id", "t3"."status_id", "role_type"."id" AS "id0", "role_type"."role"
FROM (SELECT "t2"."MOVIE_ID", "t2"."MOVIE_TITLE", "t2"."PRODUCTION_YEAR", "t2"."KIND_ID", "t2"."NUM_CAST_MEMBERS", "t2"."ALL_AKA_NAMES", "complete_cast"."id", "complete_cast"."movie_id", "complete_cast"."subject_id", "complete_cast"."status_id"
FROM "IMDB"."complete_cast"
RIGHT JOIN (SELECT ANY_VALUE("t"."id") AS "MOVIE_ID", ANY_VALUE("t"."title") AS "MOVIE_TITLE", "t"."production_year" AS "PRODUCTION_YEAR", "t"."kind_id" AS "KIND_ID", COUNT("t"."person_id") AS "NUM_CAST_MEMBERS", LISTAGG(DISTINCT "aka_name"."name", ', ') AS "ALL_AKA_NAMES"
FROM (SELECT "aka_title"."id", "aka_title"."movie_id", "aka_title"."title", "aka_title"."imdb_index", "aka_title"."kind_id", "aka_title"."production_year", "aka_title"."phonetic_code", "aka_title"."episode_of_id", "aka_title"."season_nr", "aka_title"."episode_nr", "aka_title"."note", "aka_title"."md5sum", "cast_info"."id" AS "id0", "cast_info"."person_id", "cast_info"."movie_id" AS "movie_id0", "cast_info"."person_role_id", "cast_info"."note" AS "note0", "cast_info"."nr_order", "cast_info"."role_id"
FROM "IMDB"."cast_info"
RIGHT JOIN "IMDB"."aka_title" ON "cast_info"."movie_id" = "aka_title"."movie_id") AS "t"
LEFT JOIN "IMDB"."aka_name" ON "t"."person_id" = "aka_name"."person_id"
GROUP BY "t"."id", "t"."title", "t"."production_year", "t"."kind_id") AS "t2" ON "complete_cast"."movie_id" = "t2"."MOVIE_ID") AS "t3"
LEFT JOIN "IMDB"."role_type" ON "t3"."status_id" = "role_type"."id"