SELECT COALESCE("t15"."MOVIE_ID", "t15"."MOVIE_ID") AS "MOVIE_ID", "t15"."MOVIE_TITLE", "t15"."PRODUCTION_YEAR", "t15"."LEADING_ROLE", "t15"."PRODUCTION_COMPANIES", "t15"."NUM_CAST_MEMBERS", "t15"."MOVIE_KEYWORDS", "t15"."ALL_AKA_NAMES"
FROM (SELECT "t13"."MOVIE_ID", "t13"."MOVIE_TITLE", "t13"."PRODUCTION_YEAR", "t13"."LEADING_ROLE", "t13"."PRODUCTION_COMPANIES", "t8"."NUM_CAST_MEMBERS", "t13"."MOVIE_KEYWORDS", "t8"."ALL_AKA_NAMES"
FROM (SELECT ANY_VALUE("t5"."id") AS "MOVIE_ID", ANY_VALUE("t5"."title") AS "MOVIE_TITLE", "t5"."production_year" AS "PRODUCTION_YEAR", "t5"."kind_id" AS "KIND_ID", COUNT("t5"."person_id") AS "NUM_CAST_MEMBERS", LISTAGG(DISTINCT "aka_name0"."name", ', ') AS "ALL_AKA_NAMES"
FROM (SELECT "aka_title0"."id", "aka_title0"."movie_id", "aka_title0"."title", "aka_title0"."imdb_index", "aka_title0"."kind_id", "aka_title0"."production_year", "aka_title0"."phonetic_code", "aka_title0"."episode_of_id", "aka_title0"."season_nr", "aka_title0"."episode_nr", "aka_title0"."note", "aka_title0"."md5sum", "cast_info0"."id" AS "id0", "cast_info0"."person_id", "cast_info0"."movie_id" AS "movie_id0", "cast_info0"."person_role_id", "cast_info0"."note" AS "note0", "cast_info0"."nr_order", "cast_info0"."role_id"
FROM "IMDB"."cast_info" AS "cast_info0"
RIGHT JOIN "IMDB"."aka_title" AS "aka_title0" ON "cast_info0"."movie_id" = "aka_title0"."movie_id") AS "t5"
LEFT JOIN "IMDB"."aka_name" AS "aka_name0" ON "t5"."person_id" = "aka_name0"."person_id"
GROUP BY "t5"."id", "t5"."title", "t5"."production_year", "t5"."kind_id") AS "t8"
INNER JOIN (SELECT "t10"."MOVIE_ID", "t10"."MOVIE_TITLE", "t10"."PRODUCTION_YEAR", ANY_VALUE("t10"."role") AS "LEADING_ROLE", COUNT("t10"."company_id") AS "PRODUCTION_COMPANIES", LISTAGG(DISTINCT "keyword"."keyword", ', ') AS "MOVIE_KEYWORDS"
FROM "IMDB"."keyword"
RIGHT JOIN (SELECT "t9"."MOVIE_ID", "t9"."MOVIE_TITLE", "t9"."PRODUCTION_YEAR", "t9"."KIND_ID", "t9"."NUM_CAST_MEMBERS", "t9"."ALL_AKA_NAMES", "t9"."id", "t9"."movie_id", "t9"."subject_id", "t9"."status_id", "t9"."id0", "t9"."role", "t9"."id1", "t9"."movie_id0", "t9"."company_id", "t9"."company_type_id", "t9"."note", "movie_keyword"."id" AS "id2", "movie_keyword"."movie_id" AS "movie_id1", "movie_keyword"."keyword_id"
FROM "IMDB"."movie_keyword"
RIGHT JOIN (SELECT "s1"."MOVIE_ID", "s1"."MOVIE_TITLE", "s1"."PRODUCTION_YEAR", "s1"."KIND_ID", "s1"."NUM_CAST_MEMBERS", "s1"."ALL_AKA_NAMES", "s1"."id", "s1"."movie_id_" AS "movie_id", "s1"."subject_id", "s1"."status_id", "s1"."id0", "s1"."role", "movie_companies"."id" AS "id1", "movie_companies"."movie_id" AS "movie_id0", "movie_companies"."company_id", "movie_companies"."company_type_id", "movie_companies"."note"
FROM "IMDB"."movie_companies"
RIGHT JOIN "s1" ON "movie_companies"."movie_id" = "s1"."MOVIE_ID") AS "t9" ON "movie_keyword"."movie_id" = "t9"."MOVIE_ID") AS "t10" ON "keyword"."id" = "t10"."keyword_id"
GROUP BY "t10"."MOVIE_ID", "t10"."MOVIE_TITLE", "t10"."PRODUCTION_YEAR", "t10"."role") AS "t13" ON "t8"."MOVIE_ID" = "t13"."MOVIE_ID"
ORDER BY "t13"."PRODUCTION_YEAR" DESC NULLS FIRST, "t8"."NUM_CAST_MEMBERS" DESC NULLS FIRST) AS "t15"