SELECT COALESCE("t12"."TITLE", "t12"."TITLE") AS "TITLE", "t12"."PRODUCTION_YEAR", "t12"."ACTOR_COUNT", "t12"."TITLE_SLUG", "t12"."ACTORS"
FROM (SELECT "t7"."TITLE", "t7"."PRODUCTION_YEAR", CASE WHEN "t7"."ACTOR_COUNT" IS NOT NULL THEN CAST("t7"."ACTOR_COUNT" AS BIGINT) ELSE 0 END AS "ACTOR_COUNT", REPLACE("t7"."TITLE", ' ', '-') AS "TITLE_SLUG", "t9"."EXPR$0" AS "ACTORS"
FROM (SELECT "t6"."MOVIE_ID", "t6"."TITLE", "t6"."PRODUCTION_YEAR", CAST("s1"."ACTOR_COUNT" AS BIGINT) AS "ACTOR_COUNT"
FROM "s1"
INNER JOIN (SELECT "aka_title"."id" AS "MOVIE_ID", "aka_title"."title" AS "TITLE", "aka_title"."production_year" AS "PRODUCTION_YEAR", ROW_NUMBER() OVER (PARTITION BY "aka_title"."production_year" ORDER BY "aka_title"."id") AS "RN"
FROM (SELECT SINGLE_VALUE("id") AS "$f0"
FROM "IMDB"."kind_type"
WHERE "kind" = 'movie') AS "t5"
INNER JOIN "IMDB"."aka_title" ON "t5"."$f0" = "aka_title"."kind_id") AS "t6" ON "s1"."movie_id" = "t6"."MOVIE_ID") AS "t7"
LEFT JOIN (SELECT "cast_info0"."movie_id", LISTAGG(DISTINCT CONCAT("aka_name"."name", ' (', CAST("cast_info0"."role_id" AS VARCHAR CHARACTER SET "ISO-8859-1"), ')'), ', ') AS "EXPR$0"
FROM "IMDB"."cast_info" AS "cast_info0"
INNER JOIN "IMDB"."aka_name" ON "cast_info0"."person_id" = "aka_name"."person_id"
GROUP BY "cast_info0"."movie_id") AS "t9" ON "t7"."MOVIE_ID" = "t9"."movie_id"
ORDER BY "t7"."PRODUCTION_YEAR" DESC NULLS FIRST, "t7"."TITLE") AS "t12"