SELECT COALESCE("t7"."MOVIE_ID", "t7"."MOVIE_ID") AS "MOVIE_ID", "t7"."MOVIE_TITLE", "t7"."PRODUCTION_YEAR", "t7"."CAST_COUNT", "t7"."CAST_NAMES", "t7"."KEYWORDS", LISTAGG(DISTINCT "company_name"."name", ', ') AS "COMPANIES"
FROM "IMDB"."company_name"
RIGHT JOIN (SELECT "t6"."MOVIE_ID", "t6"."MOVIE_TITLE", "t6"."PRODUCTION_YEAR", "t6"."CAST_COUNT", "t6"."CAST_NAMES", "t6"."KEYWORDS", "movie_companies"."id", "movie_companies"."movie_id", "movie_companies"."company_id", "movie_companies"."company_type_id", "movie_companies"."note"
FROM "IMDB"."movie_companies"
RIGHT JOIN (SELECT "t4"."MOVIE_ID", "t4"."MOVIE_TITLE", "t4"."PRODUCTION_YEAR", "t4"."CAST_COUNT", "t4"."CAST_NAMES", LISTAGG(DISTINCT "keyword"."keyword", ', ') AS "KEYWORDS"
FROM "IMDB"."keyword"
RIGHT JOIN (SELECT "t3"."MOVIE_ID", "t3"."MOVIE_TITLE", "t3"."PRODUCTION_YEAR", "t3"."CAST_COUNT", "t3"."CAST_NAMES", "movie_keyword"."id", "movie_keyword"."movie_id", "movie_keyword"."keyword_id"
FROM "IMDB"."movie_keyword"
RIGHT JOIN (SELECT ANY_VALUE("s1"."id") AS "MOVIE_ID", ANY_VALUE("s1"."title") AS "MOVIE_TITLE", "s1"."production_year" AS "PRODUCTION_YEAR", COUNT(DISTINCT "cast_info"."person_id") AS "CAST_COUNT", LISTAGG(DISTINCT "aka_name"."name", ', ') AS "CAST_NAMES"
FROM "s1"
INNER JOIN ("IMDB"."aka_name" INNER JOIN "IMDB"."cast_info" ON "aka_name"."person_id" = "cast_info"."person_id") ON "s1"."id" = "cast_info"."movie_id"
GROUP BY "s1"."id", "s1"."title", "s1"."production_year") AS "t3" ON "movie_keyword"."movie_id" = "t3"."MOVIE_ID") AS "t4" ON "keyword"."id" = "t4"."keyword_id"
GROUP BY "t4"."MOVIE_ID", "t4"."MOVIE_TITLE", "t4"."PRODUCTION_YEAR", "t4"."CAST_COUNT", "t4"."CAST_NAMES") AS "t6" ON "movie_companies"."movie_id" = "t6"."MOVIE_ID") AS "t7" ON "company_name"."id" = "t7"."company_id"
GROUP BY "t7"."MOVIE_ID", "t7"."MOVIE_TITLE", "t7"."PRODUCTION_YEAR", "t7"."CAST_COUNT", "t7"."CAST_NAMES", "t7"."KEYWORDS"
ORDER BY "t7"."PRODUCTION_YEAR" DESC NULLS FIRST, "t7"."CAST_COUNT" DESC NULLS FIRST