SELECT COALESCE("t7"."MOVIE_ID", "t7"."MOVIE_ID") AS "MOVIE_ID", "t7"."MOVIE_TITLE", "t7"."MOVIE_KEYWORD", "t7"."LEAD_ACTOR", "t7"."ACTOR_ROLE", "t7"."COMPANY_NAME", "t7"."COMPANY_TYPE"
FROM (SELECT "t5"."MOVIE_ID", "t5"."TITLE" AS "MOVIE_TITLE", "t5"."KEYWORD" AS "MOVIE_KEYWORD", "t1"."ACTOR_NAME" AS "LEAD_ACTOR", "t1"."ROLE_NAME" AS "ACTOR_ROLE", "t2"."COMPANY_NAME", "t2"."COMPANY_TYPE"
FROM (SELECT "title"."id" AS "MOVIE_ID", "title"."title" AS "TITLE", "s1"."name" AS "ACTOR_NAME", "role_type"."role" AS "ROLE_NAME"
FROM "IMDB"."role_type"
INNER JOIN ("IMDB"."complete_cast" INNER JOIN "IMDB"."title" ON "complete_cast"."movie_id" = "title"."id" INNER JOIN "s1" ON "complete_cast"."subject_id" = "s1"."person_id0") ON "role_type"."id" = "s1"."role_id"
WHERE "role_type"."role" = 'lead') AS "t1"
INNER JOIN ((SELECT "movie_companies"."movie_id" AS "MOVIE_ID", "company_name"."name" AS "COMPANY_NAME", "company_type"."kind" AS "COMPANY_TYPE"
FROM "IMDB"."company_type"
INNER JOIN ("IMDB"."company_name" INNER JOIN "IMDB"."movie_companies" ON "company_name"."id" = "movie_companies"."company_id") ON "company_type"."id" = "movie_companies"."company_type_id") AS "t2" INNER JOIN (SELECT "t3"."id" AS "MOVIE_ID", "t3"."title" AS "TITLE", CAST("t4"."keyword" AS VARCHAR CHARACTER SET "ISO-8859-1") AS "KEYWORD"
FROM (SELECT "title0"."id", "title0"."title", "title0"."imdb_index", "title0"."kind_id", "title0"."production_year", "title0"."imdb_id", "title0"."phonetic_code", "title0"."episode_of_id", "title0"."season_nr", "title0"."episode_nr", "title0"."series_years", "title0"."md5sum", "movie_keyword"."id" AS "id0", "movie_keyword"."movie_id", "movie_keyword"."keyword_id"
FROM "IMDB"."movie_keyword"
RIGHT JOIN "IMDB"."title" AS "title0" ON "movie_keyword"."movie_id" = "title0"."id") AS "t3"
INNER JOIN (SELECT *
FROM "IMDB"."keyword"
WHERE "keyword" LIKE '%action%') AS "t4" ON "t3"."keyword_id" = "t4"."id") AS "t5" ON "t2"."MOVIE_ID" = "t5"."MOVIE_ID") ON "t1"."MOVIE_ID" = "t5"."MOVIE_ID"
ORDER BY "t5"."MOVIE_ID") AS "t7"