SELECT COALESCE("t8"."MOVIE_ID", "t8"."MOVIE_ID") AS "MOVIE_ID", "t8"."MOVIE_TITLE", "t8"."PRODUCTION_YEAR", "t8"."ACTOR_NAME", "t8"."ACTOR_IMDB_INDEX", "t8"."COMPANY_NAMES", "t8"."COMPANY_TYPES", "t8"."KEYWORDS"
FROM (SELECT "t6"."MOVIE_ID", "t6"."MOVIE_TITLE", "t6"."PRODUCTION_YEAR", "t6"."ACTOR_NAME", "t6"."ACTOR_IMDB_INDEX", "s1"."COMPANY_NAMES", "s1"."COMPANY_TYPES", "t6"."KEYWORDS"
FROM "s1"
INNER JOIN (SELECT ANY_VALUE("t3"."id") AS "MOVIE_ID", ANY_VALUE("t3"."title") AS "MOVIE_TITLE", "t3"."production_year" AS "PRODUCTION_YEAR", ANY_VALUE("t3"."name") AS "ACTOR_NAME", ANY_VALUE("t3"."imdb_index0") AS "ACTOR_IMDB_INDEX", LISTAGG(DISTINCT "keyword"."keyword", ', ') AS "KEYWORDS"
FROM (SELECT "t2"."id", "t2"."movie_id", "t2"."title", "t2"."imdb_index", "t2"."kind_id", "t2"."production_year", "t2"."phonetic_code", "t2"."episode_of_id", "t2"."season_nr", "t2"."episode_nr", "t2"."note", "t2"."md5sum", "cast_info"."id" AS "id0", "cast_info"."person_id", "cast_info"."movie_id" AS "movie_id0", "cast_info"."person_role_id", "cast_info"."note" AS "note0", "cast_info"."nr_order", "cast_info"."role_id", "aka_name"."id" AS "id1", "aka_name"."person_id" AS "person_id0", "aka_name"."name", "aka_name"."imdb_index" AS "imdb_index0", "aka_name"."name_pcode_cf", "aka_name"."name_pcode_nf", "aka_name"."surname_pcode", "aka_name"."md5sum" AS "md5sum0", "movie_keyword"."id" AS "id2", "movie_keyword"."movie_id" AS "movie_id1", "movie_keyword"."keyword_id"
FROM "IMDB"."cast_info"
INNER JOIN ("IMDB"."movie_keyword" RIGHT JOIN (SELECT *
FROM "IMDB"."aka_title"
WHERE "production_year" >= 2000) AS "t2" ON "movie_keyword"."movie_id" = "t2"."id") ON "cast_info"."movie_id" = "t2"."id"
INNER JOIN "IMDB"."aka_name" ON "cast_info"."person_id" = "aka_name"."person_id") AS "t3"
LEFT JOIN "IMDB"."keyword" ON "t3"."keyword_id" = "keyword"."id"
GROUP BY "t3"."id", "t3"."title", "t3"."production_year", "t3"."name", "t3"."imdb_index0") AS "t6" ON "s1"."MOVIE_ID" = "t6"."MOVIE_ID"
ORDER BY "t6"."PRODUCTION_YEAR" DESC NULLS FIRST, "t6"."MOVIE_TITLE"
FETCH NEXT 100 ROWS ONLY) AS "t8"