SELECT COALESCE("t10"."MOVIE_ID", "t10"."MOVIE_ID") AS "MOVIE_ID", "t10"."TITLE", "t10"."PRODUCTION_YEAR", "t10"."TOTAL_COMPANIES", "t10"."COMPANY_NAMES", "t10"."TOTAL_KEYWORDS", "t10"."KEYWORDS", "t10"."PERSON_ID", "t10"."ACTOR_NAME", "t10"."TOTAL_MOVIES", "t10"."MOVIES"
FROM (SELECT "t8"."MOVIE_ID", "t8"."TITLE", "t8"."PRODUCTION_YEAR", "t8"."TOTAL_COMPANIES", "t8"."COMPANY_NAMES", "t8"."TOTAL_KEYWORDS", "t8"."KEYWORDS", "t1"."PERSON_ID", "t1"."NAME" AS "ACTOR_NAME", "t1"."TOTAL_MOVIES", "t1"."MOVIES"
FROM (SELECT "PERSON_ID", "NAME", COUNT(DISTINCT "movie_id") AS "TOTAL_MOVIES", LISTAGG(DISTINCT "title", "FD_COL_4") AS "MOVIES"
FROM "s1"
GROUP BY "PERSON_ID", "NAME") AS "t1"
INNER JOIN "IMDB"."cast_info" AS "cast_info0" ON "t1"."PERSON_ID" = "cast_info0"."person_id"
INNER JOIN (SELECT ANY_VALUE("t5"."id") AS "MOVIE_ID", "t5"."title" AS "TITLE", "t5"."production_year" AS "PRODUCTION_YEAR", COUNT(DISTINCT "t5"."company_id") AS "TOTAL_COMPANIES", LISTAGG(DISTINCT "t5"."name", ', ') AS "COMPANY_NAMES", COUNT(DISTINCT "t5"."keyword_id") AS "TOTAL_KEYWORDS", LISTAGG(DISTINCT "keyword"."keyword", ', ') AS "KEYWORDS"
FROM (SELECT "t4"."id", "t4"."movie_id", "t4"."title", "t4"."imdb_index", "t4"."kind_id", "t4"."production_year", "t4"."phonetic_code", "t4"."episode_of_id", "t4"."season_nr", "t4"."episode_nr", "t4"."note", "t4"."md5sum", "t4"."id0", "t4"."movie_id0", "t4"."company_id", "t4"."company_type_id", "t4"."note0", "t4"."id1", "t4"."name", "t4"."country_code", "t4"."imdb_id", "t4"."name_pcode_nf", "t4"."name_pcode_sf", "t4"."md5sum0", "movie_keyword"."id" AS "id2", "movie_keyword"."movie_id" AS "movie_id1", "movie_keyword"."keyword_id"
FROM "IMDB"."movie_keyword"
RIGHT JOIN (SELECT "t3"."id", "t3"."movie_id", "t3"."title", "t3"."imdb_index", "t3"."kind_id", "t3"."production_year", "t3"."phonetic_code", "t3"."episode_of_id", "t3"."season_nr", "t3"."episode_nr", "t3"."note", "t3"."md5sum", "t3"."id0", "t3"."movie_id0", "t3"."company_id", "t3"."company_type_id", "t3"."note0", "company_name"."id" AS "id1", "company_name"."name", "company_name"."country_code", "company_name"."imdb_id", "company_name"."name_pcode_nf", "company_name"."name_pcode_sf", "company_name"."md5sum" AS "md5sum0"
FROM "IMDB"."company_name"
RIGHT JOIN (SELECT "t2"."id", "t2"."movie_id", "t2"."title", "t2"."imdb_index", "t2"."kind_id", "t2"."production_year", "t2"."phonetic_code", "t2"."episode_of_id", "t2"."season_nr", "t2"."episode_nr", "t2"."note", "t2"."md5sum", "movie_companies"."id" AS "id0", "movie_companies"."movie_id" AS "movie_id0", "movie_companies"."company_id", "movie_companies"."company_type_id", "movie_companies"."note" AS "note0"
FROM "IMDB"."movie_companies"
RIGHT JOIN (SELECT *
FROM "IMDB"."aka_title"
WHERE "production_year" >= 2000 AND "production_year" <= 2023) AS "t2" ON "movie_companies"."movie_id" = "t2"."id") AS "t3" ON "company_name"."id" = "t3"."company_id") AS "t4" ON "movie_keyword"."movie_id" = "t4"."id") AS "t5"
LEFT JOIN "IMDB"."keyword" ON "t5"."keyword_id" = "keyword"."id"
GROUP BY "t5"."id", "t5"."title", "t5"."production_year") AS "t8" ON "cast_info0"."movie_id" = "t8"."MOVIE_ID"
ORDER BY "t8"."PRODUCTION_YEAR" DESC NULLS FIRST, "t8"."TITLE") AS "t10"