SELECT COALESCE("t0"."MOVIE_ID", "t0"."MOVIE_ID") AS "MOVIE_ID", "t0"."ROLE_NAMES", "t8"."MOVIE_ID" AS "MOVIE_ID0", "t8"."TITLE", "t8"."PRODUCTION_YEAR", "t8"."CAST_COUNT", "t8"."CAST_NAMES", "t8"."KEYWORDS"
FROM (SELECT "cast_info"."movie_id" AS "MOVIE_ID", LISTAGG(DISTINCT "role_type"."role", ', ') AS "ROLE_NAMES"
FROM "IMDB"."role_type"
INNER JOIN "IMDB"."cast_info" ON "role_type"."id" = "cast_info"."role_id"
GROUP BY "cast_info"."movie_id") AS "t0"
RIGHT JOIN (SELECT "t5"."MOVIE_ID", "t5"."TITLE", "t5"."PRODUCTION_YEAR", "t5"."CAST_COUNT", "t5"."CAST_NAMES", CASE WHEN LISTAGG(DISTINCT "keyword"."keyword", ', ') IS NOT NULL THEN CAST(LISTAGG(DISTINCT "keyword"."keyword", ', ') AS VARCHAR CHARACTER SET "ISO-8859-1") ELSE 'No Keywords' END AS "KEYWORDS"
FROM "IMDB"."keyword"
RIGHT JOIN (SELECT "t4"."MOVIE_ID", "t4"."TITLE", "t4"."PRODUCTION_YEAR", "t4"."CAST_COUNT", "t4"."CAST_NAMES", "movie_keyword"."id", "movie_keyword"."movie_id", "movie_keyword"."keyword_id"
FROM "IMDB"."movie_keyword"
RIGHT JOIN (SELECT ANY_VALUE("t1"."id") AS "MOVIE_ID", "t1"."title" AS "TITLE", "t1"."production_year" AS "PRODUCTION_YEAR", COUNT(DISTINCT "cast_info0"."person_id") AS "CAST_COUNT", LISTAGG(DISTINCT "aka_name"."name", ', ') AS "CAST_NAMES"
FROM (SELECT *
FROM "IMDB"."aka_title"
WHERE "production_year" >= 2000) AS "t1"
INNER JOIN ("IMDB"."aka_name" INNER JOIN "IMDB"."cast_info" AS "cast_info0" ON "aka_name"."person_id" = "cast_info0"."person_id") ON "t1"."id" = "cast_info0"."movie_id"
GROUP BY "t1"."id", "t1"."title", "t1"."production_year") AS "t4" ON "movie_keyword"."movie_id" = "t4"."MOVIE_ID") AS "t5" ON "keyword"."id" = "t5"."keyword_id"
GROUP BY "t5"."MOVIE_ID", "t5"."TITLE", "t5"."PRODUCTION_YEAR", "t5"."CAST_COUNT", "t5"."CAST_NAMES") AS "t8" ON "t0"."MOVIE_ID" = "t8"."MOVIE_ID"