SELECT COALESCE("MOVIE_ID", "MOVIE_ID") AS "MOVIE_ID", "TITLE", "PRODUCTION_YEAR", "CAST_COUNT", "CAST_NAMES", "KEYWORDS", "ACTOR_ROLES"
FROM (SELECT "MOVIE_ID0" AS "MOVIE_ID", "TITLE", "PRODUCTION_YEAR", "CAST_COUNT", "CAST_NAMES", "KEYWORDS", CASE WHEN "ROLE_NAMES" IS NOT NULL THEN CAST("ROLE_NAMES" AS VARCHAR CHARACTER SET "ISO-8859-1") ELSE 'No Roles' END AS "ACTOR_ROLES"
FROM "s1"
ORDER BY "PRODUCTION_YEAR" DESC NULLS FIRST, "CAST_COUNT" DESC NULLS FIRST
FETCH NEXT 50 ROWS ONLY) AS "t11"