SELECT COALESCE("t9"."MOVIE_ID", "t9"."MOVIE_ID") AS "MOVIE_ID", "t9"."MOVIE_TITLE", "t9"."PRODUCTION_YEAR", "t9"."COMPANIES", "t9"."KEYWORDS", "t9"."CAST_NAMES", "t9"."ROLES"
FROM (SELECT "t7"."MOVIE_ID", "t7"."MOVIE_TITLE", "t7"."PRODUCTION_YEAR", "t7"."COMPANIES", "t7"."KEYWORDS", "t1"."CAST_NAMES", "t1"."ROLES"
FROM (SELECT "s1"."movie_id" AS "MOVIE_ID", LISTAGG(DISTINCT "s1"."name", ', ') AS "CAST_NAMES", LISTAGG(DISTINCT "role_type"."role", ', ') AS "ROLES"
FROM "s1"
LEFT JOIN "IMDB"."role_type" ON "s1"."role_id" = "role_type"."id"
GROUP BY "s1"."movie_id") AS "t1"
RIGHT JOIN (SELECT ANY_VALUE("t3"."id") AS "MOVIE_ID", ANY_VALUE("t3"."title") AS "MOVIE_TITLE", "t3"."production_year" AS "PRODUCTION_YEAR", LISTAGG(DISTINCT "t3"."name", ', ') AS "COMPANIES", LISTAGG(DISTINCT "keyword"."keyword", ', ') AS "KEYWORDS"
FROM (SELECT "t2"."id", "t2"."movie_id", "t2"."title", "t2"."imdb_index", "t2"."kind_id", "t2"."production_year", "t2"."phonetic_code", "t2"."episode_of_id", "t2"."season_nr", "t2"."episode_nr", "t2"."note", "t2"."md5sum", "t2"."id0", "t2"."movie_id0", "t2"."company_id", "t2"."company_type_id", "t2"."note0", "company_name"."id" AS "id1", "company_name"."name", "company_name"."country_code", "company_name"."imdb_id", "company_name"."name_pcode_nf", "company_name"."name_pcode_sf", "company_name"."md5sum" AS "md5sum0", "movie_keyword"."id" AS "id2", "movie_keyword"."movie_id" AS "movie_id1", "movie_keyword"."keyword_id"
FROM "IMDB"."movie_keyword"
RIGHT JOIN ((SELECT "aka_title"."id", "aka_title"."movie_id", "aka_title"."title", "aka_title"."imdb_index", "aka_title"."kind_id", "aka_title"."production_year", "aka_title"."phonetic_code", "aka_title"."episode_of_id", "aka_title"."season_nr", "aka_title"."episode_nr", "aka_title"."note", "aka_title"."md5sum", "movie_companies"."id" AS "id0", "movie_companies"."movie_id" AS "movie_id0", "movie_companies"."company_id", "movie_companies"."company_type_id", "movie_companies"."note" AS "note0"
FROM "IMDB"."movie_companies"
RIGHT JOIN "IMDB"."aka_title" ON "movie_companies"."movie_id" = "aka_title"."id") AS "t2" LEFT JOIN "IMDB"."company_name" ON "t2"."company_id" = "company_name"."id") ON "movie_keyword"."movie_id" = "t2"."id") AS "t3"
LEFT JOIN "IMDB"."keyword" ON "t3"."keyword_id" = "keyword"."id"
WHERE "t3"."production_year" >= 2000
GROUP BY "t3"."id", "t3"."title", "t3"."production_year") AS "t7" ON "t1"."MOVIE_ID" = "t7"."MOVIE_ID"
ORDER BY "t7"."PRODUCTION_YEAR" DESC NULLS FIRST, "t7"."MOVIE_TITLE") AS "t9"