SELECT COALESCE("t10"."ACTOR_NAME", "t10"."ACTOR_NAME") AS "ACTOR_NAME", "t10"."MOVIE_COUNT", "t10"."KEYWORDS", "t10"."COMPANY_TYPES"
FROM (SELECT "t4"."ACTOR_NAME", "t8"."MOVIE_COUNT", "t4"."KEYWORDS", "t4"."COMPANY_TYPES"
FROM (SELECT ANY_VALUE("t1"."title") AS "MOVIE_TITLE", "t1"."production_year" AS "PRODUCTION_YEAR", ANY_VALUE("t1"."name") AS "ACTOR_NAME", ANY_VALUE("t1"."id1") AS "ACTOR_ID", LISTAGG(DISTINCT "keyword"."keyword", ', ') AS "KEYWORDS", LISTAGG(DISTINCT "company_type"."kind", ', ') AS "COMPANY_TYPES"
FROM (SELECT "s1"."id00" AS "id", "s1"."movie_id00" AS "movie_id", "s1"."title", "s1"."imdb_index", "s1"."kind_id", "s1"."production_year", "s1"."phonetic_code", "s1"."episode_of_id", "s1"."season_nr", "s1"."episode_nr", "s1"."note0" AS "note", "s1"."md5sum", "s1"."id" AS "id0", "s1"."person_id", "s1"."movie_id" AS "movie_id0", "s1"."person_role_id", "s1"."note" AS "note0", "s1"."nr_order", "s1"."role_id", "aka_name"."id" AS "id1", "aka_name"."person_id" AS "person_id0", "aka_name"."name", "aka_name"."imdb_index" AS "imdb_index0", "aka_name"."name_pcode_cf", "aka_name"."name_pcode_nf", "aka_name"."surname_pcode", "aka_name"."md5sum" AS "md5sum0", "s1"."id0" AS "id2", "s1"."movie_id0" AS "movie_id1", "s1"."keyword_id"
FROM "s1"
INNER JOIN "IMDB"."aka_name" ON "s1"."person_id" = "aka_name"."person_id") AS "t1"
LEFT JOIN "IMDB"."keyword" ON "t1"."keyword_id" = "keyword"."id"
LEFT JOIN "IMDB"."movie_companies" ON "t1"."id" = "movie_companies"."movie_id"
LEFT JOIN "IMDB"."company_type" ON "movie_companies"."company_type_id" = "company_type"."id"
GROUP BY "t1"."title", "t1"."production_year", "t1"."name", "t1"."id1") AS "t4"
INNER JOIN (SELECT "t7"."ACTOR_ID", COUNT(*) AS "MOVIE_COUNT"
FROM (SELECT "t5"."title", "t5"."production_year" AS "PRODUCTION_YEAR", "t5"."name", "t5"."id1", ANY_VALUE("t5"."title") AS "MOVIE_TITLE", ANY_VALUE("t5"."name") AS "ACTOR_NAME", ANY_VALUE("t5"."id1") AS "ACTOR_ID", LISTAGG(DISTINCT "keyword0"."keyword", ', ') AS "KEYWORDS", LISTAGG(DISTINCT "company_type0"."kind", ', ') AS "COMPANY_TYPES"
FROM (SELECT "s10"."id00" AS "id", "s10"."movie_id00" AS "movie_id", "s10"."title", "s10"."imdb_index", "s10"."kind_id", "s10"."production_year", "s10"."phonetic_code", "s10"."episode_of_id", "s10"."season_nr", "s10"."episode_nr", "s10"."note0" AS "note", "s10"."md5sum", "s10"."id" AS "id0", "s10"."person_id", "s10"."movie_id" AS "movie_id0", "s10"."person_role_id", "s10"."note" AS "note0", "s10"."nr_order", "s10"."role_id", "aka_name0"."id" AS "id1", "aka_name0"."person_id" AS "person_id0", "aka_name0"."name", "aka_name0"."imdb_index" AS "imdb_index0", "aka_name0"."name_pcode_cf", "aka_name0"."name_pcode_nf", "aka_name0"."surname_pcode", "aka_name0"."md5sum" AS "md5sum0", "s10"."id0" AS "id2", "s10"."movie_id0" AS "movie_id1", "s10"."keyword_id"
FROM "s1" AS "s10"
INNER JOIN "IMDB"."aka_name" AS "aka_name0" ON "s10"."person_id" = "aka_name0"."person_id") AS "t5"
LEFT JOIN "IMDB"."keyword" AS "keyword0" ON "t5"."keyword_id" = "keyword0"."id"
LEFT JOIN "IMDB"."movie_companies" AS "movie_companies0" ON "t5"."id" = "movie_companies0"."movie_id"
LEFT JOIN "IMDB"."company_type" AS "company_type0" ON "movie_companies0"."company_type_id" = "company_type0"."id"
GROUP BY "t5"."title", "t5"."production_year", "t5"."name", "t5"."id1") AS "t7"
GROUP BY "t7"."ACTOR_ID") AS "t8" ON "t4"."ACTOR_ID" = "t8"."ACTOR_ID"
ORDER BY "t8"."MOVIE_COUNT" DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY) AS "t10"