SELECT COALESCE("t10"."MOVIE_TITLE", "t10"."MOVIE_TITLE") AS "MOVIE_TITLE", "t10"."PRODUCTION_YEAR", "t10"."MOVIE_KIND", "t10"."ACTOR_NAME", "t10"."ROLE_TYPE", "t10"."KEYWORDS", "t10"."COMPANIES"
FROM (SELECT "t8"."MOVIE_TITLE", "t8"."PRODUCTION_YEAR", "t8"."MOVIE_KIND", "t8"."ACTOR_NAME", "t8"."ROLE_TYPE", "t8"."KEYWORDS", "t1"."COMPANIES"
FROM (SELECT "movie_companies"."movie_id" AS "MOVIE_ID", LISTAGG("company_name"."name", ', ') AS "COMPANIES"
FROM "IMDB"."company_name"
INNER JOIN "IMDB"."movie_companies" ON "company_name"."id" = "movie_companies"."company_id"
GROUP BY "movie_companies"."movie_id") AS "t1"
RIGHT JOIN (SELECT "t7"."MOVIE_ID", "t7"."MOVIE_TITLE", "t7"."PRODUCTION_YEAR", "t7"."MOVIE_KIND", "t7"."MOVIE_ID0", "t7"."ACTOR_NAME", "t7"."ROLE_TYPE", "t3"."MOVIE_ID" AS "MOVIE_ID1", "t3"."KEYWORDS"
FROM (SELECT "movie_keyword"."movie_id" AS "MOVIE_ID", LISTAGG("keyword"."keyword", ', ') AS "KEYWORDS"
FROM "IMDB"."keyword"
INNER JOIN "IMDB"."movie_keyword" ON "keyword"."id" = "movie_keyword"."keyword_id"
GROUP BY "movie_keyword"."movie_id") AS "t3"
RIGHT JOIN (SELECT "t6"."MOVIE_ID", "t6"."MOVIE_TITLE", "t6"."PRODUCTION_YEAR", "t6"."MOVIE_KIND", "t4"."MOVIE_ID" AS "MOVIE_ID0", "t4"."ACTOR_NAME", "t4"."ROLE_TYPE"
FROM (SELECT "s1"."movie_id" AS "MOVIE_ID", "s1"."name" AS "ACTOR_NAME", "role_type"."role" AS "ROLE_TYPE"
FROM "IMDB"."role_type"
INNER JOIN "s1" ON "role_type"."id" = "s1"."role_id") AS "t4"
RIGHT JOIN (SELECT "t5"."id" AS "MOVIE_ID", "t5"."title" AS "MOVIE_TITLE", "t5"."production_year" AS "PRODUCTION_YEAR", "kind_type"."kind" AS "MOVIE_KIND"
FROM (SELECT *
FROM "IMDB"."title"
WHERE "production_year" >= 2020) AS "t5"
INNER JOIN "IMDB"."kind_type" ON "t5"."kind_id" = "kind_type"."id") AS "t6" ON "t4"."MOVIE_ID" = "t6"."MOVIE_ID") AS "t7" ON "t3"."MOVIE_ID" = "t7"."MOVIE_ID") AS "t8" ON "t1"."MOVIE_ID" = "t8"."MOVIE_ID"
ORDER BY "t8"."PRODUCTION_YEAR" DESC NULLS FIRST, "t8"."MOVIE_TITLE") AS "t10"