SELECT COALESCE("t9"."MOVIE_ID", "t9"."MOVIE_ID") AS "MOVIE_ID", "t9"."TITLE", "t9"."PRODUCTION_YEAR", "t9"."KEYWORDS", "t9"."COMPANY_TYPES", "t9"."COMPANIES", "t9"."CAST_MEMBERS", "t9"."INFO_DETAILS"
FROM (SELECT "t7"."MOVIE_ID", "t7"."TITLE", "t7"."PRODUCTION_YEAR", "t7"."KEYWORDS", "t7"."COMPANY_TYPES", "t7"."COMPANIES", "t7"."CAST_MEMBERS", CASE WHEN "t2"."INFO_DETAILS" IS NOT NULL THEN CAST("t2"."INFO_DETAILS" AS VARCHAR CHARACTER SET "ISO-8859-1") ELSE 'No additional info' END AS "INFO_DETAILS"
FROM (SELECT "movie_info"."movie_id" AS "MOVIE_ID", LISTAGG(DISTINCT "info_type"."info", ', ') AS "INFO_DETAILS"
FROM "IMDB"."info_type"
INNER JOIN "IMDB"."movie_info" ON "info_type"."id" = "movie_info"."info_type_id"
GROUP BY "movie_info"."movie_id") AS "t2"
RIGHT JOIN (SELECT ANY_VALUE("t4"."id") AS "MOVIE_ID", "t4"."title" AS "TITLE", "t4"."production_year" AS "PRODUCTION_YEAR", LISTAGG(DISTINCT "t4"."keyword", ', ') AS "KEYWORDS", LISTAGG(DISTINCT "company_type"."kind", ', ') AS "COMPANY_TYPES", LISTAGG(DISTINCT "company_name"."name", ', ') AS "COMPANIES", LISTAGG(DISTINCT "name"."name", ', ') AS "CAST_MEMBERS"
FROM (SELECT "t3"."id", "t3"."movie_id", "t3"."title", "t3"."imdb_index", "t3"."kind_id", "t3"."production_year", "t3"."phonetic_code", "t3"."episode_of_id", "t3"."season_nr", "t3"."episode_nr", "t3"."note", "t3"."md5sum", "t3"."id0", "t3"."movie_id0", "t3"."keyword_id", "keyword"."id" AS "id1", "keyword"."keyword", "keyword"."phonetic_code" AS "phonetic_code0", "movie_companies"."id" AS "id2", "movie_companies"."movie_id" AS "movie_id1", "movie_companies"."company_id", "movie_companies"."company_type_id", "movie_companies"."note" AS "note0"
FROM "IMDB"."movie_companies"
RIGHT JOIN ((SELECT "s1"."id", "s1"."movie_id", "s1"."title", "s1"."imdb_index", "s1"."kind_id", "s1"."production_year", "s1"."phonetic_code", "s1"."episode_of_id", "s1"."season_nr", "s1"."episode_nr", "s1"."note", "s1"."md5sum", "movie_keyword"."id" AS "id0", "movie_keyword"."movie_id" AS "movie_id0", "movie_keyword"."keyword_id"
FROM "IMDB"."movie_keyword"
RIGHT JOIN "s1" ON "movie_keyword"."movie_id" = "s1"."id") AS "t3" LEFT JOIN "IMDB"."keyword" ON "t3"."keyword_id" = "keyword"."id") ON "movie_companies"."movie_id" = "t3"."id") AS "t4"
LEFT JOIN "IMDB"."company_name" ON "t4"."company_id" = "company_name"."id"
LEFT JOIN "IMDB"."company_type" ON "t4"."company_type_id" = "company_type"."id"
LEFT JOIN "IMDB"."complete_cast" ON "t4"."id" = "complete_cast"."movie_id"
LEFT JOIN "IMDB"."name" ON "complete_cast"."subject_id" = "name"."id"
GROUP BY "t4"."id", "t4"."title", "t4"."production_year") AS "t7" ON "t2"."MOVIE_ID" = "t7"."MOVIE_ID"
ORDER BY "t7"."PRODUCTION_YEAR" DESC NULLS FIRST, "t7"."TITLE") AS "t9"