SELECT COALESCE("t10"."AK_NAMES", "t10"."AK_NAMES") AS "AK_NAMES", "t10"."CHAR_NAMES", "t10"."MOVIE_ID", "t10"."MOVIE_TITLE", "t10"."PRODUCTION_COMPANIES", "t10"."KEYWORDS"
FROM (SELECT "s1"."AK_NAMES", "s1"."CHAR_NAMES", "t8"."MOVIE_ID", "t8"."MOVIE_TITLE", "t8"."PRODUCTION_COMPANIES", "t8"."KEYWORDS"
FROM "s1"
INNER JOIN (SELECT ANY_VALUE("t4"."id") AS "MOVIE_ID", ANY_VALUE("t4"."title") AS "MOVIE_TITLE", LISTAGG(DISTINCT "t4"."name", ', ') AS "PRODUCTION_COMPANIES", LISTAGG(DISTINCT "keyword"."keyword", ', ') AS "KEYWORDS"
FROM (SELECT "t3"."id", "t3"."movie_id", "t3"."title", "t3"."imdb_index", "t3"."kind_id", "t3"."production_year", "t3"."phonetic_code", "t3"."episode_of_id", "t3"."season_nr", "t3"."episode_nr", "t3"."note", "t3"."md5sum", "t3"."id0", "t3"."movie_id0", "t3"."company_id", "t3"."company_type_id", "t3"."note0", "company_name"."id" AS "id1", "company_name"."name", "company_name"."country_code", "company_name"."imdb_id", "company_name"."name_pcode_nf", "company_name"."name_pcode_sf", "company_name"."md5sum" AS "md5sum0", "movie_keyword"."id" AS "id2", "movie_keyword"."movie_id" AS "movie_id1", "movie_keyword"."keyword_id"
FROM "IMDB"."movie_keyword"
RIGHT JOIN ((SELECT "aka_title"."id", "aka_title"."movie_id", "aka_title"."title", "aka_title"."imdb_index", "aka_title"."kind_id", "aka_title"."production_year", "aka_title"."phonetic_code", "aka_title"."episode_of_id", "aka_title"."season_nr", "aka_title"."episode_nr", "aka_title"."note", "aka_title"."md5sum", "movie_companies"."id" AS "id0", "movie_companies"."movie_id" AS "movie_id0", "movie_companies"."company_id", "movie_companies"."company_type_id", "movie_companies"."note" AS "note0"
FROM "IMDB"."movie_companies"
RIGHT JOIN "IMDB"."aka_title" ON "movie_companies"."movie_id" = "aka_title"."id") AS "t3" LEFT JOIN "IMDB"."company_name" ON "t3"."company_id" = "company_name"."id") ON "movie_keyword"."movie_id" = "t3"."id") AS "t4"
LEFT JOIN "IMDB"."keyword" ON "t4"."keyword_id" = "keyword"."id"
GROUP BY "t4"."id", "t4"."title"
HAVING ANY_VALUE("t4"."title") ILIKE '%adventure%') AS "t8" ON "s1"."movie_id" = "t8"."MOVIE_ID"
ORDER BY "t8"."MOVIE_TITLE") AS "t10"