SELECT COALESCE("t12"."TITLE_ID", "t12"."TITLE_ID") AS "TITLE_ID", "t12"."TITLE", "t12"."PRODUCTION_YEAR", "t12"."ACTOR_NAMES", "t12"."KEYWORDS"
FROM (SELECT "t5"."TITLE_ID", "t5"."TITLE", "t5"."PRODUCTION_YEAR", "t10"."ACTOR_NAMES", "t5"."KEYWORDS"
FROM (SELECT "t3"."TITLE_ID", "t3"."TITLE", "t3"."PRODUCTION_YEAR", LISTAGG("keyword"."keyword", ', ') AS "KEYWORDS"
FROM (SELECT "t2"."id" AS "TITLE_ID", "t2"."title" AS "TITLE", "t2"."production_year" AS "PRODUCTION_YEAR", "s1"."name" AS "ACTOR_NAME", ROW_NUMBER() OVER (PARTITION BY "t2"."id" ORDER BY "s1"."nr_order") AS "ROLE_RANK"
FROM (SELECT "id" AS "ID"
FROM "IMDB"."kind_type"
WHERE "kind" IN ('movie', 'tv series')) AS "t1"
INNER JOIN (SELECT *
FROM "IMDB"."aka_title"
WHERE "production_year" >= 2000) AS "t2" ON "t1"."ID" = "t2"."kind_id"
INNER JOIN "s1" ON "t2"."id" = "s1"."movie_id") AS "t3"
INNER JOIN ("IMDB"."keyword" INNER JOIN "IMDB"."movie_keyword" ON "keyword"."id" = "movie_keyword"."keyword_id") ON "t3"."TITLE_ID" = "movie_keyword"."movie_id"
GROUP BY "t3"."TITLE_ID", "t3"."TITLE", "t3"."PRODUCTION_YEAR") AS "t5"
INNER JOIN (SELECT "t8"."id" AS "TITLE_ID", LISTAGG(DISTINCT "s10"."name", ', ') AS "ACTOR_NAMES"
FROM (SELECT "id" AS "ID"
FROM "IMDB"."kind_type"
WHERE "kind" IN ('movie', 'tv series')) AS "t7"
INNER JOIN (SELECT *
FROM "IMDB"."aka_title"
WHERE "production_year" >= 2000) AS "t8" ON "t7"."ID" = "t8"."kind_id"
INNER JOIN "s1" AS "s10" ON "t8"."id" = "s10"."movie_id"
GROUP BY "t8"."id") AS "t10" ON "t5"."TITLE_ID" = "t10"."TITLE_ID"
ORDER BY "t5"."PRODUCTION_YEAR" DESC NULLS FIRST, "t5"."TITLE") AS "t12"