SELECT COALESCE("TITLE", "TITLE") AS "TITLE", "PRODUCTION_YEAR", "KEYWORD_COUNT", "ACTORS", "CAST_COUNT"
FROM (SELECT "TITLE", "PRODUCTION_YEAR", "KEYWORD_COUNT", "ACTORS", "CAST_COUNT"
FROM "s1"
ORDER BY "PRODUCTION_YEAR" DESC NULLS FIRST, "KEYWORD_COUNT" DESC NULLS FIRST) AS "t12"