SELECT COALESCE("t11"."TITLE", "t11"."TITLE") AS "TITLE", "t11"."PRODUCTION_YEAR", "t11"."CAST_COUNT", "t11"."ACTOR_NAMES", "t11"."KEYWORDS", "t11"."INFO_DETAILS"
FROM (SELECT "t9"."TITLE", "t9"."PRODUCTION_YEAR", "t9"."CAST_COUNT", "t9"."ACTOR_NAMES", "t9"."KEYWORDS", "t5"."INFO_DETAILS"
FROM (SELECT "movie_id" AS "MOVIE_ID", LISTAGG("info", '; ') AS "INFO_DETAILS"
FROM "IMDB"."movie_info"
GROUP BY "movie_id") AS "t5"
RIGHT JOIN (SELECT "t8"."TITLE", "t8"."PRODUCTION_YEAR", "t8"."CAST_COUNT", "t8"."ACTOR_NAMES", "t8"."id", "t8"."movie_id", "t8"."title", "t8"."imdb_index", "t8"."kind_id", "t8"."production_year", "t8"."phonetic_code", "t8"."episode_of_id", "t8"."season_nr", "t8"."episode_nr", "t8"."note", "t8"."md5sum", "t7"."MOVIE_ID", "t7"."KEYWORDS"
FROM (SELECT "movie_keyword"."movie_id" AS "MOVIE_ID", LISTAGG("keyword"."keyword", ', ') AS "KEYWORDS"
FROM "IMDB"."keyword"
INNER JOIN "IMDB"."movie_keyword" ON "keyword"."id" = "movie_keyword"."keyword_id"
GROUP BY "movie_keyword"."movie_id") AS "t7"
RIGHT JOIN (SELECT "s1"."TITLE", "s1"."PRODUCTION_YEAR", "s1"."CAST_COUNT", "s1"."ACTOR_NAMES", "aka_title0"."id", "aka_title0"."movie_id", "aka_title0"."title", "aka_title0"."imdb_index", "aka_title0"."kind_id", "aka_title0"."production_year", "aka_title0"."phonetic_code", "aka_title0"."episode_of_id", "aka_title0"."season_nr", "aka_title0"."episode_nr", "aka_title0"."note", "aka_title0"."md5sum"
FROM "IMDB"."aka_title" AS "aka_title0"
RIGHT JOIN "s1" ON "aka_title0"."title" = "s1"."TITLE") AS "t8" ON "t7"."MOVIE_ID" = "t8"."movie_id") AS "t9" ON "t5"."MOVIE_ID" = "t9"."movie_id"
ORDER BY "t9"."CAST_COUNT" DESC NULLS FIRST) AS "t11"