SELECT COALESCE("MOVIE_TITLE", "MOVIE_TITLE") AS "MOVIE_TITLE", "PRODUCTION_YEAR", "MOVIE_KEYWORD", "ACTOR_NAME", "ROLE_NAME", "CAST_TYPE", "COMPANY_NAME", "COMPANY_TYPE"
FROM (SELECT "MOVIE_TITLE", "PRODUCTION_YEAR", "MOVIE_KEYWORD", "ACTOR_NAME", "ROLE_NAME", "CAST_TYPE", "COMPANY_NAME", "COMPANY_TYPE"
FROM "s1"
ORDER BY "PRODUCTION_YEAR" DESC NULLS FIRST, "MOVIE_TITLE") AS "t8"