SELECT COALESCE("t7"."TITLE", "t7"."TITLE") AS "TITLE", "t7"."PRODUCTION_YEAR", "t7"."NUM_CAST_MEMBERS", "t7"."CAST_NAMES", "t7"."KEYWORDS"
FROM (SELECT "t5"."TITLE", "t5"."PRODUCTION_YEAR", "t5"."NUM_CAST_MEMBERS", "t5"."CAST_NAMES", "t2"."KEYWORDS"
FROM (SELECT "movie_keyword"."movie_id" AS "MOVIE_ID", LISTAGG("keyword"."keyword", ', ') AS "KEYWORDS"
FROM "IMDB"."keyword"
INNER JOIN "IMDB"."movie_keyword" ON "keyword"."id" = "movie_keyword"."keyword_id"
GROUP BY "movie_keyword"."movie_id") AS "t2"
RIGHT JOIN (SELECT ANY_VALUE("s1"."id") AS "MOVIE_ID", "s1"."title" AS "TITLE", "s1"."production_year" AS "PRODUCTION_YEAR", COUNT(DISTINCT "cast_info"."person_id") AS "NUM_CAST_MEMBERS", LISTAGG(DISTINCT "aka_name"."name", ', ') AS "CAST_NAMES"
FROM "s1"
INNER JOIN "IMDB"."complete_cast" ON "s1"."id" = "complete_cast"."movie_id"
INNER JOIN ("IMDB"."aka_name" INNER JOIN "IMDB"."cast_info" ON "aka_name"."person_id" = "cast_info"."person_id") ON "complete_cast"."subject_id" = "cast_info"."id"
GROUP BY "s1"."id", "s1"."title", "s1"."production_year") AS "t5" ON "t2"."MOVIE_ID" = "t5"."MOVIE_ID"
ORDER BY "t5"."PRODUCTION_YEAR" DESC NULLS FIRST, "t5"."TITLE") AS "t7"