SELECT COALESCE("t8"."ACTOR_NAME", "t8"."ACTOR_NAME") AS "ACTOR_NAME", "t8"."AKA_COUNT", "t8"."KEYWORDS", "t8"."LAST_MOVIE_YEAR"
FROM (SELECT "aka_name0"."name" AS "ACTOR_NAME", "t6"."AKA_COUNT", "t6"."KEYWORDS", "t6"."LAST_MOVIE_YEAR"
FROM "IMDB"."aka_name" AS "aka_name0"
INNER JOIN (SELECT *
FROM "s1"
WHERE "AKA_COUNT" > 1) AS "t6" ON "aka_name0"."person_id" = "t6"."PERSON_ID"
ORDER BY "t6"."LAST_MOVIE_YEAR" DESC NULLS FIRST) AS "t8"