SELECT COALESCE("t8"."MOVIE_TITLE", "t8"."MOVIE_TITLE") AS "MOVIE_TITLE", "t8"."PRODUCTION_YEAR", "t8"."ACTOR_COUNT", "t8"."CAST_NAMES", "t8"."KEYWORDS", "t8"."COMPANIES", "t8"."COMPANY_TYPES"
FROM (SELECT "t6"."MOVIE_TITLE", "t6"."PRODUCTION_YEAR", "t6"."ACTOR_COUNT", "t6"."CAST_NAMES", "t6"."KEYWORDS", "t3"."COMPANIES", "t3"."COMPANY_TYPES"
FROM (SELECT ANY_VALUE("aka_title0"."title") AS "MOVIE_TITLE", LISTAGG(DISTINCT "company_name"."name", ', ') AS "COMPANIES", LISTAGG(DISTINCT "company_type"."kind", ', ') AS "COMPANY_TYPES"
FROM "IMDB"."company_type"
INNER JOIN ("IMDB"."company_name" INNER JOIN ("IMDB"."aka_title" AS "aka_title0" INNER JOIN "IMDB"."movie_companies" ON "aka_title0"."id" = "movie_companies"."movie_id") ON "company_name"."id" = "movie_companies"."company_id") ON "company_type"."id" = "movie_companies"."company_type_id"
GROUP BY "aka_title0"."title") AS "t3"
RIGHT JOIN (SELECT ANY_VALUE("s1"."title") AS "MOVIE_TITLE", "s1"."production_year" AS "PRODUCTION_YEAR", COUNT(DISTINCT "cast_info"."person_id") AS "ACTOR_COUNT", LISTAGG(DISTINCT "aka_name"."name", ', ') AS "CAST_NAMES", LISTAGG(DISTINCT "keyword"."keyword", ', ') AS "KEYWORDS"
FROM "IMDB"."aka_name"
INNER JOIN "IMDB"."cast_info" ON "aka_name"."person_id" = "cast_info"."person_id"
INNER JOIN ("s1" INNER JOIN "IMDB"."complete_cast" ON "s1"."id" = "complete_cast"."movie_id" INNER JOIN ("IMDB"."keyword" INNER JOIN "IMDB"."movie_keyword" ON "keyword"."id" = "movie_keyword"."keyword_id") ON "s1"."id" = "movie_keyword"."movie_id") ON "cast_info"."person_id" = "complete_cast"."subject_id"
GROUP BY "s1"."title", "s1"."production_year") AS "t6" ON "t3"."MOVIE_TITLE" = "t6"."MOVIE_TITLE"
ORDER BY "t6"."PRODUCTION_YEAR" DESC NULLS FIRST, "t6"."ACTOR_COUNT" DESC NULLS FIRST) AS "t8"