SELECT COALESCE("MOVIE_TITLE", "MOVIE_TITLE") AS "MOVIE_TITLE", "PRODUCTION_YEAR", LISTAGG(DISTINCT "ACTOR_NAME", "FD_COL_3") AS "ACTORS", LISTAGG(DISTINCT "COMPANY_TYPE", "FD_COL_3") AS "COMPANIES", LISTAGG(DISTINCT "MOVIE_INFO", "FD_COL_6") AS "INFORMATIONS", LISTAGG(DISTINCT "MOVIE_KEYWORD", "FD_COL_3") AS "KEYWORDS"
FROM "s1"
GROUP BY "MOVIE_TITLE", "PRODUCTION_YEAR"
ORDER BY "PRODUCTION_YEAR" DESC NULLS FIRST, "MOVIE_TITLE"