SELECT COALESCE("t16"."MOVIE_TITLE", "t16"."MOVIE_TITLE") AS "MOVIE_TITLE", "t16"."PRODUCTION_YEAR", "t16"."ACTOR_NAMES", "t16"."TOTAL_KEYWORDS", "t16"."TOTAL_COMPANIES"
FROM (SELECT "t9"."MOVIE_TITLE", "t9"."PRODUCTION_YEAR", "t9"."ACTOR_NAMES", CASE WHEN "t9"."TOTAL_KEYWORDS" IS NOT NULL THEN CAST("t9"."TOTAL_KEYWORDS" AS BIGINT) ELSE 0 END AS "TOTAL_KEYWORDS", CASE WHEN "t14"."TOTAL_COMPANIES" IS NOT NULL THEN CAST("t14"."TOTAL_COMPANIES" AS BIGINT) ELSE 0 END AS "TOTAL_COMPANIES"
FROM (SELECT "t8"."MOVIE_TITLE", "t8"."PRODUCTION_YEAR", "t8"."ACTOR_NAMES", "t8"."KEYWORD_COUNT", "t8"."COMPANY_COUNT", "t5"."movie_id" AS "MOVIE_ID", "t5"."TOTAL_KEYWORDS"
FROM (SELECT "t2"."movie_id", "t2"."TOTAL_KEYWORDS", "t4"."$f1" AS "$f0"
FROM (SELECT "movie_id", COUNT(*) AS "TOTAL_KEYWORDS"
FROM "IMDB"."movie_keyword"
GROUP BY "movie_id") AS "t2"
LEFT JOIN (SELECT "id", SINGLE_VALUE("title") AS "$f1"
FROM "IMDB"."title"
GROUP BY "id") AS "t4" ON "t2"."movie_id" = "t4"."id") AS "t5"
RIGHT JOIN (SELECT ANY_VALUE("s1"."title") AS "MOVIE_TITLE", "s1"."production_year" AS "PRODUCTION_YEAR", LISTAGG(DISTINCT "aka_name"."name", ', ') AS "ACTOR_NAMES", COUNT(DISTINCT "s1"."keyword_id") AS "KEYWORD_COUNT", COUNT(DISTINCT "s1"."name") AS "COMPANY_COUNT"
FROM "s1"
INNER JOIN "IMDB"."aka_name" ON "s1"."person_id" = "aka_name"."person_id"
GROUP BY "s1"."title", "s1"."production_year") AS "t8" ON "t5"."$f0" = "t8"."MOVIE_TITLE") AS "t9"
LEFT JOIN (SELECT "t11"."movie_id", "t11"."TOTAL_COMPANIES", "t13"."$f1" AS "$f0"
FROM (SELECT "movie_companies0"."movie_id", COUNT(DISTINCT "company_name0"."id") AS "TOTAL_COMPANIES"
FROM "IMDB"."company_name" AS "company_name0"
INNER JOIN "IMDB"."movie_companies" AS "movie_companies0" ON "company_name0"."id" = "movie_companies0"."company_id"
GROUP BY "movie_companies0"."movie_id") AS "t11"
LEFT JOIN (SELECT "id", SINGLE_VALUE("title") AS "$f1"
FROM "IMDB"."title"
GROUP BY "id") AS "t13" ON "t11"."movie_id" = "t13"."id") AS "t14" ON "t9"."MOVIE_TITLE" = "t14"."$f0"
ORDER BY "t9"."PRODUCTION_YEAR" DESC NULLS FIRST, "t9"."MOVIE_TITLE") AS "t16"