SELECT COALESCE("t4"."MOVIE_ID", "t4"."MOVIE_ID") AS "MOVIE_ID", "t4"."MOVIE_TITLE", "t4"."PRODUCTION_YEAR", "t4"."CAST_COUNT", "t4"."ACTOR_NAMES", "t0"."MOVIE_ID" AS "MOVIE_ID0", "t0"."KEYWORDS"
FROM (SELECT "movie_keyword"."movie_id" AS "MOVIE_ID", LISTAGG(DISTINCT "keyword"."keyword", ', ') AS "KEYWORDS"
FROM "IMDB"."keyword"
INNER JOIN "IMDB"."movie_keyword" ON "keyword"."id" = "movie_keyword"."keyword_id"
GROUP BY "movie_keyword"."movie_id") AS "t0"
RIGHT JOIN (SELECT ANY_VALUE("aka_title"."id") AS "MOVIE_ID", ANY_VALUE("aka_title"."title") AS "MOVIE_TITLE", "aka_title"."production_year" AS "PRODUCTION_YEAR", COUNT(*) AS "CAST_COUNT", LISTAGG(DISTINCT "aka_name"."name", ', ') AS "ACTOR_NAMES"
FROM "IMDB"."aka_title"
INNER JOIN ("IMDB"."aka_name" INNER JOIN "IMDB"."cast_info" ON "aka_name"."person_id" = "cast_info"."person_id") ON "aka_title"."id" = "cast_info"."movie_id"
GROUP BY "aka_title"."id", "aka_title"."title", "aka_title"."production_year"
HAVING COUNT(*) > 5) AS "t4" ON "t0"."MOVIE_ID" = "t4"."MOVIE_ID"