SELECT COALESCE("t26"."TITLE", "t26"."TITLE") AS "TITLE", "t26"."PRODUCTION_YEAR", "t26"."CAST_COUNT", "t26"."AVG_SALARY", "t26"."COMPANY_COUNT", "t26"."BUDGET_CATEGORY"
FROM (SELECT "t13"."TITLE", "t13"."PRODUCTION_YEAR", CASE WHEN "t13"."CAST_COUNT" IS NOT NULL THEN CAST("t13"."CAST_COUNT" AS BIGINT) ELSE 0 END AS "CAST_COUNT", CASE WHEN "t13"."AVG_SALARY" IS NOT NULL THEN CAST("t13"."AVG_SALARY" AS FLOAT) ELSE 0E0 END AS "AVG_SALARY", CASE WHEN "t24"."EXPR$0" IS NULL THEN 0 ELSE "t24"."EXPR$0" END AS "COMPANY_COUNT", CASE WHEN CASE WHEN "t13"."AVG_SALARY" IS NOT NULL THEN CAST("t13"."AVG_SALARY" AS FLOAT) ELSE 0E0 END > 1.000000E5 THEN 'High Budget  ' WHEN CASE WHEN "t13"."AVG_SALARY" IS NOT NULL THEN CAST("t13"."AVG_SALARY" AS FLOAT) ELSE 0E0 END >= 5.00000E4 THEN 'Medium Budget' ELSE 'Low Budget   ' END AS "BUDGET_CATEGORY"
FROM (SELECT "t4"."MOVIE_ID" AS "MOVIE_ID", "t4"."TITLE" AS "TITLE", "t4"."PRODUCTION_YEAR" AS "PRODUCTION_YEAR", "t4"."RAN" AS "RAN", "t12"."MOVIE_ID" AS "MOVIE_ID0", "t12"."CAST_COUNT" AS "CAST_COUNT", "t12"."AVG_SALARY" AS "AVG_SALARY", "t12"."GENRES" AS "GENRES"
FROM (SELECT "id" AS "MOVIE_ID", "title" AS "TITLE", "production_year" AS "PRODUCTION_YEAR", ROW_NUMBER() OVER (PARTITION BY "production_year" ORDER BY "production_year" DESC NULLS FIRST) AS "RAN"
FROM "IMDB"."aka_title") AS "t4"
LEFT JOIN (SELECT "t6"."MOVIE_ID", COUNT(*) AS "CAST_COUNT", AVG(CASE WHEN CAST("t10"."info" AS FLOAT) IS NOT NULL THEN CAST(CAST("t10"."info" AS FLOAT) AS FLOAT) ELSE 0E0 END) AS "AVG_SALARY", LISTAGG(DISTINCT "keyword"."keyword", ', ') AS "GENRES"
FROM (SELECT "t5"."MOVIE_ID", "t5"."TITLE", "t5"."PRODUCTION_YEAR", "t5"."RAN", "complete_cast"."id", "complete_cast"."movie_id", "complete_cast"."subject_id", "complete_cast"."status_id", "cast_info"."id" AS "id0", "cast_info"."person_id", "cast_info"."movie_id" AS "movie_id0", "cast_info"."person_role_id", "cast_info"."note", "cast_info"."nr_order", "cast_info"."role_id", "movie_keyword"."id" AS "id1", "movie_keyword"."movie_id" AS "movie_id1", "movie_keyword"."keyword_id"
FROM "IMDB"."movie_keyword"
RIGHT JOIN ("IMDB"."cast_info" INNER JOIN ((SELECT "id" AS "MOVIE_ID", "title" AS "TITLE", "production_year" AS "PRODUCTION_YEAR", ROW_NUMBER() OVER (PARTITION BY "production_year" ORDER BY "production_year" DESC NULLS FIRST) AS "RAN"
FROM "IMDB"."aka_title") AS "t5" INNER JOIN "IMDB"."complete_cast" ON "t5"."MOVIE_ID" = "complete_cast"."movie_id") ON "cast_info"."person_id" = "complete_cast"."subject_id") ON "movie_keyword"."movie_id" = "t5"."MOVIE_ID") AS "t6"
LEFT JOIN "IMDB"."keyword" ON "t6"."keyword_id" = "keyword"."id"
LEFT JOIN (SELECT "person_info0"."id", "person_info0"."person_id", "person_info0"."info_type_id", "person_info0"."info", "person_info0"."note", "t9"."$f0"
FROM (SELECT SINGLE_VALUE("id") AS "$f0"
FROM "IMDB"."info_type"
WHERE "info" = 'salary') AS "t9"
INNER JOIN "IMDB"."person_info" AS "person_info0" ON "t9"."$f0" = "person_info0"."info_type_id") AS "t10" ON "t6"."person_id" = "t10"."person_id"
GROUP BY "t6"."MOVIE_ID") AS "t12" ON "t4"."MOVIE_ID" = "t12"."MOVIE_ID"
WHERE CASE WHEN "t12"."CAST_COUNT" IS NOT NULL THEN CAST("t12"."CAST_COUNT" AS BIGINT) ELSE 0 END > 0) AS "t13"
LEFT JOIN (SELECT "t20"."TITLE", CASE WHEN "t23"."EXPR$0" IS NOT NULL THEN "t23"."EXPR$0" ELSE 0 END AS "EXPR$0"
FROM (SELECT "t14"."TITLE"
FROM (SELECT "id" AS "MOVIE_ID", "title" AS "TITLE", "production_year" AS "PRODUCTION_YEAR", ROW_NUMBER() OVER (PARTITION BY "production_year" ORDER BY "production_year" DESC NULLS FIRST) AS "RAN"
FROM "IMDB"."aka_title") AS "t14"
LEFT JOIN (SELECT "t16"."MOVIE_ID", COUNT(*) AS "CAST_COUNT", AVG(CASE WHEN CAST("s1"."info" AS FLOAT) IS NOT NULL THEN CAST(CAST("s1"."info" AS FLOAT) AS FLOAT) ELSE 0E0 END) AS "AVG_SALARY", LISTAGG(DISTINCT "keyword0"."keyword", ', ') AS "GENRES"
FROM (SELECT "t15"."MOVIE_ID", "t15"."TITLE", "t15"."PRODUCTION_YEAR", "t15"."RAN", "complete_cast0"."id", "complete_cast0"."movie_id", "complete_cast0"."subject_id", "complete_cast0"."status_id", "cast_info0"."id" AS "id0", "cast_info0"."person_id", "cast_info0"."movie_id" AS "movie_id0", "cast_info0"."person_role_id", "cast_info0"."note", "cast_info0"."nr_order", "cast_info0"."role_id", "movie_keyword0"."id" AS "id1", "movie_keyword0"."movie_id" AS "movie_id1", "movie_keyword0"."keyword_id"
FROM "IMDB"."movie_keyword" AS "movie_keyword0"
RIGHT JOIN ("IMDB"."cast_info" AS "cast_info0" INNER JOIN ((SELECT "id" AS "MOVIE_ID", "title" AS "TITLE", "production_year" AS "PRODUCTION_YEAR", ROW_NUMBER() OVER (PARTITION BY "production_year" ORDER BY "production_year" DESC NULLS FIRST) AS "RAN"
FROM "IMDB"."aka_title") AS "t15" INNER JOIN "IMDB"."complete_cast" AS "complete_cast0" ON "t15"."MOVIE_ID" = "complete_cast0"."movie_id") ON "cast_info0"."person_id" = "complete_cast0"."subject_id") ON "movie_keyword0"."movie_id" = "t15"."MOVIE_ID") AS "t16"
LEFT JOIN "IMDB"."keyword" AS "keyword0" ON "t16"."keyword_id" = "keyword0"."id"
LEFT JOIN "s1" ON "t16"."person_id" = "s1"."person_id"
GROUP BY "t16"."MOVIE_ID") AS "t18" ON "t14"."MOVIE_ID" = "t18"."MOVIE_ID"
WHERE CASE WHEN "t18"."CAST_COUNT" IS NOT NULL THEN CAST("t18"."CAST_COUNT" AS BIGINT) ELSE 0 END > 0
GROUP BY "t14"."TITLE") AS "t20"
LEFT JOIN (SELECT "aka_title3"."title" AS "TITLE", COUNT(*) AS "EXPR$0"
FROM (SELECT *
FROM "IMDB"."company_name"
WHERE "country_code" = 'USA') AS "t21"
INNER JOIN ("IMDB"."aka_title" AS "aka_title3" INNER JOIN "IMDB"."movie_companies" ON "aka_title3"."id" = "movie_companies"."movie_id") ON "t21"."id" = "movie_companies"."company_id"
GROUP BY "aka_title3"."title") AS "t23" ON "t20"."TITLE" IS NOT DISTINCT FROM "t23"."TITLE") AS "t24" ON "t13"."TITLE" = "t24"."TITLE"
ORDER BY "t13"."PRODUCTION_YEAR" DESC NULLS FIRST, 3 DESC NULLS FIRST) AS "t26"