SELECT COALESCE("TITLE", "TITLE") AS "TITLE", "PRODUCTION_YEAR", "CAST_COUNT", "COMPANY_NAMES", "COMPANY_TYPES", "KEYWORDS"
FROM (SELECT "TITLE", "PRODUCTION_YEAR", "CAST_COUNT", "COMPANY_NAMES", "COMPANY_TYPES", "KEYWORDS"
FROM "s1"
ORDER BY "PRODUCTION_YEAR" DESC NULLS FIRST, "CAST_COUNT" DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY) AS "t12"