SELECT COALESCE("t0"."MOVIE_ID", "t0"."MOVIE_ID") AS "MOVIE_ID", "t0"."KEYWORDS", "t9"."TITLE_ID", "t9"."TITLE", "t9"."PRODUCTION_YEAR", "t9"."KIND_ID", "t9"."CAST_COUNT", "t9"."ACTOR_NAMES", "t9"."MOVIE_ID" AS "MOVIE_ID0", "t9"."COMPANY_NAMES", "t9"."COMPANY_TYPES"
FROM (SELECT "movie_keyword"."movie_id" AS "MOVIE_ID", LISTAGG(DISTINCT "keyword"."keyword", ', ') AS "KEYWORDS"
FROM "IMDB"."keyword"
INNER JOIN "IMDB"."movie_keyword" ON "keyword"."id" = "movie_keyword"."keyword_id"
GROUP BY "movie_keyword"."movie_id") AS "t0"
RIGHT JOIN (SELECT "t8"."TITLE_ID", "t8"."TITLE", "t8"."PRODUCTION_YEAR", "t8"."KIND_ID", "t8"."CAST_COUNT", "t8"."ACTOR_NAMES", "t2"."MOVIE_ID", "t2"."COMPANY_NAMES", "t2"."COMPANY_TYPES"
FROM (SELECT "movie_companies"."movie_id" AS "MOVIE_ID", LISTAGG(DISTINCT "company_name"."name", ', ') AS "COMPANY_NAMES", LISTAGG(DISTINCT "company_type"."kind", ', ') AS "COMPANY_TYPES"
FROM "IMDB"."company_type"
INNER JOIN ("IMDB"."company_name" INNER JOIN "IMDB"."movie_companies" ON "company_name"."id" = "movie_companies"."company_id") ON "company_type"."id" = "movie_companies"."company_type_id"
GROUP BY "movie_companies"."movie_id") AS "t2"
RIGHT JOIN (SELECT ANY_VALUE("t4"."id") AS "TITLE_ID", "t4"."title" AS "TITLE", "t4"."production_year" AS "PRODUCTION_YEAR", "t4"."kind_id" AS "KIND_ID", COUNT("t4"."person_id") AS "CAST_COUNT", LISTAGG(DISTINCT "aka_name"."name", ', ') AS "ACTOR_NAMES"
FROM (SELECT "t3"."id", "t3"."title", "t3"."imdb_index", "t3"."kind_id", "t3"."production_year", "t3"."imdb_id", "t3"."phonetic_code", "t3"."episode_of_id", "t3"."season_nr", "t3"."episode_nr", "t3"."series_years", "t3"."md5sum", "cast_info"."id" AS "id0", "cast_info"."person_id", "cast_info"."movie_id", "cast_info"."person_role_id", "cast_info"."note", "cast_info"."nr_order", "cast_info"."role_id"
FROM "IMDB"."cast_info"
RIGHT JOIN (SELECT *
FROM "IMDB"."title"
WHERE "production_year" >= 2000 AND "production_year" <= 2023) AS "t3" ON "cast_info"."movie_id" = "t3"."id") AS "t4"
LEFT JOIN "IMDB"."aka_name" ON "t4"."person_id" = "aka_name"."person_id"
GROUP BY "t4"."id", "t4"."title", "t4"."production_year", "t4"."kind_id"
HAVING COUNT("t4"."person_id") > 3) AS "t8" ON "t2"."MOVIE_ID" = "t8"."TITLE_ID") AS "t9" ON "t0"."MOVIE_ID" = "t9"."TITLE_ID"