SELECT COALESCE("t92"."MOVIE_ID", "t92"."MOVIE_ID") AS "MOVIE_ID", "t92"."TITLE", "t92"."PRODUCTION_YEAR", "t92"."CAST_COUNT", "t92"."MOVIE_KEYWORDS", "t92"."AVG_CAST_COUNT", "t92"."UNIQUE_ACTORS"
FROM (SELECT "t42"."MOVIE_ID", "t42"."TITLE", "t42"."PRODUCTION_YEAR", "t42"."CAST_COUNT", "t42"."MOVIE_KEYWORDS", "t42"."EXPR$0" AS "AVG_CAST_COUNT", CASE WHEN "t89"."EXPR$0" IS NULL THEN 0 ELSE "t89"."EXPR$0" END AS "UNIQUE_ACTORS"
FROM (SELECT "t15"."MOVIE_ID", "t15"."TITLE", "t15"."CAST_COUNT", "t15"."MOVIE_KEYWORDS", "t15"."PRODUCTION_YEAR", "t41"."EXPR$0"
FROM (SELECT "t14"."MOVIE_ID", "t14"."TITLE", "t14"."CAST_COUNT", "t14"."MOVIE_KEYWORDS", "t14"."PRODUCTION_YEAR"
FROM (SELECT AVG(CASE WHEN "t5"."COUNT" IS NOT NULL THEN CAST("t5"."COUNT" AS BIGINT) ELSE 0 END) AS "EXPR$0"
FROM (SELECT "t4"."MOVIE_ID", "t4"."TITLE", "t4"."PRODUCTION_YEAR", "t4"."RAN", "t3"."movie_id" AS "MOVIE_ID0", "t3"."COUNT"
FROM (SELECT "movie_id", COUNT(*) AS "COUNT"
FROM "IMDB"."cast_info"
GROUP BY "movie_id") AS "t3"
RIGHT JOIN (SELECT "id" AS "MOVIE_ID", "title" AS "TITLE", "production_year" AS "PRODUCTION_YEAR", ROW_NUMBER() OVER (PARTITION BY "production_year" ORDER BY "id") AS "RAN"
FROM "IMDB"."aka_title") AS "t4" ON "t3"."movie_id" = "t4"."MOVIE_ID") AS "t5"
LEFT JOIN (SELECT "movie_keyword0"."movie_id" AS "MOVIE_ID", LISTAGG("keyword0"."keyword", ', ') AS "KEYWORDS"
FROM "IMDB"."keyword" AS "keyword0"
INNER JOIN "IMDB"."movie_keyword" AS "movie_keyword0" ON "keyword0"."id" = "movie_keyword0"."keyword_id"
GROUP BY "movie_keyword0"."movie_id") AS "t7" ON "t5"."MOVIE_ID" = "t7"."MOVIE_ID") AS "t9"
INNER JOIN (SELECT "t13"."MOVIE_ID", "t13"."TITLE", CASE WHEN "t13"."COUNT" IS NOT NULL THEN CAST("t13"."COUNT" AS BIGINT) ELSE 0 END AS "CAST_COUNT", CASE WHEN "s1"."KEYWORDS" IS NOT NULL THEN CAST("s1"."KEYWORDS" AS VARCHAR CHARACTER SET "ISO-8859-1") ELSE '' END AS "MOVIE_KEYWORDS", "t13"."PRODUCTION_YEAR"
FROM (SELECT "t12"."MOVIE_ID", "t12"."TITLE", "t12"."PRODUCTION_YEAR", "t12"."RAN", "t11"."movie_id" AS "MOVIE_ID0", "t11"."COUNT"
FROM (SELECT "movie_id", COUNT(*) AS "COUNT"
FROM "IMDB"."cast_info"
GROUP BY "movie_id") AS "t11"
RIGHT JOIN (SELECT "id" AS "MOVIE_ID", "title" AS "TITLE", "production_year" AS "PRODUCTION_YEAR", ROW_NUMBER() OVER (PARTITION BY "production_year" ORDER BY "id") AS "RAN"
FROM "IMDB"."aka_title") AS "t12" ON "t11"."movie_id" = "t12"."MOVIE_ID") AS "t13"
LEFT JOIN "s1" ON "t13"."MOVIE_ID" = "s1"."MOVIE_ID") AS "t14" ON "t9"."EXPR$0" < "t14"."CAST_COUNT") AS "t15"
LEFT JOIN (SELECT "t32"."PRODUCTION_YEAR", "t40"."EXPR$0"
FROM (SELECT "t30"."PRODUCTION_YEAR"
FROM (SELECT AVG(CASE WHEN "t19"."COUNT" IS NOT NULL THEN CAST("t19"."COUNT" AS BIGINT) ELSE 0 END) AS "EXPR$0"
FROM (SELECT "t18"."MOVIE_ID", "t18"."TITLE", "t18"."PRODUCTION_YEAR", "t18"."RAN", "t17"."movie_id" AS "MOVIE_ID0", "t17"."COUNT"
FROM (SELECT "movie_id", COUNT(*) AS "COUNT"
FROM "IMDB"."cast_info"
GROUP BY "movie_id") AS "t17"
RIGHT JOIN (SELECT "id" AS "MOVIE_ID", "title" AS "TITLE", "production_year" AS "PRODUCTION_YEAR", ROW_NUMBER() OVER (PARTITION BY "production_year" ORDER BY "id") AS "RAN"
FROM "IMDB"."aka_title") AS "t18" ON "t17"."movie_id" = "t18"."MOVIE_ID") AS "t19"
LEFT JOIN (SELECT "movie_keyword1"."movie_id" AS "MOVIE_ID", LISTAGG("keyword1"."keyword", ', ') AS "KEYWORDS"
FROM "IMDB"."keyword" AS "keyword1"
INNER JOIN "IMDB"."movie_keyword" AS "movie_keyword1" ON "keyword1"."id" = "movie_keyword1"."keyword_id"
GROUP BY "movie_keyword1"."movie_id") AS "t21" ON "t19"."MOVIE_ID" = "t21"."MOVIE_ID") AS "t23"
INNER JOIN (SELECT "t27"."MOVIE_ID", "t27"."TITLE", CASE WHEN "t27"."COUNT" IS NOT NULL THEN CAST("t27"."COUNT" AS BIGINT) ELSE 0 END AS "CAST_COUNT", CASE WHEN "t29"."KEYWORDS" IS NOT NULL THEN CAST("t29"."KEYWORDS" AS VARCHAR CHARACTER SET "ISO-8859-1") ELSE '' END AS "MOVIE_KEYWORDS", "t27"."PRODUCTION_YEAR"
FROM (SELECT "t26"."MOVIE_ID", "t26"."TITLE", "t26"."PRODUCTION_YEAR", "t26"."RAN", "t25"."movie_id" AS "MOVIE_ID0", "t25"."COUNT"
FROM (SELECT "movie_id", COUNT(*) AS "COUNT"
FROM "IMDB"."cast_info"
GROUP BY "movie_id") AS "t25"
RIGHT JOIN (SELECT "id" AS "MOVIE_ID", "title" AS "TITLE", "production_year" AS "PRODUCTION_YEAR", ROW_NUMBER() OVER (PARTITION BY "production_year" ORDER BY "id") AS "RAN"
FROM "IMDB"."aka_title") AS "t26" ON "t25"."movie_id" = "t26"."MOVIE_ID") AS "t27"
LEFT JOIN (SELECT "movie_keyword2"."movie_id" AS "MOVIE_ID", LISTAGG("keyword2"."keyword", ', ') AS "KEYWORDS"
FROM "IMDB"."keyword" AS "keyword2"
INNER JOIN "IMDB"."movie_keyword" AS "movie_keyword2" ON "keyword2"."id" = "movie_keyword2"."keyword_id"
GROUP BY "movie_keyword2"."movie_id") AS "t29" ON "t27"."MOVIE_ID" = "t29"."MOVIE_ID") AS "t30" ON "t23"."EXPR$0" < "t30"."CAST_COUNT"
GROUP BY "t30"."PRODUCTION_YEAR") AS "t32"
LEFT JOIN (SELECT "t36"."PRODUCTION_YEAR", AVG(CASE WHEN "t36"."COUNT" IS NOT NULL THEN CAST("t36"."COUNT" AS BIGINT) ELSE 0 END) AS "EXPR$0"
FROM (SELECT "t35"."MOVIE_ID", "t35"."TITLE", "t35"."PRODUCTION_YEAR", "t35"."RAN", "t34"."movie_id" AS "MOVIE_ID0", "t34"."COUNT"
FROM (SELECT "movie_id", COUNT(*) AS "COUNT"
FROM "IMDB"."cast_info"
GROUP BY "movie_id") AS "t34"
RIGHT JOIN (SELECT "id" AS "MOVIE_ID", "title" AS "TITLE", "production_year" AS "PRODUCTION_YEAR", ROW_NUMBER() OVER (PARTITION BY "production_year" ORDER BY "id") AS "RAN"
FROM "IMDB"."aka_title") AS "t35" ON "t34"."movie_id" = "t35"."MOVIE_ID") AS "t36"
LEFT JOIN (SELECT "movie_keyword3"."movie_id" AS "MOVIE_ID", LISTAGG("keyword3"."keyword", ', ') AS "KEYWORDS"
FROM "IMDB"."keyword" AS "keyword3"
INNER JOIN "IMDB"."movie_keyword" AS "movie_keyword3" ON "keyword3"."id" = "movie_keyword3"."keyword_id"
GROUP BY "movie_keyword3"."movie_id") AS "t38" ON "t36"."MOVIE_ID" = "t38"."MOVIE_ID"
GROUP BY "t36"."PRODUCTION_YEAR") AS "t40" ON "t32"."PRODUCTION_YEAR" IS NOT DISTINCT FROM "t40"."PRODUCTION_YEAR") AS "t41" ON "t15"."PRODUCTION_YEAR" = "t41"."PRODUCTION_YEAR") AS "t42"
LEFT JOIN (SELECT "t86"."MOVIE_ID" AS "movie_id", CASE WHEN "t88"."EXPR$0" IS NOT NULL THEN "t88"."EXPR$0" ELSE 0 END AS "EXPR$0"
FROM (SELECT "t58"."MOVIE_ID"
FROM (SELECT "t57"."MOVIE_ID", "t57"."TITLE", "t57"."CAST_COUNT", "t57"."MOVIE_KEYWORDS", "t57"."PRODUCTION_YEAR"
FROM (SELECT AVG(CASE WHEN "t46"."COUNT" IS NOT NULL THEN CAST("t46"."COUNT" AS BIGINT) ELSE 0 END) AS "EXPR$0"
FROM (SELECT "t45"."MOVIE_ID", "t45"."TITLE", "t45"."PRODUCTION_YEAR", "t45"."RAN", "t44"."movie_id" AS "MOVIE_ID0", "t44"."COUNT"
FROM (SELECT "movie_id", COUNT(*) AS "COUNT"
FROM "IMDB"."cast_info"
GROUP BY "movie_id") AS "t44"
RIGHT JOIN (SELECT "id" AS "MOVIE_ID", "title" AS "TITLE", "production_year" AS "PRODUCTION_YEAR", ROW_NUMBER() OVER (PARTITION BY "production_year" ORDER BY "id") AS "RAN"
FROM "IMDB"."aka_title") AS "t45" ON "t44"."movie_id" = "t45"."MOVIE_ID") AS "t46"
LEFT JOIN (SELECT "movie_keyword4"."movie_id" AS "MOVIE_ID", LISTAGG("keyword4"."keyword", ', ') AS "KEYWORDS"
FROM "IMDB"."keyword" AS "keyword4"
INNER JOIN "IMDB"."movie_keyword" AS "movie_keyword4" ON "keyword4"."id" = "movie_keyword4"."keyword_id"
GROUP BY "movie_keyword4"."movie_id") AS "t48" ON "t46"."MOVIE_ID" = "t48"."MOVIE_ID") AS "t50"
INNER JOIN (SELECT "t54"."MOVIE_ID", "t54"."TITLE", CASE WHEN "t54"."COUNT" IS NOT NULL THEN CAST("t54"."COUNT" AS BIGINT) ELSE 0 END AS "CAST_COUNT", CASE WHEN "t56"."KEYWORDS" IS NOT NULL THEN CAST("t56"."KEYWORDS" AS VARCHAR CHARACTER SET "ISO-8859-1") ELSE '' END AS "MOVIE_KEYWORDS", "t54"."PRODUCTION_YEAR"
FROM (SELECT "t53"."MOVIE_ID", "t53"."TITLE", "t53"."PRODUCTION_YEAR", "t53"."RAN", "t52"."movie_id" AS "MOVIE_ID0", "t52"."COUNT"
FROM (SELECT "movie_id", COUNT(*) AS "COUNT"
FROM "IMDB"."cast_info"
GROUP BY "movie_id") AS "t52"
RIGHT JOIN (SELECT "id" AS "MOVIE_ID", "title" AS "TITLE", "production_year" AS "PRODUCTION_YEAR", ROW_NUMBER() OVER (PARTITION BY "production_year" ORDER BY "id") AS "RAN"
FROM "IMDB"."aka_title") AS "t53" ON "t52"."movie_id" = "t53"."MOVIE_ID") AS "t54"
LEFT JOIN (SELECT "movie_keyword5"."movie_id" AS "MOVIE_ID", LISTAGG("keyword5"."keyword", ', ') AS "KEYWORDS"
FROM "IMDB"."keyword" AS "keyword5"
INNER JOIN "IMDB"."movie_keyword" AS "movie_keyword5" ON "keyword5"."id" = "movie_keyword5"."keyword_id"
GROUP BY "movie_keyword5"."movie_id") AS "t56" ON "t54"."MOVIE_ID" = "t56"."MOVIE_ID") AS "t57" ON "t50"."EXPR$0" < "t57"."CAST_COUNT") AS "t58"
LEFT JOIN (SELECT "t75"."PRODUCTION_YEAR", "t83"."EXPR$0"
FROM (SELECT "t73"."PRODUCTION_YEAR"
FROM (SELECT AVG(CASE WHEN "t62"."COUNT" IS NOT NULL THEN CAST("t62"."COUNT" AS BIGINT) ELSE 0 END) AS "EXPR$0"
FROM (SELECT "t61"."MOVIE_ID", "t61"."TITLE", "t61"."PRODUCTION_YEAR", "t61"."RAN", "t60"."movie_id" AS "MOVIE_ID0", "t60"."COUNT"
FROM (SELECT "movie_id", COUNT(*) AS "COUNT"
FROM "IMDB"."cast_info"
GROUP BY "movie_id") AS "t60"
RIGHT JOIN (SELECT "id" AS "MOVIE_ID", "title" AS "TITLE", "production_year" AS "PRODUCTION_YEAR", ROW_NUMBER() OVER (PARTITION BY "production_year" ORDER BY "id") AS "RAN"
FROM "IMDB"."aka_title") AS "t61" ON "t60"."movie_id" = "t61"."MOVIE_ID") AS "t62"
LEFT JOIN (SELECT "movie_keyword6"."movie_id" AS "MOVIE_ID", LISTAGG("keyword6"."keyword", ', ') AS "KEYWORDS"
FROM "IMDB"."keyword" AS "keyword6"
INNER JOIN "IMDB"."movie_keyword" AS "movie_keyword6" ON "keyword6"."id" = "movie_keyword6"."keyword_id"
GROUP BY "movie_keyword6"."movie_id") AS "t64" ON "t62"."MOVIE_ID" = "t64"."MOVIE_ID") AS "t66"
INNER JOIN (SELECT "t70"."MOVIE_ID", "t70"."TITLE", CASE WHEN "t70"."COUNT" IS NOT NULL THEN CAST("t70"."COUNT" AS BIGINT) ELSE 0 END AS "CAST_COUNT", CASE WHEN "t72"."KEYWORDS" IS NOT NULL THEN CAST("t72"."KEYWORDS" AS VARCHAR CHARACTER SET "ISO-8859-1") ELSE '' END AS "MOVIE_KEYWORDS", "t70"."PRODUCTION_YEAR"
FROM (SELECT "t69"."MOVIE_ID", "t69"."TITLE", "t69"."PRODUCTION_YEAR", "t69"."RAN", "t68"."movie_id" AS "MOVIE_ID0", "t68"."COUNT"
FROM (SELECT "movie_id", COUNT(*) AS "COUNT"
FROM "IMDB"."cast_info"
GROUP BY "movie_id") AS "t68"
RIGHT JOIN (SELECT "id" AS "MOVIE_ID", "title" AS "TITLE", "production_year" AS "PRODUCTION_YEAR", ROW_NUMBER() OVER (PARTITION BY "production_year" ORDER BY "id") AS "RAN"
FROM "IMDB"."aka_title") AS "t69" ON "t68"."movie_id" = "t69"."MOVIE_ID") AS "t70"
LEFT JOIN (SELECT "movie_keyword7"."movie_id" AS "MOVIE_ID", LISTAGG("keyword7"."keyword", ', ') AS "KEYWORDS"
FROM "IMDB"."keyword" AS "keyword7"
INNER JOIN "IMDB"."movie_keyword" AS "movie_keyword7" ON "keyword7"."id" = "movie_keyword7"."keyword_id"
GROUP BY "movie_keyword7"."movie_id") AS "t72" ON "t70"."MOVIE_ID" = "t72"."MOVIE_ID") AS "t73" ON "t66"."EXPR$0" < "t73"."CAST_COUNT"
GROUP BY "t73"."PRODUCTION_YEAR") AS "t75"
LEFT JOIN (SELECT "t79"."PRODUCTION_YEAR", AVG(CASE WHEN "t79"."COUNT" IS NOT NULL THEN CAST("t79"."COUNT" AS BIGINT) ELSE 0 END) AS "EXPR$0"
FROM (SELECT "t78"."MOVIE_ID", "t78"."TITLE", "t78"."PRODUCTION_YEAR", "t78"."RAN", "t77"."movie_id" AS "MOVIE_ID0", "t77"."COUNT"
FROM (SELECT "movie_id", COUNT(*) AS "COUNT"
FROM "IMDB"."cast_info"
GROUP BY "movie_id") AS "t77"
RIGHT JOIN (SELECT "id" AS "MOVIE_ID", "title" AS "TITLE", "production_year" AS "PRODUCTION_YEAR", ROW_NUMBER() OVER (PARTITION BY "production_year" ORDER BY "id") AS "RAN"
FROM "IMDB"."aka_title") AS "t78" ON "t77"."movie_id" = "t78"."MOVIE_ID") AS "t79"
LEFT JOIN (SELECT "movie_keyword8"."movie_id" AS "MOVIE_ID", LISTAGG("keyword8"."keyword", ', ') AS "KEYWORDS"
FROM "IMDB"."keyword" AS "keyword8"
INNER JOIN "IMDB"."movie_keyword" AS "movie_keyword8" ON "keyword8"."id" = "movie_keyword8"."keyword_id"
GROUP BY "movie_keyword8"."movie_id") AS "t81" ON "t79"."MOVIE_ID" = "t81"."MOVIE_ID"
GROUP BY "t79"."PRODUCTION_YEAR") AS "t83" ON "t75"."PRODUCTION_YEAR" IS NOT DISTINCT FROM "t83"."PRODUCTION_YEAR") AS "t84" ON "t58"."PRODUCTION_YEAR" = "t84"."PRODUCTION_YEAR"
GROUP BY "t58"."MOVIE_ID") AS "t86"
LEFT JOIN (SELECT "cast_info9"."movie_id", COUNT(DISTINCT "person_info"."id") AS "EXPR$0"
FROM "IMDB"."cast_info" AS "cast_info9"
INNER JOIN "IMDB"."person_info" ON "cast_info9"."person_id" = "person_info"."person_id"
GROUP BY "cast_info9"."movie_id") AS "t88" ON "t86"."MOVIE_ID" IS NOT DISTINCT FROM "t88"."movie_id") AS "t89" ON "t42"."MOVIE_ID" = "t89"."movie_id"
ORDER BY "t42"."PRODUCTION_YEAR" DESC NULLS FIRST, "t42"."CAST_COUNT" DESC NULLS FIRST
FETCH NEXT 100 ROWS ONLY) AS "t92"