SELECT COALESCE("t9"."TITLE", "t9"."TITLE") AS "TITLE", "t9"."PRODUCTION_YEAR", "t9"."TOTAL_CAST", "t9"."CAST_NAMES", "t9"."KEYWORD_COUNT", "t9"."BUDGET_INFO"
FROM (SELECT "t7"."TITLE", "t7"."PRODUCTION_YEAR", "t7"."TOTAL_CAST", "t7"."CAST_NAMES", CASE WHEN "t3"."KEYWORD_COUNT" IS NOT NULL THEN CAST("t3"."KEYWORD_COUNT" AS BIGINT) ELSE 0 END AS "KEYWORD_COUNT", "t3"."BUDGET_INFO"
FROM (SELECT "movie_info"."movie_id" AS "MOVIE_ID", COUNT("movie_keyword"."keyword_id") AS "KEYWORD_COUNT", MAX(CASE WHEN "info_type"."info" = 'Budget' THEN "movie_info"."info" ELSE NULL END) AS "BUDGET_INFO"
FROM "IMDB"."movie_info"
INNER JOIN "IMDB"."info_type" ON "movie_info"."info_type_id" = "info_type"."id"
LEFT JOIN "IMDB"."movie_keyword" ON "movie_info"."movie_id" = "movie_keyword"."movie_id"
GROUP BY "movie_info"."movie_id") AS "t3"
RIGHT JOIN (SELECT ANY_VALUE("t4"."id") AS "MOVIE_ID", "t4"."title" AS "TITLE", "t4"."production_year" AS "PRODUCTION_YEAR", "t4"."kind_id" AS "KIND_ID", COUNT(DISTINCT "t4"."person_id") AS "TOTAL_CAST", LISTAGG(DISTINCT "aka_name"."name", ', ') AS "CAST_NAMES"
FROM "IMDB"."aka_name"
RIGHT JOIN (SELECT "s1"."id", "s1"."movie_id", "s1"."title", "s1"."imdb_index", "s1"."kind_id", "s1"."production_year", "s1"."phonetic_code", "s1"."episode_of_id", "s1"."season_nr", "s1"."episode_nr", "s1"."note", "s1"."md5sum", "s1"."id0", "s1"."movie_id0", "s1"."subject_id", "s1"."status_id", "cast_info"."id" AS "id1", "cast_info"."person_id", "cast_info"."movie_id" AS "movie_id1", "cast_info"."person_role_id", "cast_info"."note" AS "note0", "cast_info"."nr_order", "cast_info"."role_id"
FROM "IMDB"."cast_info"
RIGHT JOIN "s1" ON "cast_info"."id" = "s1"."subject_id") AS "t4" ON "aka_name"."person_id" = "t4"."person_id"
GROUP BY "t4"."id", "t4"."title", "t4"."production_year", "t4"."kind_id") AS "t7" ON "t3"."MOVIE_ID" = "t7"."MOVIE_ID"
ORDER BY "t7"."PRODUCTION_YEAR" DESC NULLS FIRST, "t7"."TOTAL_CAST" DESC NULLS FIRST
FETCH NEXT 100 ROWS ONLY) AS "t9"