SELECT COALESCE("t8"."MOVIE_ID", "t8"."MOVIE_ID") AS "MOVIE_ID", "t8"."TITLE", "t8"."PRODUCTION_YEAR", "t8"."CAST", "t8"."COMPANIES", "t8"."ACTOR_COUNT", "t8"."COMPANY_COUNT"
FROM (SELECT "s1"."MOVIE_ID", "s1"."TITLE", "s1"."PRODUCTION_YEAR", CASE WHEN "s1"."ACTOR_NAMES" IS NOT NULL THEN CAST("s1"."ACTOR_NAMES" AS VARCHAR CHARACTER SET "ISO-8859-1") ELSE 'No Cast' END AS "CAST", CASE WHEN "t5"."COMPANY_NAMES" IS NOT NULL THEN CAST("t5"."COMPANY_NAMES" AS VARCHAR CHARACTER SET "ISO-8859-1") ELSE 'No Companies' END AS "COMPANIES", "s1"."ACTOR_COUNT", "t5"."COMPANY_COUNT"
FROM (SELECT "movie_companies"."movie_id" AS "MOVIE_ID", LISTAGG(DISTINCT "company_name"."name", ', ') AS "COMPANY_NAMES", COUNT(DISTINCT "movie_companies"."company_id") AS "COMPANY_COUNT"
FROM "IMDB"."company_name"
INNER JOIN "IMDB"."movie_companies" ON "company_name"."id" = "movie_companies"."company_id"
GROUP BY "movie_companies"."movie_id") AS "t5"
RIGHT JOIN "s1" ON "t5"."MOVIE_ID" = "s1"."MOVIE_ID"
WHERE "s1"."ACTOR_COUNT" > 5 OR "t5"."COMPANY_COUNT" > 0
ORDER BY "s1"."PRODUCTION_YEAR" DESC NULLS FIRST, "s1"."TITLE") AS "t8"