SELECT COALESCE("t9"."TITLE", "t9"."TITLE") AS "TITLE", "t9"."PRODUCTION_YEAR", "t9"."TOP_ACTOR", "t9"."TOTAL_MOVIES_WITH_ACTOR"
FROM (SELECT "s1"."TITLE", "s1"."PRODUCTION_YEAR", ANY_VALUE("t5"."NAME") AS "TOP_ACTOR", COUNT(DISTINCT "s1"."movie_id") AS "TOTAL_MOVIES_WITH_ACTOR"
FROM "s1"
LEFT JOIN (SELECT "t4"."person_id" AS "PERSON_ID", "aka_name"."name" AS "NAME"
FROM (SELECT MAX("MOVIE_COUNT") AS "EXPR$0"
FROM (SELECT "person_id", COUNT(DISTINCT "movie_id") AS "MOVIE_COUNT"
FROM "IMDB"."cast_info"
GROUP BY "person_id") AS "t2") AS "t3"
INNER JOIN ("IMDB"."aka_name" INNER JOIN (SELECT "person_id", COUNT(DISTINCT "movie_id") AS "MOVIE_COUNT"
FROM "IMDB"."cast_info"
GROUP BY "person_id") AS "t4" ON "aka_name"."person_id" = "t4"."person_id") ON "t3"."EXPR$0" = "t4"."MOVIE_COUNT") AS "t5" ON "s1"."person_id" = "t5"."PERSON_ID"
GROUP BY "s1"."TITLE", "s1"."PRODUCTION_YEAR", "t5"."NAME"
HAVING COUNT(DISTINCT "s1"."movie_id") > 0
ORDER BY "s1"."PRODUCTION_YEAR" DESC NULLS FIRST, "s1"."TITLE") AS "t9"