SELECT COALESCE("t5"."ACTOR_NAME", "t5"."ACTOR_NAME") AS "ACTOR_NAME", "t5"."MOVIE_TITLE", "t5"."PRODUCTION_YEAR", "t5"."MOVIE_KEYWORD", "t5"."COMPANY_NAME", "t5"."COMPANY_TYPE", "t5"."TOTAL_CAST"
FROM (SELECT "t3"."ACTOR_NAME", "t3"."MOVIE_TITLE", "t3"."PRODUCTION_YEAR", "t3"."MOVIE_KEYWORD", "t1"."COMPANY_NAME", "t1"."COMPANY_TYPE", "t2"."TOTAL_CAST"
FROM (SELECT "company_name"."name" AS "COMPANY_NAME", "company_type"."kind" AS "COMPANY_TYPE", "movie_companies"."movie_id" AS "MOVIE_ID"
FROM "IMDB"."company_type"
INNER JOIN ("IMDB"."company_name" INNER JOIN "IMDB"."movie_companies" ON "company_name"."id" = "movie_companies"."company_id") ON "company_type"."id" = "movie_companies"."company_type_id") AS "t1"
INNER JOIN ((SELECT "movie_id", COUNT(DISTINCT "subject_id") AS "TOTAL_CAST"
FROM "IMDB"."complete_cast"
GROUP BY "movie_id") AS "t2" INNER JOIN (SELECT "s1"."name" AS "ACTOR_NAME", "s1"."title" AS "MOVIE_TITLE", "s1"."production_year" AS "PRODUCTION_YEAR", CAST("keyword"."keyword" AS VARCHAR CHARACTER SET "ISO-8859-1") AS "MOVIE_KEYWORD"
FROM "s1"
INNER JOIN "IMDB"."keyword" ON "s1"."keyword_id" = "keyword"."id") AS "t3" ON "t2"."movie_id" = "t3"."PRODUCTION_YEAR") ON "t1"."MOVIE_ID" = "t3"."PRODUCTION_YEAR"
ORDER BY "t3"."PRODUCTION_YEAR" DESC NULLS FIRST, "t2"."TOTAL_CAST" DESC NULLS FIRST) AS "t5"