SELECT COALESCE("t4"."ACTOR_NAME", "t4"."ACTOR_NAME") AS "ACTOR_NAME", "t4"."MOVIE_TITLE", "t4"."PRODUCTION_YEAR", "t4"."COMPANY_TYPE", "t4"."MOVIE_KEYWORD", "t4"."ACTOR_INFO"
FROM (SELECT "aka_name"."name" AS "ACTOR_NAME", "s1"."title" AS "MOVIE_TITLE", "s1"."production_year" AS "PRODUCTION_YEAR", "company_type"."kind" AS "COMPANY_TYPE", "s1"."keyword" AS "MOVIE_KEYWORD", "person_info"."info" AS "ACTOR_INFO"
FROM "IMDB"."company_type"
INNER JOIN ((SELECT "id" AS "ID"
FROM "IMDB"."info_type"
WHERE "info" = 'Biography') AS "t2" INNER JOIN ("IMDB"."cast_info" INNER JOIN ("IMDB"."aka_name" INNER JOIN "IMDB"."person_info" ON "aka_name"."person_id" = "person_info"."person_id") ON "cast_info"."person_id" = "aka_name"."person_id") ON "t2"."ID" = "person_info"."info_type_id" INNER JOIN "s1" ON "cast_info"."movie_id" = "s1"."id1") ON "company_type"."id" = "s1"."company_type_id"
ORDER BY "s1"."production_year" DESC NULLS FIRST, "aka_name"."name") AS "t4"