SELECT COALESCE("ACTOR_NAME", "ACTOR_NAME") AS "ACTOR_NAME", "MOVIE_TITLE", "PRODUCTION_YEAR", "KEYWORDS", "COMPANIES", "ROLE_COUNT", "name"
FROM (SELECT ANY_VALUE("name") AS "ACTOR_NAME", ANY_VALUE("title") AS "MOVIE_TITLE", "PRODUCTION_YEAR", LISTAGG(DISTINCT "keyword", "FD_COL_4") AS "KEYWORDS", LISTAGG(DISTINCT "name0", "FD_COL_4") AS "COMPANIES", COUNT(DISTINCT "id0") AS "ROLE_COUNT", "name"
FROM "s1"
GROUP BY "name", "title", "PRODUCTION_YEAR"
HAVING COUNT(DISTINCT "role_id") > 2
ORDER BY "PRODUCTION_YEAR" DESC NULLS FIRST, "name") AS "t6"