SELECT COALESCE("MOVIE_ID_", "MOVIE_ID_") AS "MOVIE_ID_", "TITLE", "PRODUCTION_YEAR", "COMPANY_NAME", "KEYWORDS", "ACTORS", "TOTAL_CAST_MEMBERS"
FROM (SELECT "MOVIE_ID_", "TITLE", "PRODUCTION_YEAR", "COMPANY_NAME", "KEYWORDS", "ACTORS", COUNT(DISTINCT "id") AS "TOTAL_CAST_MEMBERS"
FROM "s1"
GROUP BY "MOVIE_ID_", "TITLE", "PRODUCTION_YEAR", "COMPANY_NAME", "KEYWORDS", "ACTORS"
ORDER BY "PRODUCTION_YEAR" DESC NULLS FIRST, 7 DESC NULLS FIRST
FETCH NEXT 50 ROWS ONLY) AS "t7"