SELECT COALESCE("keyword"."id", "keyword"."id") AS "id", "keyword"."keyword", "keyword"."phonetic_code", "t2"."id" AS "id0", "t2"."person_id", "t2"."name", "t2"."imdb_index", "t2"."name_pcode_cf", "t2"."name_pcode_nf", "t2"."surname_pcode", "t2"."md5sum", "t2"."id0" AS "id00", "t2"."person_id0", "t2"."movie_id", "t2"."person_role_id", "t2"."note", "t2"."nr_order", "t2"."role_id", "t2"."id1", "t2"."title", "t2"."imdb_index0", "t2"."kind_id", "t2"."production_year", "t2"."imdb_id", "t2"."phonetic_code" AS "phonetic_code0", "t2"."episode_of_id", "t2"."season_nr", "t2"."episode_nr", "t2"."series_years", "t2"."md5sum0", "t2"."id2", "t2"."kind", "t2"."id3", "t2"."person_id1", "t2"."info_type_id", "t2"."info", "t2"."note0", "t2"."id4", "t2"."movie_id0", "t2"."keyword_id"
FROM "IMDB"."keyword"
RIGHT JOIN (SELECT "t1"."id", "t1"."person_id", "t1"."name", "t1"."imdb_index", "t1"."name_pcode_cf", "t1"."name_pcode_nf", "t1"."surname_pcode", "t1"."md5sum", "t1"."id0", "t1"."person_id0", "t1"."movie_id", "t1"."person_role_id", "t1"."note", "t1"."nr_order", "t1"."role_id", "t1"."id1", "t1"."title", "t1"."imdb_index0", "t1"."kind_id", "t1"."production_year", "t1"."imdb_id", "t1"."phonetic_code", "t1"."episode_of_id", "t1"."season_nr", "t1"."episode_nr", "t1"."series_years", "t1"."md5sum0", "t1"."id2", "t1"."kind", "t1"."id3", "t1"."person_id1", "t1"."info_type_id", "t1"."info", "t1"."note0", "movie_keyword"."id" AS "id4", "movie_keyword"."movie_id" AS "movie_id0", "movie_keyword"."keyword_id"
FROM "IMDB"."movie_keyword"
RIGHT JOIN (SELECT "aka_name"."id", "aka_name"."person_id", "aka_name"."name", "aka_name"."imdb_index", "aka_name"."name_pcode_cf", "aka_name"."name_pcode_nf", "aka_name"."surname_pcode", "aka_name"."md5sum", "cast_info"."id" AS "id0", "cast_info"."person_id" AS "person_id0", "cast_info"."movie_id", "cast_info"."person_role_id", "cast_info"."note", "cast_info"."nr_order", "cast_info"."role_id", "t"."id" AS "id1", "t"."title", "t"."imdb_index" AS "imdb_index0", "t"."kind_id", "t"."production_year", "t"."imdb_id", "t"."phonetic_code", "t"."episode_of_id", "t"."season_nr", "t"."episode_nr", "t"."series_years", "t"."md5sum" AS "md5sum0", "t0"."id" AS "id2", "t0"."kind", "person_info"."id" AS "id3", "person_info"."person_id" AS "person_id1", "person_info"."info_type_id", "person_info"."info", "person_info"."note" AS "note0"
FROM "IMDB"."person_info"
RIGHT JOIN ("IMDB"."aka_name" INNER JOIN ((SELECT *
FROM "IMDB"."title"
WHERE "production_year" >= 2000) AS "t" INNER JOIN ("IMDB"."cast_info" INNER JOIN (SELECT *
FROM "IMDB"."comp_cast_type"
WHERE "kind" IN ('actor', 'actress')) AS "t0" ON "cast_info"."person_role_id" = "t0"."id") ON "t"."id" = "cast_info"."movie_id") ON "aka_name"."person_id" = "cast_info"."person_id") ON "person_info"."person_id" = "aka_name"."person_id") AS "t1" ON "movie_keyword"."movie_id" = "t1"."id1") AS "t2" ON "keyword"."id" = "t2"."keyword_id"