SELECT COALESCE("MOVIE_TITLE", "MOVIE_TITLE") AS "MOVIE_TITLE", "PRODUCTION_YEAR", "TOTAL_ACTORS", "KEYWORDS", "ADDITIONAL_INFORMATION"
FROM "s1"
WHERE "TOTAL_ACTORS" > 5
ORDER BY "PRODUCTION_YEAR" DESC NULLS FIRST, "MOVIE_TITLE"