SELECT COALESCE("ACTOR_NAME", "ACTOR_NAME") AS "ACTOR_NAME", "MOVIE_TITLE", "PRODUCTION_YEAR", "CHARACTER_NAME", "COMPANY_TYPE", "KEYWORD_COUNT", "production_year" AS "production_year_"
FROM (SELECT "ACTOR_NAME", "MOVIE_TITLE", "production_year" AS "PRODUCTION_YEAR", "CHARACTER_NAME", "COMPANY_TYPE", "KEYWORD_COUNT", "production_year"
FROM "s1"
ORDER BY "KEYWORD_COUNT" DESC NULLS FIRST, "production_year" DESC NULLS FIRST) AS "t5"