SELECT COALESCE("ACTOR_NAME", "ACTOR_NAME") AS "ACTOR_NAME", "MOVIE_TITLE", "CAST_TYPE", "COMPANY_NAME", "TOTAL_MOVIES"
FROM (SELECT "name0", "title", "kind", "name", ANY_VALUE("name0") AS "ACTOR_NAME", ANY_VALUE("title") AS "MOVIE_TITLE", ANY_VALUE("kind") AS "CAST_TYPE", ANY_VALUE("name") AS "COMPANY_NAME", COUNT(*) AS "TOTAL_MOVIES"
FROM "s1"
GROUP BY "kind", "name", "title", "name0"
ORDER BY 9 DESC NULLS FIRST
FETCH NEXT 50 ROWS ONLY) AS "t4"