SELECT COALESCE("t7"."MOVIE_ID", "t7"."MOVIE_ID") AS "MOVIE_ID", "t7"."TITLE", "t7"."PRODUCTION_YEAR", "t7"."CAST_COUNT", "t7"."ACTORS_LIST", "t7"."KEYWORDS_LIST"
FROM (SELECT "t5"."MOVIE_ID", "t5"."TITLE", "t5"."PRODUCTION_YEAR", "t5"."CAST_COUNT", "t5"."ACTORS_LIST", "t2"."KEYWORDS_LIST"
FROM (SELECT "movie_keyword"."movie_id" AS "MOVIE_ID", LISTAGG("keyword"."keyword", ', ') AS "KEYWORDS_LIST"
FROM "IMDB"."keyword"
INNER JOIN "IMDB"."movie_keyword" ON "keyword"."id" = "movie_keyword"."keyword_id"
GROUP BY "movie_keyword"."movie_id") AS "t2"
RIGHT JOIN (SELECT ANY_VALUE("s1"."id0") AS "MOVIE_ID", "s1"."title" AS "TITLE", "s1"."production_year" AS "PRODUCTION_YEAR", COUNT(DISTINCT "cast_info"."person_id") AS "CAST_COUNT", LISTAGG(DISTINCT "aka_name"."name", ', ') AS "ACTORS_LIST"
FROM "s1"
INNER JOIN ("IMDB"."aka_name" INNER JOIN "IMDB"."cast_info" ON "aka_name"."person_id" = "cast_info"."person_id") ON "s1"."subject_id" = "cast_info"."id"
GROUP BY "s1"."id0", "s1"."title", "s1"."production_year") AS "t5" ON "t2"."MOVIE_ID" = "t5"."MOVIE_ID"
FETCH NEXT 100 ROWS ONLY) AS "t7"