SELECT COALESCE("ACTOR_NAME", "ACTOR_NAME") AS "ACTOR_NAME", "MOVIE_TITLE", "YEAR", "KEYWORDS", "COMPANY_TYPE", "PERSONAL_INFO", "production_year", "name"
FROM (SELECT "ACTOR_NAME", "MOVIE_TITLE", "YEAR", "KEYWORDS", "COMPANY_TYPE", "PERSONAL_INFO", "production_year", "name"
FROM "s1"
ORDER BY "production_year" DESC NULLS FIRST, "name") AS "t8"