SELECT COALESCE("AKA_NAME", "AKA_NAME") AS "AKA_NAME", "TITLE_NAME", "PRODUCTION_YEAR", "ROLE_COUNT"
FROM (SELECT "AKA_NAME", "TITLE_NAME", "PRODUCTION_YEAR", "ROLE_COUNT"
FROM "s1"
ORDER BY "PRODUCTION_YEAR" DESC NULLS FIRST, "ROLE_COUNT" DESC NULLS FIRST) AS "t4"