SELECT COALESCE("t5"."ACTOR_NAME", "t5"."ACTOR_NAME") AS "ACTOR_NAME", "t5"."MOVIE_TITLE", "t5"."PRODUCTION_YEAR", "t5"."KEYWORDS", "t5"."CAST_TYPE", "t5"."COMPANY_NAME", "t5"."ACTOR_INFO", "t5"."name"
FROM (SELECT ANY_VALUE("aka_name"."name") AS "ACTOR_NAME", ANY_VALUE("s1"."title") AS "MOVIE_TITLE", "s1"."production_year" AS "PRODUCTION_YEAR", LISTAGG(DISTINCT "keyword"."keyword", ', ') AS "KEYWORDS", ANY_VALUE("comp_cast_type"."kind") AS "CAST_TYPE", ANY_VALUE("s1"."name") AS "COMPANY_NAME", ANY_VALUE("person_info"."info") AS "ACTOR_INFO", "aka_name"."name"
FROM "IMDB"."comp_cast_type"
INNER JOIN ("IMDB"."role_type" INNER JOIN "IMDB"."cast_info" ON "role_type"."id" = "cast_info"."role_id") ON "comp_cast_type"."id" = "cast_info"."person_role_id"
INNER JOIN ("IMDB"."aka_name" INNER JOIN "IMDB"."person_info" ON "aka_name"."person_id" = "person_info"."person_id") ON "cast_info"."person_id" = "aka_name"."person_id"
INNER JOIN ("IMDB"."keyword" INNER JOIN "IMDB"."movie_keyword" ON "keyword"."id" = "movie_keyword"."keyword_id" INNER JOIN "s1" ON "movie_keyword"."movie_id" = "s1"."id00") ON "cast_info"."movie_id" = "s1"."id00"
GROUP BY "aka_name"."name", "s1"."title", "s1"."production_year", "comp_cast_type"."kind", "s1"."name", "person_info"."info"
ORDER BY "s1"."production_year" DESC NULLS FIRST, "aka_name"."name") AS "t5"