SELECT COALESCE("t5"."ACTOR_NAME", "t5"."ACTOR_NAME") AS "ACTOR_NAME", "t5"."MOVIE_TITLE", "t5"."production_year" AS "PRODUCTION_YEAR", "t5"."COMPANY_TYPE", "t5"."MOVIE_INFO", "t5"."KEYWORD_COUNT", "t5"."production_year" AS "production_year_"
FROM (SELECT "t3"."name", "t3"."title", "t3"."production_year", "t3"."info", ANY_VALUE("t3"."name") AS "ACTOR_NAME", ANY_VALUE("t3"."title") AS "MOVIE_TITLE", ANY_VALUE("t3"."kind") AS "COMPANY_TYPE", ANY_VALUE("t3"."info") AS "MOVIE_INFO", COUNT(DISTINCT "keyword"."keyword") AS "KEYWORD_COUNT"
FROM (SELECT "t1"."id", "t1"."person_id", "t1"."name", "t1"."imdb_index", "t1"."name_pcode_cf", "t1"."name_pcode_nf", "t1"."surname_pcode", "t1"."md5sum", "cast_info"."id" AS "id0", "cast_info"."person_id" AS "person_id0", "cast_info"."movie_id", "cast_info"."person_role_id", "cast_info"."note", "cast_info"."nr_order", "cast_info"."role_id", "t2"."id" AS "id1", "t2"."title", "t2"."imdb_index" AS "imdb_index0", "t2"."kind_id", "t2"."production_year", "t2"."imdb_id", "t2"."phonetic_code", "t2"."episode_of_id", "t2"."season_nr", "t2"."episode_nr", "t2"."series_years", "t2"."md5sum" AS "md5sum0", "movie_companies"."id" AS "id2", "movie_companies"."movie_id" AS "movie_id0", "movie_companies"."company_id", "movie_companies"."company_type_id", "movie_companies"."note" AS "note0", "company_name"."id" AS "id3", "company_name"."name" AS "name0", "company_name"."country_code", "company_name"."imdb_id" AS "imdb_id0", "company_name"."name_pcode_nf" AS "name_pcode_nf0", "company_name"."name_pcode_sf", "company_name"."md5sum" AS "md5sum1", "s1"."id" AS "id4", "s1"."kind", "movie_info"."id" AS "id5", "movie_info"."movie_id" AS "movie_id1", "movie_info"."info_type_id", "movie_info"."info", "movie_info"."note" AS "note1", "movie_keyword"."id" AS "id6", "movie_keyword"."movie_id" AS "movie_id2", "movie_keyword"."keyword_id"
FROM "IMDB"."movie_keyword"
RIGHT JOIN ("IMDB"."movie_info" INNER JOIN ("IMDB"."cast_info" INNER JOIN (SELECT *
FROM "IMDB"."aka_name"
WHERE "name" LIKE 'A%') AS "t1" ON "cast_info"."person_id" = "t1"."person_id" INNER JOIN ("IMDB"."company_name" INNER JOIN ("IMDB"."movie_companies" INNER JOIN (SELECT *
FROM "IMDB"."title"
WHERE "production_year" >= 2000) AS "t2" ON "movie_companies"."movie_id" = "t2"."id" INNER JOIN "s1" ON "movie_companies"."company_type_id" = "s1"."id") ON "company_name"."id" = "movie_companies"."company_id") ON "cast_info"."movie_id" = "t2"."id") ON "movie_info"."movie_id" = "t2"."id") ON "movie_keyword"."movie_id" = "t2"."id") AS "t3"
LEFT JOIN "IMDB"."keyword" ON "t3"."keyword_id" = "keyword"."id"
GROUP BY "t3"."name", "t3"."title", "t3"."production_year", "t3"."info"
ORDER BY 9 DESC NULLS FIRST, "t3"."production_year" DESC NULLS FIRST) AS "t5"