SELECT COALESCE("ACTOR_NAME", "ACTOR_NAME") AS "ACTOR_NAME", "MOVIE_TITLE", "COMPANY_TYPE", "MOVIE_KEYWORD", "PERSON_INFO", "production_year"
FROM (SELECT "name0" AS "ACTOR_NAME", "title" AS "MOVIE_TITLE", "kind" AS "COMPANY_TYPE", "keyword" AS "MOVIE_KEYWORD", "info" AS "PERSON_INFO", "production_year"
FROM "s1"
ORDER BY "production_year" DESC NULLS FIRST, "name0") AS "t4"