SELECT COALESCE("role_type"."id", "role_type"."id") AS "id", "role_type"."role", "cast_info"."id" AS "id0", "cast_info"."person_id", "cast_info"."movie_id", "cast_info"."person_role_id", "cast_info"."note", "cast_info"."nr_order", "cast_info"."role_id", "aka_name"."id" AS "id1", "aka_name"."person_id" AS "person_id0", "aka_name"."name", "aka_name"."imdb_index", "aka_name"."name_pcode_cf", "aka_name"."name_pcode_nf", "aka_name"."surname_pcode", "aka_name"."md5sum", "person_info"."id" AS "id00", "person_info"."person_id" AS "person_id00", "person_info"."info_type_id", "person_info"."info", "person_info"."note" AS "note0", "t"."id" AS "id2", "t"."keyword", "t"."phonetic_code", "movie_keyword"."id" AS "id01", "movie_keyword"."movie_id" AS "movie_id0", "movie_keyword"."keyword_id", "company_type"."id" AS "id10", "company_type"."kind", "t0"."id" AS "id000", "t0"."name" AS "name0", "t0"."country_code", "t0"."imdb_id", "t0"."name_pcode_nf" AS "name_pcode_nf0", "t0"."name_pcode_sf", "t0"."md5sum" AS "md5sum0", "movie_companies"."id" AS "id0000", "movie_companies"."movie_id" AS "movie_id00", "movie_companies"."company_id", "movie_companies"."company_type_id", "movie_companies"."note" AS "note1", "complete_cast"."id" AS "id100", "complete_cast"."movie_id" AS "movie_id000", "complete_cast"."subject_id", "complete_cast"."status_id", "t1"."id" AS "id010", "t1"."title", "t1"."imdb_index" AS "imdb_index0", "t1"."kind_id", "t1"."production_year", "t1"."imdb_id" AS "imdb_id0", "t1"."phonetic_code" AS "phonetic_code0", "t1"."episode_of_id", "t1"."season_nr", "t1"."episode_nr", "t1"."series_years", "t1"."md5sum" AS "md5sum00"
FROM "IMDB"."role_type"
INNER JOIN "IMDB"."cast_info" ON "role_type"."id" = "cast_info"."role_id"
INNER JOIN ("IMDB"."aka_name" INNER JOIN "IMDB"."person_info" ON "aka_name"."person_id" = "person_info"."person_id") ON "cast_info"."person_id" = "aka_name"."person_id"
INNER JOIN ((SELECT *
FROM "IMDB"."keyword"
WHERE "keyword" LIKE '%Drama%') AS "t" INNER JOIN "IMDB"."movie_keyword" ON "t"."id" = "movie_keyword"."keyword_id" INNER JOIN ("IMDB"."company_type" INNER JOIN ((SELECT *
FROM "IMDB"."company_name"
WHERE "country_code" = 'USA') AS "t0" INNER JOIN "IMDB"."movie_companies" ON "t0"."id" = "movie_companies"."company_id") ON "company_type"."id" = "movie_companies"."company_type_id" INNER JOIN ("IMDB"."complete_cast" INNER JOIN (SELECT *
FROM "IMDB"."title"
WHERE "production_year" > 2000) AS "t1" ON "complete_cast"."movie_id" = "t1"."id") ON "movie_companies"."movie_id" = "t1"."id") ON "movie_keyword"."movie_id" = "t1"."id") ON "cast_info"."movie_id" = "t1"."id"