SELECT COALESCE("L_ORDERKEY", "L_ORDERKEY") AS "L_ORDERKEY", "REVENUE", "O_ORDERDATE", "C_NAME", "S_NAME", "P_NAME", "N_NAME", "R_NAME"
FROM "s1"
ORDER BY "REVENUE" DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY