SELECT COALESCE("SUPPLIER_NAME", "SUPPLIER_NAME") AS "SUPPLIER_NAME", "TOTAL_AVAILABLE_QTY", "UNIQUE_PARTS_SUPPLIED", "SUPPLIED_PART_DETAILS", "NATION_NAME", "DETAILED_INFO"
FROM "s1"
ORDER BY "TOTAL_AVAILABLE_QTY" DESC NULLS FIRST, "UNIQUE_PARTS_SUPPLIED" DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY