SELECT COALESCE("P_NAME", "P_NAME") AS "P_NAME", "SUPPLIER_NAME", "CUSTOMER_NAME", "O_ORDERDATE", "TOTAL_REVENUE", "TOTAL_ORDERS", "SHORT_COMMENT", "SUPPLIER_INFO", "o_orderdate" AS "o_orderdate_"
FROM (SELECT "P_NAME", ANY_VALUE("s_name") AS "SUPPLIER_NAME", ANY_VALUE("c_name") AS "CUSTOMER_NAME", "O_ORDERDATE", SUM("FD_COL_5") AS "TOTAL_REVENUE", COUNT(DISTINCT "o_orderkey") AS "TOTAL_ORDERS", ANY_VALUE("FD_COL_7") AS "SHORT_COMMENT", ANY_VALUE("FD_COL_8") AS "SUPPLIER_INFO", "O_ORDERDATE" AS "o_orderdate"
FROM "s1"
GROUP BY "P_NAME", "s_name", "c_name", "O_ORDERDATE", "p_comment"
ORDER BY 5 DESC NULLS FIRST, "O_ORDERDATE" DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY) AS "t4"