SELECT COALESCE("SUPPLIER_INFO", "SUPPLIER_INFO") AS "SUPPLIER_INFO", "PART_NAME", "AVAILABLE_QUANTITY", "MODIFIED_COMMENT", "ORDER_COUNT", "TOTAL_REVENUE", "REVENUE_CATEGORY"
FROM "s1"
ORDER BY "TOTAL_REVENUE" DESC NULLS FIRST, "SUPPLIER_INFO"
FETCH NEXT 100 ROWS ONLY