SELECT COALESCE("SHORT_NAME", "SHORT_NAME") AS "SHORT_NAME", "NATION_COUNT", "AVG_SUPPLY_COST", "MARKET_SEGMENTS", "MAX_ORDER_PRICE"
FROM "s1"
ORDER BY "AVG_SUPPLY_COST" DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY