SELECT COALESCE(ANY_VALUE("t1"."Id"), ANY_VALUE("t1"."Id")) AS "POSTID", COUNT(*) AS "REVCOUNT", MAX("t1"."CREATIONDATE") AS "LASTREVISION", COUNT(DISTINCT "t1"."UserId") AS "USERCOUNT", ANY_VALUE(CASE WHEN "t9"."EXPR$0" IS NULL THEN 0 ELSE "t9"."EXPR$0" END) AS "TOTALDOWNVOTES"
FROM (SELECT "Posts"."Id", "Posts"."PostTypeId", "Posts"."AcceptedAnswerId", "Posts"."ParentId", "Posts"."CreationDate", "Posts"."Score", "Posts"."ViewCount", "Posts"."Body", "Posts"."OwnerUserId", "Posts"."OwnerDisplayName", "Posts"."LastEditorUserId", "Posts"."LastEditorDisplayName", "Posts"."LastEditDate", "Posts"."LastActivityDate", "Posts"."Title", "Posts"."Tags", "Posts"."AnswerCount", "Posts"."CommentCount", "Posts"."FavoriteCount", "Posts"."ClosedDate", "Posts"."CommunityOwnedDate", "Posts"."ContentLicense", "t0"."POSTID", "t0"."USERID", "t0"."CREATIONDATE", "t0"."COMMENT", "t0"."TEXT", "t0"."REVISIONRANK", "PostHistory"."Id" AS "Id0", "PostHistory"."PostHistoryTypeId", "PostHistory"."PostId", "PostHistory"."RevisionGUID", "PostHistory"."CreationDate" AS "CreationDate0", "PostHistory"."UserId", "PostHistory"."UserDisplayName", "PostHistory"."Comment", "PostHistory"."Text", "PostHistory"."ContentLicense" AS "ContentLicense0"
FROM "PostHistory"
RIGHT JOIN ("Posts" INNER JOIN (SELECT "PostId" AS "POSTID", "UserId" AS "USERID", "CreationDate" AS "CREATIONDATE", "Comment" AS "COMMENT", "Text" AS "TEXT", ROW_NUMBER() OVER (PARTITION BY "PostId" ORDER BY "CreationDate" DESC NULLS FIRST) AS "REVISIONRANK"
FROM "PostHistory"
WHERE CAST("PostHistoryTypeId" AS INTEGER) IN (10, 11)) AS "t0" ON "Posts"."Id" = "t0"."POSTID") ON "PostHistory"."PostId" = "Posts"."Id") AS "t1"
LEFT JOIN (SELECT "t5"."Id" AS "PostId", CASE WHEN "t8"."EXPR$0" IS NOT NULL THEN "t8"."EXPR$0" ELSE 0 END AS "EXPR$0"
FROM (SELECT "Posts0"."Id"
FROM "PostHistory" AS "PostHistory1"
RIGHT JOIN ("Posts" AS "Posts0" INNER JOIN (SELECT "PostId" AS "POSTID", "UserId" AS "USERID", "CreationDate" AS "CREATIONDATE", "Comment" AS "COMMENT", "Text" AS "TEXT", ROW_NUMBER() OVER (PARTITION BY "PostId" ORDER BY "CreationDate" DESC NULLS FIRST) AS "REVISIONRANK"
FROM "PostHistory"
WHERE CAST("PostHistoryTypeId" AS INTEGER) IN (10, 11)) AS "t3" ON "Posts0"."Id" = "t3"."POSTID") ON "PostHistory1"."PostId" = "Posts0"."Id"
GROUP BY "Posts0"."Id") AS "t5"
LEFT JOIN (SELECT "PostId", COUNT(*) AS "EXPR$0"
FROM "Votes"
WHERE CAST("VoteTypeId" AS INTEGER) = 3
GROUP BY "PostId") AS "t8" ON "t5"."Id" IS NOT DISTINCT FROM "t8"."PostId") AS "t9" ON "t1"."Id" = "t9"."PostId"
GROUP BY "t1"."Id"