SELECT COALESCE("L_ORDERKEY", "L_ORDERKEY") AS "L_ORDERKEY", "TOTAL_REVENUE", "O_ORDERDATE", "C_NAME", "S_NAME"
FROM (SELECT "L_ORDERKEY", "TOTAL_REVENUE", "O_ORDERDATE", "C_NAME", "S_NAME"
FROM "s1"
ORDER BY "TOTAL_REVENUE" DESC NULLS FIRST
FETCH NEXT 100 ROWS ONLY) AS "t3"