SELECT COALESCE("SUPPLIER_INFO", "SUPPLIER_INFO") AS "SUPPLIER_INFO", "PART_NAME", "UPDATED_COMMENT", "TOTAL_ORDERS", "TOTAL_REVENUE", "REGION_NAME"
FROM (SELECT "SUPPLIER_INFO", "PART_NAME", "UPDATED_COMMENT", "TOTAL_ORDERS", "TOTAL_REVENUE", "REGION_NAME"
FROM "s1"
ORDER BY "TOTAL_REVENUE" DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY) AS "t5"