SELECT COALESCE("t8"."POSTTYPE", "t8"."POSTTYPE") AS "POSTTYPE", "t8"."TOTALPOSTS", "t8"."TOTALQUESTIONS", "t8"."TOTALANSWERS", "t8"."TOTALVIEWS", "t8"."AVGSCORE", "t8"."AVGANSWERSPERQUESTION", "t8"."TOTALUSERS", "t8"."TOTALREPUTATION", "t8"."AVGREPUTATION", "t8"."ACTIVEUSERS", "t8"."RECENTUSERS", "t8"."TOTALCOMMENTS", "t8"."AVGCOMMENTLENGTH", "t8"."POSITIVECOMMENTS"
FROM (SELECT "s1"."POSTTYPE", "s1"."TOTALPOSTS", "s1"."TOTALQUESTIONS", "s1"."TOTALANSWERS", "s1"."TOTALVIEWS", "s1"."AVGSCORE", "s1"."AVGANSWERSPERQUESTION", "t4"."TOTALUSERS", "t4"."TOTALREPUTATION", "t4"."AVGREPUTATION", "t4"."ACTIVEUSERS", "t4"."RECENTUSERS", "t6"."TOTALCOMMENTS", "t6"."AVGCOMMENTLENGTH", "t6"."POSITIVECOMMENTS"
FROM (SELECT COUNT(*) AS "TOTALUSERS", SUM("Reputation") AS "TOTALREPUTATION", AVG("Reputation") AS "AVGREPUTATION", COUNT(DISTINCT CASE WHEN "UpVotes" > 0 THEN "Id" ELSE NULL END) AS "ACTIVEUSERS", SUM(CASE WHEN "LastAccessDate" > CAST((DATE '2024-10-01' - INTERVAL '30' DAY) AS TIMESTAMP(0)) THEN 1 ELSE 0 END) AS "RECENTUSERS"
FROM "STACK"."Users") AS "t4",
(SELECT COUNT(*) AS "TOTALCOMMENTS", AVG(LENGTH("Text")) AS "AVGCOMMENTLENGTH", SUM(CASE WHEN "Score" > 0 THEN 1 ELSE 0 END) AS "POSITIVECOMMENTS"
FROM "STACK"."Comments") AS "t6",
"s1"
ORDER BY "s1"."TOTALPOSTS" DESC NULLS FIRST) AS "t8"