SELECT COALESCE("t4"."POSTTYPE", "t4"."POSTTYPE") AS "POSTTYPE", "t4"."POSTCOUNT", "t4"."AVERAGESCORE", "t4"."UNIQUEUSERSWITHBADGES"
FROM (SELECT "s1"."POSTTYPE", "s1"."POSTCOUNT", "s1"."AVERAGESCORE", "t2"."UNIQUEUSERSWITHBADGES"
FROM (SELECT COUNT(DISTINCT "UserId") AS "UNIQUEUSERSWITHBADGES"
FROM "STACK"."Badges") AS "t2",
"s1"
ORDER BY "s1"."POSTTYPE") AS "t4"