SELECT COALESCE("t5"."Id", "t5"."Id") AS "Id"
FROM (SELECT "t"."Id", "t"."PostTypeId", "t"."AcceptedAnswerId", "t"."ParentId", "t"."CreationDate", "t"."Score", "t"."ViewCount", "t"."Body", "t"."OwnerUserId", "t"."OwnerDisplayName", "t"."LastEditorUserId", "t"."LastEditorDisplayName", "t"."LastEditDate", "t"."LastActivityDate", "t"."Title", "t"."Tags", "t"."AnswerCount", "t"."CommentCount", "t"."FavoriteCount", "t"."ClosedDate", "t"."CommunityOwnedDate", "t"."ContentLicense", CASE WHEN "t4"."EXPR$0" IS NULL THEN 0 ELSE "t4"."EXPR$0" END AS "EXPR$0"
FROM (SELECT *
FROM "STACK"."Posts"
WHERE CAST("PostTypeId" AS INTEGER) = 1) AS "t"
LEFT JOIN (SELECT "t1"."Id" AS "PostId", CASE WHEN "t3"."EXPR$0" IS NOT NULL THEN "t3"."EXPR$0" ELSE 0 END AS "EXPR$0"
FROM (SELECT "Id"
FROM "STACK"."Posts"
WHERE CAST("PostTypeId" AS INTEGER) = 1) AS "t1"
LEFT JOIN (SELECT "PostId", COUNT(*) AS "EXPR$0"
FROM "STACK"."Comments"
GROUP BY "PostId") AS "t3" ON "t1"."Id" IS NOT DISTINCT FROM "t3"."PostId") AS "t4" ON "t"."Id" = "t4"."PostId") AS "t5"
LEFT JOIN (SELECT "t13"."Id" AS "PostId", CASE WHEN "t15"."EXPR$0" IS NOT NULL THEN "t15"."EXPR$0" ELSE 0 END AS "EXPR$0"
FROM (SELECT "t6"."Id"
FROM (SELECT *
FROM "STACK"."Posts"
WHERE CAST("PostTypeId" AS INTEGER) = 1) AS "t6"
LEFT JOIN (SELECT "t8"."Id" AS "PostId", CASE WHEN "t10"."EXPR$0" IS NOT NULL THEN "t10"."EXPR$0" ELSE 0 END AS "EXPR$0"
FROM (SELECT "Id"
FROM "STACK"."Posts"
WHERE CAST("PostTypeId" AS INTEGER) = 1) AS "t8"
LEFT JOIN (SELECT "PostId", COUNT(*) AS "EXPR$0"
FROM "STACK"."Comments"
GROUP BY "PostId") AS "t10" ON "t8"."Id" IS NOT DISTINCT FROM "t10"."PostId") AS "t11" ON "t6"."Id" = "t11"."PostId"
GROUP BY "t6"."Id") AS "t13"
LEFT JOIN (SELECT "PostId", COUNT(*) AS "EXPR$0"
FROM "STACK"."Votes"
GROUP BY "PostId") AS "t15" ON "t13"."Id" IS NOT DISTINCT FROM "t15"."PostId") AS "t16" ON "t5"."Id" = "t16"."PostId"
GROUP BY "t5"."Id"