SELECT COALESCE("DISPLAYNAME", "DISPLAYNAME") AS "DISPLAYNAME", "POSTCOUNT", "VOTECOUNT", "COMMENTCOUNT"
FROM (SELECT "DisplayName" AS "DISPLAYNAME", "POSTCOUNT", "VOTECOUNT", "COMMENTCOUNT"
FROM "s1"
ORDER BY "POSTCOUNT" DESC NULLS FIRST, "VOTECOUNT" DESC NULLS FIRST, "COMMENTCOUNT" DESC NULLS FIRST
FETCH NEXT 100 ROWS ONLY) AS "t5"