SELECT COALESCE("t10"."POSTID", "t10"."POSTID") AS "POSTID", "t10"."TITLE", "t10"."TAGSLIST", "t10"."USERDISPLAYNAME", "t10"."TOTALPOSTS", "t10"."TOTALVIEWS", "t10"."TOTALANSWERED", "t10"."HIGHENGAGEMENTPOSTS", "t10"."TOTALMODERATIONHISTORY", "t10"."TOTALCLOSURES", "t10"."TOTALREOPENS"
FROM (SELECT "t7"."POSTID", "t7"."TITLE", "t7"."TAGSLIST", "t4"."DISPLAYNAME" AS "USERDISPLAYNAME", "t4"."TOTALPOSTS", "t4"."TOTALVIEWS", "t4"."TOTALANSWERED", "t4"."HIGHENGAGEMENTPOSTS", "t7"."TOTALMODERATIONHISTORY", "t7"."TOTALCLOSURES", "t7"."TOTALREOPENS"
FROM (SELECT ANY_VALUE("Users"."Id") AS "USERID", "Users"."DisplayName" AS "DISPLAYNAME", COUNT(DISTINCT "t1"."Id") AS "TOTALPOSTS", SUM("t1"."ViewCount") AS "TOTALVIEWS", SUM(CASE WHEN "t1"."AnswerCount" > 0 THEN 1 ELSE 0 END) AS "TOTALANSWERED", SUM(CASE WHEN "t1"."ViewCount" > 100 THEN 1 ELSE 0 END) AS "HIGHENGAGEMENTPOSTS"
FROM "STACK"."Users"
INNER JOIN (SELECT *
FROM "STACK"."Posts"
WHERE "CreationDate" >= (TIMESTAMP '2024-10-01 12:34:56' - INTERVAL '1' YEAR)) AS "t1" ON "Users"."Id" = "t1"."OwnerUserId"
GROUP BY "Users"."Id", "Users"."DisplayName") AS "t4"
INNER JOIN (SELECT ANY_VALUE("s1"."Id") AS "POSTID", "s1"."Title" AS "TITLE", "s1"."ViewCount" AS "VIEWCOUNT", "s1"."AnswerCount" AS "ANSWERCOUNT", "s1"."CreationDate" AS "CREATIONDATE", LISTAGG(DISTINCT "Tags"."TagName", ', ') AS "TAGSLIST", COUNT(DISTINCT "PostHistory"."UserId") AS "TOTALMODERATIONHISTORY", SUM(CASE WHEN CAST("PostHistory"."PostHistoryTypeId" AS INTEGER) = 10 THEN 1 ELSE 0 END) AS "TOTALCLOSURES", SUM(CASE WHEN CAST("PostHistory"."PostHistoryTypeId" AS INTEGER) = 11 THEN 1 ELSE 0 END) AS "TOTALREOPENS", CAST(ANY_VALUE("s1"."Id") AS BIGINT) AS "POSTID0"
FROM "s1"
LEFT JOIN "STACK"."Tags" ON POSITION("Tags"."TagName" IN "s1"."Tags") > 0
LEFT JOIN "STACK"."PostHistory" ON "s1"."Id" = "PostHistory"."PostId"
GROUP BY "s1"."Id", "s1"."Title", "s1"."ViewCount", "s1"."AnswerCount", "s1"."CreationDate") AS "t7" ON "t4"."TOTALPOSTS" = "t7"."POSTID0"
WHERE "t4"."TOTALVIEWS" > 500
ORDER BY "t4"."TOTALANSWERED" DESC NULLS FIRST) AS "t10"