SELECT COALESCE("t9"."USERID", "t9"."USERID") AS "USERID", "t9"."DisplayName" AS "DISPLAYNAME", "t9"."TOTALBADGES", "t9"."GOLDBADGES", "t9"."SILVERBADGES", "t9"."BRONZEBADGES", "t9"."RECENTPOSTCOUNT", "t9"."TOTALCOMMENTS", "t9"."TOTALVOTES"
FROM (SELECT "Users0"."Id", "Users0"."DisplayName", "s1"."TOTALBADGES", "s1"."GOLDBADGES", "s1"."SILVERBADGES", "s1"."BRONZEBADGES", ANY_VALUE("Users0"."Id") AS "USERID", COUNT("s1"."TITLE") AS "RECENTPOSTCOUNT", SUM("s1"."COMMENTCOUNT") AS "TOTALCOMMENTS", SUM("s1"."VOTECOUNT") AS "TOTALVOTES"
FROM "s1"
LEFT JOIN "STACK"."Users" AS "Users0" ON "s1"."USERID" = "Users0"."Id"
GROUP BY "s1"."TOTALBADGES", "s1"."GOLDBADGES", "s1"."SILVERBADGES", "s1"."BRONZEBADGES", "Users0"."Id", "Users0"."DisplayName"
ORDER BY "s1"."TOTALBADGES" DESC NULLS FIRST, 9 DESC NULLS FIRST, 8 DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY) AS "t9"