SELECT COALESCE("t9"."POSTID", "t9"."POSTID") AS "POSTID", "t9"."TITLE", "t9"."VIEWCOUNT", "t9"."VOTECOUNT", "t9"."UPVOTES", "t9"."DOWNVOTES", "t9"."USERBADGECOUNT", "t9"."GOLDBADGES", "t9"."SILVERBADGES", "t9"."BRONZEBADGES"
FROM (SELECT "Posts0"."Id" AS "POSTID", "Posts0"."Title" AS "TITLE", "Posts0"."ViewCount" AS "VIEWCOUNT", "s1"."VOTECOUNT", "s1"."UPVOTES", "s1"."DOWNVOTES", CASE WHEN "t6"."BADGECOUNT" IS NOT NULL THEN CAST("t6"."BADGECOUNT" AS BIGINT) ELSE 0 END AS "USERBADGECOUNT", CASE WHEN "t6"."GOLDBADGES" IS NOT NULL THEN CAST("t6"."GOLDBADGES" AS INTEGER) ELSE 0 END AS "GOLDBADGES", CASE WHEN "t6"."SILVERBADGES" IS NOT NULL THEN CAST("t6"."SILVERBADGES" AS INTEGER) ELSE 0 END AS "SILVERBADGES", CASE WHEN "t6"."BRONZEBADGES" IS NOT NULL THEN CAST("t6"."BRONZEBADGES" AS INTEGER) ELSE 0 END AS "BRONZEBADGES"
FROM (SELECT ANY_VALUE("Users"."Id") AS "USERID", COUNT("Badges"."Id") AS "BADGECOUNT", SUM(CASE WHEN CAST("Badges"."Class" AS INTEGER) = 1 THEN 1 ELSE 0 END) AS "GOLDBADGES", SUM(CASE WHEN CAST("Badges"."Class" AS INTEGER) = 2 THEN 1 ELSE 0 END) AS "SILVERBADGES", SUM(CASE WHEN CAST("Badges"."Class" AS INTEGER) = 3 THEN 1 ELSE 0 END) AS "BRONZEBADGES"
FROM "STACK"."Badges"
RIGHT JOIN "STACK"."Users" ON "Badges"."UserId" = "Users"."Id"
GROUP BY "Users"."Id") AS "t6"
RIGHT JOIN ("STACK"."Posts" AS "Posts0" INNER JOIN "s1" ON "Posts0"."Id" = "s1"."POSTID") ON "t6"."USERID" = "s1"."OWNERUSERID"
WHERE "Posts0"."ViewCount" > 1000
ORDER BY "s1"."UPVOTES" DESC NULLS FIRST, "Posts0"."ViewCount" DESC NULLS FIRST
FETCH NEXT 50 ROWS ONLY) AS "t9"