SELECT COALESCE("t22"."USERID", "t22"."USERID") AS "USERID"
FROM (SELECT "t7"."USERID", "t7"."DISPLAYNAME", "t7"."TOTALPOSTS", "t7"."TOTALSCORE", "t7"."UPVOTECOUNT", "t7"."DOWNVOTECOUNT", "t7"."AVGCOMMENTSPERPOST", CASE WHEN "t21"."EXPR$0" IS NULL THEN 0 ELSE "t21"."EXPR$0" END AS "EXPR$0"
FROM (SELECT ANY_VALUE("t3"."Id") AS "USERID", "t3"."DisplayName" AS "DISPLAYNAME", COUNT(DISTINCT "Posts0"."Id") AS "TOTALPOSTS", SUM("Posts0"."Score") AS "TOTALSCORE", SUM("t3"."UpVotes") AS "UPVOTECOUNT", SUM("t3"."DownVotes") AS "DOWNVOTECOUNT", AVG(CASE WHEN "t3"."COMMENTCOUNT" IS NOT NULL THEN CAST("t3"."COMMENTCOUNT" AS BIGINT) ELSE 0 END) AS "AVGCOMMENTSPERPOST"
FROM (SELECT "Users"."Id", "Users"."Reputation", "Users"."CreationDate", "Users"."DisplayName", "Users"."LastAccessDate", "Users"."WebsiteUrl", "Users"."Location", "Users"."AboutMe", "Users"."Views", "Users"."UpVotes", "Users"."DownVotes", "Users"."ProfileImageUrl", "Users"."AccountId", "t2"."POSTID", "t2"."TITLE", "t2"."SCORE", "t2"."CREATIONDATE", "t2"."OWNERUSERID", "t2"."RAN", "t2"."COMMENTCOUNT"
FROM (SELECT "t1"."Id" AS "POSTID", "t1"."Title" AS "TITLE", "t1"."Score" AS "SCORE", "t1"."CreationDate" AS "CREATIONDATE", "t1"."OwnerUserId" AS "OWNERUSERID", RANK() OVER (PARTITION BY "t1"."OwnerUserId" ORDER BY "t1"."Score" DESC NULLS FIRST) AS "RAN", CASE WHEN "t0"."COMMENTCOUNT" IS NOT NULL THEN CAST("t0"."COMMENTCOUNT" AS BIGINT) ELSE 0 END AS "COMMENTCOUNT"
FROM (SELECT "PostId", COUNT(*) AS "COMMENTCOUNT"
FROM "STACK"."Comments"
GROUP BY "PostId") AS "t0"
RIGHT JOIN (SELECT *
FROM "STACK"."Posts"
WHERE "CreationDate" >= (TIMESTAMP '2024-10-01 12:34:56' - INTERVAL '1' YEAR)) AS "t1" ON "t0"."PostId" = "t1"."Id") AS "t2"
RIGHT JOIN "STACK"."Users" ON "t2"."OWNERUSERID" = "Users"."Id") AS "t3"
LEFT JOIN "STACK"."Posts" AS "Posts0" ON "t3"."Id" = "Posts0"."OwnerUserId"
GROUP BY "t3"."Id", "t3"."DisplayName"
HAVING COUNT(DISTINCT "Posts0"."Id") > 0) AS "t7"
LEFT JOIN (SELECT "t17"."USERID" AS "UserId", CASE WHEN "t20"."EXPR$0" IS NOT NULL THEN "t20"."EXPR$0" ELSE 0 END AS "EXPR$0"
FROM (SELECT "t16"."USERID"
FROM (SELECT ANY_VALUE("t12"."Id") AS "USERID"
FROM (SELECT "Users0"."Id", "Users0"."Reputation", "Users0"."CreationDate", "Users0"."DisplayName", "Users0"."LastAccessDate", "Users0"."WebsiteUrl", "Users0"."Location", "Users0"."AboutMe", "Users0"."Views", "Users0"."UpVotes", "Users0"."DownVotes", "Users0"."ProfileImageUrl", "Users0"."AccountId", "t11"."POSTID", "t11"."TITLE", "t11"."SCORE", "t11"."CREATIONDATE", "t11"."OWNERUSERID", "t11"."RAN", "t11"."COMMENTCOUNT"
FROM (SELECT "t10"."Id" AS "POSTID", "t10"."Title" AS "TITLE", "t10"."Score" AS "SCORE", "t10"."CreationDate" AS "CREATIONDATE", "t10"."OwnerUserId" AS "OWNERUSERID", RANK() OVER (PARTITION BY "t10"."OwnerUserId" ORDER BY "t10"."Score" DESC NULLS FIRST) AS "RAN", CASE WHEN "t9"."COMMENTCOUNT" IS NOT NULL THEN CAST("t9"."COMMENTCOUNT" AS BIGINT) ELSE 0 END AS "COMMENTCOUNT"
FROM (SELECT "PostId", COUNT(*) AS "COMMENTCOUNT"
FROM "STACK"."Comments"
GROUP BY "PostId") AS "t9"
RIGHT JOIN (SELECT *
FROM "STACK"."Posts"
WHERE "CreationDate" >= (TIMESTAMP '2024-10-01 12:34:56' - INTERVAL '1' YEAR)) AS "t10" ON "t9"."PostId" = "t10"."Id") AS "t11"
RIGHT JOIN "STACK"."Users" AS "Users0" ON "t11"."OWNERUSERID" = "Users0"."Id") AS "t12"
LEFT JOIN "STACK"."Posts" AS "Posts2" ON "t12"."Id" = "Posts2"."OwnerUserId"
GROUP BY "t12"."Id", "t12"."DisplayName"
HAVING COUNT(DISTINCT "Posts2"."Id") > 0) AS "t16"
GROUP BY "t16"."USERID") AS "t17"
LEFT JOIN (SELECT "UserId", COUNT(*) AS "EXPR$0"
FROM "STACK"."Badges"
WHERE CAST("Class" AS INTEGER) = 1
GROUP BY "UserId") AS "t20" ON "t17"."USERID" IS NOT DISTINCT FROM "t20"."UserId") AS "t21" ON "t7"."USERID" = "t21"."UserId") AS "t22"
LEFT JOIN (SELECT "t47"."USERID" AS "UserId", CASE WHEN "t50"."EXPR$0" IS NOT NULL THEN "t50"."EXPR$0" ELSE 0 END AS "EXPR$0"
FROM (SELECT "t31"."USERID"
FROM (SELECT ANY_VALUE("t27"."Id") AS "USERID", "t27"."DisplayName" AS "DISPLAYNAME", COUNT(DISTINCT "Posts4"."Id") AS "TOTALPOSTS", SUM("Posts4"."Score") AS "TOTALSCORE", SUM("t27"."UpVotes") AS "UPVOTECOUNT", SUM("t27"."DownVotes") AS "DOWNVOTECOUNT", AVG(CASE WHEN "t27"."COMMENTCOUNT" IS NOT NULL THEN CAST("t27"."COMMENTCOUNT" AS BIGINT) ELSE 0 END) AS "AVGCOMMENTSPERPOST"
FROM (SELECT "Users1"."Id", "Users1"."Reputation", "Users1"."CreationDate", "Users1"."DisplayName", "Users1"."LastAccessDate", "Users1"."WebsiteUrl", "Users1"."Location", "Users1"."AboutMe", "Users1"."Views", "Users1"."UpVotes", "Users1"."DownVotes", "Users1"."ProfileImageUrl", "Users1"."AccountId", "t26"."POSTID", "t26"."TITLE", "t26"."SCORE", "t26"."CREATIONDATE", "t26"."OWNERUSERID", "t26"."RAN", "t26"."COMMENTCOUNT"
FROM (SELECT "t25"."Id" AS "POSTID", "t25"."Title" AS "TITLE", "t25"."Score" AS "SCORE", "t25"."CreationDate" AS "CREATIONDATE", "t25"."OwnerUserId" AS "OWNERUSERID", RANK() OVER (PARTITION BY "t25"."OwnerUserId" ORDER BY "t25"."Score" DESC NULLS FIRST) AS "RAN", CASE WHEN "t24"."COMMENTCOUNT" IS NOT NULL THEN CAST("t24"."COMMENTCOUNT" AS BIGINT) ELSE 0 END AS "COMMENTCOUNT"
FROM (SELECT "PostId", COUNT(*) AS "COMMENTCOUNT"
FROM "STACK"."Comments"
GROUP BY "PostId") AS "t24"
RIGHT JOIN (SELECT *
FROM "STACK"."Posts"
WHERE "CreationDate" >= (TIMESTAMP '2024-10-01 12:34:56' - INTERVAL '1' YEAR)) AS "t25" ON "t24"."PostId" = "t25"."Id") AS "t26"
RIGHT JOIN "STACK"."Users" AS "Users1" ON "t26"."OWNERUSERID" = "Users1"."Id") AS "t27"
LEFT JOIN "STACK"."Posts" AS "Posts4" ON "t27"."Id" = "Posts4"."OwnerUserId"
GROUP BY "t27"."Id", "t27"."DisplayName"
HAVING COUNT(DISTINCT "Posts4"."Id") > 0) AS "t31"
LEFT JOIN (SELECT "t41"."USERID" AS "UserId", CASE WHEN "t44"."EXPR$0" IS NOT NULL THEN "t44"."EXPR$0" ELSE 0 END AS "EXPR$0"
FROM (SELECT "t40"."USERID"
FROM (SELECT ANY_VALUE("t36"."Id") AS "USERID"
FROM (SELECT "Users2"."Id", "Users2"."Reputation", "Users2"."CreationDate", "Users2"."DisplayName", "Users2"."LastAccessDate", "Users2"."WebsiteUrl", "Users2"."Location", "Users2"."AboutMe", "Users2"."Views", "Users2"."UpVotes", "Users2"."DownVotes", "Users2"."ProfileImageUrl", "Users2"."AccountId", "t35"."POSTID", "t35"."TITLE", "t35"."SCORE", "t35"."CREATIONDATE", "t35"."OWNERUSERID", "t35"."RAN", "t35"."COMMENTCOUNT"
FROM (SELECT "t34"."Id" AS "POSTID", "t34"."Title" AS "TITLE", "t34"."Score" AS "SCORE", "t34"."CreationDate" AS "CREATIONDATE", "t34"."OwnerUserId" AS "OWNERUSERID", RANK() OVER (PARTITION BY "t34"."OwnerUserId" ORDER BY "t34"."Score" DESC NULLS FIRST) AS "RAN", CASE WHEN "t33"."COMMENTCOUNT" IS NOT NULL THEN CAST("t33"."COMMENTCOUNT" AS BIGINT) ELSE 0 END AS "COMMENTCOUNT"
FROM (SELECT "PostId", COUNT(*) AS "COMMENTCOUNT"
FROM "STACK"."Comments"
GROUP BY "PostId") AS "t33"
RIGHT JOIN (SELECT *
FROM "STACK"."Posts"
WHERE "CreationDate" >= (TIMESTAMP '2024-10-01 12:34:56' - INTERVAL '1' YEAR)) AS "t34" ON "t33"."PostId" = "t34"."Id") AS "t35"
RIGHT JOIN "STACK"."Users" AS "Users2" ON "t35"."OWNERUSERID" = "Users2"."Id") AS "t36"
LEFT JOIN "STACK"."Posts" AS "Posts6" ON "t36"."Id" = "Posts6"."OwnerUserId"
GROUP BY "t36"."Id", "t36"."DisplayName"
HAVING COUNT(DISTINCT "Posts6"."Id") > 0) AS "t40"
GROUP BY "t40"."USERID") AS "t41"
LEFT JOIN (SELECT "UserId", COUNT(*) AS "EXPR$0"
FROM "STACK"."Badges"
WHERE CAST("Class" AS INTEGER) = 1
GROUP BY "UserId") AS "t44" ON "t41"."USERID" IS NOT DISTINCT FROM "t44"."UserId") AS "t45" ON "t31"."USERID" = "t45"."UserId"
GROUP BY "t31"."USERID") AS "t47"
LEFT JOIN (SELECT "UserId", COUNT(*) AS "EXPR$0"
FROM "STACK"."Badges"
WHERE CAST("Class" AS INTEGER) = 2
GROUP BY "UserId") AS "t50" ON "t47"."USERID" IS NOT DISTINCT FROM "t50"."UserId") AS "t51" ON "t22"."USERID" = "t51"."UserId"
GROUP BY "t22"."USERID"