SELECT COALESCE("t9"."USERID", "t9"."USERID") AS "USERID", "t9"."DisplayName" AS "DISPLAYNAME", "t9"."Reputation" AS "REPUTATION", "t9"."TOTALPOSTS", "t9"."TOTALSCORE", CASE WHEN "t9"."$f9" IS NOT NULL THEN CAST("t9"."$f9" AS INTEGER) ELSE 0 END AS "TOTALCOMMENTS", CASE WHEN "t9"."$f10" IS NOT NULL THEN CAST("t9"."$f10" AS INTEGER) ELSE 0 END AS "TOTALCLOSED", CASE WHEN "t9"."$f11" IS NOT NULL THEN CAST("t9"."$f11" AS INTEGER) ELSE 0 END AS "TOTALREOPENED"
FROM (SELECT "Users"."Id", "Users"."DisplayName", "Users"."Reputation", "t5"."UPVOTES", "t5"."DOWNVOTES", "t5"."REPUTATIONCHANGE", ANY_VALUE("Users"."Id") AS "USERID", COUNT(DISTINCT "s1"."POSTID") AS "TOTALPOSTS", SUM("s1"."SCORE") AS "TOTALSCORE", SUM("s1"."COMMENTCOUNT") AS "$f9", SUM("s1"."CLOSEDCOUNT") AS "$f10", SUM("s1"."REOPENEDCOUNT") AS "$f11"
FROM "STACK"."Users"
LEFT JOIN (SELECT "UserId" AS "USERID", SUM(CASE WHEN CAST("VoteTypeId" AS INTEGER) = 2 THEN 1 ELSE 0 END) AS "UPVOTES", SUM(CASE WHEN CAST("VoteTypeId" AS INTEGER) = 3 THEN 1 ELSE 0 END) AS "DOWNVOTES", SUM(CASE WHEN CAST("VoteTypeId" AS INTEGER) = 2 THEN 1 ELSE -1 END) AS "REPUTATIONCHANGE"
FROM "STACK"."Votes"
GROUP BY "UserId") AS "t5" ON "Users"."Id" = "t5"."USERID"
LEFT JOIN "s1" ON "Users"."Id" = "s1"."OWNERUSERID"
WHERE "Users"."Reputation" > 1000
GROUP BY "Users"."Id", "Users"."Reputation", "Users"."DisplayName", "t5"."UPVOTES", "t5"."DOWNVOTES", "t5"."REPUTATIONCHANGE"
ORDER BY "Users"."Reputation" DESC NULLS FIRST, 9 DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY) AS "t9"