SELECT COALESCE("t10"."DISPLAYNAME", "t10"."DISPLAYNAME") AS "DISPLAYNAME", "t10"."POSTCOUNT", "t10"."TOTALVOTES", "t10"."QUESTIONSANSWERED", "t10"."ANSWERSGIVEN", "t10"."POSTEDITS", "t10"."POSTTYPE", "t10"."TOTALPOSTSOFTYPE", "t10"."AVERAGESCORE", "t10"."TOTALVIEWS"
FROM (SELECT "s1"."DISPLAYNAME", "s1"."POSTCOUNT", "s1"."TOTALVOTES", "s1"."QUESTIONSANSWERED", "s1"."ANSWERSGIVEN", "s1"."POSTEDITS", "t8"."POSTTYPE", "t8"."POSTCOUNT" AS "TOTALPOSTSOFTYPE", "t8"."AVERAGESCORE", "t8"."TOTALVIEWS"
FROM (SELECT ANY_VALUE("PostTypes"."Name") AS "POSTTYPE", COUNT(*) AS "POSTCOUNT", AVG("t6"."Score") AS "AVERAGESCORE", SUM("t6"."ViewCount") AS "TOTALVIEWS"
FROM "STACK"."PostTypes"
INNER JOIN (SELECT *
FROM "STACK"."Posts"
WHERE "CreationDate" >= (TIMESTAMP '2024-10-01 12:34:56' - INTERVAL '1' YEAR)) AS "t6" ON "PostTypes"."Id" = "t6"."PostTypeId"
GROUP BY "PostTypes"."Name") AS "t8",
"s1"
ORDER BY "s1"."TOTALVOTES" DESC NULLS FIRST, "s1"."POSTCOUNT" DESC NULLS FIRST, "t8"."TOTALVIEWS" DESC NULLS FIRST
FETCH NEXT 100 ROWS ONLY) AS "t10"