SELECT COALESCE("Users"."DisplayName", "Users"."DisplayName") AS "DISPLAYNAME", CASE WHEN "t0"."UPVOTES" IS NOT NULL THEN CAST("t0"."UPVOTES" AS BIGINT) ELSE 0 END AS "UPVOTES", CASE WHEN "t0"."DOWNVOTES" IS NOT NULL THEN CAST("t0"."DOWNVOTES" AS BIGINT) ELSE 0 END AS "DOWNVOTES", CASE WHEN "t1"."TOTALPOSTS" IS NOT NULL THEN CAST("t1"."TOTALPOSTS" AS BIGINT) ELSE 0 END AS "TOTALPOSTS", CASE WHEN "t1"."TOTALSCORE" IS NOT NULL THEN CAST("t1"."TOTALSCORE" AS INTEGER) ELSE 0 END AS "TOTALSCORE", CASE WHEN "t1"."TOTALVIEWS" IS NOT NULL THEN CAST("t1"."TOTALVIEWS" AS INTEGER) ELSE 0 END AS "TOTALVIEWS"
FROM "STACK"."Users"
LEFT JOIN (SELECT "UserId" AS "USERID", COUNT(CASE WHEN CAST("VoteTypeId" AS INTEGER) = 2 THEN 1 ELSE NULL END) AS "UPVOTES", COUNT(CASE WHEN CAST("VoteTypeId" AS INTEGER) = 3 THEN 1 ELSE NULL END) AS "DOWNVOTES"
FROM "STACK"."Votes"
GROUP BY "UserId") AS "t0" ON "Users"."Id" = "t0"."USERID"
LEFT JOIN (SELECT "OwnerUserId", COUNT(*) AS "TOTALPOSTS", SUM("Score") AS "TOTALSCORE", SUM("ViewCount") AS "TOTALVIEWS"
FROM "STACK"."Posts"
GROUP BY "OwnerUserId") AS "t1" ON "Users"."Id" = "t1"."OwnerUserId"
WHERE CASE WHEN "t1"."TOTALPOSTS" IS NOT NULL THEN CAST("t1"."TOTALPOSTS" AS BIGINT) ELSE 0 END > 0