SELECT COALESCE("OwnerUserId", "OwnerUserId") AS "OWNERUSERID", COUNT(*) AS "TOTALPOSTS", SUM(CASE WHEN CAST("PostTypeId" AS INTEGER) = 1 THEN 1 ELSE 0 END) AS "QUESTIONS", SUM(CASE WHEN CAST("PostTypeId" AS INTEGER) = 2 THEN 1 ELSE 0 END) AS "ANSWERS", SUM("ViewCount") AS "TOTALVIEWS", SUM("Score") AS "TOTALSCORE"
FROM "STACK"."Posts"
WHERE "CreationDate" >= (TIMESTAMP '2024-10-01 12:34:56' - INTERVAL '1' YEAR)
GROUP BY "OwnerUserId"
HAVING COUNT(*) > 5