SELECT COALESCE("t11"."POSTID", "t11"."POSTID") AS "POSTID", "t11"."TITLE", "t11"."CREATIONDATE", "t11"."SCORE", "t11"."VIEWCOUNT", "t11"."OWNERDISPLAYNAME", "t11"."COMMENTCOUNT", "t11"."UPVOTES", "t11"."DOWNVOTES", "t11"."EDITCOUNT", "t11"."MOSTRECENTEDIT", "t11"."TOPUSERNAME", "t11"."TOPUSERSCORE"
FROM (SELECT "s1"."POSTID", "s1"."TITLE", "s1"."CREATIONDATE", "s1"."SCORE", "s1"."VIEWCOUNT", "s1"."OWNERDISPLAYNAME", "s1"."COMMENTCOUNT", "s1"."UPVOTES", "s1"."DOWNVOTES", "s1"."EDITCOUNT", "s1"."MOSTRECENTEDIT", "t9"."DISPLAYNAME" AS "TOPUSERNAME", "t9"."TOTALSCORE" AS "TOPUSERSCORE"
FROM (SELECT "t8"."USERID", "t8"."DisplayName" AS "DISPLAYNAME", "t8"."TOTALSCORE", "t8"."POSTCOUNT"
FROM (SELECT "Users0"."Id", "Users0"."DisplayName", ANY_VALUE("Users0"."Id") AS "USERID", SUM("Posts0"."Score") AS "TOTALSCORE", COUNT(DISTINCT "Posts0"."Id") AS "POSTCOUNT"
FROM "STACK"."Users" AS "Users0"
INNER JOIN "STACK"."Posts" AS "Posts0" ON "Users0"."Id" = "Posts0"."OwnerUserId"
GROUP BY "Users0"."Id", "Users0"."DisplayName"
ORDER BY 4 DESC NULLS FIRST
FETCH NEXT 5 ROWS ONLY) AS "t8") AS "t9",
"s1"
ORDER BY "s1"."SCORE" DESC NULLS FIRST, "s1"."VIEWCOUNT" DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY) AS "t11"