SELECT COALESCE("t2"."POSTID", "t2"."POSTID") AS "POSTID", "t2"."TITLE", "t2"."CREATIONDATE", "t2"."SCORE", "t2"."VIEWCOUNT", "t2"."ANSWERCOUNT", "t2"."COMMENTCOUNT", "t2"."OWNERDISPLAYNAME", "t2"."LASTACTIVITYDATE", "t2"."POSTTYPE", "t2"."POSTID0", "t2"."UPVOTES", "t2"."DOWNVOTES", "t7"."UserId", "t7"."BADGECOUNT", "t7"."$f0" AS "FD_COL_15"
FROM (SELECT "t1"."POSTID", "t1"."TITLE", "t1"."CREATIONDATE", "t1"."SCORE", "t1"."VIEWCOUNT", "t1"."ANSWERCOUNT", "t1"."COMMENTCOUNT", "t1"."OWNERDISPLAYNAME", "t1"."LASTACTIVITYDATE", "t1"."POSTTYPE", "t0"."POSTID" AS "POSTID0", "t0"."UPVOTES", "t0"."DOWNVOTES"
FROM (SELECT "PostId" AS "POSTID", COUNT(CASE WHEN CAST("VoteTypeId" AS INTEGER) = 2 THEN 1 ELSE NULL END) AS "UPVOTES", COUNT(CASE WHEN CAST("VoteTypeId" AS INTEGER) = 3 THEN 1 ELSE NULL END) AS "DOWNVOTES"
FROM "STACK"."Votes"
GROUP BY "PostId") AS "t0"
RIGHT JOIN (SELECT "Posts"."Id" AS "POSTID", "Posts"."Title" AS "TITLE", "Posts"."CreationDate" AS "CREATIONDATE", "Posts"."Score" AS "SCORE", "Posts"."ViewCount" AS "VIEWCOUNT", "Posts"."AnswerCount" AS "ANSWERCOUNT", "Posts"."CommentCount" AS "COMMENTCOUNT", "Users"."DisplayName" AS "OWNERDISPLAYNAME", "Posts"."LastActivityDate" AS "LASTACTIVITYDATE", "PostTypes"."Name" AS "POSTTYPE"
FROM "STACK"."PostTypes"
INNER JOIN ("STACK"."Users" INNER JOIN "STACK"."Posts" ON "Users"."Id" = "Posts"."OwnerUserId") ON "PostTypes"."Id" = "Posts"."PostTypeId") AS "t1" ON "t0"."POSTID" = "t1"."POSTID") AS "t2"
LEFT JOIN (SELECT "t4"."UserId", "t4"."BADGECOUNT", "t6"."$f1" AS "$f0"
FROM (SELECT "UserId", COUNT(*) AS "BADGECOUNT"
FROM "STACK"."Badges"
GROUP BY "UserId") AS "t4"
LEFT JOIN (SELECT "Id", SINGLE_VALUE("DisplayName") AS "$f1"
FROM "STACK"."Users"
GROUP BY "Id") AS "t6" ON "t4"."UserId" = "t6"."Id") AS "t7" ON "t2"."OWNERDISPLAYNAME" = "t7"."$f0"