SELECT COALESCE("POSTTYPE", "POSTTYPE") AS "POSTTYPE", "POSTCOUNT", "AVERAGESCORE", "TOTALCOMMENTS"
FROM (SELECT "POSTTYPE", "POSTCOUNT", "AVERAGESCORE", "TOTALCOMMENTS"
FROM "s1"
ORDER BY "POSTCOUNT" DESC NULLS FIRST) AS "t3"