SELECT COALESCE("t1"."POSTID", "t1"."POSTID") AS "POSTID", "t1"."TITLE", "t1"."OWNERDISPLAYNAME", "t1"."POSTCREATIONDATE", "t1"."SCORE", "t1"."VIEWCOUNT", "t1"."COMMENTCOUNT", "t1"."HISTORYCOUNT", COUNT("Votes"."Id") AS "VOTECOUNT"
FROM "STACK"."Votes"
RIGHT JOIN (SELECT ANY_VALUE("Posts"."Id") AS "POSTID", "Posts"."Title" AS "TITLE", "Posts"."Body" AS "BODY", ANY_VALUE("Users"."DisplayName") AS "OWNERDISPLAYNAME", ANY_VALUE("Posts"."CreationDate") AS "POSTCREATIONDATE", "Posts"."Score" AS "SCORE", "Posts"."ViewCount" AS "VIEWCOUNT", COUNT(CASE WHEN "Comments"."PostId" IS NOT NULL THEN 1 ELSE NULL END) AS "COMMENTCOUNT", COUNT("PostHistory"."Id") AS "HISTORYCOUNT"
FROM "STACK"."Posts"
LEFT JOIN "STACK"."Users" ON "Posts"."OwnerUserId" = "Users"."Id"
LEFT JOIN "STACK"."Comments" ON "Posts"."Id" = "Comments"."PostId"
LEFT JOIN "STACK"."PostHistory" ON "Posts"."Id" = "PostHistory"."PostId"
GROUP BY "Posts"."Id", "Posts"."Title", "Posts"."Body", "Users"."DisplayName", "Posts"."CreationDate", "Posts"."Score", "Posts"."ViewCount") AS "t1" ON "Votes"."PostId" = "t1"."POSTID"
GROUP BY "t1"."POSTID", "t1"."TITLE", "t1"."OWNERDISPLAYNAME", "t1"."POSTCREATIONDATE", "t1"."SCORE", "t1"."VIEWCOUNT", "t1"."COMMENTCOUNT", "t1"."HISTORYCOUNT"