SELECT COALESCE("POSTID", "POSTID") AS "POSTID", "TITLE", "OWNERDISPLAYNAME", "POSTCREATIONDATE", "SCORE", "VIEWCOUNT", "COMMENTCOUNT", "HISTORYCOUNT", "VOTECOUNT"
FROM "s1"
ORDER BY "SCORE" DESC NULLS FIRST, "VIEWCOUNT" DESC NULLS FIRST
FETCH NEXT 100 ROWS ONLY