SELECT COALESCE("t0"."Name", "t0"."Name") AS "Name", ANY_VALUE("t0"."Name") AS "POSTTYPE", COUNT(*) AS "TOTALPOSTS", SUM("t0"."Score") AS "TOTALSCORE", AVG("t0"."VOTECOUNT") AS "AVERAGEVOTES", AVG("t1"."COMMENTCOUNT") AS "AVERAGECOMMENTS", MAX("t0"."CreationDate") AS "LATESTPOSTDATE", MIN("t0"."CreationDate") AS "EARLIESTPOSTDATE"
FROM (SELECT "Posts"."Id", "Posts"."PostTypeId", "Posts"."AcceptedAnswerId", "Posts"."ParentId", "Posts"."CreationDate", "Posts"."Score", "Posts"."ViewCount", "Posts"."Body", "Posts"."OwnerUserId", "Posts"."OwnerDisplayName", "Posts"."LastEditorUserId", "Posts"."LastEditorDisplayName", "Posts"."LastEditDate", "Posts"."LastActivityDate", "Posts"."Title", "Posts"."Tags", "Posts"."AnswerCount", "Posts"."CommentCount", "Posts"."FavoriteCount", "Posts"."ClosedDate", "Posts"."CommunityOwnedDate", "Posts"."ContentLicense", "PostTypes"."Id" AS "Id0", "PostTypes"."Name", "t"."PostId" AS "POSTID", "t"."VOTECOUNT"
FROM (SELECT "PostId", COUNT(*) AS "VOTECOUNT"
FROM "STACK"."Votes"
GROUP BY "PostId") AS "t"
RIGHT JOIN ("STACK"."Posts" INNER JOIN "STACK"."PostTypes" ON "Posts"."PostTypeId" = "PostTypes"."Id") ON "t"."PostId" = "Posts"."Id") AS "t0"
LEFT JOIN (SELECT "PostId", COUNT(*) AS "COMMENTCOUNT"
FROM "STACK"."Comments"
GROUP BY "PostId") AS "t1" ON "t0"."Id" = "t1"."PostId"
GROUP BY "t0"."Name"