SELECT COALESCE("Posts"."Id", "Posts"."Id") AS "Id", "Posts"."Title", "Posts"."CreationDate", "Posts"."Score", "Posts"."ViewCount", "Users"."DisplayName", "Users"."Reputation", "PostTypes"."Name", ANY_VALUE("Posts"."Id") AS "POSTID", ANY_VALUE("Users"."DisplayName") AS "OWNERDISPLAYNAME", ANY_VALUE("Users"."Reputation") AS "OWNERREPUTATION", ANY_VALUE("PostTypes"."Name") AS "POSTTYPE", COUNT("Comments"."Id") AS "COMMENTCOUNT", COUNT("Votes"."Id") AS "VOTECOUNT"
FROM "STACK"."Posts"
LEFT JOIN "STACK"."Users" ON "Posts"."OwnerUserId" = "Users"."Id"
LEFT JOIN "STACK"."PostTypes" ON "Posts"."PostTypeId" = "PostTypes"."Id"
LEFT JOIN "STACK"."Comments" ON "Posts"."Id" = "Comments"."PostId"
LEFT JOIN "STACK"."Votes" ON "Posts"."Id" = "Votes"."PostId"
GROUP BY "Posts"."Id", "Posts"."CreationDate", "Posts"."Score", "Posts"."ViewCount", "Posts"."Title", "Users"."Reputation", "Users"."DisplayName", "PostTypes"."Name"