SELECT COALESCE("POSTTYPE", "POSTTYPE") AS "POSTTYPE", "POSTCOUNT", "TOTALUPVOTES", "TOTALDOWNVOTES", "TOTALCOMMENTS", "TOTALVIEWS", "AVERAGESCORE"
FROM (SELECT "POSTTYPE", "POSTCOUNT", "TOTALUPVOTES", "TOTALDOWNVOTES", "TOTALCOMMENTS", "TOTALVIEWS", "AVERAGESCORE"
FROM "s1"
ORDER BY "AVERAGESCORE" DESC NULLS FIRST) AS "t6"