SELECT COALESCE("POSTID", "POSTID") AS "POSTID", "TITLE", "CREATIONDATE", "OWNERDISPLAYNAME", "UPVOTES", "DOWNVOTES", "VOTECOUNT"
FROM (SELECT "Id" AS "POSTID", "Title" AS "TITLE", "CreationDate" AS "CREATIONDATE", "DisplayName" AS "OWNERDISPLAYNAME", CASE WHEN "UPVOTES_" IS NOT NULL THEN CAST("UPVOTES_" AS INTEGER) ELSE 0 END AS "UPVOTES", CASE WHEN "DOWNVOTES_" IS NOT NULL THEN CAST("DOWNVOTES_" AS INTEGER) ELSE 0 END AS "DOWNVOTES", CASE WHEN "VOTECOUNT" IS NOT NULL THEN CAST("VOTECOUNT" AS BIGINT) ELSE 0 END AS "VOTECOUNT"
FROM "s1"
ORDER BY "CreationDate" DESC NULLS FIRST
FETCH NEXT 100 ROWS ONLY) AS "t3"