SELECT COALESCE("POSTTYPE", "POSTTYPE") AS "POSTTYPE", "TOTALPOSTS", "AVERAGESCORE", "UNIQUEUSERS", "TOTALVIEWS", "TOTALCOMMENTS", "TOTALANSWERS", "USERID", "DISPLAYNAME", "POSTSCREATED", "TOTALBOUNTYRECEIVED"
FROM "s1"
ORDER BY "TOTALPOSTS" DESC NULLS FIRST