SELECT COALESCE("USERNAME", "USERNAME") AS "USERNAME", "TOTALPOSTS", "TOTALQUESTIONS", "TOTALANSWERS", "AVERAGESCORE", "TOTALVIEWS", "LASTPOSTDATE"
FROM (SELECT "DisplayName", "Id", ANY_VALUE("DisplayName") AS "USERNAME", COUNT(DISTINCT "Id0") AS "TOTALPOSTS", SUM("FD_COL_3") AS "TOTALQUESTIONS", SUM("FD_COL_4") AS "TOTALANSWERS", AVG("Score") AS "AVERAGESCORE", SUM("ViewCount") AS "TOTALVIEWS", MAX("CreationDate0") AS "LASTPOSTDATE"
FROM "s1"
GROUP BY "DisplayName", "Id"
ORDER BY 4 DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY) AS "t2"