SELECT COALESCE("POSTID", "POSTID") AS "POSTID", "TITLE", "CREATIONDATE", "VIEWCOUNT", "POSTTYPE", "OWNERDISPLAYNAME", "UPVOTESCOUNT", "DOWNVOTESCOUNT", "BADGECOUNT"
FROM (SELECT "Id" AS "POSTID", "Title" AS "TITLE", "CreationDate" AS "CREATIONDATE", "ViewCount" AS "VIEWCOUNT", "Name" AS "POSTTYPE", "DisplayName" AS "OWNERDISPLAYNAME", CASE WHEN "UPVOTESCOUNT" IS NOT NULL THEN CAST("UPVOTESCOUNT" AS INTEGER) ELSE 0 END AS "UPVOTESCOUNT", CASE WHEN "DOWNVOTESCOUNT" IS NOT NULL THEN CAST("DOWNVOTESCOUNT" AS INTEGER) ELSE 0 END AS "DOWNVOTESCOUNT", CASE WHEN "BADGECOUNT" IS NOT NULL THEN CAST("BADGECOUNT" AS BIGINT) ELSE 0 END AS "BADGECOUNT"
FROM "s1"
ORDER BY "CreationDate" DESC NULLS FIRST
FETCH NEXT 100 ROWS ONLY) AS "t4"