SELECT COALESCE("t10"."POSTID", "t10"."POSTID") AS "POSTID", "t10"."TITLE", "t10"."CREATIONDATE", "t10"."VIEWCOUNT", "t10"."SCORE", "t10"."COMMENTCOUNT", "t10"."VOTECOUNT", "t10"."USERID", "t10"."DISPLAYNAME", "t10"."POSTSCOUNT", "t10"."TOTALUPVOTES", "t10"."TOTALDOWNVOTES", "t10"."TOTALVIEWS"
FROM (SELECT "t8"."POSTID", "t8"."TITLE", "t8"."CREATIONDATE", "t8"."VIEWCOUNT", "t8"."SCORE", "t8"."COMMENTCOUNT", "t8"."VOTECOUNT", "t5"."USERID", "t5"."DISPLAYNAME", "t5"."POSTSCOUNT", "t5"."TOTALUPVOTES", "t5"."TOTALDOWNVOTES", "t5"."TOTALVIEWS"
FROM (SELECT ANY_VALUE("t3"."Id") AS "USERID", "t3"."DisplayName" AS "DISPLAYNAME", COUNT(DISTINCT "Posts0"."Id") AS "POSTSCOUNT", SUM("t3"."UpVotes") AS "TOTALUPVOTES", SUM("t3"."DownVotes") AS "TOTALDOWNVOTES", SUM("t3"."Views") AS "TOTALVIEWS"
FROM "STACK"."Posts" AS "Posts0"
RIGHT JOIN (SELECT *
FROM "STACK"."Users"
WHERE "CreationDate" >= (TIMESTAMP '2024-10-01 12:34:56' - INTERVAL '1' YEAR)) AS "t3" ON "Posts0"."OwnerUserId" = "t3"."Id"
GROUP BY "t3"."Id", "t3"."DisplayName") AS "t5"
INNER JOIN (SELECT ANY_VALUE("Id") AS "POSTID", "Title" AS "TITLE", "CreationDate" AS "CREATIONDATE", "ViewCount" AS "VIEWCOUNT", "Score" AS "SCORE", COUNT("Id0") AS "COMMENTCOUNT", COUNT(DISTINCT "Id1") AS "VOTECOUNT", COUNT(DISTINCT "Id2") AS "BADGECOUNT"
FROM "s1"
GROUP BY "Id", "CreationDate", "Score", "ViewCount", "Title") AS "t8" ON "t5"."USERID" = "t8"."POSTID"
ORDER BY "t8"."VIEWCOUNT" DESC NULLS FIRST, "t8"."SCORE" DESC NULLS FIRST
FETCH NEXT 100 ROWS ONLY) AS "t10"