SELECT COALESCE("POSTID", "POSTID") AS "POSTID", "TITLE", "CREATIONDATE", "COMMENTCOUNT", "VOTECOUNT", "ANSWERCOUNT", "USERID", "DISPLAYNAME", "BADGECOUNT"
FROM (SELECT "POSTID", "TITLE", "CREATIONDATE", "COMMENTCOUNT", "VOTECOUNT", "ANSWERCOUNT", "USERID", "DISPLAYNAME_" AS "DISPLAYNAME", "BADGECOUNT"
FROM "s1"
ORDER BY "CREATIONDATE" DESC NULLS FIRST
FETCH NEXT 100 ROWS ONLY) AS "t47"