SELECT COALESCE("t41"."POSTID", "t41"."POSTID") AS "POSTID", "t41"."TITLE", "t41"."CREATIONDATE", "t41"."COMMENTCOUNT", "t41"."VOTECOUNT", "t41"."ANSWERCOUNT", "t41"."OWNERUSERID", "Users"."Id", "Users"."Reputation", "Users"."CreationDate" AS "CreationDate_", "Users"."DisplayName", "Users"."LastAccessDate", "Users"."WebsiteUrl", "Users"."Location", "Users"."AboutMe", "Users"."Views", "Users"."UpVotes", "Users"."DownVotes", "Users"."ProfileImageUrl", "Users"."AccountId", "t44"."USERID", "t44"."DISPLAYNAME" AS "DISPLAYNAME_", "t44"."BADGECOUNT"
FROM (SELECT "t17"."Id" AS "POSTID", "t17"."Title" AS "TITLE", "t17"."CreationDate" AS "CREATIONDATE", "t17"."EXPR$0" AS "COMMENTCOUNT", "t17"."EXPR$023" AS "VOTECOUNT", CASE WHEN "t40"."EXPR$0" IS NULL THEN 0 ELSE "t40"."EXPR$0" END AS "ANSWERCOUNT", "t17"."OwnerUserId" AS "OWNERUSERID"
FROM (SELECT "t5"."Id", "t5"."PostTypeId", "t5"."AcceptedAnswerId", "t5"."ParentId", "t5"."CreationDate", "t5"."Score", "t5"."ViewCount", "t5"."Body", "t5"."OwnerUserId", "t5"."OwnerDisplayName", "t5"."LastEditorUserId", "t5"."LastEditorDisplayName", "t5"."LastEditDate", "t5"."LastActivityDate", "t5"."Title", "t5"."Tags", "t5"."AnswerCount", "t5"."CommentCount", "t5"."FavoriteCount", "t5"."ClosedDate", "t5"."CommunityOwnedDate", "t5"."ContentLicense", "t5"."EXPR$0", CASE WHEN "t16"."EXPR$0" IS NULL THEN 0 ELSE "t16"."EXPR$0" END AS "EXPR$023"
FROM (SELECT "t"."Id", "t"."PostTypeId", "t"."AcceptedAnswerId", "t"."ParentId", "t"."CreationDate", "t"."Score", "t"."ViewCount", "t"."Body", "t"."OwnerUserId", "t"."OwnerDisplayName", "t"."LastEditorUserId", "t"."LastEditorDisplayName", "t"."LastEditDate", "t"."LastActivityDate", "t"."Title", "t"."Tags", "t"."AnswerCount", "t"."CommentCount", "t"."FavoriteCount", "t"."ClosedDate", "t"."CommunityOwnedDate", "t"."ContentLicense", CASE WHEN "t4"."EXPR$0" IS NULL THEN 0 ELSE "t4"."EXPR$0" END AS "EXPR$0"
FROM (SELECT *
FROM "STACK"."Posts"
WHERE CAST("PostTypeId" AS INTEGER) = 1) AS "t"
LEFT JOIN (SELECT "t1"."Id" AS "PostId", CASE WHEN "t3"."EXPR$0" IS NOT NULL THEN "t3"."EXPR$0" ELSE 0 END AS "EXPR$0"
FROM (SELECT "Id"
FROM "STACK"."Posts"
WHERE CAST("PostTypeId" AS INTEGER) = 1) AS "t1"
LEFT JOIN (SELECT "PostId", COUNT(*) AS "EXPR$0"
FROM "STACK"."Comments"
GROUP BY "PostId") AS "t3" ON "t1"."Id" IS NOT DISTINCT FROM "t3"."PostId") AS "t4" ON "t"."Id" = "t4"."PostId") AS "t5"
LEFT JOIN (SELECT "t13"."Id" AS "PostId", CASE WHEN "t15"."EXPR$0" IS NOT NULL THEN "t15"."EXPR$0" ELSE 0 END AS "EXPR$0"
FROM (SELECT "t6"."Id"
FROM (SELECT *
FROM "STACK"."Posts"
WHERE CAST("PostTypeId" AS INTEGER) = 1) AS "t6"
LEFT JOIN (SELECT "t8"."Id" AS "PostId", CASE WHEN "t10"."EXPR$0" IS NOT NULL THEN "t10"."EXPR$0" ELSE 0 END AS "EXPR$0"
FROM (SELECT "Id"
FROM "STACK"."Posts"
WHERE CAST("PostTypeId" AS INTEGER) = 1) AS "t8"
LEFT JOIN (SELECT "PostId", COUNT(*) AS "EXPR$0"
FROM "STACK"."Comments"
GROUP BY "PostId") AS "t10" ON "t8"."Id" IS NOT DISTINCT FROM "t10"."PostId") AS "t11" ON "t6"."Id" = "t11"."PostId"
GROUP BY "t6"."Id") AS "t13"
LEFT JOIN (SELECT "PostId", COUNT(*) AS "EXPR$0"
FROM "STACK"."Votes"
GROUP BY "PostId") AS "t15" ON "t13"."Id" IS NOT DISTINCT FROM "t15"."PostId") AS "t16" ON "t5"."Id" = "t16"."PostId") AS "t17"
LEFT JOIN (SELECT "t37"."Id" AS "ParentId", CASE WHEN "t39"."EXPR$0" IS NOT NULL THEN "t39"."EXPR$0" ELSE 0 END AS "EXPR$0"
FROM (SELECT "t24"."Id"
FROM (SELECT "t18"."Id", "t18"."PostTypeId", "t18"."AcceptedAnswerId", "t18"."ParentId", "t18"."CreationDate", "t18"."Score", "t18"."ViewCount", "t18"."Body", "t18"."OwnerUserId", "t18"."OwnerDisplayName", "t18"."LastEditorUserId", "t18"."LastEditorDisplayName", "t18"."LastEditDate", "t18"."LastActivityDate", "t18"."Title", "t18"."Tags", "t18"."AnswerCount", "t18"."CommentCount", "t18"."FavoriteCount", "t18"."ClosedDate", "t18"."CommunityOwnedDate", "t18"."ContentLicense", CASE WHEN "t23"."EXPR$0" IS NULL THEN 0 ELSE "t23"."EXPR$0" END AS "EXPR$0"
FROM (SELECT *
FROM "STACK"."Posts"
WHERE CAST("PostTypeId" AS INTEGER) = 1) AS "t18"
LEFT JOIN (SELECT "t20"."Id" AS "PostId", CASE WHEN "t22"."EXPR$0" IS NOT NULL THEN "t22"."EXPR$0" ELSE 0 END AS "EXPR$0"
FROM (SELECT "Id"
FROM "STACK"."Posts"
WHERE CAST("PostTypeId" AS INTEGER) = 1) AS "t20"
LEFT JOIN (SELECT "PostId", COUNT(*) AS "EXPR$0"
FROM "STACK"."Comments"
GROUP BY "PostId") AS "t22" ON "t20"."Id" IS NOT DISTINCT FROM "t22"."PostId") AS "t23" ON "t18"."Id" = "t23"."PostId") AS "t24"
LEFT JOIN (SELECT "t32"."Id" AS "PostId", CASE WHEN "t34"."EXPR$0" IS NOT NULL THEN "t34"."EXPR$0" ELSE 0 END AS "EXPR$0"
FROM (SELECT "t25"."Id"
FROM (SELECT *
FROM "STACK"."Posts"
WHERE CAST("PostTypeId" AS INTEGER) = 1) AS "t25"
LEFT JOIN (SELECT "t27"."Id" AS "PostId", CASE WHEN "t29"."EXPR$0" IS NOT NULL THEN "t29"."EXPR$0" ELSE 0 END AS "EXPR$0"
FROM (SELECT "Id"
FROM "STACK"."Posts"
WHERE CAST("PostTypeId" AS INTEGER) = 1) AS "t27"
LEFT JOIN (SELECT "PostId", COUNT(*) AS "EXPR$0"
FROM "STACK"."Comments"
GROUP BY "PostId") AS "t29" ON "t27"."Id" IS NOT DISTINCT FROM "t29"."PostId") AS "t30" ON "t25"."Id" = "t30"."PostId"
GROUP BY "t25"."Id") AS "t32"
LEFT JOIN (SELECT "PostId", COUNT(*) AS "EXPR$0"
FROM "STACK"."Votes"
GROUP BY "PostId") AS "t34" ON "t32"."Id" IS NOT DISTINCT FROM "t34"."PostId") AS "t35" ON "t24"."Id" = "t35"."PostId"
GROUP BY "t24"."Id") AS "t37"
LEFT JOIN (SELECT "ParentId", COUNT(*) AS "EXPR$0"
FROM "STACK"."Posts"
GROUP BY "ParentId") AS "t39" ON "t37"."Id" IS NOT DISTINCT FROM "t39"."ParentId") AS "t40" ON "t17"."Id" = "t40"."ParentId") AS "t41"
INNER JOIN "STACK"."Users" ON "t41"."OWNERUSERID" = "Users"."Id"
INNER JOIN (SELECT ANY_VALUE("Users0"."Id") AS "USERID", "Users0"."DisplayName" AS "DISPLAYNAME", COUNT("Badges"."Id") AS "BADGECOUNT"
FROM "STACK"."Badges"
RIGHT JOIN "STACK"."Users" AS "Users0" ON "Badges"."UserId" = "Users0"."Id"
GROUP BY "Users0"."Id", "Users0"."DisplayName") AS "t44" ON "Users"."Id" = "t44"."USERID"