SELECT COALESCE("t"."Id", "t"."Id") AS "Id", "t"."Reputation" AS "REPUTATION", "t"."DisplayName" AS "DISPLAYNAME", ANY_VALUE("t"."Id") AS "USERID", COUNT("t"."Id0") AS "POSTCOUNT", SUM(CASE WHEN CAST("t"."PostTypeId" AS INTEGER) = 1 THEN 1 ELSE 0 END) AS "QUESTIONCOUNT", SUM(CASE WHEN CAST("t"."PostTypeId" AS INTEGER) = 2 THEN 1 ELSE 0 END) AS "ANSWERCOUNT", SUM("t0"."COMMENTCOUNT") AS "FD_COL_7", SUM("t1"."VOTECOUNT") AS "FD_COL_8"
FROM (SELECT "Users"."Id", "Users"."Reputation", "Users"."CreationDate", "Users"."DisplayName", "Users"."LastAccessDate", "Users"."WebsiteUrl", "Users"."Location", "Users"."AboutMe", "Users"."Views", "Users"."UpVotes", "Users"."DownVotes", "Users"."ProfileImageUrl", "Users"."AccountId", "Posts"."Id" AS "Id0", "Posts"."PostTypeId", "Posts"."AcceptedAnswerId", "Posts"."ParentId", "Posts"."CreationDate" AS "CreationDate0", "Posts"."Score", "Posts"."ViewCount", "Posts"."Body", "Posts"."OwnerUserId", "Posts"."OwnerDisplayName", "Posts"."LastEditorUserId", "Posts"."LastEditorDisplayName", "Posts"."LastEditDate", "Posts"."LastActivityDate", "Posts"."Title", "Posts"."Tags", "Posts"."AnswerCount", "Posts"."CommentCount", "Posts"."FavoriteCount", "Posts"."ClosedDate", "Posts"."CommunityOwnedDate", "Posts"."ContentLicense"
FROM "STACK"."Posts"
RIGHT JOIN "STACK"."Users" ON "Posts"."OwnerUserId" = "Users"."Id") AS "t"
LEFT JOIN (SELECT "PostId", COUNT(*) AS "COMMENTCOUNT"
FROM "STACK"."Comments"
GROUP BY "PostId") AS "t0" ON "t"."Id0" = "t0"."PostId"
LEFT JOIN (SELECT "PostId", COUNT(*) AS "VOTECOUNT"
FROM "STACK"."Votes"
GROUP BY "PostId") AS "t1" ON "t"."Id0" = "t1"."PostId"
GROUP BY "t"."Id", "t"."Reputation", "t"."DisplayName"