SELECT COALESCE("USERID", "USERID") AS "USERID", "REPUTATION", "DISPLAYNAME", "POSTCOUNT", "QUESTIONCOUNT", "ANSWERCOUNT", "TOTALCOMMENTS", "TOTALVOTES"
FROM (SELECT "USERID", "REPUTATION", "DISPLAYNAME", "POSTCOUNT", "QUESTIONCOUNT", "ANSWERCOUNT", CASE WHEN "FD_COL_7" IS NOT NULL THEN CAST("FD_COL_7" AS BIGINT) ELSE 0 END AS "TOTALCOMMENTS", CASE WHEN "FD_COL_8" IS NOT NULL THEN CAST("FD_COL_8" AS BIGINT) ELSE 0 END AS "TOTALVOTES"
FROM "s1"
ORDER BY "REPUTATION" DESC NULLS FIRST) AS "t6"