SELECT COALESCE("USERID", "USERID") AS "USERID", "DISPLAYNAME", "TOTALPOSTS", "TOTALQUESTIONS", "TOTALANSWERS", "TOTALCOMMENTS", "TOTALVOTES", "ENGAGEMENTSCORE"
FROM "s1"
ORDER BY "ENGAGEMENTSCORE" DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY