SELECT COALESCE("POSTTITLE", "POSTTITLE") AS "POSTTITLE", "POSTCREATIONDATE", "POSTVIEWS", "POSTSCORE", "OWNERDISPLAYNAME", "COMMENTCOUNT", "UPVOTECOUNT", "DOWNVOTECOUNT", "AVERAGEEDITS", "CreationDate"
FROM (SELECT ANY_VALUE("Title") AS "POSTTITLE", ANY_VALUE("CreationDate") AS "POSTCREATIONDATE", ANY_VALUE("ViewCount") AS "POSTVIEWS", ANY_VALUE("Score") AS "POSTSCORE", ANY_VALUE("DisplayName") AS "OWNERDISPLAYNAME", COUNT("Id1") AS "COMMENTCOUNT", SUM("FD_COL_7") AS "UPVOTECOUNT", SUM("FD_COL_8") AS "DOWNVOTECOUNT", AVG("FD_COL_9") AS "AVERAGEEDITS", "CreationDate"
FROM "s1"
GROUP BY "Title", "CreationDate", "ViewCount", "Score", "DisplayName", "Id"
ORDER BY "CreationDate" DESC NULLS FIRST
FETCH NEXT 100 ROWS ONLY) AS "t6"