SELECT COALESCE("Users"."Id", "Users"."Id") AS "Id", "Users"."Reputation", "Users"."CreationDate", "Users"."DisplayName", "Users"."LastAccessDate", "Users"."WebsiteUrl", "Users"."Location", "Users"."AboutMe", "Users"."Views", "Users"."UpVotes", "Users"."DownVotes", "Users"."ProfileImageUrl", "Users"."AccountId", "t6"."Id" AS "Id0", "t6"."PostTypeId", "t6"."AcceptedAnswerId", "t6"."ParentId", "t6"."CreationDate" AS "CreationDate0", "t6"."Score", "t6"."ViewCount", "t6"."Body", "t6"."OwnerUserId", "t6"."OwnerDisplayName", "t6"."LastEditorUserId", "t6"."LastEditorDisplayName", "t6"."LastEditDate", "t6"."LastActivityDate", "t6"."Title", "t6"."Tags", "t6"."AnswerCount", "t6"."CommentCount", "t6"."FavoriteCount", "t6"."ClosedDate", "t6"."CommunityOwnedDate", "t6"."ContentLicense", "t6"."PARENTID" AS "PARENTID_", "t6"."ACCEPTEDANSWERCOUNT", "t6"."POSTID", "t6"."COMMENTCOUNT" AS "COMMENTCOUNT_", "t6"."POSTID0", "t6"."VOTECOUNT"
FROM "STACK"."Users"
INNER JOIN (SELECT "t5"."Id", "t5"."PostTypeId", "t5"."AcceptedAnswerId", "t5"."ParentId", "t5"."CreationDate", "t5"."Score", "t5"."ViewCount", "t5"."Body", "t5"."OwnerUserId", "t5"."OwnerDisplayName", "t5"."LastEditorUserId", "t5"."LastEditorDisplayName", "t5"."LastEditDate", "t5"."LastActivityDate", "t5"."Title", "t5"."Tags", "t5"."AnswerCount", "t5"."CommentCount", "t5"."FavoriteCount", "t5"."ClosedDate", "t5"."CommunityOwnedDate", "t5"."ContentLicense", "t5"."PARENTID", "t5"."ACCEPTEDANSWERCOUNT", "t5"."POSTID", "t5"."COMMENTCOUNT", "t"."PostId" AS "POSTID0", "t"."VOTECOUNT"
FROM (SELECT "PostId", COUNT(*) AS "VOTECOUNT"
FROM "STACK"."Votes"
GROUP BY "PostId") AS "t"
RIGHT JOIN (SELECT "t4"."Id", "t4"."PostTypeId", "t4"."AcceptedAnswerId", "t4"."ParentId", "t4"."CreationDate", "t4"."Score", "t4"."ViewCount", "t4"."Body", "t4"."OwnerUserId", "t4"."OwnerDisplayName", "t4"."LastEditorUserId", "t4"."LastEditorDisplayName", "t4"."LastEditDate", "t4"."LastActivityDate", "t4"."Title", "t4"."Tags", "t4"."AnswerCount", "t4"."CommentCount", "t4"."FavoriteCount", "t4"."ClosedDate", "t4"."CommunityOwnedDate", "t4"."ContentLicense", "t4"."PARENTID", "t4"."ACCEPTEDANSWERCOUNT", "t0"."PostId" AS "POSTID", "t0"."COMMENTCOUNT"
FROM (SELECT "PostId", COUNT(*) AS "COMMENTCOUNT"
FROM "STACK"."Comments"
GROUP BY "PostId") AS "t0"
RIGHT JOIN (SELECT "t3"."Id", "t3"."PostTypeId", "t3"."AcceptedAnswerId", "t3"."ParentId", "t3"."CreationDate", "t3"."Score", "t3"."ViewCount", "t3"."Body", "t3"."OwnerUserId", "t3"."OwnerDisplayName", "t3"."LastEditorUserId", "t3"."LastEditorDisplayName", "t3"."LastEditDate", "t3"."LastActivityDate", "t3"."Title", "t3"."Tags", "t3"."AnswerCount", "t3"."CommentCount", "t3"."FavoriteCount", "t3"."ClosedDate", "t3"."CommunityOwnedDate", "t3"."ContentLicense", "t2"."ParentId" AS "PARENTID", "t2"."ACCEPTEDANSWERCOUNT"
FROM (SELECT "ParentId", COUNT(*) AS "ACCEPTEDANSWERCOUNT"
FROM "STACK"."Posts"
WHERE CAST("PostTypeId" AS INTEGER) = 2
GROUP BY "ParentId") AS "t2"
RIGHT JOIN (SELECT *
FROM "STACK"."Posts"
WHERE "CreationDate" >= TIMESTAMP '2023-01-01 00:00:00') AS "t3" ON "t2"."ParentId" = "t3"."Id") AS "t4" ON "t0"."PostId" = "t4"."Id") AS "t5" ON "t"."PostId" = "t5"."Id") AS "t6" ON "Users"."Id" = "t6"."OwnerUserId"