SELECT COALESCE("POSTID", "POSTID") AS "POSTID", "TITLE", "CREATIONDATE", "VIEWCOUNT", "SCORE", "COMMENTCOUNT", "VOTECOUNT", "TAGS", "OWNERDISPLAYNAME", "OWNERREPUTATION"
FROM (SELECT ANY_VALUE("Id") AS "POSTID", "Title" AS "TITLE", "CreationDate" AS "CREATIONDATE", "ViewCount" AS "VIEWCOUNT", "Score" AS "SCORE", COUNT("Id0") AS "COMMENTCOUNT", COUNT("Id1") AS "VOTECOUNT", ARRAY_AGG(DISTINCT "TagName") AS "TAGS", ANY_VALUE("DisplayName") AS "OWNERDISPLAYNAME", ANY_VALUE("Reputation") AS "OWNERREPUTATION"
FROM "s1"
GROUP BY "Id", "CreationDate", "Score", "ViewCount", "Title", "Id2", "Reputation", "DisplayName"
ORDER BY "CreationDate" DESC NULLS FIRST
FETCH NEXT 100 ROWS ONLY) AS "t6"