SELECT COALESCE("t1"."Id", "t1"."Id") AS "Id", "t1"."PostTypeId", "t1"."AcceptedAnswerId", "t1"."ParentId", "t1"."CreationDate", "t1"."Score", "t1"."ViewCount", "t1"."Body", "t1"."OwnerUserId", "t1"."OwnerDisplayName", "t1"."LastEditorUserId", "t1"."LastEditorDisplayName", "t1"."LastEditDate", "t1"."LastActivityDate", "t1"."Title", "t1"."Tags", "t1"."AnswerCount", "t1"."CommentCount", "t1"."FavoriteCount", "t1"."ClosedDate", "t1"."CommunityOwnedDate", "t1"."ContentLicense", "t1"."Id0", "t1"."Reputation", "t1"."CreationDate0", "t1"."DisplayName", "t1"."LastAccessDate", "t1"."WebsiteUrl", "t1"."Location", "t1"."AboutMe", "t1"."Views", "t1"."UpVotes", "t1"."DownVotes", "t1"."ProfileImageUrl", "t1"."AccountId", "t1"."POSTID", "t1"."COMMENTCOUNT" AS "COMMENTCOUNT_", "t2"."PostId" AS "POSTID0", "t2"."LINKSCOUNT", "t3"."PostId" AS "POSTID1", "t3"."HISTORYCOUNT"
FROM (SELECT "t0"."Id", "t0"."PostTypeId", "t0"."AcceptedAnswerId", "t0"."ParentId", "t0"."CreationDate", "t0"."Score", "t0"."ViewCount", "t0"."Body", "t0"."OwnerUserId", "t0"."OwnerDisplayName", "t0"."LastEditorUserId", "t0"."LastEditorDisplayName", "t0"."LastEditDate", "t0"."LastActivityDate", "t0"."Title", "t0"."Tags", "t0"."AnswerCount", "t0"."CommentCount", "t0"."FavoriteCount", "t0"."ClosedDate", "t0"."CommunityOwnedDate", "t0"."ContentLicense", "Users"."Id" AS "Id0", "Users"."Reputation", "Users"."CreationDate" AS "CreationDate0", "Users"."DisplayName", "Users"."LastAccessDate", "Users"."WebsiteUrl", "Users"."Location", "Users"."AboutMe", "Users"."Views", "Users"."UpVotes", "Users"."DownVotes", "Users"."ProfileImageUrl", "Users"."AccountId", "t"."PostId" AS "POSTID", "t"."COMMENTCOUNT"
FROM (SELECT "PostId", COUNT(*) AS "COMMENTCOUNT"
FROM "STACK"."Comments"
GROUP BY "PostId") AS "t"
RIGHT JOIN ((SELECT *
FROM "STACK"."Posts"
WHERE "CreationDate" >= CAST((DATE '2024-10-01' - INTERVAL '1' YEAR) AS TIMESTAMP(0))) AS "t0" INNER JOIN "STACK"."Users" ON "t0"."OwnerUserId" = "Users"."Id") ON "t"."PostId" = "t0"."Id") AS "t1"
LEFT JOIN (SELECT "PostId", COUNT(*) AS "LINKSCOUNT"
FROM "STACK"."PostLinks"
GROUP BY "PostId") AS "t2" ON "t1"."Id" = "t2"."PostId"
LEFT JOIN (SELECT "PostId", COUNT(*) AS "HISTORYCOUNT"
FROM "STACK"."PostHistory"
GROUP BY "PostId") AS "t3" ON "t1"."Id" = "t3"."PostId"