SELECT COALESCE("POSTID", "POSTID") AS "POSTID", "TITLE", "CREATIONDATE", "SCORE", "VIEWCOUNT", "OWNERDISPLAYNAME", "COMMENTCOUNT", "UPVOTES", "DOWNVOTES", "BADGECOUNT"
FROM (SELECT ANY_VALUE("Id") AS "POSTID", "TITLE", "CREATIONDATE", "SCORE", "VIEWCOUNT", ANY_VALUE("DisplayName") AS "OWNERDISPLAYNAME", COUNT("Id1") AS "COMMENTCOUNT", SUM("FD_COL_7") AS "UPVOTES", SUM("FD_COL_8") AS "DOWNVOTES", COUNT("Id3") AS "BADGECOUNT"
FROM "s1"
GROUP BY "Id", "TITLE", "CREATIONDATE", "SCORE", "VIEWCOUNT", "DisplayName"
ORDER BY "SCORE" DESC NULLS FIRST, "CREATIONDATE" DESC NULLS FIRST
FETCH NEXT 100 ROWS ONLY) AS "t6"