SELECT COALESCE("POSTTYPE", "POSTTYPE") AS "POSTTYPE", "TOTALPOSTS", "AVGVIEWCOUNT", "TOTALUPVOTES", "TOTALDOWNVOTES"
FROM (SELECT "POSTTYPE", "TOTALPOSTS", "FD_COL_3" AS "AVGVIEWCOUNT", "TOTALUPVOTES", "TOTALDOWNVOTES"
FROM "s1"
ORDER BY "TOTALPOSTS" DESC NULLS FIRST) AS "t3"