SELECT COALESCE("t0"."POSTID", "t0"."POSTID") AS "POSTID", "t0"."EDITCOUNT", "t0"."BODYEDITS", "t0"."TITLEEDITS", "t3"."USERID", "t3"."DISPLAYNAME", "t3"."POSTCOUNT", "t3"."TOTALSCORE", "t3"."TOTALVIEWS", "t3"."QUESTIONCOUNT", "t3"."ANSWERCOUNT"
FROM (SELECT "PostHistory"."PostId" AS "POSTID", COUNT(*) AS "EDITCOUNT", SUM(CASE WHEN "PostHistoryTypes"."Name" = 'Edit Body' THEN 1 ELSE 0 END) AS "BODYEDITS", SUM(CASE WHEN "PostHistoryTypes"."Name" = 'Edit Title' THEN 1 ELSE 0 END) AS "TITLEEDITS"
FROM "STACK"."PostHistoryTypes"
INNER JOIN "STACK"."PostHistory" ON "PostHistoryTypes"."Id" = "PostHistory"."PostHistoryTypeId"
GROUP BY "PostHistory"."PostId") AS "t0"
RIGHT JOIN (SELECT ANY_VALUE("Users"."Id") AS "USERID", "Users"."DisplayName" AS "DISPLAYNAME", COUNT("Posts"."Id") AS "POSTCOUNT", SUM(CASE WHEN "Posts"."Score" IS NOT NULL THEN CAST("Posts"."Score" AS INTEGER) ELSE 0 END) AS "TOTALSCORE", SUM(CASE WHEN "Posts"."ViewCount" IS NOT NULL THEN CAST("Posts"."ViewCount" AS INTEGER) ELSE 0 END) AS "TOTALVIEWS", SUM(CASE WHEN CAST("Posts"."PostTypeId" AS INTEGER) = 1 THEN 1 ELSE 0 END) AS "QUESTIONCOUNT", SUM(CASE WHEN CAST("Posts"."PostTypeId" AS INTEGER) = 2 THEN 1 ELSE 0 END) AS "ANSWERCOUNT"
FROM "STACK"."Posts"
RIGHT JOIN "STACK"."Users" ON "Posts"."OwnerUserId" = "Users"."Id"
GROUP BY "Users"."Id", "Users"."DisplayName") AS "t3" ON "t0"."POSTID" = "t3"."USERID"