SELECT COALESCE("t5"."POSTTYPEID", "t5"."POSTTYPEID") AS "POSTTYPEID", "t5"."POSTCOUNT", "t5"."AVGSCORE", "t5"."TOTALVIEWS", "t5"."TOTALANSWERS", "t5"."TOTALCOMMENTS", "t5"."TOTALFAVORITES", "t5"."LASTPOSTDATE", SUM("t7"."TOTALPOSTS") AS "TOTALUSERPOSTS", AVG("t7"."REPUTATION") AS "AVGUSERREPUTATION", SUM("t7"."TOTALUPVOTES") AS "TOTALUSERUPVOTES", SUM("t7"."TOTALDOWNVOTES") AS "TOTALUSERDOWNVOTES"
FROM (SELECT "PostTypeId" AS "POSTTYPEID", COUNT(*) AS "POSTCOUNT", AVG("Score") AS "AVGSCORE", SUM("ViewCount") AS "TOTALVIEWS", SUM("AnswerCount") AS "TOTALANSWERS", SUM("CommentCount") AS "TOTALCOMMENTS", SUM("FavoriteCount") AS "TOTALFAVORITES", MAX("CreationDate") AS "LASTPOSTDATE", COUNT(*) > 0 AS "$f8"
FROM "STACK"."Posts"
WHERE "CreationDate" >= (TIMESTAMP '2024-10-01 12:34:56' - INTERVAL '1' YEAR)
GROUP BY "PostTypeId"
HAVING COUNT(*) > 0) AS "t5",
(SELECT ANY_VALUE("Id") AS "USERID", "REPUTATION", COUNT(DISTINCT "Id0") AS "TOTALPOSTS", SUM("FD_COL_3") AS "TOTALUPVOTES", SUM("FD_COL_4") AS "TOTALDOWNVOTES"
FROM "s1"
GROUP BY "Id", "REPUTATION") AS "t7"
GROUP BY "t5"."POSTTYPEID", "t5"."POSTCOUNT", "t5"."AVGSCORE", "t5"."TOTALVIEWS", "t5"."TOTALANSWERS", "t5"."TOTALCOMMENTS", "t5"."TOTALFAVORITES", "t5"."LASTPOSTDATE"
ORDER BY "t5"."POSTTYPEID"