SELECT COALESCE("t9"."POSTID", "t9"."POSTID") AS "POSTID", "t9"."POSTTYPEID", "t9"."TOTALCOMMENTS", "t9"."TOTALVOTES", "t9"."UPVOTES", "t9"."DOWNVOTES", "t9"."DELETIONVOTES", "t9"."USERID", "t9"."TOTALPOSTVIEWS", "t9"."POSTSCREATED"
FROM (SELECT "t7"."POSTID", "t7"."POSTTYPEID", "t7"."TOTALCOMMENTS", "t7"."TOTALVOTES", "t7"."UPVOTES", "t7"."DOWNVOTES", "t7"."DELETIONVOTES", "t3"."USERID", "t3"."TOTALPOSTVIEWS", "t3"."POSTSCREATED"
FROM (SELECT ANY_VALUE("t1"."Id") AS "USERID", SUM("Posts0"."ViewCount") AS "TOTALPOSTVIEWS", COUNT(DISTINCT "Posts0"."Id") AS "POSTSCREATED"
FROM (SELECT *
FROM "STACK"."Users"
WHERE "CreationDate" >= (TIMESTAMP '2024-10-01 12:34:56' - INTERVAL '1' YEAR)) AS "t1"
INNER JOIN "STACK"."Posts" AS "Posts0" ON "t1"."Id" = "Posts0"."OwnerUserId"
GROUP BY "t1"."Id") AS "t3"
INNER JOIN (SELECT ANY_VALUE("t4"."Id") AS "POSTID", "t4"."PostTypeId" AS "POSTTYPEID", COUNT("t4"."Id0") AS "TOTALCOMMENTS", COUNT("Votes"."Id") AS "TOTALVOTES", SUM(CASE WHEN CAST("Votes"."VoteTypeId" AS INTEGER) = 2 THEN 1 ELSE 0 END) AS "UPVOTES", SUM(CASE WHEN CAST("Votes"."VoteTypeId" AS INTEGER) = 3 THEN 1 ELSE 0 END) AS "DOWNVOTES", SUM(CASE WHEN CAST("Votes"."VoteTypeId" AS INTEGER) = 10 THEN 1 ELSE 0 END) AS "DELETIONVOTES"
FROM "STACK"."Votes"
RIGHT JOIN (SELECT "s1"."Id", "s1"."PostTypeId", "s1"."AcceptedAnswerId", "s1"."ParentId", "s1"."CreationDate", "s1"."Score", "s1"."ViewCount", "s1"."Body", "s1"."OwnerUserId", "s1"."OwnerDisplayName", "s1"."LastEditorUserId", "s1"."LastEditorDisplayName", "s1"."LastEditDate", "s1"."LastActivityDate", "s1"."Title", "s1"."Tags", "s1"."AnswerCount", "s1"."CommentCount", "s1"."FavoriteCount", "s1"."ClosedDate", "s1"."CommunityOwnedDate", "s1"."ContentLicense", "Comments"."Id" AS "Id0", "Comments"."PostId", "Comments"."Score" AS "Score0", "Comments"."Text", "Comments"."CreationDate" AS "CreationDate0", "Comments"."UserDisplayName", "Comments"."UserId", "Comments"."ContentLicense" AS "ContentLicense0"
FROM "STACK"."Comments"
RIGHT JOIN "s1" ON "Comments"."PostId" = "s1"."Id") AS "t4" ON "Votes"."PostId" = "t4"."Id"
GROUP BY "t4"."Id", "t4"."PostTypeId") AS "t7" ON "t3"."USERID" = "t7"."POSTID"
ORDER BY "t7"."TOTALVOTES" DESC NULLS FIRST, "t7"."TOTALCOMMENTS" DESC NULLS FIRST) AS "t9"