SELECT COALESCE("t1"."POSTID", "t1"."POSTID") AS "POSTID", "t1"."TITLE", "t1"."CREATIONDATE", "t1"."VIEWCOUNT", "t1"."SCORE", "t1"."OWNERDISPLAYNAME", "t1"."COMMENTCOUNT", "t1"."BADGECOUNT", "t1"."LASTHISTORYUPDATE", "t3"."POSTID" AS "POSTID0", "t3"."VOTECOUNT", "t3"."UPVOTES", "t3"."DOWNVOTES"
FROM (SELECT ANY_VALUE("Posts"."Id") AS "POSTID", "Posts"."Title" AS "TITLE", "Posts"."CreationDate" AS "CREATIONDATE", "Posts"."ViewCount" AS "VIEWCOUNT", "Posts"."Score" AS "SCORE", ANY_VALUE("Users"."DisplayName") AS "OWNERDISPLAYNAME", COUNT("Comments"."Id") AS "COMMENTCOUNT", COUNT("Badges"."Id") AS "BADGECOUNT", MAX("PostHistory"."CreationDate") AS "LASTHISTORYUPDATE"
FROM "STACK"."Posts"
LEFT JOIN "STACK"."Users" ON "Posts"."OwnerUserId" = "Users"."Id"
LEFT JOIN "STACK"."Comments" ON "Posts"."Id" = "Comments"."PostId"
LEFT JOIN "STACK"."Badges" ON "Users"."Id" = "Badges"."UserId"
LEFT JOIN "STACK"."PostHistory" ON "Posts"."Id" = "PostHistory"."PostId"
GROUP BY "Posts"."Id", "Posts"."CreationDate", "Posts"."Score", "Posts"."ViewCount", "Posts"."Title", "Users"."DisplayName") AS "t1"
LEFT JOIN (SELECT "Votes"."PostId" AS "POSTID", COUNT(*) AS "VOTECOUNT", SUM(CASE WHEN "VoteTypes"."Name" = 'UpMod' THEN 1 ELSE 0 END) AS "UPVOTES", SUM(CASE WHEN "VoteTypes"."Name" = 'DownMod' THEN 1 ELSE 0 END) AS "DOWNVOTES"
FROM "STACK"."VoteTypes"
INNER JOIN "STACK"."Votes" ON "VoteTypes"."Id" = "Votes"."VoteTypeId"
GROUP BY "Votes"."PostId") AS "t3" ON "t1"."POSTID" = "t3"."POSTID"