SELECT COALESCE("POSTID", "POSTID") AS "POSTID", "TITLE", "CREATIONDATE", "SCORE", "VIEWCOUNT", "OWNERDISPLAYNAME", "COMMENTCOUNT", "VOTECOUNT", "LASTEDITED", "CLOSEDDATE"
FROM (SELECT ANY_VALUE("Id") AS "POSTID", "TITLE", "CREATIONDATE", "SCORE", "VIEWCOUNT", ANY_VALUE("DisplayName") AS "OWNERDISPLAYNAME", COUNT("Id1") AS "COMMENTCOUNT", COUNT("Id2") AS "VOTECOUNT", MAX("CreationDate3") AS "LASTEDITED", MAX("FD_COL_9") AS "CLOSEDDATE"
FROM "s1"
GROUP BY "Id", "TITLE", "CREATIONDATE", "SCORE", "VIEWCOUNT", "DisplayName"
ORDER BY "CREATIONDATE" DESC NULLS FIRST
FETCH NEXT 100 ROWS ONLY) AS "t6"