SELECT COALESCE("OWNERDISPLAYNAME", "OWNERDISPLAYNAME") AS "OWNERDISPLAYNAME", "TITLE", "CREATIONDATE", "LASTACTIVITYDATE", "SCORE", "ANSWERCOUNT", "VIEWCOUNT", "COMMENTCOUNT", "TAGNAME", "HISTORYCOUNT"
FROM "s1"
ORDER BY "LASTACTIVITYDATE" DESC NULLS FIRST
FETCH NEXT 100 ROWS ONLY