SELECT COALESCE("POSTID", "POSTID") AS "POSTID", "POSTTYPEID", "COMMENTCOUNT", "VOTECOUNT", "UPVOTES", "DOWNVOTES", "OFFENSIVEVOTES", "LASTACTIVITYDATE", "USERID", "BADGECOUNT", "TOTALUPVOTES", "TOTALDOWNVOTES", "TOTALVIEWS"
FROM (SELECT "POSTID", "POSTTYPEID", "COMMENTCOUNT", "VOTECOUNT", "UPVOTES", "DOWNVOTES", "OFFENSIVEVOTES", "LASTACTIVITYDATE", "USERID", "BADGECOUNT", "TOTALUPVOTES", "TOTALDOWNVOTES", "TOTALVIEWS"
FROM "s1"
ORDER BY "LASTACTIVITYDATE" DESC NULLS FIRST) AS "t7"