SELECT COALESCE("POSTTYPEID", "POSTTYPEID") AS "POSTTYPEID", "TOTALPOSTS", "ACCEPTEDANSWERS", "TOTALVIEWS", "AVGSCORE", "TOTALBADGES", "TOTALBOUNTY", "POSTHISTORYTYPE", "HISTORYCOUNT"
FROM (SELECT "POSTTYPEID", "TOTALPOSTS", "ACCEPTEDANSWERS", "TOTALVIEWS", "AVGSCORE", "TOTALBADGES", "TOTALBOUNTY", "POSTHISTORYTYPE", "HISTORYCOUNT"
FROM "s1"
ORDER BY "POSTTYPEID") AS "t12"