SELECT COALESCE("Users"."Id", "Users"."Id") AS "Id", "Users"."Reputation", "Users"."CreationDate", "Users"."DisplayName", "Users"."LastAccessDate", "Users"."WebsiteUrl", "Users"."Location", "Users"."AboutMe", "Users"."Views", "Users"."UpVotes", "Users"."DownVotes", "Users"."ProfileImageUrl", "Users"."AccountId", "t1"."USERID", "t1"."BADGECOUNT", "t1"."GOLDBADGES", "t1"."SILVERBADGES", "t1"."BRONZEBADGES", "t2"."OwnerUserId" AS "OWNERUSERID", "t2"."POSTCOUNT", "t2"."TOTALSCORE", "t2"."TOTALVIEWS", "t2"."AVGSCORE"
FROM "STACK"."Users"
LEFT JOIN (SELECT ANY_VALUE("Users0"."Id") AS "USERID", COUNT("Badges"."Id") AS "BADGECOUNT", SUM(CASE WHEN CAST("Badges"."Class" AS INTEGER) = 1 THEN 1 ELSE 0 END) AS "GOLDBADGES", SUM(CASE WHEN CAST("Badges"."Class" AS INTEGER) = 2 THEN 1 ELSE 0 END) AS "SILVERBADGES", SUM(CASE WHEN CAST("Badges"."Class" AS INTEGER) = 3 THEN 1 ELSE 0 END) AS "BRONZEBADGES"
FROM "STACK"."Badges"
RIGHT JOIN "STACK"."Users" AS "Users0" ON "Badges"."UserId" = "Users0"."Id"
GROUP BY "Users0"."Id") AS "t1" ON "Users"."Id" = "t1"."USERID"
LEFT JOIN (SELECT "OwnerUserId", COUNT(*) AS "POSTCOUNT", SUM("Score") AS "TOTALSCORE", SUM("ViewCount") AS "TOTALVIEWS", AVG("Score") AS "AVGSCORE"
FROM "STACK"."Posts"
GROUP BY "OwnerUserId") AS "t2" ON "Users"."Id" = "t2"."OwnerUserId"