SELECT COALESCE("USERID", "USERID") AS "USERID", "DISPLAYNAME", "TOTALPOSTS", "QUESTIONS", "ANSWERS", "WIKIS", "TOTALSCORE", "TOTALVIEWS", "POSTTYPENAME", "POSTCOUNT", "POSTTYPETOTALSCORE", "AVERAGEVIEWCOUNT"
FROM (SELECT "USERID", "DISPLAYNAME", "TOTALPOSTS", "QUESTIONS", "ANSWERS", "WIKIS", "TOTALSCORE0" AS "TOTALSCORE", "TOTALVIEWS", "POSTTYPENAME", "POSTCOUNT", "TOTALSCORE" AS "POSTTYPETOTALSCORE", "AVERAGEVIEWCOUNT"
FROM "s1"
ORDER BY "TOTALSCORE0" DESC NULLS FIRST, "POSTTYPENAME") AS "t7"