SELECT COALESCE("POSTID", "POSTID") AS "POSTID", "TITLE", "CREATIONDATE", "SCORE", "VIEWCOUNT", "OWNERNAME", "COMMENTCOUNT", "UPVOTES", "DOWNVOTES", "EDITCOUNT", "FIRSTEDITDATE", "LASTEDITDATE"
FROM (SELECT ANY_VALUE("Id") AS "POSTID", "TITLE", "CREATIONDATE", "SCORE", "VIEWCOUNT", ANY_VALUE("DisplayName") AS "OWNERNAME", COUNT("Id1") AS "COMMENTCOUNT", SUM("FD_COL_7") AS "UPVOTES", SUM("FD_COL_8") AS "DOWNVOTES", COUNT(DISTINCT "Id3") AS "EDITCOUNT", MIN("CreationDate3") AS "FIRSTEDITDATE", MAX("CreationDate3") AS "LASTEDITDATE"
FROM "s1"
GROUP BY "Id", "TITLE", "CREATIONDATE", "SCORE", "VIEWCOUNT", "DisplayName"
ORDER BY "CREATIONDATE" DESC NULLS FIRST
FETCH NEXT 100 ROWS ONLY) AS "t6"