SELECT COALESCE("POSTTYPE", "POSTTYPE") AS "POSTTYPE", "POSTCOUNT", "AVGSCORE", "TOTALVIEWS", "AVGANSWERCOUNT", "AVGCOMMENTCOUNT", "DISPLAYNAME", "BADGECOUNT", "MAXREPUTATION", "AVGREPUTATION"
FROM (SELECT "POSTTYPE", "POSTCOUNT", "AVGSCORE", "TOTALVIEWS", "AVGANSWERCOUNT", "AVGCOMMENTCOUNT", "DISPLAYNAME", "BADGECOUNT", "MAXREPUTATION", "AVGREPUTATION"
FROM "s1"
ORDER BY "POSTCOUNT" DESC NULLS FIRST) AS "t5"