SELECT COALESCE("POSTID", "POSTID") AS "POSTID", "TITLE", "CREATIONDATE", "OWNERDISPLAYNAME", "COMMENTCOUNT", "VOTECOUNT", "UPVOTES", "DOWNVOTES", "BADGECOUNT"
FROM (SELECT ANY_VALUE("Id") AS "POSTID", "TITLE", "CREATIONDATE", ANY_VALUE("DisplayName") AS "OWNERDISPLAYNAME", COUNT(DISTINCT "Id1") AS "COMMENTCOUNT", COUNT(DISTINCT "Id2") AS "VOTECOUNT", SUM("FD_COL_6") AS "UPVOTES", SUM("FD_COL_7") AS "DOWNVOTES", SUM("FD_COL_8") AS "BADGECOUNT"
FROM "s1"
GROUP BY "Id", "TITLE", "CREATIONDATE", "DisplayName"
ORDER BY "CREATIONDATE" DESC NULLS FIRST
FETCH NEXT 100 ROWS ONLY) AS "t6"