SELECT COALESCE("USERID", "USERID") AS "USERID", "DISPLAYNAME", "TOTALPOSTS", "QUESTIONS", "ANSWERS", "AVGPOSTSCORE", "AVGVIEWCOUNT", "TOTALCOMMENTS", "TOTALBADGES"
FROM (SELECT "Id", "DISPLAYNAME", ANY_VALUE("Id") AS "USERID", COUNT(DISTINCT "Id0") AS "TOTALPOSTS", SUM("FD_COL_3") AS "QUESTIONS", SUM("FD_COL_4") AS "ANSWERS", AVG("FD_COL_5") AS "AVGPOSTSCORE", AVG("FD_COL_6") AS "AVGVIEWCOUNT", COUNT(DISTINCT "Id1") AS "TOTALCOMMENTS", COUNT(DISTINCT "Id2") AS "TOTALBADGES"
FROM "s1"
GROUP BY "Id", "DISPLAYNAME"
ORDER BY 4 DESC NULLS FIRST
FETCH NEXT 100 ROWS ONLY) AS "t5"