SELECT COALESCE("POSTTYPE", "POSTTYPE") AS "POSTTYPE", "POSTCOUNT", "USERCOUNT", "VOTECOUNT", "COMMENTCOUNT", "AVGSCORE", "AVGVIEWCOUNT"
FROM (SELECT "POSTTYPE", "POSTCOUNT", "USERCOUNT", "VOTECOUNT", "COMMENTCOUNT", "AVGSCORE", "AVGVIEWCOUNT"
FROM "s1"
ORDER BY "POSTCOUNT" DESC NULLS FIRST) AS "t2"