SELECT COALESCE("t0"."USERID", "t0"."USERID") AS "USERID", "t0"."BADGECOUNT", "t0"."TOTALVIEWS", "t0"."TOTALUPVOTES", "t0"."TOTALDOWNVOTES", "t0"."USERID0", "t7"."POSTTYPE", "t7"."TOTALPOSTS", "t7"."TOTALCOMMENTS", "t7"."TOTALVOTES"
FROM (SELECT ANY_VALUE("Users"."Id") AS "USERID", COUNT("Badges"."Id") AS "BADGECOUNT", SUM("Users"."Views") AS "TOTALVIEWS", SUM("Users"."UpVotes") AS "TOTALUPVOTES", SUM("Users"."DownVotes") AS "TOTALDOWNVOTES", CAST(ANY_VALUE("Users"."Id") AS BIGINT) AS "USERID0"
FROM "STACK"."Badges"
RIGHT JOIN "STACK"."Users" ON "Badges"."UserId" = "Users"."Id"
GROUP BY "Users"."Id") AS "t0"
INNER JOIN (SELECT ANY_VALUE("t1"."Name") AS "POSTTYPE", COUNT("t1"."Id0") AS "TOTALPOSTS", SUM("t5"."COMMENTCOUNT") AS "TOTALCOMMENTS", SUM("t5"."VOTECOUNT") AS "TOTALVOTES"
FROM (SELECT "PostTypes"."Id", "PostTypes"."Name", "Posts"."Id" AS "Id0", "Posts"."PostTypeId", "Posts"."AcceptedAnswerId", "Posts"."ParentId", "Posts"."CreationDate", "Posts"."Score", "Posts"."ViewCount", "Posts"."Body", "Posts"."OwnerUserId", "Posts"."OwnerDisplayName", "Posts"."LastEditorUserId", "Posts"."LastEditorDisplayName", "Posts"."LastEditDate", "Posts"."LastActivityDate", "Posts"."Title", "Posts"."Tags", "Posts"."AnswerCount", "Posts"."CommentCount", "Posts"."FavoriteCount", "Posts"."ClosedDate", "Posts"."CommunityOwnedDate", "Posts"."ContentLicense"
FROM "STACK"."Posts"
RIGHT JOIN "STACK"."PostTypes" ON "Posts"."PostTypeId" = "PostTypes"."Id") AS "t1"
LEFT JOIN (SELECT ANY_VALUE("t2"."Id") AS "POSTID", "t2"."PostTypeId" AS "POSTTYPEID", COUNT("t2"."Id0") AS "COMMENTCOUNT", COUNT(DISTINCT "Votes"."Id") AS "VOTECOUNT", MAX(CASE WHEN CAST("Votes"."VoteTypeId" AS INTEGER) = 2 THEN 1 ELSE 0 END) AS "UPVOTE", MAX(CASE WHEN CAST("Votes"."VoteTypeId" AS INTEGER) = 3 THEN 1 ELSE 0 END) AS "DOWNVOTE", MAX("t2"."CreationDate") AS "LASTACTIVITYDATE"
FROM "STACK"."Votes"
RIGHT JOIN (SELECT "Posts0"."Id", "Posts0"."PostTypeId", "Posts0"."AcceptedAnswerId", "Posts0"."ParentId", "Posts0"."CreationDate", "Posts0"."Score", "Posts0"."ViewCount", "Posts0"."Body", "Posts0"."OwnerUserId", "Posts0"."OwnerDisplayName", "Posts0"."LastEditorUserId", "Posts0"."LastEditorDisplayName", "Posts0"."LastEditDate", "Posts0"."LastActivityDate", "Posts0"."Title", "Posts0"."Tags", "Posts0"."AnswerCount", "Posts0"."CommentCount", "Posts0"."FavoriteCount", "Posts0"."ClosedDate", "Posts0"."CommunityOwnedDate", "Posts0"."ContentLicense", "Comments"."Id" AS "Id0", "Comments"."PostId", "Comments"."Score" AS "Score0", "Comments"."Text", "Comments"."CreationDate" AS "CreationDate0", "Comments"."UserDisplayName", "Comments"."UserId", "Comments"."ContentLicense" AS "ContentLicense0"
FROM "STACK"."Comments"
RIGHT JOIN "STACK"."Posts" AS "Posts0" ON "Comments"."PostId" = "Posts0"."Id") AS "t2" ON "Votes"."PostId" = "t2"."Id"
GROUP BY "t2"."Id", "t2"."PostTypeId") AS "t5" ON "t1"."Id0" = "t5"."POSTID"
GROUP BY "t1"."Name") AS "t7" ON "t0"."USERID0" = "t7"."TOTALPOSTS"