SELECT COALESCE("t6"."USERID", "t6"."USERID") AS "USERID", "t6"."DISPLAYNAME", "t6"."POSTCOUNT", "t6"."COMMENTCOUNT", "t6"."UPVOTES", "t6"."DOWNVOTES", "t6"."REPUTATION"
FROM (SELECT "Users0"."Id" AS "USERID", "Users0"."DisplayName" AS "DISPLAYNAME", "t4"."POSTCOUNT", "t4"."COMMENTCOUNT", "t4"."UPVOTES", "t4"."DOWNVOTES", "t4"."REPUTATION"
FROM "STACK"."Users" AS "Users0"
INNER JOIN (SELECT ANY_VALUE("Id") AS "USERID", "REPUTATION", COUNT(DISTINCT "Id0") AS "POSTCOUNT", COUNT(DISTINCT "Id1") AS "COMMENTCOUNT", SUM("FD_COL_4") AS "UPVOTES", SUM("FD_COL_5") AS "DOWNVOTES"
FROM "s1"
GROUP BY "Id", "REPUTATION") AS "t4" ON "Users0"."Id" = "t4"."USERID"
ORDER BY "t4"."REPUTATION" DESC NULLS FIRST, "t4"."POSTCOUNT" DESC NULLS FIRST
FETCH NEXT 100 ROWS ONLY) AS "t6"