SELECT COALESCE("TITLE", "TITLE") AS "TITLE", "CREATIONDATE", "OWNERDISPLAYNAME", "VIEWCOUNT", "SCORE", "COMMENTCOUNT", "VOTECOUNT", "LASTEDITDATE"
FROM (SELECT "Title" AS "TITLE", "CreationDate0" AS "CREATIONDATE", ANY_VALUE("DisplayName") AS "OWNERDISPLAYNAME", "ViewCount" AS "VIEWCOUNT", "Score" AS "SCORE", COUNT("Id1") AS "COMMENTCOUNT", COUNT("Id2") AS "VOTECOUNT", MAX("CreationDate") AS "LASTEDITDATE"
FROM "s1"
GROUP BY "CreationDate0", "Score", "ViewCount", "Title", "DisplayName"
ORDER BY "Score" DESC NULLS FIRST, "CreationDate0" DESC NULLS FIRST
FETCH NEXT 100 ROWS ONLY) AS "t6"