SELECT COALESCE("t8"."POSTID", "t8"."POSTID") AS "POSTID", "t8"."TITLE", "t8"."CREATIONDATE", "t8"."SCORE", "t8"."VIEWCOUNT", "t8"."COMMENTCOUNT", "t8"."ANSWERCOUNT", "t8"."USERID", "t8"."BADGECOUNT", "t8"."TOTALUPVOTES", "t8"."TOTALDOWNVOTES"
FROM (SELECT "t6"."POSTID", "t6"."TITLE", "t6"."CREATIONDATE", "t6"."SCORE", "t6"."VIEWCOUNT", "t6"."COMMENTCOUNT", "t6"."ANSWERCOUNT", "t2"."USERID", "t2"."BADGECOUNT", "t2"."TOTALUPVOTES", "t2"."TOTALDOWNVOTES"
FROM (SELECT ANY_VALUE("Users"."Id") AS "USERID", COUNT(DISTINCT "Badges"."Id") AS "BADGECOUNT", SUM("Users"."UpVotes") AS "TOTALUPVOTES", SUM("Users"."DownVotes") AS "TOTALDOWNVOTES"
FROM "STACK"."Badges"
RIGHT JOIN "STACK"."Users" ON "Badges"."UserId" = "Users"."Id"
GROUP BY "Users"."Id") AS "t2"
INNER JOIN (SELECT ANY_VALUE("t3"."Id") AS "POSTID", "t3"."Title" AS "TITLE", "t3"."CreationDate" AS "CREATIONDATE", "t3"."Score" AS "SCORE", "t3"."ViewCount" AS "VIEWCOUNT", COUNT(DISTINCT "t3"."Id0") AS "COMMENTCOUNT", COUNT(DISTINCT "Posts0"."Id") AS "ANSWERCOUNT"
FROM "STACK"."Posts" AS "Posts0"
RIGHT JOIN (SELECT "s1"."Id", "s1"."PostTypeId", "s1"."AcceptedAnswerId", "s1"."ParentId", "s1"."CreationDate", "s1"."Score", "s1"."ViewCount", "s1"."Body", "s1"."OwnerUserId", "s1"."OwnerDisplayName", "s1"."LastEditorUserId", "s1"."LastEditorDisplayName", "s1"."LastEditDate", "s1"."LastActivityDate", "s1"."Title", "s1"."Tags", "s1"."AnswerCount", "s1"."CommentCount", "s1"."FavoriteCount", "s1"."ClosedDate", "s1"."CommunityOwnedDate", "s1"."ContentLicense", "Comments"."Id" AS "Id0", "Comments"."PostId", "Comments"."Score" AS "Score0", "Comments"."Text", "Comments"."CreationDate" AS "CreationDate0", "Comments"."UserDisplayName", "Comments"."UserId", "Comments"."ContentLicense" AS "ContentLicense0"
FROM "STACK"."Comments"
RIGHT JOIN "s1" ON "Comments"."PostId" = "s1"."Id") AS "t3" ON "Posts0"."ParentId" = "t3"."Id"
GROUP BY "t3"."Id", "t3"."CreationDate", "t3"."Score", "t3"."ViewCount", "t3"."Title") AS "t6" ON "t2"."USERID" = "t6"."POSTID"
ORDER BY "t6"."SCORE" DESC NULLS FIRST, "t6"."VIEWCOUNT" DESC NULLS FIRST
FETCH NEXT 100 ROWS ONLY) AS "t8"