SELECT COALESCE("PostTypes"."Name", "PostTypes"."Name") AS "Name", ANY_VALUE("PostTypes"."Name") AS "POSTTYPE", COUNT(*) AS "TOTALPOSTS", AVG("Posts"."Score") AS "AVERAGESCORE", SUM("t"."COMMENTCOUNT") AS "TOTALCOMMENTS"
FROM "STACK"."Posts"
INNER JOIN "STACK"."PostTypes" ON "Posts"."PostTypeId" = "PostTypes"."Id"
LEFT JOIN (SELECT "PostId", COUNT(*) AS "COMMENTCOUNT"
FROM "STACK"."Comments"
GROUP BY "PostId") AS "t" ON "Posts"."Id" = "t"."PostId"
GROUP BY "PostTypes"."Name"