SELECT COALESCE("POSTTYPE", "POSTTYPE") AS "POSTTYPE", "TOTALPOSTS", "AVERAGESCORE", "TOTALCOMMENTS"
FROM (SELECT "POSTTYPE", "TOTALPOSTS", "AVERAGESCORE", "TOTALCOMMENTS"
FROM "s1"
ORDER BY "TOTALPOSTS" DESC NULLS FIRST) AS "t3"