SELECT COALESCE("POSTID", "POSTID") AS "POSTID", "TITLE", "CREATIONDATE", "VIEWCOUNT", "SCORE", "OWNERDISPLAYNAME", "COMMENTCOUNT", "VOTECOUNT", "UPVOTES", "DOWNVOTES", "BADGECOUNT"
FROM (SELECT ANY_VALUE("Id") AS "POSTID", "TITLE", "CREATIONDATE", "VIEWCOUNT", "SCORE", ANY_VALUE("DisplayName") AS "OWNERDISPLAYNAME", COUNT("Id1") AS "COMMENTCOUNT", COUNT(DISTINCT "Id2") AS "VOTECOUNT", SUM("FD_COL_8") AS "UPVOTES", SUM("FD_COL_9") AS "DOWNVOTES", COUNT("Id3") AS "BADGECOUNT"
FROM "s1"
GROUP BY "Id", "TITLE", "CREATIONDATE", "VIEWCOUNT", "SCORE", "DisplayName"
ORDER BY "CREATIONDATE" DESC NULLS FIRST
FETCH NEXT 100 ROWS ONLY) AS "t6"