SELECT COALESCE("PostTypeId", "PostTypeId") AS "PostTypeId", COUNT(*) AS "TOTALPOSTS", SUM("Score") AS "TOTALSCORE", AVG("ViewCount") AS "AVERAGEVIEWCOUNT", AVG("AnswerCount") AS "AVERAGEANSWERCOUNT", AVG("CommentCount") AS "AVERAGECOMMENTCOUNT"
FROM "STACK"."Posts"
GROUP BY "PostTypeId"