SELECT COALESCE("s1"."PostTypeId", "s1"."PostTypeId") AS "PostTypeId", "s1"."TOTALPOSTS", "s1"."TOTALSCORE", "s1"."AVERAGEVIEWCOUNT", "s1"."AVERAGEANSWERCOUNT", "s1"."AVERAGECOMMENTCOUNT", "t1"."TOTALUSERS", "t1"."AVERAGEREPUTATION", "t1"."MOSTRECENTACCESSDATE", "t2"."VoteTypeId" AS "VOTETYPEID", "t2"."TOTALVOTES"
FROM "s1",
((SELECT COUNT(*) AS "TOTALUSERS", AVG("Reputation") AS "AVERAGEREPUTATION", MAX("LastAccessDate") AS "MOSTRECENTACCESSDATE"
FROM "STACK"."Users") AS "t1", (SELECT "VoteTypeId", COUNT(*) AS "TOTALVOTES"
FROM "STACK"."Votes"
GROUP BY "VoteTypeId") AS "t2")
ORDER BY "s1"."PostTypeId", "t2"."VoteTypeId"