SELECT COALESCE("t1"."POSTID", "t1"."POSTID") AS "POSTID", "t1"."POSTUPVOTES", "t1"."POSTDOWNVOTES", "t4"."USERID", "t4"."DISPLAYNAME", "t4"."TOTALVOTES", "t4"."UPVOTES", "t4"."DOWNVOTES", "t7"."POSTID" AS "POSTID0", "t7"."TITLE", "t7"."OWNERUSERID", "t7"."SCORE", "t7"."VIEWCOUNT", "t7"."ANSWERCOUNT", "t7"."COMMENTCOUNT"
FROM (SELECT ANY_VALUE("Posts"."Id") AS "POSTID", SUM(CASE WHEN CAST("Votes"."VoteTypeId" AS INTEGER) = 2 THEN 1 ELSE 0 END) AS "POSTUPVOTES", SUM(CASE WHEN CAST("Votes"."VoteTypeId" AS INTEGER) = 3 THEN 1 ELSE 0 END) AS "POSTDOWNVOTES"
FROM "STACK"."Votes"
RIGHT JOIN "STACK"."Posts" ON "Votes"."PostId" = "Posts"."Id"
GROUP BY "Posts"."Id") AS "t1"
INNER JOIN ((SELECT ANY_VALUE("Users"."Id") AS "USERID", "Users"."DisplayName" AS "DISPLAYNAME", COUNT("Votes0"."Id") AS "TOTALVOTES", SUM(CASE WHEN CAST("Votes0"."VoteTypeId" AS INTEGER) = 2 THEN 1 ELSE 0 END) AS "UPVOTES", SUM(CASE WHEN CAST("Votes0"."VoteTypeId" AS INTEGER) = 3 THEN 1 ELSE 0 END) AS "DOWNVOTES"
FROM "STACK"."Votes" AS "Votes0"
RIGHT JOIN "STACK"."Users" ON "Votes0"."UserId" = "Users"."Id"
GROUP BY "Users"."Id", "Users"."DisplayName") AS "t4" INNER JOIN (SELECT ANY_VALUE("Posts0"."Id") AS "POSTID", "Posts0"."Title" AS "TITLE", "Posts0"."OwnerUserId" AS "OWNERUSERID", "Posts0"."Score" AS "SCORE", "Posts0"."ViewCount" AS "VIEWCOUNT", "Posts0"."AnswerCount" AS "ANSWERCOUNT", COUNT("Comments"."Id") AS "COMMENTCOUNT"
FROM "STACK"."Comments"
RIGHT JOIN "STACK"."Posts" AS "Posts0" ON "Comments"."PostId" = "Posts0"."Id"
GROUP BY "Posts0"."Id", "Posts0"."Score", "Posts0"."ViewCount", "Posts0"."OwnerUserId", "Posts0"."Title", "Posts0"."AnswerCount") AS "t7" ON "t4"."USERID" = "t7"."OWNERUSERID") ON "t1"."POSTID" = "t7"."POSTID"