SELECT COALESCE("t1"."TOTALPOSTS", "t1"."TOTALPOSTS") AS "TOTALPOSTS", "t1"."UNIQUEUSERS", "t1"."TOTALANSWERS", "t1"."TOTALCOMMENTS", "s1"."TOTALVOTES", "s1"."UNIQUEVOTERS", "t2"."TOTALUSERS", "t2"."AVGREPUTATION", "t2"."MAXREPUTATION"
FROM (SELECT COUNT(*) AS "TOTALPOSTS", COUNT(DISTINCT "OwnerUserId") AS "UNIQUEUSERS", SUM("AnswerCount") AS "TOTALANSWERS", SUM("CommentCount") AS "TOTALCOMMENTS"
FROM "STACK"."Posts") AS "t1",
("s1", (SELECT COUNT(*) AS "TOTALUSERS", AVG("Reputation") AS "AVGREPUTATION", MAX("Reputation") AS "MAXREPUTATION"
FROM "STACK"."Users") AS "t2")