SELECT COALESCE("USERID", "USERID") AS "USERID", "DISPLAYNAME", "REPUTATION", "POSTCOUNT", "QUESTIONCOUNT", "ANSWERCOUNT", "TOTALCOMMENTSCORE", "TOTALBOUNTYAMOUNT", "BADGECOUNT", "LASTACTIVE"
FROM (SELECT "Id", "DISPLAYNAME", "REPUTATION", ANY_VALUE("Id") AS "USERID", COUNT(DISTINCT "Id0") AS "POSTCOUNT", SUM("FD_COL_4") AS "QUESTIONCOUNT", SUM("FD_COL_5") AS "ANSWERCOUNT", SUM("Score0") AS "TOTALCOMMENTSCORE", SUM("BountyAmount") AS "TOTALBOUNTYAMOUNT", COUNT(DISTINCT "Id3") AS "BADGECOUNT", MAX("CreationDate0") AS "LASTACTIVE"
FROM "s1"
GROUP BY "Id", "DISPLAYNAME", "REPUTATION"
ORDER BY "REPUTATION" DESC NULLS FIRST, 5 DESC NULLS FIRST
FETCH NEXT 100 ROWS ONLY) AS "t4"