SELECT COALESCE("t9"."POSTID", "t9"."POSTID") AS "POSTID", "t9"."TITLE", "t9"."CREATIONDATE", "t9"."OWNERDISPLAYNAME", "t9"."NUMBEROFCOMMENTS", "t9"."NUMBEROFANSWERS", "t9"."TOTALUPVOTES"
FROM (SELECT "s1"."Id" AS "POSTID", "s1"."Title" AS "TITLE", "s1"."CreationDate" AS "CREATIONDATE", "s1"."DisplayName" AS "OWNERDISPLAYNAME", CASE WHEN "s1"."COMMENTCOUNT_" IS NOT NULL THEN CAST("s1"."COMMENTCOUNT_" AS BIGINT) ELSE 0 END AS "NUMBEROFCOMMENTS", CASE WHEN "s1"."ANSWERCOUNT_" IS NOT NULL THEN CAST("s1"."ANSWERCOUNT_" AS BIGINT) ELSE 0 END AS "NUMBEROFANSWERS", CASE WHEN "t7"."TOTALUPVOTES" IS NOT NULL THEN CAST("t7"."TOTALUPVOTES" AS BIGINT) ELSE 0 END AS "TOTALUPVOTES"
FROM (SELECT "PostId", COUNT(*) AS "TOTALUPVOTES"
FROM "STACK"."Votes"
WHERE CAST("VoteTypeId" AS INTEGER) = 2
GROUP BY "PostId") AS "t7"
RIGHT JOIN "s1" ON "t7"."PostId" = "s1"."Id"
ORDER BY "s1"."CreationDate" DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY) AS "t9"