SELECT COALESCE("DISPLAYNAME", "DISPLAYNAME") AS "DISPLAYNAME", "POSTCOUNT", "QUESTIONCOUNT", "ANSWERCOUNT", "AVERAGEREPUTATION"
FROM (SELECT "DISPLAYNAME", COUNT(DISTINCT "Id0") AS "POSTCOUNT", SUM("FD_COL_2") AS "QUESTIONCOUNT", SUM("FD_COL_3") AS "ANSWERCOUNT", AVG("Reputation") AS "AVERAGEREPUTATION"
FROM "s1"
GROUP BY "DISPLAYNAME"
ORDER BY 2 DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY) AS "t2"