SELECT COALESCE("DisplayName", "DisplayName") AS "DisplayName", "POSTCOUNT", "TOTALVIEWS"
FROM (SELECT "DisplayName", COUNT(*) AS "POSTCOUNT", SUM("ViewCount") AS "TOTALVIEWS"
FROM "s1"
GROUP BY "DisplayName"
ORDER BY 2 DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY) AS "t1"