SELECT COALESCE("POSTID", "POSTID") AS "POSTID", "TITLE", "OWNER", "CREATIONDATE", "VIEWCOUNT", "SCORE", "COMMENTCOUNT"
FROM (SELECT "Id" AS "POSTID", "Title" AS "TITLE", "DisplayName" AS "OWNER", "CreationDate" AS "CREATIONDATE", "ViewCount" AS "VIEWCOUNT", "Score" AS "SCORE", "FD_COL_35" AS "COMMENTCOUNT"
FROM "s1"
ORDER BY "CreationDate" DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY) AS "t8"