SELECT COALESCE("Users"."Id", "Users"."Id") AS "Id", "Users"."Reputation", "Users"."CreationDate", "Users"."DisplayName", "Users"."LastAccessDate", "Users"."WebsiteUrl", "Users"."Location", "Users"."AboutMe", "Users"."Views", "Users"."UpVotes", "Users"."DownVotes", "Users"."ProfileImageUrl", "Users"."AccountId", "t0"."OWNERUSERID", "t0"."TOTALPOSTS", "t0"."ANSWEREDQUESTIONS", "t0"."QUESTIONS", "t0"."POPULARPOSTS", "t3"."USERID", "t3"."DISPLAYNAME" AS "DISPLAYNAME_", "t3"."BADGECOUNT", "t3"."GOLDBADGES", "t3"."SILVERBADGES", "t3"."BRONZEBADGES"
FROM "STACK"."Users"
LEFT JOIN (SELECT "OwnerUserId" AS "OWNERUSERID", COUNT(*) AS "TOTALPOSTS", COUNT(DISTINCT "ParentId") AS "ANSWEREDQUESTIONS", SUM(CASE WHEN CAST("PostTypeId" AS INTEGER) = 1 THEN 1 ELSE 0 END) AS "QUESTIONS", SUM(CASE WHEN "ViewCount" > 100 THEN 1 ELSE 0 END) AS "POPULARPOSTS"
FROM "STACK"."Posts"
GROUP BY "OwnerUserId") AS "t0" ON "Users"."Id" = "t0"."OWNERUSERID"
LEFT JOIN (SELECT ANY_VALUE("Users0"."Id") AS "USERID", "Users0"."DisplayName" AS "DISPLAYNAME", COUNT("Badges"."Id") AS "BADGECOUNT", SUM(CASE WHEN CAST("Badges"."Class" AS INTEGER) = 1 THEN 1 ELSE 0 END) AS "GOLDBADGES", SUM(CASE WHEN CAST("Badges"."Class" AS INTEGER) = 2 THEN 1 ELSE 0 END) AS "SILVERBADGES", SUM(CASE WHEN CAST("Badges"."Class" AS INTEGER) = 3 THEN 1 ELSE 0 END) AS "BRONZEBADGES"
FROM "STACK"."Badges"
RIGHT JOIN "STACK"."Users" AS "Users0" ON "Badges"."UserId" = "Users0"."Id"
GROUP BY "Users0"."Id", "Users0"."DisplayName") AS "t3" ON "Users"."Id" = "t3"."USERID"