SELECT COALESCE("t10"."POSTID", "t10"."POSTID") AS "POSTID", "t10"."TITLE", "t10"."TAGSLIST", "t10"."USERDISPLAYNAME", "t10"."TOTALPOSTS", "t10"."TOTALVIEWS", "t10"."TOTALANSWERED", "t10"."HIGHENGAGEMENTPOSTS", "t10"."TOTALMODERATIONHISTORY", "t10"."TOTALCLOSURES", "t10"."TOTALREOPENS"
FROM (SELECT "t7"."POSTID", "t7"."TITLE", "t7"."TAGSLIST", "t5"."DISPLAYNAME" AS "USERDISPLAYNAME", "t5"."TOTALPOSTS", "t5"."TOTALVIEWS", "t5"."TOTALANSWERED", "t5"."HIGHENGAGEMENTPOSTS", "t7"."TOTALMODERATIONHISTORY", "t7"."TOTALCLOSURES", "t7"."TOTALREOPENS"
FROM (SELECT ANY_VALUE("Users"."Id") AS "USERID", "Users"."DisplayName" AS "DISPLAYNAME", COUNT(DISTINCT "t2"."Id") AS "TOTALPOSTS", SUM("t2"."ViewCount") AS "TOTALVIEWS", SUM(CASE WHEN "t2"."AnswerCount" > 0 THEN 1 ELSE 0 END) AS "TOTALANSWERED", SUM(CASE WHEN "t2"."ViewCount" > 100 THEN 1 ELSE 0 END) AS "HIGHENGAGEMENTPOSTS"
FROM "STACK"."Users"
INNER JOIN (SELECT *
FROM "STACK"."Posts"
WHERE "CreationDate" >= (TIMESTAMP '2024-10-01 12:34:56' - INTERVAL '1' YEAR)) AS "t2" ON "Users"."Id" = "t2"."OwnerUserId"
GROUP BY "Users"."Id", "Users"."DisplayName") AS "t5"
INNER JOIN (SELECT ANY_VALUE("Id") AS "POSTID", "TITLE", "VIEWCOUNT", "ANSWERCOUNT", "CREATIONDATE", LISTAGG(DISTINCT "TagName", "FD_COL_6") AS "TAGSLIST", COUNT(DISTINCT "UserId") AS "TOTALMODERATIONHISTORY", SUM("FD_COL_8") AS "TOTALCLOSURES", SUM("FD_COL_9") AS "TOTALREOPENS", CAST(ANY_VALUE("Id") AS BIGINT) AS "POSTID0"
FROM "s1"
GROUP BY "Id", "TITLE", "VIEWCOUNT", "ANSWERCOUNT", "CREATIONDATE") AS "t7" ON "t5"."TOTALPOSTS" = "t7"."POSTID0"
WHERE "t5"."TOTALVIEWS" > 500
ORDER BY "t5"."TOTALANSWERED" DESC NULLS FIRST) AS "t10"