SELECT COALESCE("t"."OwnerUserId", "t"."OwnerUserId") AS "OWNERUSERID", "t"."POSTCOUNT", "t"."TOTALVIEWS", "t"."TOTALSCORE", "t"."AVGSCORE", "t2"."USERID", "t2"."DISPLAYNAME", "t2"."BADGECOUNT", "t2"."GOLDBADGES", "t2"."SILVERBADGES", "t2"."BRONZEBADGES"
FROM (SELECT "OwnerUserId", COUNT(*) AS "POSTCOUNT", SUM("ViewCount") AS "TOTALVIEWS", SUM("Score") AS "TOTALSCORE", AVG("Score") AS "AVGSCORE"
FROM "STACK"."Posts"
GROUP BY "OwnerUserId") AS "t"
INNER JOIN (SELECT ANY_VALUE("Users"."Id") AS "USERID", "Users"."DisplayName" AS "DISPLAYNAME", COUNT("Badges"."Id") AS "BADGECOUNT", SUM(CASE WHEN CAST("Badges"."Class" AS INTEGER) = 1 THEN 1 ELSE 0 END) AS "GOLDBADGES", SUM(CASE WHEN CAST("Badges"."Class" AS INTEGER) = 2 THEN 1 ELSE 0 END) AS "SILVERBADGES", SUM(CASE WHEN CAST("Badges"."Class" AS INTEGER) = 3 THEN 1 ELSE 0 END) AS "BRONZEBADGES"
FROM "STACK"."Badges"
RIGHT JOIN "STACK"."Users" ON "Badges"."UserId" = "Users"."Id"
GROUP BY "Users"."Id", "Users"."DisplayName") AS "t2" ON "t"."OwnerUserId" = "t2"."USERID"
WHERE "t2"."BADGECOUNT" > 0 AND "t"."POSTCOUNT" > 10