SELECT COALESCE("t10"."USERID", "t10"."USERID") AS "USERID", "t10"."DISPLAYNAME", "t10"."TOTALBADGES", "t10"."GOLDBADGES", "t10"."SILVERBADGES", "t10"."BRONZEBADGES", "t10"."POSTID", "t10"."TITLE", "t10"."COMMENTCOUNT", "t10"."UPVOTECOUNT", "t10"."DOWNVOTECOUNT"
FROM (SELECT "t3"."USERID", "t3"."DISPLAYNAME", "t3"."TOTALBADGES", "t3"."GOLDBADGES", "t3"."SILVERBADGES", "t3"."BRONZEBADGES", "t8"."POSTID", "t8"."TITLE", "t8"."COMMENTCOUNT", "t8"."UPVOTECOUNT", "t8"."DOWNVOTECOUNT"
FROM "STACK"."Posts" AS "Posts0"
INNER JOIN (SELECT ANY_VALUE("Users"."Id") AS "USERID", "Users"."DisplayName" AS "DISPLAYNAME", COUNT("Badges"."Id") AS "TOTALBADGES", SUM(CASE WHEN CAST("Badges"."Class" AS INTEGER) = 1 THEN 1 ELSE 0 END) AS "GOLDBADGES", SUM(CASE WHEN CAST("Badges"."Class" AS INTEGER) = 2 THEN 1 ELSE 0 END) AS "SILVERBADGES", SUM(CASE WHEN CAST("Badges"."Class" AS INTEGER) = 3 THEN 1 ELSE 0 END) AS "BRONZEBADGES"
FROM "STACK"."Badges"
RIGHT JOIN "STACK"."Users" ON "Badges"."UserId" = "Users"."Id"
GROUP BY "Users"."Id", "Users"."DisplayName") AS "t3" ON "Posts0"."OwnerUserId" = "t3"."USERID"
INNER JOIN (SELECT ANY_VALUE("t4"."Id") AS "POSTID", "t4"."Title" AS "TITLE", COUNT("t4"."Id0") AS "COMMENTCOUNT", SUM(CASE WHEN CAST("Votes"."VoteTypeId" AS INTEGER) = 2 THEN 1 ELSE 0 END) AS "UPVOTECOUNT", SUM(CASE WHEN CAST("Votes"."VoteTypeId" AS INTEGER) = 3 THEN 1 ELSE 0 END) AS "DOWNVOTECOUNT"
FROM "STACK"."Votes"
RIGHT JOIN (SELECT "s1"."Id", "s1"."PostTypeId", "s1"."AcceptedAnswerId", "s1"."ParentId", "s1"."CreationDate", "s1"."Score", "s1"."ViewCount", "s1"."Body", "s1"."OwnerUserId", "s1"."OwnerDisplayName", "s1"."LastEditorUserId", "s1"."LastEditorDisplayName", "s1"."LastEditDate", "s1"."LastActivityDate", "s1"."Title", "s1"."Tags", "s1"."AnswerCount", "s1"."CommentCount", "s1"."FavoriteCount", "s1"."ClosedDate", "s1"."CommunityOwnedDate", "s1"."ContentLicense", "Comments"."Id" AS "Id0", "Comments"."PostId", "Comments"."Score" AS "Score0", "Comments"."Text", "Comments"."CreationDate" AS "CreationDate0", "Comments"."UserDisplayName", "Comments"."UserId", "Comments"."ContentLicense" AS "ContentLicense0"
FROM "STACK"."Comments"
RIGHT JOIN "s1" ON "Comments"."PostId" = "s1"."Id") AS "t4" ON "Votes"."PostId" = "t4"."Id"
GROUP BY "t4"."Id", "t4"."Title"
HAVING COUNT("t4"."Id0") > 5 AND SUM(CASE WHEN CAST("Votes"."VoteTypeId" AS INTEGER) = 2 THEN 1 ELSE 0 END) > SUM(CASE WHEN CAST("Votes"."VoteTypeId" AS INTEGER) = 3 THEN 1 ELSE 0 END)) AS "t8" ON "Posts0"."Id" = "t8"."POSTID"
ORDER BY "t3"."TOTALBADGES" DESC NULLS FIRST, "t8"."UPVOTECOUNT" DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY) AS "t10"