SELECT COALESCE("t10"."USERDISPLAYNAME", "t10"."USERDISPLAYNAME") AS "USERDISPLAYNAME", "t10"."TOTALREPUTATION", "t10"."BADGECOUNT", "t10"."CLOSEDPOSTS", "t10"."POSTTITLE", "t10"."POSTCREATIONDATE", "t10"."POSTUPVOTES", "t10"."POSTDOWNVOTES", "t10"."POSTAVGVOTE"
FROM (SELECT "s1"."DISPLAYNAME" AS "USERDISPLAYNAME", "s1"."TOTALREPUTATION", "s1"."BADGECOUNT", "s1"."CLOSEDPOSTS", "s1"."Title" AS "POSTTITLE", "s1"."CreationDate" AS "POSTCREATIONDATE", CASE WHEN "t7"."TOTALUPVOTES" IS NOT NULL THEN CAST("t7"."TOTALUPVOTES" AS INTEGER) ELSE 0 END AS "POSTUPVOTES", CASE WHEN "t7"."TOTALDOWNVOTES" IS NOT NULL THEN CAST("t7"."TOTALDOWNVOTES" AS INTEGER) ELSE 0 END AS "POSTDOWNVOTES", CASE WHEN "t7"."AVGVOTETYPE" IS NOT NULL THEN CAST("t7"."AVGVOTETYPE" AS INTEGER) ELSE 0 END AS "POSTAVGVOTE"
FROM (SELECT "PostId" AS "POSTID", SUM(CASE WHEN CAST("VoteTypeId" AS INTEGER) = 2 THEN 1 ELSE 0 END) AS "TOTALUPVOTES", SUM(CASE WHEN CAST("VoteTypeId" AS INTEGER) = 3 THEN 1 ELSE 0 END) AS "TOTALDOWNVOTES", AVG(CASE WHEN CAST("VoteTypeId" AS INTEGER) IN (2, 3) THEN "VoteTypeId" ELSE NULL END) AS "AVGVOTETYPE"
FROM "STACK"."Votes"
GROUP BY "PostId") AS "t7"
RIGHT JOIN "s1" ON "t7"."POSTID" = "s1"."Id"
WHERE "s1"."CLOSEDPOSTS" > 0
ORDER BY "s1"."TOTALREPUTATION" DESC NULLS FIRST, "s1"."CreationDate" DESC NULLS FIRST
FETCH NEXT 100 ROWS ONLY) AS "t10"