SELECT COALESCE("t4"."POSTID", "t4"."POSTID") AS "POSTID", "t4"."TITLE", "t4"."SCORE", "t4"."CREATIONDATE", "t4"."UPVOTES", "t4"."DOWNVOTES", "t4"."USERBADGECOUNT", "t9"."POSTID" AS "POSTID0", "t9"."LASTCLOSEDATE", "t9"."CLOSEREASONNAMES"
FROM (SELECT "t2"."Id" AS "POSTID", "t2"."Title" AS "TITLE", "t2"."Score" AS "SCORE", "t2"."CreationDate" AS "CREATIONDATE", CASE WHEN "t2"."UPVOTES" IS NOT NULL THEN CAST("t2"."UPVOTES" AS INTEGER) ELSE 0 END AS "UPVOTES", CASE WHEN "t2"."DOWNVOTES" IS NOT NULL THEN CAST("t2"."DOWNVOTES" AS INTEGER) ELSE 0 END AS "DOWNVOTES", CASE WHEN "t3"."BADGECOUNT" IS NOT NULL THEN CAST("t3"."BADGECOUNT" AS BIGINT) ELSE 0 END AS "USERBADGECOUNT"
FROM (SELECT "t1"."Id", "t1"."PostTypeId", "t1"."AcceptedAnswerId", "t1"."ParentId", "t1"."CreationDate", "t1"."Score", "t1"."ViewCount", "t1"."Body", "t1"."OwnerUserId", "t1"."OwnerDisplayName", "t1"."LastEditorUserId", "t1"."LastEditorDisplayName", "t1"."LastEditDate", "t1"."LastActivityDate", "t1"."Title", "t1"."Tags", "t1"."AnswerCount", "t1"."CommentCount", "t1"."FavoriteCount", "t1"."ClosedDate", "t1"."CommunityOwnedDate", "t1"."ContentLicense", "t0"."POSTID", "t0"."UPVOTES", "t0"."DOWNVOTES", "t0"."TOTALVOTES"
FROM (SELECT "PostId" AS "POSTID", SUM(CASE WHEN CAST("VoteTypeId" AS INTEGER) = 2 THEN 1 ELSE 0 END) AS "UPVOTES", SUM(CASE WHEN CAST("VoteTypeId" AS INTEGER) = 3 THEN 1 ELSE 0 END) AS "DOWNVOTES", COUNT(*) AS "TOTALVOTES"
FROM "STACK"."Votes"
GROUP BY "PostId") AS "t0"
RIGHT JOIN (SELECT *
FROM "STACK"."Posts"
WHERE "CreationDate" >= (TIMESTAMP '2024-10-01 12:34:56' - INTERVAL '30' DAY)) AS "t1" ON "t0"."POSTID" = "t1"."Id") AS "t2"
LEFT JOIN "STACK"."Users" ON "t2"."OwnerUserId" = "Users"."Id"
LEFT JOIN (SELECT "UserId", COUNT(*) AS "BADGECOUNT"
FROM "STACK"."Badges"
GROUP BY "UserId") AS "t3" ON "Users"."Id" = "t3"."UserId") AS "t4"
LEFT JOIN (SELECT "t6"."PostId" AS "POSTID", MAX("t6"."CreationDate") AS "LASTCLOSEDATE", LISTAGG("t5"."Name", ', ') AS "CLOSEREASONNAMES"
FROM (SELECT "Id", "Name", CAST("Id" AS INTEGER) AS "Id0"
FROM "STACK"."CloseReasonTypes") AS "t5"
INNER JOIN (SELECT "Id", "PostHistoryTypeId", "PostId", "RevisionGUID", "CreationDate", "UserId", "UserDisplayName", "Comment", "Text", "ContentLicense", CAST("Comment" AS INTEGER) AS "Comment0"
FROM "STACK"."PostHistory") AS "t6" ON "t5"."Id0" = "t6"."Comment0"
WHERE CAST("t6"."PostHistoryTypeId" AS INTEGER) = 10
GROUP BY "t6"."PostId") AS "t9" ON "t4"."POSTID" = "t9"."POSTID"