SELECT COALESCE("POSTID", "POSTID") AS "POSTID", "TITLE", "SCORE", "CREATIONDATE", "UPVOTES", "DOWNVOTES", "USERBADGECOUNT", "LASTCLOSEDATE", "CLOSEREASONNAMES", "POSTSTATUS"
FROM (SELECT "POSTID", "TITLE", "SCORE", "CREATIONDATE", "UPVOTES", "DOWNVOTES", "USERBADGECOUNT", "LASTCLOSEDATE", "CLOSEREASONNAMES", CASE WHEN "LASTCLOSEDATE" IS NOT NULL THEN 'Closed' ELSE 'Open  ' END AS "POSTSTATUS"
FROM "s1"
ORDER BY "SCORE" DESC NULLS FIRST, "CREATIONDATE" DESC NULLS FIRST
FETCH NEXT 100 ROWS ONLY) AS "t12"