SELECT COALESCE("t10"."USERID", "t10"."USERID") AS "USERID", "t10"."DISPLAYNAME", "t10"."NETVOTES", "t10"."GOLDBADGES", "t10"."SILVERBADGES", "t10"."BRONZEBADGES", "t10"."COMMENTCOUNT", "t10"."RELATEDPOSTS"
FROM (SELECT "t8"."USERID", "t8"."DISPLAYNAME", "t8"."NETVOTES", "t8"."GOLDBADGES", "t8"."SILVERBADGES", "t8"."BRONZEBADGES", CASE WHEN "t3"."COMMENTCOUNT" IS NOT NULL THEN CAST("t3"."COMMENTCOUNT" AS BIGINT) ELSE 0 END AS "COMMENTCOUNT", CASE WHEN "t3"."RELATEDPOSTS" IS NOT NULL THEN CAST("t3"."RELATEDPOSTS" AS BIGINT) ELSE 0 END AS "RELATEDPOSTS"
FROM (SELECT ANY_VALUE("t1"."Id") AS "POSTID", "t1"."OwnerUserId" AS "OWNERUSERID", COUNT("t1"."Id0") AS "COMMENTCOUNT", COUNT(DISTINCT "Posts0"."Id") AS "RELATEDPOSTS"
FROM (SELECT "s1"."Id", "s1"."PostTypeId", "s1"."AcceptedAnswerId", "s1"."ParentId", "s1"."CreationDate", "s1"."Score", "s1"."ViewCount", "s1"."Body", "s1"."OwnerUserId", "s1"."OwnerDisplayName", "s1"."LastEditorUserId", "s1"."LastEditorDisplayName", "s1"."LastEditDate", "s1"."LastActivityDate", "s1"."Title", "s1"."Tags", "s1"."AnswerCount", "s1"."CommentCount", "s1"."FavoriteCount", "s1"."ClosedDate", "s1"."CommunityOwnedDate", "s1"."ContentLicense", "Comments"."Id" AS "Id0", "Comments"."PostId", "Comments"."Score" AS "Score0", "Comments"."Text", "Comments"."CreationDate" AS "CreationDate0", "Comments"."UserDisplayName", "Comments"."UserId", "Comments"."ContentLicense" AS "ContentLicense0"
FROM "STACK"."Comments"
RIGHT JOIN "s1" ON "Comments"."PostId" = "s1"."Id") AS "t1"
LEFT JOIN "STACK"."PostLinks" ON "t1"."Id" = "PostLinks"."PostId"
LEFT JOIN "STACK"."Posts" AS "Posts0" ON "PostLinks"."RelatedPostId" = "Posts0"."Id"
GROUP BY "t1"."Id", "t1"."OwnerUserId") AS "t3"
RIGHT JOIN (SELECT ANY_VALUE("t4"."Id") AS "USERID", "t4"."DisplayName" AS "DISPLAYNAME", SUM(CASE WHEN CAST("t4"."VoteTypeId" AS INTEGER) = 2 THEN 1 ELSE 0 END) - SUM(CASE WHEN CAST("t4"."VoteTypeId" AS INTEGER) = 3 THEN 1 ELSE 0 END) AS "NETVOTES", SUM(CASE WHEN CAST("Badges"."Class" AS INTEGER) = 1 THEN 1 ELSE 0 END) AS "GOLDBADGES", SUM(CASE WHEN CAST("Badges"."Class" AS INTEGER) = 2 THEN 1 ELSE 0 END) AS "SILVERBADGES", SUM(CASE WHEN CAST("Badges"."Class" AS INTEGER) = 3 THEN 1 ELSE 0 END) AS "BRONZEBADGES"
FROM (SELECT "Users"."Id", "Users"."Reputation", "Users"."CreationDate", "Users"."DisplayName", "Users"."LastAccessDate", "Users"."WebsiteUrl", "Users"."Location", "Users"."AboutMe", "Users"."Views", "Users"."UpVotes", "Users"."DownVotes", "Users"."ProfileImageUrl", "Users"."AccountId", "Votes"."Id" AS "Id0", "Votes"."PostId", "Votes"."VoteTypeId", "Votes"."UserId", "Votes"."CreationDate" AS "CreationDate0", "Votes"."BountyAmount"
FROM "STACK"."Votes"
RIGHT JOIN "STACK"."Users" ON "Votes"."UserId" = "Users"."Id") AS "t4"
LEFT JOIN "STACK"."Badges" ON "t4"."Id" = "Badges"."UserId"
GROUP BY "t4"."Id", "t4"."DisplayName"
HAVING SUM(CASE WHEN CAST("t4"."VoteTypeId" AS INTEGER) = 2 THEN 1 ELSE 0 END) - SUM(CASE WHEN CAST("t4"."VoteTypeId" AS INTEGER) = 3 THEN 1 ELSE 0 END) > 10 AND (SUM(CASE WHEN CAST("Badges"."Class" AS INTEGER) = 1 THEN 1 ELSE 0 END) > 0 OR SUM(CASE WHEN CAST("Badges"."Class" AS INTEGER) = 2 THEN 1 ELSE 0 END) > 2)) AS "t8" ON "t3"."OWNERUSERID" = "t8"."USERID"
ORDER BY "t8"."NETVOTES" DESC NULLS FIRST, "t8"."DISPLAYNAME"
FETCH NEXT 50 ROWS ONLY) AS "t10"