SELECT COALESCE("t3"."USERID", "t3"."USERID") AS "USERID", "t3"."DISPLAYNAME", "t3"."TOTALSCORE", "t3"."TOTALPOSTS", "t3"."TOTALBADGES", "t3"."AVGVIEWCOUNT", "t17"."POSTID", "t17"."REVCOUNT", "t17"."LASTREVISION", "t17"."USERCOUNT", "t17"."TOTALDOWNVOTES"
FROM (SELECT ANY_VALUE("t"."Id") AS "USERID", "t"."DisplayName" AS "DISPLAYNAME", SUM("t"."Score") AS "TOTALSCORE", COUNT(DISTINCT "t"."Id0") AS "TOTALPOSTS", COUNT(DISTINCT "Badges"."Id") AS "TOTALBADGES", AVG(CASE WHEN "t"."ViewCount" IS NOT NULL THEN CAST("t"."ViewCount" AS INTEGER) ELSE 0 END) AS "AVGVIEWCOUNT"
FROM (SELECT "Users"."Id", "Users"."Reputation", "Users"."CreationDate", "Users"."DisplayName", "Users"."LastAccessDate", "Users"."WebsiteUrl", "Users"."Location", "Users"."AboutMe", "Users"."Views", "Users"."UpVotes", "Users"."DownVotes", "Users"."ProfileImageUrl", "Users"."AccountId", "Posts"."Id" AS "Id0", "Posts"."PostTypeId", "Posts"."AcceptedAnswerId", "Posts"."ParentId", "Posts"."CreationDate" AS "CreationDate0", "Posts"."Score", "Posts"."ViewCount", "Posts"."Body", "Posts"."OwnerUserId", "Posts"."OwnerDisplayName", "Posts"."LastEditorUserId", "Posts"."LastEditorDisplayName", "Posts"."LastEditDate", "Posts"."LastActivityDate", "Posts"."Title", "Posts"."Tags", "Posts"."AnswerCount", "Posts"."CommentCount", "Posts"."FavoriteCount", "Posts"."ClosedDate", "Posts"."CommunityOwnedDate", "Posts"."ContentLicense"
FROM "STACK"."Posts"
RIGHT JOIN "STACK"."Users" ON "Posts"."OwnerUserId" = "Users"."Id") AS "t"
LEFT JOIN "STACK"."Badges" ON "t"."Id" = "Badges"."UserId"
GROUP BY "t"."Id", "t"."DisplayName"
HAVING COUNT(DISTINCT "t"."Id0") > 5 AND SUM("t"."Score") IS NOT NULL) AS "t3"
INNER JOIN (SELECT ANY_VALUE("t6"."Id") AS "POSTID", COUNT(*) AS "REVCOUNT", MAX("t6"."CREATIONDATE") AS "LASTREVISION", COUNT(DISTINCT "t6"."UserId") AS "USERCOUNT", ANY_VALUE(CASE WHEN "t14"."EXPR$0" IS NULL THEN 0 ELSE "t14"."EXPR$0" END) AS "TOTALDOWNVOTES"
FROM (SELECT "Posts0"."Id", "Posts0"."PostTypeId", "Posts0"."AcceptedAnswerId", "Posts0"."ParentId", "Posts0"."CreationDate", "Posts0"."Score", "Posts0"."ViewCount", "Posts0"."Body", "Posts0"."OwnerUserId", "Posts0"."OwnerDisplayName", "Posts0"."LastEditorUserId", "Posts0"."LastEditorDisplayName", "Posts0"."LastEditDate", "Posts0"."LastActivityDate", "Posts0"."Title", "Posts0"."Tags", "Posts0"."AnswerCount", "Posts0"."CommentCount", "Posts0"."FavoriteCount", "Posts0"."ClosedDate", "Posts0"."CommunityOwnedDate", "Posts0"."ContentLicense", "t5"."POSTID", "t5"."USERID", "t5"."CREATIONDATE", "t5"."COMMENT", "t5"."TEXT", "t5"."REVISIONRANK", "PostHistory"."Id" AS "Id0", "PostHistory"."PostHistoryTypeId", "PostHistory"."PostId", "PostHistory"."RevisionGUID", "PostHistory"."CreationDate" AS "CreationDate0", "PostHistory"."UserId", "PostHistory"."UserDisplayName", "PostHistory"."Comment", "PostHistory"."Text", "PostHistory"."ContentLicense" AS "ContentLicense0"
FROM "STACK"."PostHistory"
RIGHT JOIN ("STACK"."Posts" AS "Posts0" INNER JOIN (SELECT "PostId" AS "POSTID", "UserId" AS "USERID", "CreationDate" AS "CREATIONDATE", "Comment" AS "COMMENT", "Text" AS "TEXT", ROW_NUMBER() OVER (PARTITION BY "PostId" ORDER BY "CreationDate" DESC NULLS FIRST) AS "REVISIONRANK"
FROM "STACK"."PostHistory"
WHERE CAST("PostHistoryTypeId" AS INTEGER) IN (10, 11)) AS "t5" ON "Posts0"."Id" = "t5"."POSTID") ON "PostHistory"."PostId" = "Posts0"."Id") AS "t6"
LEFT JOIN (SELECT "t10"."Id" AS "PostId", CASE WHEN "t13"."EXPR$0" IS NOT NULL THEN "t13"."EXPR$0" ELSE 0 END AS "EXPR$0"
FROM (SELECT "Posts1"."Id"
FROM "STACK"."PostHistory" AS "PostHistory1"
RIGHT JOIN ("STACK"."Posts" AS "Posts1" INNER JOIN (SELECT "PostId" AS "POSTID", "UserId" AS "USERID", "CreationDate" AS "CREATIONDATE", "Comment" AS "COMMENT", "Text" AS "TEXT", ROW_NUMBER() OVER (PARTITION BY "PostId" ORDER BY "CreationDate" DESC NULLS FIRST) AS "REVISIONRANK"
FROM "STACK"."PostHistory"
WHERE CAST("PostHistoryTypeId" AS INTEGER) IN (10, 11)) AS "t8" ON "Posts1"."Id" = "t8"."POSTID") ON "PostHistory1"."PostId" = "Posts1"."Id"
GROUP BY "Posts1"."Id") AS "t10"
LEFT JOIN (SELECT "PostId", COUNT(*) AS "EXPR$0"
FROM "STACK"."Votes"
WHERE CAST("VoteTypeId" AS INTEGER) = 3
GROUP BY "PostId") AS "t13" ON "t10"."Id" IS NOT DISTINCT FROM "t13"."PostId") AS "t14" ON "t6"."Id" = "t14"."PostId"
GROUP BY "t6"."Id") AS "t17" ON "t3"."USERID" = "t17"."POSTID"