SELECT COALESCE("USERID", "USERID") AS "USERID", "DISPLAYNAME", "TOTALPOSTS", "TOTALVOTES", "TOTALUPVOTES", "TOTALDOWNVOTES", "TOTALBADGES", "HIGHESTBADGELEVEL", "BADGELEVELDESCRIPTION"
FROM "s1"
ORDER BY "TOTALPOSTS" DESC NULLS FIRST, "TOTALVOTES" DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY