SELECT COALESCE("POSTID", "POSTID") AS "POSTID", "TITLE", "CREATIONDATE", "SCORE", "VIEWCOUNT", "ANSWERCOUNT", "OWNERUSERID", "RN"
FROM (SELECT "Id" AS "POSTID", "Title" AS "TITLE", "CreationDate" AS "CREATIONDATE", "Score" AS "SCORE", "ViewCount" AS "VIEWCOUNT", "AnswerCount" AS "ANSWERCOUNT", "OwnerUserId" AS "OWNERUSERID", ROW_NUMBER() OVER (PARTITION BY "OwnerUserId" ORDER BY "CreationDate" DESC NULLS FIRST) AS "RN"
FROM "STACK"."Posts"
WHERE "CreationDate" >= (TIMESTAMP '2024-10-01 12:34:56' - INTERVAL '30' DAY)) AS "t0"
WHERE "SCORE" > 10