SELECT COALESCE("POSTID", "POSTID") AS "POSTID", "TITLE", "SCORE", "TOTALCLOSECOUNT", "OWNERDISPLAYNAME", "OWNERREPUTATION", "EFFECTIVEOWNER"
FROM (SELECT "Id" AS "POSTID", "Title" AS "TITLE", "Score" AS "SCORE", CASE WHEN "CLOSECOUNT" IS NOT NULL THEN CAST("CLOSECOUNT" AS BIGINT) ELSE 0 END AS "TOTALCLOSECOUNT", "DISPLAYNAME" AS "OWNERDISPLAYNAME", "REPUTATION" AS "OWNERREPUTATION", "DISPLAYNAME" AS "EFFECTIVEOWNER"
FROM "s1"
WHERE CASE WHEN "CLOSECOUNT" IS NOT NULL THEN CAST("CLOSECOUNT" AS BIGINT) ELSE 0 END = 0
ORDER BY "Score" DESC NULLS FIRST, "Title") AS "t8"