SELECT COALESCE("t5"."DISPLAYNAME", "t5"."DISPLAYNAME") AS "DISPLAYNAME", "t5"."REPUTATION", COUNT("t0"."POSTID") AS "FD_COL_2", SUM(CASE WHEN "t0"."CLOSEDATE" >= (TIMESTAMP '2024-10-01 12:34:56' - INTERVAL '1' MONTH) THEN 1 ELSE 0 END) AS "RECENTCLOSEDPOSTS", LISTAGG(DISTINCT "t0"."TITLE", ', ') AS "CLOSEDPOSTTITLES"
FROM (SELECT "Posts"."Id" AS "POSTID", "Posts"."Title" AS "TITLE", "t"."UserDisplayName" AS "USERDISPLAYNAME", "t"."CreationDate" AS "CLOSEDATE"
FROM (SELECT *
FROM "STACK"."PostHistory"
WHERE CAST("PostHistoryTypeId" AS INTEGER) = 10) AS "t"
INNER JOIN "STACK"."Posts" ON "t"."PostId" = "Posts"."Id") AS "t0"
RIGHT JOIN (SELECT "t4"."DISPLAYNAME", "t4"."REPUTATION", "t2"."POSTCOUNT", "t2"."TOTALVIEWS", "t2"."AVERAGESCORE"
FROM (SELECT "OwnerUserId", COUNT(*) AS "POSTCOUNT", SUM("ViewCount") AS "TOTALVIEWS", AVG("Score") AS "AVERAGESCORE"
FROM "STACK"."Posts"
WHERE "CreationDate" >= (TIMESTAMP '2024-10-01 12:34:56' - INTERVAL '1' YEAR)
GROUP BY "OwnerUserId") AS "t2"
INNER JOIN (SELECT *
FROM (SELECT "Id" AS "ID", "DisplayName" AS "DISPLAYNAME", "Reputation" AS "REPUTATION", ROW_NUMBER() OVER (ORDER BY "Reputation" DESC NULLS FIRST) AS "REPUTATIONRANK"
FROM "STACK"."Users") AS "t3"
WHERE "REPUTATION" > 1000) AS "t4" ON "t2"."OwnerUserId" = "t4"."ID") AS "t5" ON "t0"."USERDISPLAYNAME" = "t5"."DISPLAYNAME"
GROUP BY "t5"."DISPLAYNAME", "t5"."REPUTATION"