SELECT COALESCE("DISPLAYNAME", "DISPLAYNAME") AS "DISPLAYNAME", "REPUTATION", "FD_COL_2", "RECENTCLOSEDPOSTS", "CLOSEDPOSTTITLES"
FROM "s1"
ORDER BY "REPUTATION" DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY