SELECT COALESCE("t16"."DISPLAYNAME", "t16"."DISPLAYNAME") AS "DISPLAYNAME", "t16"."REPUTATION", "t16"."TITLE", "t16"."CREATIONDATE", "t16"."COMMENTCOUNT", "t16"."UPVOTECOUNT", "t16"."DOWNVOTECOUNT", "t16"."ACCEPTEDANSWERUPVOTES", "t16"."RELATEDPOSTCOUNT", "t16"."DUPLICATECOUNT"
FROM (SELECT "t14"."DISPLAYNAME", "t14"."REPUTATION", "t14"."TITLE", "t14"."CREATIONDATE", "t14"."COMMENTCOUNT", "t14"."UPVOTECOUNT", "t14"."DOWNVOTECOUNT", "t14"."TOTALUPVOTES" AS "ACCEPTEDANSWERUPVOTES", "t2"."RELATEDPOSTCOUNT", "t2"."DUPLICATECOUNT"
FROM (SELECT "PostLinks"."PostId" AS "POSTID", COUNT(DISTINCT "PostLinks"."RelatedPostId") AS "RELATEDPOSTCOUNT", SUM(CASE WHEN "LinkTypes"."Name" = 'Duplicate' THEN 1 ELSE 0 END) AS "DUPLICATECOUNT"
FROM "STACK"."LinkTypes"
INNER JOIN "STACK"."PostLinks" ON "LinkTypes"."Id" = "PostLinks"."LinkTypeId"
GROUP BY "PostLinks"."PostId") AS "t2"
RIGHT JOIN (SELECT "t8"."ID", "t8"."DISPLAYNAME", "t8"."REPUTATION", "t8"."RAN", "t13"."POSTID", "t13"."TITLE", "t13"."CREATIONDATE", "t13"."OWNERUSERID", "t13"."COMMENTCOUNT", "t13"."UPVOTECOUNT", "t13"."DOWNVOTECOUNT", "t6"."ANSWERID", "t6"."ACCEPTEDANSWERID", "t6"."TOTALUPVOTES"
FROM (SELECT ANY_VALUE("t3"."Id") AS "ANSWERID", "t3"."AcceptedAnswerId" AS "ACCEPTEDANSWERID", SUM(CASE WHEN CAST("Votes"."VoteTypeId" AS INTEGER) = 2 THEN 1 ELSE 0 END) AS "TOTALUPVOTES"
FROM "STACK"."Votes"
RIGHT JOIN (SELECT *
FROM "STACK"."Posts"
WHERE CAST("PostTypeId" AS INTEGER) = 2) AS "t3" ON "Votes"."PostId" = "t3"."Id"
GROUP BY "t3"."Id", "t3"."AcceptedAnswerId") AS "t6"
RIGHT JOIN ((SELECT *
FROM (SELECT "Id" AS "ID", "DisplayName" AS "DISPLAYNAME", "Reputation" AS "REPUTATION", ROW_NUMBER() OVER (ORDER BY "Reputation" DESC NULLS FIRST) AS "RAN"
FROM "STACK"."Users") AS "t7"
WHERE "REPUTATION" > 1000) AS "t8" INNER JOIN (SELECT ANY_VALUE("t9"."Id") AS "POSTID", "t9"."Title" AS "TITLE", "t9"."CreationDate" AS "CREATIONDATE", "t9"."OwnerUserId" AS "OWNERUSERID", COUNT("t9"."Id0") AS "COMMENTCOUNT", SUM(CASE WHEN CAST("Votes0"."VoteTypeId" AS INTEGER) = 2 THEN 1 ELSE 0 END) AS "UPVOTECOUNT", SUM(CASE WHEN CAST("Votes0"."VoteTypeId" AS INTEGER) = 3 THEN 1 ELSE 0 END) AS "DOWNVOTECOUNT"
FROM "STACK"."Votes" AS "Votes0"
RIGHT JOIN (SELECT "s1"."Id", "s1"."PostTypeId", "s1"."AcceptedAnswerId", "s1"."ParentId", "s1"."CreationDate", "s1"."Score", "s1"."ViewCount", "s1"."Body", "s1"."OwnerUserId", "s1"."OwnerDisplayName", "s1"."LastEditorUserId", "s1"."LastEditorDisplayName", "s1"."LastEditDate", "s1"."LastActivityDate", "s1"."Title", "s1"."Tags", "s1"."AnswerCount", "s1"."CommentCount", "s1"."FavoriteCount", "s1"."ClosedDate", "s1"."CommunityOwnedDate", "s1"."ContentLicense", "Comments"."Id" AS "Id0", "Comments"."PostId", "Comments"."Score" AS "Score0", "Comments"."Text", "Comments"."CreationDate" AS "CreationDate0", "Comments"."UserDisplayName", "Comments"."UserId", "Comments"."ContentLicense" AS "ContentLicense0"
FROM "STACK"."Comments"
RIGHT JOIN "s1" ON "Comments"."PostId" = "s1"."Id") AS "t9" ON "Votes0"."PostId" = "t9"."Id"
GROUP BY "t9"."Id", "t9"."Title", "t9"."CreationDate", "t9"."OwnerUserId"
HAVING SUM(CASE WHEN CAST("Votes0"."VoteTypeId" AS INTEGER) = 2 THEN 1 ELSE 0 END) - SUM(CASE WHEN CAST("Votes0"."VoteTypeId" AS INTEGER) = 3 THEN 1 ELSE 0 END) > 10) AS "t13" ON "t8"."ID" = "t13"."OWNERUSERID") ON "t6"."ACCEPTEDANSWERID" = "t13"."POSTID") AS "t14" ON "t2"."POSTID" = "t14"."POSTID"
ORDER BY "t14"."REPUTATION" DESC NULLS FIRST, "t14"."CREATIONDATE" DESC NULLS FIRST
OFFSET 0 ROWS
FETCH NEXT 10 ROWS ONLY) AS "t16"