SELECT COALESCE("TITLE", "TITLE") AS "TITLE", "CREATIONDATE", "OWNERDISPLAYNAME", "SCORE", "UPVOTES", "DOWNVOTES", "TOTALBADGES", "TOTALPOSTS"
FROM (SELECT "TITLE", "CREATIONDATE_" AS "CREATIONDATE", "DisplayName_" AS "OWNERDISPLAYNAME", "SCORE", "UPVOTES_" AS "UPVOTES", "DOWNVOTES_" AS "DOWNVOTES", "TOTALBADGES", "TOTALPOSTS"
FROM "s1"
ORDER BY "SCORE" DESC NULLS FIRST, "UPVOTES_" DESC NULLS FIRST, "DOWNVOTES_") AS "t9"