SELECT COALESCE("t10"."USERID", "t10"."USERID") AS "USERID", "t10"."DISPLAYNAME", "t10"."REPUTATION", "t10"."VIEWS", "t10"."UPVOTES", "t10"."DOWNVOTES", "t10"."POSTCOUNT", "t10"."QUESTIONCOUNT", "t10"."ANSWERCOUNT", "t10"."CLOSEDPOSTCOUNT", "t10"."GOLDBADGECOUNT", "t10"."EDITCOUNT"
FROM (SELECT "t8"."USERID", "t8"."DISPLAYNAME", "t8"."REPUTATION", "t8"."VIEWS", "t8"."UPVOTES", "t8"."DOWNVOTES", "t8"."POSTCOUNT", "t8"."QUESTIONCOUNT", "t8"."ANSWERCOUNT", "t8"."CLOSEDPOSTCOUNT", CASE WHEN "t8"."BADGECOUNT" IS NOT NULL THEN CAST("t8"."BADGECOUNT" AS BIGINT) ELSE 0 END AS "GOLDBADGECOUNT", CASE WHEN "t3"."EDITCOUNT" IS NOT NULL THEN CAST("t3"."EDITCOUNT" AS BIGINT) ELSE 0 END AS "EDITCOUNT"
FROM (SELECT "UserId", COUNT(*) AS "EDITCOUNT"
FROM "STACK"."PostHistory"
WHERE CAST("PostHistoryTypeId" AS INTEGER) IN (4, 5, 6)
GROUP BY "UserId") AS "t3"
RIGHT JOIN (SELECT "t7"."USERID", "t7"."DISPLAYNAME", "t7"."REPUTATION", "t7"."VIEWS", "t7"."UPVOTES", "t7"."DOWNVOTES", "t7"."POSTCOUNT", "t7"."QUESTIONCOUNT", "t7"."ANSWERCOUNT", "t7"."CLOSEDPOSTCOUNT", "t5"."UserId" AS "USERID0", "t5"."BADGECOUNT"
FROM (SELECT "UserId", COUNT(*) AS "BADGECOUNT"
FROM "STACK"."Badges"
WHERE CAST("Class" AS INTEGER) = 1
GROUP BY "UserId") AS "t5"
RIGHT JOIN (SELECT ANY_VALUE("Id") AS "USERID", "DISPLAYNAME", "REPUTATION", "VIEWS", "UPVOTES", "DOWNVOTES", COUNT(DISTINCT "Id0") AS "POSTCOUNT", SUM("FD_COL_7") AS "QUESTIONCOUNT", SUM("FD_COL_8") AS "ANSWERCOUNT", SUM("FD_COL_9") AS "CLOSEDPOSTCOUNT"
FROM "s1"
GROUP BY "Id", "DISPLAYNAME", "REPUTATION", "VIEWS", "UPVOTES", "DOWNVOTES") AS "t7" ON "t5"."UserId" = "t7"."USERID") AS "t8" ON "t3"."UserId" = "t8"."USERID"
ORDER BY "t8"."REPUTATION" DESC NULLS FIRST, "t8"."POSTCOUNT" DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY) AS "t10"