SELECT COALESCE("USER", "USER") AS "USER", "POST_TITLE", "POST_CREATION_DATE", "POST_SCORE", "AVERAGE_COMMENT_SCORE", "TOTAL_UPVOTES", "TOTAL_DOWNVOTES"
FROM (SELECT "DisplayName" AS "USER", "Title" AS "POST_TITLE", "CreationDate" AS "POST_CREATION_DATE", "Score" AS "POST_SCORE", CASE WHEN "AVG_COMMENT_SCORE" IS NOT NULL THEN CAST("AVG_COMMENT_SCORE" AS INTEGER) ELSE 0 END AS "AVERAGE_COMMENT_SCORE", CASE WHEN "UPVOTES" IS NOT NULL THEN CAST("UPVOTES" AS INTEGER) ELSE 0 END AS "TOTAL_UPVOTES", CASE WHEN "DOWNVOTES" IS NOT NULL THEN CAST("DOWNVOTES" AS INTEGER) ELSE 0 END AS "TOTAL_DOWNVOTES"
FROM "s1"
ORDER BY "CreationDate" DESC NULLS FIRST
FETCH NEXT 100 ROWS ONLY) AS "t6"