SELECT COALESCE("t8"."USERID", "t8"."USERID") AS "USERID", "t8"."DISPLAYNAME", "t8"."BADGECOUNT", "t8"."TOTALPOSTS", "t8"."QUESTIONS", "t8"."ANSWERS", "t8"."TOTALSCORE", "t8"."AVGVIEWCOUNT"
FROM (SELECT "t3"."Id" AS "USERID", "t3"."DisplayName" AS "DISPLAYNAME", "t6"."BADGECOUNT", "t2"."TOTALPOSTS", "t2"."QUESTIONS", "t2"."ANSWERS", "t2"."TOTALSCORE", "t2"."AVGVIEWCOUNT"
FROM (SELECT "OWNERUSERID", COUNT(*) AS "TOTALPOSTS", SUM("FD_COL_1") AS "QUESTIONS", SUM("FD_COL_2") AS "ANSWERS", SUM("Score") AS "TOTALSCORE", AVG("ViewCount") AS "AVGVIEWCOUNT"
FROM "s1"
GROUP BY "OWNERUSERID") AS "t2"
INNER JOIN (SELECT *
FROM "STACK"."Users"
WHERE "LastAccessDate" > CAST((CURRENT_DATE - INTERVAL '6' MONTH) AS TIMESTAMP(0))) AS "t3" ON "t2"."OWNERUSERID" = "t3"."Id"
INNER JOIN (SELECT ANY_VALUE("Users0"."Id") AS "USERID", "Users0"."DisplayName" AS "DISPLAYNAME", COUNT("Badges"."Id") AS "BADGECOUNT", SUM(CASE WHEN CAST("Badges"."Class" AS INTEGER) = 1 THEN 1 ELSE 0 END) AS "GOLDBADGES", SUM(CASE WHEN CAST("Badges"."Class" AS INTEGER) = 2 THEN 1 ELSE 0 END) AS "SILVERBADGES", SUM(CASE WHEN CAST("Badges"."Class" AS INTEGER) = 3 THEN 1 ELSE 0 END) AS "BRONZEBADGES"
FROM "STACK"."Badges"
RIGHT JOIN "STACK"."Users" AS "Users0" ON "Badges"."UserId" = "Users0"."Id"
GROUP BY "Users0"."Id", "Users0"."DisplayName") AS "t6" ON "t3"."Id" = "t6"."USERID"
ORDER BY "t2"."TOTALSCORE" DESC NULLS FIRST, "t6"."BADGECOUNT" DESC NULLS FIRST
FETCH NEXT 100 ROWS ONLY) AS "t8"