SELECT COALESCE("OwnerUserId", "OwnerUserId") AS "OWNERUSERID", CASE WHEN CAST("PostTypeId" AS INTEGER) = 1 THEN 1 ELSE 0 END AS "FD_COL_1", CASE WHEN CAST("PostTypeId" AS INTEGER) = 2 THEN 1 ELSE 0 END AS "FD_COL_2", "Score", "ViewCount"
FROM "STACK"."Posts"
WHERE "CreationDate" > CAST((CURRENT_DATE - INTERVAL '1' YEAR) AS TIMESTAMP(0))