SELECT COALESCE("t8"."USERID", "t8"."USERID") AS "USERID", "t8"."DISPLAYNAME", "t8"."REPUTATION", "t8"."CREATIONDATE", "t8"."TOTALPOSTS", "t8"."TOTALQUESTIONS", "t8"."TOTALANSWERS", "t8"."TOTALUPVOTES", "t8"."TOTALDOWNVOTES", "t8"."TOTALBADGES", "t8"."GOLDBADGES", "t8"."SILVERBADGES", "t8"."BRONZEBADGES"
FROM (SELECT "t5"."USERID", "t5"."DISPLAYNAME", "t5"."REPUTATION", "t5"."CREATIONDATE", "t5"."TOTALPOSTS", "t5"."TOTALQUESTIONS", "t5"."TOTALANSWERS", "t5"."TOTALUPVOTES", "t5"."TOTALDOWNVOTES", CASE WHEN "t3"."TOTALBADGES" IS NOT NULL THEN CAST("t3"."TOTALBADGES" AS BIGINT) ELSE 0 END AS "TOTALBADGES", CASE WHEN "t3"."GOLDBADGES" IS NOT NULL THEN CAST("t3"."GOLDBADGES" AS INTEGER) ELSE 0 END AS "GOLDBADGES", CASE WHEN "t3"."SILVERBADGES" IS NOT NULL THEN CAST("t3"."SILVERBADGES" AS INTEGER) ELSE 0 END AS "SILVERBADGES", CASE WHEN "t3"."BRONZEBADGES" IS NOT NULL THEN CAST("t3"."BRONZEBADGES" AS INTEGER) ELSE 0 END AS "BRONZEBADGES"
FROM (SELECT "UserId" AS "USERID", COUNT(*) AS "TOTALBADGES", SUM(CASE WHEN CAST("Class" AS INTEGER) = 1 THEN 1 ELSE 0 END) AS "GOLDBADGES", SUM(CASE WHEN CAST("Class" AS INTEGER) = 2 THEN 1 ELSE 0 END) AS "SILVERBADGES", SUM(CASE WHEN CAST("Class" AS INTEGER) = 3 THEN 1 ELSE 0 END) AS "BRONZEBADGES"
FROM "STACK"."Badges"
GROUP BY "UserId") AS "t3"
RIGHT JOIN (SELECT ANY_VALUE("Id") AS "USERID", "DISPLAYNAME", "REPUTATION", "CREATIONDATE", COUNT(DISTINCT "Id0") AS "TOTALPOSTS", COUNT(DISTINCT "FD_COL_5") AS "TOTALQUESTIONS", COUNT(DISTINCT "FD_COL_6") AS "TOTALANSWERS", SUM("FD_COL_7") AS "TOTALUPVOTES", SUM("FD_COL_8") AS "TOTALDOWNVOTES"
FROM "s1"
GROUP BY "Id", "DISPLAYNAME", "REPUTATION", "CREATIONDATE") AS "t5" ON "t3"."USERID" = "t5"."USERID"
WHERE "t5"."REPUTATION" > 1000
ORDER BY "t5"."TOTALPOSTS" DESC NULLS FIRST, "t5"."TOTALUPVOTES" DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY) AS "t8"