SELECT COALESCE("OwnerUserId", "OwnerUserId") AS "OWNERUSERID", CASE WHEN "Score" > 0 THEN 1 ELSE 0 END AS "FD_COL_1", CASE WHEN CAST("PostTypeId" AS INTEGER) = 1 THEN 1 ELSE 0 END AS "FD_COL_2", CASE WHEN CAST("PostTypeId" AS INTEGER) = 2 THEN 1 ELSE 0 END AS "FD_COL_3"
FROM "STACK"."Posts"
WHERE "CreationDate" >= CAST((DATE '2024-10-01' - INTERVAL '1' YEAR) AS TIMESTAMP(0))