SELECT COALESCE("t0"."OWNERUSERID", "t0"."OWNERUSERID") AS "OWNERUSERID", "t0"."TOTALPOSTS", "t0"."QUESTIONS", "t0"."ANSWERS", "t0"."AVGPOSTSCORE", "t0"."TOTALVIEWS", "t4"."USERID", "t4"."DISPLAYNAME", "t4"."REPUTATION", "t4"."BADGECOUNT", "t4"."UPVOTESRECEIVED", "t4"."DOWNVOTESRECEIVED"
FROM (SELECT "OwnerUserId" AS "OWNERUSERID", COUNT(*) AS "TOTALPOSTS", COUNT(DISTINCT CASE WHEN CAST("PostTypeId" AS INTEGER) = 1 THEN "Id" ELSE NULL END) AS "QUESTIONS", COUNT(DISTINCT CASE WHEN CAST("PostTypeId" AS INTEGER) = 2 THEN "Id" ELSE NULL END) AS "ANSWERS", AVG("Score") AS "AVGPOSTSCORE", SUM("ViewCount") AS "TOTALVIEWS"
FROM "STACK"."Posts"
GROUP BY "OwnerUserId") AS "t0"
INNER JOIN (SELECT ANY_VALUE("t1"."Id") AS "USERID", "t1"."DisplayName" AS "DISPLAYNAME", "t1"."Reputation" AS "REPUTATION", COUNT("t1"."Id0") AS "BADGECOUNT", SUM(CASE WHEN CAST("Votes"."VoteTypeId" AS INTEGER) = 2 THEN 1 ELSE 0 END) AS "UPVOTESRECEIVED", SUM(CASE WHEN CAST("Votes"."VoteTypeId" AS INTEGER) = 3 THEN 1 ELSE 0 END) AS "DOWNVOTESRECEIVED"
FROM "STACK"."Votes"
RIGHT JOIN (SELECT "Users"."Id", "Users"."Reputation", "Users"."CreationDate", "Users"."DisplayName", "Users"."LastAccessDate", "Users"."WebsiteUrl", "Users"."Location", "Users"."AboutMe", "Users"."Views", "Users"."UpVotes", "Users"."DownVotes", "Users"."ProfileImageUrl", "Users"."AccountId", "Badges"."Id" AS "Id0", "Badges"."UserId", "Badges"."Name", "Badges"."Date", "Badges"."Class", "Badges"."TagBased"
FROM "STACK"."Badges"
RIGHT JOIN "STACK"."Users" ON "Badges"."UserId" = "Users"."Id") AS "t1" ON "Votes"."UserId" = "t1"."Id"
GROUP BY "t1"."Id", "t1"."DisplayName", "t1"."Reputation") AS "t4" ON "t0"."OWNERUSERID" = "t4"."USERID"