SELECT COALESCE("t7"."DISPLAYNAME", "t7"."DISPLAYNAME") AS "DISPLAYNAME", "t7"."REPUTATION", "t7"."POSTCOUNT", "t7"."POPULARPOSTS", "t7"."HIGHSCOREPOSTS", "t7"."BADGECOUNT", "t7"."USERTIER"
FROM (SELECT "t4"."DISPLAYNAME", "t4"."REPUTATION", "t4"."POSTCOUNT", "t4"."POPULARPOSTS", "t4"."HIGHSCOREPOSTS", CASE WHEN "t2"."BADGECOUNT" IS NOT NULL THEN CAST("t2"."BADGECOUNT" AS BIGINT) ELSE 0 END AS "BADGECOUNT", CASE WHEN "t4"."REPUTATION" > 1000 THEN 'Elite ' WHEN "t4"."REPUTATION" > 500 THEN 'Pro   ' ELSE 'Novice' END AS "USERTIER"
FROM (SELECT "UserId", COUNT(*) AS "BADGECOUNT"
FROM "STACK"."Badges"
GROUP BY "UserId") AS "t2"
RIGHT JOIN (SELECT ANY_VALUE("Id") AS "USERID", "DISPLAYNAME", "REPUTATION", COUNT(DISTINCT "Id0") AS "POSTCOUNT", SUM("FD_COL_4") AS "POPULARPOSTS", SUM("FD_COL_5") AS "HIGHSCOREPOSTS"
FROM "s1"
GROUP BY "Id", "DISPLAYNAME", "REPUTATION") AS "t4" ON "t2"."UserId" = "t4"."USERID"
WHERE "t4"."POSTCOUNT" > 10
ORDER BY "t4"."REPUTATION" DESC NULLS FIRST, "t4"."POSTCOUNT" DESC NULLS FIRST
FETCH NEXT 20 ROWS ONLY) AS "t7"