SELECT COALESCE("t0"."OWNERUSERID", "t0"."OWNERUSERID") AS "OWNERUSERID", "t0"."TOTALQUESTIONS", "t0"."TOTALANSWERS", "t0"."AVGSCORE", "t0"."TOTALVIEWS", "t3"."USERID", "t3"."DISPLAYNAME", "t3"."REPUTATION", "t3"."TOTALUPVOTES", "t3"."TOTALDOWNVOTES", "t3"."TOTALDELETIONS", "t3"."TOTALUNDELETIONS"
FROM (SELECT "OwnerUserId" AS "OWNERUSERID", COUNT(CASE WHEN CAST("PostTypeId" AS INTEGER) = 1 THEN 1 ELSE NULL END) AS "TOTALQUESTIONS", COUNT(CASE WHEN CAST("PostTypeId" AS INTEGER) = 2 THEN 1 ELSE NULL END) AS "TOTALANSWERS", AVG("Score") AS "AVGSCORE", SUM("ViewCount") AS "TOTALVIEWS"
FROM "STACK"."Posts"
GROUP BY "OwnerUserId") AS "t0"
RIGHT JOIN (SELECT ANY_VALUE("Users"."Id") AS "USERID", "Users"."DisplayName" AS "DISPLAYNAME", "Users"."Reputation" AS "REPUTATION", SUM(CASE WHEN CAST("Votes"."VoteTypeId" AS INTEGER) = 2 THEN 1 ELSE 0 END) AS "TOTALUPVOTES", SUM(CASE WHEN CAST("Votes"."VoteTypeId" AS INTEGER) = 3 THEN 1 ELSE 0 END) AS "TOTALDOWNVOTES", SUM(CASE WHEN CAST("Votes"."VoteTypeId" AS INTEGER) = 10 THEN 1 ELSE 0 END) AS "TOTALDELETIONS", SUM(CASE WHEN CAST("Votes"."VoteTypeId" AS INTEGER) = 11 THEN 1 ELSE 0 END) AS "TOTALUNDELETIONS"
FROM "STACK"."Votes"
RIGHT JOIN "STACK"."Users" ON "Votes"."UserId" = "Users"."Id"
GROUP BY "Users"."Id", "Users"."DisplayName", "Users"."Reputation") AS "t3" ON "t0"."OWNERUSERID" = "t3"."USERID"
WHERE "t3"."REPUTATION" > 100