SELECT COALESCE("t16"."USERID", "t16"."USERID") AS "USERID", "t16"."DisplayName" AS "DISPLAYNAME", "t16"."Reputation" AS "REPUTATION", "t16"."ENGAGEDPOSTCOUNT", "t16"."Reputation" AS "Reputation_"
FROM (SELECT "Users0"."Id", "Users0"."DisplayName", "Users0"."Reputation", ANY_VALUE("Users0"."Id") AS "USERID", COUNT("t12"."POSTID") AS "ENGAGEDPOSTCOUNT"
FROM (SELECT "t9"."POSTID", "t9"."TITLE", "t9"."COMMENTCOUNT", "t9"."EDITCOUNT", "t9"."DISPLAYNAME", "t9"."REPUTATION", "t11"."$f1" AS "$f0"
FROM (SELECT "t8"."POSTID", "t8"."TITLE", "t8"."COMMENTCOUNT", "t8"."EDITCOUNT", "Users"."DisplayName" AS "DISPLAYNAME", "Users"."Reputation" AS "REPUTATION"
FROM "STACK"."Users"
INNER JOIN (SELECT "t5"."POSTID", "t5"."TITLE", "t5"."COMMENTCOUNT", "t5"."EDITCOUNT", "t5"."LASTEDITDATE", "t7"."$f1" AS "$f0"
FROM (SELECT *
FROM (SELECT ANY_VALUE("t1"."Id") AS "POSTID", "t1"."Title" AS "TITLE", COUNT(CASE WHEN "t1"."Id0" IS NOT NULL THEN 1 ELSE NULL END) AS "COMMENTCOUNT", COUNT(DISTINCT "PostHistory"."UserId") AS "EDITCOUNT", MAX("PostHistory"."CreationDate") AS "LASTEDITDATE"
FROM "STACK"."PostHistory"
RIGHT JOIN (SELECT "s1"."Id", "s1"."PostTypeId", "s1"."AcceptedAnswerId", "s1"."ParentId", "s1"."CreationDate", "s1"."Score", "s1"."ViewCount", "s1"."Body", "s1"."OwnerUserId", "s1"."OwnerDisplayName", "s1"."LastEditorUserId", "s1"."LastEditorDisplayName", "s1"."LastEditDate", "s1"."LastActivityDate", "s1"."Title", "s1"."Tags", "s1"."AnswerCount", "s1"."CommentCount", "s1"."FavoriteCount", "s1"."ClosedDate", "s1"."CommunityOwnedDate", "s1"."ContentLicense", "Comments"."Id" AS "Id0", "Comments"."PostId", "Comments"."Score" AS "Score0", "Comments"."Text", "Comments"."CreationDate" AS "CreationDate0", "Comments"."UserDisplayName", "Comments"."UserId", "Comments"."ContentLicense" AS "ContentLicense0"
FROM "STACK"."Comments"
RIGHT JOIN "s1" ON "Comments"."PostId" = "s1"."Id") AS "t1" ON "PostHistory"."PostId" = "t1"."Id"
GROUP BY "t1"."Id", "t1"."Title") AS "t4"
WHERE "t4"."COMMENTCOUNT" > 5 AND "t4"."EDITCOUNT" > 2) AS "t5"
LEFT JOIN (SELECT "Id", SINGLE_VALUE("OwnerUserId") AS "$f1"
FROM "STACK"."Posts"
GROUP BY "Id") AS "t7" ON "t5"."POSTID" = "t7"."Id") AS "t8" ON "Users"."Id" = "t8"."$f0") AS "t9"
LEFT JOIN (SELECT "Id", SINGLE_VALUE("OwnerUserId") AS "$f1"
FROM "STACK"."Posts"
GROUP BY "Id") AS "t11" ON "t9"."POSTID" = "t11"."Id") AS "t12"
RIGHT JOIN "STACK"."Users" AS "Users0" ON "t12"."$f0" = "Users0"."Id"
GROUP BY "Users0"."Id", "Users0"."Reputation", "Users0"."DisplayName"
ORDER BY 5 DESC NULLS FIRST, "Users0"."Reputation" DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY) AS "t16"