SELECT COALESCE("t0"."USERID", "t0"."USERID") AS "USERID", "t0"."BADGECOUNT", "t0"."GOLDBADGES", "t0"."SILVERBADGES", "t0"."BRONZEBADGES", "t3"."USERID" AS "USERID0", "t3"."DISPLAYNAME", "t3"."REPUTATION", "t3"."POSTCOUNT", "t3"."QUESTIONCOUNT", "t3"."ANSWERCOUNT", "t3"."ACCEPTEDANSWERS", "t3"."POPULARPOSTS"
FROM (SELECT "UserId" AS "USERID", COUNT(*) AS "BADGECOUNT", SUM(CASE WHEN CAST("Class" AS INTEGER) = 1 THEN 1 ELSE 0 END) AS "GOLDBADGES", SUM(CASE WHEN CAST("Class" AS INTEGER) = 2 THEN 1 ELSE 0 END) AS "SILVERBADGES", SUM(CASE WHEN CAST("Class" AS INTEGER) = 3 THEN 1 ELSE 0 END) AS "BRONZEBADGES"
FROM "STACK"."Badges"
GROUP BY "UserId") AS "t0"
RIGHT JOIN (SELECT ANY_VALUE("Users"."Id") AS "USERID", "Users"."DisplayName" AS "DISPLAYNAME", "Users"."Reputation" AS "REPUTATION", COUNT(DISTINCT "Posts"."Id") AS "POSTCOUNT", SUM(CASE WHEN CAST("Posts"."PostTypeId" AS INTEGER) = 1 THEN 1 ELSE 0 END) AS "QUESTIONCOUNT", SUM(CASE WHEN CAST("Posts"."PostTypeId" AS INTEGER) = 2 THEN 1 ELSE 0 END) AS "ANSWERCOUNT", SUM(CASE WHEN CAST("Posts"."PostTypeId" AS INTEGER) = 1 AND "Posts"."AcceptedAnswerId" IS NOT NULL THEN 1 ELSE 0 END) AS "ACCEPTEDANSWERS", SUM(CASE WHEN "Posts"."ViewCount" > 100 THEN 1 ELSE 0 END) AS "POPULARPOSTS"
FROM "STACK"."Posts"
RIGHT JOIN "STACK"."Users" ON "Posts"."OwnerUserId" = "Users"."Id"
GROUP BY "Users"."Id", "Users"."DisplayName", "Users"."Reputation") AS "t3" ON "t0"."USERID" = "t3"."USERID"
WHERE "t3"."REPUTATION" > 1000 AND "t3"."POSTCOUNT" > 10