SELECT COALESCE("USERID", "USERID") AS "USERID", "DISPLAYNAME", "REPUTATION", "UPVOTES", "DOWNVOTES", "USERTOTALPOSTS", "AVERAGESCORE", "TIMESCLOSED", "TIMESREOPENED", "HOTQUESTIONCHANGES"
FROM (SELECT "Id" AS "USERID", "DisplayName" AS "DISPLAYNAME", "Reputation" AS "REPUTATION", "UPVOTES_" AS "UPVOTES", "DOWNVOTES_" AS "DOWNVOTES", "TOTALPOSTS" AS "USERTOTALPOSTS", "AVERAGESCORE", "TIMESCLOSED", "TIMESREOPENED", "HOTQUESTIONCHANGES"
FROM "s1"
ORDER BY "UPVOTES_" DESC NULLS FIRST, "AVERAGESCORE" DESC NULLS FIRST
FETCH NEXT 50 ROWS ONLY) AS "t8"