SELECT COALESCE("USERID", "USERID") AS "USERID", "DISPLAYNAME", "TOTALPOSTS", "TOTALSCORE", "UPVOTECOUNT", "DOWNVOTECOUNT", "AVGCOMMENTSPERPOST", "SCORECATEGORY", "GOLDBADGES", "SILVERBADGES", "BRONZEBADGES"
FROM (SELECT "USERID", "DISPLAYNAME", "TOTALPOSTS", "TOTALSCORE", "UPVOTECOUNT", "DOWNVOTECOUNT", "AVGCOMMENTSPERPOST", CASE WHEN "TOTALSCORE" > 100 THEN 'High Scorer  ' WHEN "TOTALSCORE" >= 50 AND "TOTALSCORE" <= 100 THEN 'Medium Scorer' ELSE 'Low Scorer   ' END AS "SCORECATEGORY", "FD_COL_7" AS "GOLDBADGES", "FD_COL_8" AS "SILVERBADGES", "FD_COL_9" AS "BRONZEBADGES"
FROM "s1"
ORDER BY "TOTALSCORE" DESC NULLS FIRST, "DISPLAYNAME"
OFFSET 0 ROWS
FETCH NEXT 100 ROWS ONLY) AS "t115"