SELECT COALESCE("USERID", "USERID") AS "USERID", "DISPLAYNAME", "TOTALPOSTS", "TOTALQUESTIONS", "TOTALANSWERS", "AVERAGEREPUTATION", "TOTALUPVOTES", "TOTALDOWNVOTES", "POSTID", "TITLE", "CREATIONDATE", "COMMENTCOUNT", "RELATEDPOSTLINKS", "CLOSEDDATE", "REOPENEDDATE", "POSTSTATUS"
FROM (SELECT "USERID", "DISPLAYNAME", "TOTALPOSTS", "TOTALQUESTIONS", "TOTALANSWERS", "AVERAGEREPUTATION", "TOTALUPVOTES", "TOTALDOWNVOTES", "POSTID", "TITLE", "CREATIONDATE", "COMMENTCOUNT", "RELATEDPOSTLINKS", "CLOSEDDATE", "REOPENEDDATE", CASE WHEN "CLOSEDDATE" IS NOT NULL THEN 'Closed  ' WHEN "REOPENEDDATE" IS NOT NULL THEN 'Reopened' ELSE 'Active  ' END AS "POSTSTATUS"
FROM "s1"
ORDER BY "TOTALPOSTS" DESC NULLS FIRST, "AVERAGEREPUTATION" DESC NULLS FIRST
FETCH NEXT 50 ROWS ONLY) AS "t10"