SELECT COALESCE("DISPLAYNAME", "DISPLAYNAME") AS "DISPLAYNAME", "TITLE", "VIEWCOUNT", "SCORE", "UPVOTECOUNT", "DOWNVOTECOUNT", "TOTALCOMMENTSCORE"
FROM (SELECT "DISPLAYNAME", "TITLE_" AS "TITLE", "VIEWCOUNT_" AS "VIEWCOUNT", "SCORE_" AS "SCORE", "UPVOTECOUNT", "DOWNVOTECOUNT", "TOTALCOMMENTSCORE"
FROM "s1"
ORDER BY "SCORE_" DESC NULLS FIRST, "VIEWCOUNT_" DESC NULLS FIRST) AS "t11"