SELECT COALESCE("t9"."USERID", "t9"."USERID") AS "USERID", "t9"."DISPLAYNAME", "t9"."TOTALPOSTS", "t9"."TOTALQUESTIONS", "t9"."TOTALANSWERS", "t9"."TOTALUPVOTES", "t9"."TOTALDOWNVOTES", "t9"."TOTALBADGES", "t9"."GOLDBADGES", "t9"."SILVERBADGES", "t9"."BRONZEBADGES", "t9"."TOTALPOSTCLOSURES", "t9"."FIRSTCLOSEDATE", "t9"."LASTCLOSEDATE"
FROM (SELECT "s1"."USERID", "s1"."DISPLAYNAME", "s1"."TOTALPOSTS", "s1"."TOTALQUESTIONS", "s1"."TOTALANSWERS", "s1"."TOTALUPVOTES", "s1"."TOTALDOWNVOTES", "s1"."TOTALBADGES", "s1"."GOLDBADGES", "s1"."SILVERBADGES", "s1"."BRONZEBADGES", "t7"."TOTALPOSTCLOSURES", "t7"."FIRSTCLOSEDATE", "t7"."LASTCLOSEDATE"
FROM "s1"
LEFT JOIN (SELECT "UserId", COUNT(*) AS "TOTALPOSTCLOSURES", MIN("CreationDate") AS "FIRSTCLOSEDATE", MAX("CreationDate") AS "LASTCLOSEDATE"
FROM "STACK"."PostHistory"
WHERE CAST("PostHistoryTypeId" AS INTEGER) = 10
GROUP BY "UserId") AS "t7" ON "s1"."USERID" = "t7"."UserId"
ORDER BY "s1"."TOTALPOSTS" DESC NULLS FIRST, "s1"."TOTALUPVOTES" DESC NULLS FIRST
FETCH NEXT 100 ROWS ONLY) AS "t9"