SELECT COALESCE("t10"."DISPLAYNAME", "t10"."DISPLAYNAME") AS "DISPLAYNAME", "t10"."POSTCOUNT", "t10"."TOTALVOTES", "t10"."QUESTIONSANSWERED", "t10"."ANSWERSGIVEN", "t10"."POSTEDITS", "t10"."POSTTYPE", "t10"."TOTALPOSTSOFTYPE", "t10"."AVERAGESCORE", "t10"."TOTALVIEWS"
FROM (SELECT "t8"."DISPLAYNAME", "t8"."POSTCOUNT", "t8"."TOTALVOTES", "t8"."QUESTIONSANSWERED", "t8"."ANSWERSGIVEN", "t8"."POSTEDITS", "t6"."POSTTYPE", "t6"."POSTCOUNT" AS "TOTALPOSTSOFTYPE", "t6"."AVERAGESCORE", "t6"."TOTALVIEWS"
FROM (SELECT ANY_VALUE("PostTypes"."Name") AS "POSTTYPE", COUNT(*) AS "POSTCOUNT", AVG("t4"."Score") AS "AVERAGESCORE", SUM("t4"."ViewCount") AS "TOTALVIEWS"
FROM "STACK"."PostTypes"
INNER JOIN (SELECT *
FROM "STACK"."Posts"
WHERE "CreationDate" >= (TIMESTAMP '2024-10-01 12:34:56' - INTERVAL '1' YEAR)) AS "t4" ON "PostTypes"."Id" = "t4"."PostTypeId"
GROUP BY "PostTypes"."Name") AS "t6",
(SELECT ANY_VALUE("Id") AS "USERID", "DISPLAYNAME", COUNT(DISTINCT "Id0") AS "POSTCOUNT", SUM("VOTE_COUNT") AS "TOTALVOTES", SUM("FD_COL_4") AS "QUESTIONSANSWERED", SUM("FD_COL_5") AS "ANSWERSGIVEN", COUNT(DISTINCT "Id1") AS "POSTEDITS"
FROM "s1"
GROUP BY "Id", "DISPLAYNAME") AS "t8"
ORDER BY "t8"."TOTALVOTES" DESC NULLS FIRST, "t8"."POSTCOUNT" DESC NULLS FIRST, "t6"."TOTALVIEWS" DESC NULLS FIRST
FETCH NEXT 100 ROWS ONLY) AS "t10"