SELECT COALESCE("t"."Id", "t"."Id") AS "Id", "t"."Reputation", "t"."CreationDate", "t"."DisplayName", "t"."LastAccessDate", "t"."WebsiteUrl", "t"."Location", "t"."AboutMe", "t"."Views", "t"."UpVotes", "t"."DownVotes", "t"."ProfileImageUrl", "t"."AccountId", "t1"."USERID", "t1"."BADGECOUNT", "t3"."OWNERUSERID", "t3"."POSTCOUNT", "t3"."QUESTIONCOUNT", "t3"."ANSWERCOUNT", "t3"."TOTALVIEWS", "t5"."USERID" AS "USERID0", "t5"."EDITCOUNT", "t5"."TITLEANDBODYEDITS"
FROM (SELECT *
FROM "STACK"."Users"
WHERE "Reputation" > 1000) AS "t"
LEFT JOIN (SELECT ANY_VALUE("Users0"."Id") AS "USERID", COUNT("Badges"."Id") AS "BADGECOUNT"
FROM "STACK"."Badges"
RIGHT JOIN "STACK"."Users" AS "Users0" ON "Badges"."UserId" = "Users0"."Id"
GROUP BY "Users0"."Id") AS "t1" ON "t"."Id" = "t1"."USERID"
LEFT JOIN (SELECT "OwnerUserId" AS "OWNERUSERID", COUNT(*) AS "POSTCOUNT", SUM(CASE WHEN CAST("PostTypeId" AS INTEGER) = 1 THEN 1 ELSE 0 END) AS "QUESTIONCOUNT", SUM(CASE WHEN CAST("PostTypeId" AS INTEGER) = 2 THEN 1 ELSE 0 END) AS "ANSWERCOUNT", SUM("ViewCount") AS "TOTALVIEWS"
FROM "STACK"."Posts"
GROUP BY "OwnerUserId") AS "t3" ON "t"."Id" = "t3"."OWNERUSERID"
LEFT JOIN (SELECT "UserId" AS "USERID", COUNT(*) AS "EDITCOUNT", SUM(CASE WHEN CAST("PostHistoryTypeId" AS INTEGER) IN (4, 5, 6) THEN 1 ELSE 0 END) AS "TITLEANDBODYEDITS"
FROM "STACK"."PostHistory"
GROUP BY "UserId") AS "t5" ON "t"."Id" = "t5"."USERID"