SELECT COALESCE("USERID", "USERID") AS "USERID", "DISPLAYNAME", "POSTCOUNT", "QUESTIONCOUNT", "ANSWERCOUNT", "TOTALBOUNTY", "TOTALUPVOTES", "TOTALDOWNVOTES", "BADGECOUNT", "HIGHESTBADGECLASS"
FROM (SELECT "USERID", "DISPLAYNAME", "POSTCOUNT", "QUESTIONCOUNT", "ANSWERCOUNT", "TOTALBOUNTY", "TOTALUPVOTES", "TOTALDOWNVOTES", CASE WHEN "BADGECOUNT" IS NOT NULL THEN CAST("BADGECOUNT" AS BIGINT) ELSE 0 END AS "BADGECOUNT", CASE WHEN "HIGHESTBADGECLASS" IS NOT NULL THEN CAST("HIGHESTBADGECLASS" AS INTEGER) ELSE 0 END AS "HIGHESTBADGECLASS"
FROM "s1"
ORDER BY "TOTALUPVOTES" DESC NULLS FIRST, "POSTCOUNT" DESC NULLS FIRST
FETCH NEXT 50 ROWS ONLY) AS "t7"