SELECT COALESCE("DISPLAYNAME", "DISPLAYNAME") AS "DISPLAYNAME", "UPVOTES", "DOWNVOTES", "TOTALPOSTS", "TOTALSCORE", "TOTALVIEWS"
FROM "s1"
ORDER BY "TOTALSCORE" DESC NULLS FIRST, "TOTALVIEWS" DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY