SELECT COALESCE("DISPLAYNAME", "DISPLAYNAME") AS "DISPLAYNAME", "REPUTATION", "TOTALBADGES", "TOTALPOSTS", "TOTALQUESTIONS", "TOTALANSWERS", "TOTALVIEWS"
FROM (SELECT "DISPLAYNAME", "REPUTATION", "TOTALBADGES", "TOTALPOSTS", "TOTALQUESTIONS", "TOTALANSWERS", "TOTALVIEWS"
FROM "s1"
ORDER BY "REPUTATION" DESC NULLS FIRST) AS "t12"