SELECT COALESCE("USERID", "USERID") AS "USERID", "DISPLAYNAME", "POSTCOUNT", "QUESTIONS", "ANSWERS", "CLOSEDPOSTS", "AVGREPUTATION", "NETVOTES", "BADGENAME", "CLASS"
FROM (SELECT "USERID_" AS "USERID", "DISPLAYNAME", "POSTCOUNT", "QUESTIONS", "ANSWERS", "CLOSEDPOSTS", "AVGREPUTATION", "NETVOTES", "Name" AS "BADGENAME", "Class" AS "CLASS"
FROM "s1"
ORDER BY "NETVOTES" DESC NULLS FIRST, "AVGREPUTATION" DESC NULLS FIRST) AS "t8"