SELECT COALESCE("t0"."OwnerUserId", "t0"."OwnerUserId") AS "OWNERUSERID", "t0"."LASTACTIVITYDATE", "t7"."Id", "t7"."Reputation", "t7"."CreationDate", "t7"."DisplayName", "t7"."LastAccessDate", "t7"."WebsiteUrl", "t7"."Location", "t7"."AboutMe", "t7"."Views", "t7"."UpVotes", "t7"."DownVotes", "t7"."ProfileImageUrl", "t7"."AccountId", "t7"."USERID", "t7"."GOLDBADGES", "t7"."SILVERBADGES", "t7"."BRONZEBADGES", "t7"."OWNERUSERID" AS "OWNERUSERID0", "t7"."QUESTIONCOUNT", "t7"."ANSWERCOUNT", "t7"."TOTALSCORE", "t7"."TOTALVIEWS"
FROM (SELECT "OwnerUserId", MAX("LastActivityDate") AS "LASTACTIVITYDATE"
FROM "STACK"."Posts"
GROUP BY "OwnerUserId"
HAVING MAX("LastActivityDate") > CAST((CURRENT_DATE - INTERVAL '6' MONTH) AS TIMESTAMP(0))) AS "t0"
INNER JOIN (SELECT "Users0"."Id", "Users0"."Reputation", "Users0"."CreationDate", "Users0"."DisplayName", "Users0"."LastAccessDate", "Users0"."WebsiteUrl", "Users0"."Location", "Users0"."AboutMe", "Users0"."Views", "Users0"."UpVotes", "Users0"."DownVotes", "Users0"."ProfileImageUrl", "Users0"."AccountId", "t6"."USERID", "t6"."GOLDBADGES", "t6"."SILVERBADGES", "t6"."BRONZEBADGES", CAST("t4"."OWNERUSERID" AS INTEGER) AS "OWNERUSERID", CAST("t4"."QUESTIONCOUNT" AS BIGINT) AS "QUESTIONCOUNT", CAST("t4"."ANSWERCOUNT" AS BIGINT) AS "ANSWERCOUNT", CAST("t4"."TOTALSCORE" AS INTEGER) AS "TOTALSCORE", CAST("t4"."TOTALVIEWS" AS INTEGER) AS "TOTALVIEWS"
FROM (SELECT "Posts0"."OwnerUserId" AS "OWNERUSERID", COUNT(CASE WHEN CAST("Posts0"."PostTypeId" AS INTEGER) = 1 THEN 1 ELSE NULL END) AS "QUESTIONCOUNT", COUNT(CASE WHEN CAST("Posts0"."PostTypeId" AS INTEGER) = 2 THEN 1 ELSE NULL END) AS "ANSWERCOUNT", SUM("Posts0"."Score") AS "TOTALSCORE", SUM("Posts0"."ViewCount") AS "TOTALVIEWS"
FROM (SELECT *
FROM "STACK"."Users"
WHERE "Reputation" > 1000) AS "t1"
INNER JOIN "STACK"."Posts" AS "Posts0" ON "t1"."Id" = "Posts0"."OwnerUserId"
GROUP BY "Posts0"."OwnerUserId"
HAVING COUNT(CASE WHEN CAST("Posts0"."PostTypeId" AS INTEGER) = 1 THEN 1 ELSE NULL END) > 5 OR COUNT(CASE WHEN CAST("Posts0"."PostTypeId" AS INTEGER) = 2 THEN 1 ELSE NULL END) > 10) AS "t4"
INNER JOIN ("STACK"."Users" AS "Users0" LEFT JOIN (SELECT "UserId" AS "USERID", COUNT(CASE WHEN CAST("Class" AS INTEGER) = 1 THEN 1 ELSE NULL END) AS "GOLDBADGES", COUNT(CASE WHEN CAST("Class" AS INTEGER) = 2 THEN 1 ELSE NULL END) AS "SILVERBADGES", COUNT(CASE WHEN CAST("Class" AS INTEGER) = 3 THEN 1 ELSE NULL END) AS "BRONZEBADGES"
FROM "STACK"."Badges"
GROUP BY "UserId") AS "t6" ON "Users0"."Id" = "t6"."USERID") ON "t4"."OWNERUSERID" = "Users0"."Id") AS "t7" ON "t0"."OwnerUserId" = "t7"."Id"