SELECT COALESCE("t0"."OWNERUSERID", "t0"."OWNERUSERID") AS "OWNERUSERID", "t0"."POSTCOUNT", "t0"."QUESTIONCOUNT", "t0"."ANSWERCOUNT", "t0"."TOTALSCORE", "t0"."AVGVIEWCOUNT", "t3"."USERID", "t3"."DISPLAYNAME", "t3"."BADGECOUNT", "t3"."GOLDCOUNT", "t3"."SILVERCOUNT", "t3"."BRONZECOUNT"
FROM (SELECT "OwnerUserId" AS "OWNERUSERID", COUNT(*) AS "POSTCOUNT", COUNT(CASE WHEN CAST("PostTypeId" AS INTEGER) = 1 THEN 1 ELSE NULL END) AS "QUESTIONCOUNT", COUNT(CASE WHEN CAST("PostTypeId" AS INTEGER) = 2 THEN 1 ELSE NULL END) AS "ANSWERCOUNT", SUM("Score") AS "TOTALSCORE", AVG("ViewCount") AS "AVGVIEWCOUNT"
FROM "STACK"."Posts"
GROUP BY "OwnerUserId") AS "t0"
INNER JOIN (SELECT ANY_VALUE("Users"."Id") AS "USERID", "Users"."DisplayName" AS "DISPLAYNAME", COUNT("Badges"."Id") AS "BADGECOUNT", SUM(CASE WHEN CAST("Badges"."Class" AS INTEGER) = 1 THEN 1 ELSE 0 END) AS "GOLDCOUNT", SUM(CASE WHEN CAST("Badges"."Class" AS INTEGER) = 2 THEN 1 ELSE 0 END) AS "SILVERCOUNT", SUM(CASE WHEN CAST("Badges"."Class" AS INTEGER) = 3 THEN 1 ELSE 0 END) AS "BRONZECOUNT"
FROM "STACK"."Badges"
RIGHT JOIN "STACK"."Users" ON "Badges"."UserId" = "Users"."Id"
GROUP BY "Users"."Id", "Users"."DisplayName") AS "t3" ON "t0"."OWNERUSERID" = "t3"."USERID"
WHERE "t3"."BADGECOUNT" > 0