SELECT COALESCE("t11"."POSTID", "t11"."POSTID") AS "POSTID", "t11"."TITLE", "t11"."CREATIONDATE", "t11"."SCORE", "t11"."VIEWCOUNT", "t11"."OWNERDISPLAYNAME", "t11"."COMMENTCOUNT", "t11"."UPVOTES", "t11"."DOWNVOTES", "t11"."EDITCOUNT", "t11"."MOSTRECENTEDIT", "t11"."TOPUSERNAME", "t11"."TOPUSERSCORE"
FROM (SELECT "t9"."POSTID", "t9"."TITLE", "t9"."CREATIONDATE", "t9"."SCORE", "t9"."VIEWCOUNT", "t9"."OWNERDISPLAYNAME", "t9"."COMMENTCOUNT", "t9"."UPVOTES", "t9"."DOWNVOTES", "t9"."EDITCOUNT", "t9"."MOSTRECENTEDIT", "t5"."DISPLAYNAME" AS "TOPUSERNAME", "t5"."TOTALSCORE" AS "TOPUSERSCORE"
FROM (SELECT "t4"."USERID", "t4"."DisplayName" AS "DISPLAYNAME", "t4"."TOTALSCORE", "t4"."POSTCOUNT"
FROM (SELECT "Users0"."Id", "Users0"."DisplayName", ANY_VALUE("Users0"."Id") AS "USERID", SUM("Posts0"."Score") AS "TOTALSCORE", COUNT(DISTINCT "Posts0"."Id") AS "POSTCOUNT"
FROM "STACK"."Users" AS "Users0"
INNER JOIN "STACK"."Posts" AS "Posts0" ON "Users0"."Id" = "Posts0"."OwnerUserId"
GROUP BY "Users0"."Id", "Users0"."DisplayName"
ORDER BY 4 DESC NULLS FIRST
FETCH NEXT 5 ROWS ONLY) AS "t4") AS "t5",
(SELECT "t8"."POSTID", "t8"."TITLE", "t8"."CREATIONDATE", "t8"."SCORE", "t8"."VIEWCOUNT", "t8"."OWNERDISPLAYNAME", "t8"."COMMENTCOUNT", "t8"."UPVOTES", "t8"."DOWNVOTES", "t6"."PostId" AS "POSTID0", "t6"."EDITCOUNT", "t6"."MOSTRECENTEDIT"
FROM (SELECT "PostId", COUNT(*) AS "EDITCOUNT", MAX("CreationDate") AS "MOSTRECENTEDIT"
FROM "STACK"."PostHistory"
GROUP BY "PostId") AS "t6"
RIGHT JOIN (SELECT ANY_VALUE("Id") AS "POSTID", "TITLE", "CREATIONDATE", "SCORE", "VIEWCOUNT", ANY_VALUE("DisplayName") AS "OWNERDISPLAYNAME", COUNT("Id1") AS "COMMENTCOUNT", SUM("FD_COL_7") AS "UPVOTES", SUM("FD_COL_8") AS "DOWNVOTES"
FROM "s1"
GROUP BY "Id", "TITLE", "CREATIONDATE", "SCORE", "VIEWCOUNT", "DisplayName") AS "t8" ON "t6"."PostId" = "t8"."POSTID") AS "t9"
ORDER BY "t9"."SCORE" DESC NULLS FIRST, "t9"."VIEWCOUNT" DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY) AS "t11"