SELECT COALESCE("t0"."USERID", "t0"."USERID") AS "USERID", "t0"."DISPLAYNAME", "t0"."TOTALCOMMENTS", "t0"."LASTCOMMENTDATE", "t4"."USERID" AS "USERID0", "t4"."DISPLAYNAME" AS "DISPLAYNAME0", "t4"."TOTALPOSTS", "t4"."TOTALQUESTIONS", "t4"."TOTALANSWERS", "t4"."TOTALSCORE", "t4"."AVGVIEWS", "t4"."LASTPOSTDATE"
FROM (SELECT ANY_VALUE("Users"."Id") AS "USERID", "Users"."DisplayName" AS "DISPLAYNAME", COUNT("Comments"."Id") AS "TOTALCOMMENTS", MAX("Comments"."CreationDate") AS "LASTCOMMENTDATE"
FROM "STACK"."Comments"
RIGHT JOIN "STACK"."Users" ON "Comments"."UserId" = "Users"."Id"
GROUP BY "Users"."Id", "Users"."DisplayName") AS "t0"
RIGHT JOIN (SELECT ANY_VALUE("Users0"."Id") AS "USERID", "Users0"."DisplayName" AS "DISPLAYNAME", COUNT(DISTINCT "Posts"."Id") AS "TOTALPOSTS", SUM(CASE WHEN CAST("Posts"."PostTypeId" AS INTEGER) = 1 THEN 1 ELSE 0 END) AS "TOTALQUESTIONS", SUM(CASE WHEN CAST("Posts"."PostTypeId" AS INTEGER) = 2 THEN 1 ELSE 0 END) AS "TOTALANSWERS", SUM("Posts"."Score") AS "TOTALSCORE", AVG("Posts"."ViewCount") AS "AVGVIEWS", MAX("Posts"."CreationDate") AS "LASTPOSTDATE"
FROM "STACK"."Posts"
RIGHT JOIN "STACK"."Users" AS "Users0" ON "Posts"."OwnerUserId" = "Users0"."Id"
GROUP BY "Users0"."Id", "Users0"."DisplayName"
HAVING COUNT(DISTINCT "Posts"."Id") > 5 AND SUM("Posts"."Score") > 100) AS "t4" ON "t0"."USERID" = "t4"."USERID"