SELECT COALESCE("p_partkey", "p_partkey") AS "p_partkey", "p_name", "TOTAL_QUANTITY", "TOTAL_REVENUE", "AVERAGE_DISCOUNT", "TOTAL_ORDERS"
FROM "s1"
ORDER BY "TOTAL_REVENUE" DESC NULLS FIRST
FETCH NEXT 100 ROWS ONLY