SELECT COALESCE("p_name", "p_name") AS "p_name", "TOTAL_AVAILABLE_QUANTITY", "AVERAGE_SUPPLY_COST", "TOTAL_SUPPLIERS"
FROM "s1"
ORDER BY "TOTAL_AVAILABLE_QUANTITY" DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY