SELECT COALESCE("P_PARTKEY", "P_PARTKEY") AS "P_PARTKEY", "P_NAME", "SUPPLIER_NAME", "PS_SUPPLYCOST", "PS_AVAILQTY", "TOTAL_REVENUE"
FROM (SELECT "P_PARTKEY", "P_NAME", "SUPPLIER_NAME", "PS_SUPPLYCOST", "PS_AVAILQTY", "TOTAL_REVENUE"
FROM "s1"
ORDER BY "TOTAL_REVENUE" DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY) AS "t4"