SELECT COALESCE("P_BRAND", "P_BRAND") AS "P_BRAND", "P_TYPE", "TOTAL_COST"
FROM (SELECT "P_BRAND", "P_TYPE", SUM("FD_COL_2") AS "TOTAL_COST"
FROM "s1"
GROUP BY "P_BRAND", "P_TYPE"
ORDER BY 3 DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY) AS "t2"