SELECT COALESCE("S_SUPPKEY", "S_SUPPKEY") AS "S_SUPPKEY", "S_NAME", "TOTALSUPPLYCOST"
FROM (SELECT "s_suppkey" AS "S_SUPPKEY", "s_name" AS "S_NAME", "TOTALSUPPLYCOST"
FROM (SELECT "s_suppkey", "s_name", "s_address", "s_nationkey", "s_phone", "s_acctbal", "s_comment", "S_SUPPKEY_", "TOTALSUPPLYCOST"
FROM "s1"
ORDER BY "TOTALSUPPLYCOST" DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY) AS "t2"
ORDER BY "TOTALSUPPLYCOST") AS "t4"