SELECT COALESCE("p_partkey", "p_partkey") AS "p_partkey", "p_name", "TOTAL_AVAILABLE_QUANTITY", "AVERAGE_SUPPLY_COST"
FROM "s1"
ORDER BY "TOTAL_AVAILABLE_QUANTITY" DESC NULLS FIRST
FETCH NEXT 100 ROWS ONLY