SELECT COALESCE("P_PARTKEY", "P_PARTKEY") AS "P_PARTKEY", "P_NAME", "REVENUE", "R_NAME", "N_NAME"
FROM (SELECT "P_PARTKEY", "P_NAME", "REVENUE", "R_NAME", "N_NAME"
FROM "s1"
ORDER BY "REVENUE" DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY) AS "t4"