SELECT COALESCE("t4"."C_CUSTKEY", "t4"."C_CUSTKEY") AS "C_CUSTKEY", "t4"."C_NAME", "t4"."TOTAL_SPENT", "t4"."SPEND_RANK", "t15"."r_regionkey", "t15"."r_name", "t15"."r_comment", "t15"."n_nationkey", "t15"."n_name", "t15"."n_regionkey", "t15"."n_comment", "t15"."s_suppkey", "t15"."s_name", "t15"."s_address", "t15"."s_nationkey", "t15"."s_phone", "t15"."s_acctbal", "t15"."s_comment", "t15"."S_SUPPKEY" AS "S_SUPPKEY_", "t15"."S_NAME" AS "S_NAME_", "t15"."TOTAL_SUPPLY_COST", "t15"."UNIQUE_PARTS", "t15"."C_CUSTKEY" AS "C_CUSTKEY0", "t15"."C_NAME" AS "C_NAME0", "t15"."TOTAL_SPENT" AS "TOTAL_SPENT0"
FROM (SELECT "t"."c_custkey" AS "C_CUSTKEY", "t"."c_name" AS "C_NAME", SUM("t2"."TOTAL_DISCOUNTED_PRICE") AS "TOTAL_SPENT", RANK() OVER (ORDER BY SUM("t2"."TOTAL_DISCOUNTED_PRICE") DESC NULLS FIRST) AS "SPEND_RANK"
FROM (SELECT "customer"."c_custkey", "customer"."c_name", "customer"."c_address", "customer"."c_nationkey", "customer"."c_phone", "customer"."c_acctbal", "customer"."c_mktsegment", "customer"."c_comment", "orders"."o_orderkey", "orders"."o_custkey", "orders"."o_orderstatus", "orders"."o_totalprice", "orders"."o_orderdate", "orders"."o_orderpriority", "orders"."o_clerk", "orders"."o_shippriority", "orders"."o_comment"
FROM "TPCH"."orders"
RIGHT JOIN "TPCH"."customer" ON "orders"."o_custkey" = "customer"."c_custkey") AS "t"
LEFT JOIN (SELECT "t0"."o_orderkey" AS "O_ORDERKEY", "t0"."o_orderdate" AS "O_ORDERDATE", SUM("lineitem"."l_extendedprice" * (1 - "lineitem"."l_discount")) AS "TOTAL_DISCOUNTED_PRICE"
FROM (SELECT *
FROM "TPCH"."orders"
WHERE "o_orderdate" >= DATE '1997-01-01') AS "t0"
INNER JOIN "TPCH"."lineitem" ON "t0"."o_orderkey" = "lineitem"."l_orderkey"
GROUP BY "t0"."o_orderkey", "t0"."o_orderdate") AS "t2" ON "t"."o_orderkey" = "t2"."O_ORDERKEY"
GROUP BY "t"."c_custkey", "t"."c_name") AS "t4"
RIGHT JOIN (SELECT "t14"."r_regionkey", "t14"."r_name", "t14"."r_comment", "t14"."n_nationkey", "t14"."n_name", "t14"."n_regionkey", "t14"."n_comment", "t14"."s_suppkey", "t14"."s_name", "t14"."s_address", "t14"."s_nationkey", "t14"."s_phone", "t14"."s_acctbal", "t14"."s_comment", "t14"."S_SUPPKEY", "t14"."S_NAME", "t14"."TOTAL_SUPPLY_COST", "t14"."UNIQUE_PARTS", "t9"."c_custkey" AS "C_CUSTKEY", "t9"."c_name" AS "C_NAME", "t9"."TOTAL_SPENT"
FROM (SELECT "t5"."c_custkey", "t5"."c_name", SUM("t8"."TOTAL_DISCOUNTED_PRICE") AS "TOTAL_SPENT"
FROM (SELECT "customer0"."c_custkey", "customer0"."c_name", "customer0"."c_address", "customer0"."c_nationkey", "customer0"."c_phone", "customer0"."c_acctbal", "customer0"."c_mktsegment", "customer0"."c_comment", "orders1"."o_orderkey", "orders1"."o_custkey", "orders1"."o_orderstatus", "orders1"."o_totalprice", "orders1"."o_orderdate", "orders1"."o_orderpriority", "orders1"."o_clerk", "orders1"."o_shippriority", "orders1"."o_comment"
FROM "TPCH"."orders" AS "orders1"
RIGHT JOIN "TPCH"."customer" AS "customer0" ON "orders1"."o_custkey" = "customer0"."c_custkey") AS "t5"
LEFT JOIN (SELECT "t6"."o_orderkey" AS "O_ORDERKEY", "t6"."o_orderdate" AS "O_ORDERDATE", SUM("lineitem0"."l_extendedprice" * (1 - "lineitem0"."l_discount")) AS "TOTAL_DISCOUNTED_PRICE"
FROM (SELECT *
FROM "TPCH"."orders"
WHERE "o_orderdate" >= DATE '1997-01-01') AS "t6"
INNER JOIN "TPCH"."lineitem" AS "lineitem0" ON "t6"."o_orderkey" = "lineitem0"."l_orderkey"
GROUP BY "t6"."o_orderkey", "t6"."o_orderdate") AS "t8" ON "t5"."o_orderkey" = "t8"."O_ORDERKEY"
GROUP BY "t5"."c_custkey", "t5"."c_name") AS "t9"
RIGHT JOIN (SELECT "t11"."r_regionkey", "t11"."r_name", "t11"."r_comment", "t11"."n_nationkey", "t11"."n_name", "t11"."n_regionkey", "t11"."n_comment", "t11"."s_suppkey", "t11"."s_name", "t11"."s_address", "t11"."s_nationkey", "t11"."s_phone", "t11"."s_acctbal", "t11"."s_comment", "t13"."S_SUPPKEY", "t13"."S_NAME", "t13"."TOTAL_SUPPLY_COST", "t13"."UNIQUE_PARTS", CAST("t11"."n_nationkey" AS BIGINT) AS "n_nationkey0"
FROM (SELECT "t10"."r_regionkey", "t10"."r_name", "t10"."r_comment", "t10"."n_nationkey", "t10"."n_name", "t10"."n_regionkey", "t10"."n_comment", "supplier"."s_suppkey", "supplier"."s_name", "supplier"."s_address", "supplier"."s_nationkey", "supplier"."s_phone", "supplier"."s_acctbal", "supplier"."s_comment"
FROM "TPCH"."supplier"
RIGHT JOIN (SELECT "region"."r_regionkey", "region"."r_name", "region"."r_comment", "nation"."n_nationkey", "nation"."n_name", "nation"."n_regionkey", "nation"."n_comment"
FROM "TPCH"."nation"
RIGHT JOIN "TPCH"."region" ON "nation"."n_regionkey" = "region"."r_regionkey") AS "t10" ON "supplier"."s_nationkey" = "t10"."n_nationkey") AS "t11"
LEFT JOIN (SELECT "supplier0"."s_suppkey" AS "S_SUPPKEY", "supplier0"."s_name" AS "S_NAME", SUM("partsupp"."ps_supplycost" * "partsupp"."ps_availqty") AS "TOTAL_SUPPLY_COST", COUNT(DISTINCT "partsupp"."ps_partkey") AS "UNIQUE_PARTS"
FROM "TPCH"."supplier" AS "supplier0"
INNER JOIN "TPCH"."partsupp" ON "supplier0"."s_suppkey" = "partsupp"."ps_suppkey"
GROUP BY "supplier0"."s_suppkey", "supplier0"."s_name") AS "t13" ON "t11"."s_suppkey" = "t13"."S_SUPPKEY") AS "t14" ON "t9"."c_custkey" = "t14"."n_nationkey0") AS "t15" ON "t4"."C_CUSTKEY" = "t15"."C_CUSTKEY"