SELECT COALESCE("r_name", "r_name") AS "R_NAME", "TOTAL_SUPPLIER_COST", "AVERAGE_CUSTOMER_SPENT", "CUSTOMER_COUNT"
FROM (SELECT "r_name", SUM("TOTAL_SUPPLY_COST") AS "TOTAL_SUPPLIER_COST", AVG("TOTAL_SPENT") AS "AVERAGE_CUSTOMER_SPENT", COUNT(DISTINCT "C_CUSTKEY") AS "CUSTOMER_COUNT", COUNT(DISTINCT "S_SUPPKEY_") AS "$f4"
FROM "s1"
GROUP BY "r_name"
HAVING COUNT(DISTINCT "S_SUPPKEY_") > 5 AND AVG("TOTAL_SPENT") IS NOT NULL
ORDER BY 2 DESC NULLS FIRST) AS "t19"