SELECT COALESCE("t0"."R_NAME", "t0"."R_NAME") AS "R_NAME", "t0"."s_suppkey", CASE WHEN "t2"."TOTAL_SUPPLY_COST" IS NOT NULL THEN CAST("t2"."TOTAL_SUPPLY_COST" AS DECIMAL(19, 2)) ELSE 0.00 END AS "FD_COL_2", CASE WHEN "t5"."TOTAL_PRICE" IS NOT NULL THEN CAST("t5"."TOTAL_PRICE" AS DECIMAL(19, 4)) ELSE 0.0000 END AS "FD_COL_3", "t5"."NUMBER_OF_ITEMS", "t2"."UNIQUE_PARTS"
FROM (SELECT "t"."N_NATIONKEY", "t"."R_NAME", "t"."N_NAME", "supplier"."s_suppkey", "supplier"."s_name", "supplier"."s_address", "supplier"."s_nationkey", "supplier"."s_phone", "supplier"."s_acctbal", "supplier"."s_comment"
FROM "TPCH"."supplier"
RIGHT JOIN (SELECT "nation"."n_nationkey" AS "N_NATIONKEY", "region"."r_name" AS "R_NAME", "nation"."n_name" AS "N_NAME"
FROM "TPCH"."nation"
LEFT JOIN "TPCH"."region" ON "nation"."n_regionkey" = "region"."r_regionkey") AS "t" ON "supplier"."s_nationkey" = "t"."N_NATIONKEY") AS "t0"
LEFT JOIN (SELECT "supplier0"."s_suppkey" AS "S_SUPPKEY", "supplier0"."s_name" AS "S_NAME", SUM("partsupp"."ps_supplycost" * "partsupp"."ps_availqty") AS "TOTAL_SUPPLY_COST", COUNT(DISTINCT "partsupp"."ps_partkey") AS "UNIQUE_PARTS"
FROM "TPCH"."supplier" AS "supplier0"
INNER JOIN "TPCH"."partsupp" ON "supplier0"."s_suppkey" = "partsupp"."ps_suppkey"
GROUP BY "supplier0"."s_suppkey", "supplier0"."s_name") AS "t2" ON "t0"."s_suppkey" = "t2"."S_SUPPKEY"
LEFT JOIN (SELECT "t3"."o_orderkey" AS "O_ORDERKEY", "t3"."o_orderdate" AS "O_ORDERDATE", SUM("lineitem"."l_extendedprice" * (1 - "lineitem"."l_discount")) AS "TOTAL_PRICE", COUNT(*) AS "NUMBER_OF_ITEMS"
FROM (SELECT *
FROM "TPCH"."orders"
WHERE "o_orderdate" >= DATE '1997-01-01') AS "t3"
INNER JOIN "TPCH"."lineitem" ON "t3"."o_orderkey" = "lineitem"."l_orderkey"
GROUP BY "t3"."o_orderkey", "t3"."o_orderdate") AS "t5" ON "t0"."s_suppkey" = "t5"."O_ORDERKEY"