SELECT COALESCE("REGION", "REGION") AS "REGION", "NATION", "NATION_SALES", "TOTAL_SUPPLY_COST", "SALES_TO_SUPPLY_COST_RATIO"
FROM "s1"
ORDER BY "SALES_TO_SUPPLY_COST_RATIO" DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY