SELECT COALESCE("t2"."r_name", "t2"."r_name") AS "REGION", "t2"."n_name" AS "NATION", CASE WHEN "t2"."TOTAL_SALES" IS NOT NULL THEN CAST("t2"."TOTAL_SALES" AS DECIMAL(19, 2)) ELSE 0.00 END AS "NATION_SALES", CAST("t5"."TOTAL_SUPPLY_COST" AS DECIMAL(19, 2)) AS "TOTAL_SUPPLY_COST", CASE WHEN CASE WHEN "t2"."TOTAL_SALES" IS NOT NULL THEN CAST("t2"."TOTAL_SALES" AS DECIMAL(19, 2)) ELSE 0.00 END > 0.00 THEN CASE WHEN "t2"."TOTAL_SALES" IS NOT NULL THEN CAST("t2"."TOTAL_SALES" AS DECIMAL(19, 2)) ELSE 0.00 END / CAST("t5"."TOTAL_SUPPLY_COST" AS DECIMAL(19, 2)) ELSE NULL END AS "SALES_TO_SUPPLY_COST_RATIO"
FROM (SELECT "t"."r_regionkey", "t"."r_name", "t"."r_comment", "t"."n_nationkey", "t"."n_name", "t"."n_regionkey", "t"."n_comment", "t1"."n_name" AS "N_NAME", "t1"."TOTAL_SALES", CAST("t"."n_nationkey" AS BIGINT) AS "n_nationkey0"
FROM (SELECT "region"."r_regionkey", "region"."r_name", "region"."r_comment", "nation"."n_nationkey", "nation"."n_name", "nation"."n_regionkey", "nation"."n_comment"
FROM "TPCH"."nation"
RIGHT JOIN "TPCH"."region" ON "nation"."n_regionkey" = "region"."r_regionkey") AS "t"
LEFT JOIN (SELECT "t0"."n_name", SUM("orders"."o_totalprice") AS "TOTAL_SALES"
FROM "TPCH"."orders"
RIGHT JOIN (SELECT "nation0"."n_nationkey", "nation0"."n_name", "nation0"."n_regionkey", "nation0"."n_comment", "customer"."c_custkey", "customer"."c_name", "customer"."c_address", "customer"."c_nationkey", "customer"."c_phone", "customer"."c_acctbal", "customer"."c_mktsegment", "customer"."c_comment"
FROM "TPCH"."customer"
RIGHT JOIN "TPCH"."nation" AS "nation0" ON "customer"."c_nationkey" = "nation0"."n_nationkey") AS "t0" ON "orders"."o_custkey" = "t0"."c_custkey"
GROUP BY "t0"."n_name") AS "t1" ON "t"."n_name" = "t1"."n_name") AS "t2"
INNER JOIN (SELECT "partsupp"."ps_suppkey" AS "PS_SUPPKEY", SUM("partsupp"."ps_supplycost" * "partsupp"."ps_availqty") AS "TOTAL_SUPPLY_COST"
FROM "TPCH"."part"
INNER JOIN "TPCH"."partsupp" ON "part"."p_partkey" = "partsupp"."ps_partkey"
GROUP BY "partsupp"."ps_suppkey"
HAVING SUM("partsupp"."ps_supplycost" * "partsupp"."ps_availqty") > 10000000.00) AS "t5" ON "t2"."n_nationkey0" = "t5"."PS_SUPPKEY"