SELECT COALESCE("R_NAME", "R_NAME") AS "R_NAME", "UNIQUE_CUSTOMERS", "AVG_SUPPLIER_COST", "LARGE_ORDERS", "POPULAR_PARTS"
FROM (SELECT "R_NAME", COUNT(DISTINCT "c_custkey") AS "UNIQUE_CUSTOMERS", AVG("TOTAL_COST") AS "AVG_SUPPLIER_COST", SUM("FD_COL_3") AS "LARGE_ORDERS", LISTAGG(DISTINCT "p_name", "FD_COL_5") AS "POPULAR_PARTS"
FROM "s1"
GROUP BY "R_NAME"
ORDER BY 2 DESC NULLS FIRST, 3 DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY) AS "t12"