SELECT COALESCE("t6"."r_name", "t6"."r_name") AS "R_NAME", "customer"."c_custkey", "t6"."TOTAL_COST", CASE WHEN "t8"."TOTAL_LINES" > 5 THEN 1 ELSE 0 END AS "FD_COL_3", "part"."p_name", ', ' AS "FD_COL_5"
FROM (SELECT "t5"."r_regionkey", "t5"."r_name", "t5"."r_comment", "t5"."n_nationkey", "t5"."n_name", "t5"."n_regionkey", "t5"."n_comment", "t5"."s_suppkey", "t5"."s_name", "t5"."s_address", "t5"."s_nationkey", "t5"."s_phone", "t5"."s_acctbal", "t5"."s_comment", "t5"."S_SUPPKEY", "t5"."S_NAME", "t5"."TOTAL_COST", "t5"."l_orderkey", "t5"."l_partkey", "t5"."l_suppkey", "t5"."l_linenumber", "t5"."l_quantity", "t5"."l_extendedprice", "t5"."l_discount", "t5"."l_tax", "t5"."l_returnflag", "t5"."l_linestatus", "t5"."l_shipdate", "t5"."l_commitdate", "t5"."l_receiptdate", "t5"."l_shipinstruct", "t5"."l_shipmode", "t5"."l_comment", CAST("t"."o_orderkey" AS BIGINT) AS "o_orderkey", CAST("t"."o_custkey" AS BIGINT) AS "o_custkey", CAST("t"."o_orderstatus" AS VARCHAR CHARACTER SET "ISO-8859-1") AS "o_orderstatus", CAST("t"."o_totalprice" AS DECIMAL(15, 2)) AS "o_totalprice", CAST("t"."o_orderdate" AS DATE) AS "o_orderdate", CAST("t"."o_orderpriority" AS VARCHAR CHARACTER SET "ISO-8859-1") AS "o_orderpriority", CAST("t"."o_clerk" AS VARCHAR CHARACTER SET "ISO-8859-1") AS "o_clerk", CAST("t"."o_shippriority" AS INTEGER) AS "o_shippriority", CAST("t"."o_comment" AS VARCHAR CHARACTER SET "ISO-8859-1") AS "o_comment"
FROM (SELECT *
FROM "TPCH"."orders"
WHERE "o_orderstatus" = 'O') AS "t"
INNER JOIN (SELECT "t4"."r_regionkey", "t4"."r_name", "t4"."r_comment", "t4"."n_nationkey", "t4"."n_name", "t4"."n_regionkey", "t4"."n_comment", "t4"."s_suppkey", "t4"."s_name", "t4"."s_address", "t4"."s_nationkey", "t4"."s_phone", "t4"."s_acctbal", "t4"."s_comment", "t4"."S_SUPPKEY", "t4"."S_NAME", "t4"."TOTAL_COST", "lineitem"."l_orderkey", "lineitem"."l_partkey", "lineitem"."l_suppkey", "lineitem"."l_linenumber", "lineitem"."l_quantity", "lineitem"."l_extendedprice", "lineitem"."l_discount", "lineitem"."l_tax", "lineitem"."l_returnflag", "lineitem"."l_linestatus", "lineitem"."l_shipdate", "lineitem"."l_commitdate", "lineitem"."l_receiptdate", "lineitem"."l_shipinstruct", "lineitem"."l_shipmode", "lineitem"."l_comment"
FROM "TPCH"."lineitem"
RIGHT JOIN (SELECT "t3"."r_regionkey", "t3"."r_name", "t3"."r_comment", "t3"."n_nationkey", "t3"."n_name", "t3"."n_regionkey", "t3"."n_comment", "t3"."s_suppkey", "t3"."s_name", "t3"."s_address", "t3"."s_nationkey", "t3"."s_phone", "t3"."s_acctbal", "t3"."s_comment", CAST("t1"."S_SUPPKEY" AS BIGINT) AS "S_SUPPKEY", CAST("t1"."S_NAME" AS VARCHAR CHARACTER SET "ISO-8859-1") AS "S_NAME", CAST("t1"."TOTAL_COST" AS DECIMAL(19, 2)) AS "TOTAL_COST"
FROM (SELECT "supplier"."s_suppkey" AS "S_SUPPKEY", "supplier"."s_name" AS "S_NAME", SUM("partsupp"."ps_supplycost" * "partsupp"."ps_availqty") AS "TOTAL_COST"
FROM "TPCH"."supplier"
INNER JOIN "TPCH"."partsupp" ON "supplier"."s_suppkey" = "partsupp"."ps_suppkey"
GROUP BY "supplier"."s_suppkey", "supplier"."s_name") AS "t1"
INNER JOIN (SELECT "t2"."r_regionkey", "t2"."r_name", "t2"."r_comment", "t2"."n_nationkey", "t2"."n_name", "t2"."n_regionkey", "t2"."n_comment", "supplier0"."s_suppkey", "supplier0"."s_name", "supplier0"."s_address", "supplier0"."s_nationkey", "supplier0"."s_phone", "supplier0"."s_acctbal", "supplier0"."s_comment"
FROM "TPCH"."supplier" AS "supplier0"
RIGHT JOIN (SELECT "region"."r_regionkey", "region"."r_name", "region"."r_comment", "nation"."n_nationkey", "nation"."n_name", "nation"."n_regionkey", "nation"."n_comment"
FROM "TPCH"."nation"
RIGHT JOIN "TPCH"."region" ON "nation"."n_regionkey" = "region"."r_regionkey") AS "t2" ON "supplier0"."s_nationkey" = "t2"."n_nationkey") AS "t3" ON "t1"."S_SUPPKEY" = "t3"."s_suppkey") AS "t4" ON "lineitem"."l_suppkey" = "t4"."s_suppkey") AS "t5" ON "t"."o_orderkey" = "t5"."l_orderkey") AS "t6"
LEFT JOIN (SELECT "l_orderkey" AS "L_ORDERKEY", COUNT(*) AS "TOTAL_LINES", SUM("l_extendedprice" * (1 - "l_discount")) AS "TOTAL_REVENUE"
FROM "TPCH"."lineitem"
GROUP BY "l_orderkey") AS "t8" ON "t6"."o_orderkey" = "t8"."L_ORDERKEY"
LEFT JOIN "TPCH"."partsupp" AS "partsupp0" ON "t6"."l_partkey" = "partsupp0"."ps_partkey"
LEFT JOIN "TPCH"."part" ON "partsupp0"."ps_partkey" = "part"."p_partkey"
LEFT JOIN "TPCH"."customer" ON "t6"."o_custkey" = "customer"."c_custkey"