SELECT COALESCE("t14"."R_NAME", "t14"."R_NAME") AS "R_NAME", "t14"."REGION_COUNT", "t14"."TOTAL_RETAIL_PRICE", "t14"."AVG_ORDER_PRICE"
FROM (SELECT "t12"."R_NAME", "t12"."REGION_COUNT", CASE WHEN "t12"."$f2" IS NOT NULL THEN CAST("t12"."$f2" AS DECIMAL(19, 2)) ELSE 0.00 END AS "TOTAL_RETAIL_PRICE", "t12"."AVG_ORDER_PRICE"
FROM (SELECT AVG("o_totalprice") AS "EXPR$0"
FROM "TPCH"."orders") AS "t11"
INNER JOIN (SELECT "R_NAME", "REGION_COUNT", SUM("P_RETAILPRICE") AS "$f2", AVG("O_TOTALPRICE") AS "AVG_ORDER_PRICE"
FROM "s1"
GROUP BY "R_NAME", "REGION_COUNT") AS "t12" ON "t11"."EXPR$0" < "t12"."AVG_ORDER_PRICE"
ORDER BY "t12"."R_NAME" DESC NULLS FIRST
OFFSET 5 ROWS
FETCH NEXT 10 ROWS ONLY) AS "t14"