SELECT COALESCE("t0"."O_ORDERKEY", "t0"."O_ORDERKEY") AS "O_ORDERKEY", "t0"."O_ORDERDATE", "t0"."O_TOTALPRICE", "t0"."ORDER_RANK", "t0"."$f4" AS "FD_COL_4", "t9"."R_NAME", "t9"."REGION_COUNT", "t9"."TOTAL_QUANTITY", "t9"."P_PARTKEY", "t9"."P_NAME", "t9"."P_RETAILPRICE", "t9"."SIZE_CATEGORY"
FROM (SELECT "o_orderkey" AS "O_ORDERKEY", "o_orderdate" AS "O_ORDERDATE", "o_totalprice" AS "O_TOTALPRICE", ROW_NUMBER() OVER (PARTITION BY EXTRACT(YEAR FROM "o_orderdate") ORDER BY "o_totalprice" DESC NULLS FIRST) AS "ORDER_RANK", EXTRACT(YEAR FROM "o_orderdate") AS "$f4"
FROM "TPCH"."orders"
WHERE "o_orderdate" >= DATE '1994-01-01') AS "t0"
RIGHT JOIN (SELECT "t8"."R_NAME", "t8"."REGION_COUNT", "t8"."TOTAL_QUANTITY", "t1"."P_PARTKEY", "t1"."P_NAME", "t1"."P_RETAILPRICE", "t1"."SIZE_CATEGORY"
FROM (SELECT "p_partkey" AS "P_PARTKEY", "p_name" AS "P_NAME", "p_retailprice" AS "P_RETAILPRICE", CASE WHEN "p_size" >= 1 AND "p_size" <= 5 THEN 'Small ' WHEN "p_size" >= 6 AND "p_size" <= 15 THEN 'Medium' ELSE 'Large ' END AS "SIZE_CATEGORY"
FROM "TPCH"."part") AS "t1"
RIGHT JOIN (SELECT "t6"."r_name" AS "R_NAME", COUNT(DISTINCT "t6"."N_NATIONKEY") AS "REGION_COUNT", SUM("t2"."TOTAL_QTY") AS "TOTAL_QUANTITY", COUNT(DISTINCT "t6"."N_NATIONKEY") > 5 AS "$f3"
FROM (SELECT "l_orderkey", SUM("l_quantity") AS "TOTAL_QTY"
FROM "TPCH"."lineitem"
GROUP BY "l_orderkey") AS "t2"
RIGHT JOIN (SELECT "region"."r_regionkey", "region"."r_name", "region"."r_comment", "t5"."N_NAME", "t5"."SUPPLIER_COUNT", "t5"."N_NATIONKEY", CAST("t5"."N_NATIONKEY" AS BIGINT) AS "N_NATIONKEY0"
FROM (SELECT "nation"."n_name" AS "N_NAME", COUNT(DISTINCT "supplier"."s_suppkey") AS "SUPPLIER_COUNT", "nation"."n_nationkey" AS "N_NATIONKEY"
FROM "TPCH"."nation"
INNER JOIN "TPCH"."supplier" ON "nation"."n_nationkey" = "supplier"."s_nationkey"
GROUP BY "nation"."n_nationkey", "nation"."n_name") AS "t5"
RIGHT JOIN "TPCH"."region" ON "t5"."N_NATIONKEY" = "region"."r_regionkey") AS "t6" ON "t2"."l_orderkey" = "t6"."N_NATIONKEY0"
GROUP BY "t6"."r_name") AS "t8" ON "t8"."$f3") AS "t9" ON "t0"."$f4" = "t9"."REGION_COUNT"