SELECT COALESCE("NATION_REGION", "NATION_REGION") AS "NATION_REGION", "UNIQUE_CUSTOMERS", "TOTAL_RETAIL_PRICE_LARGE_NAME", ROUND("$f5", 2) AS "AVG_SALES_PRICE", "PART_COMMENTS"
FROM (SELECT "n_name", "r_name", ANY_VALUE("FD_COL_2") AS "NATION_REGION", COUNT(DISTINCT "c_custkey") AS "UNIQUE_CUSTOMERS", SUM("FD_COL_4") AS "TOTAL_RETAIL_PRICE_LARGE_NAME", AVG("FD_COL_5") AS "$f5", LISTAGG(DISTINCT "p_comment", "FD_COL_7") AS "PART_COMMENTS"
FROM "s1"
GROUP BY "n_name", "r_name"
HAVING COUNT(DISTINCT "c_custkey") > 10
ORDER BY 3) AS "t4"