SELECT COALESCE("P_NAME", "P_NAME") AS "P_NAME", "S_NAME", "TOTAL_QUANTITY", "AVG_PRICE", "ORDER_COUNT", "TRUNCATED_SUPPLIER_COMMENT", "REGION_NATION"
FROM (SELECT "P_NAME", "S_NAME", "TOTAL_QUANTITY", "AVG_PRICE", "ORDER_COUNT", "TRUNCATED_SUPPLIER_COMMENT", "REGION_NATION"
FROM "s1"
WHERE "TOTAL_QUANTITY" > 1000.00
ORDER BY "TOTAL_QUANTITY" DESC NULLS FIRST, "AVG_PRICE") AS "t6"