SELECT COALESCE("DETAILS", "DETAILS") AS "DETAILS", "TOTAL_COUNT", "TOTAL_SUPPLY_COST"
FROM (SELECT "DETAILS", COUNT(*) AS "TOTAL_COUNT", SUM("PS_SUPPLYCOST") AS "TOTAL_SUPPLY_COST"
FROM "s1"
GROUP BY "DETAILS"
HAVING COUNT(*) > 1
ORDER BY 3 DESC NULLS FIRST) AS "t7"