SELECT COALESCE("SUPPLIER_REGION_NAME", "SUPPLIER_REGION_NAME") AS "SUPPLIER_REGION_NAME", "TOTAL_REVENUE", "ORDERS_COUNT", "AVG_PRICE_BUILDING", "PART_NAMES"
FROM (SELECT "SUPPLIER_REGION_NAME", "TOTAL_REVENUE", "ORDERS_COUNT", "AVG_PRICE_BUILDING", "PART_NAMES"
FROM "s1"
ORDER BY "TOTAL_REVENUE" DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY) AS "t5"