SELECT COALESCE("SUPPLIER_NAME", "SUPPLIER_NAME") AS "SUPPLIER_NAME", "PART_NAME", "TOTAL_ORDERS", "TOTAL_REVENUE", "MARKET_SEGMENTS", "FIRST_SHIP_DATE", "LAST_SHIP_DATE"
FROM (SELECT "SUPPLIER_NAME", "PART_NAME", "TOTAL_ORDERS", "TOTAL_REVENUE", "MARKET_SEGMENTS", "FIRST_SHIP_DATE", "LAST_SHIP_DATE"
FROM "s1"
ORDER BY "TOTAL_REVENUE" DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY) AS "t7"