SELECT COALESCE("t3"."FORMATTED_NAME_ADDRESS", "t3"."FORMATTED_NAME_ADDRESS") AS "FORMATTED_NAME_ADDRESS", "t3"."P_NAME", "t3"."MODIFIED_COMMENT", "t3"."C_NAME", SUM("t5"."L_QUANTITY") AS "TOTAL_QUANTITY", SUM("t5"."L_EXTENDEDPRICE" * (1 - "t5"."L_DISCOUNT")) AS "TOTAL_REVENUE"
FROM (SELECT "t2"."S_SUPPKEY", "t2"."S_NAME", "t2"."S_NATIONKEY", "t2"."FORMATTED_NAME_ADDRESS", "t2"."ps_partkey", "t2"."ps_suppkey", "t2"."ps_availqty", "t2"."ps_supplycost", "t2"."ps_comment", "t2"."P_PARTKEY", "t2"."P_NAME", "t2"."P_MFGR", "t2"."P_TYPE", "t2"."P_SIZE", "t2"."MODIFIED_COMMENT", "t"."C_CUSTKEY", "t"."C_NAME", "t"."C_MKTSEGMENT", "t"."LAST_TEN_ADDRESS_DIGITS"
FROM (SELECT "c_custkey" AS "C_CUSTKEY", "c_name" AS "C_NAME", "c_mktsegment" AS "C_MKTSEGMENT", RIGHT("c_address", 10) AS "LAST_TEN_ADDRESS_DIGITS"
FROM "TPCH"."customer") AS "t"
INNER JOIN (SELECT "t0"."S_SUPPKEY", "t0"."S_NAME", "t0"."S_NATIONKEY", "t0"."FORMATTED_NAME_ADDRESS", "partsupp"."ps_partkey", "partsupp"."ps_suppkey", "partsupp"."ps_availqty", "partsupp"."ps_supplycost", "partsupp"."ps_comment", "t1"."P_PARTKEY", "t1"."P_NAME", "t1"."P_MFGR", "t1"."P_TYPE", "t1"."P_SIZE", "t1"."MODIFIED_COMMENT", CAST("t0"."S_NATIONKEY" AS BIGINT) AS "S_NATIONKEY0"
FROM (SELECT "s_suppkey" AS "S_SUPPKEY", "s_name" AS "S_NAME", "s_nationkey" AS "S_NATIONKEY", CONCAT("s_name", ' (', SUBSTRING("s_address", 1, 10), '...)') AS "FORMATTED_NAME_ADDRESS"
FROM "TPCH"."supplier") AS "t0"
INNER JOIN ((SELECT "p_partkey" AS "P_PARTKEY", "p_name" AS "P_NAME", "p_mfgr" AS "P_MFGR", "p_type" AS "P_TYPE", "p_size" AS "P_SIZE", REPLACE("p_comment", 'part', 'component') AS "MODIFIED_COMMENT"
FROM "TPCH"."part") AS "t1" INNER JOIN "TPCH"."partsupp" ON "t1"."P_PARTKEY" = "partsupp"."ps_partkey") ON "t0"."S_SUPPKEY" = "partsupp"."ps_suppkey") AS "t2" ON "t"."C_CUSTKEY" = "t2"."S_NATIONKEY0") AS "t3"
INNER JOIN (SELECT "l_orderkey" AS "L_ORDERKEY", "l_partkey" AS "L_PARTKEY", "l_quantity" AS "L_QUANTITY", "l_extendedprice" AS "L_EXTENDEDPRICE", "l_discount" AS "L_DISCOUNT"
FROM "TPCH"."lineitem"
WHERE "l_returnflag" = 'N') AS "t5" ON "t3"."P_PARTKEY" = "t5"."L_ORDERKEY"
GROUP BY "t3"."FORMATTED_NAME_ADDRESS", "t3"."P_NAME", "t3"."MODIFIED_COMMENT", "t3"."C_NAME"