SELECT COALESCE("FORMATTED_NAME_ADDRESS", "FORMATTED_NAME_ADDRESS") AS "FORMATTED_NAME_ADDRESS", "P_NAME", "MODIFIED_COMMENT", "C_NAME", "TOTAL_QUANTITY", "TOTAL_REVENUE"
FROM "s1"
ORDER BY "TOTAL_REVENUE" DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY