SELECT COALESCE("P_NAME", "P_NAME") AS "P_NAME", "SUPPLIER_PART_INFO", "TOTAL_ORDERS", "TOTAL_REVENUE", "SHORT_COMMENT"
FROM (SELECT "P_NAME", CONCAT('Supplier: ', "s_name", ', Part Type: ', "p_type", ', Average Supply Cost: ', CAST("FD_COL_4" AS VARCHAR CHARACTER SET "ISO-8859-1")) AS "SUPPLIER_PART_INFO", "TOTAL_ORDERS", "TOTAL_REVENUE", "SHORT_COMMENT"
FROM "s1"
WHERE "TOTAL_ORDERS" > 5
ORDER BY "TOTAL_REVENUE" DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY) AS "t7"