SELECT COALESCE("PART_NAME", "PART_NAME") AS "PART_NAME", "SUPPLIER_NAME", "NATION_NAME", "TOTAL_QUANTITY_SOLD", "AVG_PRICE_AFTER_DISCOUNT", "TOTAL_ORDERS", "ORDER_PRIORITIES", "LATEST_SHIP_DATE"
FROM (SELECT "PART_NAME", "SUPPLIER_NAME", "NATION_NAME", "TOTAL_QUANTITY_SOLD", "AVG_PRICE_AFTER_DISCOUNT", "TOTAL_ORDERS", "ORDER_PRIORITIES", "LATEST_SHIP_DATE"
FROM "s1"
ORDER BY "TOTAL_QUANTITY_SOLD" DESC NULLS FIRST) AS "t7"