SELECT COALESCE("SUPPLIER_NAME", "SUPPLIER_NAME") AS "SUPPLIER_NAME", "PART_NAME", "TOTAL_AVAILABLE_QUANTITY", "MIN_DISCOUNT", "MAX_TAX", "UNIQUE_CUSTOMERS", "REGION_NAME", "TRIMMED_SUPPLIER_COMMENT"
FROM (SELECT "SUPPLIER_NAME", "PART_NAME", "TOTAL_AVAILABLE_QUANTITY", "MIN_DISCOUNT", "MAX_TAX", "UNIQUE_CUSTOMERS", "REGION_NAME", "TRIMMED_SUPPLIER_COMMENT"
FROM "s1"
WHERE "TOTAL_AVAILABLE_QUANTITY" > 1000
ORDER BY "TOTAL_AVAILABLE_QUANTITY" DESC NULLS FIRST, "UNIQUE_CUSTOMERS" DESC NULLS FIRST) AS "t6"