SELECT COALESCE("P_PARTKEY", "P_PARTKEY") AS "P_PARTKEY", "UPPERCASE_PART_NAME", "BRAND_TYPE", "MODIFIED_COMMENT", "TOTAL_SUPPLY_VALUE", "SUPPLIER_NAME", "REGION_NAME", "TOTAL_ORDERS"
FROM (SELECT "P_PARTKEY", ANY_VALUE("FD_COL_7") AS "UPPERCASE_PART_NAME", ANY_VALUE("FD_COL_8") AS "BRAND_TYPE", ANY_VALUE("FD_COL_9") AS "MODIFIED_COMMENT", CASE WHEN SUM("FD_COL_10") IS NOT NULL THEN CAST(SUM("FD_COL_10") AS DECIMAL(19, 2)) ELSE 0.00 END AS "TOTAL_SUPPLY_VALUE", ANY_VALUE("s_name") AS "SUPPLIER_NAME", ANY_VALUE("r_name") AS "REGION_NAME", COUNT(DISTINCT "o_orderkey") AS "TOTAL_ORDERS"
FROM "s1"
GROUP BY "P_PARTKEY", "p_name", "p_brand", "p_type", "p_comment", "s_name", "r_name"
HAVING COUNT(DISTINCT "o_orderkey") > 10
ORDER BY 5 DESC NULLS FIRST, 2) AS "t6"