SELECT COALESCE("SUPPLIER_INFO", "SUPPLIER_INFO") AS "SUPPLIER_INFO", "TOTAL_ORDERS", "TOTAL_REVENUE", "AVG_PART_PRICE", "PART_NAMES"
FROM (SELECT "SUPPLIER_INFO", "TOTAL_ORDERS", "TOTAL_REVENUE", "AVG_PART_PRICE", "PART_NAMES"
FROM "s1"
WHERE "TOTAL_REVENUE" > 100000.0000
ORDER BY "TOTAL_REVENUE" DESC NULLS FIRST) AS "t6"