SELECT COALESCE("SUPPLIER_NAME", "SUPPLIER_NAME") AS "SUPPLIER_NAME", "PART_NAME", "PART_BRAND", "TOTAL_AVAILABLE_QUANTITY", "AVG_EXTENDED_PRICE", "UNIQUE_CUSTOMERS", "REGION_NAME"
FROM (SELECT "SUPPLIER_NAME", "PART_NAME", "PART_BRAND", "TOTAL_AVAILABLE_QUANTITY", "AVG_EXTENDED_PRICE", "UNIQUE_CUSTOMERS", "REGION_NAME"
FROM "s1"
ORDER BY "TOTAL_AVAILABLE_QUANTITY" DESC NULLS FIRST, "AVG_EXTENDED_PRICE") AS "t7"