SELECT COALESCE("P_TYPE", "P_TYPE") AS "P_TYPE", "UNIQUE_SUPPLIERS", "TOTAL_AVAILQTY", "AVG_PRICE", "DESCRIPTIONS"
FROM (SELECT "P_TYPE", COUNT(DISTINCT "S_NAME") AS "UNIQUE_SUPPLIERS", SUM("PS_AVAILQTY") AS "TOTAL_AVAILQTY", AVG("P_RETAILPRICE") AS "AVG_PRICE", LISTAGG("PART_DESCRIPTION", "FD_COL_5") AS "DESCRIPTIONS"
FROM "s1"
GROUP BY "P_TYPE"
HAVING COUNT(DISTINCT "S_NAME") > 1
ORDER BY 4 DESC NULLS FIRST) AS "t3"