SELECT COALESCE("PART_NAME", "PART_NAME") AS "PART_NAME", "SUPPLIER_NAME", "CUSTOMER_NAME", "ORDER_DATE", "ORDER_COUNT", "TOTAL_REVENUE", "REGIONS_INVOLVED", "RETURN_STATUS"
FROM "s1"
ORDER BY "TOTAL_REVENUE" DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY