SELECT COALESCE("P_NAME", "P_NAME") AS "P_NAME", "SUPPLIER_COUNT", "AVG_SUPPLY_COST", "TOTAL_DISCOUNTED_QUANTITY", "MAX_RECENT_ORDER_VALUE", "SUPPLIER_NAMES"
FROM (SELECT "P_NAME", COUNT(DISTINCT "ps_suppkey") AS "SUPPLIER_COUNT", AVG("ps_supplycost") AS "AVG_SUPPLY_COST", SUM("FD_COL_3") AS "TOTAL_DISCOUNTED_QUANTITY", MAX("FD_COL_4") AS "MAX_RECENT_ORDER_VALUE", LISTAGG(DISTINCT "s_name", "FD_COL_6") AS "SUPPLIER_NAMES"
FROM "s1"
GROUP BY "P_NAME"
HAVING COUNT(DISTINCT "ps_suppkey") > 5
ORDER BY 3 DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY) AS "t6"