SELECT COALESCE("S_NAME", "S_NAME") AS "S_NAME", "P_NAME", "TOTAL_PARTS", "TOTAL_COST", "REGION_NAME", "CUSTOMER_NAME", "TOTAL_ORDERS", "AVERAGE_ORDER_VALUE"
FROM (SELECT "S_NAME", "P_NAME", "TOTAL_PARTS", "TOTAL_COST", "R_NAME" AS "REGION_NAME", "C_NAME" AS "CUSTOMER_NAME", "TOTAL_ORDERS", "AVERAGE_ORDER_VALUE"
FROM "s1"
ORDER BY "TOTAL_PARTS" DESC NULLS FIRST, "AVERAGE_ORDER_VALUE" DESC NULLS FIRST) AS "t11"