SELECT COALESCE("PART_SUPPLIER", "PART_SUPPLIER") AS "PART_SUPPLIER", "UNIQUE_CUSTOMERS", "TOTAL_REVENUE", "REGION_NAME", "COMMENT_EXCERPT"
FROM (SELECT "PART_SUPPLIER", "UNIQUE_CUSTOMERS", "TOTAL_REVENUE", "REGION_NAME", "COMMENT_EXCERPT"
FROM "s1"
WHERE "TOTAL_REVENUE" > 100000.0000
ORDER BY "TOTAL_REVENUE" DESC NULLS FIRST, "UNIQUE_CUSTOMERS") AS "t7"