SELECT COALESCE("TOP_CUSTOMER", "TOP_CUSTOMER") AS "TOP_CUSTOMER", "TOP_SUPPLIER", "PRODUCT_COUNT", "TOTAL_SPENT"
FROM (SELECT "C_NAME" AS "TOP_CUSTOMER", "SC_NAME" AS "TOP_SUPPLIER", "PRODUCT_COUNT", "TOTAL_SPENT"
FROM "s1"
ORDER BY "TOTAL_SPENT" DESC NULLS FIRST, "PRODUCT_COUNT" DESC NULLS FIRST) AS "t12"