SELECT COALESCE("NATION_NAME", "NATION_NAME") AS "NATION_NAME", "REGION_NAME", "SUPPLIER_NAME", "TOTAL_AVAILABLE_QUANTITY", "DISTINCT_PARTS_SUPPLIED", "PART_NAMES", "BENCHMARK_DATE"
FROM (SELECT "n_name_" AS "NATION_NAME", "REGION_NAME", "S_NAME" AS "SUPPLIER_NAME", "TOTAL_AVAILABLE_QUANTITY", "DISTINCT_PARTS_SUPPLIED", "PART_NAMES", DATE '1998-10-01' AS "BENCHMARK_DATE"
FROM "s1"
ORDER BY "TOTAL_AVAILABLE_QUANTITY" DESC NULLS FIRST) AS "t5"