SELECT COALESCE("t1"."S_SUPPKEY", "t1"."S_SUPPKEY") AS "S_SUPPKEY", "t1"."S_NAME", "t1"."S_NATIONKEY", "t1"."TOTAL_AVAILABLE_QUANTITY", "t1"."DISTINCT_PARTS_SUPPLIED", "t1"."PART_NAMES", "t2"."N_NATIONKEY", "t2"."N_NAME", "t2"."R_REGIONKEY", "t2"."REGION_NAME", "nation0"."n_nationkey" AS "n_nationkey_", "nation0"."n_name" AS "n_name_", "nation0"."n_regionkey", "nation0"."n_comment"
FROM (SELECT "supplier"."s_suppkey" AS "S_SUPPKEY", "supplier"."s_name" AS "S_NAME", "supplier"."s_nationkey" AS "S_NATIONKEY", SUM("partsupp"."ps_availqty") AS "TOTAL_AVAILABLE_QUANTITY", COUNT(DISTINCT "partsupp"."ps_partkey") AS "DISTINCT_PARTS_SUPPLIED", LISTAGG(DISTINCT "part"."p_name", ', ') AS "PART_NAMES"
FROM "TPCH"."supplier"
INNER JOIN ("TPCH"."part" INNER JOIN "TPCH"."partsupp" ON "part"."p_partkey" = "partsupp"."ps_partkey") ON "supplier"."s_suppkey" = "partsupp"."ps_suppkey"
GROUP BY "supplier"."s_suppkey", "supplier"."s_name", "supplier"."s_nationkey"
HAVING SUM("partsupp"."ps_availqty") > 1000) AS "t1"
INNER JOIN ((SELECT "nation"."n_nationkey" AS "N_NATIONKEY", "nation"."n_name" AS "N_NAME", "region"."r_regionkey" AS "R_REGIONKEY", "region"."r_name" AS "REGION_NAME"
FROM "TPCH"."region"
INNER JOIN "TPCH"."nation" ON "region"."r_regionkey" = "nation"."n_regionkey") AS "t2" INNER JOIN "TPCH"."nation" AS "nation0" ON "t2"."N_NATIONKEY" = "nation0"."n_nationkey") ON "t1"."S_NATIONKEY" = "t2"."N_NATIONKEY"