SELECT COALESCE("PART_NAME", "PART_NAME") AS "PART_NAME", "ORDER_COUNT", "TOTAL_REVENUE", "REGION_NAME", "NATION_NAME"
FROM (SELECT "PART_NAME", "ORDER_COUNT", "TOTAL_REVENUE", "REGION_NAME", "NATION_NAME"
FROM "s1"
WHERE "TOTAL_REVENUE" > 10000.0000
ORDER BY "TOTAL_REVENUE" DESC NULLS FIRST, "PART_NAME") AS "t6"