SELECT COALESCE("SUPPLIER_INFO", "SUPPLIER_INFO") AS "SUPPLIER_INFO", "TOTAL_PARTS_SUPPLIED", "TOTAL_AVAILABLE_QUANTITY", "AVERAGE_SUPPLY_COST", "PARTS_DETAILS", "REGION_NAME"
FROM (SELECT "SUPPLIER_INFO", "TOTAL_PARTS_SUPPLIED", "TOTAL_AVAILABLE_QUANTITY", "AVERAGE_SUPPLY_COST", "PARTS_DETAILS", "REGION_NAME"
FROM "s1"
WHERE "TOTAL_PARTS_SUPPLIED" > 5
ORDER BY "TOTAL_AVAILABLE_QUANTITY" DESC NULLS FIRST) AS "t5"