SELECT COALESCE("t2"."r_name", "t2"."r_name") AS "r_name", "t2"."SUPPLIER_NAME", "t4"."CUSTOMER_NAME", "t2"."SUPPLY_INFO", '; ' AS "FD_COL_4", "t4"."ORDER_SUMMARY"
FROM (SELECT "t1"."r_regionkey", "t1"."r_name", "t1"."r_comment", "t1"."n_nationkey", "t1"."n_name", "t1"."n_regionkey", "t1"."n_comment", "t1"."s_suppkey", "t1"."s_name", "t1"."s_address", "t1"."s_nationkey", "t1"."s_phone", "t1"."s_acctbal", "t1"."s_comment", "t"."SUPPLIER_NAME", "t"."PART_NAME", "t"."AVAILABLE_QUANTITY", "t"."SUPPLY_COST", "t"."SUPPLY_INFO"
FROM (SELECT "supplier"."s_name" AS "SUPPLIER_NAME", "part"."p_name" AS "PART_NAME", "partsupp"."ps_availqty" AS "AVAILABLE_QUANTITY", "partsupp"."ps_supplycost" AS "SUPPLY_COST", CONCAT("supplier"."s_name", ' supplies ', "part"."p_name", ' with availability of ', CAST("partsupp"."ps_availqty" AS VARCHAR CHARACTER SET "ISO-8859-1"), ' units at a cost of $', CAST(CAST("partsupp"."ps_supplycost" AS DECIMAL(12, 2)) AS VARCHAR CHARACTER SET "ISO-8859-1")) AS "SUPPLY_INFO"
FROM "TPCH"."supplier"
INNER JOIN ("TPCH"."part" INNER JOIN "TPCH"."partsupp" ON "part"."p_partkey" = "partsupp"."ps_partkey") ON "supplier"."s_suppkey" = "partsupp"."ps_suppkey") AS "t"
RIGHT JOIN (SELECT "t0"."r_regionkey", "t0"."r_name", "t0"."r_comment", "t0"."n_nationkey", "t0"."n_name", "t0"."n_regionkey", "t0"."n_comment", "supplier0"."s_suppkey", "supplier0"."s_name", "supplier0"."s_address", "supplier0"."s_nationkey", "supplier0"."s_phone", "supplier0"."s_acctbal", "supplier0"."s_comment"
FROM "TPCH"."supplier" AS "supplier0"
RIGHT JOIN (SELECT "region"."r_regionkey", "region"."r_name", "region"."r_comment", "nation"."n_nationkey", "nation"."n_name", "nation"."n_regionkey", "nation"."n_comment"
FROM "TPCH"."nation"
RIGHT JOIN "TPCH"."region" ON "nation"."n_regionkey" = "region"."r_regionkey") AS "t0" ON "supplier0"."s_nationkey" = "t0"."n_nationkey") AS "t1" ON "t"."SUPPLIER_NAME" = "t1"."s_name") AS "t2"
LEFT JOIN (SELECT ANY_VALUE("customer"."c_name") AS "CUSTOMER_NAME", COUNT(*) AS "TOTAL_ORDERS", SUM("orders"."o_totalprice") AS "TOTAL_SPENT", CONCAT("customer"."c_name", ' has placed ', CAST(COUNT(*) AS VARCHAR CHARACTER SET "ISO-8859-1"), ' orders totaling $', CAST(CAST(SUM("orders"."o_totalprice") AS DECIMAL(12, 2)) AS VARCHAR CHARACTER SET "ISO-8859-1")) AS "ORDER_SUMMARY"
FROM "TPCH"."customer"
INNER JOIN "TPCH"."orders" ON "customer"."c_custkey" = "orders"."o_custkey"
GROUP BY "customer"."c_name") AS "t4" ON "t2"."SUPPLIER_NAME" = "t4"."CUSTOMER_NAME"