SELECT COALESCE("CUSTOMER_INFO", "CUSTOMER_INFO") AS "CUSTOMER_INFO", "TOTAL_REVENUE", "TOTAL_ORDERS", "SUPPLIED_PARTS", "LAST_ORDER_DATE"
FROM (SELECT "CUSTOMER_INFO", "TOTAL_REVENUE", "TOTAL_ORDERS", "SUPPLIED_PARTS", "LAST_ORDER_DATE"
FROM "s1"
WHERE "TOTAL_REVENUE" > 10000.0000
ORDER BY "TOTAL_REVENUE" DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY) AS "t5"