SELECT COALESCE("P_NAME", "P_NAME") AS "P_NAME", "S_NAME", "N_NAME", "TOTAL_ORDERS", "AVG_ORDER_VALUE"
FROM "s1"
ORDER BY "TOTAL_ORDERS" DESC NULLS FIRST, "AVG_ORDER_VALUE" DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY