SELECT COALESCE("P_NAME", "P_NAME") AS "P_NAME", "P_BRAND", "SUPPLIER_INFO", "TOTAL_AVAILQTY", "TOTAL_ORDERS", "AVG_ORDER_VALUE", "CUSTOMER_DETAILS"
FROM (SELECT "P_NAME", "P_BRAND", "SUPPLIER_INFO", "TOTAL_AVAILQTY", "TOTAL_ORDERS", "AVG_ORDER_VALUE", "CUSTOMER_DETAILS"
FROM "s1"
ORDER BY "TOTAL_AVAILQTY" DESC NULLS FIRST, "AVG_ORDER_VALUE" DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY) AS "t5"