SELECT COALESCE("DETAILED_INFO", "DETAILED_INFO") AS "DETAILED_INFO", "COMMENT_LENGTH", "SHORT_COMMENT", "ORDER_COUNT"
FROM (SELECT "DETAILED_INFO", "COMMENT_LENGTH", "SHORT_COMMENT", "ORDER_COUNT"
FROM "s1"
WHERE "ORDER_COUNT" > 5
ORDER BY "COMMENT_LENGTH" DESC NULLS FIRST) AS "t8"