SELECT COALESCE("SUPPLIER_REGION", "SUPPLIER_REGION") AS "SUPPLIER_REGION", "ORDER_COUNT", "TOTAL_REVENUE", "AVG_QUANTITY_PER_ORDER", "PART_NAMES"
FROM (SELECT "SUPPLIER_REGION", "ORDER_COUNT", "TOTAL_REVENUE", "AVG_QUANTITY_PER_ORDER", "PART_NAMES"
FROM "s1"
ORDER BY "TOTAL_REVENUE" DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY) AS "t5"