SELECT COALESCE("SPECIAL_PART_COUNT", "SPECIAL_PART_COUNT") AS "SPECIAL_PART_COUNT", "AVERAGE_RETAIL_PRICE", "UNIQUE_SUPPLIERS_COUNT", "REGION_NAME", "NATION_NAME"
FROM (SELECT "SPECIAL_PART_COUNT", "AVERAGE_RETAIL_PRICE", "UNIQUE_SUPPLIERS_COUNT", "REGION_NAME", "NATION_NAME"
FROM "s1"
WHERE "UNIQUE_SUPPLIERS_COUNT" > 5
ORDER BY "REGION_NAME", "NATION_NAME") AS "t5"