SELECT COALESCE("COMBINED_NAME", "COMBINED_NAME") AS "COMBINED_NAME", "SUPPLIER_COUNT", "PART_SUPPLIER_COUNT", "DETAILED_INFO", "NATION_NAME", "PART_NAME"
FROM (SELECT CONCAT("NATION_NAME", ' | ', "PART_NAME") AS "COMBINED_NAME", "SUPPLIER_COUNT", "PART_SUPPLIER_COUNT", CONCAT('Nation: ', "NATION_NAME", ', Suppliers: ', CAST("SUPPLIER_COUNT" AS VARCHAR CHARACTER SET "ISO-8859-1"), ', Part: ', "PART_NAME", ', Part Suppliers: ', CAST("PART_SUPPLIER_COUNT" AS VARCHAR CHARACTER SET "ISO-8859-1")) AS "DETAILED_INFO", "NATION_NAME", "PART_NAME"
FROM "s1"
ORDER BY "NATION_NAME", "PART_NAME") AS "t7"