SELECT COALESCE("P_PARTKEY", "P_PARTKEY") AS "P_PARTKEY", "SHORT_PART_NAME", "COMMENT_LENGTH", "REGION_NAME", "SUPPLIER_COUNT", "SUPPLIER_NAMES", "MAX_EXTENDED_PRICE"
FROM (SELECT "P_PARTKEY", "SHORT_PART_NAME", "COMMENT_LENGTH", "REGION_NAME", "SUPPLIER_COUNT", "SUPPLIER_NAMES", "MAX_EXTENDED_PRICE"
FROM "s1"
ORDER BY "COMMENT_LENGTH" DESC NULLS FIRST, "SUPPLIER_COUNT" DESC NULLS FIRST) AS "t6"