SELECT COALESCE("N_NAME", "N_NAME") AS "N_NAME", "PART_COUNT", "MAX_UPPER_NAME_LENGTH", "MIN_LOWER_COMMENT_LENGTH", "MAX_MODIFIED_COMMENT_LENGTH", "AGGREGATED_BRAND_TYPE"
FROM (SELECT "N_NAME", COUNT(DISTINCT "P_PARTKEY") AS "PART_COUNT", MAX("FD_COL_2") AS "MAX_UPPER_NAME_LENGTH", MIN("FD_COL_3") AS "MIN_LOWER_COMMENT_LENGTH", MAX("FD_COL_4") AS "MAX_MODIFIED_COMMENT_LENGTH", LISTAGG("BRAND_TYPE", "FD_COL_6") AS "AGGREGATED_BRAND_TYPE"
FROM "s1"
GROUP BY "N_NAME"
ORDER BY 2 DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY) AS "t5"