SELECT COALESCE("DISTINCT_PART_COUNT", "DISTINCT_PART_COUNT") AS "DISTINCT_PART_COUNT", "AVERAGE_SUPPLIER_BALANCE", "SUPPLIER_NATIONS"
FROM (SELECT "DISTINCT_PART_COUNT", "AVERAGE_SUPPLIER_BALANCE", "SUPPLIER_NATIONS"
FROM "s1"
ORDER BY "AVERAGE_SUPPLIER_BALANCE" DESC NULLS FIRST) AS "t7"