SELECT COALESCE("CUSTOMER_NAME", "CUSTOMER_NAME") AS "CUSTOMER_NAME", "SUPPLIER_NAME", "PART_NAME", "NUMBER_OF_ORDERS", "TOTAL_REVENUE", "ORDER_SUMMARY"
FROM (SELECT "CUSTOMER_NAME", "SUPPLIER_NAME", "PART_NAME", "NUMBER_OF_ORDERS", "TOTAL_REVENUE", "ORDER_SUMMARY"
FROM "s1"
WHERE "TOTAL_REVENUE" > 1000.0000
ORDER BY "TOTAL_REVENUE" DESC NULLS FIRST) AS "t7"