SELECT COALESCE("SUPPLIER_REGION", "SUPPLIER_REGION") AS "SUPPLIER_REGION", "TOTAL_QUANTITY", "AVG_PRICE", "ORDER_COUNT", "PART_NAMES"
FROM (SELECT "SUPPLIER_REGION", "TOTAL_QUANTITY", "AVG_PRICE", "ORDER_COUNT", "PART_NAMES"
FROM "s1"
WHERE "TOTAL_QUANTITY" > 100.00
ORDER BY "TOTAL_QUANTITY" DESC NULLS FIRST) AS "t6"