SELECT COALESCE("P_NAME", "P_NAME") AS "P_NAME", "S_NAME", "TOTAL_AVAILABLE_QUANTITY", "TOTAL_ORDERS", "AVG_ORDER_PRICE", "REGION_NATION"
FROM (SELECT "P_NAME", "S_NAME", "r_name", "n_name", SUM("ps_availqty") AS "TOTAL_AVAILABLE_QUANTITY", COUNT(DISTINCT "o_orderkey") AS "TOTAL_ORDERS", AVG("o_totalprice") AS "AVG_ORDER_PRICE", ANY_VALUE("FD_COL_7") AS "REGION_NATION"
FROM "s1"
GROUP BY "P_NAME", "S_NAME", "r_name", "n_name"
HAVING SUM("ps_availqty") > 1000
ORDER BY 7 DESC NULLS FIRST, 6 DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY) AS "t7"