SELECT COALESCE("SUPPLIER_NAME", "SUPPLIER_NAME") AS "SUPPLIER_NAME", "PART_NAME", "TOTAL_ORDERS", "TOTAL_REVENUE", "AVG_RETURN_AMT", "SUPPLIER_COMMENTS", "SANITIZED_PART_NAME"
FROM (SELECT "SUPPLIER_NAME", "PART_NAME", "TOTAL_ORDERS", "TOTAL_REVENUE", "AVG_RETURN_AMT", "SUPPLIER_COMMENTS", "SANITIZED_PART_NAME"
FROM "s1"
WHERE "FD_COL_9" > 5.00
ORDER BY "TOTAL_REVENUE" DESC NULLS FIRST) AS "t5"