SELECT COALESCE("SUPPLIER_INFO", "SUPPLIER_INFO") AS "SUPPLIER_INFO", "TOTAL_ORDERS", "TOTAL_REVENUE", "AVG_DISCOUNTED_PRICE", "PART_NAMES", "FURNITURE_CUSTOMERS"
FROM (SELECT "s_name", "n_name", "r_name", ANY_VALUE("FD_COL_3") AS "SUPPLIER_INFO", COUNT(DISTINCT "o_orderkey") AS "TOTAL_ORDERS", SUM("FD_COL_5") AS "TOTAL_REVENUE", AVG("FD_COL_6") AS "AVG_DISCOUNTED_PRICE", LISTAGG(DISTINCT "p_name", "FD_COL_8") AS "PART_NAMES", COUNT(DISTINCT "FD_COL_9") AS "FURNITURE_CUSTOMERS"
FROM "s1"
GROUP BY "s_name", "n_name", "r_name"
ORDER BY 6 DESC NULLS FIRST, 5 DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY) AS "t3"