SELECT COALESCE("P_BRAND", "P_BRAND") AS "P_BRAND", "SUPPLIER_COUNT", "AVG_PRICE", "LAST_SHIP_DATE", "FIRST_SHIP_DATE", "SUPPLIER_INFO"
FROM (SELECT "P_BRAND", "SUPPLIER_COUNT", "AVG_PRICE", "LAST_SHIP_DATE", "FIRST_SHIP_DATE", "SUPPLIER_INFO"
FROM "s1"
ORDER BY "AVG_PRICE" DESC NULLS FIRST) AS "t7"