SELECT COALESCE("SUPPLIER_INFO", "SUPPLIER_INFO") AS "SUPPLIER_INFO", "SHORT_PART_NAME", "CUSTOMER_COUNT", "TOTAL_REVENUE", "REGION_NAME"
FROM (SELECT "SUPPLIER_INFO", "SHORT_PART_NAME", "CUSTOMER_COUNT", "TOTAL_REVENUE", "REGION_NAME"
FROM "s1"
WHERE "CUSTOMER_COUNT" > 5
ORDER BY "TOTAL_REVENUE" DESC NULLS FIRST, "REGION_NAME") AS "t6"