SELECT COALESCE("SUPPLIER_NAME", "SUPPLIER_NAME") AS "SUPPLIER_NAME", "TOTAL_PARTS_SUPPLIED", "TOTAL_AVAILABLE_QUANTITY", "SUPPLIED_PART_NAMES", "REGION_NAME"
FROM (SELECT "SUPPLIER_NAME", "TOTAL_PARTS_SUPPLIED", "TOTAL_AVAILABLE_QUANTITY", "SUPPLIED_PART_NAMES", "REGION_NAME"
FROM "s1"
ORDER BY "TOTAL_PARTS_SUPPLIED" DESC NULLS FIRST, "SUPPLIER_NAME") AS "t6"