SELECT COALESCE("P_NAME", "P_NAME") AS "P_NAME", "SUPPLIER_COUNT", "TOTAL_AVAILABLE_QUANTITY", "AVERAGE_PRICE", "SUPPLIER_DETAILS"
FROM "s1"
WHERE "SUPPLIER_COUNT" > 2
ORDER BY "AVERAGE_PRICE" DESC NULLS FIRST