SELECT COALESCE("P_NAME", "P_NAME") AS "P_NAME", "S_NAME", "N_NAME", "CITY", "TOTAL_ORDERS", "TOTAL_QUANTITY", "AVG_PRICE"
FROM (SELECT "P_NAME", "S_NAME", "N_NAME", "CITY", "TOTAL_ORDERS", "TOTAL_QUANTITY", "AVG_PRICE"
FROM "s1"
WHERE "TOTAL_ORDERS" > 10
ORDER BY "TOTAL_QUANTITY" DESC NULLS FIRST, "AVG_PRICE") AS "t7"