SELECT COALESCE("P_NAME", "P_NAME") AS "P_NAME", "SUPPLIER_INFO", "SANITIZED_COMMENT", "NAME_LENGTH", "SHORT_ADDRESS", "FORMATTED_PHONE", "ORDER_COUNT"
FROM (SELECT "P_NAME", "SUPPLIER_INFO", "SANITIZED_COMMENT", "NAME_LENGTH", "SHORT_ADDRESS", "FORMATTED_PHONE", "ORDER_COUNT"
FROM "s1"
ORDER BY "NAME_LENGTH" DESC NULLS FIRST, "ORDER_COUNT" DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY) AS "t5"