SELECT COALESCE("P_NAME", "P_NAME") AS "P_NAME", "SUPPLIER_COUNT", "TOTAL_DISCOUNTED_SALES", "AVG_QUANTITY_PER_LINE", "LATEST_SHIPDATE", "EARLIEST_SHIPDATE", "SUPPLIER_DETAILS"
FROM "s1"
WHERE "SUPPLIER_COUNT" > 5
ORDER BY "TOTAL_DISCOUNTED_SALES" DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY