SELECT COALESCE("SUPPLIER_NAME", "SUPPLIER_NAME") AS "SUPPLIER_NAME", "PART_NAME", "TOTAL_AVAILABLE_QUANTITY", "TOTAL_ORDERS", "CUSTOMER_NAMES", "TOTAL_RETAIL_VALUE"
FROM "s1"
ORDER BY "TOTAL_RETAIL_VALUE" DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY