SELECT COALESCE("S_NAME", "S_NAME") AS "S_NAME", "S_ADDRESS", "COMMENT_EXCERPT", "SUPPLIER_INFO", "PART_COUNT", "TOTAL_AVAILABILITY", "AVERAGE_SUPPLY_COST", "SANITIZED_COMMENT", "COST_CATEGORY"
FROM (SELECT "S_NAME", "S_ADDRESS", "COMMENT_EXCERPT", "SUPPLIER_INFO", "PART_COUNT", "TOTAL_AVAILABILITY", "AVERAGE_SUPPLY_COST", "SANITIZED_COMMENT", CASE WHEN "AVERAGE_SUPPLY_COST" > 100.00 THEN 'Expensive ' ELSE 'Affordable' END AS "COST_CATEGORY"
FROM "s1"
ORDER BY "TOTAL_AVAILABILITY" DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY) AS "t4"