SELECT COALESCE("PART_INFO", "PART_INFO") AS "PART_INFO", "SUPPLIER_COUNT", "NATIONS_SUPPLIED", "UNIQUE_SUPPLIERS", "AVG_SUPPLY_COST"
FROM "s1"
ORDER BY "SUPPLIER_COUNT" DESC NULLS FIRST, "AVG_SUPPLY_COST"
FETCH NEXT 10 ROWS ONLY