SELECT COALESCE("P_NAME", "P_NAME") AS "P_NAME", "S_NAME", "SUPPLIER_INFO", "TOTAL_REVENUE"
FROM (SELECT "P_NAME", "S_NAME", "r_name", "n_name", ANY_VALUE("FD_COL_4") AS "SUPPLIER_INFO", SUM("FD_COL_5") AS "TOTAL_REVENUE"
FROM "s1"
GROUP BY "P_NAME", "S_NAME", "r_name", "n_name"
HAVING SUM("FD_COL_5") > 1000.0000
ORDER BY 6 DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY) AS "t6"