SELECT COALESCE("P_PARTKEY", "P_PARTKEY") AS "P_PARTKEY", "P_NAME", "P_RETAILPRICE", "COMMENT_LENGTH", "TOTAL_AVAILABLE_QTY", "SUPPLIER_COUNT", "C_CUSTKEY", "C_NAME", "TOTAL_ORDER_VALUE", "ORDER_COUNT", "COMBINED_INFO"
FROM (SELECT "P_PARTKEY", "P_NAME", "P_RETAILPRICE", "COMMENT_LENGTH", "TOTAL_AVAILABLE_QTY", "SUPPLIER_COUNT", "C_CUSTKEY", "C_NAME", "TOTAL_ORDER_VALUE", "ORDER_COUNT", CONCAT('Part: ', "P_NAME", ' | Customer: ', "C_NAME") AS "COMBINED_INFO"
FROM "s1"
FETCH NEXT 100 ROWS ONLY) AS "t6"