SELECT COALESCE("SUPPLIER_NAME", "SUPPLIER_NAME") AS "SUPPLIER_NAME", "PART_NAME", "SHORT_COMMENT", "LOCATION_INFO", "TOTAL_AVAILABLE_QTY"
FROM (SELECT "SUPPLIER_NAME", "PART_NAME", "SHORT_COMMENT", "LOCATION_INFO", "TOTAL_AVAILABLE_QTY"
FROM "s1"
WHERE "TOTAL_AVAILABLE_QTY" > 50
ORDER BY "LOCATION_INFO", "PART_NAME") AS "t4"