SELECT COALESCE("t2"."S_SUPPKEY", "t2"."S_SUPPKEY") AS "S_SUPPKEY", "t2"."S_NAME", "t2"."NATION", "t2"."TOTAL_PARTS", "t2"."TOTAL_SUPPLYCOST", "t6"."C_CUSTKEY", "t6"."C_NAME", "t6"."TOTAL_ORDERS", "t6"."TOTAL_SPENT", "t6"."EXPR$0" AS "FD_COL_9"
FROM (SELECT "S_SUPPKEY", "S_NAME", "NATION", "TOTAL_PARTS", "TOTAL_SUPPLYCOST"
FROM (SELECT "supplier"."s_suppkey", "supplier"."s_name", "nation"."n_name", ANY_VALUE("nation"."n_name") AS "NATION", COUNT(DISTINCT "part"."p_partkey") AS "TOTAL_PARTS", SUM("partsupp"."ps_supplycost") AS "TOTAL_SUPPLYCOST"
FROM "TPCH"."nation"
INNER JOIN "TPCH"."supplier" ON "nation"."n_nationkey" = "supplier"."s_nationkey"
INNER JOIN ("TPCH"."part" INNER JOIN "TPCH"."partsupp" ON "part"."p_partkey" = "partsupp"."ps_partkey") ON "supplier"."s_suppkey" = "partsupp"."ps_suppkey"
GROUP BY "nation"."n_name", "supplier"."s_suppkey", "supplier"."s_name") AS "t0"
WHERE "t0"."TOTAL_SUPPLYCOST" > 10000.00) AS "t2"
INNER JOIN (SELECT "t5"."c_custkey" AS "C_CUSTKEY", "t5"."c_name" AS "C_NAME", "t5"."TOTAL_ORDERS", "t5"."TOTAL_SPENT", "t4"."EXPR$0"
FROM (SELECT MAX("t3"."TOTAL_PARTS") AS "EXPR$0"
FROM (SELECT "nation0"."n_name", "supplier0"."s_suppkey", "supplier0"."s_name", ANY_VALUE("nation0"."n_name") AS "NATION", COUNT(DISTINCT "part0"."p_partkey") AS "TOTAL_PARTS", SUM("partsupp0"."ps_supplycost") AS "TOTAL_SUPPLYCOST"
FROM "TPCH"."nation" AS "nation0"
INNER JOIN "TPCH"."supplier" AS "supplier0" ON "nation0"."n_nationkey" = "supplier0"."s_nationkey"
INNER JOIN ("TPCH"."part" AS "part0" INNER JOIN "TPCH"."partsupp" AS "partsupp0" ON "part0"."p_partkey" = "partsupp0"."ps_partkey") ON "supplier0"."s_suppkey" = "partsupp0"."ps_suppkey"
GROUP BY "nation0"."n_name", "supplier0"."s_suppkey", "supplier0"."s_name") AS "t3") AS "t4",
(SELECT "customer"."c_custkey", "customer"."c_name", COUNT(DISTINCT "orders"."o_orderkey") AS "TOTAL_ORDERS", SUM("orders"."o_totalprice") AS "TOTAL_SPENT"
FROM "TPCH"."customer"
INNER JOIN "TPCH"."orders" ON "customer"."c_custkey" = "orders"."o_custkey"
GROUP BY "customer"."c_custkey", "customer"."c_name") AS "t5") AS "t6" ON "t2"."TOTAL_PARTS" = "t6"."EXPR$0"