SELECT COALESCE("SUPPLIER_NAME", "SUPPLIER_NAME") AS "SUPPLIER_NAME", "SUPPLIER_NATION", "PARTS_SUPPLIED", "TOTAL_SUPPLY_COST", "CUSTOMER_NAME", "TOTAL_ORDERS_PLACED", "TOTAL_SPENT_BY_CUSTOMER"
FROM (SELECT "S_NAME" AS "SUPPLIER_NAME", "NATION" AS "SUPPLIER_NATION", "TOTAL_PARTS" AS "PARTS_SUPPLIED", "TOTAL_SUPPLYCOST" AS "TOTAL_SUPPLY_COST", "C_NAME" AS "CUSTOMER_NAME", "TOTAL_ORDERS" AS "TOTAL_ORDERS_PLACED", "TOTAL_SPENT" AS "TOTAL_SPENT_BY_CUSTOMER"
FROM "s1"
ORDER BY "TOTAL_SPENT" DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY) AS "t9"