SELECT COALESCE("SUPPLIER_INFO", "SUPPLIER_INFO") AS "SUPPLIER_INFO", "PART_NAME", "AVAILABLE_QUANTITY", "MODIFIED_COMMENT", "ORDER_COUNT", "TOTAL_REVENUE", CASE WHEN "TOTAL_REVENUE" > 1000.0000 THEN 'High  ' WHEN "TOTAL_REVENUE" >= 500.0000 AND "TOTAL_REVENUE" <= 1000.0000 THEN 'Medium' ELSE 'Low   ' END AS "REVENUE_CATEGORY"
FROM (SELECT "s_name", "s_address", "p_name", "ps_availqty", "p_comment", ANY_VALUE("FD_COL_5") AS "SUPPLIER_INFO", ANY_VALUE("p_name") AS "PART_NAME", ANY_VALUE("ps_availqty") AS "AVAILABLE_QUANTITY", ANY_VALUE("FD_COL_6") AS "MODIFIED_COMMENT", COUNT(DISTINCT "o_orderkey") AS "ORDER_COUNT", SUM("FD_COL_8") AS "TOTAL_REVENUE"
FROM "s1"
GROUP BY "s_name", "s_address", "p_name", "ps_availqty", "p_comment"
ORDER BY 11 DESC NULLS FIRST, 6
FETCH NEXT 100 ROWS ONLY) AS "t5"