SELECT COALESCE("NATION_NAME", "NATION_NAME") AS "NATION_NAME", "SUPPLIER_COUNT", "LARGE_PART_AVAIL_QTY", "AVG_RETAIL_PRICE", "PART_NAMES", "MAX_ORDER_TOTAL_PRICE"
FROM (SELECT "n_name", ANY_VALUE("n_name") AS "NATION_NAME", COUNT(DISTINCT "s_suppkey") AS "SUPPLIER_COUNT", SUM("FD_COL_2") AS "LARGE_PART_AVAIL_QTY", AVG("p_retailprice") AS "AVG_RETAIL_PRICE", LISTAGG(DISTINCT "p_name", "FD_COL_5") AS "PART_NAMES", MAX("o_totalprice") AS "MAX_ORDER_TOTAL_PRICE"
FROM "s1"
GROUP BY "n_name"
HAVING COUNT(DISTINCT "s_suppkey") > 5
ORDER BY 2) AS "t5"