SELECT COALESCE("P_NAME", "P_NAME") AS "P_NAME", "S_NAME", "N_NAME", "R_NAME", "TOTAL_ORDERS", "TOTAL_REVENUE", "AVG_SUPPLIER_BALANCE", "ORDER_PRIORITIES"
FROM "s1"
WHERE "TOTAL_REVENUE" > 10000.00
ORDER BY "TOTAL_REVENUE" DESC NULLS FIRST, "TOTAL_ORDERS" DESC NULLS FIRST