SELECT COALESCE("P_NAME", "P_NAME") AS "P_NAME", "SUPPLIER_NAME", "TOTAL_QUANTITY", "TOTAL_REVENUE", "TOTAL_ORDERS", "LAST_SHIP_DATE", "FIRST_SHIP_DATE", "AVERAGE_DISCOUNT", "REGIONS_SUPPLY", "SHORT_COMMENT"
FROM (SELECT "P_NAME", "SUPPLIER_NAME", "TOTAL_QUANTITY", "TOTAL_REVENUE", "TOTAL_ORDERS", "LAST_SHIP_DATE", "FIRST_SHIP_DATE", "AVERAGE_DISCOUNT", "REGIONS_SUPPLY", "SHORT_COMMENT"
FROM "s1"
ORDER BY "TOTAL_REVENUE" DESC NULLS FIRST) AS "t5"