SELECT COALESCE("PART_DETAILS", "PART_DETAILS") AS "PART_DETAILS", "SUPPLIER_NAME", "CUSTOMER_INFO", "O_ORDERKEY", "O_ORDERDATE", "TOTAL_REVENUE"
FROM (SELECT "PART_DETAILS", "SUPPLIER_NAME", "CUSTOMER_INFO", "O_ORDERKEY", "O_ORDERDATE", "TOTAL_REVENUE"
FROM "s1"
WHERE "TOTAL_REVENUE" > 5000.0000
ORDER BY "TOTAL_REVENUE" DESC NULLS FIRST) AS "t6"