SELECT COALESCE("P_NAME", "P_NAME") AS "P_NAME", "SHORT_COMMENT", "SUPPLIER_REGION_INFO", "ORDER_COUNT", "TOTAL_QUANTITY", "AVG_PRICE", "PRICE_TYPE"
FROM (SELECT "P_NAME", "SHORT_COMMENT", "SUPPLIER_REGION_INFO", "ORDER_COUNT", "TOTAL_QUANTITY", "AVG_PRICE", CASE WHEN "FD_COL_10" > 0.00 THEN 'Discounted   ' ELSE 'Regular Price' END AS "PRICE_TYPE"
FROM "s1"
ORDER BY "TOTAL_QUANTITY" DESC NULLS FIRST, "AVG_PRICE") AS "t6"