SELECT COALESCE("P_NAME", "P_NAME") AS "P_NAME", "RETURNED_QUANTITY", "TOTAL_ORDERS", "MAX_PRICE", "SUPPLIER_DETAILS"
FROM "s1"
WHERE "RETURNED_QUANTITY" > 0.00
ORDER BY "TOTAL_ORDERS" DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY