SELECT COALESCE("REGION", "REGION") AS "REGION", "CUSTOMER_COUNT", "TOTAL_SUPPLIER_BALANCE", "AVERAGE_ORDER_VALUE"
FROM (SELECT "REGION", "CUSTOMER_COUNT", "TOTAL_SUPPLIER_BALANCE", "AVERAGE_ORDER_VALUE"
FROM "s1"
ORDER BY "TOTAL_SUPPLIER_BALANCE" DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY) AS "t11"