SELECT COALESCE("R_NAME", "R_NAME") AS "R_NAME", COUNT(DISTINCT "s_suppkey") AS "SUPPLIER_COUNT", AVG("TOTAL_SPENT") AS "AVG_CUSTOMER_SPENT", MAX("ps_supplycost") AS "MAX_SUPPLY_COST", SUM("FD_COL_4") AS "TOTAL_DISCOUNTED_SALES", SUM("FD_COL_5") AS "TOTAL_RETURNED_QUANTITY"
FROM "s1"
GROUP BY "R_NAME"
ORDER BY "R_NAME" DESC NULLS FIRST