SELECT COALESCE("R_NAME", "R_NAME") AS "R_NAME", CASE WHEN "$f1" IS NOT NULL THEN CAST("$f1" AS DECIMAL(19, 4)) ELSE 0.0000 END AS "TOTAL_RETURNED", "TOTAL_CUSTOMERS", "AVG_SUPPLIER_ACCT_BAL", "TOTAL_ORDERS", "TOTAL_QTY_AVAILABLE", "MAX_SUPPLY_COST"
FROM (SELECT "R_NAME", SUM("FD_COL_1") AS "$f1", COUNT(DISTINCT "c_custkey") AS "TOTAL_CUSTOMERS", AVG("AVG_ACCTBAL") AS "AVG_SUPPLIER_ACCT_BAL", COUNT(DISTINCT "o_orderkey") AS "TOTAL_ORDERS", SUM("TOTAL_AVAIL_QTY") AS "TOTAL_QTY_AVAILABLE", MAX("AVG_SUPPLY_COST") AS "MAX_SUPPLY_COST"
FROM "s1"
GROUP BY "R_NAME"
HAVING COUNT(DISTINCT "c_custkey") > 10
ORDER BY 5 DESC NULLS FIRST) AS "t12"