SELECT COALESCE("N_NAME", "N_NAME") AS "N_NAME", "R_NAME", "TOTAL_SUPPLY_VALUE", "TOTAL_ORDERS", "AVG_ORDER_VALUE"
FROM (SELECT "n_name" AS "N_NAME", "r_name" AS "R_NAME", CASE WHEN SUM("TOTAL_SUPPLY_VALUE") IS NOT NULL THEN CAST(SUM("TOTAL_SUPPLY_VALUE") AS DECIMAL(19, 2)) ELSE 0.00 END AS "TOTAL_SUPPLY_VALUE", CASE WHEN SUM("TOTAL_ORDERS") IS NOT NULL THEN CAST(SUM("TOTAL_ORDERS") AS BIGINT) ELSE 0 END AS "TOTAL_ORDERS", CASE WHEN AVG("AVG_ORDER_VALUE") IS NOT NULL THEN CAST(AVG("AVG_ORDER_VALUE") AS DECIMAL(15, 2)) ELSE 0.00 END AS "AVG_ORDER_VALUE"
FROM "s1"
GROUP BY "n_name", "r_name"
ORDER BY 3 DESC NULLS FIRST, 4 DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY) AS "t10"