SELECT COALESCE("t4"."n_nationkey", "t4"."n_nationkey") AS "n_nationkey", "t4"."n_name", "t4"."n_regionkey", "t4"."n_comment", "t4"."r_regionkey", "t4"."r_name", "t4"."r_comment", "t4"."PS_SUPPKEY", "t4"."TOTAL_SUPPLY_VALUE", "t4"."PART_COUNT", "t4"."n_nationkey0", "t6"."c_custkey" AS "C_CUSTKEY", "t6"."c_name" AS "C_NAME", "t6"."TOTAL_ORDERS", "t6"."AVG_ORDER_VALUE"
FROM (SELECT "t2"."n_nationkey", "t2"."n_name", "t2"."n_regionkey", "t2"."n_comment", "t2"."r_regionkey", "t2"."r_name", "t2"."r_comment", "t1"."PS_SUPPKEY", "t1"."TOTAL_SUPPLY_VALUE", "t1"."PART_COUNT", CAST("t2"."n_nationkey" AS BIGINT) AS "n_nationkey0"
FROM (SELECT "partsupp"."ps_suppkey" AS "PS_SUPPKEY", SUM("partsupp"."ps_supplycost" * "partsupp"."ps_availqty") AS "TOTAL_SUPPLY_VALUE", COUNT(DISTINCT "partsupp"."ps_partkey") AS "PART_COUNT"
FROM (SELECT *
FROM "TPCH"."supplier"
WHERE "s_acctbal" > 10000.00) AS "t"
INNER JOIN "TPCH"."partsupp" ON "t"."s_suppkey" = "partsupp"."ps_suppkey"
GROUP BY "partsupp"."ps_suppkey") AS "t1"
RIGHT JOIN (SELECT "nation"."n_nationkey", "nation"."n_name", "nation"."n_regionkey", "nation"."n_comment", "region"."r_regionkey", "region"."r_name", "region"."r_comment", CAST("nation"."n_nationkey" AS BIGINT) AS "n_nationkey0"
FROM "TPCH"."region"
INNER JOIN "TPCH"."nation" ON "region"."r_regionkey" = "nation"."n_regionkey") AS "t2" ON "t1"."PS_SUPPKEY" = "t2"."n_nationkey0"
WHERE "t2"."r_name" LIKE 'Europe%') AS "t4"
LEFT JOIN (SELECT "customer"."c_custkey", "customer"."c_name", COUNT("orders"."o_orderkey") AS "TOTAL_ORDERS", AVG("orders"."o_totalprice") AS "AVG_ORDER_VALUE"
FROM "TPCH"."orders"
RIGHT JOIN "TPCH"."customer" ON "orders"."o_custkey" = "customer"."c_custkey"
GROUP BY "customer"."c_custkey", "customer"."c_name"
HAVING COUNT("orders"."o_orderkey") > 5) AS "t6" ON "t4"."n_nationkey0" = "t6"."c_custkey"