SELECT COALESCE("t9"."C_NAME", "t9"."C_NAME") AS "C_NAME", "t9"."REGION_NAME", "t9"."NATION_NAME", "t9"."CUSTOMER_SEGMENT", "t"."PS_SUPPLYCOST", CASE WHEN "t9"."TOTAL_AVAILABLE_QUANTITY" IS NOT NULL THEN CAST("t9"."TOTAL_AVAILABLE_QUANTITY" AS BIGINT) ELSE 0 END AS "FD_COL_5"
FROM (SELECT "partsupp"."ps_partkey" AS "PS_PARTKEY", "nation"."n_name" AS "NATION_NAME", "region"."r_name" AS "REGION_NAME", "partsupp"."ps_supplycost" AS "PS_SUPPLYCOST"
FROM "TPCH"."region"
INNER JOIN "TPCH"."nation" ON "region"."r_regionkey" = "nation"."n_regionkey"
INNER JOIN "TPCH"."supplier" ON "nation"."n_nationkey" = "supplier"."s_nationkey"
INNER JOIN "TPCH"."partsupp" ON "supplier"."s_suppkey" = "partsupp"."ps_suppkey") AS "t"
RIGHT JOIN (SELECT "t4"."C_CUSTKEY", "t4"."C_NAME", "t4"."TOTAL_SPENT", "t4"."ORDER_COUNT", "t4"."CUSTOMER_SEGMENT", "t8"."R_REGIONKEY", "t8"."REGION_NAME", "t8"."NATION_NAME", "t8"."SUPPLIER_COUNT", "t0"."ps_partkey" AS "PS_PARTKEY", "t0"."TOTAL_AVAILABLE_QUANTITY", "t0"."AVG_SUPPLY_COST"
FROM (SELECT "ps_partkey", SUM("ps_availqty") AS "TOTAL_AVAILABLE_QUANTITY", AVG("ps_supplycost") AS "AVG_SUPPLY_COST"
FROM "TPCH"."partsupp"
GROUP BY "ps_partkey") AS "t0"
RIGHT JOIN ((SELECT "customer"."c_custkey" AS "C_CUSTKEY", "customer"."c_name" AS "C_NAME", CASE WHEN "t2"."TOTAL_SPENT" IS NOT NULL THEN CAST("t2"."TOTAL_SPENT" AS DECIMAL(19, 2)) ELSE 0.00 END AS "TOTAL_SPENT", CASE WHEN "t2"."ORDER_COUNT" IS NOT NULL THEN CAST("t2"."ORDER_COUNT" AS BIGINT) ELSE 0 END AS "ORDER_COUNT", CASE WHEN CAST("t2"."TOTAL_SPENT" AS DECIMAL(19, 2)) > 10000.00 THEN 'High Value  ' WHEN CAST("t2"."TOTAL_SPENT" AS DECIMAL(19, 2)) >= 5000.00 AND CAST("t2"."TOTAL_SPENT" AS DECIMAL(19, 2)) <= 10000.00 OR 0.00 >= 5000.00 AND 0.00 <= 10000.00 AND "t2"."TOTAL_SPENT" IS NULL THEN 'Medium Value' ELSE 'Low Value   ' END AS "CUSTOMER_SEGMENT"
FROM "TPCH"."customer"
LEFT JOIN (SELECT "o_custkey", SUM("o_totalprice") AS "TOTAL_SPENT", COUNT(*) AS "ORDER_COUNT"
FROM "TPCH"."orders"
WHERE "o_orderdate" >= DATE '1997-01-01'
GROUP BY "o_custkey") AS "t2" ON "customer"."c_custkey" = "t2"."o_custkey"
WHERE CASE WHEN "t2"."ORDER_COUNT" IS NOT NULL THEN CAST("t2"."ORDER_COUNT" AS BIGINT) ELSE 0 END > 1) AS "t4" INNER JOIN (SELECT "R_REGIONKEY", "REGION_NAME", "NATION_NAME", "SUPPLIER_COUNT"
FROM (SELECT "region0"."r_regionkey", "region0"."r_name", "nation0"."n_name", ANY_VALUE("region0"."r_name") AS "REGION_NAME", ANY_VALUE("nation0"."n_name") AS "NATION_NAME", COUNT(DISTINCT "supplier0"."s_suppkey") AS "SUPPLIER_COUNT"
FROM "TPCH"."supplier" AS "supplier0"
RIGHT JOIN ("TPCH"."nation" AS "nation0" INNER JOIN "TPCH"."region" AS "region0" ON "nation0"."n_regionkey" = "region0"."r_regionkey") ON "supplier0"."s_nationkey" = "nation0"."n_nationkey"
GROUP BY "nation0"."n_name", "region0"."r_regionkey", "region0"."r_name") AS "t6"
WHERE "t6"."SUPPLIER_COUNT" > 0) AS "t8" ON "t4"."C_CUSTKEY" = "t8"."SUPPLIER_COUNT") ON "t0"."ps_partkey" = "t4"."C_CUSTKEY") AS "t9" ON "t"."PS_PARTKEY" = "t9"."C_CUSTKEY"