SELECT COALESCE("REGION_NAME", "REGION_NAME") AS "REGION_NAME", "NATION_NAME", "CUSTOMER_COUNT", "TOTAL_ORDER_VALUE", CASE WHEN "$f4" IS NOT NULL THEN CAST("$f4" AS DECIMAL(19, 4)) ELSE 0.0000 END AS "TOTAL_LINEITEM_VALUE", "AVERAGE_SUPPLIER_COUNT"
FROM (SELECT "REGION_NAME", "NATION_NAME", COUNT(DISTINCT "C_CUSTKEY") AS "CUSTOMER_COUNT", SUM("O_TOTALPRICE") AS "TOTAL_ORDER_VALUE", SUM("FD_COL_4") AS "$f4", AVG("SUPPLIER_COUNT") AS "AVERAGE_SUPPLIER_COUNT"
FROM "s1"
GROUP BY "REGION_NAME", "NATION_NAME"
HAVING COUNT(DISTINCT "C_CUSTKEY") > 5
ORDER BY 4 DESC NULLS FIRST, "REGION_NAME", "NATION_NAME") AS "t10"