SELECT COALESCE("t4"."REGION_NAME", "t4"."REGION_NAME") AS "REGION_NAME", "t4"."NATION_NAME", "t4"."C_CUSTKEY", "t4"."O_TOTALPRICE", "t4"."l_extendedprice" * (1 - "t4"."l_discount") AS "FD_COL_4", "t5"."SUPPLIER_COUNT"
FROM (SELECT "t3"."C_CUSTKEY", "t3"."NATION_NAME", "t3"."REGION_NAME", "t3"."C_ACCTBAL", "t3"."O_ORDERKEY", "t3"."O_ORDERDATE", "t3"."O_TOTALPRICE", "t3"."O_ORDERSTATUS", "t3"."ORDER_RANK", "t3"."O_CUSTKEY", "lineitem"."l_orderkey", "lineitem"."l_partkey", "lineitem"."l_suppkey", "lineitem"."l_linenumber", "lineitem"."l_quantity", "lineitem"."l_extendedprice", "lineitem"."l_discount", "lineitem"."l_tax", "lineitem"."l_returnflag", "lineitem"."l_linestatus", "lineitem"."l_shipdate", "lineitem"."l_commitdate", "lineitem"."l_receiptdate", "lineitem"."l_shipinstruct", "lineitem"."l_shipmode", "lineitem"."l_comment"
FROM "TPCH"."lineitem"
RIGHT JOIN (SELECT "t2"."C_CUSTKEY", "t2"."NATION_NAME", "t2"."REGION_NAME", "t2"."C_ACCTBAL", "t0"."O_ORDERKEY", "t0"."O_ORDERDATE", "t0"."O_TOTALPRICE", "t0"."O_ORDERSTATUS", "t0"."ORDER_RANK", "t0"."O_CUSTKEY"
FROM (SELECT "o_orderkey" AS "O_ORDERKEY", "o_orderdate" AS "O_ORDERDATE", "o_totalprice" AS "O_TOTALPRICE", "o_orderstatus" AS "O_ORDERSTATUS", DENSE_RANK() OVER (PARTITION BY "o_orderstatus" ORDER BY "o_totalprice" DESC NULLS FIRST) AS "ORDER_RANK", "o_custkey" AS "O_CUSTKEY"
FROM "TPCH"."orders"
WHERE "o_orderdate" >= DATE '1996-01-01' AND "o_orderdate" < DATE '1997-01-01') AS "t0"
RIGHT JOIN (SELECT "t1"."c_custkey" AS "C_CUSTKEY", "nation"."n_name" AS "NATION_NAME", "region"."r_name" AS "REGION_NAME", "t1"."c_acctbal" AS "C_ACCTBAL"
FROM "TPCH"."region"
INNER JOIN "TPCH"."nation" ON "region"."r_regionkey" = "nation"."n_regionkey"
INNER JOIN (SELECT *
FROM "TPCH"."customer"
WHERE "c_acctbal" > 1000.00) AS "t1" ON "nation"."n_nationkey" = "t1"."c_nationkey") AS "t2" ON "t0"."O_CUSTKEY" = "t2"."C_CUSTKEY") AS "t3" ON "lineitem"."l_orderkey" = "t3"."O_ORDERKEY") AS "t4"
LEFT JOIN (SELECT "ps_partkey", COUNT(DISTINCT "ps_suppkey") AS "SUPPLIER_COUNT"
FROM "TPCH"."partsupp"
GROUP BY "ps_partkey") AS "t5" ON "t4"."l_partkey" = "t5"."ps_partkey"