SELECT COALESCE("P_NAME", "P_NAME") AS "P_NAME", "TOTAL_REVENUE", "SUPPLIER_REVENUE", "CUSTOMER_EXPENDITURE"
FROM (SELECT "P_NAME", "TOTAL_REVENUE", "SUPPLIER_REVENUE", "CUSTOMER_EXPENDITURE"
FROM "s1"
ORDER BY "TOTAL_REVENUE" DESC NULLS FIRST, "SUPPLIER_REVENUE" DESC NULLS FIRST, "CUSTOMER_EXPENDITURE" DESC NULLS FIRST) AS "t13"