SELECT COALESCE("t1"."p_partkey", "t1"."p_partkey") AS "P_PARTKEY", "t1"."p_name" AS "P_NAME", "t1"."AVG_EXTENDED_PRICE", "t6"."r_regionkey", "t6"."r_name", "t6"."r_comment", "t6"."n_nationkey", "t6"."n_name", "t6"."n_regionkey", "t6"."n_comment", "t6"."S_SUPPKEY", "t6"."S_NAME", "t6"."TOTAL_SUPPLY_COST"
FROM (SELECT "part"."p_partkey", "part"."p_name", AVG("t"."l_extendedprice") AS "AVG_EXTENDED_PRICE"
FROM "TPCH"."part"
INNER JOIN (SELECT *
FROM "TPCH"."lineitem"
WHERE "l_shipdate" >= DATE '1997-01-01' AND "l_shipdate" <= DATE '1997-12-31') AS "t" ON "part"."p_partkey" = "t"."l_partkey"
GROUP BY "part"."p_partkey", "part"."p_name"
HAVING AVG("t"."l_extendedprice") > 100.00) AS "t1"
INNER JOIN (SELECT "t2"."r_regionkey", "t2"."r_name", "t2"."r_comment", "t2"."n_nationkey", "t2"."n_name", "t2"."n_regionkey", "t2"."n_comment", "t5"."S_SUPPKEY", "t5"."S_NAME", "t5"."TOTAL_SUPPLY_COST"
FROM (SELECT "region"."r_regionkey", "region"."r_name", "region"."r_comment", "nation"."n_nationkey", "nation"."n_name", "nation"."n_regionkey", "nation"."n_comment", CAST("nation"."n_nationkey" AS BIGINT) AS "n_nationkey0"
FROM "TPCH"."region"
INNER JOIN "TPCH"."nation" ON "region"."r_regionkey" = "nation"."n_regionkey") AS "t2"
INNER JOIN (SELECT "supplier"."s_suppkey" AS "S_SUPPKEY", "supplier"."s_name" AS "S_NAME", SUM("partsupp"."ps_supplycost" * "partsupp"."ps_availqty") AS "TOTAL_SUPPLY_COST"
FROM "TPCH"."supplier"
INNER JOIN "TPCH"."partsupp" ON "supplier"."s_suppkey" = "partsupp"."ps_suppkey"
GROUP BY "supplier"."s_suppkey", "supplier"."s_name"
HAVING SUM("partsupp"."ps_supplycost" * "partsupp"."ps_availqty") > 50000.00) AS "t5" ON "t2"."n_nationkey0" = "t5"."S_SUPPKEY") AS "t6" ON "t1"."p_partkey" = "t6"."S_SUPPKEY"