SELECT COALESCE("REGION_NAME", "REGION_NAME") AS "REGION_NAME", "NATION_NAME", "SUPPLIER_NAME", "PART_NAME", "AVG_EXTENDED_PRICE", "TOTAL_SUPPLY_COST"
FROM (SELECT "r_name" AS "REGION_NAME", "n_name" AS "NATION_NAME", "S_NAME" AS "SUPPLIER_NAME", "P_NAME" AS "PART_NAME", "AVG_EXTENDED_PRICE", "TOTAL_SUPPLY_COST"
FROM "s1"
ORDER BY "r_name", "n_name", "TOTAL_SUPPLY_COST" DESC NULLS FIRST) AS "t9"