SELECT COALESCE("SUPPLIER_NAME", "SUPPLIER_NAME") AS "SUPPLIER_NAME", "CUSTOMER_NAME", "TOTAL_SPENT"
FROM (SELECT "S_NAME" AS "SUPPLIER_NAME", "C_NAME" AS "CUSTOMER_NAME", "TOTAL_SPENT"
FROM "s1"
ORDER BY "S_NAME", "TOTAL_SPENT" DESC NULLS FIRST) AS "t7"