SELECT COALESCE("REGION_NAME", "REGION_NAME") AS "REGION_NAME", "TOTAL_SALES", "UNIQUE_CUSTOMERS", "ORDER_COUNT", "TOTAL_SALES" / CASE WHEN "UNIQUE_CUSTOMERS" = 0 THEN NULL ELSE "UNIQUE_CUSTOMERS" END AS "AVG_SALES_PER_CUSTOMER", "TOTAL_SALES" / CASE WHEN "ORDER_COUNT" = 0 THEN NULL ELSE "ORDER_COUNT" END AS "AVG_SALES_PER_ORDER"
FROM (SELECT "R_REGIONKEY", "r_name", ANY_VALUE("r_name") AS "REGION_NAME", SUM("FD_COL_2") AS "TOTAL_SALES", COUNT(DISTINCT "c_custkey") AS "UNIQUE_CUSTOMERS", COUNT(DISTINCT "o_orderkey") AS "ORDER_COUNT"
FROM "s1"
GROUP BY "R_REGIONKEY", "r_name"
ORDER BY 4 DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY) AS "t3"