SELECT COALESCE("NATION_NAME", "NATION_NAME") AS "NATION_NAME", "REGION_NAME0", "AVG_SUPPLY_COST", "TOTAL_AVAILABLE_QUANTITY", "PART_COUNT"
FROM (SELECT "NATION_NAME", "REGION_NAME0", AVG("PS_SUPPLYCOST") AS "AVG_SUPPLY_COST", SUM("PS_AVAILQTY") AS "TOTAL_AVAILABLE_QUANTITY", COUNT(DISTINCT "P_NAME") AS "PART_COUNT"
FROM "s1"
GROUP BY "NATION_NAME", "REGION_NAME0"
ORDER BY "REGION_NAME0", 3 DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY) AS "t6"