SELECT COALESCE("REVENUE_TIER", "REVENUE_TIER") AS "REVENUE_TIER", COUNT(*) AS "NATION_COUNT", AVG("TOTAL_REVENUE") AS "AVG_REVENUE", SUM("TOTAL_ORDERS") AS "TOTAL_ORDERS_AGGREGATED"
FROM (SELECT CASE WHEN SUM("FD_COL_1") >= 1000000.0000 THEN 'High  ' WHEN SUM("FD_COL_1") >= 500000.0000 THEN 'Medium' ELSE 'Low   ' END AS "REVENUE_TIER", SUM("FD_COL_1") AS "TOTAL_REVENUE", COUNT(DISTINCT "o_orderkey") AS "TOTAL_ORDERS"
FROM "s1"
GROUP BY "n_name") AS "t3"
GROUP BY "REVENUE_TIER"
ORDER BY "REVENUE_TIER" DESC NULLS FIRST