SELECT COALESCE("NATION_NAME", "NATION_NAME") AS "NATION_NAME", "TOTAL_REVENUE", "TOTAL_ORDERS", "AVG_CUSTOMER_BALANCE"
FROM (SELECT "n_name", ANY_VALUE("n_name") AS "NATION_NAME", SUM("FD_COL_1") AS "TOTAL_REVENUE", COUNT(DISTINCT "o_orderkey") AS "TOTAL_ORDERS", AVG("c_acctbal") AS "AVG_CUSTOMER_BALANCE"
FROM "s1"
GROUP BY "n_name"
HAVING SUM("FD_COL_1") > 1000000.0000
ORDER BY 3 DESC NULLS FIRST) AS "t4"