SELECT COALESCE("NATION_NAME", "NATION_NAME") AS "NATION_NAME", "REGION_NAME", "TOTAL_REVENUE", "NUMBER_OF_ORDERS", "UNIQUE_CUSTOMERS"
FROM (SELECT "n_name", "r_name", ANY_VALUE("n_name") AS "NATION_NAME", ANY_VALUE("r_name") AS "REGION_NAME", SUM("FD_COL_2") AS "TOTAL_REVENUE", COUNT(DISTINCT "o_orderkey") AS "NUMBER_OF_ORDERS", COUNT(DISTINCT "c_custkey") AS "UNIQUE_CUSTOMERS"
FROM "s1"
GROUP BY "n_name", "r_name"
ORDER BY 5 DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY) AS "t4"