SELECT COALESCE("t1"."S_SUPPKEY", "t1"."S_SUPPKEY") AS "S_SUPPKEY", "t1"."S_NAME", "t1"."TOTAL_SUPPLY_VALUE", "t8"."O_ORDERKEY", "t8"."O_TOTALPRICE", "t8"."C_NAME", "t8"."S_NAME" AS "S_NAME0", "t8"."TOTAL_SUPPLY_VALUE" AS "TOTAL_SUPPLY_VALUE0", "t8"."TOTAL_LINE_VALUE", "t10"."L_ORDERKEY", "t10"."TOTAL_LINE_VALUE" AS "TOTAL_LINE_VALUE0"
FROM (SELECT "supplier"."s_suppkey" AS "S_SUPPKEY", "supplier"."s_name" AS "S_NAME", SUM("partsupp"."ps_supplycost" * "partsupp"."ps_availqty") AS "TOTAL_SUPPLY_VALUE"
FROM "TPCH"."supplier"
INNER JOIN "TPCH"."partsupp" ON "supplier"."s_suppkey" = "partsupp"."ps_suppkey"
GROUP BY "supplier"."s_suppkey", "supplier"."s_name"
HAVING SUM("partsupp"."ps_supplycost" * "partsupp"."ps_availqty") > 100000.00) AS "t1"
INNER JOIN (SELECT "t5"."O_ORDERKEY", "t5"."O_TOTALPRICE", "t5"."C_NAME", "t3"."S_NAME", "t3"."TOTAL_SUPPLY_VALUE", "t7"."TOTAL_LINE_VALUE"
FROM (SELECT "supplier0"."s_suppkey" AS "S_SUPPKEY", "supplier0"."s_name" AS "S_NAME", SUM("partsupp0"."ps_supplycost" * "partsupp0"."ps_availqty") AS "TOTAL_SUPPLY_VALUE"
FROM "TPCH"."supplier" AS "supplier0"
INNER JOIN "TPCH"."partsupp" AS "partsupp0" ON "supplier0"."s_suppkey" = "partsupp0"."ps_suppkey"
GROUP BY "supplier0"."s_suppkey", "supplier0"."s_name") AS "t3"
INNER JOIN ((SELECT "orders0"."o_orderkey" AS "O_ORDERKEY", "orders0"."o_totalprice" AS "O_TOTALPRICE", "customer"."c_name" AS "C_NAME"
FROM (SELECT AVG("o_totalprice") AS "EXPR$0"
FROM "TPCH"."orders") AS "t4"
INNER JOIN ("TPCH"."customer" INNER JOIN "TPCH"."orders" AS "orders0" ON "customer"."c_custkey" = "orders0"."o_custkey") ON "t4"."EXPR$0" < "orders0"."o_totalprice") AS "t5" INNER JOIN (SELECT "l_orderkey" AS "L_ORDERKEY", SUM("l_extendedprice" * (1 - "l_discount")) AS "TOTAL_LINE_VALUE"
FROM "TPCH"."lineitem"
GROUP BY "l_orderkey") AS "t7" ON "t5"."O_ORDERKEY" = "t7"."L_ORDERKEY") ON "t3"."S_SUPPKEY" = "t5"."O_ORDERKEY") AS "t8" ON "t1"."S_NAME" = "t8"."S_NAME"
INNER JOIN (SELECT "l_orderkey" AS "L_ORDERKEY", SUM("l_extendedprice" * (1 - "l_discount")) AS "TOTAL_LINE_VALUE"
FROM "TPCH"."lineitem"
GROUP BY "l_orderkey") AS "t10" ON "t8"."O_ORDERKEY" = "t10"."L_ORDERKEY"