SELECT COALESCE("S_NAME", "S_NAME") AS "S_NAME", "ORDER_COUNT", "TOTAL_REVENUE", "P_NAME", "P_MFGR", "P_TYPE", "R_NAME"
FROM (SELECT "S_NAME", "ORDER_COUNT", "TOTAL_REVENUE", "p_name" AS "P_NAME", "p_mfgr" AS "P_MFGR", "p_type" AS "P_TYPE", "r_name" AS "R_NAME"
FROM "s1"
ORDER BY "TOTAL_REVENUE" DESC NULLS FIRST, "p_name") AS "t5"