SELECT COALESCE("NATION", "NATION") AS "NATION", "REGION", "TOTAL_REVENUE", "TOTAL_ORDERS", "UNIQUE_CUSTOMERS", "AVERAGE_ORDER_VALUE"
FROM (SELECT "n_name", "r_name", ANY_VALUE("n_name") AS "NATION", ANY_VALUE("r_name") AS "REGION", SUM("FD_COL_2") AS "TOTAL_REVENUE", COUNT(DISTINCT "o_orderkey") AS "TOTAL_ORDERS", COUNT(DISTINCT "c_custkey") AS "UNIQUE_CUSTOMERS", AVG("o_totalprice") AS "AVERAGE_ORDER_VALUE"
FROM "s1"
GROUP BY "n_name", "r_name"
ORDER BY 5 DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY) AS "t4"