SELECT COALESCE("NATION", "NATION") AS "NATION", "TOTAL_REVENUE", "NUM_CUSTOMERS", "AVG_DISCOUNTED_PRICE"
FROM (SELECT "n_name", ANY_VALUE("n_name") AS "NATION", SUM("o_totalprice") AS "TOTAL_REVENUE", COUNT(DISTINCT "c_custkey") AS "NUM_CUSTOMERS", AVG("FD_COL_3") AS "AVG_DISCOUNTED_PRICE"
FROM "s1"
GROUP BY "n_name"
ORDER BY 3 DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY) AS "t4"