SELECT COALESCE("t1"."S_SUPPKEY", "t1"."S_SUPPKEY") AS "S_SUPPKEY", "t1"."S_NAME", "t1"."S_NATIONKEY", "t1"."TOTAL_COST", "t3"."c_custkey" AS "C_CUSTKEY", "t3"."c_name" AS "C_NAME", "t3"."c_nationkey" AS "C_NATIONKEY", "t3"."ORDER_COUNT", "t3"."TOTAL_SPENT", "t4"."n_nationkey" AS "N_NATIONKEY", "t4"."n_name" AS "N_NAME", "t4"."SUPPLIER_COUNT"
FROM (SELECT "supplier"."s_suppkey" AS "S_SUPPKEY", "supplier"."s_name" AS "S_NAME", "supplier"."s_nationkey" AS "S_NATIONKEY", SUM("partsupp"."ps_supplycost" * "partsupp"."ps_availqty") AS "TOTAL_COST"
FROM "TPCH"."supplier"
INNER JOIN "TPCH"."partsupp" ON "supplier"."s_suppkey" = "partsupp"."ps_suppkey"
GROUP BY "supplier"."s_suppkey", "supplier"."s_name", "supplier"."s_nationkey"
HAVING SUM("partsupp"."ps_supplycost" * "partsupp"."ps_availqty") > 100000.00) AS "t1"
INNER JOIN ((SELECT "customer"."c_custkey", "customer"."c_name", "customer"."c_nationkey", COUNT(*) AS "ORDER_COUNT", SUM("t2"."o_totalprice") AS "TOTAL_SPENT"
FROM "TPCH"."customer"
INNER JOIN (SELECT *
FROM "TPCH"."orders"
WHERE "o_orderstatus" = 'F') AS "t2" ON "customer"."c_custkey" = "t2"."o_custkey"
GROUP BY "customer"."c_custkey", "customer"."c_name", "customer"."c_nationkey") AS "t3" INNER JOIN (SELECT "nation"."n_nationkey", "nation"."n_name", COUNT(*) AS "SUPPLIER_COUNT"
FROM "TPCH"."nation"
INNER JOIN "TPCH"."supplier" AS "supplier0" ON "nation"."n_nationkey" = "supplier0"."s_nationkey"
GROUP BY "nation"."n_nationkey", "nation"."n_name") AS "t4" ON "t3"."c_nationkey" = "t4"."n_nationkey") ON "t1"."S_NATIONKEY" = "t3"."c_nationkey"