SELECT COALESCE("N_NAME", "N_NAME") AS "N_NAME", "C_NAME", "S_NAME", "TOTAL_COST", "ORDER_COUNT", "TOTAL_SPENT", "SUPPLIER_COUNT"
FROM (SELECT "N_NAME", "C_NAME", "S_NAME", "TOTAL_COST", "ORDER_COUNT", "TOTAL_SPENT", "SUPPLIER_COUNT"
FROM "s1"
ORDER BY "TOTAL_SPENT" DESC NULLS FIRST, "TOTAL_COST" DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY) AS "t7"