SELECT COALESCE("O_ORDERKEY", "O_ORDERKEY") AS "O_ORDERKEY", "TOTAL_REVENUE", "UNIQUE_CUSTOMERS", "AVG_CUSTOMER_BALANCE", "TOTAL_SUPPLY_VALUE", "TOTAL_PARTS_SUPPLIED", "LAST_SHIP_DATE"
FROM (SELECT "O_ORDERKEY", "TOTAL_REVENUE", "UNIQUE_CUSTOMERS", "AVG_CUSTOMER_BALANCE", "TOTAL_SUPPLY_VALUE", "TOTAL_PARTS_SUPPLIED", "LAST_SHIP_DATE"
FROM "s1"
ORDER BY "TOTAL_REVENUE" DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY) AS "t8"