SELECT COALESCE("NATION_NAME", "NATION_NAME") AS "NATION_NAME", "TOTAL_REVENUE", "ORDER_COUNT"
FROM (SELECT "n_name", ANY_VALUE("n_name") AS "NATION_NAME", SUM("FD_COL_1") AS "TOTAL_REVENUE", COUNT(DISTINCT "o_orderkey") AS "ORDER_COUNT"
FROM "s1"
GROUP BY "n_name"
ORDER BY 3 DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY) AS "t4"