SELECT COALESCE("O_ORDERKEY", "O_ORDERKEY") AS "O_ORDERKEY", "TOTAL_ITEMS", "TOTAL_DISCOUNTED_PRICE", "TOTAL_QUANTITY", "AVG_SUPPLY_COST", "REGION_NAME"
FROM (SELECT "O_ORDERKEY", "TOTAL_ITEMS", "TOTAL_DISCOUNTED_PRICE", "TOTAL_QUANTITY", "AVG_SUPPLY_COST", "r_name" AS "REGION_NAME"
FROM "s1"
ORDER BY "TOTAL_DISCOUNTED_PRICE" DESC NULLS FIRST) AS "t5"