SELECT COALESCE("t4"."O_ORDERKEY", "t4"."O_ORDERKEY") AS "O_ORDERKEY", "t4"."LINE_ITEM_COUNT", "t4"."TOTAL_ORDER_VALUE", "t4"."O_ORDERDATE", "t4"."O_ORDERSTATUS", "t4"."O_CUSTKEY", "t4"."$f0" AS "FD_COL_6", "t10"."n_nationkey", "t10"."n_name", "t10"."r_regionkey", "t10"."SUPPLIER_COUNT", "t10"."TOTAL_SUPPLY_COST_PER_NATION"
FROM (SELECT "t1"."O_ORDERKEY", "t1"."LINE_ITEM_COUNT", "t1"."TOTAL_ORDER_VALUE", "t1"."O_ORDERDATE", "t1"."O_ORDERSTATUS", "t1"."O_CUSTKEY", "t3"."$f1" AS "$f0"
FROM (SELECT "orders"."o_orderkey" AS "O_ORDERKEY", COUNT(*) AS "LINE_ITEM_COUNT", SUM("lineitem"."l_extendedprice") AS "TOTAL_ORDER_VALUE", "orders"."o_orderdate" AS "O_ORDERDATE", "orders"."o_orderstatus" AS "O_ORDERSTATUS", "orders"."o_custkey" AS "O_CUSTKEY"
FROM "TPCH"."orders"
INNER JOIN "TPCH"."lineitem" ON "orders"."o_orderkey" = "lineitem"."l_orderkey"
GROUP BY "orders"."o_orderkey", "orders"."o_custkey", "orders"."o_orderstatus", "orders"."o_orderdate") AS "t1"
LEFT JOIN (SELECT "c_custkey", SINGLE_VALUE("c_nationkey") AS "$f1"
FROM "TPCH"."customer"
GROUP BY "c_custkey") AS "t3" ON "t1"."O_CUSTKEY" = "t3"."c_custkey") AS "t4"
INNER JOIN (SELECT "nation"."n_nationkey", "nation"."n_name", "region"."r_regionkey", COUNT(DISTINCT "supplier0"."s_suppkey") AS "SUPPLIER_COUNT", SUM("t6"."TOTAL_SUPPLY_COST") AS "TOTAL_SUPPLY_COST_PER_NATION"
FROM "TPCH"."region"
INNER JOIN "TPCH"."nation" ON "region"."r_regionkey" = "nation"."n_regionkey"
INNER JOIN ((SELECT "supplier"."s_suppkey" AS "S_SUPPKEY", "supplier"."s_name" AS "S_NAME", "supplier"."s_nationkey" AS "S_NATIONKEY", SUM("partsupp"."ps_availqty") AS "TOTAL_AVAILABLE_QUANTITY", SUM("partsupp"."ps_supplycost" * "partsupp"."ps_availqty") AS "TOTAL_SUPPLY_COST"
FROM "TPCH"."supplier"
INNER JOIN "TPCH"."partsupp" ON "supplier"."s_suppkey" = "partsupp"."ps_suppkey"
GROUP BY "supplier"."s_suppkey", "supplier"."s_name", "supplier"."s_nationkey") AS "t6" INNER JOIN "TPCH"."supplier" AS "supplier0" ON "t6"."S_SUPPKEY" = "supplier0"."s_suppkey") ON "nation"."n_nationkey" = "supplier0"."s_nationkey"
GROUP BY "region"."r_regionkey", "nation"."n_nationkey", "nation"."n_name"
HAVING SUM("t6"."TOTAL_SUPPLY_COST") > 10000.00) AS "t10" ON "t4"."$f0" = "t10"."n_nationkey"