SELECT COALESCE("NATION_NAME", "NATION_NAME") AS "NATION_NAME", "SUPPLIER_COUNT", "TOTAL_SUPPLY_COST_PER_NATION", "LINE_ITEM_COUNT", "TOTAL_ORDER_VALUE", "O_ORDERSTATUS"
FROM (SELECT "n_name" AS "NATION_NAME", "SUPPLIER_COUNT", "TOTAL_SUPPLY_COST_PER_NATION", "LINE_ITEM_COUNT", "TOTAL_ORDER_VALUE", "O_ORDERSTATUS"
FROM "s1"
ORDER BY "TOTAL_ORDER_VALUE" DESC NULLS FIRST, "SUPPLIER_COUNT") AS "t13"