SELECT COALESCE("CUSTOMER_NAME", "CUSTOMER_NAME") AS "CUSTOMER_NAME", "TOTAL_REVENUE", "NATION_NAME", "O_ORDERDATE", "o_orderdate" AS "o_orderdate_"
FROM (SELECT "CUSTOMER_NAME", "TOTAL_REVENUE", "NATION_NAME", "O_ORDERDATE", "O_ORDERDATE" AS "o_orderdate"
FROM "s1"
ORDER BY "TOTAL_REVENUE" DESC NULLS FIRST, "O_ORDERDATE" DESC NULLS FIRST) AS "t6"