SELECT COALESCE("NATION_NAME", "NATION_NAME") AS "NATION_NAME", "TOTAL_REVENUE", "REGION_NAME"
FROM (SELECT "NATION_NAME", "TOTAL_REVENUE", "REGION_NAME"
FROM "s1"
ORDER BY "TOTAL_REVENUE" DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY) AS "t5"