SELECT COALESCE("region"."r_regionkey", "region"."r_regionkey") AS "r_regionkey", "region"."r_name", "region"."r_comment", "nation"."n_nationkey", "nation"."n_name", "nation"."n_regionkey", "nation"."n_comment", "supplier"."s_suppkey", "supplier"."s_name", "supplier"."s_address", "supplier"."s_nationkey", "supplier"."s_phone", "supplier"."s_acctbal", "supplier"."s_comment", "t3"."p_partkey", "t3"."p_name", "t3"."p_mfgr", "t3"."p_brand", "t3"."p_type", "t3"."p_size", "t3"."p_container", "t3"."p_retailprice", "t3"."p_comment", "t3"."S_SUPPKEY" AS "S_SUPPKEY_", "t3"."S_NAME" AS "S_NAME_", "t3"."S_NATIONKEY" AS "S_NATIONKEY_", "t3"."TOTAL_SUPPLY_COST", "t5"."n_nationkey" AS "N_NATIONKEY_", "t5"."n_name" AS "N_NAME_", "t5"."CUSTOMER_COUNT", "t5"."TOTAL_ORDER_VALUE"
FROM "TPCH"."region"
INNER JOIN "TPCH"."nation" ON "region"."r_regionkey" = "nation"."n_regionkey"
INNER JOIN "TPCH"."supplier" ON "nation"."n_nationkey" = "supplier"."s_nationkey"
INNER JOIN (SELECT "part"."p_partkey", "part"."p_name", "part"."p_mfgr", "part"."p_brand", "part"."p_type", "part"."p_size", "part"."p_container", "part"."p_retailprice", "part"."p_comment", "t2"."S_SUPPKEY", "t2"."S_NAME", "t2"."S_NATIONKEY", "t2"."TOTAL_SUPPLY_COST"
FROM (SELECT "supplier0"."s_suppkey" AS "S_SUPPKEY", "supplier0"."s_name" AS "S_NAME", "supplier0"."s_nationkey" AS "S_NATIONKEY", SUM("partsupp"."ps_supplycost" * "partsupp"."ps_availqty") AS "TOTAL_SUPPLY_COST", SUM("partsupp"."ps_supplycost" * "partsupp"."ps_availqty") > 10000.00 AS "$f4"
FROM "TPCH"."supplier" AS "supplier0"
INNER JOIN "TPCH"."partsupp" ON "supplier0"."s_suppkey" = "partsupp"."ps_suppkey"
GROUP BY "supplier0"."s_suppkey", "supplier0"."s_name", "supplier0"."s_nationkey"
HAVING SUM("partsupp"."ps_supplycost" * "partsupp"."ps_availqty") > 10000.00) AS "t2",
"TPCH"."part") AS "t3" ON "supplier"."s_suppkey" = "t3"."p_partkey"
INNER JOIN (SELECT "t4"."n_nationkey", "t4"."n_name", COUNT(DISTINCT "t4"."c_custkey") AS "CUSTOMER_COUNT", SUM("orders"."o_totalprice") AS "TOTAL_ORDER_VALUE"
FROM "TPCH"."orders"
RIGHT JOIN (SELECT "nation0"."n_nationkey", "nation0"."n_name", "nation0"."n_regionkey", "nation0"."n_comment", "customer"."c_custkey", "customer"."c_name", "customer"."c_address", "customer"."c_nationkey", "customer"."c_phone", "customer"."c_acctbal", "customer"."c_mktsegment", "customer"."c_comment"
FROM "TPCH"."customer"
RIGHT JOIN "TPCH"."nation" AS "nation0" ON "customer"."c_nationkey" = "nation0"."n_nationkey") AS "t4" ON "orders"."o_custkey" = "t4"."c_custkey"
GROUP BY "t4"."n_nationkey", "t4"."n_name") AS "t5" ON "nation"."n_nationkey" = "t5"."n_nationkey"