SELECT COALESCE("SUPPLIER_NAME", "SUPPLIER_NAME") AS "SUPPLIER_NAME", "REGION", "NATION", "TOTAL_ORDERS"
FROM (SELECT "SUPPLIER_NAME", "REGION", "NATION", "TOTAL_ORDERS"
FROM "s1"
ORDER BY "TOTAL_ORDERS" DESC NULLS FIRST) AS "t9"