SELECT COALESCE("t3"."TOTALPOSTS", "t3"."TOTALPOSTS") AS "TOTALPOSTS", "t3"."TOTALUSERS", "t3"."AVGVIEWCOUNT", "t3"."AVGSCORE", "s1"."TOTALUSERS" AS "TOTALUSERS0", "s1"."AVGREPUTATION", "s1"."AVGUPVOTES", "s1"."AVGDOWNVOTES", "s1"."TOTALVOTES", "s1"."TOTALPOSTVOTES", "s1"."AVGUPVOTES0", "s1"."AVGDOWNVOTES0"
FROM (SELECT COUNT(*) AS "TOTALPOSTS", COUNT(DISTINCT "OwnerUserId") AS "TOTALUSERS", AVG("ViewCount") AS "AVGVIEWCOUNT", AVG("Score") AS "AVGSCORE"
FROM "STACK"."Posts") AS "t3",
"s1"