SELECT COALESCE("t"."TOTALUSERS", "t"."TOTALUSERS") AS "TOTALUSERS", "t"."AVGREPUTATION", "t"."AVGUPVOTES", "t"."AVGDOWNVOTES", "t1"."TOTALVOTES", "t1"."TOTALPOSTVOTES", "t1"."AVGUPVOTES" AS "AVGUPVOTES0", "t1"."AVGDOWNVOTES" AS "AVGDOWNVOTES0"
FROM (SELECT COUNT(*) AS "TOTALUSERS", AVG("Reputation") AS "AVGREPUTATION", AVG("UpVotes") AS "AVGUPVOTES", AVG("DownVotes") AS "AVGDOWNVOTES"
FROM "STACK"."Users") AS "t",
(SELECT COUNT(*) AS "TOTALVOTES", COUNT(DISTINCT "PostId") AS "TOTALPOSTVOTES", AVG(CASE WHEN CAST("VoteTypeId" AS INTEGER) = 2 THEN 1 ELSE 0 END) AS "AVGUPVOTES", AVG(CASE WHEN CAST("VoteTypeId" AS INTEGER) = 3 THEN 1 ELSE 0 END) AS "AVGDOWNVOTES"
FROM "STACK"."Votes") AS "t1"