SELECT COALESCE("t2"."POSTID", "t2"."POSTID") AS "POSTID", "t2"."TITLE", "t2"."OWNERDISPLAYNAME", "t2"."POSTCREATIONDATE", "t2"."SCORE", "t2"."VIEWCOUNT", "t2"."COMMENTCOUNT", "t2"."HISTORYCOUNT", COUNT("Votes"."Id") AS "VOTECOUNT"
FROM "STACK"."Votes"
RIGHT JOIN (SELECT ANY_VALUE("Id") AS "POSTID", "TITLE", "BODY", ANY_VALUE("DisplayName") AS "OWNERDISPLAYNAME", ANY_VALUE("CreationDate") AS "POSTCREATIONDATE", "SCORE", "VIEWCOUNT", COUNT("FD_COL_7") AS "COMMENTCOUNT", COUNT("Id2") AS "HISTORYCOUNT"
FROM "s1"
GROUP BY "Id", "TITLE", "BODY", "DisplayName", "CreationDate", "SCORE", "VIEWCOUNT") AS "t2" ON "Votes"."PostId" = "t2"."POSTID"
GROUP BY "t2"."POSTID", "t2"."TITLE", "t2"."OWNERDISPLAYNAME", "t2"."POSTCREATIONDATE", "t2"."SCORE", "t2"."VIEWCOUNT", "t2"."COMMENTCOUNT", "t2"."HISTORYCOUNT"
ORDER BY "t2"."SCORE" DESC NULLS FIRST, "t2"."VIEWCOUNT" DESC NULLS FIRST
FETCH NEXT 100 ROWS ONLY