SELECT COALESCE("POSTTYPE", "POSTTYPE") AS "POSTTYPE", "TOTALPOSTS", "POSITIVESCOREDPOSTS", "TOTALVIEWS", "AVERAGESCORE", "AVERAGEANSWERCOUNT", "AVERAGECOMMENTCOUNT", "UNIQUEPOSTOWNERS", "AVERAGEUSERREPUTATION"
FROM (SELECT "POSTTYPE", "TOTALPOSTS", "POSITIVESCOREDPOSTS", "TOTALVIEWS", "AVERAGESCORE", "AVERAGEANSWERCOUNT", "AVERAGECOMMENTCOUNT", "UNIQUEPOSTOWNERS", "AVERAGEUSERREPUTATION"
FROM "s1"
ORDER BY "TOTALPOSTS" DESC NULLS FIRST) AS "t3"