SELECT COALESCE("t6"."POSTID", "t6"."POSTID") AS "POSTID", "t6"."POSTTYPE", "t6"."COMMENTCOUNT", "t6"."VOTECOUNT", "t6"."AVGUSERREPUTATION", "t6"."HISTORYCOUNT", "t6"."CLOSECOUNT", "t6"."REOPENCOUNT"
FROM (SELECT "t2"."POSTID", "t2"."POSTTYPE", "t2"."COMMENTCOUNT", "t2"."VOTECOUNT", "t2"."AVGUSERREPUTATION", "t4"."HISTORYCOUNT", "t4"."CLOSECOUNT", "t4"."REOPENCOUNT"
FROM (SELECT ANY_VALUE("t0"."Id") AS "POSTID", ANY_VALUE("t0"."Name") AS "POSTTYPE", COUNT("t0"."Id1") AS "COMMENTCOUNT", COUNT(DISTINCT "Votes"."UserId") AS "VOTECOUNT", AVG("Users"."Reputation") AS "AVGUSERREPUTATION"
FROM (SELECT "s1"."Id", "s1"."PostTypeId", "s1"."AcceptedAnswerId", "s1"."ParentId", "s1"."CreationDate", "s1"."Score", "s1"."ViewCount", "s1"."Body", "s1"."OwnerUserId", "s1"."OwnerDisplayName", "s1"."LastEditorUserId", "s1"."LastEditorDisplayName", "s1"."LastEditDate", "s1"."LastActivityDate", "s1"."Title", "s1"."Tags", "s1"."AnswerCount", "s1"."CommentCount", "s1"."FavoriteCount", "s1"."ClosedDate", "s1"."CommunityOwnedDate", "s1"."ContentLicense", "s1"."Id0", "s1"."Name", "Comments"."Id" AS "Id1", "Comments"."PostId", "Comments"."Score" AS "Score0", "Comments"."Text", "Comments"."CreationDate" AS "CreationDate0", "Comments"."UserDisplayName", "Comments"."UserId", "Comments"."ContentLicense" AS "ContentLicense0"
FROM "STACK"."Comments"
RIGHT JOIN "s1" ON "Comments"."PostId" = "s1"."Id") AS "t0"
LEFT JOIN "STACK"."Votes" ON "t0"."Id" = "Votes"."PostId"
LEFT JOIN "STACK"."Users" ON "Votes"."UserId" = "Users"."Id"
GROUP BY "t0"."Id", "t0"."Name") AS "t2"
LEFT JOIN (SELECT "PostId" AS "POSTID", COUNT(*) AS "HISTORYCOUNT", COUNT(CASE WHEN CAST("PostHistoryTypeId" AS INTEGER) = 10 THEN 1 ELSE NULL END) AS "CLOSECOUNT", COUNT(CASE WHEN CAST("PostHistoryTypeId" AS INTEGER) = 11 THEN 1 ELSE NULL END) AS "REOPENCOUNT"
FROM "STACK"."PostHistory"
GROUP BY "PostId") AS "t4" ON "t2"."POSTID" = "t4"."POSTID"
ORDER BY "t2"."VOTECOUNT" DESC NULLS FIRST, "t2"."COMMENTCOUNT" DESC NULLS FIRST) AS "t6"