SELECT COALESCE("t3"."POSTID", "t3"."POSTID") AS "POSTID", "t3"."TITLE", "t3"."CREATIONDATE", "t3"."OWNERDISPLAYNAME", "t3"."UPVOTES", "t3"."DOWNVOTES", "t3"."VOTECOUNT"
FROM (SELECT "s1"."Id" AS "POSTID", "s1"."Title" AS "TITLE", "s1"."CreationDate" AS "CREATIONDATE", "s1"."DisplayName" AS "OWNERDISPLAYNAME", CASE WHEN "t1"."UPVOTES" IS NOT NULL THEN CAST("t1"."UPVOTES" AS INTEGER) ELSE 0 END AS "UPVOTES", CASE WHEN "t1"."DOWNVOTES" IS NOT NULL THEN CAST("t1"."DOWNVOTES" AS INTEGER) ELSE 0 END AS "DOWNVOTES", CASE WHEN "t1"."VOTECOUNT" IS NOT NULL THEN CAST("t1"."VOTECOUNT" AS BIGINT) ELSE 0 END AS "VOTECOUNT"
FROM "s1"
LEFT JOIN (SELECT "PostId" AS "POSTID", SUM(CASE WHEN CAST("VoteTypeId" AS INTEGER) = 2 THEN 1 ELSE 0 END) AS "UPVOTES", SUM(CASE WHEN CAST("VoteTypeId" AS INTEGER) = 3 THEN 1 ELSE 0 END) AS "DOWNVOTES", COUNT(*) AS "VOTECOUNT"
FROM "STACK"."Votes"
GROUP BY "PostId") AS "t1" ON "s1"."Id" = "t1"."POSTID"
ORDER BY "s1"."CreationDate" DESC NULLS FIRST
FETCH NEXT 100 ROWS ONLY) AS "t3"