SELECT COALESCE("t7"."POSTTYPE", "t7"."POSTTYPE") AS "POSTTYPE", "t7"."POSTCOUNT", "t7"."AVGVIEWS", "t7"."AVGSCORE", "t7"."TOPUSER", "t7"."REPUTATION", "t7"."TOTALPOSTS"
FROM (SELECT "t5"."POSTTYPE", "t5"."POSTCOUNT", "t5"."AVGVIEWS", "t5"."AVGSCORE", "t3"."DISPLAYNAME" AS "TOPUSER", "t3"."REPUTATION", "t3"."TOTALPOSTS"
FROM (SELECT ANY_VALUE("Users"."Id") AS "USERID", "Users"."DisplayName" AS "DISPLAYNAME", "Users"."Reputation" AS "REPUTATION", COUNT("Posts0"."Id") AS "TOTALPOSTS"
FROM "STACK"."Posts" AS "Posts0"
RIGHT JOIN "STACK"."Users" ON "Posts0"."OwnerUserId" = "Users"."Id"
GROUP BY "Users"."Id", "Users"."Reputation", "Users"."DisplayName"
ORDER BY "Users"."Reputation" DESC NULLS FIRST
FETCH NEXT 5 ROWS ONLY) AS "t3",
(SELECT ANY_VALUE("Name") AS "POSTTYPE", COUNT(*) AS "POSTCOUNT", AVG("ViewCount") AS "AVGVIEWS", AVG("Score") AS "AVGSCORE"
FROM "s1"
GROUP BY "Name") AS "t5"
ORDER BY "t5"."POSTCOUNT" DESC NULLS FIRST) AS "t7"