SELECT COALESCE("t2"."POSTTYPE", "t2"."POSTTYPE") AS "POSTTYPE", "t2"."TOTALPOSTS", "t2"."AVERAGESCORE", "t2"."UNIQUEUSERS", "t2"."TOTALVIEWS", "t2"."TOTALCOMMENTS", "t2"."TOTALANSWERS", "t4"."USERID", "t4"."DISPLAYNAME", "t4"."POSTSCREATED", "t4"."TOTALBOUNTYRECEIVED"
FROM (SELECT ANY_VALUE("PostTypes"."Name") AS "POSTTYPE", COUNT(*) AS "TOTALPOSTS", AVG("Posts0"."Score") AS "AVERAGESCORE", COUNT(DISTINCT "Posts0"."OwnerUserId") AS "UNIQUEUSERS", SUM("Posts0"."ViewCount") AS "TOTALVIEWS", SUM("Posts0"."CommentCount") AS "TOTALCOMMENTS", SUM("Posts0"."AnswerCount") AS "TOTALANSWERS"
FROM "STACK"."PostTypes"
INNER JOIN "STACK"."Posts" AS "Posts0" ON "PostTypes"."Id" = "Posts0"."PostTypeId"
GROUP BY "PostTypes"."Name") AS "t2"
INNER JOIN (SELECT ANY_VALUE("Id0") AS "USERID", "DisplayName" AS "DISPLAYNAME", COUNT("Id00") AS "POSTSCREATED", SUM("BountyAmount") AS "TOTALBOUNTYRECEIVED"
FROM "s1"
GROUP BY "Id0", "DisplayName") AS "t4" ON "t2"."UNIQUEUSERS" = "t4"."POSTSCREATED"
ORDER BY "t2"."TOTALPOSTS" DESC NULLS FIRST