SELECT COALESCE("PostId", "PostId") AS "POSTID", COUNT(CASE WHEN CAST("PostHistoryTypeId" AS INTEGER) = 10 THEN 1 ELSE NULL END) AS "CLOSECOUNT", COUNT(CASE WHEN CAST("PostHistoryTypeId" AS INTEGER) = 11 THEN 1 ELSE NULL END) AS "REOPENCOUNT"
FROM "STACK"."PostHistory"
GROUP BY "PostId"