SELECT COALESCE("t10"."USERID", "t10"."USERID") AS "USERID", "t10"."REPUTATION", "t10"."POSTCOUNT", "t10"."TOTALSCORE", "t10"."TOTALCOMMENTS", "t10"."POSTID", "t10"."TITLE", "t10"."CREATIONDATE", "t10"."POSTTYPE", "t10"."UPVOTES", "t10"."DOWNVOTES"
FROM (SELECT "t8"."USERID", "t8"."REPUTATION", "t8"."POSTCOUNT", "t8"."TOTALSCORE", "t8"."TOTALCOMMENTS", "t2"."POSTID", "t2"."TITLE", "t2"."CREATIONDATE", "t2"."POSTTYPE", "t2"."UPVOTES", "t2"."DOWNVOTES"
FROM (SELECT "Posts"."Id" AS "POSTID", "Posts"."Title" AS "TITLE", "Posts"."CreationDate" AS "CREATIONDATE", "PostTypes"."Name" AS "POSTTYPE", CASE WHEN "s1"."UPVOTES" IS NOT NULL THEN CAST("s1"."UPVOTES" AS INTEGER) ELSE 0 END AS "UPVOTES", CASE WHEN "s1"."DOWNVOTES" IS NOT NULL THEN CAST("s1"."DOWNVOTES" AS INTEGER) ELSE 0 END AS "DOWNVOTES", "Posts"."OwnerUserId" AS "OWNERUSERID"
FROM "s1"
RIGHT JOIN ("STACK"."Posts" INNER JOIN "STACK"."PostTypes" ON "Posts"."PostTypeId" = "PostTypes"."Id") ON "s1"."POSTID" = "Posts"."Id") AS "t2"
INNER JOIN (SELECT ANY_VALUE("t4"."Id") AS "USERID", "t4"."Reputation" AS "REPUTATION", COUNT(DISTINCT "t4"."Id0") AS "POSTCOUNT", SUM(CASE WHEN "t4"."Score" IS NOT NULL THEN CAST("t4"."Score" AS INTEGER) ELSE 0 END) AS "TOTALSCORE", SUM(CASE WHEN "t5"."COMMENTCOUNT" IS NOT NULL THEN CAST("t5"."COMMENTCOUNT" AS BIGINT) ELSE 0 END) AS "TOTALCOMMENTS"
FROM (SELECT "t3"."Id", "t3"."Reputation", "t3"."CreationDate", "t3"."DisplayName", "t3"."LastAccessDate", "t3"."WebsiteUrl", "t3"."Location", "t3"."AboutMe", "t3"."Views", "t3"."UpVotes", "t3"."DownVotes", "t3"."ProfileImageUrl", "t3"."AccountId", "Posts0"."Id" AS "Id0", "Posts0"."PostTypeId", "Posts0"."AcceptedAnswerId", "Posts0"."ParentId", "Posts0"."CreationDate" AS "CreationDate0", "Posts0"."Score", "Posts0"."ViewCount", "Posts0"."Body", "Posts0"."OwnerUserId", "Posts0"."OwnerDisplayName", "Posts0"."LastEditorUserId", "Posts0"."LastEditorDisplayName", "Posts0"."LastEditDate", "Posts0"."LastActivityDate", "Posts0"."Title", "Posts0"."Tags", "Posts0"."AnswerCount", "Posts0"."CommentCount", "Posts0"."FavoriteCount", "Posts0"."ClosedDate", "Posts0"."CommunityOwnedDate", "Posts0"."ContentLicense"
FROM "STACK"."Posts" AS "Posts0"
RIGHT JOIN (SELECT *
FROM "STACK"."Users"
WHERE "Reputation" > 0) AS "t3" ON "Posts0"."OwnerUserId" = "t3"."Id") AS "t4"
LEFT JOIN (SELECT "PostId", COUNT(*) AS "COMMENTCOUNT"
FROM "STACK"."Comments"
GROUP BY "PostId") AS "t5" ON "t4"."Id0" = "t5"."PostId"
GROUP BY "t4"."Id", "t4"."Reputation") AS "t8" ON "t2"."OWNERUSERID" = "t8"."USERID"
ORDER BY "t8"."REPUTATION" DESC NULLS FIRST, "t8"."TOTALSCORE" DESC NULLS FIRST, "t2"."UPVOTES" DESC NULLS FIRST) AS "t10"