SELECT COALESCE("t8"."POSTTYPE", "t8"."POSTTYPE") AS "POSTTYPE", "t8"."TOTALPOSTS", "t8"."TOTALQUESTIONS", "t8"."TOTALANSWERS", "t8"."TOTALVIEWS", "t8"."AVGSCORE", "t8"."AVGANSWERSPERQUESTION", "t8"."TOTALUSERS", "t8"."TOTALREPUTATION", "t8"."AVGREPUTATION", "t8"."ACTIVEUSERS", "t8"."RECENTUSERS", "t8"."TOTALCOMMENTS", "t8"."AVGCOMMENTLENGTH", "t8"."POSITIVECOMMENTS"
FROM (SELECT "t6"."POSTTYPE", "t6"."TOTALPOSTS", "t6"."TOTALQUESTIONS", "t6"."TOTALANSWERS", "t6"."TOTALVIEWS", "t6"."AVGSCORE", "t6"."AVGANSWERSPERQUESTION", "t3"."TOTALUSERS", "t3"."TOTALREPUTATION", "t3"."AVGREPUTATION", "t3"."ACTIVEUSERS", "t3"."RECENTUSERS", "s1"."TOTALCOMMENTS", "s1"."AVGCOMMENTLENGTH", "s1"."POSITIVECOMMENTS"
FROM (SELECT COUNT(*) AS "TOTALUSERS", SUM("Reputation") AS "TOTALREPUTATION", AVG("Reputation") AS "AVGREPUTATION", COUNT(DISTINCT CASE WHEN "UpVotes" > 0 THEN "Id" ELSE NULL END) AS "ACTIVEUSERS", SUM(CASE WHEN "LastAccessDate" > CAST((DATE '2024-10-01' - INTERVAL '30' DAY) AS TIMESTAMP(0)) THEN 1 ELSE 0 END) AS "RECENTUSERS"
FROM "STACK"."Users") AS "t3",
"s1",
(SELECT ANY_VALUE("PostTypes"."Name") AS "POSTTYPE", COUNT(*) AS "TOTALPOSTS", SUM(CASE WHEN CAST("Posts"."PostTypeId" AS INTEGER) = 1 THEN 1 ELSE 0 END) AS "TOTALQUESTIONS", SUM(CASE WHEN CAST("Posts"."PostTypeId" AS INTEGER) = 2 THEN 1 ELSE 0 END) AS "TOTALANSWERS", SUM("Posts"."ViewCount") AS "TOTALVIEWS", AVG("Posts"."Score") AS "AVGSCORE", AVG("Posts"."AnswerCount") AS "AVGANSWERSPERQUESTION"
FROM "STACK"."PostTypes"
INNER JOIN "STACK"."Posts" ON "PostTypes"."Id" = "Posts"."PostTypeId"
GROUP BY "PostTypes"."Name") AS "t6"
ORDER BY "t6"."TOTALPOSTS" DESC NULLS FIRST) AS "t8"