SELECT COALESCE("USERID", "USERID") AS "USERID", "DISPLAYNAME", "TOTALPOSTS", "TOTALQUESTIONS", "TOTALANSWERS", "TOTALCOMMENTS", "TOTALVOTES", "ENGAGEMENTSCORE"
FROM (SELECT ANY_VALUE("Id") AS "USERID", "DISPLAYNAME", COUNT("Id0") AS "TOTALPOSTS", SUM("FD_COL_3") AS "TOTALQUESTIONS", SUM("FD_COL_4") AS "TOTALANSWERS", SUM("FD_COL_5") AS "TOTALCOMMENTS", SUM("FD_COL_6") AS "TOTALVOTES", COUNT("Id0") + SUM("FD_COL_5") + SUM("FD_COL_6") AS "ENGAGEMENTSCORE"
FROM "s1"
GROUP BY "Id", "DISPLAYNAME"
ORDER BY 8 DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY) AS "t6"