SELECT COALESCE("t16"."DISPLAYNAME", "t16"."DISPLAYNAME") AS "DISPLAYNAME", "t16"."TITLE", "t16"."USERTOTALVOTES", "t16"."POSTTOTALVOTES", "t16"."TOTALCOMMENTS", "t16"."POSTUPVOTES", "t16"."POSTDOWNVOTES"
FROM (SELECT "t6"."DISPLAYNAME", "t12"."TITLE", "t10"."TOTALVOTES" AS "USERTOTALVOTES", "t14"."TOTALVOTES" AS "POSTTOTALVOTES", "t14"."TOTALCOMMENTS", "t14"."UPVOTES" AS "POSTUPVOTES", "t14"."DOWNVOTES" AS "POSTDOWNVOTES"
FROM (SELECT ANY_VALUE("t3"."Id") AS "USERID", "t3"."DisplayName" AS "DISPLAYNAME", COUNT(DISTINCT "t3"."Id0") AS "TOTALVOTES", SUM(CASE WHEN "VoteTypes0"."Name" = 'UpMod' THEN 1 ELSE 0 END) AS "UPVOTES", SUM(CASE WHEN "VoteTypes0"."Name" = 'DownMod' THEN 1 ELSE 0 END) AS "DOWNVOTES"
FROM (SELECT "Users"."Id", "Users"."Reputation", "Users"."CreationDate", "Users"."DisplayName", "Users"."LastAccessDate", "Users"."WebsiteUrl", "Users"."Location", "Users"."AboutMe", "Users"."Views", "Users"."UpVotes", "Users"."DownVotes", "Users"."ProfileImageUrl", "Users"."AccountId", "Votes0"."Id" AS "Id0", "Votes0"."PostId", "Votes0"."VoteTypeId", "Votes0"."UserId", "Votes0"."CreationDate" AS "CreationDate0", "Votes0"."BountyAmount"
FROM "STACK"."Votes" AS "Votes0"
RIGHT JOIN "STACK"."Users" ON "Votes0"."UserId" = "Users"."Id") AS "t3"
LEFT JOIN "STACK"."VoteTypes" AS "VoteTypes0" ON "t3"."VoteTypeId" = "VoteTypes0"."Id"
GROUP BY "t3"."Id", "t3"."DisplayName") AS "t6"
INNER JOIN (SELECT ANY_VALUE("t7"."Id") AS "USERID", "t7"."DisplayName" AS "DISPLAYNAME", COUNT(DISTINCT "t7"."Id0") AS "TOTALVOTES", SUM(CASE WHEN "VoteTypes1"."Name" = 'UpMod' THEN 1 ELSE 0 END) AS "UPVOTES", SUM(CASE WHEN "VoteTypes1"."Name" = 'DownMod' THEN 1 ELSE 0 END) AS "DOWNVOTES"
FROM (SELECT "Users0"."Id", "Users0"."Reputation", "Users0"."CreationDate", "Users0"."DisplayName", "Users0"."LastAccessDate", "Users0"."WebsiteUrl", "Users0"."Location", "Users0"."AboutMe", "Users0"."Views", "Users0"."UpVotes", "Users0"."DownVotes", "Users0"."ProfileImageUrl", "Users0"."AccountId", "Votes1"."Id" AS "Id0", "Votes1"."PostId", "Votes1"."VoteTypeId", "Votes1"."UserId", "Votes1"."CreationDate" AS "CreationDate0", "Votes1"."BountyAmount"
FROM "STACK"."Votes" AS "Votes1"
RIGHT JOIN "STACK"."Users" AS "Users0" ON "Votes1"."UserId" = "Users0"."Id") AS "t7"
LEFT JOIN "STACK"."VoteTypes" AS "VoteTypes1" ON "t7"."VoteTypeId" = "VoteTypes1"."Id"
GROUP BY "t7"."Id", "t7"."DisplayName") AS "t10" ON "t6"."USERID" = "t10"."USERID"
INNER JOIN ((SELECT ANY_VALUE("Id") AS "POSTID", "TITLE", COUNT(DISTINCT "Id0") AS "TOTALCOMMENTS", COUNT(DISTINCT "Id1") AS "TOTALVOTES", SUM("FD_COL_4") AS "UPVOTES", SUM("FD_COL_5") AS "DOWNVOTES"
FROM "s1"
GROUP BY "Id", "TITLE") AS "t12" INNER JOIN (SELECT ANY_VALUE("Id") AS "POSTID", "TITLE", COUNT(DISTINCT "Id0") AS "TOTALCOMMENTS", COUNT(DISTINCT "Id1") AS "TOTALVOTES", SUM("FD_COL_4") AS "UPVOTES", SUM("FD_COL_5") AS "DOWNVOTES"
FROM "s1"
GROUP BY "Id", "TITLE") AS "t14" ON "t12"."POSTID" = "t14"."POSTID") ON "t6"."USERID" = "t12"."POSTID"
ORDER BY "t10"."TOTALVOTES" DESC NULLS FIRST, "t14"."TOTALVOTES" DESC NULLS FIRST) AS "t16"