SELECT COALESCE("t5"."POSTTYPENAME", "t5"."POSTTYPENAME") AS "POSTTYPENAME", "t5"."POSTCOUNT", "t5"."AVGSCORE", "t5"."USERCOUNT", "t5"."VOTETYPENAME", "t5"."VOTECOUNT"
FROM (SELECT "t3"."POSTTYPENAME", "t3"."POSTCOUNT", "t3"."AVGSCORE", "t3"."USERCOUNT", "s1"."VOTETYPENAME", "s1"."VOTECOUNT"
FROM "s1",
(SELECT ANY_VALUE("PostTypes"."Name") AS "POSTTYPENAME", COUNT(*) AS "POSTCOUNT", AVG("Posts"."Score") AS "AVGSCORE", COUNT(DISTINCT "Votes0"."UserId") AS "USERCOUNT"
FROM "STACK"."Votes" AS "Votes0"
RIGHT JOIN ("STACK"."Posts" INNER JOIN "STACK"."PostTypes" ON "Posts"."PostTypeId" = "PostTypes"."Id") ON "Votes0"."PostId" = "Posts"."Id"
GROUP BY "PostTypes"."Name") AS "t3"
ORDER BY "t3"."POSTTYPENAME", "s1"."VOTETYPENAME") AS "t5"