SELECT COALESCE("t8"."USERID", "t8"."USERID") AS "USERID", "t8"."DISPLAYNAME", "t8"."TOTALPOSTS0", "t8"."TOTALCOMMENTS0", "t8"."TOTALUPVOTES", "t8"."TOTALDOWNVOTES", "t8"."LASTPOSTDATE", "t8"."POSTTYPE", "t8"."TOTALPOSTS", "t8"."AVERAGESCORE", "t8"."AVERAGEVIEWCOUNT", "t8"."TOTALANSWERS", "t8"."TOTALCOMMENTS"
FROM (SELECT "s1"."USERID", "s1"."DISPLAYNAME", "s1"."TOTALPOSTS" AS "TOTALPOSTS0", "s1"."TOTALCOMMENTS" AS "TOTALCOMMENTS0", "s1"."TOTALUPVOTES", "s1"."TOTALDOWNVOTES", "s1"."LASTPOSTDATE", "t6"."POSTTYPE", "t6"."TOTALPOSTS", "t6"."AVERAGESCORE", "t6"."AVERAGEVIEWCOUNT", "t6"."TOTALANSWERS", "t6"."TOTALCOMMENTS"
FROM (SELECT ANY_VALUE("PostTypes"."Name") AS "POSTTYPE", COUNT(*) AS "TOTALPOSTS", AVG("Posts0"."Score") AS "AVERAGESCORE", AVG("Posts0"."ViewCount") AS "AVERAGEVIEWCOUNT", SUM("Posts0"."AnswerCount") AS "TOTALANSWERS", SUM("Posts0"."CommentCount") AS "TOTALCOMMENTS"
FROM "STACK"."PostTypes"
INNER JOIN "STACK"."Posts" AS "Posts0" ON "PostTypes"."Id" = "Posts0"."PostTypeId"
GROUP BY "PostTypes"."Name") AS "t6",
"s1"
ORDER BY "s1"."TOTALPOSTS" DESC NULLS FIRST, "s1"."TOTALUPVOTES" DESC NULLS FIRST) AS "t8"