SELECT COALESCE("POSTTYPEID", "POSTTYPEID") AS "POSTTYPEID", "POSTCOUNT", "AVGSCORE", "TOTALVIEWS", "TOTALANSWERS", "TOTALCOMMENTS", "TOTALFAVORITES", "LASTPOSTDATE", "TOTALUSERPOSTS", "AVGUSERREPUTATION", "TOTALUSERUPVOTES", "TOTALUSERDOWNVOTES"
FROM "s1"
ORDER BY "POSTTYPEID"