SELECT COALESCE("t5"."USERID", "t5"."USERID") AS "USERID", "t5"."DISPLAYNAME", "t5"."REPUTATION", "t5"."TOTALPOSTS", "t5"."TOTALCOMMENTS", "t5"."TOTALUPVOTES", "t5"."TOTALDOWNVOTES", "t5"."TOTALBADGES", "t5"."REPUTATION" AS "Reputation_"
FROM (SELECT "s1"."Id", "s1"."DisplayName" AS "DISPLAYNAME", "s1"."Reputation" AS "REPUTATION", ANY_VALUE("s1"."Id") AS "USERID", COUNT(DISTINCT "s1"."Id0") AS "TOTALPOSTS", COUNT(DISTINCT "s1"."Id1") AS "TOTALCOMMENTS", SUM(CASE WHEN CAST("Votes"."VoteTypeId" AS INTEGER) = 2 THEN 1 ELSE 0 END) AS "TOTALUPVOTES", SUM(CASE WHEN CAST("Votes"."VoteTypeId" AS INTEGER) = 3 THEN 1 ELSE 0 END) AS "TOTALDOWNVOTES", SUM(CASE WHEN "Badges"."Id" IS NOT NULL THEN 1 ELSE 0 END) AS "TOTALBADGES"
FROM "s1"
LEFT JOIN "STACK"."Votes" ON "s1"."Id0" = "Votes"."PostId"
LEFT JOIN "STACK"."Badges" ON "s1"."Id" = "Badges"."UserId"
GROUP BY "s1"."Id", "s1"."DisplayName", "s1"."Reputation"
ORDER BY 5 DESC NULLS FIRST, "s1"."Reputation" DESC NULLS FIRST
FETCH NEXT 100 ROWS ONLY) AS "t5"