SELECT COALESCE("t5"."DISPLAYNAME", "t5"."DISPLAYNAME") AS "DISPLAYNAME", "t5"."POSTCOUNT", "t5"."VOTECOUNT", "t5"."COMMENTCOUNT"
FROM (SELECT "Users0"."DisplayName" AS "DISPLAYNAME", "s1"."POSTCOUNT", "s1"."VOTECOUNT", "s1"."COMMENTCOUNT"
FROM "STACK"."Users" AS "Users0"
INNER JOIN "s1" ON "Users0"."Id" = "s1"."USERID"
ORDER BY "s1"."POSTCOUNT" DESC NULLS FIRST, "s1"."VOTECOUNT" DESC NULLS FIRST, "s1"."COMMENTCOUNT" DESC NULLS FIRST
FETCH NEXT 100 ROWS ONLY) AS "t5"