SELECT COALESCE("USERID", "USERID") AS "USERID", "DISPLAYNAME", "TOTALPOSTS", "AVERAGESCORE", "TOTALCOMMENTS"
FROM (SELECT "USERID", "DISPLAYNAME", "TOTALPOSTS", "AVERAGESCORE", "TOTALCOMMENTS"
FROM "s1"
ORDER BY "TOTALPOSTS" DESC NULLS FIRST, "AVERAGESCORE" DESC NULLS FIRST) AS "t4"