SELECT COALESCE("t7"."USERID", "t7"."USERID") AS "USERID", "t7"."DISPLAYNAME", "t7"."POSTCOUNT", "t7"."QUESTIONCOUNT", "t7"."ANSWERCOUNT", "t7"."TOTALVIEWS", "t7"."AVERAGESCORE", "t7"."POSTTYPE", "t7"."TOTALPOSTS", "t7"."AVERAGEVIEWS", "t7"."AVERAGESCORE0"
FROM (SELECT "s1"."USERID", "s1"."DISPLAYNAME", "s1"."POSTCOUNT", "s1"."QUESTIONCOUNT", "s1"."ANSWERCOUNT", "s1"."TOTALVIEWS", "s1"."AVERAGESCORE", "t5"."POSTTYPE", "t5"."TOTALPOSTS", "t5"."AVERAGEVIEWS", "t5"."AVERAGESCORE" AS "AVERAGESCORE0"
FROM (SELECT ANY_VALUE("PostTypes"."Name") AS "POSTTYPE", COUNT(*) AS "TOTALPOSTS", AVG("Posts0"."ViewCount") AS "AVERAGEVIEWS", AVG("Posts0"."Score") AS "AVERAGESCORE"
FROM "STACK"."PostTypes"
INNER JOIN "STACK"."Posts" AS "Posts0" ON "PostTypes"."Id" = "Posts0"."PostTypeId"
GROUP BY "PostTypes"."Name") AS "t5",
"s1"
ORDER BY "s1"."TOTALVIEWS" DESC NULLS FIRST, "s1"."AVERAGESCORE" DESC NULLS FIRST) AS "t7"