SELECT COALESCE("t8"."USERID", "t8"."USERID") AS "USERID", "t8"."REPUTATION", "t8"."POSTCOUNT", "t8"."BADGECOUNT", "t8"."TOTALBOUNTIES", "t8"."TOTALVIEWS", "t8"."POSTID", "t8"."POSTTYPEID", "t8"."ACCEPTEDANSWERID", "t8"."COMMENTCOUNT", "t8"."VOTECOUNT"
FROM (SELECT "t6"."USERID", "t6"."REPUTATION", "t6"."POSTCOUNT", "t6"."BADGECOUNT", "t6"."TOTALBOUNTIES", "t6"."TOTALVIEWS", "t4"."POSTID", "t4"."POSTTYPEID", "t4"."ACCEPTEDANSWERID", "t4"."COMMENTCOUNT", "t4"."VOTECOUNT"
FROM (SELECT ANY_VALUE("t2"."Id") AS "POSTID", "t2"."PostTypeId" AS "POSTTYPEID", "t2"."AcceptedAnswerId" AS "ACCEPTEDANSWERID", COUNT(DISTINCT "t2"."Id0") AS "COMMENTCOUNT", COUNT(DISTINCT "Votes0"."Id") AS "VOTECOUNT"
FROM "STACK"."Votes" AS "Votes0"
RIGHT JOIN (SELECT "Posts0"."Id", "Posts0"."PostTypeId", "Posts0"."AcceptedAnswerId", "Posts0"."ParentId", "Posts0"."CreationDate", "Posts0"."Score", "Posts0"."ViewCount", "Posts0"."Body", "Posts0"."OwnerUserId", "Posts0"."OwnerDisplayName", "Posts0"."LastEditorUserId", "Posts0"."LastEditorDisplayName", "Posts0"."LastEditDate", "Posts0"."LastActivityDate", "Posts0"."Title", "Posts0"."Tags", "Posts0"."AnswerCount", "Posts0"."CommentCount", "Posts0"."FavoriteCount", "Posts0"."ClosedDate", "Posts0"."CommunityOwnedDate", "Posts0"."ContentLicense", "Comments"."Id" AS "Id0", "Comments"."PostId", "Comments"."Score" AS "Score0", "Comments"."Text", "Comments"."CreationDate" AS "CreationDate0", "Comments"."UserDisplayName", "Comments"."UserId", "Comments"."ContentLicense" AS "ContentLicense0"
FROM "STACK"."Comments"
RIGHT JOIN "STACK"."Posts" AS "Posts0" ON "Comments"."PostId" = "Posts0"."Id") AS "t2" ON "Votes0"."PostId" = "t2"."Id"
GROUP BY "t2"."Id", "t2"."PostTypeId", "t2"."AcceptedAnswerId") AS "t4"
INNER JOIN (SELECT ANY_VALUE("Id") AS "USERID", "REPUTATION", COUNT(DISTINCT "Id0") AS "POSTCOUNT", COUNT(DISTINCT "Id1") AS "BADGECOUNT", SUM("FD_COL_4") AS "TOTALBOUNTIES", SUM("FD_COL_5") AS "TOTALVIEWS"
FROM "s1"
GROUP BY "Id", "REPUTATION") AS "t6" ON "t4"."ACCEPTEDANSWERID" = "t6"."USERID"
ORDER BY "t6"."REPUTATION" DESC NULLS FIRST, "t6"."POSTCOUNT" DESC NULLS FIRST) AS "t8"