SELECT COALESCE("t9"."DISPLAYNAME", "t9"."DISPLAYNAME") AS "DISPLAYNAME", "t9"."VOTECOUNT", "t9"."UPVOTES", "t9"."DOWNVOTES", "t9"."POSTID", "t9"."TITLE", "t9"."SCORE", "t9"."VIEWCOUNT", "t9"."COMMENTCOUNT", "t9"."ANSWERCOUNT"
FROM (SELECT "t2"."DISPLAYNAME", "t2"."VOTECOUNT", "t2"."UPVOTES", "t2"."DOWNVOTES", "t7"."POSTID", "t7"."TITLE", "t7"."SCORE", "t7"."VIEWCOUNT", "t7"."COMMENTCOUNT", "t7"."ANSWERCOUNT"
FROM (SELECT ANY_VALUE("Id") AS "USERID", "DISPLAYNAME", COUNT("Id0") AS "VOTECOUNT", SUM("FD_COL_3") AS "UPVOTES", SUM("FD_COL_4") AS "DOWNVOTES"
FROM "s1"
GROUP BY "Id", "DISPLAYNAME") AS "t2"
INNER JOIN (SELECT ANY_VALUE("t3"."Id") AS "POSTID", "t3"."Title" AS "TITLE", "t3"."Score" AS "SCORE", "t3"."ViewCount" AS "VIEWCOUNT", "t3"."CreationDate" AS "CREATIONDATE", COUNT("t3"."Id0") AS "COMMENTCOUNT", COUNT("t4"."Id") AS "ANSWERCOUNT"
FROM (SELECT "Posts"."Id", "Posts"."PostTypeId", "Posts"."AcceptedAnswerId", "Posts"."ParentId", "Posts"."CreationDate", "Posts"."Score", "Posts"."ViewCount", "Posts"."Body", "Posts"."OwnerUserId", "Posts"."OwnerDisplayName", "Posts"."LastEditorUserId", "Posts"."LastEditorDisplayName", "Posts"."LastEditDate", "Posts"."LastActivityDate", "Posts"."Title", "Posts"."Tags", "Posts"."AnswerCount", "Posts"."CommentCount", "Posts"."FavoriteCount", "Posts"."ClosedDate", "Posts"."CommunityOwnedDate", "Posts"."ContentLicense", "Comments"."Id" AS "Id0", "Comments"."PostId", "Comments"."Score" AS "Score0", "Comments"."Text", "Comments"."CreationDate" AS "CreationDate0", "Comments"."UserDisplayName", "Comments"."UserId", "Comments"."ContentLicense" AS "ContentLicense0"
FROM "STACK"."Comments"
RIGHT JOIN "STACK"."Posts" ON "Comments"."PostId" = "Posts"."Id") AS "t3"
LEFT JOIN (SELECT *
FROM "STACK"."Posts"
WHERE CAST("PostTypeId" AS INTEGER) = 2) AS "t4" ON "t3"."Id" = "t4"."ParentId"
GROUP BY "t3"."Id", "t3"."CreationDate", "t3"."Score", "t3"."ViewCount", "t3"."Title") AS "t7" ON "t2"."USERID" = "t7"."POSTID"
ORDER BY "t2"."VOTECOUNT" DESC NULLS FIRST, "t7"."SCORE" DESC NULLS FIRST) AS "t9"