SELECT COALESCE("t0"."OWNERDISPLAYNAME", "t0"."OWNERDISPLAYNAME") AS "OWNERDISPLAYNAME", "t0"."TITLE", "t0"."CREATIONDATE", "t0"."LASTACTIVITYDATE", "t0"."SCORE", "t0"."ANSWERCOUNT", "t0"."VIEWCOUNT", "t0"."COMMENTCOUNT", "t0"."TAGNAME", COUNT("PostHistory"."PostHistoryTypeId") AS "HISTORYCOUNT"
FROM "STACK"."PostHistory"
RIGHT JOIN (SELECT "s1"."Id0" AS "POSTID", "s1"."Title" AS "TITLE", "s1"."CreationDate0" AS "CREATIONDATE", "s1"."LastActivityDate" AS "LASTACTIVITYDATE", "s1"."Score" AS "SCORE", "s1"."AnswerCount" AS "ANSWERCOUNT", "s1"."ViewCount" AS "VIEWCOUNT", "s1"."CommentCount" AS "COMMENTCOUNT", "s1"."DisplayName" AS "OWNERDISPLAYNAME", "s1"."TagName" AS "TAGNAME", "PostHistory0"."CreationDate" AS "HISTORYCREATIONDATE", "PostHistory0"."PostHistoryTypeId" AS "POSTHISTORYTYPEID"
FROM "STACK"."PostHistory" AS "PostHistory0"
RIGHT JOIN "s1" ON "PostHistory0"."PostId" = "s1"."Id0") AS "t0" ON "PostHistory"."PostId" = "t0"."POSTID"
GROUP BY "t0"."TITLE", "t0"."CREATIONDATE", "t0"."LASTACTIVITYDATE", "t0"."SCORE", "t0"."ANSWERCOUNT", "t0"."VIEWCOUNT", "t0"."COMMENTCOUNT", "t0"."OWNERDISPLAYNAME", "t0"."TAGNAME"
ORDER BY "t0"."LASTACTIVITYDATE" DESC NULLS FIRST
FETCH NEXT 100 ROWS ONLY