SELECT COALESCE("POSTTYPE", "POSTTYPE") AS "POSTTYPE", "TOTALPOSTS", "AVERAGESCORE", "TOTALVIEWS", "UNIQUEUSERS"
FROM (SELECT "POSTTYPE", "TOTALPOSTS", "AVERAGESCORE", "TOTALVIEWS", "UNIQUEUSERS"
FROM "s1"
ORDER BY "TOTALPOSTS" DESC NULLS FIRST) AS "t3"