SELECT COALESCE("t15"."POSTID", "t15"."POSTID") AS "POSTID", "t15"."TITLE", "t15"."CREATIONDATE", "t15"."SCORE", "t15"."VIEWCOUNT", "t15"."COMMENTCOUNT", "t15"."VOTECOUNT", "t15"."ANSWERCOUNT", "t15"."USERID", "t15"."DISPLAYNAME", "t15"."TOTALVIEWS", "t15"."TOTALUPVOTES", "t15"."TOTALDOWNVOTES", "t15"."BADGECOUNT"
FROM (SELECT "t13"."POSTID", "t13"."TITLE", "t13"."CREATIONDATE", "t13"."SCORE", "t13"."VIEWCOUNT", "t13"."COMMENTCOUNT", "t13"."VOTECOUNT", "t13"."ANSWERCOUNT", "t3"."USERID", "t3"."DISPLAYNAME", "t3"."TOTALVIEWS", "t3"."TOTALUPVOTES", "t3"."TOTALDOWNVOTES", "t3"."BADGECOUNT"
FROM (SELECT ANY_VALUE("Users"."Id") AS "USERID", "Users"."DisplayName" AS "DISPLAYNAME", SUM("Users"."Views") AS "TOTALVIEWS", SUM("Users"."UpVotes") AS "TOTALUPVOTES", SUM("Users"."DownVotes") AS "TOTALDOWNVOTES", COUNT("Badges"."Id") AS "BADGECOUNT"
FROM "STACK"."Badges"
RIGHT JOIN "STACK"."Users" ON "Badges"."UserId" = "Users"."Id"
GROUP BY "Users"."Id", "Users"."DisplayName") AS "t3"
INNER JOIN (SELECT ANY_VALUE("t4"."Id") AS "POSTID", "t4"."Title" AS "TITLE", "t4"."CreationDate" AS "CREATIONDATE", "t4"."Score" AS "SCORE", "t4"."ViewCount" AS "VIEWCOUNT", COUNT(DISTINCT "t4"."Id0") AS "COMMENTCOUNT", COUNT(DISTINCT "t4"."Id1") AS "VOTECOUNT", ANY_VALUE(CASE WHEN "t10"."EXPR$0" IS NULL THEN 0 ELSE "t10"."EXPR$0" END) AS "ANSWERCOUNT"
FROM (SELECT "s1"."Id", "s1"."PostTypeId", "s1"."AcceptedAnswerId", "s1"."ParentId", "s1"."CreationDate", "s1"."Score", "s1"."ViewCount", "s1"."Body", "s1"."OwnerUserId", "s1"."OwnerDisplayName", "s1"."LastEditorUserId", "s1"."LastEditorDisplayName", "s1"."LastEditDate", "s1"."LastActivityDate", "s1"."Title", "s1"."Tags", "s1"."AnswerCount", "s1"."CommentCount", "s1"."FavoriteCount", "s1"."ClosedDate", "s1"."CommunityOwnedDate", "s1"."ContentLicense", "s1"."Id0", "s1"."PostId", "s1"."Score0", "s1"."Text", "s1"."CreationDate0", "s1"."UserDisplayName", "s1"."UserId", "s1"."ContentLicense0", "Votes"."Id" AS "Id1", "Votes"."PostId" AS "PostId0", "Votes"."VoteTypeId", "Votes"."UserId" AS "UserId0", "Votes"."CreationDate" AS "CreationDate1", "Votes"."BountyAmount"
FROM "STACK"."Votes"
RIGHT JOIN "s1" ON "Votes"."PostId" = "s1"."Id") AS "t4"
LEFT JOIN (SELECT "t7"."Id" AS "ParentId", CASE WHEN "t9"."EXPR$0" IS NOT NULL THEN "t9"."EXPR$0" ELSE 0 END AS "EXPR$0"
FROM (SELECT "t5"."Id"
FROM "STACK"."Votes" AS "Votes0"
RIGHT JOIN (SELECT "Posts0"."Id", "Posts0"."PostTypeId", "Posts0"."AcceptedAnswerId", "Posts0"."ParentId", "Posts0"."CreationDate", "Posts0"."Score", "Posts0"."ViewCount", "Posts0"."Body", "Posts0"."OwnerUserId", "Posts0"."OwnerDisplayName", "Posts0"."LastEditorUserId", "Posts0"."LastEditorDisplayName", "Posts0"."LastEditDate", "Posts0"."LastActivityDate", "Posts0"."Title", "Posts0"."Tags", "Posts0"."AnswerCount", "Posts0"."CommentCount", "Posts0"."FavoriteCount", "Posts0"."ClosedDate", "Posts0"."CommunityOwnedDate", "Posts0"."ContentLicense", "Comments0"."Id" AS "Id0", "Comments0"."PostId", "Comments0"."Score" AS "Score0", "Comments0"."Text", "Comments0"."CreationDate" AS "CreationDate0", "Comments0"."UserDisplayName", "Comments0"."UserId", "Comments0"."ContentLicense" AS "ContentLicense0"
FROM "STACK"."Comments" AS "Comments0"
RIGHT JOIN "STACK"."Posts" AS "Posts0" ON "Comments0"."PostId" = "Posts0"."Id") AS "t5" ON "Votes0"."PostId" = "t5"."Id"
GROUP BY "t5"."Id") AS "t7"
LEFT JOIN (SELECT "ParentId", COUNT(*) AS "EXPR$0"
FROM "STACK"."Posts"
GROUP BY "ParentId") AS "t9" ON "t7"."Id" IS NOT DISTINCT FROM "t9"."ParentId") AS "t10" ON "t4"."Id" = "t10"."ParentId"
GROUP BY "t4"."Id", "t4"."CreationDate", "t4"."Score", "t4"."ViewCount", "t4"."Title") AS "t13" ON "t3"."USERID" = "t13"."POSTID"
ORDER BY "t13"."SCORE" DESC NULLS FIRST, "t13"."VIEWCOUNT" DESC NULLS FIRST
FETCH NEXT 100 ROWS ONLY) AS "t15"