SELECT COALESCE("POSTTYPE", "POSTTYPE") AS "POSTTYPE", "TOTALPOSTS", "AVGCOMMENTS", "AVGVOTES", "AVGOWNERREPUTATION"
FROM (SELECT "POSTTYPE", "TOTALPOSTS", "AVGCOMMENTS", "AVGVOTES", "AVGOWNERREPUTATION"
FROM "s1"
ORDER BY "TOTALPOSTS" DESC NULLS FIRST) AS "t7"