SELECT COALESCE("t9"."POSTID", "t9"."POSTID") AS "POSTID", "t9"."POSTTYPEID", "t9"."CREATIONDATE", "t9"."SCORE", "t9"."VIEWCOUNT", "t9"."COMMENTCOUNT", "t9"."VOTECOUNT", "t9"."USERID", "t9"."REPUTATION", "t9"."BADGECOUNT", "t9"."TOTALPOSTS"
FROM (SELECT "s1"."POSTID", "s1"."POSTTYPEID", "s1"."CREATIONDATE", "s1"."SCORE", "s1"."VIEWCOUNT", "s1"."COMMENTCOUNT", "s1"."VOTECOUNT", "t7"."USERID", "t7"."REPUTATION", "t7"."BADGECOUNT", "t7"."TOTALPOSTS"
FROM (SELECT ANY_VALUE("t5"."Id") AS "USERID", "t5"."Reputation" AS "REPUTATION", COUNT(DISTINCT "t5"."Id0") AS "BADGECOUNT", COUNT(DISTINCT "Posts0"."Id") AS "TOTALPOSTS"
FROM "STACK"."Posts" AS "Posts0"
RIGHT JOIN (SELECT "Users0"."Id", "Users0"."Reputation", "Users0"."CreationDate", "Users0"."DisplayName", "Users0"."LastAccessDate", "Users0"."WebsiteUrl", "Users0"."Location", "Users0"."AboutMe", "Users0"."Views", "Users0"."UpVotes", "Users0"."DownVotes", "Users0"."ProfileImageUrl", "Users0"."AccountId", "Badges"."Id" AS "Id0", "Badges"."UserId", "Badges"."Name", "Badges"."Date", "Badges"."Class", "Badges"."TagBased"
FROM "STACK"."Badges"
RIGHT JOIN "STACK"."Users" AS "Users0" ON "Badges"."UserId" = "Users0"."Id") AS "t5" ON "Posts0"."OwnerUserId" = "t5"."Id"
GROUP BY "t5"."Id", "t5"."Reputation") AS "t7"
INNER JOIN "s1" ON "t7"."USERID" = "s1"."Id"
ORDER BY "s1"."SCORE" DESC NULLS FIRST, "s1"."VIEWCOUNT" DESC NULLS FIRST) AS "t9"