SELECT COALESCE("t5"."POSTTYPE", "t5"."POSTTYPE") AS "POSTTYPE", "t5"."POSTCOUNT", "t5"."AVGSCORE", "t5"."TOTALVIEWS", "t5"."AVGANSWERCOUNT", "t5"."AVGCOMMENTCOUNT", "t5"."DISPLAYNAME", "t5"."BADGECOUNT", "t5"."MAXREPUTATION", "t5"."AVGREPUTATION"
FROM (SELECT "t3"."POSTTYPE", "t3"."POSTCOUNT", "t3"."AVGSCORE", "t3"."TOTALVIEWS", "t3"."AVGANSWERCOUNT", "t3"."AVGCOMMENTCOUNT", "t1"."DisplayName" AS "DISPLAYNAME", "t1"."BADGECOUNT", "t1"."MAXREPUTATION", "t1"."AVGREPUTATION"
FROM (SELECT "DisplayName", COUNT("Id") AS "BADGECOUNT", MAX("Reputation") AS "MAXREPUTATION", AVG("Reputation") AS "AVGREPUTATION"
FROM "s1"
GROUP BY "DisplayName"
ORDER BY 2 DESC NULLS FIRST
FETCH NEXT 1 ROWS ONLY) AS "t1",
(SELECT ANY_VALUE("PostTypes"."Name") AS "POSTTYPE", COUNT(*) AS "POSTCOUNT", AVG("Posts"."Score") AS "AVGSCORE", SUM("Posts"."ViewCount") AS "TOTALVIEWS", AVG("Posts"."AnswerCount") AS "AVGANSWERCOUNT", AVG("Posts"."CommentCount") AS "AVGCOMMENTCOUNT"
FROM "STACK"."PostTypes"
INNER JOIN "STACK"."Posts" ON "PostTypes"."Id" = "Posts"."PostTypeId"
GROUP BY "PostTypes"."Name") AS "t3"
ORDER BY "t3"."POSTCOUNT" DESC NULLS FIRST) AS "t5"