SELECT COALESCE("t4"."USERID", "t4"."USERID") AS "USERID", "t4"."POSTCOUNT", "t4"."TOTALUPVOTES", "t4"."TOTALDOWNVOTES", "t6"."POSTID", "t6"."POSTTYPEID", "t6"."COMMENTCOUNT", "t6"."VOTECOUNT", "t6"."UPVOTECOUNT", "t6"."DOWNVOTECOUNT"
FROM (SELECT ANY_VALUE("Users"."Id") AS "USERID", COUNT(DISTINCT "Posts0"."Id") AS "POSTCOUNT", SUM("Users"."UpVotes") AS "TOTALUPVOTES", SUM("Users"."DownVotes") AS "TOTALDOWNVOTES"
FROM "STACK"."Users"
INNER JOIN "STACK"."Posts" AS "Posts0" ON "Users"."Id" = "Posts0"."OwnerUserId"
GROUP BY "Users"."Id") AS "t4"
INNER JOIN (SELECT ANY_VALUE("Id") AS "POSTID", "POSTTYPEID", COUNT("Id0") AS "COMMENTCOUNT", COUNT("Id1") AS "VOTECOUNT", SUM("FD_COL_4") AS "UPVOTECOUNT", SUM("FD_COL_5") AS "DOWNVOTECOUNT"
FROM "s1"
GROUP BY "Id", "POSTTYPEID") AS "t6" ON "t4"."USERID" = "t6"."POSTID"
ORDER BY "t4"."POSTCOUNT" DESC NULLS FIRST, "t6"."VOTECOUNT" DESC NULLS FIRST
FETCH NEXT 100 ROWS ONLY