SELECT COALESCE("t5"."USERID", "t5"."USERID") AS "USERID", "t5"."DISPLAYNAME", "t5"."TOTALPOSTS", "t5"."QUESTIONS", "t5"."ANSWERS", "t5"."AVGPOSTSCORE", "t5"."AVGVIEWCOUNT", "t5"."TOTALCOMMENTS", "t5"."TOTALBADGES"
FROM (SELECT "s1"."Id", "s1"."DisplayName" AS "DISPLAYNAME", ANY_VALUE("s1"."Id") AS "USERID", COUNT(DISTINCT "s1"."Id0") AS "TOTALPOSTS", SUM(CASE WHEN CAST("s1"."PostTypeId" AS INTEGER) = 1 THEN 1 ELSE 0 END) AS "QUESTIONS", SUM(CASE WHEN CAST("s1"."PostTypeId" AS INTEGER) = 2 THEN 1 ELSE 0 END) AS "ANSWERS", AVG(CASE WHEN "s1"."Score" IS NOT NULL THEN CAST("s1"."Score" AS INTEGER) ELSE 0 END) AS "AVGPOSTSCORE", AVG(CASE WHEN "s1"."ViewCount" IS NOT NULL THEN CAST("s1"."ViewCount" AS INTEGER) ELSE 0 END) AS "AVGVIEWCOUNT", COUNT(DISTINCT "s1"."Id1") AS "TOTALCOMMENTS", COUNT(DISTINCT "Badges"."Id") AS "TOTALBADGES"
FROM "s1"
LEFT JOIN "STACK"."Badges" ON "s1"."Id" = "Badges"."UserId"
GROUP BY "s1"."Id", "s1"."DisplayName"
ORDER BY 4 DESC NULLS FIRST
FETCH NEXT 100 ROWS ONLY) AS "t5"