SELECT COALESCE("USERREPUTATION", "USERREPUTATION") AS "USERREPUTATION", "TOTALPOSTS", "TOTALQUESTIONS", "TOTALANSWERS", "TOTALVOTES", "AVERAGEPOSTSCORE", "MOSTRECENTPOST", "UNIQUEVOTERS"
FROM (SELECT "USERREPUTATION", "TOTALPOSTS", "TOTALQUESTIONS", "TOTALANSWERS", "TOTALVOTES", "AVERAGEPOSTSCORE", "MOSTRECENTPOST", "UNIQUEVOTERS"
FROM "s1"
ORDER BY "USERREPUTATION" DESC NULLS FIRST) AS "t4"