SELECT COALESCE("t8"."POSTID", "t8"."POSTID") AS "POSTID", "t8"."POSTTYPEID", "t8"."CREATIONDATE", "t8"."COMMENTCOUNT", "t8"."UPVOTECOUNT", "t8"."DOWNVOTECOUNT", "t8"."USERID", "t8"."REPUTATION", "t8"."POSTCOUNT", "t8"."BADGECOUNT"
FROM (SELECT "t6"."POSTID", "t6"."POSTTYPEID", "t6"."CREATIONDATE", "t6"."COMMENTCOUNT", "t6"."UPVOTECOUNT", "t6"."DOWNVOTECOUNT", "t2"."USERID", "t2"."REPUTATION", "t2"."POSTCOUNT", "t2"."BADGECOUNT"
FROM (SELECT ANY_VALUE("s1"."Id") AS "USERID", "s1"."Reputation" AS "REPUTATION", COUNT(DISTINCT "s1"."Id0") AS "POSTCOUNT", COUNT(DISTINCT "Badges"."Id") AS "BADGECOUNT"
FROM "s1"
LEFT JOIN "STACK"."Badges" ON "s1"."Id" = "Badges"."UserId"
GROUP BY "s1"."Id", "s1"."Reputation") AS "t2"
INNER JOIN (SELECT ANY_VALUE("t3"."Id") AS "POSTID", "t3"."PostTypeId" AS "POSTTYPEID", "t3"."CreationDate" AS "CREATIONDATE", COUNT("t3"."Id0") AS "COMMENTCOUNT", SUM(CASE WHEN CAST("Votes"."VoteTypeId" AS INTEGER) = 2 THEN 1 ELSE 0 END) AS "UPVOTECOUNT", SUM(CASE WHEN CAST("Votes"."VoteTypeId" AS INTEGER) = 3 THEN 1 ELSE 0 END) AS "DOWNVOTECOUNT", CAST("t3"."PostTypeId" AS INTEGER) AS "POSTTYPEID0"
FROM "STACK"."Votes"
RIGHT JOIN (SELECT "Posts0"."Id", "Posts0"."PostTypeId", "Posts0"."AcceptedAnswerId", "Posts0"."ParentId", "Posts0"."CreationDate", "Posts0"."Score", "Posts0"."ViewCount", "Posts0"."Body", "Posts0"."OwnerUserId", "Posts0"."OwnerDisplayName", "Posts0"."LastEditorUserId", "Posts0"."LastEditorDisplayName", "Posts0"."LastEditDate", "Posts0"."LastActivityDate", "Posts0"."Title", "Posts0"."Tags", "Posts0"."AnswerCount", "Posts0"."CommentCount", "Posts0"."FavoriteCount", "Posts0"."ClosedDate", "Posts0"."CommunityOwnedDate", "Posts0"."ContentLicense", "Comments"."Id" AS "Id0", "Comments"."PostId", "Comments"."Score" AS "Score0", "Comments"."Text", "Comments"."CreationDate" AS "CreationDate0", "Comments"."UserDisplayName", "Comments"."UserId", "Comments"."ContentLicense" AS "ContentLicense0"
FROM "STACK"."Comments"
RIGHT JOIN "STACK"."Posts" AS "Posts0" ON "Comments"."PostId" = "Posts0"."Id") AS "t3" ON "Votes"."PostId" = "t3"."Id"
GROUP BY "t3"."Id", "t3"."PostTypeId", "t3"."CreationDate") AS "t6" ON "t2"."USERID" = "t6"."POSTTYPEID0"
ORDER BY "t6"."CREATIONDATE" DESC NULLS FIRST) AS "t8"