SELECT COALESCE("POSTTYPE", "POSTTYPE") AS "POSTTYPE", "TOTALPOSTS", "TOTALVOTES", "TOTALUSERS", "VOTESPERPOST", "USERSPERPOST"
FROM (SELECT "POSTTYPE", "TOTALPOSTS", "TOTALVOTES", "TOTALUSERS", CAST("TOTALVOTES" AS DECIMAL(19, 1)) / CASE WHEN "TOTALPOSTS" = 0 THEN NULL ELSE "TOTALPOSTS" END AS "VOTESPERPOST", CAST("TOTALUSERS" AS DECIMAL(19, 1)) / CASE WHEN "TOTALPOSTS" = 0 THEN NULL ELSE "TOTALPOSTS" END AS "USERSPERPOST"
FROM "s1"
ORDER BY "TOTALPOSTS" DESC NULLS FIRST) AS "t3"