SELECT COALESCE("t10"."USERID", "t10"."USERID") AS "USERID", "t10"."BADGECOUNT", "t10"."TOTALVIEWS", "t10"."TOTALUPVOTES", "t10"."TOTALDOWNVOTES", "t10"."POSTTYPE", "t10"."TOTALPOSTS", "t10"."TOTALCOMMENTS", "t10"."TOTALVOTES"
FROM (SELECT "t1"."USERID", "t1"."BADGECOUNT", "t1"."TOTALVIEWS", "t1"."TOTALUPVOTES", "t1"."TOTALDOWNVOTES", "t8"."POSTTYPE", "t8"."TOTALPOSTS", "t8"."TOTALCOMMENTS", "t8"."TOTALVOTES"
FROM (SELECT ANY_VALUE("Id0") AS "USERID", COUNT("Id") AS "BADGECOUNT", SUM("Views") AS "TOTALVIEWS", SUM("UpVotes") AS "TOTALUPVOTES", SUM("DownVotes") AS "TOTALDOWNVOTES", CAST(ANY_VALUE("Id0") AS BIGINT) AS "USERID0"
FROM "s1"
GROUP BY "Id0") AS "t1"
INNER JOIN (SELECT ANY_VALUE("t2"."Name") AS "POSTTYPE", COUNT("t2"."Id0") AS "TOTALPOSTS", SUM("t6"."COMMENTCOUNT") AS "TOTALCOMMENTS", SUM("t6"."VOTECOUNT") AS "TOTALVOTES"
FROM (SELECT "PostTypes"."Id", "PostTypes"."Name", "Posts"."Id" AS "Id0", "Posts"."PostTypeId", "Posts"."AcceptedAnswerId", "Posts"."ParentId", "Posts"."CreationDate", "Posts"."Score", "Posts"."ViewCount", "Posts"."Body", "Posts"."OwnerUserId", "Posts"."OwnerDisplayName", "Posts"."LastEditorUserId", "Posts"."LastEditorDisplayName", "Posts"."LastEditDate", "Posts"."LastActivityDate", "Posts"."Title", "Posts"."Tags", "Posts"."AnswerCount", "Posts"."CommentCount", "Posts"."FavoriteCount", "Posts"."ClosedDate", "Posts"."CommunityOwnedDate", "Posts"."ContentLicense"
FROM "STACK"."Posts"
RIGHT JOIN "STACK"."PostTypes" ON "Posts"."PostTypeId" = "PostTypes"."Id") AS "t2"
LEFT JOIN (SELECT ANY_VALUE("t3"."Id") AS "POSTID", "t3"."PostTypeId" AS "POSTTYPEID", COUNT("t3"."Id0") AS "COMMENTCOUNT", COUNT(DISTINCT "Votes"."Id") AS "VOTECOUNT", MAX(CASE WHEN CAST("Votes"."VoteTypeId" AS INTEGER) = 2 THEN 1 ELSE 0 END) AS "UPVOTE", MAX(CASE WHEN CAST("Votes"."VoteTypeId" AS INTEGER) = 3 THEN 1 ELSE 0 END) AS "DOWNVOTE", MAX("t3"."CreationDate") AS "LASTACTIVITYDATE"
FROM "STACK"."Votes"
RIGHT JOIN (SELECT "Posts0"."Id", "Posts0"."PostTypeId", "Posts0"."AcceptedAnswerId", "Posts0"."ParentId", "Posts0"."CreationDate", "Posts0"."Score", "Posts0"."ViewCount", "Posts0"."Body", "Posts0"."OwnerUserId", "Posts0"."OwnerDisplayName", "Posts0"."LastEditorUserId", "Posts0"."LastEditorDisplayName", "Posts0"."LastEditDate", "Posts0"."LastActivityDate", "Posts0"."Title", "Posts0"."Tags", "Posts0"."AnswerCount", "Posts0"."CommentCount", "Posts0"."FavoriteCount", "Posts0"."ClosedDate", "Posts0"."CommunityOwnedDate", "Posts0"."ContentLicense", "Comments"."Id" AS "Id0", "Comments"."PostId", "Comments"."Score" AS "Score0", "Comments"."Text", "Comments"."CreationDate" AS "CreationDate0", "Comments"."UserDisplayName", "Comments"."UserId", "Comments"."ContentLicense" AS "ContentLicense0"
FROM "STACK"."Comments"
RIGHT JOIN "STACK"."Posts" AS "Posts0" ON "Comments"."PostId" = "Posts0"."Id") AS "t3" ON "Votes"."PostId" = "t3"."Id"
GROUP BY "t3"."Id", "t3"."PostTypeId") AS "t6" ON "t2"."Id0" = "t6"."POSTID"
GROUP BY "t2"."Name") AS "t8" ON "t1"."USERID0" = "t8"."TOTALPOSTS"
ORDER BY "t1"."TOTALVIEWS" DESC NULLS FIRST, "t8"."TOTALPOSTS" DESC NULLS FIRST) AS "t10"