SELECT COALESCE("POSTID", "POSTID") AS "POSTID", "TITLE", "CREATIONDATE", "COMMENTCOUNT", "VOTECOUNT", "HISTORYCHANGECOUNT", "OWNERDISPLAYNAME", "OWNERREPUTATION"
FROM (SELECT ANY_VALUE("Id") AS "POSTID", "TITLE", "CREATIONDATE", COUNT("FD_COL_5") AS "COMMENTCOUNT", COUNT(DISTINCT "Id1") AS "VOTECOUNT", COUNT(DISTINCT "Id2") AS "HISTORYCHANGECOUNT", ANY_VALUE("DisplayName") AS "OWNERDISPLAYNAME", ANY_VALUE("Reputation") AS "OWNERREPUTATION"
FROM "s1"
GROUP BY "Id", "TITLE", "CREATIONDATE", "DisplayName", "Reputation"
ORDER BY "CREATIONDATE" DESC NULLS FIRST
FETCH NEXT 100 ROWS ONLY) AS "t6"