SELECT COALESCE("t7"."USERID", "t7"."USERID") AS "USERID", "t7"."REPUTATION", "t7"."POSTCOUNT", "t7"."COMMENTCOUNT", "t7"."BADGECOUNT", "t7"."TOTALVOTES", "t7"."UPVOTES", "t7"."DOWNVOTES"
FROM (SELECT "s1"."USERID", "s1"."REPUTATION", "s1"."POSTCOUNT", "s1"."COMMENTCOUNT", "s1"."BADGECOUNT", CASE WHEN "t5"."VOTECOUNT" IS NOT NULL THEN CAST("t5"."VOTECOUNT" AS BIGINT) ELSE 0 END AS "TOTALVOTES", CASE WHEN "t5"."UPVOTES" IS NOT NULL THEN CAST("t5"."UPVOTES" AS INTEGER) ELSE 0 END AS "UPVOTES", CASE WHEN "t5"."DOWNVOTES" IS NOT NULL THEN CAST("t5"."DOWNVOTES" AS INTEGER) ELSE 0 END AS "DOWNVOTES"
FROM (SELECT "Votes"."UserId" AS "USERID", COUNT(*) AS "VOTECOUNT", SUM(CASE WHEN "VoteTypes"."Name" = 'UpMod' THEN 1 ELSE 0 END) AS "UPVOTES", SUM(CASE WHEN "VoteTypes"."Name" = 'DownMod' THEN 1 ELSE 0 END) AS "DOWNVOTES"
FROM "STACK"."VoteTypes"
INNER JOIN "STACK"."Votes" ON "VoteTypes"."Id" = "Votes"."VoteTypeId"
GROUP BY "Votes"."UserId") AS "t5"
RIGHT JOIN "s1" ON "t5"."USERID" = "s1"."USERID"
ORDER BY "s1"."REPUTATION" DESC NULLS FIRST
FETCH NEXT 100 ROWS ONLY) AS "t7"