SELECT COALESCE("t6"."POSTID", "t6"."POSTID") AS "POSTID", "t6"."TITLE", "t6"."CREATIONDATE", "t6"."OWNERDISPLAYNAME", "t6"."SCORE", "t6"."VIEWCOUNT", "t6"."ANSWERCOUNT", "t6"."COMMENTCOUNT"
FROM (SELECT "t4"."Id" AS "POSTID", "t4"."Title" AS "TITLE", "t4"."CreationDate" AS "CREATIONDATE", "t4"."DisplayName" AS "OWNERDISPLAYNAME", "t4"."Score" AS "SCORE", "t4"."ViewCount" AS "VIEWCOUNT", CASE WHEN "t4"."ANSWERCOUNT" IS NOT NULL THEN CAST("t4"."ANSWERCOUNT" AS BIGINT) ELSE 0 END AS "ANSWERCOUNT", CASE WHEN "t1"."COMMENTCOUNT" IS NOT NULL THEN CAST("t1"."COMMENTCOUNT" AS BIGINT) ELSE 0 END AS "COMMENTCOUNT"
FROM (SELECT "PostId", COUNT(*) AS "COMMENTCOUNT"
FROM "STACK"."Comments"
GROUP BY "PostId") AS "t1"
RIGHT JOIN (SELECT "t3"."Id", "t3"."PostTypeId", "t3"."AcceptedAnswerId", "t3"."ParentId", "t3"."CreationDate", "t3"."Score", "t3"."ViewCount", "t3"."Body", "t3"."OwnerUserId", "t3"."OwnerDisplayName", "t3"."LastEditorUserId", "t3"."LastEditorDisplayName", "t3"."LastEditDate", "t3"."LastActivityDate", "t3"."Title", "t3"."Tags", "t3"."AnswerCount", "t3"."CommentCount", "t3"."FavoriteCount", "t3"."ClosedDate", "t3"."CommunityOwnedDate", "t3"."ContentLicense", "Users"."Id" AS "Id0", "Users"."Reputation", "Users"."CreationDate" AS "CreationDate0", "Users"."DisplayName", "Users"."LastAccessDate", "Users"."WebsiteUrl", "Users"."Location", "Users"."AboutMe", "Users"."Views", "Users"."UpVotes", "Users"."DownVotes", "Users"."ProfileImageUrl", "Users"."AccountId", "t2"."ParentId" AS "PARENTID", "t2"."ANSWERCOUNT"
FROM (SELECT "ParentId", COUNT(*) AS "ANSWERCOUNT"
FROM "s1"
GROUP BY "ParentId") AS "t2"
RIGHT JOIN ("STACK"."Users" INNER JOIN (SELECT *
FROM "STACK"."Posts"
WHERE "CreationDate" >= TIMESTAMP '2022-01-01 00:00:00') AS "t3" ON "Users"."Id" = "t3"."OwnerUserId") ON "t2"."ParentId" = "t3"."Id") AS "t4" ON "t1"."PostId" = "t4"."Id"
ORDER BY "t4"."Score" DESC NULLS FIRST, "t4"."ViewCount" DESC NULLS FIRST) AS "t6"