SELECT COALESCE("t"."PostId", "t"."PostId") AS "POSTID", "t"."HISTORYCOUNT", "t"."LASTEDITED", "t2"."POSTID" AS "POSTID0", "t2"."TITLE", "t2"."CREATIONDATE", "t2"."VIEWCOUNT", "t2"."SCORE", "t2"."OWNERREPUTATION", "t2"."COMMENTCOUNT", "t2"."VOTECOUNT"
FROM (SELECT "PostId", COUNT(*) AS "HISTORYCOUNT", MAX("CreationDate") AS "LASTEDITED"
FROM "STACK"."PostHistory"
GROUP BY "PostId") AS "t"
RIGHT JOIN (SELECT ANY_VALUE("Posts"."Id") AS "POSTID", "Posts"."Title" AS "TITLE", "Posts"."CreationDate" AS "CREATIONDATE", "Posts"."ViewCount" AS "VIEWCOUNT", "Posts"."Score" AS "SCORE", ANY_VALUE("Users"."Reputation") AS "OWNERREPUTATION", COUNT(DISTINCT "Comments"."Id") AS "COMMENTCOUNT", COUNT(DISTINCT "Votes"."Id") AS "VOTECOUNT"
FROM "STACK"."Posts"
LEFT JOIN "STACK"."Users" ON "Posts"."OwnerUserId" = "Users"."Id"
LEFT JOIN "STACK"."Comments" ON "Posts"."Id" = "Comments"."PostId"
LEFT JOIN "STACK"."Votes" ON "Posts"."Id" = "Votes"."PostId"
GROUP BY "Posts"."Id", "Posts"."CreationDate", "Posts"."Score", "Posts"."ViewCount", "Posts"."Title", "Users"."Reputation") AS "t2" ON "t"."PostId" = "t2"."POSTID"