SELECT COALESCE("t5"."USERID", "t5"."USERID") AS "USERID", "t5"."DISPLAYNAME", "t5"."TOTALPOSTS", "t5"."TOTALQUESTIONS", "t5"."TOTALANSWERS", "t5"."TOTALVIEWS", "t5"."AVERAGESCORE", "t5"."TOTALBADGES"
FROM (SELECT "s1"."USERID", "s1"."DISPLAYNAME", "s1"."TOTALPOSTS", "s1"."TOTALQUESTIONS", "s1"."TOTALANSWERS", "s1"."TOTALVIEWS", "s1"."AVERAGESCORE", CASE WHEN "t3"."TOTALBADGES" IS NOT NULL THEN CAST("t3"."TOTALBADGES" AS BIGINT) ELSE 0 END AS "TOTALBADGES"
FROM "s1"
LEFT JOIN (SELECT "UserId", COUNT(*) AS "TOTALBADGES"
FROM "STACK"."Badges"
GROUP BY "UserId") AS "t3" ON "s1"."USERID" = "t3"."UserId"
ORDER BY "s1"."TOTALPOSTS" DESC NULLS FIRST
FETCH NEXT 100 ROWS ONLY) AS "t5"