SELECT COALESCE("POSTID", "POSTID") AS "POSTID", "TITLE", "CREATIONDATE", "VIEWCOUNT", "SCORE", "OWNERREPUTATION", "COMMENTCOUNT", "VOTECOUNT", "POSTHISTORYCOUNT", "LASTEDITED"
FROM (SELECT "POSTID0" AS "POSTID", "TITLE", "CREATIONDATE", "VIEWCOUNT", "SCORE", "OWNERREPUTATION", "COMMENTCOUNT", "VOTECOUNT", CASE WHEN "HISTORYCOUNT" IS NOT NULL THEN CAST("HISTORYCOUNT" AS BIGINT) ELSE 0 END AS "POSTHISTORYCOUNT", "LASTEDITED"
FROM "s1"
ORDER BY "VIEWCOUNT" DESC NULLS FIRST, "SCORE" DESC NULLS FIRST) AS "t5"