SELECT COALESCE("USERID", "USERID") AS "USERID", "DISPLAYNAME", "POSTCOUNT", "QUESTIONCOUNT", "ANSWERCOUNT", "COMMENTCOUNT", "UPVOTES", "DOWNVOTES", "REPUTATION", "CREATIONDATE", "LASTACCESSDATE"
FROM (SELECT "USERID", "DISPLAYNAME_" AS "DISPLAYNAME", "POSTCOUNT", "QUESTIONCOUNT", "ANSWERCOUNT", "COMMENTCOUNT", "UPVOTES_" AS "UPVOTES", "DOWNVOTES_" AS "DOWNVOTES", "Reputation" AS "REPUTATION", "CreationDate" AS "CREATIONDATE", "LastAccessDate" AS "LASTACCESSDATE"
FROM "s1"
ORDER BY "POSTCOUNT" DESC NULLS FIRST
FETCH NEXT 100 ROWS ONLY) AS "t6"