SELECT COALESCE("POSTID", "POSTID") AS "POSTID", "TITLE", "USERREPUTATION", "POSTCREATIONDATE", "LASTACTIVITYDATE", "COMMENTCOUNT", "UPVOTES", "DOWNVOTES", "SCORE", "VIEWCOUNT", "ANSWERCOUNT", "FAVORITECOUNT"
FROM (SELECT "POSTID", "TITLE", "USERREPUTATION", "POSTCREATIONDATE", "LASTACTIVITYDATE", "COMMENTCOUNT0" AS "COMMENTCOUNT", "UPVOTES", "DOWNVOTES", "SCORE", "VIEWCOUNT", "ANSWERCOUNT", "FAVORITECOUNT"
FROM "s1"
ORDER BY "LASTACTIVITYDATE" DESC NULLS FIRST
FETCH NEXT 100 ROWS ONLY) AS "t7"