SELECT COALESCE("USERID", "USERID") AS "USERID", "USERDISPLAYNAME", "TOTALPOSTS", "TOTALPOSTSCORE", "TOTALPOSTVIEWS", "TOTALVOTES", "LASTPOSTDATE"
FROM "s1"
ORDER BY "TOTALPOSTS" DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY