SELECT COALESCE("t5"."POSTID", "t5"."POSTID") AS "POSTID", "t5"."POSTTYPEID", "t5"."CREATIONDATE", "t5"."SCORE", "t5"."VIEWCOUNT", "t5"."ANSWERCOUNT", "t5"."TOTALCOMMENTCOUNT", "t5"."FAVORITECOUNT", "t5"."OWNERREPUTATION", "t5"."REVISIONCOUNT", "t5"."LASTEDITDATE", "t5"."CLOSEDPOSTS", "t5"."REOPENEDPOSTS"
FROM (SELECT "s1"."POSTID", "s1"."POSTTYPEID", "s1"."CREATIONDATE", "s1"."SCORE", "s1"."VIEWCOUNT", "s1"."ANSWERCOUNT", "s1"."TOTALCOMMENTCOUNT", "s1"."FAVORITECOUNT", "s1"."OWNERREPUTATION", "t3"."REVISIONCOUNT", "t3"."LASTEDITDATE", "t3"."CLOSEDPOSTS", "t3"."REOPENEDPOSTS"
FROM (SELECT "PostId" AS "POSTID", COUNT(*) AS "REVISIONCOUNT", MAX("CreationDate") AS "LASTEDITDATE", MAX(CASE WHEN CAST("PostHistoryTypeId" AS INTEGER) = 10 THEN 1 ELSE 0 END) AS "CLOSEDPOSTS", MAX(CASE WHEN CAST("PostHistoryTypeId" AS INTEGER) = 11 THEN 1 ELSE 0 END) AS "REOPENEDPOSTS"
FROM "STACK"."PostHistory"
GROUP BY "PostId") AS "t3"
RIGHT JOIN "s1" ON "t3"."POSTID" = "s1"."POSTID"
ORDER BY "s1"."CREATIONDATE" DESC NULLS FIRST
FETCH NEXT 100 ROWS ONLY) AS "t5"