SELECT COALESCE("t6"."POSTID", "t6"."POSTID") AS "POSTID", "t6"."TITLE", "t6"."CREATIONDATE", "t6"."VIEWCOUNT", "t6"."SCORE", "t6"."OWNERDISPLAYNAME", "t6"."COMMENTCOUNT", "t6"."VOTECOUNT", "t6"."UPVOTES", "t6"."DOWNVOTES", "t6"."BADGECOUNT"
FROM (SELECT ANY_VALUE("s1"."Id") AS "POSTID", "s1"."Title" AS "TITLE", "s1"."CreationDate" AS "CREATIONDATE", "s1"."ViewCount" AS "VIEWCOUNT", "s1"."Score" AS "SCORE", ANY_VALUE("s1"."DisplayName") AS "OWNERDISPLAYNAME", COUNT("s1"."Id1") AS "COMMENTCOUNT", COUNT(DISTINCT "s1"."Id2") AS "VOTECOUNT", SUM(CASE WHEN CAST("s1"."VoteTypeId" AS INTEGER) = 2 THEN 1 ELSE 0 END) AS "UPVOTES", SUM(CASE WHEN CAST("s1"."VoteTypeId" AS INTEGER) = 3 THEN 1 ELSE 0 END) AS "DOWNVOTES", COUNT("Badges"."Id") AS "BADGECOUNT"
FROM "s1"
LEFT JOIN "STACK"."Badges" ON "s1"."Id0" = "Badges"."UserId"
GROUP BY "s1"."Id", "s1"."Title", "s1"."CreationDate", "s1"."ViewCount", "s1"."Score", "s1"."DisplayName"
ORDER BY "s1"."CreationDate" DESC NULLS FIRST
FETCH NEXT 100 ROWS ONLY) AS "t6"