SELECT COALESCE("POSTID", "POSTID") AS "POSTID", "TITLE", "CREATIONDATE", "AUTHOR", "COMMENTCOUNT", "UPVOTES", "DOWNVOTES", "BADGECOUNT"
FROM (SELECT ANY_VALUE("Id") AS "POSTID", "TITLE", "CREATIONDATE", ANY_VALUE("DisplayName") AS "AUTHOR", COUNT("Id1") AS "COMMENTCOUNT", SUM("FD_COL_5") AS "UPVOTES", SUM("FD_COL_6") AS "DOWNVOTES", COUNT(DISTINCT "Id3") AS "BADGECOUNT"
FROM "s1"
GROUP BY "Id", "TITLE", "CREATIONDATE", "DisplayName"
ORDER BY "CREATIONDATE" DESC NULLS FIRST
FETCH NEXT 100 ROWS ONLY) AS "t7"