SELECT COALESCE("t9"."USERID", "t9"."USERID") AS "USERID", "t9"."DISPLAYNAME", "t9"."REPUTATION", "t9"."POSTCOUNT", "t9"."UPVOTES", "t9"."DOWNVOTES", "t9"."AVGREPUTATION", "t9"."AVGPOSTCOUNT", "t9"."AVGUPVOTES", "t9"."AVGDOWNVOTES"
FROM (SELECT "t7"."USERID", "t7"."DISPLAYNAME", "t7"."REPUTATION", "t7"."POSTCOUNT", "t7"."UPVOTES", "t7"."DOWNVOTES", "t3"."AVGREPUTATION", "t3"."AVGPOSTCOUNT", "t3"."AVGUPVOTES", "t3"."AVGDOWNVOTES"
FROM (SELECT AVG("t2"."REPUTATION") AS "AVGREPUTATION", AVG("t2"."POSTCOUNT") AS "AVGPOSTCOUNT", AVG("t2"."$f5") AS "AVGUPVOTES", AVG("t2"."$f6") AS "AVGDOWNVOTES"
FROM (SELECT "s1"."Id", "s1"."DisplayName" AS "DISPLAYNAME", "s1"."Reputation" AS "REPUTATION", ANY_VALUE("s1"."Id") AS "USERID", COUNT(DISTINCT "s1"."Id0") AS "POSTCOUNT", SUM(CASE WHEN CAST("Votes"."VoteTypeId" AS INTEGER) = 2 THEN 1 ELSE 0 END) AS "$f5", SUM(CASE WHEN CAST("Votes"."VoteTypeId" AS INTEGER) = 3 THEN 1 ELSE 0 END) AS "$f6"
FROM "STACK"."Votes"
RIGHT JOIN "s1" ON "Votes"."PostId" = "s1"."Id0"
GROUP BY "s1"."Id", "s1"."DisplayName", "s1"."Reputation") AS "t2") AS "t3",
(SELECT ANY_VALUE("s10"."Id") AS "USERID", "s10"."DisplayName" AS "DISPLAYNAME", "s10"."Reputation" AS "REPUTATION", COUNT(DISTINCT "s10"."Id0") AS "POSTCOUNT", SUM(CASE WHEN CAST("Votes0"."VoteTypeId" AS INTEGER) = 2 THEN 1 ELSE 0 END) AS "UPVOTES", SUM(CASE WHEN CAST("Votes0"."VoteTypeId" AS INTEGER) = 3 THEN 1 ELSE 0 END) AS "DOWNVOTES"
FROM "STACK"."Votes" AS "Votes0"
RIGHT JOIN "s1" AS "s10" ON "Votes0"."PostId" = "s10"."Id0"
WHERE "s10"."Reputation" > 1000
GROUP BY "s10"."Id", "s10"."DisplayName", "s10"."Reputation") AS "t7"
ORDER BY "t7"."REPUTATION" DESC NULLS FIRST) AS "t9"