SELECT COALESCE("t1"."PostTypeId", "t1"."PostTypeId") AS "PostTypeId", "t1"."TOTALPOSTS", "t1"."TOTALSCORE", "t1"."AVERAGEVIEWCOUNT", "t1"."AVERAGEANSWERCOUNT", "t1"."AVERAGECOMMENTCOUNT", "t2"."TOTALUSERS", "t2"."AVERAGEREPUTATION", "t2"."MOSTRECENTACCESSDATE", "s1"."VoteTypeId", "s1"."TOTALVOTES"
FROM (SELECT "PostTypeId", COUNT(*) AS "TOTALPOSTS", SUM("Score") AS "TOTALSCORE", AVG("ViewCount") AS "AVERAGEVIEWCOUNT", AVG("AnswerCount") AS "AVERAGEANSWERCOUNT", AVG("CommentCount") AS "AVERAGECOMMENTCOUNT"
FROM "STACK"."Posts"
GROUP BY "PostTypeId") AS "t1",
((SELECT COUNT(*) AS "TOTALUSERS", AVG("Reputation") AS "AVERAGEREPUTATION", MAX("LastAccessDate") AS "MOSTRECENTACCESSDATE"
FROM "STACK"."Users") AS "t2", "s1")
ORDER BY "t1"."PostTypeId", "s1"."VoteTypeId"