SELECT COALESCE("t8"."POSTTYPEID", "t8"."POSTTYPEID") AS "POSTTYPEID", "t8"."TOTALPOSTS", "t8"."TOTALACCEPTEDANSWERS", "t8"."USERID", "t8"."REPUTATION", "t8"."POSTSCOUNT", "t8"."TOTALBOUNTIES"
FROM (SELECT "t6"."POSTTYPEID", "t6"."TOTALPOSTS", "t6"."TOTALACCEPTEDANSWERS", "s1"."USERID", "s1"."REPUTATION", "s1"."POSTSCOUNT", "s1"."TOTALBOUNTIES"
FROM (SELECT "PostTypeId" AS "POSTTYPEID", COUNT(*) AS "TOTALPOSTS", SUM(1) AS "TOTALACCEPTEDANSWERS"
FROM "STACK"."Posts"
GROUP BY "PostTypeId") AS "t6",
"s1"
ORDER BY "t6"."TOTALPOSTS" DESC NULLS FIRST, "s1"."REPUTATION" DESC NULLS FIRST) AS "t8"