SELECT COALESCE("t0"."USERID", "t0"."USERID") AS "USERID", "t0"."DISPLAYNAME", "t0"."POSTCOUNT", "t0"."TOTALSCORE", "t0"."TOTALVIEWS", "t2"."POSTID", "t2"."TITLE", "t2"."POSTTYPE", "t2"."CREATIONDATE", "t2"."LASTACTIVITYDATE", "t2"."SCORE", "t2"."VIEWCOUNT", "t2"."COMMENTCOUNT", "t2"."OWNERUSERID"
FROM (SELECT ANY_VALUE("Users"."Id") AS "USERID", "Users"."DisplayName" AS "DISPLAYNAME", COUNT("Posts"."Id") AS "POSTCOUNT", SUM("Posts"."Score") AS "TOTALSCORE", SUM("Posts"."ViewCount") AS "TOTALVIEWS"
FROM "STACK"."Posts"
RIGHT JOIN "STACK"."Users" ON "Posts"."OwnerUserId" = "Users"."Id"
GROUP BY "Users"."Id", "Users"."DisplayName") AS "t0"
INNER JOIN (SELECT "Posts0"."Id" AS "POSTID", "Posts0"."Title" AS "TITLE", "PostTypes"."Name" AS "POSTTYPE", "Posts0"."CreationDate" AS "CREATIONDATE", "Posts0"."LastActivityDate" AS "LASTACTIVITYDATE", "Posts0"."Score" AS "SCORE", "Posts0"."ViewCount" AS "VIEWCOUNT", CASE WHEN "t1"."COMMENTCOUNT" IS NOT NULL THEN CAST("t1"."COMMENTCOUNT" AS BIGINT) ELSE 0 END AS "COMMENTCOUNT", "Posts0"."OwnerUserId" AS "OWNERUSERID"
FROM "STACK"."Posts" AS "Posts0"
INNER JOIN "STACK"."PostTypes" ON "Posts0"."PostTypeId" = "PostTypes"."Id"
LEFT JOIN (SELECT "PostId", COUNT(*) AS "COMMENTCOUNT"
FROM "STACK"."Comments"
GROUP BY "PostId") AS "t1" ON "Posts0"."Id" = "t1"."PostId") AS "t2" ON "t0"."USERID" = "t2"."OWNERUSERID"