SELECT COALESCE("t1"."TOTALPOSTS", "t1"."TOTALPOSTS") AS "TOTALPOSTS", "t1"."UNIQUEUSERS", "t1"."TOTALANSWERS", "t1"."TOTALCOMMENTS", "t2"."TOTALVOTES", "t2"."UNIQUEVOTERS", "s1"."TOTALUSERS", "s1"."AVGREPUTATION", "s1"."MAXREPUTATION"
FROM (SELECT COUNT(*) AS "TOTALPOSTS", COUNT(DISTINCT "OwnerUserId") AS "UNIQUEUSERS", SUM("AnswerCount") AS "TOTALANSWERS", SUM("CommentCount") AS "TOTALCOMMENTS"
FROM "STACK"."Posts") AS "t1",
((SELECT COUNT(*) AS "TOTALVOTES", COUNT(DISTINCT "UserId") AS "UNIQUEVOTERS"
FROM "STACK"."Votes") AS "t2", "s1")