SELECT COALESCE("t4"."USERID", "t4"."USERID") AS "USERID", "t4"."DISPLAYNAME", "t4"."REPUTATION", "t4"."POSTCOUNT", "t4"."QUESTIONCOUNT", "t4"."ANSWERCOUNT", "t4"."TOTALCOMMENTSCORE", "t4"."TOTALBOUNTYAMOUNT", "t4"."BADGECOUNT", "t4"."LASTACTIVE"
FROM (SELECT "s1"."Id", "s1"."DisplayName" AS "DISPLAYNAME", "s1"."Reputation" AS "REPUTATION", ANY_VALUE("s1"."Id") AS "USERID", COUNT(DISTINCT "s1"."Id0") AS "POSTCOUNT", SUM(CASE WHEN CAST("s1"."PostTypeId" AS INTEGER) = 1 THEN 1 ELSE 0 END) AS "QUESTIONCOUNT", SUM(CASE WHEN CAST("s1"."PostTypeId" AS INTEGER) = 2 THEN 1 ELSE 0 END) AS "ANSWERCOUNT", SUM("s1"."Score0") AS "TOTALCOMMENTSCORE", SUM("Votes"."BountyAmount") AS "TOTALBOUNTYAMOUNT", COUNT(DISTINCT "Badges"."Id") AS "BADGECOUNT", MAX("s1"."CreationDate0") AS "LASTACTIVE"
FROM "s1"
LEFT JOIN "STACK"."Votes" ON "s1"."Id0" = "Votes"."PostId" AND "s1"."Id" = "Votes"."UserId"
LEFT JOIN "STACK"."Badges" ON "s1"."Id" = "Badges"."UserId"
GROUP BY "s1"."Id", "s1"."DisplayName", "s1"."Reputation"
ORDER BY "s1"."Reputation" DESC NULLS FIRST, 5 DESC NULLS FIRST
FETCH NEXT 100 ROWS ONLY) AS "t4"