SELECT COALESCE("DisplayName", "DisplayName") AS "DisplayName", "POSTCOUNT"
FROM (SELECT "DisplayName", COUNT(DISTINCT "Id0") AS "POSTCOUNT"
FROM "s1"
GROUP BY "DisplayName"
ORDER BY 2 DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY) AS "t2"