SELECT COALESCE("DISPLAYNAME", "DISPLAYNAME") AS "DISPLAYNAME", "POSTCOUNT", "QUESTIONCOUNT", "ANSWERCOUNT", "AVERAGEREPUTATION"
FROM "s1"
ORDER BY "POSTCOUNT" DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY