SELECT COALESCE("t14"."USERID", "t14"."USERID") AS "USERID", "t14"."DISPLAYNAME", "t14"."BADGECOUNT", "t14"."POSTCOUNT", "t14"."QUESTIONCOUNT", "t14"."ANSWERCOUNT", "t14"."TOTALSCORE", "t14"."AVERAGEVIEWS", "t14"."RECENTACTIVITYCOUNT"
FROM (SELECT "s1"."USERID", "s1"."DISPLAYNAME", "s1"."BADGECOUNT", "s1"."POSTCOUNT", "s1"."QUESTIONCOUNT", "s1"."ANSWERCOUNT", "s1"."TOTALSCORE", "s1"."AVERAGEVIEWS", "s1"."RECENTACTIVITYCOUNT"
FROM (SELECT AVG("TOTALSCORE") AS "EXPR$0"
FROM (SELECT "OwnerUserId" AS "OWNERUSERID", COUNT(*) AS "POSTCOUNT", COUNT(CASE WHEN CAST("PostTypeId" AS INTEGER) = 1 THEN 1 ELSE NULL END) AS "QUESTIONCOUNT", COUNT(CASE WHEN CAST("PostTypeId" AS INTEGER) = 2 THEN 1 ELSE NULL END) AS "ANSWERCOUNT", SUM("Score") AS "TOTALSCORE", AVG("ViewCount") AS "AVERAGEVIEWS"
FROM "STACK"."Posts"
GROUP BY "OwnerUserId") AS "t10") AS "t11",
"s1"
WHERE "s1"."TOTALSCORE" >= "t11"."EXPR$0" OR "s1"."RECENTACTIVITYCOUNT" > 5
ORDER BY "s1"."TOTALSCORE" DESC NULLS FIRST, "s1"."QUESTIONCOUNT" DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY) AS "t14"