SELECT COALESCE("t9"."USERID", "t9"."USERID") AS "USERID", "t9"."DISPLAYNAME", "t9"."TOTALPOSTS", "t9"."QUESTIONS", "t9"."ANSWERS", "t9"."TOTALSCORE", "t9"."AVERAGEBOUNTY", "t9"."TOTALCLOSEDPOSTS", "t9"."TOTALCLOSEDQUESTIONS", "t9"."TOTALCLOSEDANSWERS", "t9"."TOTALCLOSEREASONS"
FROM (SELECT "t5"."USERID", "t5"."DISPLAYNAME", "t5"."TOTALPOSTS", "t5"."QUESTIONS", "t5"."ANSWERS", "t5"."TOTALSCORE", "t5"."AVERAGEBOUNTY", "t7"."TOTALCLOSEDPOSTS", "t7"."TOTALCLOSEDQUESTIONS", "t7"."TOTALCLOSEDANSWERS", "t7"."TOTALCLOSEREASONS"
FROM (SELECT ANY_VALUE("t1"."Id") AS "USERID", "t1"."DisplayName" AS "DISPLAYNAME", COUNT(DISTINCT "t1"."Id0") AS "TOTALPOSTS", SUM(CASE WHEN CAST("t1"."PostTypeId" AS INTEGER) = 1 THEN 1 ELSE 0 END) AS "QUESTIONS", SUM(CASE WHEN CAST("t1"."PostTypeId" AS INTEGER) = 2 THEN 1 ELSE 0 END) AS "ANSWERS", SUM("t1"."Score") AS "TOTALSCORE", AVG("t2"."BountyAmount") AS "AVERAGEBOUNTY"
FROM (SELECT "Users"."Id", "Users"."Reputation", "Users"."CreationDate", "Users"."DisplayName", "Users"."LastAccessDate", "Users"."WebsiteUrl", "Users"."Location", "Users"."AboutMe", "Users"."Views", "Users"."UpVotes", "Users"."DownVotes", "Users"."ProfileImageUrl", "Users"."AccountId", "Posts"."Id" AS "Id0", "Posts"."PostTypeId", "Posts"."AcceptedAnswerId", "Posts"."ParentId", "Posts"."CreationDate" AS "CreationDate0", "Posts"."Score", "Posts"."ViewCount", "Posts"."Body", "Posts"."OwnerUserId", "Posts"."OwnerDisplayName", "Posts"."LastEditorUserId", "Posts"."LastEditorDisplayName", "Posts"."LastEditDate", "Posts"."LastActivityDate", "Posts"."Title", "Posts"."Tags", "Posts"."AnswerCount", "Posts"."CommentCount", "Posts"."FavoriteCount", "Posts"."ClosedDate", "Posts"."CommunityOwnedDate", "Posts"."ContentLicense"
FROM "STACK"."Posts"
RIGHT JOIN "STACK"."Users" ON "Posts"."OwnerUserId" = "Users"."Id") AS "t1"
LEFT JOIN (SELECT *
FROM "STACK"."Votes"
WHERE CAST("VoteTypeId" AS INTEGER) = 8) AS "t2" ON "t1"."Id0" = "t2"."PostId"
GROUP BY "t1"."Id", "t1"."DisplayName") AS "t5"
LEFT JOIN (SELECT "s1"."UserId" AS "USERID", COUNT(DISTINCT "s1"."PostId") AS "TOTALCLOSEDPOSTS", COUNT(DISTINCT CASE WHEN CAST("Posts0"."PostTypeId" AS INTEGER) = 1 THEN "s1"."PostId" ELSE NULL END) AS "TOTALCLOSEDQUESTIONS", COUNT(DISTINCT CASE WHEN CAST("Posts0"."PostTypeId" AS INTEGER) = 2 THEN "s1"."PostId" ELSE NULL END) AS "TOTALCLOSEDANSWERS", COUNT(DISTINCT "s1"."Comment") AS "TOTALCLOSEREASONS"
FROM "s1"
INNER JOIN "STACK"."Posts" AS "Posts0" ON "s1"."PostId" = "Posts0"."Id"
GROUP BY "s1"."UserId") AS "t7" ON "t5"."USERID" = "t7"."USERID"
ORDER BY "t5"."TOTALSCORE" DESC NULLS FIRST, "t5"."TOTALPOSTS" DESC NULLS FIRST) AS "t9"