SELECT COALESCE("POSTID", "POSTID") AS "POSTID", "TITLE", "TAGSLIST", "USERDISPLAYNAME", "TOTALPOSTS", "TOTALVIEWS", "TOTALANSWERED", "HIGHENGAGEMENTPOSTS", "TOTALMODERATIONHISTORY", "TOTALCLOSURES", "TOTALREOPENS"
FROM (SELECT "POSTID", "TITLE", "TAGSLIST", "DISPLAYNAME" AS "USERDISPLAYNAME", "TOTALPOSTS", "TOTALVIEWS", "TOTALANSWERED", "HIGHENGAGEMENTPOSTS", "TOTALMODERATIONHISTORY", "TOTALCLOSURES", "TOTALREOPENS"
FROM "s1"
ORDER BY "TOTALANSWERED" DESC NULLS FIRST) AS "t10"