SELECT COALESCE("t2"."USERID", "t2"."USERID") AS "USERID", "t2"."DISPLAYNAME", "t2"."TOTALPOSTS", "t2"."TOTALVIEWS", "t2"."TOTALANSWERED", "t2"."HIGHENGAGEMENTPOSTS", "t6"."POSTID", "t6"."TITLE", "t6"."VIEWCOUNT", "t6"."ANSWERCOUNT", "t6"."CREATIONDATE", "t6"."TAGSLIST", "t6"."TOTALMODERATIONHISTORY", "t6"."TOTALCLOSURES", "t6"."TOTALREOPENS", "t6"."POSTID0"
FROM (SELECT ANY_VALUE("Users"."Id") AS "USERID", "Users"."DisplayName" AS "DISPLAYNAME", COUNT(DISTINCT "t"."Id") AS "TOTALPOSTS", SUM("t"."ViewCount") AS "TOTALVIEWS", SUM(CASE WHEN "t"."AnswerCount" > 0 THEN 1 ELSE 0 END) AS "TOTALANSWERED", SUM(CASE WHEN "t"."ViewCount" > 100 THEN 1 ELSE 0 END) AS "HIGHENGAGEMENTPOSTS"
FROM "STACK"."Users"
INNER JOIN (SELECT *
FROM "STACK"."Posts"
WHERE "CreationDate" >= (TIMESTAMP '2024-10-01 12:34:56' - INTERVAL '1' YEAR)) AS "t" ON "Users"."Id" = "t"."OwnerUserId"
GROUP BY "Users"."Id", "Users"."DisplayName") AS "t2"
INNER JOIN (SELECT ANY_VALUE("t3"."Id") AS "POSTID", "t3"."Title" AS "TITLE", "t3"."ViewCount" AS "VIEWCOUNT", "t3"."AnswerCount" AS "ANSWERCOUNT", "t3"."CreationDate" AS "CREATIONDATE", LISTAGG(DISTINCT "Tags"."TagName", ', ') AS "TAGSLIST", COUNT(DISTINCT "PostHistory"."UserId") AS "TOTALMODERATIONHISTORY", SUM(CASE WHEN CAST("PostHistory"."PostHistoryTypeId" AS INTEGER) = 10 THEN 1 ELSE 0 END) AS "TOTALCLOSURES", SUM(CASE WHEN CAST("PostHistory"."PostHistoryTypeId" AS INTEGER) = 11 THEN 1 ELSE 0 END) AS "TOTALREOPENS", CAST(ANY_VALUE("t3"."Id") AS BIGINT) AS "POSTID0"
FROM (SELECT *
FROM "STACK"."Posts"
WHERE CAST("PostTypeId" AS INTEGER) = 1 AND "CreationDate" >= (TIMESTAMP '2024-10-01 12:34:56' - INTERVAL '1' YEAR)) AS "t3"
LEFT JOIN "STACK"."Tags" ON POSITION("Tags"."TagName" IN "t3"."Tags") > 0
LEFT JOIN "STACK"."PostHistory" ON "t3"."Id" = "PostHistory"."PostId"
GROUP BY "t3"."Id", "t3"."Title", "t3"."ViewCount", "t3"."AnswerCount", "t3"."CreationDate") AS "t6" ON "t2"."TOTALPOSTS" = "t6"."POSTID0"
WHERE "t2"."TOTALVIEWS" > 500