SELECT COALESCE("t6"."DISPLAYNAME", "t6"."DISPLAYNAME") AS "DISPLAYNAME", "t6"."BADGECOUNT", "t6"."GOLDBADGES", "t6"."SILVERBADGES", "t6"."BRONZEBADGES", "t6"."POSTCOUNT", "t6"."TOTALVIEWS", "t6"."TOTALSCORE", "t6"."AVGSCORE"
FROM (SELECT "t3"."DISPLAYNAME", "t3"."BADGECOUNT", "t3"."GOLDBADGES", "t3"."SILVERBADGES", "t3"."BRONZEBADGES", "t1"."POSTCOUNT", "t1"."TOTALVIEWS", "t1"."TOTALSCORE", "t1"."AVGSCORE"
FROM (SELECT "OwnerUserId", COUNT(*) AS "POSTCOUNT", SUM("ViewCount") AS "TOTALVIEWS", SUM("Score") AS "TOTALSCORE", AVG("Score") AS "AVGSCORE"
FROM "STACK"."Posts"
GROUP BY "OwnerUserId") AS "t1"
INNER JOIN (SELECT ANY_VALUE("Id") AS "USERID", "DISPLAYNAME", COUNT("Id0") AS "BADGECOUNT", SUM("FD_COL_3") AS "GOLDBADGES", SUM("FD_COL_4") AS "SILVERBADGES", SUM("FD_COL_5") AS "BRONZEBADGES"
FROM "s1"
GROUP BY "Id", "DISPLAYNAME") AS "t3" ON "t1"."OwnerUserId" = "t3"."USERID"
WHERE "t3"."BADGECOUNT" > 0 AND "t1"."POSTCOUNT" > 10
ORDER BY "t1"."TOTALSCORE" DESC NULLS FIRST, "t1"."TOTALVIEWS" DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY) AS "t6"