SELECT COALESCE("t6"."USERID", "t6"."USERID") AS "USERID", "t6"."DISPLAYNAME", "t6"."BADGECOUNT", "t6"."GOLDBADGES", "t6"."SILVERBADGES", "t6"."BRONZEBADGES", "t6"."TOTALPOSTS", "t6"."QUESTIONS", "t6"."ANSWERS", "t6"."TAGWIKIS", "t6"."TOTALVIEWS", "t6"."TOTALSCORE", "t6"."AVGSCOREPERPOST"
FROM (SELECT "s1"."Id" AS "USERID", "s1"."DisplayName" AS "DISPLAYNAME", "s1"."BADGECOUNT", "s1"."GOLDBADGES", "s1"."SILVERBADGES", "s1"."BRONZEBADGES", "t4"."TOTALPOSTS", "t4"."QUESTIONS", "t4"."ANSWERS", "t4"."TAGWIKIS", "t4"."TOTALVIEWS", "t4"."TOTALSCORE", CASE WHEN "t4"."TOTALPOSTS" > 0 THEN "t4"."TOTALSCORE" / CAST("t4"."TOTALPOSTS" AS FLOAT) ELSE 0E0 END AS "AVGSCOREPERPOST"
FROM (SELECT "OwnerUserId" AS "OWNERUSERID", COUNT(*) AS "TOTALPOSTS", COUNT(CASE WHEN CAST("PostTypeId" AS INTEGER) = 1 THEN 1 ELSE NULL END) AS "QUESTIONS", COUNT(CASE WHEN CAST("PostTypeId" AS INTEGER) = 2 THEN 1 ELSE NULL END) AS "ANSWERS", COUNT(CASE WHEN CAST("PostTypeId" AS INTEGER) IN (4, 5) THEN 1 ELSE NULL END) AS "TAGWIKIS", SUM("ViewCount") AS "TOTALVIEWS", SUM("Score") AS "TOTALSCORE"
FROM "STACK"."Posts"
GROUP BY "OwnerUserId") AS "t4"
INNER JOIN "s1" ON "t4"."OWNERUSERID" = "s1"."USERID"
ORDER BY 13 DESC NULLS FIRST, "s1"."BADGECOUNT" DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY) AS "t6"