SELECT COALESCE("t9"."USERID", "t9"."USERID") AS "USERID", "t9"."DisplayName" AS "DISPLAYNAME", "t9"."TOTALBADGES", "t9"."GOLDBADGES", "t9"."SILVERBADGES", "t9"."BRONZEBADGES", "t9"."RECENTPOSTCOUNT", "t9"."TOTALCOMMENTS", "t9"."TOTALVOTES"
FROM (SELECT "Users0"."Id", "Users0"."DisplayName", "t3"."TOTALBADGES", "t3"."GOLDBADGES", "t3"."SILVERBADGES", "t3"."BRONZEBADGES", ANY_VALUE("Users0"."Id") AS "USERID", COUNT("t6"."TITLE") AS "RECENTPOSTCOUNT", SUM("t6"."COMMENTCOUNT") AS "TOTALCOMMENTS", SUM("t6"."VOTECOUNT") AS "TOTALVOTES"
FROM (SELECT ANY_VALUE("Users"."Id") AS "USERID", "Users"."DisplayName" AS "DISPLAYNAME", COUNT("Badges"."Id") AS "TOTALBADGES", SUM(CASE WHEN CAST("Badges"."Class" AS INTEGER) = 1 THEN 1 ELSE 0 END) AS "GOLDBADGES", SUM(CASE WHEN CAST("Badges"."Class" AS INTEGER) = 2 THEN 1 ELSE 0 END) AS "SILVERBADGES", SUM(CASE WHEN CAST("Badges"."Class" AS INTEGER) = 3 THEN 1 ELSE 0 END) AS "BRONZEBADGES"
FROM "STACK"."Badges"
RIGHT JOIN "STACK"."Users" ON "Badges"."UserId" = "Users"."Id"
GROUP BY "Users"."Id", "Users"."DisplayName") AS "t3"
LEFT JOIN (SELECT "t4"."OwnerUserId" AS "OWNERUSERID", "t4"."Title" AS "TITLE", "t4"."CreationDate" AS "CREATIONDATE", COUNT("t4"."Id0") AS "COMMENTCOUNT", SUM(CASE WHEN "Votes"."CreationDate" IS NOT NULL THEN 1 ELSE 0 END) AS "VOTECOUNT"
FROM "STACK"."Votes"
RIGHT JOIN (SELECT "s1"."Id", "s1"."PostTypeId", "s1"."AcceptedAnswerId", "s1"."ParentId", "s1"."CreationDate", "s1"."Score", "s1"."ViewCount", "s1"."Body", "s1"."OwnerUserId", "s1"."OwnerDisplayName", "s1"."LastEditorUserId", "s1"."LastEditorDisplayName", "s1"."LastEditDate", "s1"."LastActivityDate", "s1"."Title", "s1"."Tags", "s1"."AnswerCount", "s1"."CommentCount", "s1"."FavoriteCount", "s1"."ClosedDate", "s1"."CommunityOwnedDate", "s1"."ContentLicense", "Comments"."Id" AS "Id0", "Comments"."PostId", "Comments"."Score" AS "Score0", "Comments"."Text", "Comments"."CreationDate" AS "CreationDate0", "Comments"."UserDisplayName", "Comments"."UserId", "Comments"."ContentLicense" AS "ContentLicense0"
FROM "STACK"."Comments"
RIGHT JOIN "s1" ON "Comments"."PostId" = "s1"."Id") AS "t4" ON "Votes"."PostId" = "t4"."Id"
GROUP BY "t4"."OwnerUserId", "t4"."Title", "t4"."CreationDate") AS "t6" ON "t3"."USERID" = "t6"."OWNERUSERID"
LEFT JOIN "STACK"."Users" AS "Users0" ON "t3"."USERID" = "Users0"."Id"
GROUP BY "t3"."TOTALBADGES", "t3"."GOLDBADGES", "t3"."SILVERBADGES", "t3"."BRONZEBADGES", "Users0"."Id", "Users0"."DisplayName"
ORDER BY "t3"."TOTALBADGES" DESC NULLS FIRST, 9 DESC NULLS FIRST, 8 DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY) AS "t9"