SELECT COALESCE("t13"."TAGNAME", "t13"."TAGNAME") AS "TAGNAME", "t13"."POSTCOUNT", "t13"."QUESTIONCOUNT", "t13"."ANSWERCOUNT", "t13"."AVGVIEWCOUNT", "t13"."AVGSCORE", "t13"."RECENTPOSTDATE", "t13"."ACTIVEUSER", "t13"."TOTALUPVOTES", "t13"."TOTALDOWNVOTES", "t13"."TOTALCOMMENTS", "t13"."TOTALBADGES", "t13"."TOTALPOSTS", "t13"."POSITIVEPOSTS", "t13"."POPULARPOSTS"
FROM (SELECT "t11"."TAGNAME", "t11"."POSTCOUNT", "t11"."QUESTIONCOUNT", "t11"."ANSWERCOUNT", "t11"."AVGVIEWCOUNT", "t11"."AVGSCORE", "t11"."RECENTPOSTDATE", "t11"."DISPLAYNAME" AS "ACTIVEUSER", "t11"."TOTALUPVOTES", "t11"."TOTALDOWNVOTES", "t11"."TOTALCOMMENTS", "t11"."TOTALBADGES", "t6"."TOTALPOSTS", "t6"."POSITIVEPOSTS", "t6"."POPULARPOSTS"
FROM (SELECT "OwnerDisplayName" AS "OWNERDISPLAYNAME", COUNT(*) AS "TOTALPOSTS", SUM(CASE WHEN "Score" > 0 THEN 1 ELSE 0 END) AS "POSITIVEPOSTS", SUM(CASE WHEN "ViewCount" > 100 THEN 1 ELSE 0 END) AS "POPULARPOSTS", COUNT(*) > 5 AS "$f4"
FROM "STACK"."Posts"
GROUP BY "OwnerDisplayName"
HAVING COUNT(*) > 5) AS "t6",
(SELECT "t8"."TAGNAME", "t8"."POSTCOUNT", "t8"."QUESTIONCOUNT", "t8"."ANSWERCOUNT", "t8"."AVGVIEWCOUNT", "t8"."AVGSCORE", "t8"."RECENTPOSTDATE", "t10"."DISPLAYNAME", "t10"."TOTALUPVOTES", "t10"."TOTALDOWNVOTES", "t10"."TOTALCOMMENTS", "t10"."TOTALBADGES"
FROM (SELECT "Tags"."TagName" AS "TAGNAME", COUNT(DISTINCT "Posts0"."Id") AS "POSTCOUNT", SUM(CASE WHEN CAST("Posts0"."PostTypeId" AS INTEGER) = 1 THEN 1 ELSE 0 END) AS "QUESTIONCOUNT", SUM(CASE WHEN CAST("Posts0"."PostTypeId" AS INTEGER) = 2 THEN 1 ELSE 0 END) AS "ANSWERCOUNT", AVG("Posts0"."ViewCount") AS "AVGVIEWCOUNT", AVG("Posts0"."Score") AS "AVGSCORE", MAX("Posts0"."CreationDate") AS "RECENTPOSTDATE"
FROM "STACK"."Posts" AS "Posts0"
RIGHT JOIN "STACK"."Tags" ON "Posts0"."Tags" LIKE '%' || "Tags"."TagName" || '%'
GROUP BY "Tags"."TagName") AS "t8",
(SELECT "DISPLAYNAME", "TOTALUPVOTES", "TOTALDOWNVOTES", "TOTALCOMMENTS", "TOTALBADGES", "TOTALUPVOTES" > 0 AS "$f5"
FROM "s1"
WHERE "TOTALUPVOTES" > 0) AS "t10") AS "t11"
ORDER BY "t11"."POSTCOUNT" DESC NULLS FIRST, "t11"."TOTALUPVOTES" DESC NULLS FIRST, "t6"."TOTALPOSTS" DESC NULLS FIRST) AS "t13"