SELECT COALESCE("POSTID", "POSTID") AS "POSTID", "TITLE", "VIEWCOUNT", "DISPLAYNAME", "REPUTATIONLEVEL", "UPVOTES", "DOWNVOTES", "CLOSEVOTES", "ANSWERCOUNT"
FROM (SELECT "POSTID", "TITLE", "VIEWCOUNT", "DISPLAYNAME", "REPUTATIONLEVEL", CASE WHEN "FD_COL_6" IS NOT NULL THEN CAST("FD_COL_6" AS BIGINT) ELSE 0 END AS "UPVOTES", CASE WHEN "FD_COL_7" IS NOT NULL THEN CAST("FD_COL_7" AS BIGINT) ELSE 0 END AS "DOWNVOTES", CASE WHEN "FD_COL_8" IS NOT NULL THEN CAST("FD_COL_8" AS BIGINT) ELSE 0 END AS "CLOSEVOTES", "ANSWERCOUNT"
FROM "s1"
ORDER BY "VIEWCOUNT" DESC NULLS FIRST) AS "t11"