SELECT COALESCE("t7"."DISPLAYNAME", "t7"."DISPLAYNAME") AS "DISPLAYNAME", "t7"."BADGECOUNT", "t7"."QUESTIONCOUNT", "t7"."ANSWERCOUNT", "t7"."TOTALSCORE", "t7"."AVGVIEWCOUNT", "t7"."BADGESUMMARY"
FROM (SELECT "t3"."DisplayName" AS "DISPLAYNAME", CASE WHEN "t3"."BADGECOUNT" IS NOT NULL THEN CAST("t3"."BADGECOUNT" AS BIGINT) ELSE 0 END AS "BADGECOUNT", CASE WHEN "t5"."QUESTIONCOUNT" IS NOT NULL THEN CAST("t5"."QUESTIONCOUNT" AS BIGINT) ELSE 0 END AS "QUESTIONCOUNT", CASE WHEN "t5"."ANSWERCOUNT" IS NOT NULL THEN CAST("t5"."ANSWERCOUNT" AS BIGINT) ELSE 0 END AS "ANSWERCOUNT", CASE WHEN "t5"."TOTALSCORE" IS NOT NULL THEN CAST("t5"."TOTALSCORE" AS INTEGER) ELSE 0 END AS "TOTALSCORE", CASE WHEN "t5"."AVGVIEWCOUNT" IS NOT NULL THEN CAST("t5"."AVGVIEWCOUNT" AS INTEGER) ELSE 0 END AS "AVGVIEWCOUNT", CONCAT('Gold: ', CAST(CASE WHEN "t3"."GOLDBADGES" IS NOT NULL THEN CAST("t3"."GOLDBADGES" AS INTEGER) ELSE 0 END AS VARCHAR CHARACTER SET "ISO-8859-1"), ', Silver: ', CAST(CASE WHEN "t3"."SILVERBADGES" IS NOT NULL THEN CAST("t3"."SILVERBADGES" AS INTEGER) ELSE 0 END AS VARCHAR CHARACTER SET "ISO-8859-1"), ', Bronze: ', CAST(CASE WHEN "t3"."BRONZEBADGES" IS NOT NULL THEN CAST("t3"."BRONZEBADGES" AS INTEGER) ELSE 0 END AS VARCHAR CHARACTER SET "ISO-8859-1")) AS "BADGESUMMARY"
FROM (SELECT *
FROM "STACK"."Users" AS "Users0"
LEFT JOIN (SELECT ANY_VALUE("Id") AS "USERID", "DISPLAYNAME", COUNT("Id0") AS "BADGECOUNT", SUM("FD_COL_3") AS "GOLDBADGES", SUM("FD_COL_4") AS "SILVERBADGES", SUM("FD_COL_5") AS "BRONZEBADGES"
FROM "s1"
GROUP BY "Id", "DISPLAYNAME") AS "t2" ON "Users0"."Id" = "t2"."USERID"
WHERE CASE WHEN "t2"."BADGECOUNT" IS NOT NULL THEN CAST("t2"."BADGECOUNT" AS BIGINT) ELSE 0 END > 0) AS "t3"
LEFT JOIN (SELECT "OwnerUserId" AS "OWNERUSERID", COUNT(CASE WHEN CAST("PostTypeId" AS INTEGER) = 1 THEN 1 ELSE NULL END) AS "QUESTIONCOUNT", COUNT(CASE WHEN CAST("PostTypeId" AS INTEGER) = 2 THEN 1 ELSE NULL END) AS "ANSWERCOUNT", SUM("Score") AS "TOTALSCORE", AVG("ViewCount") AS "AVGVIEWCOUNT", COUNT(DISTINCT "Tags") AS "UNIQUETAGCOUNT"
FROM "STACK"."Posts"
GROUP BY "OwnerUserId") AS "t5" ON "t3"."Id" = "t5"."OWNERUSERID"
ORDER BY 5 DESC NULLS FIRST, 2 DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY) AS "t7"