SELECT COALESCE("USERID", "USERID") AS "USERID", "DISPLAYNAME", "TOTALBADGES", "GOLDBADGES", "SILVERBADGES", "BRONZEBADGES", "POSTID", "TITLE", "COMMENTCOUNT", "UPVOTECOUNT", "DOWNVOTECOUNT"
FROM (SELECT "USERID", "DISPLAYNAME", "TOTALBADGES", "GOLDBADGES", "SILVERBADGES", "BRONZEBADGES", "POSTID", "TITLE_" AS "TITLE", "COMMENTCOUNT_" AS "COMMENTCOUNT", "UPVOTECOUNT", "DOWNVOTECOUNT"
FROM "s1"
ORDER BY "TOTALBADGES" DESC NULLS FIRST, "UPVOTECOUNT" DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY) AS "t10"