SELECT COALESCE("t11"."USERNAME", "t11"."USERNAME") AS "USERNAME", "t11"."TOTALUPVOTES", "t11"."TOTALDOWNVOTES", "t11"."POSTID", "t11"."POSTTITLE", "t11"."VIEWCOUNT", "t11"."TOTALANSWERS", "t11"."TOTALCOMMENTS", "t11"."CLOSECOUNT", "t11"."LASTCLOSEDDATE"
FROM (SELECT "s1"."DISPLAYNAME" AS "USERNAME", "s1"."TOTALUPVOTES", "s1"."TOTALDOWNVOTES", "Posts"."Id" AS "POSTID", "Posts"."Title" AS "POSTTITLE", "Posts"."ViewCount" AS "VIEWCOUNT", "t9"."TOTALANSWERS", "t9"."TOTALCOMMENTS", "t5"."CLOSECOUNT", "t5"."LASTCLOSEDDATE"
FROM (SELECT "PostId", COUNT(*) AS "CLOSECOUNT", MAX("CreationDate") AS "LASTCLOSEDDATE"
FROM "STACK"."PostHistory"
WHERE CAST("PostHistoryTypeId" AS INTEGER) = 10
GROUP BY "PostId") AS "t5"
RIGHT JOIN ("STACK"."Posts" INNER JOIN (SELECT "t8"."Id" AS "POSTID", "t8"."Title" AS "TITLE", "t8"."ViewCount" AS "VIEWCOUNT", CASE WHEN "t7"."TOTALANSWERS" IS NOT NULL THEN CAST("t7"."TOTALANSWERS" AS BIGINT) ELSE 0 END AS "TOTALANSWERS", CASE WHEN "t7"."TOTALCOMMENTS" IS NOT NULL THEN CAST("t7"."TOTALCOMMENTS" AS BIGINT) ELSE 0 END AS "TOTALCOMMENTS"
FROM (SELECT "t6"."ParentId", COUNT(*) AS "TOTALANSWERS", COUNT(DISTINCT "Comments"."Id") AS "TOTALCOMMENTS"
FROM "STACK"."Comments"
RIGHT JOIN (SELECT *
FROM "STACK"."Posts"
WHERE CAST("PostTypeId" AS INTEGER) = 2) AS "t6" ON "Comments"."PostId" = "t6"."Id"
GROUP BY "t6"."ParentId") AS "t7"
RIGHT JOIN (SELECT *
FROM "STACK"."Posts"
WHERE CAST("PostTypeId" AS INTEGER) = 1) AS "t8" ON "t7"."ParentId" = "t8"."Id") AS "t9" ON "Posts"."Id" = "t9"."POSTID" INNER JOIN "s1" ON "Posts"."OwnerUserId" = "s1"."USERID") ON "t5"."PostId" = "Posts"."Id"
ORDER BY "Posts"."ViewCount" DESC NULLS FIRST, "s1"."TOTALUPVOTES" DESC NULLS FIRST) AS "t11"