SELECT COALESCE("t10"."USERDISPLAYNAME", "t10"."USERDISPLAYNAME") AS "USERDISPLAYNAME", "t10"."TOTALREPUTATION", "t10"."BADGECOUNT", "t10"."CLOSEDPOSTS", "t10"."POSTTITLE", "t10"."POSTCREATIONDATE", "t10"."POSTUPVOTES", "t10"."POSTDOWNVOTES", "t10"."POSTAVGVOTE"
FROM (SELECT "t7"."DISPLAYNAME" AS "USERDISPLAYNAME", "t7"."TOTALREPUTATION", "t7"."BADGECOUNT", "t7"."CLOSEDPOSTS", "Posts0"."Title" AS "POSTTITLE", "Posts0"."CreationDate" AS "POSTCREATIONDATE", CASE WHEN "t5"."TOTALUPVOTES" IS NOT NULL THEN CAST("t5"."TOTALUPVOTES" AS INTEGER) ELSE 0 END AS "POSTUPVOTES", CASE WHEN "t5"."TOTALDOWNVOTES" IS NOT NULL THEN CAST("t5"."TOTALDOWNVOTES" AS INTEGER) ELSE 0 END AS "POSTDOWNVOTES", CASE WHEN "t5"."AVGVOTETYPE" IS NOT NULL THEN CAST("t5"."AVGVOTETYPE" AS INTEGER) ELSE 0 END AS "POSTAVGVOTE"
FROM (SELECT "PostId" AS "POSTID", SUM(CASE WHEN CAST("VoteTypeId" AS INTEGER) = 2 THEN 1 ELSE 0 END) AS "TOTALUPVOTES", SUM(CASE WHEN CAST("VoteTypeId" AS INTEGER) = 3 THEN 1 ELSE 0 END) AS "TOTALDOWNVOTES", AVG(CASE WHEN CAST("VoteTypeId" AS INTEGER) IN (2, 3) THEN "VoteTypeId" ELSE NULL END) AS "AVGVOTETYPE"
FROM "STACK"."Votes"
GROUP BY "PostId") AS "t5"
RIGHT JOIN ("STACK"."Posts" AS "Posts0" INNER JOIN (SELECT ANY_VALUE("Id") AS "USERID", "DisplayName" AS "DISPLAYNAME", SUM("Reputation") AS "TOTALREPUTATION", COUNT("Id0") AS "BADGECOUNT", COUNT(DISTINCT "POSTID") AS "CLOSEDPOSTS"
FROM "s1"
GROUP BY "Id", "DisplayName") AS "t7" ON "Posts0"."OwnerUserId" = "t7"."USERID") ON "t5"."POSTID" = "Posts0"."Id"
WHERE "t7"."CLOSEDPOSTS" > 0
ORDER BY "t7"."TOTALREPUTATION" DESC NULLS FIRST, "Posts0"."CreationDate" DESC NULLS FIRST
FETCH NEXT 100 ROWS ONLY) AS "t10"