SELECT COALESCE("USERID", "USERID") AS "USERID", "DISPLAYNAME", "TOTALPOSTS", "TOTALBOUNTY", "GOLDBADGES", "SILVERBADGES", "BRONZEBADGES", "RECENTPOSTSCOUNT", "AVERAGERECENTPOSTSCORE"
FROM (SELECT "USERID", "DISPLAYNAME", "TOTALPOSTS", "TOTALBOUNTY", "GOLDBADGES", "SILVERBADGES", "BRONZEBADGES", "RECENTPOSTSCOUNT", "AVERAGERECENTPOSTSCORE"
FROM "s1"
WHERE "RECENTPOSTSCOUNT" > 5 AND "FD_COL_9" >= 20
ORDER BY "TOTALBOUNTY" DESC NULLS FIRST, "AVERAGERECENTPOSTSCORE" DESC NULLS FIRST) AS "t11"