SELECT COALESCE("t7"."DISPLAYNAME", "t7"."DISPLAYNAME") AS "DISPLAYNAME", "t7"."TOTALPOSTS", "t7"."QUESTIONS", "t7"."ANSWERS", "t7"."BADGECOUNT", "t7"."AVGSCORE", "t7"."TOTALVIEWS"
FROM (SELECT "t3"."DisplayName" AS "DISPLAYNAME", "t5"."TOTALPOSTS", "t5"."QUESTIONS", "t5"."ANSWERS", CASE WHEN "s1"."BADGECOUNT" IS NOT NULL THEN CAST("s1"."BADGECOUNT" AS BIGINT) ELSE 0 END AS "BADGECOUNT", "t5"."AVGSCORE", "t5"."TOTALVIEWS"
FROM (SELECT *
FROM "STACK"."Users"
WHERE "Reputation" > 1000) AS "t3"
LEFT JOIN "s1" ON "t3"."Id" = "s1"."USERID"
LEFT JOIN (SELECT "OwnerUserId" AS "OWNERUSERID", COUNT(*) AS "TOTALPOSTS", SUM(CASE WHEN CAST("PostTypeId" AS INTEGER) = 1 THEN 1 ELSE 0 END) AS "QUESTIONS", SUM(CASE WHEN CAST("PostTypeId" AS INTEGER) = 2 THEN 1 ELSE 0 END) AS "ANSWERS", AVG("Score") AS "AVGSCORE", SUM("ViewCount") AS "TOTALVIEWS"
FROM "STACK"."Posts"
GROUP BY "OwnerUserId") AS "t5" ON "t3"."Id" = "t5"."OWNERUSERID"
ORDER BY 5 DESC NULLS FIRST, "t5"."TOTALPOSTS" DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY) AS "t7"