SELECT COALESCE("t8"."POSTID", "t8"."POSTID") AS "POSTID", "t8"."TITLE", "t8"."SCORE", "t8"."TOTALCLOSECOUNT", "t8"."OWNERDISPLAYNAME", "t8"."OWNERREPUTATION", "t8"."EFFECTIVEOWNER"
FROM (SELECT "s1"."Id" AS "POSTID", "s1"."Title" AS "TITLE", "s1"."Score" AS "SCORE", CASE WHEN "t5"."CLOSECOUNT" IS NOT NULL THEN CAST("t5"."CLOSECOUNT" AS BIGINT) ELSE 0 END AS "TOTALCLOSECOUNT", "s1"."DISPLAYNAME" AS "OWNERDISPLAYNAME", "s1"."REPUTATION" AS "OWNERREPUTATION", "s1"."DISPLAYNAME" AS "EFFECTIVEOWNER"
FROM (SELECT "PostId", COUNT(*) AS "CLOSECOUNT"
FROM "STACK"."PostHistory"
WHERE CAST("PostHistoryTypeId" AS INTEGER) = 10
GROUP BY "PostId") AS "t5"
RIGHT JOIN "s1" ON "t5"."PostId" = "s1"."Id"
WHERE CASE WHEN "t5"."CLOSECOUNT" IS NOT NULL THEN CAST("t5"."CLOSECOUNT" AS BIGINT) ELSE 0 END = 0
ORDER BY "s1"."Score" DESC NULLS FIRST, "s1"."Title") AS "t8"