SELECT COALESCE("DISPLAYNAME", "DISPLAYNAME") AS "DISPLAYNAME", "REPUTATION", COUNT("POSTID") AS "FD_COL_2", SUM("FD_COL_3") AS "RECENTCLOSEDPOSTS", LISTAGG(DISTINCT "TITLE", "FD_COL_5") AS "CLOSEDPOSTTITLES"
FROM "s1"
GROUP BY "DISPLAYNAME", "REPUTATION"
ORDER BY "REPUTATION" DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY