SELECT COALESCE("t10"."USERID", "t10"."USERID") AS "USERID", "t10"."DISPLAYNAME", "t10"."REPUTATION", "t10"."VIEWS", "t10"."UPVOTES", "t10"."DOWNVOTES", "t10"."POSTCOUNT", "t10"."QUESTIONCOUNT", "t10"."ANSWERCOUNT", "t10"."CLOSEDPOSTCOUNT", "t10"."GOLDBADGECOUNT", "t10"."EDITCOUNT"
FROM (SELECT "t8"."USERID", "t8"."DISPLAYNAME", "t8"."REPUTATION", "t8"."VIEWS", "t8"."UPVOTES", "t8"."DOWNVOTES", "t8"."POSTCOUNT", "t8"."QUESTIONCOUNT", "t8"."ANSWERCOUNT", "t8"."CLOSEDPOSTCOUNT", CASE WHEN "t8"."BADGECOUNT" IS NOT NULL THEN CAST("t8"."BADGECOUNT" AS BIGINT) ELSE 0 END AS "GOLDBADGECOUNT", CASE WHEN "t1"."EDITCOUNT" IS NOT NULL THEN CAST("t1"."EDITCOUNT" AS BIGINT) ELSE 0 END AS "EDITCOUNT"
FROM (SELECT "UserId", COUNT(*) AS "EDITCOUNT"
FROM "s1"
GROUP BY "UserId") AS "t1"
RIGHT JOIN (SELECT "t7"."USERID", "t7"."DISPLAYNAME", "t7"."REPUTATION", "t7"."VIEWS", "t7"."UPVOTES", "t7"."DOWNVOTES", "t7"."POSTCOUNT", "t7"."QUESTIONCOUNT", "t7"."ANSWERCOUNT", "t7"."CLOSEDPOSTCOUNT", "t3"."UserId" AS "USERID0", "t3"."BADGECOUNT"
FROM (SELECT "UserId", COUNT(*) AS "BADGECOUNT"
FROM "STACK"."Badges"
WHERE CAST("Class" AS INTEGER) = 1
GROUP BY "UserId") AS "t3"
RIGHT JOIN (SELECT ANY_VALUE("t4"."Id") AS "USERID", "t4"."DisplayName" AS "DISPLAYNAME", "t4"."Reputation" AS "REPUTATION", "t4"."Views" AS "VIEWS", "t4"."UpVotes" AS "UPVOTES", "t4"."DownVotes" AS "DOWNVOTES", COUNT(DISTINCT "Posts"."Id") AS "POSTCOUNT", SUM(CASE WHEN CAST("Posts"."PostTypeId" AS INTEGER) = 1 THEN 1 ELSE 0 END) AS "QUESTIONCOUNT", SUM(CASE WHEN CAST("Posts"."PostTypeId" AS INTEGER) = 2 THEN 1 ELSE 0 END) AS "ANSWERCOUNT", SUM(CASE WHEN "Posts"."ClosedDate" IS NOT NULL THEN 1 ELSE 0 END) AS "CLOSEDPOSTCOUNT"
FROM "STACK"."Posts"
RIGHT JOIN (SELECT *
FROM "STACK"."Users"
WHERE "Reputation" > 1000) AS "t4" ON "Posts"."OwnerUserId" = "t4"."Id"
GROUP BY "t4"."Id", "t4"."DisplayName", "t4"."Reputation", "t4"."Views", "t4"."UpVotes", "t4"."DownVotes") AS "t7" ON "t3"."UserId" = "t7"."USERID") AS "t8" ON "t1"."UserId" = "t8"."USERID"
ORDER BY "t8"."REPUTATION" DESC NULLS FIRST, "t8"."POSTCOUNT" DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY) AS "t10"