SELECT COALESCE("UserId", "UserId") AS "USERID", COUNT(CASE WHEN CAST("Class" AS INTEGER) = 1 THEN 1 ELSE NULL END) AS "GOLDBADGES", COUNT(CASE WHEN CAST("Class" AS INTEGER) = 2 THEN 1 ELSE NULL END) AS "SILVERBADGES", COUNT(CASE WHEN CAST("Class" AS INTEGER) = 3 THEN 1 ELSE NULL END) AS "BRONZEBADGES"
FROM "STACK"."Badges"
GROUP BY "UserId"