SELECT COALESCE("t8"."TOPUSER", "t8"."TOPUSER") AS "TOPUSER", "t8"."TOTALUPVOTES", "t8"."TOTALDOWNVOTES", "t8"."POSTCOUNT", "t8"."POPULARTAG", "t8"."TAGPOSTCOUNT", "t8"."TAGTOTALVIEWS", "t8"."ACTIVITYUSERID", "t8"."POSTTITLE", "t8"."COMMENT", "t8"."ACTIVITYDATE"
FROM (SELECT "t5"."DISPLAYNAME" AS "TOPUSER", "t5"."TOTALUPVOTES", "t5"."TOTALDOWNVOTES", "t5"."POSTCOUNT", "t6"."TagName" AS "POPULARTAG", "t6"."POSTCOUNT" AS "TAGPOSTCOUNT", "t6"."TOTALVIEWS" AS "TAGTOTALVIEWS", "t2"."USERID" AS "ACTIVITYUSERID", "t2"."POSTTITLE", "t2"."COMMENT", "t2"."CREATIONDATE" AS "ACTIVITYDATE"
FROM (SELECT "Users"."Id" AS "USERID", "Users"."DisplayName" AS "DISPLAYNAME", "t1"."CreationDate" AS "CREATIONDATE", "t1"."Comment" AS "COMMENT", "Posts0"."Title" AS "POSTTITLE"
FROM "STACK"."Users"
INNER JOIN ("STACK"."Posts" AS "Posts0" INNER JOIN (SELECT *
FROM "STACK"."PostHistory"
WHERE "CreationDate" >= (TIMESTAMP '2024-10-01 12:34:56' - INTERVAL '1' MONTH)) AS "t1" ON "Posts0"."Id" = "t1"."PostId") ON "Users"."Id" = "t1"."UserId") AS "t2"
RIGHT JOIN (SELECT ANY_VALUE("t3"."Id") AS "USERID", "t3"."DisplayName" AS "DISPLAYNAME", SUM("t3"."UpVotes") AS "TOTALUPVOTES", SUM("t3"."DownVotes") AS "TOTALDOWNVOTES", COUNT(DISTINCT "Posts1"."Id") AS "POSTCOUNT"
FROM "STACK"."Posts" AS "Posts1"
RIGHT JOIN (SELECT *
FROM "STACK"."Users"
WHERE "CreationDate" >= (TIMESTAMP '2024-10-01 12:34:56' - INTERVAL '1' YEAR)) AS "t3" ON "Posts1"."OwnerUserId" = "t3"."Id"
GROUP BY "t3"."Id", "t3"."DisplayName") AS "t5" ON "t2"."USERID" = "t5"."USERID"
CROSS JOIN (SELECT "TagName", "POSTCOUNT", "TOTALVIEWS"
FROM "s1"
ORDER BY "POSTCOUNT" DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY) AS "t6"
ORDER BY "t5"."TOTALUPVOTES" DESC NULLS FIRST, "t6"."POSTCOUNT" DESC NULLS FIRST, "t2"."CREATIONDATE" DESC NULLS FIRST) AS "t8"