SELECT COALESCE("t8"."USERID", "t8"."USERID") AS "USERID", "t8"."DISPLAYNAME", "t8"."BADGECOUNT", "t8"."TOTALPOSTS", "t8"."QUESTIONS", "t8"."ANSWERS", "t8"."TOTALSCORE", "t8"."AVGVIEWCOUNT"
FROM (SELECT "s1"."Id" AS "USERID", "s1"."DisplayName" AS "DISPLAYNAME", "t6"."BADGECOUNT", "s1"."TOTALPOSTS", "s1"."QUESTIONS", "s1"."ANSWERS", "s1"."TOTALSCORE", "s1"."AVGVIEWCOUNT"
FROM "s1"
INNER JOIN (SELECT ANY_VALUE("Users0"."Id") AS "USERID", "Users0"."DisplayName" AS "DISPLAYNAME", COUNT("Badges"."Id") AS "BADGECOUNT", SUM(CASE WHEN CAST("Badges"."Class" AS INTEGER) = 1 THEN 1 ELSE 0 END) AS "GOLDBADGES", SUM(CASE WHEN CAST("Badges"."Class" AS INTEGER) = 2 THEN 1 ELSE 0 END) AS "SILVERBADGES", SUM(CASE WHEN CAST("Badges"."Class" AS INTEGER) = 3 THEN 1 ELSE 0 END) AS "BRONZEBADGES"
FROM "STACK"."Badges"
RIGHT JOIN "STACK"."Users" AS "Users0" ON "Badges"."UserId" = "Users0"."Id"
GROUP BY "Users0"."Id", "Users0"."DisplayName") AS "t6" ON "s1"."Id" = "t6"."USERID"
ORDER BY "s1"."TOTALSCORE" DESC NULLS FIRST, "t6"."BADGECOUNT" DESC NULLS FIRST
FETCH NEXT 100 ROWS ONLY) AS "t8"