SELECT COALESCE("t8"."USERID", "t8"."USERID") AS "USERID", "t8"."DISPLAYNAME", "t8"."REPUTATION", "t8"."CREATIONDATE", "t8"."TOTALPOSTS", "t8"."TOTALQUESTIONS", "t8"."TOTALANSWERS", "t8"."TOTALUPVOTES", "t8"."TOTALDOWNVOTES", "t8"."TOTALBADGES", "t8"."GOLDBADGES", "t8"."SILVERBADGES", "t8"."BRONZEBADGES"
FROM (SELECT "t5"."USERID", "t5"."DISPLAYNAME", "t5"."REPUTATION", "t5"."CREATIONDATE", "t5"."TOTALPOSTS", "t5"."TOTALQUESTIONS", "t5"."TOTALANSWERS", "t5"."TOTALUPVOTES", "t5"."TOTALDOWNVOTES", CASE WHEN "s1"."TOTALBADGES" IS NOT NULL THEN CAST("s1"."TOTALBADGES" AS BIGINT) ELSE 0 END AS "TOTALBADGES", CASE WHEN "s1"."GOLDBADGES" IS NOT NULL THEN CAST("s1"."GOLDBADGES" AS INTEGER) ELSE 0 END AS "GOLDBADGES", CASE WHEN "s1"."SILVERBADGES" IS NOT NULL THEN CAST("s1"."SILVERBADGES" AS INTEGER) ELSE 0 END AS "SILVERBADGES", CASE WHEN "s1"."BRONZEBADGES" IS NOT NULL THEN CAST("s1"."BRONZEBADGES" AS INTEGER) ELSE 0 END AS "BRONZEBADGES"
FROM "s1"
RIGHT JOIN (SELECT ANY_VALUE("t2"."Id") AS "USERID", "t2"."DisplayName" AS "DISPLAYNAME", "t2"."Reputation" AS "REPUTATION", "t2"."CreationDate" AS "CREATIONDATE", COUNT(DISTINCT "t2"."Id0") AS "TOTALPOSTS", COUNT(DISTINCT CASE WHEN CAST("t2"."PostTypeId" AS INTEGER) = 1 THEN "t2"."Id0" ELSE NULL END) AS "TOTALQUESTIONS", COUNT(DISTINCT CASE WHEN CAST("t2"."PostTypeId" AS INTEGER) = 2 THEN "t2"."Id0" ELSE NULL END) AS "TOTALANSWERS", SUM(CASE WHEN CAST("Votes"."VoteTypeId" AS INTEGER) = 2 THEN 1 ELSE 0 END) AS "TOTALUPVOTES", SUM(CASE WHEN CAST("Votes"."VoteTypeId" AS INTEGER) = 3 THEN 1 ELSE 0 END) AS "TOTALDOWNVOTES"
FROM "STACK"."Votes"
RIGHT JOIN (SELECT "Users"."Id", "Users"."Reputation", "Users"."CreationDate", "Users"."DisplayName", "Users"."LastAccessDate", "Users"."WebsiteUrl", "Users"."Location", "Users"."AboutMe", "Users"."Views", "Users"."UpVotes", "Users"."DownVotes", "Users"."ProfileImageUrl", "Users"."AccountId", "Posts"."Id" AS "Id0", "Posts"."PostTypeId", "Posts"."AcceptedAnswerId", "Posts"."ParentId", "Posts"."CreationDate" AS "CreationDate0", "Posts"."Score", "Posts"."ViewCount", "Posts"."Body", "Posts"."OwnerUserId", "Posts"."OwnerDisplayName", "Posts"."LastEditorUserId", "Posts"."LastEditorDisplayName", "Posts"."LastEditDate", "Posts"."LastActivityDate", "Posts"."Title", "Posts"."Tags", "Posts"."AnswerCount", "Posts"."CommentCount", "Posts"."FavoriteCount", "Posts"."ClosedDate", "Posts"."CommunityOwnedDate", "Posts"."ContentLicense"
FROM "STACK"."Posts"
RIGHT JOIN "STACK"."Users" ON "Posts"."OwnerUserId" = "Users"."Id") AS "t2" ON "Votes"."PostId" = "t2"."Id0"
GROUP BY "t2"."Id", "t2"."DisplayName", "t2"."Reputation", "t2"."CreationDate") AS "t5" ON "s1"."USERID" = "t5"."USERID"
WHERE "t5"."REPUTATION" > 1000
ORDER BY "t5"."TOTALPOSTS" DESC NULLS FIRST, "t5"."TOTALUPVOTES" DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY) AS "t8"