SELECT COALESCE("t7"."USERID", "t7"."USERID") AS "USERID", "t7"."DISPLAYNAME", "t7"."BADGECOUNT", "t7"."GOLDBADGES", "t7"."SILVERBADGES", "t7"."BRONZEBADGES", "t7"."POSTCOUNT", "t7"."SCOREPOSITIVE", "t7"."QUESTIONS", "t7"."ANSWERS"
FROM (SELECT "s1"."USERID", "s1"."DISPLAYNAME", "s1"."BADGECOUNT", "s1"."GOLDBADGES", "s1"."SILVERBADGES", "s1"."BRONZEBADGES", "t5"."POSTCOUNT", "t5"."SCOREPOSITIVE", "t5"."QUESTIONS", "t5"."ANSWERS"
FROM "s1"
LEFT JOIN (SELECT "OwnerUserId" AS "OWNERUSERID", COUNT(*) AS "POSTCOUNT", SUM(CASE WHEN "Score" > 0 THEN 1 ELSE 0 END) AS "SCOREPOSITIVE", SUM(CASE WHEN CAST("PostTypeId" AS INTEGER) = 1 THEN 1 ELSE 0 END) AS "QUESTIONS", SUM(CASE WHEN CAST("PostTypeId" AS INTEGER) = 2 THEN 1 ELSE 0 END) AS "ANSWERS"
FROM "STACK"."Posts"
WHERE "CreationDate" >= CAST((DATE '2024-10-01' - INTERVAL '1' YEAR) AS TIMESTAMP(0))
GROUP BY "OwnerUserId") AS "t5" ON "s1"."USERID" = "t5"."OWNERUSERID"
ORDER BY "s1"."BADGECOUNT" DESC NULLS FIRST, "t5"."SCOREPOSITIVE" DESC NULLS FIRST, "t5"."POSTCOUNT" DESC NULLS FIRST
FETCH NEXT 100 ROWS ONLY) AS "t7"