SELECT COALESCE("OwnerUserId", "OwnerUserId") AS "OWNERUSERID", COUNT(*) AS "TOTALPOSTS", COUNT(DISTINCT CASE WHEN CAST("PostTypeId" AS INTEGER) = 1 THEN "Id" ELSE NULL END) AS "QUESTIONS", COUNT(DISTINCT CASE WHEN CAST("PostTypeId" AS INTEGER) = 2 THEN "Id" ELSE NULL END) AS "ANSWERS", AVG("Score") AS "AVGPOSTSCORE", SUM("ViewCount") AS "TOTALVIEWS"
FROM "STACK"."Posts"
GROUP BY "OwnerUserId"