SELECT COALESCE("t7"."DISPLAYNAME", "t7"."DISPLAYNAME") AS "DISPLAYNAME", "t7"."REPUTATION", "t7"."POSTCOUNT", "t7"."POPULARPOSTS", "t7"."HIGHSCOREPOSTS", "t7"."BADGECOUNT", "t7"."USERTIER"
FROM (SELECT "t4"."DISPLAYNAME", "t4"."REPUTATION", "t4"."POSTCOUNT", "t4"."POPULARPOSTS", "t4"."HIGHSCOREPOSTS", CASE WHEN "s1"."BADGECOUNT" IS NOT NULL THEN CAST("s1"."BADGECOUNT" AS BIGINT) ELSE 0 END AS "BADGECOUNT", CASE WHEN "t4"."REPUTATION" > 1000 THEN 'Elite ' WHEN "t4"."REPUTATION" > 500 THEN 'Pro   ' ELSE 'Novice' END AS "USERTIER"
FROM "s1"
RIGHT JOIN (SELECT ANY_VALUE("t1"."Id") AS "USERID", "t1"."DisplayName" AS "DISPLAYNAME", "t1"."Reputation" AS "REPUTATION", COUNT(DISTINCT "Posts"."Id") AS "POSTCOUNT", SUM(CASE WHEN "Posts"."ViewCount" > 1000 THEN 1 ELSE 0 END) AS "POPULARPOSTS", SUM(CASE WHEN "Posts"."Score" > 50 THEN 1 ELSE 0 END) AS "HIGHSCOREPOSTS"
FROM "STACK"."Posts"
RIGHT JOIN (SELECT *
FROM "STACK"."Users"
WHERE "Reputation" > 100) AS "t1" ON "Posts"."OwnerUserId" = "t1"."Id"
GROUP BY "t1"."Id", "t1"."DisplayName", "t1"."Reputation") AS "t4" ON "s1"."UserId" = "t4"."USERID"
WHERE "t4"."POSTCOUNT" > 10
ORDER BY "t4"."REPUTATION" DESC NULLS FIRST, "t4"."POSTCOUNT" DESC NULLS FIRST
FETCH NEXT 20 ROWS ONLY) AS "t7"