SELECT COALESCE("t7"."DISPLAYNAME", "t7"."DISPLAYNAME") AS "DISPLAYNAME", "t7"."REPUTATION", "t7"."TOTALUPVOTES", "t7"."TOTALDOWNVOTES", "t7"."TOTALQUESTIONS", "t7"."TOTALANSWERS", "t7"."AVGSCORE", "t7"."TOTALVIEWS", "t7"."ENGAGEMENTCATEGORY"
FROM (SELECT "s1"."DISPLAYNAME", "s1"."REPUTATION", "s1"."TOTALUPVOTES", "s1"."TOTALDOWNVOTES", "t4"."TOTALQUESTIONS", "t4"."TOTALANSWERS", "t4"."AVGSCORE", "t4"."TOTALVIEWS", CASE WHEN "t4"."TOTALANSWERS" > "t4"."TOTALQUESTIONS" THEN 'High Answer Rate   ' WHEN "s1"."TOTALUPVOTES" > "s1"."TOTALDOWNVOTES" THEN 'Positive Engagement' ELSE 'Needs Improvement  ' END AS "ENGAGEMENTCATEGORY"
FROM (SELECT "OwnerUserId" AS "OWNERUSERID", COUNT(CASE WHEN CAST("PostTypeId" AS INTEGER) = 1 THEN 1 ELSE NULL END) AS "TOTALQUESTIONS", COUNT(CASE WHEN CAST("PostTypeId" AS INTEGER) = 2 THEN 1 ELSE NULL END) AS "TOTALANSWERS", AVG("Score") AS "AVGSCORE", SUM("ViewCount") AS "TOTALVIEWS"
FROM "STACK"."Posts"
GROUP BY "OwnerUserId") AS "t4"
RIGHT JOIN "s1" ON "t4"."OWNERUSERID" = "s1"."USERID"
WHERE "s1"."REPUTATION" > 100
ORDER BY "s1"."REPUTATION" DESC NULLS FIRST, "s1"."TOTALUPVOTES" DESC NULLS FIRST) AS "t7"