SELECT COALESCE("t5"."DISPLAYNAME", "t5"."DISPLAYNAME") AS "DISPLAYNAME", "t5"."POSTCOUNT", "t5"."QUESTIONCOUNT", "t5"."ANSWERCOUNT", "t5"."AVGSCORE", "t5"."TOTALVIEWS", "t5"."TOTALCOMMENTS", "t5"."BADGECOUNT", "t5"."HIGHESTBADGECLASS"
FROM (SELECT "t3"."DisplayName" AS "DISPLAYNAME", "s1"."POSTCOUNT", "s1"."QUESTIONCOUNT", "s1"."ANSWERCOUNT", "s1"."AVGSCORE", "s1"."TOTALVIEWS", "s1"."TOTALCOMMENTS", CASE WHEN "t2"."BADGECOUNT" IS NOT NULL THEN CAST("t2"."BADGECOUNT" AS BIGINT) ELSE 0 END AS "BADGECOUNT", CASE WHEN "t2"."HIGHESTBADGECLASS" IS NOT NULL THEN CAST("t2"."HIGHESTBADGECLASS" AS INTEGER) ELSE 0 END AS "HIGHESTBADGECLASS"
FROM (SELECT "UserId", COUNT(*) AS "BADGECOUNT", MAX("Class") AS "HIGHESTBADGECLASS"
FROM "STACK"."Badges"
GROUP BY "UserId") AS "t2"
RIGHT JOIN ((SELECT *
FROM "STACK"."Users"
WHERE "Reputation" > 1000) AS "t3" INNER JOIN "s1" ON "t3"."Id" = "s1"."OWNERUSERID") ON "t2"."UserId" = "t3"."Id"
ORDER BY "s1"."AVGSCORE" DESC NULLS FIRST, "s1"."TOTALVIEWS" DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY) AS "t5"