SELECT COALESCE("t7"."DISPLAYNAME", "t7"."DISPLAYNAME") AS "DISPLAYNAME", "t7"."REPUTATION", "t7"."POSTCOUNT", "t7"."QUESTIONCOUNT", "t7"."ANSWERCOUNT", "t7"."ACCEPTEDANSWERS", "t7"."POPULARPOSTS", "t7"."BADGECOUNT", "t7"."GOLDBADGES", "t7"."SILVERBADGES", "t7"."BRONZEBADGES"
FROM (SELECT "t4"."DISPLAYNAME", "t4"."REPUTATION", "t4"."POSTCOUNT", "t4"."QUESTIONCOUNT", "t4"."ANSWERCOUNT", "t4"."ACCEPTEDANSWERS", "t4"."POPULARPOSTS", CASE WHEN "t2"."BADGECOUNT" IS NOT NULL THEN CAST("t2"."BADGECOUNT" AS BIGINT) ELSE 0 END AS "BADGECOUNT", CASE WHEN "t2"."GOLDBADGES" IS NOT NULL THEN CAST("t2"."GOLDBADGES" AS INTEGER) ELSE 0 END AS "GOLDBADGES", CASE WHEN "t2"."SILVERBADGES" IS NOT NULL THEN CAST("t2"."SILVERBADGES" AS INTEGER) ELSE 0 END AS "SILVERBADGES", CASE WHEN "t2"."BRONZEBADGES" IS NOT NULL THEN CAST("t2"."BRONZEBADGES" AS INTEGER) ELSE 0 END AS "BRONZEBADGES"
FROM (SELECT "UserId" AS "USERID", COUNT(*) AS "BADGECOUNT", SUM(CASE WHEN CAST("Class" AS INTEGER) = 1 THEN 1 ELSE 0 END) AS "GOLDBADGES", SUM(CASE WHEN CAST("Class" AS INTEGER) = 2 THEN 1 ELSE 0 END) AS "SILVERBADGES", SUM(CASE WHEN CAST("Class" AS INTEGER) = 3 THEN 1 ELSE 0 END) AS "BRONZEBADGES"
FROM "STACK"."Badges"
GROUP BY "UserId") AS "t2"
RIGHT JOIN (SELECT ANY_VALUE("Id") AS "USERID", "DISPLAYNAME", "REPUTATION", COUNT(DISTINCT "Id0") AS "POSTCOUNT", SUM("FD_COL_4") AS "QUESTIONCOUNT", SUM("FD_COL_5") AS "ANSWERCOUNT", SUM("FD_COL_6") AS "ACCEPTEDANSWERS", SUM("FD_COL_7") AS "POPULARPOSTS"
FROM "s1"
GROUP BY "Id", "DISPLAYNAME", "REPUTATION") AS "t4" ON "t2"."USERID" = "t4"."USERID"
WHERE "t4"."REPUTATION" > 1000 AND "t4"."POSTCOUNT" > 10
ORDER BY "t4"."REPUTATION" DESC NULLS FIRST, "t4"."POSTCOUNT" DESC NULLS FIRST
FETCH NEXT 100 ROWS ONLY) AS "t7"