SELECT COALESCE("t8"."USERID", "t8"."USERID") AS "USERID", "t8"."DISPLAYNAME", "t8"."REPUTATION", "t8"."UPVOTES", "t8"."DOWNVOTES", "t8"."USERTOTALPOSTS", "t8"."AVERAGESCORE", "t8"."TIMESCLOSED", "t8"."TIMESREOPENED", "t8"."HOTQUESTIONCHANGES"
FROM (SELECT "Users0"."Id" AS "USERID", "Users0"."DisplayName" AS "DISPLAYNAME", "Users0"."Reputation" AS "REPUTATION", "s1"."UPVOTES", "s1"."DOWNVOTES", "t5"."TOTALPOSTS" AS "USERTOTALPOSTS", "t5"."AVERAGESCORE", "t5"."TIMESCLOSED", "t5"."TIMESREOPENED", "t5"."HOTQUESTIONCHANGES"
FROM "STACK"."Users" AS "Users0"
INNER JOIN (SELECT "Posts0"."OwnerUserId" AS "OWNERUSERID", COUNT(*) AS "TOTALPOSTS", AVG("Posts0"."Score") AS "AVERAGESCORE", SUM(CASE WHEN CAST("PostHistory"."PostHistoryTypeId" AS INTEGER) = 10 THEN 1 ELSE 0 END) AS "TIMESCLOSED", SUM(CASE WHEN CAST("PostHistory"."PostHistoryTypeId" AS INTEGER) = 11 THEN 1 ELSE 0 END) AS "TIMESREOPENED", SUM(CASE WHEN CAST("PostHistory"."PostHistoryTypeId" AS INTEGER) IN (52, 53) THEN 1 ELSE 0 END) AS "HOTQUESTIONCHANGES"
FROM "STACK"."PostHistory"
RIGHT JOIN "STACK"."Posts" AS "Posts0" ON "PostHistory"."PostId" = "Posts0"."Id"
GROUP BY "Posts0"."OwnerUserId") AS "t5" ON "Users0"."Id" = "t5"."OWNERUSERID"
INNER JOIN "s1" ON "t5"."OWNERUSERID" = "s1"."USERID"
WHERE "Users0"."Reputation" > 1000
ORDER BY "s1"."UPVOTES" DESC NULLS FIRST, "t5"."AVERAGESCORE" DESC NULLS FIRST
FETCH NEXT 50 ROWS ONLY) AS "t8"