SELECT COALESCE("t115"."USERID", "t115"."USERID") AS "USERID", "t115"."DISPLAYNAME", "t115"."TOTALPOSTS", "t115"."TOTALSCORE", "t115"."UPVOTECOUNT", "t115"."DOWNVOTECOUNT", "t115"."AVGCOMMENTSPERPOST", "t115"."SCORECATEGORY", "t115"."GOLDBADGES", "t115"."SILVERBADGES", "t115"."BRONZEBADGES"
FROM (SELECT "t53"."USERID", "t53"."DISPLAYNAME", "t53"."TOTALPOSTS", "t53"."TOTALSCORE", "t53"."UPVOTECOUNT", "t53"."DOWNVOTECOUNT", "t53"."AVGCOMMENTSPERPOST", CASE WHEN "t53"."TOTALSCORE" > 100 THEN 'High Scorer  ' WHEN "t53"."TOTALSCORE" >= 50 AND "t53"."TOTALSCORE" <= 100 THEN 'Medium Scorer' ELSE 'Low Scorer   ' END AS "SCORECATEGORY", "t53"."EXPR$0" AS "GOLDBADGES", "t53"."EXPR$08" AS "SILVERBADGES", CASE WHEN "t112"."EXPR$0" IS NULL THEN 0 ELSE "t112"."EXPR$0" END AS "BRONZEBADGES"
FROM (SELECT "t37"."USERID", "t37"."DISPLAYNAME", "t37"."TOTALPOSTS", "t37"."TOTALSCORE", "t37"."UPVOTECOUNT", "t37"."DOWNVOTECOUNT", "t37"."AVGCOMMENTSPERPOST", "t37"."EXPR$0", CASE WHEN "t52"."EXPR$0" IS NULL THEN 0 ELSE "t52"."EXPR$0" END AS "EXPR$08"
FROM (SELECT "t22"."USERID", "t22"."DISPLAYNAME", "t22"."TOTALPOSTS", "t22"."TOTALSCORE", "t22"."UPVOTECOUNT", "t22"."DOWNVOTECOUNT", "t22"."AVGCOMMENTSPERPOST", CASE WHEN "t36"."EXPR$0" IS NULL THEN 0 ELSE "t36"."EXPR$0" END AS "EXPR$0"
FROM (SELECT ANY_VALUE("t18"."Id") AS "USERID", "t18"."DisplayName" AS "DISPLAYNAME", COUNT(DISTINCT "Posts2"."Id") AS "TOTALPOSTS", SUM("Posts2"."Score") AS "TOTALSCORE", SUM("t18"."UpVotes") AS "UPVOTECOUNT", SUM("t18"."DownVotes") AS "DOWNVOTECOUNT", AVG(CASE WHEN "t18"."COMMENTCOUNT" IS NOT NULL THEN CAST("t18"."COMMENTCOUNT" AS BIGINT) ELSE 0 END) AS "AVGCOMMENTSPERPOST"
FROM (SELECT "Users0"."Id", "Users0"."Reputation", "Users0"."CreationDate", "Users0"."DisplayName", "Users0"."LastAccessDate", "Users0"."WebsiteUrl", "Users0"."Location", "Users0"."AboutMe", "Users0"."Views", "Users0"."UpVotes", "Users0"."DownVotes", "Users0"."ProfileImageUrl", "Users0"."AccountId", "t17"."POSTID", "t17"."TITLE", "t17"."SCORE", "t17"."CREATIONDATE", "t17"."OWNERUSERID", "t17"."RAN", "t17"."COMMENTCOUNT"
FROM (SELECT "t16"."Id" AS "POSTID", "t16"."Title" AS "TITLE", "t16"."Score" AS "SCORE", "t16"."CreationDate" AS "CREATIONDATE", "t16"."OwnerUserId" AS "OWNERUSERID", RANK() OVER (PARTITION BY "t16"."OwnerUserId" ORDER BY "t16"."Score" DESC NULLS FIRST) AS "RAN", CASE WHEN "t15"."COMMENTCOUNT" IS NOT NULL THEN CAST("t15"."COMMENTCOUNT" AS BIGINT) ELSE 0 END AS "COMMENTCOUNT"
FROM (SELECT "PostId", COUNT(*) AS "COMMENTCOUNT"
FROM "STACK"."Comments"
GROUP BY "PostId") AS "t15"
RIGHT JOIN (SELECT *
FROM "STACK"."Posts"
WHERE "CreationDate" >= (TIMESTAMP '2024-10-01 12:34:56' - INTERVAL '1' YEAR)) AS "t16" ON "t15"."PostId" = "t16"."Id") AS "t17"
RIGHT JOIN "STACK"."Users" AS "Users0" ON "t17"."OWNERUSERID" = "Users0"."Id") AS "t18"
LEFT JOIN "STACK"."Posts" AS "Posts2" ON "t18"."Id" = "Posts2"."OwnerUserId"
GROUP BY "t18"."Id", "t18"."DisplayName"
HAVING COUNT(DISTINCT "Posts2"."Id") > 0) AS "t22"
LEFT JOIN (SELECT "t32"."USERID" AS "UserId", CASE WHEN "t35"."EXPR$0" IS NOT NULL THEN "t35"."EXPR$0" ELSE 0 END AS "EXPR$0"
FROM (SELECT "t31"."USERID"
FROM (SELECT ANY_VALUE("t27"."Id") AS "USERID"
FROM (SELECT "Users1"."Id", "Users1"."Reputation", "Users1"."CreationDate", "Users1"."DisplayName", "Users1"."LastAccessDate", "Users1"."WebsiteUrl", "Users1"."Location", "Users1"."AboutMe", "Users1"."Views", "Users1"."UpVotes", "Users1"."DownVotes", "Users1"."ProfileImageUrl", "Users1"."AccountId", "t26"."POSTID", "t26"."TITLE", "t26"."SCORE", "t26"."CREATIONDATE", "t26"."OWNERUSERID", "t26"."RAN", "t26"."COMMENTCOUNT"
FROM (SELECT "t25"."Id" AS "POSTID", "t25"."Title" AS "TITLE", "t25"."Score" AS "SCORE", "t25"."CreationDate" AS "CREATIONDATE", "t25"."OwnerUserId" AS "OWNERUSERID", RANK() OVER (PARTITION BY "t25"."OwnerUserId" ORDER BY "t25"."Score" DESC NULLS FIRST) AS "RAN", CASE WHEN "t24"."COMMENTCOUNT" IS NOT NULL THEN CAST("t24"."COMMENTCOUNT" AS BIGINT) ELSE 0 END AS "COMMENTCOUNT"
FROM (SELECT "PostId", COUNT(*) AS "COMMENTCOUNT"
FROM "STACK"."Comments"
GROUP BY "PostId") AS "t24"
RIGHT JOIN (SELECT *
FROM "STACK"."Posts"
WHERE "CreationDate" >= (TIMESTAMP '2024-10-01 12:34:56' - INTERVAL '1' YEAR)) AS "t25" ON "t24"."PostId" = "t25"."Id") AS "t26"
RIGHT JOIN "STACK"."Users" AS "Users1" ON "t26"."OWNERUSERID" = "Users1"."Id") AS "t27"
LEFT JOIN "STACK"."Posts" AS "Posts4" ON "t27"."Id" = "Posts4"."OwnerUserId"
GROUP BY "t27"."Id", "t27"."DisplayName"
HAVING COUNT(DISTINCT "Posts4"."Id") > 0) AS "t31"
GROUP BY "t31"."USERID") AS "t32"
LEFT JOIN (SELECT "UserId", COUNT(*) AS "EXPR$0"
FROM "STACK"."Badges"
WHERE CAST("Class" AS INTEGER) = 1
GROUP BY "UserId") AS "t35" ON "t32"."USERID" IS NOT DISTINCT FROM "t35"."UserId") AS "t36" ON "t22"."USERID" = "t36"."UserId") AS "t37"
LEFT JOIN (SELECT "t48"."USERID" AS "UserId", CASE WHEN "t51"."EXPR$0" IS NOT NULL THEN "t51"."EXPR$0" ELSE 0 END AS "EXPR$0"
FROM (SELECT "t46"."USERID"
FROM (SELECT ANY_VALUE("t42"."Id") AS "USERID", "t42"."DisplayName" AS "DISPLAYNAME", COUNT(DISTINCT "Posts6"."Id") AS "TOTALPOSTS", SUM("Posts6"."Score") AS "TOTALSCORE", SUM("t42"."UpVotes") AS "UPVOTECOUNT", SUM("t42"."DownVotes") AS "DOWNVOTECOUNT", AVG(CASE WHEN "t42"."COMMENTCOUNT" IS NOT NULL THEN CAST("t42"."COMMENTCOUNT" AS BIGINT) ELSE 0 END) AS "AVGCOMMENTSPERPOST"
FROM (SELECT "Users2"."Id", "Users2"."Reputation", "Users2"."CreationDate", "Users2"."DisplayName", "Users2"."LastAccessDate", "Users2"."WebsiteUrl", "Users2"."Location", "Users2"."AboutMe", "Users2"."Views", "Users2"."UpVotes", "Users2"."DownVotes", "Users2"."ProfileImageUrl", "Users2"."AccountId", "t41"."POSTID", "t41"."TITLE", "t41"."SCORE", "t41"."CREATIONDATE", "t41"."OWNERUSERID", "t41"."RAN", "t41"."COMMENTCOUNT"
FROM (SELECT "t40"."Id" AS "POSTID", "t40"."Title" AS "TITLE", "t40"."Score" AS "SCORE", "t40"."CreationDate" AS "CREATIONDATE", "t40"."OwnerUserId" AS "OWNERUSERID", RANK() OVER (PARTITION BY "t40"."OwnerUserId" ORDER BY "t40"."Score" DESC NULLS FIRST) AS "RAN", CASE WHEN "t39"."COMMENTCOUNT" IS NOT NULL THEN CAST("t39"."COMMENTCOUNT" AS BIGINT) ELSE 0 END AS "COMMENTCOUNT"
FROM (SELECT "PostId", COUNT(*) AS "COMMENTCOUNT"
FROM "STACK"."Comments"
GROUP BY "PostId") AS "t39"
RIGHT JOIN (SELECT *
FROM "STACK"."Posts"
WHERE "CreationDate" >= (TIMESTAMP '2024-10-01 12:34:56' - INTERVAL '1' YEAR)) AS "t40" ON "t39"."PostId" = "t40"."Id") AS "t41"
RIGHT JOIN "STACK"."Users" AS "Users2" ON "t41"."OWNERUSERID" = "Users2"."Id") AS "t42"
LEFT JOIN "STACK"."Posts" AS "Posts6" ON "t42"."Id" = "Posts6"."OwnerUserId"
GROUP BY "t42"."Id", "t42"."DisplayName"
HAVING COUNT(DISTINCT "Posts6"."Id") > 0) AS "t46"
LEFT JOIN "s1" ON "t46"."USERID" = "s1"."UserId"
GROUP BY "t46"."USERID") AS "t48"
LEFT JOIN (SELECT "UserId", COUNT(*) AS "EXPR$0"
FROM "STACK"."Badges"
WHERE CAST("Class" AS INTEGER) = 2
GROUP BY "UserId") AS "t51" ON "t48"."USERID" IS NOT DISTINCT FROM "t51"."UserId") AS "t52" ON "t37"."USERID" = "t52"."UserId") AS "t53"
LEFT JOIN (SELECT "t108"."USERID" AS "UserId", CASE WHEN "t111"."EXPR$0" IS NOT NULL THEN "t111"."EXPR$0" ELSE 0 END AS "EXPR$0"
FROM (SELECT "t77"."USERID"
FROM (SELECT "t62"."USERID", "t62"."DISPLAYNAME", "t62"."TOTALPOSTS", "t62"."TOTALSCORE", "t62"."UPVOTECOUNT", "t62"."DOWNVOTECOUNT", "t62"."AVGCOMMENTSPERPOST", CASE WHEN "t76"."EXPR$0" IS NULL THEN 0 ELSE "t76"."EXPR$0" END AS "EXPR$0"
FROM (SELECT ANY_VALUE("t58"."Id") AS "USERID", "t58"."DisplayName" AS "DISPLAYNAME", COUNT(DISTINCT "Posts8"."Id") AS "TOTALPOSTS", SUM("Posts8"."Score") AS "TOTALSCORE", SUM("t58"."UpVotes") AS "UPVOTECOUNT", SUM("t58"."DownVotes") AS "DOWNVOTECOUNT", AVG(CASE WHEN "t58"."COMMENTCOUNT" IS NOT NULL THEN CAST("t58"."COMMENTCOUNT" AS BIGINT) ELSE 0 END) AS "AVGCOMMENTSPERPOST"
FROM (SELECT "Users3"."Id", "Users3"."Reputation", "Users3"."CreationDate", "Users3"."DisplayName", "Users3"."LastAccessDate", "Users3"."WebsiteUrl", "Users3"."Location", "Users3"."AboutMe", "Users3"."Views", "Users3"."UpVotes", "Users3"."DownVotes", "Users3"."ProfileImageUrl", "Users3"."AccountId", "t57"."POSTID", "t57"."TITLE", "t57"."SCORE", "t57"."CREATIONDATE", "t57"."OWNERUSERID", "t57"."RAN", "t57"."COMMENTCOUNT"
FROM (SELECT "t56"."Id" AS "POSTID", "t56"."Title" AS "TITLE", "t56"."Score" AS "SCORE", "t56"."CreationDate" AS "CREATIONDATE", "t56"."OwnerUserId" AS "OWNERUSERID", RANK() OVER (PARTITION BY "t56"."OwnerUserId" ORDER BY "t56"."Score" DESC NULLS FIRST) AS "RAN", CASE WHEN "t55"."COMMENTCOUNT" IS NOT NULL THEN CAST("t55"."COMMENTCOUNT" AS BIGINT) ELSE 0 END AS "COMMENTCOUNT"
FROM (SELECT "PostId", COUNT(*) AS "COMMENTCOUNT"
FROM "STACK"."Comments"
GROUP BY "PostId") AS "t55"
RIGHT JOIN (SELECT *
FROM "STACK"."Posts"
WHERE "CreationDate" >= (TIMESTAMP '2024-10-01 12:34:56' - INTERVAL '1' YEAR)) AS "t56" ON "t55"."PostId" = "t56"."Id") AS "t57"
RIGHT JOIN "STACK"."Users" AS "Users3" ON "t57"."OWNERUSERID" = "Users3"."Id") AS "t58"
LEFT JOIN "STACK"."Posts" AS "Posts8" ON "t58"."Id" = "Posts8"."OwnerUserId"
GROUP BY "t58"."Id", "t58"."DisplayName"
HAVING COUNT(DISTINCT "Posts8"."Id") > 0) AS "t62"
LEFT JOIN (SELECT "t72"."USERID" AS "UserId", CASE WHEN "t75"."EXPR$0" IS NOT NULL THEN "t75"."EXPR$0" ELSE 0 END AS "EXPR$0"
FROM (SELECT "t71"."USERID"
FROM (SELECT ANY_VALUE("t67"."Id") AS "USERID"
FROM (SELECT "Users4"."Id", "Users4"."Reputation", "Users4"."CreationDate", "Users4"."DisplayName", "Users4"."LastAccessDate", "Users4"."WebsiteUrl", "Users4"."Location", "Users4"."AboutMe", "Users4"."Views", "Users4"."UpVotes", "Users4"."DownVotes", "Users4"."ProfileImageUrl", "Users4"."AccountId", "t66"."POSTID", "t66"."TITLE", "t66"."SCORE", "t66"."CREATIONDATE", "t66"."OWNERUSERID", "t66"."RAN", "t66"."COMMENTCOUNT"
FROM (SELECT "t65"."Id" AS "POSTID", "t65"."Title" AS "TITLE", "t65"."Score" AS "SCORE", "t65"."CreationDate" AS "CREATIONDATE", "t65"."OwnerUserId" AS "OWNERUSERID", RANK() OVER (PARTITION BY "t65"."OwnerUserId" ORDER BY "t65"."Score" DESC NULLS FIRST) AS "RAN", CASE WHEN "t64"."COMMENTCOUNT" IS NOT NULL THEN CAST("t64"."COMMENTCOUNT" AS BIGINT) ELSE 0 END AS "COMMENTCOUNT"
FROM (SELECT "PostId", COUNT(*) AS "COMMENTCOUNT"
FROM "STACK"."Comments"
GROUP BY "PostId") AS "t64"
RIGHT JOIN (SELECT *
FROM "STACK"."Posts"
WHERE "CreationDate" >= (TIMESTAMP '2024-10-01 12:34:56' - INTERVAL '1' YEAR)) AS "t65" ON "t64"."PostId" = "t65"."Id") AS "t66"
RIGHT JOIN "STACK"."Users" AS "Users4" ON "t66"."OWNERUSERID" = "Users4"."Id") AS "t67"
LEFT JOIN "STACK"."Posts" AS "Posts10" ON "t67"."Id" = "Posts10"."OwnerUserId"
GROUP BY "t67"."Id", "t67"."DisplayName"
HAVING COUNT(DISTINCT "Posts10"."Id") > 0) AS "t71"
GROUP BY "t71"."USERID") AS "t72"
LEFT JOIN (SELECT "UserId", COUNT(*) AS "EXPR$0"
FROM "STACK"."Badges"
WHERE CAST("Class" AS INTEGER) = 1
GROUP BY "UserId") AS "t75" ON "t72"."USERID" IS NOT DISTINCT FROM "t75"."UserId") AS "t76" ON "t62"."USERID" = "t76"."UserId") AS "t77"
LEFT JOIN (SELECT "t102"."USERID" AS "UserId", CASE WHEN "t105"."EXPR$0" IS NOT NULL THEN "t105"."EXPR$0" ELSE 0 END AS "EXPR$0"
FROM (SELECT "t86"."USERID"
FROM (SELECT ANY_VALUE("t82"."Id") AS "USERID", "t82"."DisplayName" AS "DISPLAYNAME", COUNT(DISTINCT "Posts12"."Id") AS "TOTALPOSTS", SUM("Posts12"."Score") AS "TOTALSCORE", SUM("t82"."UpVotes") AS "UPVOTECOUNT", SUM("t82"."DownVotes") AS "DOWNVOTECOUNT", AVG(CASE WHEN "t82"."COMMENTCOUNT" IS NOT NULL THEN CAST("t82"."COMMENTCOUNT" AS BIGINT) ELSE 0 END) AS "AVGCOMMENTSPERPOST"
FROM (SELECT "Users5"."Id", "Users5"."Reputation", "Users5"."CreationDate", "Users5"."DisplayName", "Users5"."LastAccessDate", "Users5"."WebsiteUrl", "Users5"."Location", "Users5"."AboutMe", "Users5"."Views", "Users5"."UpVotes", "Users5"."DownVotes", "Users5"."ProfileImageUrl", "Users5"."AccountId", "t81"."POSTID", "t81"."TITLE", "t81"."SCORE", "t81"."CREATIONDATE", "t81"."OWNERUSERID", "t81"."RAN", "t81"."COMMENTCOUNT"
FROM (SELECT "t80"."Id" AS "POSTID", "t80"."Title" AS "TITLE", "t80"."Score" AS "SCORE", "t80"."CreationDate" AS "CREATIONDATE", "t80"."OwnerUserId" AS "OWNERUSERID", RANK() OVER (PARTITION BY "t80"."OwnerUserId" ORDER BY "t80"."Score" DESC NULLS FIRST) AS "RAN", CASE WHEN "t79"."COMMENTCOUNT" IS NOT NULL THEN CAST("t79"."COMMENTCOUNT" AS BIGINT) ELSE 0 END AS "COMMENTCOUNT"
FROM (SELECT "PostId", COUNT(*) AS "COMMENTCOUNT"
FROM "STACK"."Comments"
GROUP BY "PostId") AS "t79"
RIGHT JOIN (SELECT *
FROM "STACK"."Posts"
WHERE "CreationDate" >= (TIMESTAMP '2024-10-01 12:34:56' - INTERVAL '1' YEAR)) AS "t80" ON "t79"."PostId" = "t80"."Id") AS "t81"
RIGHT JOIN "STACK"."Users" AS "Users5" ON "t81"."OWNERUSERID" = "Users5"."Id") AS "t82"
LEFT JOIN "STACK"."Posts" AS "Posts12" ON "t82"."Id" = "Posts12"."OwnerUserId"
GROUP BY "t82"."Id", "t82"."DisplayName"
HAVING COUNT(DISTINCT "Posts12"."Id") > 0) AS "t86"
LEFT JOIN (SELECT "t96"."USERID" AS "UserId", CASE WHEN "t99"."EXPR$0" IS NOT NULL THEN "t99"."EXPR$0" ELSE 0 END AS "EXPR$0"
FROM (SELECT "t95"."USERID"
FROM (SELECT ANY_VALUE("t91"."Id") AS "USERID"
FROM (SELECT "Users6"."Id", "Users6"."Reputation", "Users6"."CreationDate", "Users6"."DisplayName", "Users6"."LastAccessDate", "Users6"."WebsiteUrl", "Users6"."Location", "Users6"."AboutMe", "Users6"."Views", "Users6"."UpVotes", "Users6"."DownVotes", "Users6"."ProfileImageUrl", "Users6"."AccountId", "t90"."POSTID", "t90"."TITLE", "t90"."SCORE", "t90"."CREATIONDATE", "t90"."OWNERUSERID", "t90"."RAN", "t90"."COMMENTCOUNT"
FROM (SELECT "t89"."Id" AS "POSTID", "t89"."Title" AS "TITLE", "t89"."Score" AS "SCORE", "t89"."CreationDate" AS "CREATIONDATE", "t89"."OwnerUserId" AS "OWNERUSERID", RANK() OVER (PARTITION BY "t89"."OwnerUserId" ORDER BY "t89"."Score" DESC NULLS FIRST) AS "RAN", CASE WHEN "t88"."COMMENTCOUNT" IS NOT NULL THEN CAST("t88"."COMMENTCOUNT" AS BIGINT) ELSE 0 END AS "COMMENTCOUNT"
FROM (SELECT "PostId", COUNT(*) AS "COMMENTCOUNT"
FROM "STACK"."Comments"
GROUP BY "PostId") AS "t88"
RIGHT JOIN (SELECT *
FROM "STACK"."Posts"
WHERE "CreationDate" >= (TIMESTAMP '2024-10-01 12:34:56' - INTERVAL '1' YEAR)) AS "t89" ON "t88"."PostId" = "t89"."Id") AS "t90"
RIGHT JOIN "STACK"."Users" AS "Users6" ON "t90"."OWNERUSERID" = "Users6"."Id") AS "t91"
LEFT JOIN "STACK"."Posts" AS "Posts14" ON "t91"."Id" = "Posts14"."OwnerUserId"
GROUP BY "t91"."Id", "t91"."DisplayName"
HAVING COUNT(DISTINCT "Posts14"."Id") > 0) AS "t95"
GROUP BY "t95"."USERID") AS "t96"
LEFT JOIN (SELECT "UserId", COUNT(*) AS "EXPR$0"
FROM "STACK"."Badges"
WHERE CAST("Class" AS INTEGER) = 1
GROUP BY "UserId") AS "t99" ON "t96"."USERID" IS NOT DISTINCT FROM "t99"."UserId") AS "t100" ON "t86"."USERID" = "t100"."UserId"
GROUP BY "t86"."USERID") AS "t102"
LEFT JOIN (SELECT "UserId", COUNT(*) AS "EXPR$0"
FROM "STACK"."Badges"
WHERE CAST("Class" AS INTEGER) = 2
GROUP BY "UserId") AS "t105" ON "t102"."USERID" IS NOT DISTINCT FROM "t105"."UserId") AS "t106" ON "t77"."USERID" = "t106"."UserId"
GROUP BY "t77"."USERID") AS "t108"
LEFT JOIN (SELECT "UserId", COUNT(*) AS "EXPR$0"
FROM "STACK"."Badges"
WHERE CAST("Class" AS INTEGER) = 3
GROUP BY "UserId") AS "t111" ON "t108"."USERID" IS NOT DISTINCT FROM "t111"."UserId") AS "t112" ON "t53"."USERID" = "t112"."UserId"
ORDER BY "t53"."TOTALSCORE" DESC NULLS FIRST, "t53"."DISPLAYNAME"
OFFSET 0 ROWS
FETCH NEXT 100 ROWS ONLY) AS "t115"