SELECT COALESCE("t8"."USERID", "t8"."USERID") AS "UserId", CASE WHEN "t11"."EXPR$0" IS NOT NULL THEN "t11"."EXPR$0" ELSE 0 END AS "FD_COL_1"
FROM (SELECT "t7"."USERID"
FROM (SELECT ANY_VALUE("t3"."Id") AS "USERID"
FROM (SELECT "Users"."Id", "Users"."Reputation", "Users"."CreationDate", "Users"."DisplayName", "Users"."LastAccessDate", "Users"."WebsiteUrl", "Users"."Location", "Users"."AboutMe", "Users"."Views", "Users"."UpVotes", "Users"."DownVotes", "Users"."ProfileImageUrl", "Users"."AccountId", "t2"."POSTID", "t2"."TITLE", "t2"."SCORE", "t2"."CREATIONDATE", "t2"."OWNERUSERID", "t2"."RAN", "t2"."COMMENTCOUNT"
FROM (SELECT "t1"."Id" AS "POSTID", "t1"."Title" AS "TITLE", "t1"."Score" AS "SCORE", "t1"."CreationDate" AS "CREATIONDATE", "t1"."OwnerUserId" AS "OWNERUSERID", RANK() OVER (PARTITION BY "t1"."OwnerUserId" ORDER BY "t1"."Score" DESC NULLS FIRST) AS "RAN", CASE WHEN "t0"."COMMENTCOUNT" IS NOT NULL THEN CAST("t0"."COMMENTCOUNT" AS BIGINT) ELSE 0 END AS "COMMENTCOUNT"
FROM (SELECT "PostId", COUNT(*) AS "COMMENTCOUNT"
FROM "STACK"."Comments"
GROUP BY "PostId") AS "t0"
RIGHT JOIN (SELECT *
FROM "STACK"."Posts"
WHERE "CreationDate" >= (TIMESTAMP '2024-10-01 12:34:56' - INTERVAL '1' YEAR)) AS "t1" ON "t0"."PostId" = "t1"."Id") AS "t2"
RIGHT JOIN "STACK"."Users" ON "t2"."OWNERUSERID" = "Users"."Id") AS "t3"
LEFT JOIN "STACK"."Posts" AS "Posts0" ON "t3"."Id" = "Posts0"."OwnerUserId"
GROUP BY "t3"."Id", "t3"."DisplayName"
HAVING COUNT(DISTINCT "Posts0"."Id") > 0) AS "t7"
GROUP BY "t7"."USERID") AS "t8"
LEFT JOIN (SELECT "UserId", COUNT(*) AS "EXPR$0"
FROM "STACK"."Badges"
WHERE CAST("Class" AS INTEGER) = 1
GROUP BY "UserId") AS "t11" ON "t8"."USERID" IS NOT DISTINCT FROM "t11"."UserId"