SELECT COALESCE("t9"."USERID", "t9"."USERID") AS "USERID", "t9"."DisplayName" AS "DISPLAYNAME", "t9"."Reputation" AS "REPUTATION", "t9"."TOTALPOSTS", "t9"."TOTALSCORE", CASE WHEN "t9"."$f9" IS NOT NULL THEN CAST("t9"."$f9" AS INTEGER) ELSE 0 END AS "TOTALCOMMENTS", CASE WHEN "t9"."$f10" IS NOT NULL THEN CAST("t9"."$f10" AS INTEGER) ELSE 0 END AS "TOTALCLOSED", CASE WHEN "t9"."$f11" IS NOT NULL THEN CAST("t9"."$f11" AS INTEGER) ELSE 0 END AS "TOTALREOPENED"
FROM (SELECT "Users"."Id", "Users"."DisplayName", "Users"."Reputation", "t3"."UPVOTES", "t3"."DOWNVOTES", "t3"."REPUTATIONCHANGE", ANY_VALUE("Users"."Id") AS "USERID", COUNT(DISTINCT "t5"."POSTID") AS "TOTALPOSTS", SUM("t5"."SCORE") AS "TOTALSCORE", SUM("t5"."COMMENTCOUNT") AS "$f9", SUM("t5"."CLOSEDCOUNT") AS "$f10", SUM("t5"."REOPENEDCOUNT") AS "$f11"
FROM "STACK"."Users"
LEFT JOIN (SELECT "UserId" AS "USERID", SUM(CASE WHEN CAST("VoteTypeId" AS INTEGER) = 2 THEN 1 ELSE 0 END) AS "UPVOTES", SUM(CASE WHEN CAST("VoteTypeId" AS INTEGER) = 3 THEN 1 ELSE 0 END) AS "DOWNVOTES", SUM(CASE WHEN CAST("VoteTypeId" AS INTEGER) = 2 THEN 1 ELSE -1 END) AS "REPUTATIONCHANGE"
FROM "STACK"."Votes"
GROUP BY "UserId") AS "t3" ON "Users"."Id" = "t3"."USERID"
LEFT JOIN (SELECT ANY_VALUE("Id") AS "POSTID", "OWNERUSERID", "TITLE", "CREATIONDATE", "SCORE", "VIEWCOUNT", SUM("FD_COL_6") AS "COMMENTCOUNT", SUM("FD_COL_7") AS "CLOSEDCOUNT", SUM("FD_COL_8") AS "REOPENEDCOUNT"
FROM "s1"
GROUP BY "Id", "OWNERUSERID", "TITLE", "CREATIONDATE", "SCORE", "VIEWCOUNT") AS "t5" ON "Users"."Id" = "t5"."OWNERUSERID"
WHERE "Users"."Reputation" > 1000
GROUP BY "Users"."Id", "Users"."Reputation", "Users"."DisplayName", "t3"."UPVOTES", "t3"."DOWNVOTES", "t3"."REPUTATIONCHANGE"
ORDER BY "Users"."Reputation" DESC NULLS FIRST, 9 DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY) AS "t9"