SELECT COALESCE("t11"."DISPLAYNAME", "t11"."DISPLAYNAME") AS "DISPLAYNAME", "t11"."TITLE", "t11"."VIEWCOUNT", "t11"."SCORE", "t11"."UPVOTECOUNT", "t11"."DOWNVOTECOUNT", "t11"."TOTALCOMMENTSCORE"
FROM (SELECT "t9"."DISPLAYNAME", "s1"."TITLE", "s1"."VIEWCOUNT", "s1"."SCORE", "s1"."UPVOTECOUNT", "s1"."DOWNVOTECOUNT", "s1"."TOTALCOMMENTSCORE"
FROM "STACK"."Posts" AS "Posts0"
INNER JOIN "s1" ON "Posts0"."Id" = "s1"."POSTID"
INNER JOIN (SELECT ANY_VALUE("t5"."Id") AS "USERID", "t5"."DisplayName" AS "DISPLAYNAME", SUM(CASE WHEN CAST("t5"."VoteTypeId" AS INTEGER) IN (2, 3) THEN 1 ELSE 0 END) AS "VOTECOUNT", COUNT(DISTINCT "Comments0"."Id") AS "COMMENTCOUNT", COUNT(DISTINCT "Posts1"."Id") AS "POSTCOUNT"
FROM (SELECT "Users"."Id", "Users"."Reputation", "Users"."CreationDate", "Users"."DisplayName", "Users"."LastAccessDate", "Users"."WebsiteUrl", "Users"."Location", "Users"."AboutMe", "Users"."Views", "Users"."UpVotes", "Users"."DownVotes", "Users"."ProfileImageUrl", "Users"."AccountId", "Votes0"."Id" AS "Id0", "Votes0"."PostId", "Votes0"."VoteTypeId", "Votes0"."UserId", "Votes0"."CreationDate" AS "CreationDate0", "Votes0"."BountyAmount"
FROM "STACK"."Votes" AS "Votes0"
RIGHT JOIN "STACK"."Users" ON "Votes0"."UserId" = "Users"."Id") AS "t5"
LEFT JOIN "STACK"."Comments" AS "Comments0" ON "t5"."Id" = "Comments0"."UserId"
LEFT JOIN "STACK"."Posts" AS "Posts1" ON "t5"."Id" = "Posts1"."OwnerUserId"
GROUP BY "t5"."Id", "t5"."DisplayName"
HAVING COUNT(DISTINCT "Posts1"."Id") >= 5) AS "t9" ON "Posts0"."OwnerUserId" = "t9"."USERID"
ORDER BY "s1"."SCORE" DESC NULLS FIRST, "s1"."VIEWCOUNT" DESC NULLS FIRST) AS "t11"