SELECT COALESCE("t2"."USERID", "t2"."USERID") AS "USERID", "t2"."DISPLAYNAME", "t2"."TOTALPOSTS", "t2"."TOTALQUESTIONS", "t2"."TOTALANSWERS", "t2"."TOTALUPVOTES", "t2"."TOTALDOWNVOTES", "t4"."USERID" AS "USERID0", "t4"."TOTALBADGES", "t4"."GOLDBADGES", "t4"."SILVERBADGES", "t4"."BRONZEBADGES", "t6"."UserId" AS "USERID1", "t6"."TOTALPOSTCLOSURES", "t6"."FIRSTCLOSEDATE", "t6"."LASTCLOSEDATE"
FROM (SELECT ANY_VALUE("t"."Id") AS "USERID", "t"."DisplayName" AS "DISPLAYNAME", COUNT("t"."Id0") AS "TOTALPOSTS", SUM(CASE WHEN CAST("t"."PostTypeId" AS INTEGER) = 1 THEN 1 ELSE 0 END) AS "TOTALQUESTIONS", SUM(CASE WHEN CAST("t"."PostTypeId" AS INTEGER) = 2 THEN 1 ELSE 0 END) AS "TOTALANSWERS", SUM(CASE WHEN CAST("Votes"."VoteTypeId" AS INTEGER) = 2 THEN 1 ELSE 0 END) AS "TOTALUPVOTES", SUM(CASE WHEN CAST("Votes"."VoteTypeId" AS INTEGER) = 3 THEN 1 ELSE 0 END) AS "TOTALDOWNVOTES"
FROM "STACK"."Votes"
RIGHT JOIN (SELECT "Users"."Id", "Users"."Reputation", "Users"."CreationDate", "Users"."DisplayName", "Users"."LastAccessDate", "Users"."WebsiteUrl", "Users"."Location", "Users"."AboutMe", "Users"."Views", "Users"."UpVotes", "Users"."DownVotes", "Users"."ProfileImageUrl", "Users"."AccountId", "Posts"."Id" AS "Id0", "Posts"."PostTypeId", "Posts"."AcceptedAnswerId", "Posts"."ParentId", "Posts"."CreationDate" AS "CreationDate0", "Posts"."Score", "Posts"."ViewCount", "Posts"."Body", "Posts"."OwnerUserId", "Posts"."OwnerDisplayName", "Posts"."LastEditorUserId", "Posts"."LastEditorDisplayName", "Posts"."LastEditDate", "Posts"."LastActivityDate", "Posts"."Title", "Posts"."Tags", "Posts"."AnswerCount", "Posts"."CommentCount", "Posts"."FavoriteCount", "Posts"."ClosedDate", "Posts"."CommunityOwnedDate", "Posts"."ContentLicense"
FROM "STACK"."Posts"
RIGHT JOIN "STACK"."Users" ON "Posts"."OwnerUserId" = "Users"."Id") AS "t" ON "Votes"."PostId" = "t"."Id0"
GROUP BY "t"."Id", "t"."DisplayName") AS "t2"
LEFT JOIN (SELECT "UserId" AS "USERID", COUNT(*) AS "TOTALBADGES", SUM(CASE WHEN CAST("Class" AS INTEGER) = 1 THEN 1 ELSE 0 END) AS "GOLDBADGES", SUM(CASE WHEN CAST("Class" AS INTEGER) = 2 THEN 1 ELSE 0 END) AS "SILVERBADGES", SUM(CASE WHEN CAST("Class" AS INTEGER) = 3 THEN 1 ELSE 0 END) AS "BRONZEBADGES"
FROM "STACK"."Badges"
GROUP BY "UserId") AS "t4" ON "t2"."USERID" = "t4"."USERID"
LEFT JOIN (SELECT "UserId", COUNT(*) AS "TOTALPOSTCLOSURES", MIN("CreationDate") AS "FIRSTCLOSEDATE", MAX("CreationDate") AS "LASTCLOSEDATE"
FROM "STACK"."PostHistory"
WHERE CAST("PostHistoryTypeId" AS INTEGER) = 10
GROUP BY "UserId") AS "t6" ON "t2"."USERID" = "t6"."UserId"