SELECT COALESCE("t13"."USERID", "t13"."USERID") AS "USERID", "t13"."DISPLAYNAME", "t13"."POSTCOUNT", "t13"."QUESTIONCOUNT", "t13"."ANSWERCOUNT", "t13"."UPVOTECOUNT", "t13"."DOWNVOTECOUNT", "t13"."BADGECOUNT", "t13"."GOLDBADGES", "t13"."SILVERBADGES", "t13"."BRONZEBADGES", "t13"."TOTALPOSTS", "t13"."AVGCOMMENTSPERPOST", "t13"."MAXVIEWS", "t13"."FIRSTPOSTDATE", "t13"."LASTPOSTDATE"
FROM (SELECT "t5"."USERID", "t5"."DISPLAYNAME", "t5"."POSTCOUNT", "t5"."QUESTIONCOUNT", "t5"."ANSWERCOUNT", "t5"."UPVOTECOUNT", "t5"."DOWNVOTECOUNT", "s1"."BADGECOUNT", "s1"."GOLDBADGES", "s1"."SILVERBADGES", "s1"."BRONZEBADGES", "t11"."TOTALPOSTS", "t11"."AVGCOMMENTSPERPOST", "t11"."MAXVIEWS", "t11"."FIRSTPOSTDATE", "t11"."LASTPOSTDATE"
FROM (SELECT ANY_VALUE("t2"."Id") AS "USERID", "t2"."DisplayName" AS "DISPLAYNAME", COUNT(DISTINCT "t2"."Id0") AS "POSTCOUNT", SUM(CASE WHEN CAST("t2"."PostTypeId" AS INTEGER) = 1 THEN 1 ELSE 0 END) AS "QUESTIONCOUNT", SUM(CASE WHEN CAST("t2"."PostTypeId" AS INTEGER) = 2 THEN 1 ELSE 0 END) AS "ANSWERCOUNT", SUM(CASE WHEN CAST("Votes"."VoteTypeId" AS INTEGER) = 2 THEN 1 ELSE 0 END) AS "UPVOTECOUNT", SUM(CASE WHEN CAST("Votes"."VoteTypeId" AS INTEGER) = 3 THEN 1 ELSE 0 END) AS "DOWNVOTECOUNT"
FROM "STACK"."Votes"
RIGHT JOIN (SELECT "Users"."Id", "Users"."Reputation", "Users"."CreationDate", "Users"."DisplayName", "Users"."LastAccessDate", "Users"."WebsiteUrl", "Users"."Location", "Users"."AboutMe", "Users"."Views", "Users"."UpVotes", "Users"."DownVotes", "Users"."ProfileImageUrl", "Users"."AccountId", "Posts"."Id" AS "Id0", "Posts"."PostTypeId", "Posts"."AcceptedAnswerId", "Posts"."ParentId", "Posts"."CreationDate" AS "CreationDate0", "Posts"."Score", "Posts"."ViewCount", "Posts"."Body", "Posts"."OwnerUserId", "Posts"."OwnerDisplayName", "Posts"."LastEditorUserId", "Posts"."LastEditorDisplayName", "Posts"."LastEditDate", "Posts"."LastActivityDate", "Posts"."Title", "Posts"."Tags", "Posts"."AnswerCount", "Posts"."CommentCount", "Posts"."FavoriteCount", "Posts"."ClosedDate", "Posts"."CommunityOwnedDate", "Posts"."ContentLicense"
FROM "STACK"."Posts"
RIGHT JOIN "STACK"."Users" ON "Posts"."OwnerUserId" = "Users"."Id") AS "t2" ON "Votes"."PostId" = "t2"."Id0"
GROUP BY "t2"."Id", "t2"."DisplayName") AS "t5"
LEFT JOIN "s1" ON "t5"."USERID" = "s1"."USERID"
LEFT JOIN (SELECT "Posts0"."OwnerUserId" AS "OWNERUSERID", COUNT(DISTINCT "Posts0"."Id") AS "TOTALPOSTS", AVG(CASE WHEN CASE WHEN "t9"."EXPR$0" IS NULL THEN 0 ELSE "t9"."EXPR$0" END IS NOT NULL THEN CAST(CASE WHEN "t9"."EXPR$0" IS NULL THEN 0 ELSE "t9"."EXPR$0" END AS BIGINT) ELSE 0 END) AS "AVGCOMMENTSPERPOST", MAX("Posts0"."ViewCount") AS "MAXVIEWS", MIN("Posts0"."CreationDate") AS "FIRSTPOSTDATE", MAX("Posts0"."CreationDate") AS "LASTPOSTDATE"
FROM "STACK"."Posts" AS "Posts0"
LEFT JOIN (SELECT "t6"."Id" AS "PostId", CASE WHEN "t8"."EXPR$0" IS NOT NULL THEN "t8"."EXPR$0" ELSE 0 END AS "EXPR$0"
FROM (SELECT "Id"
FROM "STACK"."Posts") AS "t6"
LEFT JOIN (SELECT "PostId", COUNT(*) AS "EXPR$0"
FROM "STACK"."Comments"
GROUP BY "PostId") AS "t8" ON "t6"."Id" IS NOT DISTINCT FROM "t8"."PostId") AS "t9" ON "Posts0"."Id" = "t9"."PostId"
GROUP BY "Posts0"."OwnerUserId") AS "t11" ON "t5"."USERID" = "t11"."OWNERUSERID"
ORDER BY "t5"."POSTCOUNT" DESC NULLS FIRST, "t5"."UPVOTECOUNT" DESC NULLS FIRST
FETCH NEXT 100 ROWS ONLY) AS "t13"