SELECT COALESCE("OwnerUserId", "OwnerUserId") AS "OWNERUSERID", COUNT(*) AS "POSTCOUNT", SUM(CASE WHEN CAST("PostTypeId" AS INTEGER) = 1 THEN 1 ELSE 0 END) AS "QUESTIONCOUNT", SUM(CASE WHEN CAST("PostTypeId" AS INTEGER) = 2 THEN 1 ELSE 0 END) AS "ANSWERCOUNT", SUM("Score") AS "TOTALSCORE"
FROM "STACK"."Posts"
GROUP BY "OwnerUserId"