SELECT COALESCE("t8"."POSTID", "t8"."POSTID") AS "POSTID", "t8"."TITLE", "t8"."SCORE", "t8"."OWNERDISPLAYNAME", "t8"."CREATIONDATE", "t8"."COMMENTCOUNT", "t8"."ENGAGEMENTLEVEL", "t8"."UPVOTES", "t8"."DOWNVOTES"
FROM (SELECT "s1"."POSTID", "s1"."TITLE", "s1"."SCORE", "s1"."OWNERDISPLAYNAME", "s1"."CREATIONDATE", "s1"."COMMENTCOUNT", "s1"."ENGAGEMENTLEVEL", CASE WHEN "t6"."UPVOTES" IS NOT NULL THEN CAST("t6"."UPVOTES" AS INTEGER) ELSE 0 END AS "UPVOTES", CASE WHEN "t6"."DOWNVOTES" IS NOT NULL THEN CAST("t6"."DOWNVOTES" AS INTEGER) ELSE 0 END AS "DOWNVOTES"
FROM (SELECT "PostId" AS "POSTID", SUM(CASE WHEN CAST("VoteTypeId" AS INTEGER) = 2 THEN 1 ELSE 0 END) AS "UPVOTES", SUM(CASE WHEN CAST("VoteTypeId" AS INTEGER) = 3 THEN 1 ELSE 0 END) AS "DOWNVOTES"
FROM "STACK"."Votes"
GROUP BY "PostId") AS "t6"
RIGHT JOIN "s1" ON "t6"."POSTID" = "s1"."POSTID"
ORDER BY "s1"."SCORE" DESC NULLS FIRST, "s1"."COMMENTCOUNT" DESC NULLS FIRST
FETCH NEXT 50 ROWS ONLY) AS "t8"