SELECT COALESCE("t7"."USERID", "t7"."USERID") AS "USERID", "t7"."DISPLAYNAME", "t7"."POSTCOUNT", "t7"."QUESTIONCOUNT", "t7"."ANSWERCOUNT", "t7"."TOTALBOUNTY", "t7"."TOTALUPVOTES", "t7"."TOTALDOWNVOTES", "t7"."BADGECOUNT", "t7"."HIGHESTBADGECLASS"
FROM (SELECT "s1"."USERID", "s1"."DISPLAYNAME", "s1"."POSTCOUNT", "s1"."QUESTIONCOUNT", "s1"."ANSWERCOUNT", "s1"."TOTALBOUNTY", "s1"."TOTALUPVOTES", "s1"."TOTALDOWNVOTES", CASE WHEN "t5"."BADGECOUNT" IS NOT NULL THEN CAST("t5"."BADGECOUNT" AS BIGINT) ELSE 0 END AS "BADGECOUNT", CASE WHEN "t5"."HIGHESTBADGECLASS" IS NOT NULL THEN CAST("t5"."HIGHESTBADGECLASS" AS INTEGER) ELSE 0 END AS "HIGHESTBADGECLASS"
FROM "s1"
LEFT JOIN (SELECT "UserId", COUNT(*) AS "BADGECOUNT", MAX("Class") AS "HIGHESTBADGECLASS"
FROM "STACK"."Badges"
GROUP BY "UserId") AS "t5" ON "s1"."USERID" = "t5"."UserId"
ORDER BY "s1"."TOTALUPVOTES" DESC NULLS FIRST, "s1"."POSTCOUNT" DESC NULLS FIRST
FETCH NEXT 50 ROWS ONLY) AS "t7"