SELECT COALESCE("t5"."DISPLAYNAME", "t5"."DISPLAYNAME") AS "DISPLAYNAME", "t5"."UPVOTES", "t5"."DOWNVOTES", "t5"."TOTALPOSTS", "t5"."TOTALSCORE", "t5"."TOTALVIEWS"
FROM (SELECT "Users"."DisplayName" AS "DISPLAYNAME", CASE WHEN "s1"."UPVOTES" IS NOT NULL THEN CAST("s1"."UPVOTES" AS BIGINT) ELSE 0 END AS "UPVOTES", CASE WHEN "s1"."DOWNVOTES" IS NOT NULL THEN CAST("s1"."DOWNVOTES" AS BIGINT) ELSE 0 END AS "DOWNVOTES", CASE WHEN "t2"."TOTALPOSTS" IS NOT NULL THEN CAST("t2"."TOTALPOSTS" AS BIGINT) ELSE 0 END AS "TOTALPOSTS", CASE WHEN "t2"."TOTALSCORE" IS NOT NULL THEN CAST("t2"."TOTALSCORE" AS INTEGER) ELSE 0 END AS "TOTALSCORE", CASE WHEN "t2"."TOTALVIEWS" IS NOT NULL THEN CAST("t2"."TOTALVIEWS" AS INTEGER) ELSE 0 END AS "TOTALVIEWS"
FROM "STACK"."Users"
LEFT JOIN "s1" ON "Users"."Id" = "s1"."USERID"
LEFT JOIN (SELECT "OwnerUserId", COUNT(*) AS "TOTALPOSTS", SUM("Score") AS "TOTALSCORE", SUM("ViewCount") AS "TOTALVIEWS"
FROM "STACK"."Posts"
GROUP BY "OwnerUserId") AS "t2" ON "Users"."Id" = "t2"."OwnerUserId"
WHERE CASE WHEN "t2"."TOTALPOSTS" IS NOT NULL THEN CAST("t2"."TOTALPOSTS" AS BIGINT) ELSE 0 END > 0
ORDER BY 5 DESC NULLS FIRST, 6 DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY) AS "t5"