SELECT COALESCE("UserId", "UserId") AS "USERID", COUNT(CASE WHEN CAST("VoteTypeId" AS INTEGER) = 2 THEN 1 ELSE NULL END) AS "UPVOTES", COUNT(CASE WHEN CAST("VoteTypeId" AS INTEGER) = 3 THEN 1 ELSE NULL END) AS "DOWNVOTES"
FROM "STACK"."Votes"
GROUP BY "UserId"