SELECT COALESCE("OwnerUserId", "OwnerUserId") AS "OWNERUSERID", COUNT(CASE WHEN CAST("PostTypeId" AS INTEGER) = 1 THEN 1 ELSE NULL END) AS "QUESTIONS", COUNT(CASE WHEN CAST("PostTypeId" AS INTEGER) = 2 THEN 1 ELSE NULL END) AS "ANSWERS", AVG("Score") AS "AVERAGESCORE", SUM("ViewCount") AS "TOTALVIEWS", COUNT(DISTINCT "Tags") AS "UNIQUETAGS"
FROM "STACK"."Posts"
GROUP BY "OwnerUserId"