SELECT COALESCE("t7"."DISPLAYNAME", "t7"."DISPLAYNAME") AS "DISPLAYNAME", "t7"."REPUTATION", "t7"."LASTACCESSDATE", "t7"."ENGAGEMENTSCORE", "t7"."BADGECOUNT", "t7"."GOLDBADGES", "t7"."SILVERBADGES", "t7"."BRONZEBADGES", "t7"."POSTCOUNT", "t7"."QUESTIONCOUNT", "t7"."ANSWERCOUNT", "t7"."WIKICOUNT", "t7"."TOTALSCORE", "t7"."AVGVIEWCOUNT"
FROM (SELECT "s1"."DisplayName_" AS "DISPLAYNAME", "s1"."Reputation" AS "REPUTATION", "s1"."LastAccessDate" AS "LASTACCESSDATE", "s1"."Views" + "s1"."UpVotes" - "s1"."DownVotes" AS "ENGAGEMENTSCORE", "s1"."BADGECOUNT", "s1"."GOLDBADGES", "s1"."SILVERBADGES", "s1"."BRONZEBADGES", "t5"."POSTCOUNT", "t5"."QUESTIONCOUNT", "t5"."ANSWERCOUNT", "t5"."WIKICOUNT", "t5"."TOTALSCORE", "t5"."AVGVIEWCOUNT"
FROM "s1"
LEFT JOIN (SELECT "OwnerUserId" AS "OWNERUSERID", COUNT(*) AS "POSTCOUNT", SUM(CASE WHEN CAST("PostTypeId" AS INTEGER) = 1 THEN 1 ELSE 0 END) AS "QUESTIONCOUNT", SUM(CASE WHEN CAST("PostTypeId" AS INTEGER) = 2 THEN 1 ELSE 0 END) AS "ANSWERCOUNT", SUM(CASE WHEN CAST("PostTypeId" AS INTEGER) = 3 THEN 1 ELSE 0 END) AS "WIKICOUNT", SUM("Score") AS "TOTALSCORE", AVG("ViewCount") AS "AVGVIEWCOUNT"
FROM "STACK"."Posts"
GROUP BY "OwnerUserId") AS "t5" ON "s1"."Id" = "t5"."OWNERUSERID"
ORDER BY 4 DESC NULLS FIRST, "s1"."Reputation" DESC NULLS FIRST
FETCH NEXT 100 ROWS ONLY) AS "t7"