SELECT COALESCE("OwnerUserId", "OwnerUserId") AS "OWNERUSERID", COUNT(CASE WHEN CAST("PostTypeId" AS INTEGER) = 1 THEN 1 ELSE NULL END) AS "QUESTIONCOUNT", COUNT(CASE WHEN CAST("PostTypeId" AS INTEGER) = 2 THEN 1 ELSE NULL END) AS "ANSWERCOUNT", SUM("Score") AS "TOTALSCORE", SUM("ViewCount") AS "TOTALVIEWS"
FROM "STACK"."Posts"
GROUP BY "OwnerUserId"