SELECT COALESCE(SUPPLIER_NAME, SUPPLIER_NAME) AS SUPPLIER_NAME, PART_NAME, DESCRIPTION, REGION_NAME, TOTAL_ORDERS, TOTAL_QUANTITY, TOTAL_REVENUE, AVG_PRICE_AFTER_DISCOUNT
FROM s1
ORDER BY TOTAL_REVENUE DESC NULLS FIRST
LIMIT 10