SELECT COALESCE(t6.POSTTYPE, t6.POSTTYPE) AS POSTTYPE, t6.POSTCOUNT, t6.AVGVIEWCOUNT, t6.AVGSCORE, t6.USERID, t6.REPUTATION, t6.CREATIONDATE, t6.POSTSCOUNT
FROM (SELECT t1.POSTTYPE, t1.POSTCOUNT, t1.AVGVIEWCOUNT, t1.AVGSCORE, t4.USERID, t4.REPUTATION, t4.CREATIONDATE, t4.POSTSCOUNT
FROM (SELECT MIN(PostTypes.Name) AS POSTTYPE, COUNT(*) AS POSTCOUNT, AVG(Posts0.ViewCount) AS AVGVIEWCOUNT, AVG(Posts0.Score) AS AVGSCORE
FROM PostTypes
INNER JOIN Posts AS Posts0 ON PostTypes.Id = Posts0.PostTypeId
GROUP BY PostTypes.Name) AS t1,
(SELECT MIN(Id0) AS USERID, Reputation AS REPUTATION, CreationDate0 AS CREATIONDATE, COUNT(Id) AS POSTSCOUNT, COUNT(Id) > 0 AS FD_D_f4
FROM s1
GROUP BY Id0, Reputation, CreationDate0
HAVING COUNT(Id) > 0) AS t4
ORDER BY t1.POSTTYPE) AS t6