SELECT COALESCE(ANY_VALUE("name"), ANY_VALUE("name")) AS "ACTOR_NAME", ANY_VALUE("title") AS "MOVIE_TITLE", "PRODUCTION_YEAR", ANY_VALUE("kind") AS "CAST_TYPE", LISTAGG(DISTINCT "keyword", "FD_COL_5") AS "MOVIE_KEYWORDS", "name"
FROM "s1"
GROUP BY "name", "title", "PRODUCTION_YEAR", "kind"
ORDER BY "PRODUCTION_YEAR" DESC NULLS FIRST, "name"