SELECT COALESCE("TITLE", "TITLE") AS "TITLE", "ACTOR_NAME", "MOVIE_KEYWORD", "COMPANY_NAME", "COMPANY_TYPE", "PERSON_INFO", "production_year"
FROM "s1"
ORDER BY "production_year" DESC NULLS FIRST, "TITLE"
FETCH NEXT 100 ROWS ONLY