SELECT COALESCE("MOVIE_ID", "MOVIE_ID") AS "MOVIE_ID", "TITLE", "PRODUCTION_YEAR", "TOTAL_COMPANIES", "TOTAL_KEYWORDS", "TOTAL_ACTORS", "MOVIE_ERA"
FROM "s1"
ORDER BY "PRODUCTION_YEAR" DESC NULLS FIRST, "TITLE"