SELECT COALESCE("TITLE", "TITLE") AS "TITLE", "CAST_COUNT", "AVG_ORDER", "KEYWORD", "MOVIE_COUNT", "COMPANY_NAME", "MOVIES_PRODUCED"
FROM "s1"
ORDER BY "CAST_COUNT" DESC NULLS FIRST, "MOVIES_PRODUCED"
FETCH NEXT 50 ROWS ONLY