SELECT COALESCE("MOVIE_ID", "MOVIE_ID") AS "MOVIE_ID", "TITLE", "PRODUCTION_YEAR", "GENRES", "TOTAL_CAST", "DIRECTOR_COUNT", "MOVIE_STATUS"
FROM "s1"
ORDER BY "PRODUCTION_YEAR" DESC NULLS FIRST, "TITLE"