SELECT COALESCE("MOVIE_ID", "MOVIE_ID") AS "MOVIE_ID", "TITLE", "PRODUCTION_YEAR", "AVG_STARRING_ROLES", "FULL_CAST_COUNT", "ACTORS_LIST", "KEYWORDS", "EXPR$7" AS "FD_COL_7"
FROM (SELECT "MOVIE_ID", "TITLE", "PRODUCTION_YEAR", "AVG_STARRING_ROLES", "FULL_CAST_COUNT", "ACTORS_LIST", "KEYWORDS", CASE WHEN "AVG_STARRING_ROLES" > 3 THEN 1 ELSE 2 END AS "EXPR$7"
FROM "s1"
WHERE "KEYWORDS" LIKE '%action%' OR "TITLE" LIKE '% thriller%'
ORDER BY 8, "PRODUCTION_YEAR" DESC NULLS FIRST) AS "t11"