SELECT COALESCE("MOVIE_TITLE", "MOVIE_TITLE") AS "MOVIE_TITLE", "PRODUCTION_YEAR", LISTAGG(DISTINCT "COMPANY_NAME", "FD_COL_3") AS "COMPANIES", LISTAGG(DISTINCT "MOVIE_KEYWORD", "FD_COL_3") AS "KEYWORDS", LISTAGG(DISTINCT "FD_COL_5", "FD_COL_3") AS "CAST"
FROM "s1"
GROUP BY "MOVIE_TITLE", "PRODUCTION_YEAR"
ORDER BY "PRODUCTION_YEAR" DESC NULLS FIRST, "MOVIE_TITLE"
FETCH NEXT 100 ROWS ONLY