SELECT COALESCE("MOVIE_ID", "MOVIE_ID") AS "MOVIE_ID", "MOVIE_TITLE", "PRODUCTION_YEAR", "KEYWORD", "CAST_NAMES", "COMPANY_NAME", "COMPANY_TYPE", "TOTAL_COMPANIES"
FROM (SELECT "t1"."MOVIE_ID", "t1"."MOVIE_TITLE", "t1"."PRODUCTION_YEAR", "t1"."KEYWORD", "t1"."CAST_NAMES", CASE WHEN "t4"."COMPANY_NAME" IS NOT NULL THEN CAST("t4"."COMPANY_NAME" AS VARCHAR CHARACTER SET "ISO-8859-1") ELSE 'Unknown' END AS "COMPANY_NAME", CASE WHEN "t4"."COMPANY_TYPE" IS NOT NULL THEN CAST("t4"."COMPANY_TYPE" AS VARCHAR CHARACTER SET "ISO-8859-1") ELSE 'Unknown' END AS "COMPANY_TYPE", CASE WHEN "t4"."TOTAL_COMPANIES" IS NOT NULL THEN CAST("t4"."TOTAL_COMPANIES" AS BIGINT) ELSE 0 END AS "TOTAL_COMPANIES"
FROM (SELECT ANY_VALUE("aka_title"."id") AS "MOVIE_ID", ANY_VALUE("aka_title"."title") AS "MOVIE_TITLE", "aka_title"."production_year" AS "PRODUCTION_YEAR", ANY_VALUE("keyword"."keyword") AS "KEYWORD", ARRAY_AGG(DISTINCT "aka_name"."name") AS "CAST_NAMES"
FROM "IMDB"."aka_title"
INNER JOIN "IMDB"."movie_keyword" ON "aka_title"."id" = "movie_keyword"."movie_id"
INNER JOIN "IMDB"."keyword" ON "movie_keyword"."keyword_id" = "keyword"."id"
INNER JOIN "IMDB"."complete_cast" ON "aka_title"."id" = "complete_cast"."movie_id"
INNER JOIN "IMDB"."aka_name" ON "complete_cast"."subject_id" = "aka_name"."person_id"
GROUP BY "aka_title"."id", "keyword"."keyword", "aka_title"."title", "aka_title"."production_year") AS "t1"
LEFT JOIN (SELECT "movie_companies"."movie_id" AS "MOVIE_ID", ANY_VALUE("company_name"."name") AS "COMPANY_NAME", ANY_VALUE("company_type"."kind") AS "COMPANY_TYPE", COUNT(*) AS "TOTAL_COMPANIES"
FROM "IMDB"."movie_companies"
INNER JOIN "IMDB"."company_name" ON "movie_companies"."company_id" = "company_name"."id"
INNER JOIN "IMDB"."company_type" ON "movie_companies"."company_type_id" = "company_type"."id"
GROUP BY "movie_companies"."movie_id", "company_name"."name", "company_type"."kind") AS "t4" ON "t1"."MOVIE_ID" = "t4"."MOVIE_ID") AS "t5"
WHERE "t5"."PRODUCTION_YEAR" >= 2000 AND "t5"."PRODUCTION_YEAR" <= 2023