SELECT COALESCE("MOVIE_ID", "MOVIE_ID") AS "MOVIE_ID", "MOVIE_TITLE", "PRODUCTION_YEAR", "KEYWORD", "CAST_NAMES", "COMPANY_NAME", "COMPANY_TYPE", "TOTAL_COMPANIES"
FROM "s1"
ORDER BY "PRODUCTION_YEAR" DESC NULLS FIRST, "MOVIE_TITLE"
FETCH NEXT 100 ROWS ONLY