SELECT COALESCE("t0"."MOVIE_ID", "t0"."MOVIE_ID") AS "MOVIE_ID", "t0"."TITLE", "t0"."PRODUCTION_YEAR", ARRAY_AGG(DISTINCT "t0"."KEYWORD") AS "KEYWORDS", ARRAY_AGG(DISTINCT "t1"."ACTOR_NAME") AS "ACTORS", ARRAY_AGG(DISTINCT "t1"."ACTOR_ROLE") AS "ROLES", COUNT(DISTINCT "t0"."COMPANY_NAME") AS "COMPANY_COUNT"
FROM (SELECT "aka_title"."id" AS "MOVIE_ID", "aka_title"."title" AS "TITLE", "aka_title"."production_year" AS "PRODUCTION_YEAR", "keyword"."keyword" AS "KEYWORD", "company_name"."name" AS "COMPANY_NAME", "company_type"."kind" AS "COMPANY_TYPE"
FROM "IMDB"."aka_title"
LEFT JOIN "IMDB"."movie_keyword" ON "aka_title"."id" = "movie_keyword"."movie_id"
LEFT JOIN "IMDB"."keyword" ON "movie_keyword"."keyword_id" = "keyword"."id"
LEFT JOIN "IMDB"."movie_companies" ON "aka_title"."id" = "movie_companies"."movie_id"
LEFT JOIN "IMDB"."company_name" ON "movie_companies"."company_id" = "company_name"."id"
LEFT JOIN "IMDB"."company_type" ON "movie_companies"."company_type_id" = "company_type"."id"
WHERE "aka_title"."production_year" >= 2000 AND "keyword"."keyword" IS NOT NULL) AS "t0"
LEFT JOIN (SELECT "cast_info"."movie_id" AS "MOVIE_ID", "aka_name"."name" AS "ACTOR_NAME", "role_type"."role" AS "ACTOR_ROLE"
FROM "IMDB"."cast_info"
INNER JOIN "IMDB"."aka_name" ON "cast_info"."person_id" = "aka_name"."person_id"
INNER JOIN "IMDB"."role_type" ON "cast_info"."role_id" = "role_type"."id") AS "t1" ON "t0"."MOVIE_ID" = "t1"."MOVIE_ID"
GROUP BY "t0"."MOVIE_ID", "t0"."TITLE", "t0"."PRODUCTION_YEAR"