SELECT COALESCE("t5"."TITLE", "t5"."TITLE") AS "TITLE", "t5"."PRODUCTION_YEAR", "t7"."NAME", "movie_info0"."info_type_id"
FROM (SELECT "t3"."TITLE_ID", "t3"."TITLE", "t3"."PRODUCTION_YEAR"
FROM (SELECT "TITLE_ID", "TITLE", "PRODUCTION_YEAR"
FROM (SELECT ANY_VALUE("title"."id") AS "TITLE_ID", "title"."title" AS "TITLE", "title"."production_year" AS "PRODUCTION_YEAR", COUNT(*) AS "ACTOR_COUNT"
FROM "IMDB"."title"
INNER JOIN "IMDB"."movie_companies" ON "title"."id" = "movie_companies"."movie_id"
INNER JOIN "IMDB"."cast_info" ON "title"."id" = "cast_info"."movie_id"
GROUP BY "title"."id", "title"."title", "title"."production_year") AS "t1"
WHERE "t1"."ACTOR_COUNT" > 5) AS "t3"
INNER JOIN "IMDB"."movie_info" ON "t3"."TITLE_ID" = "movie_info"."movie_id"
WHERE "movie_info"."info" ILIKE '%award%') AS "t5"
INNER JOIN "IMDB"."cast_info" AS "cast_info0" ON "t5"."TITLE_ID" = "cast_info0"."movie_id"
INNER JOIN (SELECT "person_id" AS "PERSON_ID", "name" AS "NAME", "id" AS "ID"
FROM "IMDB"."aka_name"
WHERE "name" ILIKE '%Smith%') AS "t7" ON "cast_info0"."person_id" = "t7"."PERSON_ID"
INNER JOIN "IMDB"."movie_info" AS "movie_info0" ON "t5"."TITLE_ID" = "movie_info0"."movie_id"