SELECT COALESCE("MOVIE_ID", "MOVIE_ID") AS "MOVIE_ID", "TITLE", "PRODUCTION_YEAR", "CAST_COUNT", "KEYWORD_COUNT", "KEYWORDS", "ACTOR_NAMES", "CAST_SIZE_CATEGORY"
FROM "s1"
ORDER BY "PRODUCTION_YEAR" DESC NULLS FIRST, "CAST_COUNT" DESC NULLS FIRST