SELECT COALESCE("t0"."MOVIE_ID", "t0"."MOVIE_ID") AS "MOVIE_ID", "t0"."TITLE", "t0"."PRODUCTION_YEAR", "t1"."ACTOR_NAME" || ' (' || "t1"."ROLE_NAME" || ')' AS "FD_COL_3", ', ' AS "FD_COL_4", "t2"."COMPANY_NAME" || ' (' || "t2"."COMPANY_TYPE" || ')' AS "FD_COL_5", "t0"."KEYWORD"
FROM (SELECT "aka_title"."id" AS "MOVIE_ID", "aka_title"."title" AS "TITLE", "aka_title"."production_year" AS "PRODUCTION_YEAR", "keyword"."keyword" AS "KEYWORD", ROW_NUMBER() OVER (PARTITION BY "aka_title"."id" ORDER BY "keyword"."keyword") AS "KEYWORD_RANK"
FROM "IMDB"."aka_title"
INNER JOIN "IMDB"."movie_keyword" ON "aka_title"."id" = "movie_keyword"."movie_id"
INNER JOIN "IMDB"."keyword" ON "movie_keyword"."keyword_id" = "keyword"."id"
WHERE "aka_title"."production_year" >= 2000 AND "aka_title"."production_year" <= 2023) AS "t0"
LEFT JOIN (SELECT "cast_info"."movie_id" AS "MOVIE_ID", "aka_name"."name" AS "ACTOR_NAME", "role_type"."role" AS "ROLE_NAME"
FROM "IMDB"."cast_info"
INNER JOIN "IMDB"."aka_name" ON "cast_info"."person_id" = "aka_name"."person_id"
INNER JOIN "IMDB"."role_type" ON "cast_info"."role_id" = "role_type"."id") AS "t1" ON "t0"."MOVIE_ID" = "t1"."MOVIE_ID"
LEFT JOIN (SELECT "movie_companies"."movie_id" AS "MOVIE_ID", "company_name"."name" AS "COMPANY_NAME", "company_type"."kind" AS "COMPANY_TYPE"
FROM "IMDB"."movie_companies"
INNER JOIN "IMDB"."company_name" ON "movie_companies"."company_id" = "company_name"."id"
INNER JOIN "IMDB"."company_type" ON "movie_companies"."company_type_id" = "company_type"."id") AS "t2" ON "t0"."MOVIE_ID" = "t2"."MOVIE_ID"