SELECT COALESCE("t1"."MOVIE_ID", "t1"."MOVIE_ID") AS "MOVIE_ID", "t1"."TITLE", "t1"."PRODUCTION_YEAR", "t1"."KEYWORD", "t1"."NUM_CAST_MEMBERS", "t1"."CAST_NAMES"
FROM (SELECT ANY_VALUE("aka_title"."id") AS "MOVIE_ID", "aka_title"."title" AS "TITLE", "aka_title"."production_year" AS "PRODUCTION_YEAR", ANY_VALUE("keyword"."keyword") AS "KEYWORD", COUNT(DISTINCT "cast_info"."person_id") AS "NUM_CAST_MEMBERS", CASE WHEN LISTAGG(DISTINCT "aka_name"."name", ', ') IS NOT NULL THEN CAST(LISTAGG(DISTINCT "aka_name"."name", ', ') AS VARCHAR CHARACTER SET "ISO-8859-1") ELSE 'No Cast' END AS "CAST_NAMES"
FROM "IMDB"."aka_title"
LEFT JOIN "IMDB"."movie_keyword" ON "aka_title"."id" = "movie_keyword"."movie_id"
LEFT JOIN "IMDB"."keyword" ON "movie_keyword"."keyword_id" = "keyword"."id"
LEFT JOIN "IMDB"."cast_info" ON "aka_title"."id" = "cast_info"."movie_id"
LEFT JOIN "IMDB"."aka_name" ON "cast_info"."person_id" = "aka_name"."person_id"
GROUP BY "aka_title"."id", "aka_title"."title", "aka_title"."production_year", "keyword"."keyword") AS "t1"
INNER JOIN (SELECT "KEYWORD"
FROM (SELECT "t4"."KEYWORD", COUNT(*) AS "MOVIE_COUNT"
FROM (SELECT ANY_VALUE("keyword0"."keyword") AS "KEYWORD"
FROM "IMDB"."aka_title" AS "aka_title0"
LEFT JOIN "IMDB"."movie_keyword" AS "movie_keyword0" ON "aka_title0"."id" = "movie_keyword0"."movie_id"
LEFT JOIN "IMDB"."keyword" AS "keyword0" ON "movie_keyword0"."keyword_id" = "keyword0"."id"
LEFT JOIN "IMDB"."cast_info" AS "cast_info0" ON "aka_title0"."id" = "cast_info0"."movie_id"
LEFT JOIN "IMDB"."aka_name" AS "aka_name0" ON "cast_info0"."person_id" = "aka_name0"."person_id"
GROUP BY "aka_title0"."id", "aka_title0"."title", "aka_title0"."production_year", "keyword0"."keyword") AS "t4"
GROUP BY "t4"."KEYWORD"
HAVING COUNT(*) > 1
ORDER BY 2 DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY) AS "t8") AS "t9" ON "t1"."KEYWORD" = "t9"."KEYWORD"