SELECT COALESCE("MOVIE_ID", "MOVIE_ID") AS "MOVIE_ID", "TITLE", "PRODUCTION_YEAR", "KEYWORD", "NUM_CAST_MEMBERS", "CAST_NAMES"
FROM "s1"
ORDER BY "PRODUCTION_YEAR" DESC NULLS FIRST, "NUM_CAST_MEMBERS" DESC NULLS FIRST