SELECT COALESCE("t1"."MOVIE_ID", "t1"."MOVIE_ID") AS "MOVIE_ID", "t1"."TITLE", "t1"."PRODUCTION_YEAR", "t1"."AKA_NAMES", "t1"."KEYWORDS", "t1"."CAST_COUNT", "t3"."COMPANY_NAMES", "t3"."COMPANY_TYPES"
FROM (SELECT ANY_VALUE("aka_title"."id") AS "MOVIE_ID", "aka_title"."title" AS "TITLE", "aka_title"."production_year" AS "PRODUCTION_YEAR", LISTAGG(DISTINCT "aka_name"."name", ', ') AS "AKA_NAMES", LISTAGG(DISTINCT "keyword"."keyword", ', ') AS "KEYWORDS", COUNT("complete_cast"."id") AS "CAST_COUNT"
FROM "IMDB"."aka_title"
LEFT JOIN "IMDB"."aka_name" ON "aka_title"."id" = "aka_name"."id"
LEFT JOIN "IMDB"."movie_keyword" ON "aka_title"."id" = "movie_keyword"."movie_id"
LEFT JOIN "IMDB"."keyword" ON "movie_keyword"."keyword_id" = "keyword"."id"
LEFT JOIN "IMDB"."complete_cast" ON "aka_title"."id" = "complete_cast"."movie_id"
GROUP BY "aka_title"."id", "aka_title"."title", "aka_title"."production_year") AS "t1"
LEFT JOIN (SELECT "movie_companies"."movie_id" AS "MOVIE_ID", LISTAGG(DISTINCT "company_name"."name", ', ') AS "COMPANY_NAMES", LISTAGG(DISTINCT "company_type"."kind", ', ') AS "COMPANY_TYPES"
FROM "IMDB"."movie_companies"
INNER JOIN "IMDB"."company_name" ON "movie_companies"."company_id" = "company_name"."id"
INNER JOIN "IMDB"."company_type" ON "movie_companies"."company_type_id" = "company_type"."id"
GROUP BY "movie_companies"."movie_id") AS "t3" ON "t1"."MOVIE_ID" = "t3"."MOVIE_ID"
WHERE "t1"."PRODUCTION_YEAR" >= 2000