SELECT COALESCE(ANY_VALUE("title"), ANY_VALUE("title")) AS "MOVIE_TITLE", ANY_VALUE("name") AS "ACTOR_NAME", ANY_VALUE("role") AS "ACTOR_ROLE", ANY_VALUE("note0") AS "CASTING_NOTE", "PRODUCTION_YEAR", LISTAGG(DISTINCT "keyword", "FD_COL_6") AS "KEYWORDS", COUNT(DISTINCT "company_id") AS "PRODUCTION_COMPANIES", "title"
FROM "s1"
GROUP BY "title", "name", "role", "note0", "PRODUCTION_YEAR"
ORDER BY "PRODUCTION_YEAR" DESC NULLS FIRST, "title"
FETCH NEXT 100 ROWS ONLY