SELECT COALESCE("t4"."MOVIE_ID", "t4"."MOVIE_ID") AS "MOVIE_ID", "t4"."MOVIE_TITLE", "t4"."PRODUCTION_YEAR", "t4"."LEADING_ROLE", "t4"."PRODUCTION_COMPANIES", "t7"."NUM_CAST_MEMBERS", "t4"."MOVIE_KEYWORDS", "t7"."ALL_AKA_NAMES"
FROM (SELECT "t1"."MOVIE_ID", "t1"."MOVIE_TITLE", "t1"."PRODUCTION_YEAR", ANY_VALUE("role_type"."role") AS "LEADING_ROLE", COUNT("movie_companies"."company_id") AS "PRODUCTION_COMPANIES", LISTAGG(DISTINCT "keyword"."keyword", ', ') AS "MOVIE_KEYWORDS"
FROM (SELECT ANY_VALUE("aka_title"."id") AS "MOVIE_ID", ANY_VALUE("aka_title"."title") AS "MOVIE_TITLE", "aka_title"."production_year" AS "PRODUCTION_YEAR", "aka_title"."kind_id" AS "KIND_ID", COUNT("cast_info"."person_id") AS "NUM_CAST_MEMBERS", LISTAGG(DISTINCT "aka_name"."name", ', ') AS "ALL_AKA_NAMES"
FROM "IMDB"."aka_title"
LEFT JOIN "IMDB"."cast_info" ON "aka_title"."movie_id" = "cast_info"."movie_id"
LEFT JOIN "IMDB"."aka_name" ON "cast_info"."person_id" = "aka_name"."person_id"
GROUP BY "aka_title"."id", "aka_title"."title", "aka_title"."production_year", "aka_title"."kind_id") AS "t1"
LEFT JOIN "IMDB"."complete_cast" ON "t1"."MOVIE_ID" = "complete_cast"."movie_id"
LEFT JOIN "IMDB"."role_type" ON "complete_cast"."status_id" = "role_type"."id"
LEFT JOIN "IMDB"."movie_companies" ON "t1"."MOVIE_ID" = "movie_companies"."movie_id"
LEFT JOIN "IMDB"."movie_keyword" ON "t1"."MOVIE_ID" = "movie_keyword"."movie_id"
LEFT JOIN "IMDB"."keyword" ON "movie_keyword"."keyword_id" = "keyword"."id"
GROUP BY "t1"."MOVIE_ID", "t1"."MOVIE_TITLE", "t1"."PRODUCTION_YEAR", "role_type"."role") AS "t4"
INNER JOIN (SELECT ANY_VALUE("aka_title0"."id") AS "MOVIE_ID", ANY_VALUE("aka_title0"."title") AS "MOVIE_TITLE", "aka_title0"."production_year" AS "PRODUCTION_YEAR", "aka_title0"."kind_id" AS "KIND_ID", COUNT("cast_info0"."person_id") AS "NUM_CAST_MEMBERS", LISTAGG(DISTINCT "aka_name0"."name", ', ') AS "ALL_AKA_NAMES"
FROM "IMDB"."aka_title" AS "aka_title0"
LEFT JOIN "IMDB"."cast_info" AS "cast_info0" ON "aka_title0"."movie_id" = "cast_info0"."movie_id"
LEFT JOIN "IMDB"."aka_name" AS "aka_name0" ON "cast_info0"."person_id" = "aka_name0"."person_id"
GROUP BY "aka_title0"."id", "aka_title0"."title", "aka_title0"."production_year", "aka_title0"."kind_id") AS "t7" ON "t4"."MOVIE_ID" = "t7"."MOVIE_ID"