SELECT COALESCE("t4"."MOVIE_ID", "t4"."MOVIE_ID") AS "MOVIE_ID", "t4"."MOVIE_TITLE", "t4"."PRODUCTION_YEAR", "t4"."CAST_COUNT", "t4"."CAST_NAMES", "t4"."KEYWORDS", LISTAGG(DISTINCT "company_name"."name", ', ') AS "COMPANIES"
FROM (SELECT "t2"."MOVIE_ID", "t2"."MOVIE_TITLE", "t2"."PRODUCTION_YEAR", "t2"."CAST_COUNT", "t2"."CAST_NAMES", LISTAGG(DISTINCT "keyword"."keyword", ', ') AS "KEYWORDS"
FROM (SELECT ANY_VALUE("aka_title"."id") AS "MOVIE_ID", ANY_VALUE("aka_title"."title") AS "MOVIE_TITLE", "aka_title"."production_year" AS "PRODUCTION_YEAR", COUNT(DISTINCT "cast_info"."person_id") AS "CAST_COUNT", LISTAGG(DISTINCT "aka_name"."name", ', ') AS "CAST_NAMES"
FROM "IMDB"."aka_title"
INNER JOIN "IMDB"."cast_info" ON "aka_title"."id" = "cast_info"."movie_id"
INNER JOIN "IMDB"."aka_name" ON "cast_info"."person_id" = "aka_name"."person_id"
WHERE "aka_title"."production_year" >= 2000
GROUP BY "aka_title"."id", "aka_title"."title", "aka_title"."production_year") AS "t2"
LEFT JOIN "IMDB"."movie_keyword" ON "t2"."MOVIE_ID" = "movie_keyword"."movie_id"
LEFT JOIN "IMDB"."keyword" ON "movie_keyword"."keyword_id" = "keyword"."id"
GROUP BY "t2"."MOVIE_ID", "t2"."MOVIE_TITLE", "t2"."PRODUCTION_YEAR", "t2"."CAST_COUNT", "t2"."CAST_NAMES") AS "t4"
LEFT JOIN "IMDB"."movie_companies" ON "t4"."MOVIE_ID" = "movie_companies"."movie_id"
LEFT JOIN "IMDB"."company_name" ON "movie_companies"."company_id" = "company_name"."id"
GROUP BY "t4"."MOVIE_ID", "t4"."MOVIE_TITLE", "t4"."PRODUCTION_YEAR", "t4"."CAST_COUNT", "t4"."CAST_NAMES", "t4"."KEYWORDS"