SELECT COALESCE("t"."MOVIE_ID", "t"."MOVIE_ID") AS "MOVIE_ID", "t"."TITLE", "t"."KEYWORD", "t0"."MOVIE_ID" AS "MOVIE_ID0", "t0"."TITLE" AS "TITLE0", "t0"."ACTOR_NAME", "t0"."ROLE_NAME", "t1"."MOVIE_ID" AS "MOVIE_ID1", "t1"."COMPANY_NAME", "t1"."COMPANY_TYPE"
FROM (SELECT "title"."id" AS "MOVIE_ID", "title"."title" AS "TITLE", "keyword"."keyword" AS "KEYWORD"
FROM "IMDB"."title"
LEFT JOIN "IMDB"."movie_keyword" ON "title"."id" = "movie_keyword"."movie_id"
LEFT JOIN "IMDB"."keyword" ON "movie_keyword"."keyword_id" = "keyword"."id") AS "t"
INNER JOIN (SELECT "title0"."id" AS "MOVIE_ID", "title0"."title" AS "TITLE", "aka_name"."name" AS "ACTOR_NAME", "role_type"."role" AS "ROLE_NAME"
FROM "IMDB"."title" AS "title0"
INNER JOIN "IMDB"."complete_cast" ON "title0"."id" = "complete_cast"."movie_id"
INNER JOIN "IMDB"."cast_info" ON "complete_cast"."subject_id" = "cast_info"."person_id"
INNER JOIN "IMDB"."aka_name" ON "cast_info"."person_id" = "aka_name"."person_id"
INNER JOIN "IMDB"."role_type" ON "cast_info"."role_id" = "role_type"."id") AS "t0" ON "t"."MOVIE_ID" = "t0"."MOVIE_ID"
INNER JOIN (SELECT "movie_companies"."movie_id" AS "MOVIE_ID", "company_name"."name" AS "COMPANY_NAME", "company_type"."kind" AS "COMPANY_TYPE"
FROM "IMDB"."movie_companies"
INNER JOIN "IMDB"."company_name" ON "movie_companies"."company_id" = "company_name"."id"
INNER JOIN "IMDB"."company_type" ON "movie_companies"."company_type_id" = "company_type"."id") AS "t1" ON "t"."MOVIE_ID" = "t1"."MOVIE_ID"