SELECT COALESCE("MOVIE_ID", "MOVIE_ID") AS "MOVIE_ID", "TITLE" AS "MOVIE_TITLE", "KEYWORD" AS "MOVIE_KEYWORD", "ACTOR_NAME" AS "LEAD_ACTOR", "ROLE_NAME" AS "ACTOR_ROLE", "COMPANY_NAME", "COMPANY_TYPE"
FROM "s1"
WHERE "KEYWORD" LIKE '%action%' AND "ROLE_NAME" = 'lead'
ORDER BY "MOVIE_ID"