SELECT COALESCE("MOVIE_ID", "MOVIE_ID") AS "MOVIE_ID", "MOVIE_TITLE", "PRODUCTION_YEAR", "ACTOR_NAME", "ACTOR_IMDB_INDEX", "COMPANY_NAMES", "COMPANY_TYPES", "KEYWORDS"
FROM "s1"
ORDER BY "PRODUCTION_YEAR" DESC NULLS FIRST, "MOVIE_TITLE"
FETCH NEXT 100 ROWS ONLY