SELECT COALESCE("MOVIE_ID", "MOVIE_ID") AS "MOVIE_ID", "TITLE", "PRODUCTION_YEAR", "CAST_COUNT", "CAST_NAMES", "KEYWORDS", "ACTOR_ROLES"
FROM "s1"
ORDER BY "PRODUCTION_YEAR" DESC NULLS FIRST, "CAST_COUNT" DESC NULLS FIRST
FETCH NEXT 50 ROWS ONLY