SELECT COALESCE("t5"."MOVIE_ID", "t5"."MOVIE_ID") AS "MOVIE_ID", "t5"."TITLE", "t5"."PRODUCTION_YEAR", "t5"."CAST_COUNT", "t5"."CAST_NAMES", "t5"."KEYWORDS", CASE WHEN "t7"."ROLE_NAMES" IS NOT NULL THEN CAST("t7"."ROLE_NAMES" AS VARCHAR CHARACTER SET "ISO-8859-1") ELSE 'No Roles' END AS "ACTOR_ROLES"
FROM (SELECT "t2"."MOVIE_ID", "t2"."TITLE", "t2"."PRODUCTION_YEAR", "t2"."CAST_COUNT", "t2"."CAST_NAMES", CASE WHEN LISTAGG(DISTINCT "keyword"."keyword", ', ') IS NOT NULL THEN CAST(LISTAGG(DISTINCT "keyword"."keyword", ', ') AS VARCHAR CHARACTER SET "ISO-8859-1") ELSE 'No Keywords' END AS "KEYWORDS"
FROM (SELECT ANY_VALUE("aka_title"."id") AS "MOVIE_ID", "aka_title"."title" AS "TITLE", "aka_title"."production_year" AS "PRODUCTION_YEAR", COUNT(DISTINCT "cast_info"."person_id") AS "CAST_COUNT", LISTAGG(DISTINCT "aka_name"."name", ', ') AS "CAST_NAMES"
FROM "IMDB"."aka_title"
INNER JOIN "IMDB"."cast_info" ON "aka_title"."id" = "cast_info"."movie_id"
INNER JOIN "IMDB"."aka_name" ON "cast_info"."person_id" = "aka_name"."person_id"
WHERE "aka_title"."production_year" >= 2000
GROUP BY "aka_title"."id", "aka_title"."title", "aka_title"."production_year") AS "t2"
LEFT JOIN "IMDB"."movie_keyword" ON "t2"."MOVIE_ID" = "movie_keyword"."movie_id"
LEFT JOIN "IMDB"."keyword" ON "movie_keyword"."keyword_id" = "keyword"."id"
GROUP BY "t2"."MOVIE_ID", "t2"."TITLE", "t2"."PRODUCTION_YEAR", "t2"."CAST_COUNT", "t2"."CAST_NAMES") AS "t5"
LEFT JOIN (SELECT "cast_info0"."movie_id" AS "MOVIE_ID", LISTAGG(DISTINCT "role_type"."role", ', ') AS "ROLE_NAMES"
FROM "IMDB"."cast_info" AS "cast_info0"
INNER JOIN "IMDB"."role_type" ON "cast_info0"."role_id" = "role_type"."id"
GROUP BY "cast_info0"."movie_id") AS "t7" ON "t5"."MOVIE_ID" = "t7"."MOVIE_ID"