SELECT COALESCE("PRODUCTION_YEAR", "PRODUCTION_YEAR") AS "PRODUCTION_YEAR", "TITLE_COUNT", "AVG_TITLE_LENGTH", ANY_VALUE("kind") AS "COMPANY_TYPE", COUNT(DISTINCT "company_id") AS "COMPANY_COUNT"
FROM "s1"
GROUP BY "PRODUCTION_YEAR", "TITLE_COUNT", "AVG_TITLE_LENGTH", "kind"
ORDER BY "PRODUCTION_YEAR", "AVG_TITLE_LENGTH" DESC NULLS FIRST