SELECT COALESCE("t3"."MOVIE_ID", "t3"."MOVIE_ID") AS "MOVIE_ID", "t3"."TITLE", "t3"."PRODUCTION_YEAR", "t3"."NUM_CAST_MEMBERS", "t3"."CAST_NAMES", "t10"."KEYWORDS"
FROM (SELECT *
FROM (SELECT ANY_VALUE("title"."id") AS "MOVIE_ID", "title"."title" AS "TITLE", "title"."production_year" AS "PRODUCTION_YEAR", COUNT(DISTINCT "cast_info"."person_id") AS "NUM_CAST_MEMBERS", LISTAGG(DISTINCT "aka_name"."name", ', ') AS "CAST_NAMES"
FROM "IMDB"."title"
INNER JOIN "IMDB"."movie_companies" ON "title"."id" = "movie_companies"."movie_id"
INNER JOIN "IMDB"."cast_info" ON "movie_companies"."movie_id" = "cast_info"."movie_id"
INNER JOIN "IMDB"."aka_name" ON "cast_info"."person_id" = "aka_name"."person_id"
GROUP BY "title"."id", "title"."title", "title"."production_year") AS "t1"
WHERE "t1"."PRODUCTION_YEAR" >= 2000 AND "t1"."PRODUCTION_YEAR" <= 2023) AS "t3"
LEFT JOIN (SELECT "t8"."MOVIE_ID", LISTAGG("keyword"."keyword", ', ') AS "KEYWORDS"
FROM "IMDB"."movie_keyword"
INNER JOIN "IMDB"."keyword" ON "movie_keyword"."keyword_id" = "keyword"."id"
INNER JOIN (SELECT *
FROM (SELECT ANY_VALUE("title0"."id") AS "MOVIE_ID", "title0"."title" AS "TITLE", "title0"."production_year" AS "PRODUCTION_YEAR", COUNT(DISTINCT "cast_info0"."person_id") AS "NUM_CAST_MEMBERS", LISTAGG(DISTINCT "aka_name0"."name", ', ') AS "CAST_NAMES"
FROM "IMDB"."title" AS "title0"
INNER JOIN "IMDB"."movie_companies" AS "movie_companies0" ON "title0"."id" = "movie_companies0"."movie_id"
INNER JOIN "IMDB"."cast_info" AS "cast_info0" ON "movie_companies0"."movie_id" = "cast_info0"."movie_id"
INNER JOIN "IMDB"."aka_name" AS "aka_name0" ON "cast_info0"."person_id" = "aka_name0"."person_id"
GROUP BY "title0"."id", "title0"."title", "title0"."production_year") AS "t6"
WHERE "t6"."PRODUCTION_YEAR" >= 2000 AND "t6"."PRODUCTION_YEAR" <= 2023) AS "t8" ON "movie_keyword"."movie_id" = "t8"."MOVIE_ID"
GROUP BY "t8"."MOVIE_ID") AS "t10" ON "t3"."MOVIE_ID" = "t10"."MOVIE_ID"