SELECT COALESCE("aka_title"."id", "aka_title"."id") AS "id", "aka_title"."title" AS "TITLE", "aka_title"."production_year" AS "PRODUCTION_YEAR", "keyword"."keyword", "company_name"."name" AS "name0", "aka_name"."name"
FROM "IMDB"."aka_title"
INNER JOIN "IMDB"."movie_keyword" ON "aka_title"."id" = "movie_keyword"."movie_id"
INNER JOIN "IMDB"."keyword" ON "movie_keyword"."keyword_id" = "keyword"."id"
INNER JOIN "IMDB"."cast_info" ON "aka_title"."id" = "cast_info"."movie_id"
INNER JOIN "IMDB"."aka_name" ON "cast_info"."person_id" = "aka_name"."person_id"
INNER JOIN "IMDB"."movie_companies" ON "aka_title"."id" = "movie_companies"."movie_id"
INNER JOIN "IMDB"."company_name" ON "movie_companies"."company_id" = "company_name"."id"