SELECT COALESCE("MOVIE_ID", "MOVIE_ID") AS "MOVIE_ID", "TITLE", "PRODUCTION_YEAR", "KEYWORDS", "COMPANIES", "ACTORS", "ERA", "ACTOR_COUNT"
FROM (SELECT "MOVIE_ID", "TITLE", "PRODUCTION_YEAR", "KEYWORDS", "COMPANIES", "ACTORS", "ERA", COUNT(DISTINCT "ACTORS") AS "ACTOR_COUNT"
FROM (SELECT ANY_VALUE("id") AS "MOVIE_ID", "TITLE", "PRODUCTION_YEAR", ARRAY_AGG(DISTINCT "keyword") AS "KEYWORDS", ARRAY_AGG(DISTINCT "name0") AS "COMPANIES", ARRAY_AGG(DISTINCT "name") AS "ACTORS", CASE WHEN "PRODUCTION_YEAR" < 2000 THEN 'Classic' WHEN "PRODUCTION_YEAR" >= 2000 AND "PRODUCTION_YEAR" <= 2010 THEN 'Modern ' ELSE 'Recent ' END AS "ERA"
FROM "s1"
GROUP BY "id", "TITLE", "PRODUCTION_YEAR") AS "t2"
WHERE "PRODUCTION_YEAR" >= 2010
GROUP BY "MOVIE_ID", "TITLE", "PRODUCTION_YEAR", "KEYWORDS", "COMPANIES", "ACTORS", "ERA"
ORDER BY "PRODUCTION_YEAR" DESC NULLS FIRST, 8 DESC NULLS FIRST) AS "t5"