SELECT COALESCE("MOVIE_TITLE", "MOVIE_TITLE") AS "MOVIE_TITLE", "PRODUCTION_YEAR", "ACTORS", "COMPANY_TYPES", "KEYWORDS"
FROM (SELECT ANY_VALUE("title") AS "MOVIE_TITLE", "PRODUCTION_YEAR", LISTAGG("name", "FD_COL_4") AS "ACTORS", LISTAGG("kind", "FD_COL_4") AS "COMPANY_TYPES", LISTAGG("keyword", "FD_COL_4") AS "KEYWORDS"
FROM "s1"
GROUP BY "id", "title", "PRODUCTION_YEAR") AS "t2"
WHERE "PRODUCTION_YEAR" >= 2000 AND LOWER("ACTORS") LIKE '%john%'
ORDER BY "PRODUCTION_YEAR" DESC NULLS FIRST