SELECT COALESCE("MOVIE_ID", "MOVIE_ID") AS "MOVIE_ID", "MOVIE_TITLE", "PRODUCTION_YEAR", "COMPANIES", "KEYWORDS", "CAST_NAMES", "ROLES"
FROM "s1"
ORDER BY "PRODUCTION_YEAR" DESC NULLS FIRST, "MOVIE_TITLE"