SELECT COALESCE("TITLE", "TITLE") AS "TITLE", "PRODUCTION_YEAR", "KEYWORDS", "COMPANIES", "ACTOR_NAME", "ROLE", "ROLE_COUNT"
FROM "s1"
ORDER BY "PRODUCTION_YEAR" DESC NULLS FIRST, "ROLE_COUNT" DESC NULLS FIRST