SELECT COALESCE("t1"."TITLE", "t1"."TITLE") AS "TITLE", "t1"."PRODUCTION_YEAR", "t1"."KEYWORDS", "t1"."COMPANIES", "t4"."ACTOR_NAME", "t4"."ROLE", "t4"."ROLE_COUNT"
FROM (SELECT ANY_VALUE("aka_title"."id") AS "TITLE_ID", "aka_title"."title" AS "TITLE", "aka_title"."production_year" AS "PRODUCTION_YEAR", LISTAGG(DISTINCT "keyword"."keyword", ', ') AS "KEYWORDS", LISTAGG(DISTINCT "company_name"."name", ', ') AS "COMPANIES"
FROM "IMDB"."aka_title"
LEFT JOIN "IMDB"."movie_keyword" ON "aka_title"."id" = "movie_keyword"."movie_id"
LEFT JOIN "IMDB"."keyword" ON "movie_keyword"."keyword_id" = "keyword"."id"
LEFT JOIN "IMDB"."movie_companies" ON "aka_title"."id" = "movie_companies"."movie_id"
LEFT JOIN "IMDB"."company_name" ON "movie_companies"."company_id" = "company_name"."id"
GROUP BY "aka_title"."id", "aka_title"."title", "aka_title"."production_year") AS "t1"
LEFT JOIN (SELECT "cast_info"."movie_id" AS "MOVIE_ID", ANY_VALUE("aka_name"."name") AS "ACTOR_NAME", ANY_VALUE("role_type"."role") AS "ROLE", COUNT(*) AS "ROLE_COUNT"
FROM "IMDB"."cast_info"
INNER JOIN "IMDB"."aka_name" ON "cast_info"."person_id" = "aka_name"."person_id"
INNER JOIN "IMDB"."role_type" ON "cast_info"."role_id" = "role_type"."id"
GROUP BY "cast_info"."movie_id", "aka_name"."name", "role_type"."role") AS "t4" ON "t1"."TITLE_ID" = "t4"."MOVIE_ID"
WHERE "t1"."PRODUCTION_YEAR" >= 2000 AND "t1"."PRODUCTION_YEAR" <= 2023