SELECT COALESCE("t2"."ACTOR_NAME", "t2"."ACTOR_NAME") AS "ACTOR_NAME", "t7"."MOVIE_COUNT", "t2"."KEYWORDS", "t2"."COMPANY_TYPES"
FROM (SELECT ANY_VALUE("aka_title"."title") AS "MOVIE_TITLE", "aka_title"."production_year" AS "PRODUCTION_YEAR", ANY_VALUE("aka_name"."name") AS "ACTOR_NAME", ANY_VALUE("aka_name"."id") AS "ACTOR_ID", LISTAGG(DISTINCT "keyword"."keyword", ', ') AS "KEYWORDS", LISTAGG(DISTINCT "company_type"."kind", ', ') AS "COMPANY_TYPES"
FROM "IMDB"."aka_title"
INNER JOIN "IMDB"."cast_info" ON "aka_title"."id" = "cast_info"."movie_id"
INNER JOIN "IMDB"."aka_name" ON "cast_info"."person_id" = "aka_name"."person_id"
LEFT JOIN "IMDB"."movie_keyword" ON "aka_title"."id" = "movie_keyword"."movie_id"
LEFT JOIN "IMDB"."keyword" ON "movie_keyword"."keyword_id" = "keyword"."id"
LEFT JOIN "IMDB"."movie_companies" ON "aka_title"."id" = "movie_companies"."movie_id"
LEFT JOIN "IMDB"."company_type" ON "movie_companies"."company_type_id" = "company_type"."id"
WHERE "aka_title"."production_year" >= 2000
GROUP BY "aka_title"."title", "aka_title"."production_year", "aka_name"."name", "aka_name"."id") AS "t2"
INNER JOIN (SELECT "t6"."ACTOR_ID", COUNT(*) AS "MOVIE_COUNT"
FROM (SELECT ANY_VALUE("aka_name0"."id") AS "ACTOR_ID"
FROM "IMDB"."aka_title" AS "aka_title0"
INNER JOIN "IMDB"."cast_info" AS "cast_info0" ON "aka_title0"."id" = "cast_info0"."movie_id"
INNER JOIN "IMDB"."aka_name" AS "aka_name0" ON "cast_info0"."person_id" = "aka_name0"."person_id"
LEFT JOIN "IMDB"."movie_keyword" AS "movie_keyword0" ON "aka_title0"."id" = "movie_keyword0"."movie_id"
LEFT JOIN "IMDB"."keyword" AS "keyword0" ON "movie_keyword0"."keyword_id" = "keyword0"."id"
LEFT JOIN "IMDB"."movie_companies" AS "movie_companies0" ON "aka_title0"."id" = "movie_companies0"."movie_id"
LEFT JOIN "IMDB"."company_type" AS "company_type0" ON "movie_companies0"."company_type_id" = "company_type0"."id"
WHERE "aka_title0"."production_year" >= 2000
GROUP BY "aka_title0"."title", "aka_title0"."production_year", "aka_name0"."name", "aka_name0"."id") AS "t6"
GROUP BY "t6"."ACTOR_ID") AS "t7" ON "t2"."ACTOR_ID" = "t7"."ACTOR_ID"