SELECT COALESCE("MOVIE_ID", "MOVIE_ID") AS "MOVIE_ID", "TITLE", "PRODUCTION_YEAR", "CAST_COUNT", "CAST_NAMES", "KEYWORDS"
FROM (SELECT "t3"."MOVIE_ID", "t3"."TITLE", "t3"."PRODUCTION_YEAR", "t3"."CAST_COUNT", "t3"."CAST_NAMES", "t5"."KEYWORDS"
FROM (SELECT ANY_VALUE("id") AS "MOVIE_ID", "TITLE", "PRODUCTION_YEAR", COUNT(DISTINCT "person_id") AS "CAST_COUNT", LISTAGG(DISTINCT "name", "FD_COL_5") AS "CAST_NAMES"
FROM "s1"
GROUP BY "id", "TITLE", "PRODUCTION_YEAR") AS "t3"
LEFT JOIN (SELECT "movie_keyword"."movie_id" AS "MOVIE_ID", LISTAGG("keyword"."keyword", ', ') AS "KEYWORDS"
FROM "IMDB"."movie_keyword"
INNER JOIN "IMDB"."keyword" ON "movie_keyword"."keyword_id" = "keyword"."id"
GROUP BY "movie_keyword"."movie_id") AS "t5" ON "t3"."MOVIE_ID" = "t5"."MOVIE_ID") AS "t6"
WHERE "t6"."CAST_COUNT" > 5
ORDER BY "PRODUCTION_YEAR" DESC NULLS FIRST, "CAST_COUNT" DESC NULLS FIRST
FETCH NEXT 100 ROWS ONLY