SELECT COALESCE("t5"."MOVIE_ID", "t5"."MOVIE_ID") AS "MOVIE_ID", "t5"."TITLE", "t5"."PRODUCTION_YEAR", "t5"."CAST_COUNT", "t5"."KEYWORDS", "complete_cast0"."id", "complete_cast0"."movie_id" AS "movie_id_", "complete_cast0"."subject_id", "complete_cast0"."status_id"
FROM (SELECT "t1"."MOVIE_ID", "t1"."TITLE", "t1"."PRODUCTION_YEAR", "t1"."CAST_COUNT", CASE WHEN "t3"."KEYWORDS" IS NOT NULL THEN CAST("t3"."KEYWORDS" AS VARCHAR CHARACTER SET "ISO-8859-1") ELSE 'No Keywords' END AS "KEYWORDS"
FROM (SELECT ANY_VALUE("title"."id") AS "MOVIE_ID", "title"."title" AS "TITLE", "title"."production_year" AS "PRODUCTION_YEAR", COUNT(DISTINCT "cast_info"."person_id") AS "CAST_COUNT"
FROM "IMDB"."title"
INNER JOIN "IMDB"."complete_cast" ON "title"."id" = "complete_cast"."movie_id"
INNER JOIN "IMDB"."cast_info" ON "complete_cast"."subject_id" = "cast_info"."id"
GROUP BY "title"."id", "title"."title", "title"."production_year") AS "t1"
LEFT JOIN (SELECT "movie_keyword"."movie_id" AS "MOVIE_ID", LISTAGG("keyword"."keyword", ', ') AS "KEYWORDS"
FROM "IMDB"."movie_keyword"
INNER JOIN "IMDB"."keyword" ON "movie_keyword"."keyword_id" = "keyword"."id"
GROUP BY "movie_keyword"."movie_id") AS "t3" ON "t1"."MOVIE_ID" = "t3"."MOVIE_ID"
ORDER BY "t1"."CAST_COUNT" DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY) AS "t5"
INNER JOIN "IMDB"."complete_cast" AS "complete_cast0" ON "t5"."MOVIE_ID" = "complete_cast0"."movie_id"