SELECT COALESCE("t3"."ACTOR_ID", "t3"."ACTOR_ID") AS "ACTOR_ID", "t3"."ACTOR_NAME", "t6"."MOVIE_TITLE", "t6"."YEAR", "t6"."ROLE_COUNT", "t3"."TOTAL_ROLES"
FROM (SELECT "t1"."ACTOR_ID", "t1"."ACTOR_NAME", SUM("t1"."ROLE_COUNT") AS "TOTAL_ROLES"
FROM (SELECT ANY_VALUE("aka_name"."id") AS "ACTOR_ID", ANY_VALUE("aka_name"."name") AS "ACTOR_NAME", COUNT(*) AS "ROLE_COUNT"
FROM "IMDB"."aka_name"
INNER JOIN "IMDB"."cast_info" ON "aka_name"."person_id" = "cast_info"."person_id"
INNER JOIN "IMDB"."aka_title" ON "cast_info"."movie_id" = "aka_title"."movie_id"
GROUP BY "aka_name"."id", "aka_name"."name", "aka_title"."title", "aka_title"."production_year") AS "t1"
GROUP BY "t1"."ACTOR_ID", "t1"."ACTOR_NAME"
ORDER BY 3 DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY) AS "t3"
INNER JOIN (SELECT ANY_VALUE("aka_name0"."id") AS "ACTOR_ID", ANY_VALUE("aka_name0"."name") AS "ACTOR_NAME", ANY_VALUE("aka_title0"."title") AS "MOVIE_TITLE", ANY_VALUE("aka_title0"."production_year") AS "YEAR", COUNT(*) AS "ROLE_COUNT"
FROM "IMDB"."aka_name" AS "aka_name0"
INNER JOIN "IMDB"."cast_info" AS "cast_info0" ON "aka_name0"."person_id" = "cast_info0"."person_id"
INNER JOIN "IMDB"."aka_title" AS "aka_title0" ON "cast_info0"."movie_id" = "aka_title0"."movie_id"
GROUP BY "aka_name0"."id", "aka_name0"."name", "aka_title0"."title", "aka_title0"."production_year") AS "t6" ON "t3"."ACTOR_ID" = "t6"."ACTOR_ID"