SELECT COALESCE("MOVIE_ID", "MOVIE_ID") AS "MOVIE_ID", "MOVIE_TITLE", "PRODUCTION_YEAR", "ALIASES", "KEYWORDS", "COMPANIES", "CAST_INFO"
FROM "s1"
ORDER BY "PRODUCTION_YEAR" DESC NULLS FIRST, "MOVIE_TITLE"