SELECT COALESCE("ACTOR_NAME", "ACTOR_NAME") AS "ACTOR_NAME", "MOVIE_COUNT", "MOVIE_TITLE", "PRODUCTION_YEAR", "ROLES"
FROM "s1"
ORDER BY "MOVIE_COUNT" DESC NULLS FIRST, "PRODUCTION_YEAR" DESC NULLS FIRST