SELECT COALESCE("t4"."ACTOR_NAME", "t4"."ACTOR_NAME") AS "ACTOR_NAME", "t4"."MOVIE_COUNT", "t7"."MOVIE_TITLE", "t7"."PRODUCTION_YEAR", "t7"."ROLES"
FROM (SELECT "t1"."ACTOR_NAME", COUNT(*) AS "MOVIE_COUNT"
FROM (SELECT ANY_VALUE("aka_name"."name") AS "ACTOR_NAME"
FROM "IMDB"."aka_name"
INNER JOIN "IMDB"."cast_info" ON "aka_name"."person_id" = "cast_info"."person_id"
INNER JOIN "IMDB"."aka_title" ON "cast_info"."movie_id" = "aka_title"."movie_id"
INNER JOIN "IMDB"."role_type" ON "cast_info"."role_id" = "role_type"."id"
GROUP BY "aka_name"."name", "aka_title"."title", "aka_title"."production_year") AS "t1"
GROUP BY "t1"."ACTOR_NAME"
ORDER BY 2 DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY) AS "t4"
INNER JOIN (SELECT ANY_VALUE("aka_name0"."name") AS "ACTOR_NAME", ANY_VALUE("aka_title0"."title") AS "MOVIE_TITLE", "aka_title0"."production_year" AS "PRODUCTION_YEAR", LISTAGG(DISTINCT "role_type0"."role", ', ') AS "ROLES"
FROM "IMDB"."aka_name" AS "aka_name0"
INNER JOIN "IMDB"."cast_info" AS "cast_info0" ON "aka_name0"."person_id" = "cast_info0"."person_id"
INNER JOIN "IMDB"."aka_title" AS "aka_title0" ON "cast_info0"."movie_id" = "aka_title0"."movie_id"
INNER JOIN "IMDB"."role_type" AS "role_type0" ON "cast_info0"."role_id" = "role_type0"."id"
GROUP BY "aka_name0"."name", "aka_title0"."title", "aka_title0"."production_year") AS "t7" ON "t4"."ACTOR_NAME" = "t7"."ACTOR_NAME"