SELECT COALESCE("t5"."ACTOR_NAME", "t5"."ACTOR_NAME") AS "ACTOR_NAME", "t5"."AVG_CO_STARS_OVER_ALL_MOVIES", "t9"."MOVIE_TITLE", ', ' AS "FD_COL_3"
FROM (SELECT "ACTOR_NAME", AVG("AVG_CO_STARS") AS "AVG_CO_STARS_OVER_ALL_MOVIES"
FROM (SELECT "t1"."ACTOR_NAME", AVG("t1"."CO_STARS_COUNT") AS "AVG_CO_STARS"
FROM (SELECT ANY_VALUE("aka_name"."name") AS "ACTOR_NAME", ANY_VALUE("title"."title") AS "MOVIE_TITLE", ANY_VALUE("title"."production_year") AS "MOVIE_YEAR", COUNT(DISTINCT "cast_info"."id") AS "CO_STARS_COUNT"
FROM "IMDB"."aka_name"
INNER JOIN "IMDB"."cast_info" ON "aka_name"."person_id" = "cast_info"."person_id"
INNER JOIN "IMDB"."title" ON "cast_info"."movie_id" = "title"."id"
GROUP BY "aka_name"."name", "aka_name"."person_id", "title"."title", "title"."production_year") AS "t1"
GROUP BY "t1"."ACTOR_NAME", "t1"."MOVIE_TITLE", "t1"."MOVIE_YEAR") AS "t3"
GROUP BY "ACTOR_NAME"
ORDER BY 2 DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY) AS "t5"
INNER JOIN (SELECT "t8"."ACTOR_NAME", "t8"."MOVIE_TITLE", "t8"."MOVIE_YEAR", AVG("t8"."CO_STARS_COUNT") AS "AVG_CO_STARS", COUNT(*) AS "MOVIE_COUNT"
FROM (SELECT ANY_VALUE("aka_name0"."name") AS "ACTOR_NAME", ANY_VALUE("title0"."title") AS "MOVIE_TITLE", ANY_VALUE("title0"."production_year") AS "MOVIE_YEAR", COUNT(DISTINCT "cast_info0"."id") AS "CO_STARS_COUNT"
FROM "IMDB"."aka_name" AS "aka_name0"
INNER JOIN "IMDB"."cast_info" AS "cast_info0" ON "aka_name0"."person_id" = "cast_info0"."person_id"
INNER JOIN "IMDB"."title" AS "title0" ON "cast_info0"."movie_id" = "title0"."id"
GROUP BY "aka_name0"."name", "aka_name0"."person_id", "title0"."title", "title0"."production_year") AS "t8"
GROUP BY "t8"."ACTOR_NAME", "t8"."MOVIE_TITLE", "t8"."MOVIE_YEAR") AS "t9" ON "t5"."ACTOR_NAME" = "t9"."ACTOR_NAME"