SELECT COALESCE("ACTOR_NAME", "ACTOR_NAME") AS "ACTOR_NAME", "MOVIE_TITLE", "PRODUCTION_YEAR", "ROLE_NAME", "KEYWORDS", "TOTAL_COACTORS", "production_year_"
FROM "s1"
ORDER BY "TOTAL_COACTORS" DESC NULLS FIRST, "production_year_" DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY