SELECT COALESCE("t0"."MOVIE_TITLE", "t0"."MOVIE_TITLE") AS "MOVIE_TITLE", "t0"."PRODUCTION_YEAR", "t0"."MOVIE_KEYWORD", "t2"."ACTOR_NAME", "t2"."ROLE_NAME", "t2"."CAST_TYPE", "t4"."COMPANY_NAME", "t4"."COMPANY_TYPE"
FROM (SELECT "title"."id" AS "MOVIE_ID", "title"."title" AS "MOVIE_TITLE", "title"."production_year" AS "PRODUCTION_YEAR", "keyword"."keyword" AS "MOVIE_KEYWORD", "kind_type"."kind" AS "TITLE_KIND"
FROM "IMDB"."title"
LEFT JOIN "IMDB"."kind_type" ON "title"."kind_id" = "kind_type"."id"
LEFT JOIN "IMDB"."movie_keyword" ON "title"."id" = "movie_keyword"."movie_id"
LEFT JOIN "IMDB"."keyword" ON "movie_keyword"."keyword_id" = "keyword"."id"
WHERE "title"."production_year" >= 2000 AND "title"."production_year" <= 2020) AS "t0"
INNER JOIN (SELECT "cast_info"."movie_id" AS "MOVIE_ID", "aka_name"."name" AS "ACTOR_NAME", "role_type"."role" AS "ROLE_NAME", "comp_cast_type"."kind" AS "CAST_TYPE"
FROM "IMDB"."cast_info"
INNER JOIN "IMDB"."aka_name" ON "cast_info"."person_id" = "aka_name"."person_id"
INNER JOIN "IMDB"."role_type" ON "cast_info"."role_id" = "role_type"."id"
INNER JOIN "IMDB"."comp_cast_type" ON "cast_info"."person_role_id" = "comp_cast_type"."id"
WHERE "role_type"."role" LIKE '%Actor%') AS "t2" ON "t0"."MOVIE_ID" = "t2"."MOVIE_ID"
INNER JOIN (SELECT "movie_companies"."movie_id" AS "MOVIE_ID", "company_name"."name" AS "COMPANY_NAME", "company_type"."kind" AS "COMPANY_TYPE"
FROM "IMDB"."movie_companies"
INNER JOIN "IMDB"."company_name" ON "movie_companies"."company_id" = "company_name"."id"
INNER JOIN "IMDB"."company_type" ON "movie_companies"."company_type_id" = "company_type"."id"
WHERE "company_type"."kind" LIKE '%Production%') AS "t4" ON "t0"."MOVIE_ID" = "t4"."MOVIE_ID"
WHERE "t0"."MOVIE_KEYWORD" IS NOT NULL OR "t2"."ACTOR_NAME" IS NOT NULL OR "t4"."COMPANY_NAME" IS NOT NULL