SELECT COALESCE("aka_name0"."name", "aka_name0"."name") AS "ACTOR_NAME", "t4"."AKA_COUNT", "t4"."KEYWORDS", "t4"."LAST_MOVIE_YEAR"
FROM "IMDB"."aka_name" AS "aka_name0"
INNER JOIN (SELECT "PERSON_ID", COUNT(DISTINCT "AKA_ID") AS "AKA_COUNT", LISTAGG(DISTINCT "MOVIE_KEYWORD", "FD_COL_3") AS "KEYWORDS", MAX("PRODUCTION_YEAR") AS "LAST_MOVIE_YEAR"
FROM "s1"
GROUP BY "PERSON_ID") AS "t4" ON "aka_name0"."person_id" = "t4"."PERSON_ID"
WHERE "t4"."AKA_COUNT" > 1
ORDER BY "t4"."LAST_MOVIE_YEAR" DESC NULLS FIRST