SELECT COALESCE("t2"."MOVIE_TITLE", "t2"."MOVIE_TITLE") AS "MOVIE_TITLE", "t2"."PRODUCTION_YEAR", "t2"."ACTOR_COUNT", "t2"."CAST_NAMES", "t2"."KEYWORDS", "t5"."COMPANIES", "t5"."COMPANY_TYPES"
FROM (SELECT ANY_VALUE("aka_title"."title") AS "MOVIE_TITLE", "aka_title"."production_year" AS "PRODUCTION_YEAR", COUNT(DISTINCT "cast_info"."person_id") AS "ACTOR_COUNT", LISTAGG(DISTINCT "aka_name"."name", ', ') AS "CAST_NAMES", LISTAGG(DISTINCT "keyword"."keyword", ', ') AS "KEYWORDS"
FROM "IMDB"."aka_title"
INNER JOIN "IMDB"."movie_keyword" ON "aka_title"."id" = "movie_keyword"."movie_id"
INNER JOIN "IMDB"."keyword" ON "movie_keyword"."keyword_id" = "keyword"."id"
INNER JOIN "IMDB"."complete_cast" ON "aka_title"."id" = "complete_cast"."movie_id"
INNER JOIN "IMDB"."cast_info" ON "complete_cast"."subject_id" = "cast_info"."person_id"
INNER JOIN "IMDB"."aka_name" ON "cast_info"."person_id" = "aka_name"."person_id"
WHERE "aka_title"."production_year" >= 1980 AND "aka_title"."production_year" <= 2020
GROUP BY "aka_title"."title", "aka_title"."production_year") AS "t2"
LEFT JOIN (SELECT ANY_VALUE("aka_title0"."title") AS "MOVIE_TITLE", LISTAGG(DISTINCT "company_name"."name", ', ') AS "COMPANIES", LISTAGG(DISTINCT "company_type"."kind", ', ') AS "COMPANY_TYPES"
FROM "IMDB"."aka_title" AS "aka_title0"
INNER JOIN "IMDB"."movie_companies" ON "aka_title0"."id" = "movie_companies"."movie_id"
INNER JOIN "IMDB"."company_name" ON "movie_companies"."company_id" = "company_name"."id"
INNER JOIN "IMDB"."company_type" ON "movie_companies"."company_type_id" = "company_type"."id"
GROUP BY "aka_title0"."title") AS "t5" ON "t2"."MOVIE_TITLE" = "t5"."MOVIE_TITLE"