SELECT COALESCE("MOVIE_TITLE", "MOVIE_TITLE") AS "MOVIE_TITLE", "PRODUCTION_YEAR", "ACTOR_COUNT", "CAST_NAMES", "KEYWORDS", "COMPANIES", "COMPANY_TYPES"
FROM "s1"
ORDER BY "PRODUCTION_YEAR" DESC NULLS FIRST, "ACTOR_COUNT" DESC NULLS FIRST