SELECT COALESCE("MOVIE_ID", "MOVIE_ID") AS "MOVIE_ID", "MOVIE_TITLE", "PRODUCTION_YEAR", LISTAGG(DISTINCT "MOVIE_KEYWORD", "FD_COL_4") AS "KEYWORDS", LISTAGG(DISTINCT "COMPANY_NAME", "FD_COL_4") AS "COMPANIES", LISTAGG(DISTINCT "FD_COL_6", "FD_COL_4") AS "CAST_DETAILS"
FROM "s1"
GROUP BY "MOVIE_ID", "MOVIE_TITLE", "PRODUCTION_YEAR"
ORDER BY "PRODUCTION_YEAR" DESC NULLS FIRST, "MOVIE_TITLE"