SELECT COALESCE("t2"."MOVIE_ID", "t2"."MOVIE_ID") AS "MOVIE_ID", "t2"."MOVIE_TITLE", "t2"."PRODUCTION_YEAR", "t2"."CAST_COUNT", "t2"."ACTOR_NAMES", CASE WHEN "t4"."KEYWORDS" IS NOT NULL THEN CAST("t4"."KEYWORDS" AS VARCHAR CHARACTER SET "ISO-8859-1") ELSE 'No keywords' END AS "KEYWORDS", CASE WHEN "t6"."COMPANIES" IS NOT NULL THEN CAST("t6"."COMPANIES" AS VARCHAR CHARACTER SET "ISO-8859-1") ELSE 'No companies listed' END AS "COMPANIES"
FROM (SELECT ANY_VALUE("aka_title"."id") AS "MOVIE_ID", ANY_VALUE("aka_title"."title") AS "MOVIE_TITLE", "aka_title"."production_year" AS "PRODUCTION_YEAR", COUNT(*) AS "CAST_COUNT", LISTAGG(DISTINCT "aka_name"."name", ', ') AS "ACTOR_NAMES"
FROM "IMDB"."aka_title"
INNER JOIN "IMDB"."cast_info" ON "aka_title"."id" = "cast_info"."movie_id"
INNER JOIN "IMDB"."aka_name" ON "cast_info"."person_id" = "aka_name"."person_id"
GROUP BY "aka_title"."id", "aka_title"."title", "aka_title"."production_year"
HAVING COUNT(*) > 5) AS "t2"
LEFT JOIN (SELECT "movie_keyword"."movie_id" AS "MOVIE_ID", LISTAGG(DISTINCT "keyword"."keyword", ', ') AS "KEYWORDS"
FROM "IMDB"."movie_keyword"
INNER JOIN "IMDB"."keyword" ON "movie_keyword"."keyword_id" = "keyword"."id"
GROUP BY "movie_keyword"."movie_id") AS "t4" ON "t2"."MOVIE_ID" = "t4"."MOVIE_ID"
LEFT JOIN (SELECT "movie_companies"."movie_id" AS "MOVIE_ID", LISTAGG(DISTINCT "company_name"."name", ', ') AS "COMPANIES"
FROM "IMDB"."movie_companies"
INNER JOIN "IMDB"."company_name" ON "movie_companies"."company_id" = "company_name"."id"
GROUP BY "movie_companies"."movie_id") AS "t6" ON "t2"."MOVIE_ID" = "t6"."MOVIE_ID"