SELECT COALESCE("TITLE", "TITLE") AS "TITLE", "PRODUCTION_YEAR", LISTAGG(DISTINCT "KEYWORD", "FD_COL_4") AS "KEYWORDS", LISTAGG(DISTINCT "name", "FD_COL_4") AS "COMPANIES"
FROM "s1"
GROUP BY "MOVIE_ID", "TITLE", "PRODUCTION_YEAR"
HAVING "PRODUCTION_YEAR" >= 2000
ORDER BY "PRODUCTION_YEAR" DESC NULLS FIRST