SELECT COALESCE("TITLE_ID", "TITLE_ID") AS "TITLE_ID", "TITLE", "PRODUCTION_YEAR", "INFO_COUNT", "LATEST_INFO", "EARLIEST_INFO", "ACTOR_COUNT", "ROLES"
FROM "s1"
ORDER BY "PRODUCTION_YEAR" DESC NULLS FIRST, "ACTOR_COUNT" DESC NULLS FIRST
FETCH NEXT 50 ROWS ONLY