SELECT COALESCE("t2"."TITLE", "t2"."TITLE") AS "TITLE", "t2"."PRODUCTION_YEAR", "t2"."TOTAL_CAST", "t2"."CAST_NAMES", CASE WHEN "t4"."KEYWORD_COUNT" IS NOT NULL THEN CAST("t4"."KEYWORD_COUNT" AS BIGINT) ELSE 0 END AS "KEYWORD_COUNT", "t4"."BUDGET_INFO"
FROM (SELECT ANY_VALUE("aka_title"."id") AS "MOVIE_ID", "aka_title"."title" AS "TITLE", "aka_title"."production_year" AS "PRODUCTION_YEAR", "aka_title"."kind_id" AS "KIND_ID", COUNT(DISTINCT "cast_info"."person_id") AS "TOTAL_CAST", LISTAGG(DISTINCT "aka_name"."name", ', ') AS "CAST_NAMES"
FROM "IMDB"."aka_title"
LEFT JOIN "IMDB"."complete_cast" ON "aka_title"."id" = "complete_cast"."movie_id"
LEFT JOIN "IMDB"."cast_info" ON "complete_cast"."subject_id" = "cast_info"."id"
LEFT JOIN "IMDB"."aka_name" ON "cast_info"."person_id" = "aka_name"."person_id"
WHERE "aka_title"."production_year" > 2000
GROUP BY "aka_title"."id", "aka_title"."title", "aka_title"."production_year", "aka_title"."kind_id") AS "t2"
LEFT JOIN (SELECT "movie_info"."movie_id" AS "MOVIE_ID", COUNT("movie_keyword"."keyword_id") AS "KEYWORD_COUNT", MAX(CASE WHEN "info_type"."info" = 'Budget' THEN "movie_info"."info" ELSE NULL END) AS "BUDGET_INFO"
FROM "IMDB"."movie_info"
INNER JOIN "IMDB"."info_type" ON "movie_info"."info_type_id" = "info_type"."id"
LEFT JOIN "IMDB"."movie_keyword" ON "movie_info"."movie_id" = "movie_keyword"."movie_id"
GROUP BY "movie_info"."movie_id") AS "t4" ON "t2"."MOVIE_ID" = "t4"."MOVIE_ID"