SELECT COALESCE("TITLE", "TITLE") AS "TITLE", "PRODUCTION_YEAR", "TOTAL_CAST", "CAST_NAMES", "KEYWORD_COUNT", "BUDGET_INFO"
FROM "s1"
ORDER BY "PRODUCTION_YEAR" DESC NULLS FIRST, "TOTAL_CAST" DESC NULLS FIRST
FETCH NEXT 100 ROWS ONLY