SELECT COALESCE("aka_name"."person_id", "aka_name"."person_id") AS "PERSON_ID", ANY_VALUE("aka_name"."name") AS "ACTOR_NAME", ANY_VALUE("title"."title") AS "MOVIE_TITLE", ANY_VALUE("company_type"."kind") AS "COMPANY_TYPE", COUNT(DISTINCT "t2"."ROLE_ID") AS "TOTAL_ROLES", AVG("t0"."INFO_LENGTH") AS "AVG_INFO_LENGTH"
FROM "IMDB"."aka_name"
INNER JOIN "IMDB"."cast_info" ON "aka_name"."person_id" = "cast_info"."person_id"
INNER JOIN "IMDB"."title" ON "cast_info"."movie_id" = "title"."id"
INNER JOIN "IMDB"."movie_companies" ON "title"."id" = "movie_companies"."movie_id"
INNER JOIN "IMDB"."company_type" ON "movie_companies"."company_type_id" = "company_type"."id"
LEFT JOIN (SELECT "movie_id" AS "MOVIE_ID", AVG(LENGTH("info")) AS "INFO_LENGTH"
FROM "IMDB"."movie_info"
GROUP BY "movie_id") AS "t0" ON "title"."id" = "t0"."MOVIE_ID"
INNER JOIN (SELECT "role_id" AS "ROLE_ID", "movie_id" AS "MOVIE_ID"
FROM "IMDB"."cast_info"
GROUP BY "role_id", "movie_id") AS "t2" ON "cast_info"."role_id" = "t2"."ROLE_ID" AND "cast_info"."movie_id" = "t2"."MOVIE_ID"
WHERE "title"."production_year" >= 2000
GROUP BY "aka_name"."person_id", "aka_name"."name", "title"."title", "company_type"."kind", "t0"."INFO_LENGTH"