SELECT COALESCE("PERSON_ID", "PERSON_ID") AS "PERSON_ID", "ACTOR_NAME", "MOVIE_TITLE", "COMPANY_TYPE", "TOTAL_ROLES", "AVG_INFO_LENGTH"
FROM "s1"
ORDER BY "TOTAL_ROLES" DESC NULLS FIRST, "AVG_INFO_LENGTH" DESC NULLS FIRST
FETCH NEXT 100 ROWS ONLY