SELECT COALESCE("ACTOR_NAME", "ACTOR_NAME") AS "ACTOR_NAME", "MOVIE_TITLE", "COMPANY_TYPE", "MOVIE_KEYWORD", "PERSON_INFO", "TOTAL_CASTS", "title"
FROM (SELECT ANY_VALUE("name") AS "ACTOR_NAME", ANY_VALUE("title") AS "MOVIE_TITLE", ANY_VALUE("kind") AS "COMPANY_TYPE", ANY_VALUE("keyword") AS "MOVIE_KEYWORD", ANY_VALUE("info") AS "PERSON_INFO", COUNT(DISTINCT "person_id0") AS "TOTAL_CASTS", "title"
FROM "s1"
WHERE "production_year" > 2000 AND "kind" LIKE '%production%'
GROUP BY "name", "title", "kind", "keyword", "info"
ORDER BY 6 DESC NULLS FIRST, "title"
FETCH NEXT 50 ROWS ONLY) AS "t4"