SELECT COALESCE("t2"."MOVIE_ID", "t2"."MOVIE_ID") AS "MOVIE_ID", "t2"."TITLE", "t2"."PRODUCTION_YEAR", "t2"."ACTOR_COUNT" AS "ACTOR_COUNT_SAFE", CASE WHEN "t4"."KEYWORD_COUNT" IS NULL THEN 0 ELSE "t4"."KEYWORD_COUNT" END AS "KEYWORD_COUNT_SAFE", CASE WHEN CASE WHEN "t4"."KEYWORD_COUNT" IS NULL THEN 0 ELSE "t4"."KEYWORD_COUNT" END IS NOT NULL THEN CAST("t2"."ACTOR_COUNT" - CASE WHEN "t4"."KEYWORD_COUNT" IS NULL THEN 0 ELSE "t4"."KEYWORD_COUNT" END AS BIGINT) ELSE 0 END AS "ACTOR_KEYWORD_DIFF"
FROM (SELECT ANY_VALUE("aka_title"."id") AS "MOVIE_ID", "aka_title"."title" AS "TITLE", "aka_title"."production_year" AS "PRODUCTION_YEAR", COUNT(DISTINCT "cast_info"."person_id") AS "ACTOR_COUNT", LISTAGG(DISTINCT "aka_name"."name", ', ') AS "ACTOR_NAMES"
FROM "IMDB"."aka_title"
LEFT JOIN "IMDB"."complete_cast" ON "aka_title"."id" = "complete_cast"."movie_id"
LEFT JOIN "IMDB"."cast_info" ON "complete_cast"."subject_id" = "cast_info"."id"
LEFT JOIN "IMDB"."aka_name" ON "cast_info"."person_id" = "aka_name"."person_id"
WHERE "aka_title"."production_year" >= 2000
GROUP BY "aka_title"."id", "aka_title"."title", "aka_title"."production_year") AS "t2"
LEFT JOIN (SELECT "movie_id" AS "MOVIE_ID", COUNT(*) AS "KEYWORD_COUNT"
FROM "IMDB"."movie_keyword"
GROUP BY "movie_id") AS "t4" ON "t2"."MOVIE_ID" = "t4"."MOVIE_ID"