SELECT COALESCE("MOVIE_ID", "MOVIE_ID") AS "MOVIE_ID", "TITLE", "PRODUCTION_YEAR", "ACTOR_COUNT_SAFE", "KEYWORD_COUNT_SAFE", "ACTOR_KEYWORD_DIFF"
FROM "s1"
ORDER BY "PRODUCTION_YEAR" DESC NULLS FIRST, "ACTOR_COUNT_SAFE" DESC NULLS FIRST