SELECT COALESCE("ACTOR_NAME", "ACTOR_NAME") AS "ACTOR_NAME", "MOVIE_TITLE", "COMPANY_TYPE", "TOTAL_CAST", "AVG_MOVIE_RATING"
FROM "s1"
ORDER BY "AVG_MOVIE_RATING" DESC NULLS FIRST, "TOTAL_CAST" DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY