SELECT COALESCE("ACTOR_NAME", "ACTOR_NAME") AS "ACTOR_NAME", "MOVIE_TITLE", "CAST_TYPE", "ADDITIONAL_INFO", "MOVIE_KEYWORD", "production_year"
FROM "s1"
ORDER BY "ACTOR_NAME", "production_year" DESC NULLS FIRST