SELECT COALESCE("MOVIE_TITLE", "MOVIE_TITLE") AS "MOVIE_TITLE", "PRODUCTION_YEAR", "NUM_ACTORS", "NUM_KEYWORDS", "COMPANIES"
FROM (SELECT ANY_VALUE("title") AS "MOVIE_TITLE", "PRODUCTION_YEAR", COUNT(DISTINCT "person_id") AS "NUM_ACTORS", COUNT(DISTINCT "keyword") AS "NUM_KEYWORDS", LISTAGG(DISTINCT "name", "FD_COL_6") AS "COMPANIES"
FROM "s1"
GROUP BY "id", "title", "PRODUCTION_YEAR") AS "t3"
WHERE "NUM_ACTORS" > 5
ORDER BY "PRODUCTION_YEAR" DESC NULLS FIRST, "NUM_ACTORS" DESC NULLS FIRST
FETCH NEXT 10 ROWS ONLY