SELECT COALESCE("MOVIE_TITLE", "MOVIE_TITLE") AS "MOVIE_TITLE", "PRODUCTION_YEAR", COUNT(DISTINCT "ACTOR_NAME") AS "TOTAL_ACTORS", LISTAGG(DISTINCT "MOVIE_KEYWORD", "FD_COL_4") AS "KEYWORDS", LISTAGG(DISTINCT "PERSON_INFO", "FD_COL_4") AS "ADDITIONAL_INFORMATION"
FROM "s1"
GROUP BY "MOVIE_TITLE", "PRODUCTION_YEAR"
HAVING COUNT(DISTINCT "ACTOR_NAME") > 5
ORDER BY "PRODUCTION_YEAR" DESC NULLS FIRST, "MOVIE_TITLE"