SELECT COALESCE("ACTOR_NAME", "ACTOR_NAME") AS "ACTOR_NAME", "MOVIE_TITLE", "COMPANY_TYPE", "KEYWORD_COUNT", "MOVIE_TAGLINE", "MOVIE_SYNOPSIS", "name", "title"
FROM "s1"
ORDER BY "KEYWORD_COUNT" DESC NULLS FIRST, "name", "title"
FETCH NEXT 50 ROWS ONLY