SELECT COALESCE("ACTOR_NAME", "ACTOR_NAME") AS "ACTOR_NAME", "MOVIE_TITLE", "ROLE", "CASTING_TYPE", "COMPANY_NAME", "MOVIE_KEYWORD", "MOVIE_INFO", "ACTOR_COUNT", "production_year"
FROM "s1"
ORDER BY "ACTOR_COUNT" DESC NULLS FIRST, "production_year" DESC NULLS FIRST