SELECT COALESCE("ACTOR_NAME", "ACTOR_NAME") AS "ACTOR_NAME", "MOVIE_TITLE", "CAST_TYPE", "COMPANY_NAME", "MOVIE_INFO", "MOVIE_KEYWORD", "production_year"
FROM "s1"
ORDER BY "production_year" DESC NULLS FIRST, "ACTOR_NAME"