SELECT COALESCE("AKA_NAME", "AKA_NAME") AS "AKA_NAME", "TITLE_NAME", "PRODUCTION_YEAR", "ROLE_COUNT"
FROM (SELECT "AKA_NAME", "TITLE_NAME", "PRODUCTION_YEAR", COUNT(*) AS "ROLE_COUNT"
FROM "s1"
GROUP BY "AKA_ID", "AKA_NAME", "TITLE_NAME", "PRODUCTION_YEAR"
HAVING COUNT(*) > 2
ORDER BY "PRODUCTION_YEAR" DESC NULLS FIRST, 4 DESC NULLS FIRST) AS "t5"