SELECT COALESCE("ACTOR_NAME", "ACTOR_NAME") AS "ACTOR_NAME", "MOVIE_TITLE", "COMPANY_TYPE", "MOVIE_KEYWORD", "MOVIE_INFO", "production_year"
FROM "s1"
ORDER BY "production_year" DESC NULLS FIRST, "ACTOR_NAME"
FETCH NEXT 50 ROWS ONLY