SELECT COALESCE("ACTOR_NAME", "ACTOR_NAME") AS "ACTOR_NAME", "MOVIE_TITLE", "PRODUCTION_YEAR", "CAST_TYPE", "MOVIE_KEYWORD", "CHARACTER_NOTE"
FROM "s1"
ORDER BY "PRODUCTION_YEAR" DESC NULLS FIRST, "ACTOR_NAME"
FETCH NEXT 100 ROWS ONLY