SELECT COALESCE("t1"."MOVIE_ID", "t1"."MOVIE_ID") AS "MOVIE_ID", "t1"."MOVIE_TITLE", "t1"."ACTOR_NAME", "t1"."ACTOR_ROLE", "t1"."TOTAL_APPEARANCES", "t4"."COMPANY_NAME", "t4"."COMPANY_TYPE", "t4"."TOTAL_MOVIES"
FROM (SELECT ANY_VALUE("title"."id") AS "MOVIE_ID", ANY_VALUE("title"."title") AS "MOVIE_TITLE", ANY_VALUE("aka_name"."name") AS "ACTOR_NAME", ANY_VALUE("role_type"."role") AS "ACTOR_ROLE", COUNT(*) AS "TOTAL_APPEARANCES"
FROM "IMDB"."title"
INNER JOIN "IMDB"."cast_info" ON "title"."id" = "cast_info"."movie_id"
INNER JOIN "IMDB"."aka_name" ON "cast_info"."person_id" = "aka_name"."person_id"
INNER JOIN "IMDB"."role_type" ON "cast_info"."role_id" = "role_type"."id"
GROUP BY "title"."id", "title"."title", "aka_name"."name", "role_type"."role") AS "t1"
LEFT JOIN "IMDB"."complete_cast" ON "t1"."MOVIE_ID" = "complete_cast"."movie_id"
LEFT JOIN (SELECT "movie_companies"."movie_id" AS "MOVIE_ID", ANY_VALUE("company_name"."name") AS "COMPANY_NAME", ANY_VALUE("company_type"."kind") AS "COMPANY_TYPE", COUNT(*) AS "TOTAL_MOVIES"
FROM "IMDB"."movie_companies"
INNER JOIN "IMDB"."company_name" ON "movie_companies"."company_id" = "company_name"."id"
INNER JOIN "IMDB"."company_type" ON "movie_companies"."company_type_id" = "company_type"."id"
GROUP BY "movie_companies"."movie_id", "company_name"."name", "company_type"."kind") AS "t4" ON "t1"."MOVIE_ID" = "t4"."MOVIE_ID"
WHERE "t1"."TOTAL_APPEARANCES" > 1 AND "t4"."TOTAL_MOVIES" > 5