SELECT COALESCE("MOVIE_ID", "MOVIE_ID") AS "MOVIE_ID", "MOVIE_TITLE", "ACTOR_NAME", "ACTOR_ROLE", "TOTAL_APPEARANCES", "COMPANY_NAME", "COMPANY_TYPE", "TOTAL_MOVIES"
FROM "s1"
ORDER BY "TOTAL_APPEARANCES" DESC NULLS FIRST, "TOTAL_MOVIES" DESC NULLS FIRST
FETCH NEXT 100 ROWS ONLY