SELECT COALESCE("t0"."MOVIE_ID", "t0"."MOVIE_ID") AS "MOVIE_ID", "t0"."TITLE", "t0"."PRODUCTION_YEAR", "t3"."NUM_COMPANIES", "t3"."NUM_KEYWORDS", "t3"."NUM_ACTORS"
FROM (SELECT "aka_title"."id" AS "MOVIE_ID", "aka_title"."title" AS "TITLE", "aka_title"."production_year" AS "PRODUCTION_YEAR", "company_name"."name" AS "COMPANY_NAME", "keyword"."keyword" AS "MOVIE_KEYWORD", "aka_name"."name" AS "ACTOR_NAME"
FROM "IMDB"."aka_title"
INNER JOIN "IMDB"."movie_companies" ON "aka_title"."id" = "movie_companies"."movie_id"
INNER JOIN "IMDB"."company_name" ON "movie_companies"."company_id" = "company_name"."id"
INNER JOIN "IMDB"."movie_keyword" ON "aka_title"."id" = "movie_keyword"."movie_id"
INNER JOIN "IMDB"."keyword" ON "movie_keyword"."keyword_id" = "keyword"."id"
INNER JOIN "IMDB"."cast_info" ON "aka_title"."id" = "cast_info"."movie_id"
INNER JOIN "IMDB"."aka_name" ON "cast_info"."person_id" = "aka_name"."person_id"
WHERE "aka_title"."production_year" >= 2000 AND "company_name"."country_code" = 'USA') AS "t0"
INNER JOIN (SELECT "aka_title0"."id" AS "MOVIE_ID", COUNT(DISTINCT "company_name0"."name") AS "NUM_COMPANIES", COUNT(DISTINCT "keyword0"."keyword") AS "NUM_KEYWORDS", COUNT(DISTINCT "aka_name0"."name") AS "NUM_ACTORS"
FROM "IMDB"."aka_title" AS "aka_title0"
INNER JOIN "IMDB"."movie_companies" AS "movie_companies0" ON "aka_title0"."id" = "movie_companies0"."movie_id"
INNER JOIN "IMDB"."company_name" AS "company_name0" ON "movie_companies0"."company_id" = "company_name0"."id"
INNER JOIN "IMDB"."movie_keyword" AS "movie_keyword0" ON "aka_title0"."id" = "movie_keyword0"."movie_id"
INNER JOIN "IMDB"."keyword" AS "keyword0" ON "movie_keyword0"."keyword_id" = "keyword0"."id"
INNER JOIN "IMDB"."cast_info" AS "cast_info0" ON "aka_title0"."id" = "cast_info0"."movie_id"
INNER JOIN "IMDB"."aka_name" AS "aka_name0" ON "cast_info0"."person_id" = "aka_name0"."person_id"
WHERE "aka_title0"."production_year" >= 2000 AND "company_name0"."country_code" = 'USA'
GROUP BY "aka_title0"."id") AS "t3" ON "t0"."MOVIE_ID" = "t3"."MOVIE_ID"