SELECT COALESCE("MOVIE_ID", "MOVIE_ID") AS "MOVIE_ID", "TITLE", "PRODUCTION_YEAR", "NUM_COMPANIES", "NUM_KEYWORDS", "NUM_ACTORS"
FROM "s1"
ORDER BY "PRODUCTION_YEAR" DESC NULLS FIRST, "NUM_ACTORS" DESC NULLS FIRST, "NUM_COMPANIES" DESC NULLS FIRST
FETCH NEXT 50 ROWS ONLY