SELECT COALESCE("TITLE", "TITLE") AS "TITLE", "PRODUCTION_YEAR", "CAST_NAMES", "KEYWORDS", "MOVIE_INFO"
FROM "s1"
WHERE "PRODUCTION_YEAR" >= 2000 AND "KEYWORDS" ILIKE '%action%' AND "CAST_NAMES" IS NOT NULL