SELECT COALESCE("title"."id", "title"."id") AS "ID", "title"."title" AS "TITLE", "title"."production_year" AS "PRODUCTION_YEAR", "t0"."CAST_NAMES", "t2"."KEYWORDS", CASE WHEN "movie_info"."info" IS NOT NULL THEN CAST("movie_info"."info" AS VARCHAR CHARACTER SET "ISO-8859-1") ELSE 'No info' END AS "MOVIE_INFO"
FROM "IMDB"."title"
LEFT JOIN (SELECT "cast_info"."movie_id" AS "MOVIE_ID", LISTAGG("aka_name"."name", ', ') AS "CAST_NAMES", COUNT(DISTINCT "cast_info"."person_id") AS "TOTAL_CAST_COUNT"
FROM "IMDB"."cast_info"
INNER JOIN "IMDB"."aka_name" ON "cast_info"."person_id" = "aka_name"."person_id"
GROUP BY "cast_info"."movie_id") AS "t0" ON "title"."id" = "t0"."MOVIE_ID"
LEFT JOIN (SELECT "movie_keyword"."movie_id" AS "MOVIE_ID", LISTAGG("keyword"."keyword", ', ') AS "KEYWORDS"
FROM "IMDB"."movie_keyword"
INNER JOIN "IMDB"."keyword" ON "movie_keyword"."keyword_id" = "keyword"."id"
GROUP BY "movie_keyword"."movie_id") AS "t2" ON "title"."id" = "t2"."MOVIE_ID"
LEFT JOIN "IMDB"."movie_info" ON "title"."id" = "movie_info"."movie_id"