SELECT COALESCE("AKA_ID", "AKA_ID") AS "AKA_ID", "AKA_NAME", "MOVIE_TITLE", "PRODUCTION_YEAR", "NR_ORDER", "CAST_TYPE", "COMPANY_NAME", "MOVIE_KEYWORD"
FROM "s1"
ORDER BY "PRODUCTION_YEAR" DESC NULLS FIRST, "AKA_NAME"