SELECT COALESCE("ACTOR_NAME", "ACTOR_NAME") AS "ACTOR_NAME", "MOVIE_TITLE", "COMPANY_TYPE", "MOVIE_KEYWORD", "PERSON_INFO", "production_year"
FROM "s1"
ORDER BY "ACTOR_NAME", "production_year" DESC NULLS FIRST
FETCH NEXT 100 ROWS ONLY