SELECT COALESCE("MOVIE_TITLE", "MOVIE_TITLE") AS "MOVIE_TITLE", "ACTOR_NAME", "ALIAS_COUNT", "KEYWORDS", "COMPANY_TYPE"
FROM "s1"
ORDER BY "ALIAS_COUNT" DESC NULLS FIRST, "MOVIE_TITLE"
FETCH NEXT 50 ROWS ONLY