SELECT COALESCE("ACTOR_NAME", "ACTOR_NAME") AS "ACTOR_NAME", "MOVIE_TITLE", "COMPANY_TYPE", "COMPANY_NAME", "PRODUCTION_YEAR", "MOVIE_KEYWORD", "ACTOR_COUNT", "production_year_"
FROM "s1"
ORDER BY "ACTOR_COUNT" DESC NULLS FIRST, "production_year_" DESC NULLS FIRST
FETCH NEXT 50 ROWS ONLY