SELECT COALESCE("ACTOR_NAME", "ACTOR_NAME") AS "ACTOR_NAME", "ACTOR_IMDB_INDEX", "MOVIE_TITLE", "MOVIE_YEAR", "ROLE_ID", "COMPANY_TYPE", "COMPANY_NAME", "MOVIE_INFO", "MOVIE_KEYWORD"
FROM "s1"
ORDER BY "MOVIE_YEAR" DESC NULLS FIRST, "ACTOR_NAME"
FETCH NEXT 100 ROWS ONLY